### ISSUE TITLE
Error with associative arrays

### ISSUE THREAD

**Issue by Mattmn** [CraftTweaker/CraftTweaker#1001]
#### Issue Description:
Buggy behavior using associative arrays of type double[double]

#### What happens:
throws an Operand stack underflow error when retrieving values from the associative array.

#### What you expected to happen:
receive a value of type double.

#### Script used:
https://pastebin.com/ues6K9R9

#### crafttweaker.log file:
https://pastebin.com/nVCLvz4K

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Crafttweaker: 2-1.12-4.1.20.564
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://pastebin.com/nVCLvz4K

**Comment by kindlich** [comment]
Put the `as double[double]` on the side of the `{}`
So `var arrDblDbl= {} as double[double];`

**Comment by jaredlll08** [comment]
Can this be closed?

**Comment by Mattmn** [comment]
Yes that fixed it, thanks. It's was just unexpected because placing the type in front of the array worked fine for other types, like `var arrItemString as IItemStack[string] = {};`
