### ISSUE TITLE
Help with fireworks

### ISSUE THREAD

**Issue by Nohicom** [CraftTweaker/CraftTweaker#1003]
Hello! I'm sorry, I didn't know what category this would go into.

Is it possible to use CraftTweaker to replicate vanilla minecraft's firework crafting systems? Let's say I wanted to allow players to craft fireworks with higher durations than the 1-3 duration rockets you can craft by default, but still be able to have actual firework patterns stored in the rockets too, how would I write the recipe for that?

Additionally, or perhaps as the way to do that, is it possible to copy the NBT data from an input item in a recipe to the output item?

**Comment by jaredlll08** [comment]
for fireworks: no

for nbt transfer
https://github.com/CraftTweaker/CraftTweaker-Examples/blob/master/crafttweaker/crafting%20table%20recipes/recipe%20functions/enchantment_transfer/enchantment_transfer.zs
