### ISSUE TITLE
[1.16.1] Datapacks errors whilst attempting to create SP world.

### ISSUE THREAD

**Issue by Gbergz** [CraftTweaker/CraftTweaker#1004]
#### Issue Description:
Getting Datapacks Errors while trying to create a world.

#### What happens:
Just installed the first release of CraftTweaker for 1.16.1 and I'm getting Datapacks Errors while trying to create a SP world.
Prompts me with a button called "Safe Mode", pressing it and nothing happens at all. Only "Back to title screen" works. Yields no world creation ofcourse.

This is all on a clean instance with only forge 1.16.1 & crafttweaker

GIF of what happens: https://gyazo.com/66a55e8d3235abfc085fb0f3c23bed69

#### What you expected to happen:
Creating the world as normal with no Datapacks error prompts.

#### Script used:
No scripts are being used for the moment.

#### crafttweaker.log file:
https://hastebin.com/dogujabija.md

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.16.1
- Forge: 32.0.59
- Crafttweaker: 1.16.1-7.0.0.1
- Using a server: No.

#### Your most recent log file where the issue was present: 

https://gist.github.com/Gbergz/c986cf80aa7131e4c09f5c7b238d1e93

**Comment by jaredlll08** [comment]
If you add a script, does it work?

Also can you just confirm it works without crafttweaker please.

**Comment by Gbergz** [comment]
The world creation works without crafttweaker installed, yes.

And if I add a script it still doesn't work.

**Comment by jaredlll08** [comment]
Oh, update Forge to the latest, should need 32.0.61

**Comment by whatthedrunk** [comment]
I got the same thing on 32.0.61 and adding a test script still gave me the error.

**Comment by jaredlll08** [comment]
I can't seem to be able to reproduce, could I get a clean log from someone running 32.0.61+ please

**Comment by Gbergz** [comment]
Running with Forge 32.0.62 + CraftTweaker now and it works. I'm able to generate and join a SP world.

EDIT: Works with multiple mods aswell. Seems updating Forge to .62 solved it for me.

**Comment by whatthedrunk** [comment]
I did some testing and for me removing Biomes O Plenty fixed it.

**Comment by jaredlll08** [comment]
Going to close this then :)
