### ISSUE TITLE
Help!  Crafttweaker Error!

### ISSUE THREAD

**Issue by ZurexX** [CraftTweaker/CraftTweaker#1006]
Hello,
I just started editing recipes with Crafttweaker, but now i have a problem with a Recipe from Overloaded.

I already searched on google for a solution, but I cannot find the Problem.

If i'am joining a minecraft world, in says in the Chat: ERROR: [crafttweaker : SIDE_CLIENT]: Error parsing crafting.zs:13 -- ] or , expected .

Script: https://pastebin.com/0pdTTb5g

Crafttweaker Log: https://pastebin.com/GthEaBfk

**Comment by kindlich** [comment]
Please use your full script.
We can't tell what was line 13 since in your script it doesn't exist.
Also, you did not provide what version of CraftTweaker and Minecraft you are running on.

The issue Template exists for a reason.

**Comment by ZurexX** [comment]
> Please use your full script.
> We can't tell what was line 13 since in your script it doesn't exist.
> Also, you did not provide what version of CraftTweaker and Minecraft you are running on.
> 
> The issue Template exists for a reason.

This was the full script. 
CraftTweaker2-1.12-4.1.20.581 for the minecraft version 1.12.2

**Comment by jaredlll08** [comment]
You're log references line 13, your script is like 5 lines, so either that isn't the full script or you gave us an old log.

**Comment by ZurexX** [comment]
> You're log references line 13, your script is like 5 lines, so either that isn't the full script or you gave us an old log.

The Script, is 5 lines. There's no more Script.

**Comment by jaredlll08** [comment]
You're log references line 13, your script is like 5 lines, so either that isn't the full script or you gave us an old log.

**Comment by ZurexX** [comment]
> You're log references line 13, your script is like 5 lines, so either that isn't the full script or you gave us an old log.

It is the only one Script i did, so there can't be an old log

**Comment by jaredlll08** [comment]
You need to start reading what I am saying.

the log you provided us, references line 13: `crafting.zs:13` (format is `file.zs:line`).

So once again, either you have given us a bad log, or you haven't included your full script.

The only way for this to error on line 13 is for line 13 to exist. which it doesn't with what you have provided.

**Comment by ZurexX** [comment]
This is was all of the Script and it was the newest Log. I ask on other Websites
