### ISSUE TITLE
[1.16.1] Command /ct hand(or any CT command) stops working after a /reload

### ISSUE THREAD

**Issue by Gbergz** [CraftTweaker/CraftTweaker#1009]
#### Issue Description: 
This bug occurs with a clean instance & only CraftTweaker. But it also appears when using an instance with 100+ Mods.
When using ``/ct hand`` to get item IDs etc. And then using /reload, the command ``/ct hand`` becomes an Unknown or Incomplete command.

EDIT: It appears every CT Command stops working after a ``/reload``.

#### What happens:
The command ``/ct hand`` stops working after a ``/reload``.

#### What you expected to happen:
That the command ``/ct hand`` still works after a ``/reload``.

#### Script used:
No scripts are used in this instance. But i've tried with scripts and it still happens.

#### crafttweaker.log file
https://gist.github.com/Gbergz/0c425b4166fbab4f2177c9cf5a70714e

____
#### Affected Versions:

- Minecraft: 1.16.1
- Forge: 32.0.63/66
- Crafttweaker: 7.0.0.6
- Using a server: No.

#### Your most recent log file where the issue was present: 
https://gist.github.com/Gbergz/fc52898e5a2081ed47a6d9264a5a41b9

**Comment by jaredlll08** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/6969
