### ISSUE TITLE
[1.12.2]Crafting is all broken.

### ISSUE THREAD

**Issue by Terra-B-Welch** [CraftTweaker/CraftTweaker#1013]
#### Issue Description:
Not entirely certain why, but when I attempt to craft anything form a mod I get errors from CTGUI when attempting to craft anything that isn't vanilla, namely primalcore stuff has problems and I am unable to craft anything from the mod whatsoever.

It never shows any script errors ingame, just the issue stated above.

#### What happens:
Most mod recipes fail to function, rendering them uncraftable, I get numerous crash reports from Vanillafix. I managed to pull this out of the log file. I've even had it just straight up delete items when attempting to craft with them using JEI.

https://pastebin.com/JKDjgv9u

(The pastebin was what I pulled out of MultiMC's log.)

#### What you expected to happen:
To be able to craft, and not be error-bombed.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
All scripts combined into one here, sorted by their zs files.
https://gist.github.com/Terra-B-Welch/3f5abac5fb7cea8c7c26d10ca1481e73

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/Terra-B-Welch/39b903481131b7be25e7d31b66a3723d

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.2
- Forge: 14.28.5.2847
- Crafttweaker: 4.1.20.581
- Using a server: No

#### Your most recent log file where the issue was present: 
https://gist.github.com/Terra-B-Welch/9f6ea373de96f7655788238746ac304c

**Comment by jaredlll08** [comment]
firstly please never put your scripts like that. it helps noone.

secondly remove every instance of `replaceAllOccurences` and try again.

**Comment by Terra-B-Welch** [comment]
The replaceAllOccurances instance that was triggering it was the paper one.
Apparently it really doesn't like fixing recipes that use paper.

**Comment by jaredlll08** [comment]
Cool, all I can say is don't use replaceallOccurances, it is buggy, broken and just unfixable.

**Comment by Terra-B-Welch** [comment]
I'll keep all the ones I have now(as they all work without issue) but I don't think I'll be adding any more in the future.
As for the paper, I just made a new recipe for the one reason why I wanted the paper oredict recipe to be used(realistic torches matchbox)
