### ISSUE TITLE
1.12.2 Server crash, noclassdeffound - linux

### ISSUE THREAD

**Issue by deadspidervenom** [CraftTweaker/CraftTweaker#1014]
https://pastebin.com/kz3aJa2j

On load up server crashes, client loads up just fine.

Mod version CraftTweaker2-1.12-4.1.20.581.jar

**Comment by deadspidervenom** [comment]
Why was my issue closed

@jaredlll08

**Comment by jaredlll08** [comment]
You don't bother to fill out the issue template.
I don't bother giving you a reason.
