### ISSUE TITLE
[1.15.2] ae2 recipetypes are unknown

### ISSUE THREAD

**Issue by TheUntamed** [CraftTweaker/CraftTweaker#1025]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:
I tried to add my own recipes to ae2 recipetypes like the grinder via crafttweakers data support. I had to recognize that ae2's recipetypes are unknown. I posted this issue on ae2 github which will explain everything else:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4521

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://gist.github.com/TheUntamed/23daed1a5adc2aeb70c0fdf7b7b5a217

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/TheUntamed/fc3046af88be6295c798d83ad5fb748c

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.15.2
- Forge: forge-31.2.33
- Crafttweaker: 6.0.0.37
- appliedenergistics2: 7.0.0-beta.1

#### Your most recent log file where the issue was present: 

https://gist.github.com/TheUntamed/1d45457940026eebe969ea5c97aee30a

**Comment by jaredlll08** [comment]
Not on our side.
