### ISSUE TITLE
[1.16.1] NullPointerException on load

### ISSUE THREAD

**Issue by davisjw** [CraftTweaker/CraftTweaker#1028]
#### What happens:
On Load get NullPointerException; no scripts load

#### What you expected to happen:
Scripts to load and work properly without NPE

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/A1pDcYdB

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/5EEsUX0i

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.16.1
- Forge: 32.0.77
- Crafttweaker: 7.0.0.21 & 7.0.0.22
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 
https://pastebin.com/RnrYPLPp

**Comment by jaredlll08** [comment]
You say this is 1.16.1?

Where are you getting:
```
import mods.immersiveengineering.Crusher;
import mods.immersiveengineering.ArcFurnace;
import mods.mekanism.enrichment;
```
from?

**Comment by davisjw** [comment]
i was trying something that I picked up from a different modpack.  figuring that importing would load the class related to the machine and I could short-hand the machine.  Here is the paste for my original script where I had everything written out.
https://pastebin.com/vYEZ7nL6

**Comment by jaredlll08** [comment]
Don't take other peoples scripts if you don't know what you're doing.


Neither IE nor mekanism have crafttweaker support in 1.16.
