### ISSUE TITLE
Hiding Item with NBT tags

### ISSUE THREAD

**Issue by monster010** [CraftTweaker/CraftTweaker#1029]
#### Issue Description:
I try to hide items that have an NBT tag, for example enchanted books.

#### What happens:
Nothing.
![Screenshot](https://i.imgur.com/vi4b6bT.png)

#### What you expected to happen:
That the items are hidden.

#### Script used:
https://pastebin.com/Qb78d8zN

#### crafttweaker.log file:
https://pastebin.com/BbGrpmhR
https://pastebin.com/3BZk74at
The two together are one log.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Crafttweaker: 1.12-4.1.20.582
- Using a server: no

#### Your most recent log file where the issue was present: 
https://gist.github.com/monster010/39d3cf798a4814f8cb833732dc60f790

**Comment by kindlich** [comment]
If I remember correctly, JEI used a special module to show enchanted books (and potion arrows) so you can't hide them.
In the worst case you can use JEI's inbuilt hiding feature for these few cases.

**Comment by monster010** [comment]
I can guess, is it the same with decocraft props?

But why don't you write the code in the correct order, so that everything is added first and then everything is removed? For me this is the correct order and not the other way around, then the problem would not exist or am I thinking wrong?

Oh, although the problem would probably still exist, depending on what the rest of the code looks like and depending on when the things are hidden.

**Comment by jaredlll08** [comment]
I have no idea what you're going on about, but whatever it is, it isn't related to this issue.

Actions are staged, removals always run before additions.

As kindlich said, the issue is with JEI and you should probably use the built in JEI hiding mode.
