### ISSUE TITLE
Need help on this error on code, can't seem to see whats wrong

### ISSUE THREAD

**Issue by Jennifercutixx** [CraftTweaker/CraftTweaker#1031]
The error:
![Error](https://user-images.githubusercontent.com/60190810/89556677-a7382000-d809-11ea-8d55-3415094f14c6.png)
The code:
![code](https://user-images.githubusercontent.com/60190810/89556716-b6b76900-d809-11ea-8da5-aa55c250ca39.png)

Any help on this would be apprieated, been useing this for ages and never had this error before beacuse it was working.

**Comment by jaredlll08** [comment]
use the issue template.
