### ISSUE TITLE
getting this error: side-client error parsing recipeHandler.zs:33 (expected

### ISSUE THREAD

**Issue by farnoods** [CraftTweaker/CraftTweaker#1034]
I've triple checked my syntax, can't find what's wrong with my code for the life of me. Please help.

This is the script: [link](https://gofile.io/d/JcVTbF)
This is the crafttweaker log: [link](https://gofile.io/d/0SSuxx)

**Comment by jaredlll08** [comment]
Read the issue template.

It includes stuff we need like what mc version, Forge version, mod version, and it says to upload your scripts to pastebin or gist.github.com

Im not downloading a file to tell you what is wrong. 

On top of that I'm on mobile, so even if i was willing to download the file, I couldn't even read it

**Comment by farnoods** [comment]
This is the script:  https://pastebin.com/b5VuhmZs 
This is the crafttweaker log:  https://pastebin.com/EMkYETe2 

MC Version: 1.12.2
Forge Version: 14.23.5.2847
Crafttweaker Version:  1.12 - 4.1.19

**Comment by kindlich** [comment]
You didn't close one of your code blocks in `createShapelessRecipe`
You got 3 `{` but only 2 `}`
