### ISSUE TITLE
Cannot cast ZenTypeNative: crafttweaker.item.IItemStack to ZenTypeNative: crafttweaker.oredict.IOreDictEntry

### ISSUE THREAD

**Issue by farnoods** [CraftTweaker/CraftTweaker#1036]
Getting this error.. I think my casting is wrong but I don't know how to fix it. Appreciate it if someone can help

oreDictHandler.zs: https://pastebin.com/n2tRTGKF
oreDict.zs: https://pastebin.com/4GKvnS2p
postinit.zs: https://pastebin.com/JiZnNzvW

crafttweaker log: https://pastebin.com/3WeMyU1u

MC Version: 1.12.2
Forge Version: 14.23.5.2854
Crafttweaker Version: 1.12-4.1.20.574

**Comment by kindlich** [comment]
`static oreDictAdditions as IItemStack[][IOreDictEntry]` tells ZS that your keys (the things before the `:` in the declaration) need to be an IOreDictEntry.
However, `<biomesoplenty:gem_block:6>` is an Item, not an oredice Bracket Handler.
An oredict entry looks like
`<ore:blockSapphire>`

You can get the oredict that an item is in by holding it in your hand and typing `/ct hand`.
The chat message will include any oredict entries that the item is in.

**Comment by kindlich** [comment]
Is this still an issue?
If not I will close it

**Comment by farnoods** [comment]
No, all fine now. Thank you so much for the help!
