### ISSUE TITLE
[1.12.2] Crash on startup

### ISSUE THREAD

**Issue by DarkScorn** [CraftTweaker/CraftTweaker#1037]
#### What happens:
Game crashes on startup

#### What you expected to happen:
add a recipe to transposer for fluid ammonia

____

- Minecraft: 1.12.2
- Forge:14.23.5.2847
- Crafttweaker: 1.12, 4.1.20.562
- Using a server: no

#### Your most recent log file where the issue was present: 
https://gist.github.com/DarkScorn/7833ced6e9a4bc0ec2131318b5b013d1
https://gist.github.com/DarkScorn/5ae2f9696a54bbc786403e8c3fb92851
https://gist.github.com/DarkScorn/2d6570c60b8b7f3dade14ef64ed91d0b

**Comment by jaredlll08** [comment]
I don't care how long the script is, github ***removes*** stuff from it because it is considered markdown (notice how none of your items have `<>`.

Also I'm not downloading files. everything on https://pastebin.com / https://gist.github.com

**Comment by jaredlll08** [comment]
No idea what is going on with your links, there is so much duplicate / different data.

Either way what is your `rockhounding.zs` script?

**Comment by DarkScorn** [comment]
here is rockhounding zs, this script does not cause crash, but always says error parsing in-game.

https://gist.github.com/DarkScorn/0826f57c1591c0d11a84a4e127c832d8

**Comment by jaredlll08** [comment]
Yea uh, that file is very far from fine, no idea what you're doing using `*` for comments.

I suggest you read this
https://docs.blamejared.com/1.12/en/Getting_Started/#comments


That file is definitely causing the errors, your other files aren't even being loaded yet.

**Comment by DarkScorn** [comment]
Okay then, thanks.
