### ISSUE TITLE
[1.12.2] Renaming enchanted golden apple also renames the normal one

### ISSUE THREAD

**Issue by vizthex123** [CraftTweaker/CraftTweaker#1038]
### What happens:
Both of the Golden Apples get renamed

#### What you expected to happen:
Only the shiny one gets renamed

#### Script used
`<minecraft:golden_apple:1>.displayName = "Mystical Apple";`

#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Crafttweaker: 4.1.20.582
- Using a server: No
- If yes, does the client have the exact same scripts?

**Comment by jaredlll08** [comment]
If the items use the same translation key (which they do), there is nothing that can be done on the global scale. Not even with a resource pack.

**Comment by vizthex123** [comment]
Argh, alright then. I was hoping it'd be fixable.
