### ISSUE TITLE
Server failed to start: crafttweaker failed to load.

### ISSUE THREAD

**Issue by BigCasper** [CraftTweaker/CraftTweaker#1039]
#### Issue Description:
Plain and simple, crafttweaker failed to load correctly. I've read the log. Nothing simple comes to mind.

#### What happens:
Server crashes on start.

#### What you expected to happen:
Server starts without spilling.

#### Script used: (I don't think the server even got to loading scripts)
https://pastebin.com/hFrWBMwU
https://pastebin.com/sLB6AAru
https://pastebin.com/CdEG8CdC
https://pastebin.com/ikFyfH3T
https://pastebin.com/YCFJVfsE
https://pastebin.com/wdFDg5r1

#### crafttweaker.log file: https://pastebin.com/WvN99s4B

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.16.1
- Forge: 32.106/107
- Crafttweaker: 7.0.0.19
- Using a server: Yes
- If yes, does the client have the exact same scripts? Yes. Client works fine. Only server is making issues.

#### Your most recent log file where the issue was present: https://pastebin.com/hRat3DDN (server log)

[pastebin/gist/etc link here]

**Comment by kindlich** [comment]
Get the latest 1.16 beta from CurseForge (we should be at .23 atm iirc), it should've been fixed in there already.
