### ISSUE TITLE
Can't run a server with CT in 1.16.1

### ISSUE THREAD

**Issue by Protected** [CraftTweaker/CraftTweaker#1040]
#### Issue Description:
I'm preparing a 1.16 Forge headless/dedicated server. When CT is in the mods directory, the server crashes during the launch sequence. Removing CT allows the server to function normally. The exact same setup doesn't crash a 1.16 client.

#### What happens:
Shortly after the MinecraftForge Initialized message, a NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag exception is thrown. Loading continues but shuts down a few moments later, referencing this exception again ("Loading errors encountered").

#### What you expected to happen:
Initialization with no exceptions and no crash (as it happens in a GUI client).

#### Script used
N/A: No scripts in use.

#### crafttweaker.log file
Literally just this single line:

[18:39:02.203][CONSTRUCT][CLIENT][ERROR] BEP recipemanager has a validator but no BEP method

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.16.1
- Forge: 32.0.106 *&* 32.0.108 (both tested)
- Crafttweaker: 7.0.0.19
- Using a server: yes
- If yes, does the client have the exact same scripts? yes

#### Your most recent log file where the issue was present (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.):

https://gist.github.com/Protected/834a86548802cfe8cc6b3ed7d62ee5a2

**Comment by jaredlll08** [comment]
Update crafttweaker to the latest on curse, should be 7.0.0.23
