### ISSUE TITLE
Crash My server!

### ISSUE THREAD

**Issue by MrScautHD** [CraftTweaker/CraftTweaker#1042]
Hi i have Installed you mod in my modpack and Crash this mod my modpack can you pls fix this in the next version?
[crash.txt](https://github.com/CraftTweaker/CraftTweaker/files/5064928/crash.txt)

**Comment by jaredlll08** [comment]
follow the template.

**Comment by kindlich** [comment]
Also please don't report bugs that have been fixed already.
Check the closed issues section first.

**Comment by MrScautHD** [comment]
is it not work i have the newst version!

**Comment by kindlich** [comment]
Since you did not provide any of the information we asked for we can't help you.
The issue template is there for a reason.

**Comment by MrScautHD** [comment]
ok i make a new
