### ISSUE TITLE
My Server is Crahsed with Crafttweaker!

### ISSUE THREAD

**Issue by MrScautHD** [CraftTweaker/CraftTweaker#1043]
#### Intro:
My Sever Crashded when i add the Newst Version of you mod 
My server is on 1.16.1-32.0.106
And this is a Modpack:https://www.curseforge.com/minecraft/modpacks/toria

#### What happens:
The Server Chrased with you mod!

#### Script used (Please pastebin.com or gist.github.com your script, posting an unpasted or ungist'd script will automatically 
https://pastebin.com/zqBgLsRJ

#### crafttweaker.log file (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:
- Forge:yes
- Crafttweaker: yes
- Using a server: yes
- If yes, does the client have the exact same scripts?
yes but Only on server is the Crash and the Cleint not!

#### Your most recent log file where the issue was present (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.):

[https://pastebin.com/zqBgLsRJ]

**Comment by jaredlll08** [comment]
https://www.curseforge.com/minecraft/mc-mods/crafttweaker/files/3027150
