### ISSUE TITLE
Cant seem to add Immersive Engineering Reicpe's to Crafttwecker.

### ISSUE THREAD

**Issue by chyper111** [CraftTweaker/CraftTweaker#1050]
#### Intro:
I tried to add this harden clay recipe to the crusher and it didn't add. 

mods.immersiveengineering.Crusher.addRecipe(<minecraft:clay_ball>*4, <minecraft:hardened_clay>, 4000);

I also tried to add this ore just to make sure.
mods.immersiveengineering.Crusher.addRecipe(<immersiveengineering:dust_copper>*2, 
<more_ores:copper>, 1024);

#### Issue Description:
cant add recipe.

#### What happens:
nothing just says error but i cant find any info on it

#### crafttweaker.log file (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.15
- Forge:31.2.36
- Crafttweaker: 6.0.0.24
- Using a server: no just lan
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.):

[pastebin/gist/etc link here]

**Comment by chyper111** [comment]
just need to know what I'm doing wrong cant find any info on this.

**Comment by jaredlll08** [comment]
immersive engineering doesn't have crafttweaker support in 1.14+.


Also seriously, if I ask you to pastebin / gist your script. do it. Github applies markdown to scripts and removes `<>`

**Comment by chyper111** [comment]
i had one line of script didn't see the need to Paste bin but thanks for the quick response

**Comment by jaredlll08** [comment]
Well considering github posted it as:
![image](https://user-images.githubusercontent.com/5553605/90950680-36714480-e454-11ea-808b-d45e3cb7a590.png)

How am I meant to know if
```
immersiveengineering:dust_copper
```

is actually:
```
<immersiveengineering:dust_copper>
```
or if you actually have
```
immersiveengineering:dust_copper
```
in your script.

**Comment by chyper111** [comment]
ahh thats the problem with the script other then not being usable in 1.15.
which was my original question.

**Comment by chyper111** [comment]
which btw i cant find any info about it not being useable for 1.15. its
nice to know that so i don't waste your time.

**Comment by jaredlll08** [comment]
I'm not sure what more information I could give.

besides the fact that I never supported IE in any of my mods, it was always added by them, the docs don't exist because the support doesn't exist.

and there are probably 3 other issues asking the same question.

**Comment by chyper111** [comment]
No thats cool I appreciate you just telling me it doesnt exist. I dont want
to bug somebody over something they can't do anything about. I just needed
to know why it wasnt working is all. You solved that. Thanks
