### ISSUE TITLE
EntityLivingAttackedEvent and EntityLivingHurtEvent amount should have a setter

### ISSUE THREAD

**Issue by ExpensiveLadder** [CraftTweaker/CraftTweaker#1051]
**Feature request name**
EntityLivingAttackedEvent and EntityLivingHurtEvent amount should have a setter

**Feature request description**

**Feature request reason**
Change damage when an entity is hurt

**Feature request dependencies**
no

**Comment by ExpensiveLadder** [comment]
Heres an example it makes creepers take half damage from lightning
[Example.txt](https://github.com/CraftTweaker/CraftTweaker/files/5115422/Example.txt)

**Comment by jaredlll08** [comment]
EntityLivingAttackedEvent doesn't have an option to set the value.

EntityLivingHurtEvent does however, so I added that.
