### ISSUE TITLE
[1.16.2] Server Crash

### ISSUE THREAD

**Issue by Daejangnamu** [CraftTweaker/CraftTweaker#1052]
https://gist.github.com/Daejangnamu/b2bc442e83332cd160335373a3cfcfdc

Forge 1.16.2-33.0.7
CraftTweaker-1.16.2-7.0.0.27

**Comment by jaredlll08** [comment]
use the template.
I'm not going to download files.

**Comment by Daejangnamu** [comment]
> use the template.
> I'm not going to download files.

I don't know what a template is.
Please tell me how to use it.

**Comment by Daejangnamu** [comment]
> use the template.
> I'm not going to download files.

https://gist.github.com/Daejangnamu/b2bc442e83332cd160335373a3cfcfdc

**Comment by jaredlll08** [comment]
Thanks

**Comment by jaredlll08** [comment]
Does it work fine in singleplayer?

**Comment by jaredlll08** [comment]
I'm unable to reproduce, can you try on forge 33.0.20 with just crafttweaker alone?

**Comment by Daejangnamu** [comment]
multiplayer
i should use forge 33.0.7.
Don't support?

**Comment by jaredlll08** [comment]
I'm asking if you can test on 33.0.20.


Also does it work with *just* crafttweaker?

**Comment by Daejangnamu** [comment]
> I'm asking if you can test on 33.0.20.
> 
> Also does it work with _just_ crafttweaker?

I'm working now. I'll test it later.

**Comment by Daejangnamu** [comment]
Forge 33.0.20 It works fine.

**Comment by jaredlll08** [comment]
if 33.0.20 works fine, then use that one.
