### ISSUE TITLE
Question regarding Backpacks mod recipes

### ISSUE THREAD

**Issue by xJon** [CraftTweaker/CraftTweaker#1053]
Hi,
The [Backpacks mod](https://www.curseforge.com/minecraft/mc-mods/forge-backpacks) adds recipes which craft backpacks with a specific UID; holding one and typing `/ct hand` prints this:
```
<backpack:backpack:200>.withTag({"backpack-UID": "10512ab0-c73e-41cc-b574-4c54bc25e36f", slots: 54, leather_tier: "III", frame_tier: "III", slots_used: 0, module_slots: 6, slots_per_row: 9})
```
It appears that attempting to craft one without the `backpack-UID` field makes it non-usable.
Is there any way of making custom crafting recipes for the mod with that requirement? Can CraftTweaker generate such UID?
Thank you!

**Comment by jaredlll08** [comment]
Not really, that would require randomness (to generate a random uuid), which isn't really in CraftTweaker (it is a mission to sync things correctly).
