### ISSUE TITLE
Configuration / Lava (Help me please)

### ISSUE THREAD

**Issue by CapivaraTupiniquim** [CraftTweaker/CraftTweaker#1055]
Can someone help me generate lava with cobblestone in More Cauldrons Mod and Inspirations Mod? I don't know how to configure this to be possible.
If you have an easier way with another mod also accepted (a very OP generation of lava).

**Comment by jaredlll08** [comment]
https://discord.blamejared.com

**Comment by CapivaraTupiniquim** [comment]
@jaredlll08 can you help me on Discord? I'll text there
