### ISSUE TITLE
Fermentation Station / Industrial Foregoing

### ISSUE THREAD

**Issue by LnX-OrioN** [CraftTweaker/CraftTweaker#1057]
Hi, Can you add compatibility with the fermentation station in industrial foregoing mod, i want add custom recipes for my modpack ( Ascensio on curseforge ).

Fermentation station fits perfectly to use with rustic and others alcool mods for brewing.
The rustic brewing barrels doesn't allow automations with pipes or floppers.

Thanks for consider my request 😉

Minecraft 1.12.2
Forge 14.23.5.2847

**Comment by jaredlll08** [comment]
Duplicating your question from https://github.com/jaredlll08/ModTweaker/issues/764
Isn't going to get you far.

1.12 isn't supported for new features anymore, so either ask the mod dev of that mod, or make an addon mod yourself.
