### ISSUE TITLE
mc1.16.1|ct12.0.4| Im creating a pack. i cant get anything to work besed on the reference materials ive found

### ISSUE THREAD

**Issue by reapersremorse** [CraftTweaker/CraftTweaker#1059]
I would like to say I'm sorry for posting an issue in the wrong place first. 
-----------------------------------------------------------------------------------------------------------------------
I am able to add and remove anything from vanilla crafting. but when i try anything modded it does not work. the chat error complains about syntax. I can't change fuel values, hide items in jei, and maybe more.
I'm able to add and remove recipes for vanilla and for the extended crafting mod easily. but when I try doing something "extra" it does not work.
if anyone can show me the error in my ways, I would be most appreciated.
if i need to setup a github repo, i will.

this is a personal pack that i have not released, mostly used for me and some friends. im in the process of rebuilding for the 5th version
-----------------------------------------------------------------------------------------------------------------------
my referenced material:
https://docs.blamejared.com/
https://github.com/CraftTweaker/CraftTweaker-Examples/blob/master/1.14/general.zs
https://github.com/CraftTweaker/CraftTweaker-Documentation/blob/master/docs/Mods/JEI/JEI.md
-----------------------------------------------------------------------------------------------------------------------
Important info:
Minecraft 1.16.1
forge-32.0.108
CraftTweaker | Jaredlll08 | CraftTweaker-1.16.1-7.0.0.24.jar
Crafting Tweaks | BlayTheNinth | CraftingTweaks_1.16.1-12.0.4.jar
Applied Energistics 2 | AlgorithmX2 | appliedenergistics2-8.0.0-beta.2.jar
JEI Integration | SnowShock35 | jeiintegration_1.16.1-4.0.0.4.jar
JEITweaker | Jaredlll08 | JEITweaker-1.16.1-1.0.1.2.jar
Just Enough Items (JEI) | mezz | jei-1.16.1-7.0.1.10.jar
Just Enough Resources (JER) | way2muchnoise | JustEnoughResources-1.16.1-0.11.1.98.jar
KubeJS | LatvianModder | kubejs-2.7.2.59.jar
Extended Crafting | BlakeBr0 | ExtendedCrafting-1.16.1-3.0.1.jar
-----------------------------------------------------------------------------------------------------------------------
//my furnace_changes.zs file
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.item.IIngredient;
import crafttweaker.api.FurnaceManager;
import crafttweaker.api.registries.ICookingRecipeManager;
import crafttweaker.api.BlastFurnaceManager;
import crafttweaker.api.CampFireManager;
import crafttweaker.api.CraftingTableManager;
import crafttweaker.api.registries.IRecipeManager;
import crafttweaker.api.SmokerManager;
import crafttweaker.api.StoneCutterManager;

furnace.setFuel(minecraft:glass, 400); //wont work
mods.jei.JEI.hideCategory("appliedenergistics2:facade");//wont work
mods.jei.JEI.removeAndHide(appliedenergistics2:facade);//wont work
mods.jei.JEI.hide(item:appliedenergistics2:facade);//wont work
-----------------------------------------------------------------------------------------------------------------------
//my remove_recipes.zs file
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.item.IIngredient;
import crafttweaker.api.FurnaceManager;
import crafttweaker.api.registries.ICookingRecipeManager;
import crafttweaker.api.BlastFurnaceManager;
import crafttweaker.api.CampFireManager;
import crafttweaker.api.CraftingTableManager;
import crafttweaker.api.registries.IRecipeManager;
import crafttweaker.api.SmokerManager;
import crafttweaker.api.StoneCutterManager;

//removeRecipe(IItemStack output);
craftingTable.removeRecipe(item:quark:charcoal_block);//this works well
-----------------------------------------------------------------------------------------------------------------------
//logs
https://gist.github.com/reapersremorse/12a982e7651e66389a7e44006c51b7a1

**Comment by jaredlll08** [comment]
the template specifically asked for scripts on gist.github.com.

if you look at that you posted you will notice the difference between what github shows and what you posted.

**Comment by reapersremorse** [comment]
sorry, I'm not seeing what the difference is. I have imports but that's not in any error logs.
also sorry ive been at work or i would have messaged back sooner.

i just copied over this line: mods.jei.JEI.hide(<minecraft:diamond>);//does not work
from: https://github.com/CraftTweaker/CraftTweaker-Documentation/blob/master/docs/Mods/JEI/JEI.md

the chat log says
Parser Exception: furnace_changes.zs19:18: Invalid bracket expression: no prefix minecraft
Parser Exception: furnace_changes.zs19:37: ; expected
scripts are invalid!

if I change the prefix before minecarft to be item:
EX: mods.jei.JEI.hide(<item:minecraft:diamond>);

then i get the following message: Parser Exception: furnace_changes.zs19:0 Member not found: hide Scripts are invalid!
i copied over the word for word what was in the template. I'm still not getting the hiding to work. I tried vanilla items without nbt and modded.

it may be staring me right in the face but im just not seeing the issue.

i just created a public github for the pack im working on. if that helps. https://github.com/reapersremorse/PackVersions/tree/master/Minecraft_1.16.1/Sanctuary_Sky

**Comment by reapersremorse** [comment]
i just noticed that what i sent you does not have <> brackets but my code does
and the code does not work, sorry i didnt ni=otice that before im just exhausted

but my code still does not work without or with these

**Comment by jaredlll08** [comment]
you're looking at the 1.12 docs
https://docs.blamejared.com

all items need to have `<item:` before them, like so:
`<item:minecraft:diamond>`

**Comment by reapersremorse** [comment]
i had 

> you're looking at the 1.12 docs
https://docs.blamejared.com
all items need to have <item: before them, like so:
<item:minecraft:diamond>

i had that already.
i found the real fix, i had 
mods.jei.JEI.hide(<item:minecraft:diamond>)
but its changed to
mods.jei.JEI.hideItem(<item:minecraft:diamond>)

from hide to hideItem

i realize i was looking at older versions of the code. i didnt see the documentation for jeitweaker when i started looking for this.

for some reason my <> brackets keep getting deleted when i post on here. but i have dated documentation showing that my only issue was the hideItem and not the prefix of item

when i started looking for a fix a week ago, i didnt see this jeitweaker documentation on your site, which is why i started looking elsewhere. and i found old examples. 

sorry for bothering you.

**Comment by jaredlll08** [comment]
> sorry for bothering you.

Don't be! 

If you have any more questions, feel free to join the discord server
https://discord.blamejared.com

It's way better for general questions like this, github is more suited towards bug reports :)

**Comment by reapersremorse** [comment]
thank you for putting up with my nonsense lol i just joined
