### ISSUE TITLE
blood altar documentation

### ISSUE THREAD

**Issue by DmitrijevK** [CraftTweaker/CraftTweaker#1061]
#### Intro:
Template from documentation don't work

#### Issue Description:
Blood altar recipe template from documentation don't work

#### What happens:
Template from documentation don't work

#### What you expected to happen:
Template from documentation don't work

#### crafttweaker.log file (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will 
https://gist.github.com/Dmitrjiev/5822abaf33463d36278d47bc1cdf9bc5

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.2
- Forge:  14.23.2854
- Crafttweaker: 2-1.12-4.1.20.586
- Using a server: -
- If yes, does the client have the exact same scripts?

**Comment by DmitrijevK** [comment]
modtweaker is installed

**Comment by jaredlll08** [comment]
```
[INITIALIZATION][CLIENT][ERROR] [crafttweaker | SIDE_CLIENT]: Error parsing ba.zs:3 -- ; expected
[INITIALIZATION][CLIENT][ERROR] [crafttweaker | SIDE_CLIENT]: Error parsing infusion.zs:24 -- ; expected
```


You're missing a semi colon at the end of a line, but since I don't have your full scripts, I can't really help from there.

Look for missing semicolons on line 3 or `ba.zs` and line 24 of `infusion.zs`

**Comment by DmitrijevK** [comment]
mods.bloodmagic.BloodAltar.addRecipe(<minecraft:glass>, <minecraft:stick>, 0, 20,30,40)**;**

**Comment by jaredlll08** [comment]
that still doesn't help me, especially since github stripped the `<>` away.

Since this isn't a bug, you should join https://discord.blamejared.com and ask for help there
