### ISSUE TITLE
[Feature Request] Remove existing JEI description tab.

### ISSUE THREAD

**Issue by AlasICannotSwim** [CraftTweaker/CraftTweaker#1065]
Currently, there exists the option to add JEI information tabs:

mods.jei.JEI.addDescription(IItemStack, string);

However, there is no way to remove text in an existing JEI info tab. This can be troublesome in cases where you want to replace an information tab.

**Comment by democat3457** [comment]
This is an issue for JEI

**Comment by jaredlll08** [comment]
As Democat said, this is an issue for JEI.

JEI doesn't have an API method to remove information.
