### ISSUE TITLE
[1.12.2]Deleting a recipe from ThermalExpansion (Transposer)

### ISSUE THREAD

**Issue by kellixon** [CraftTweaker/CraftTweaker#1072]
MC - 1.12.2.
Forge - 14.23.5.2854.
CraftTweaker - CraftTweaker2 4.1.20.589.
ThermalExpansion - ThermalExpansion 5.5.7.1.
I can't delete a recipe from ThermalExpansion: 1 and 4 pearls on the way out. What am I doing wrong?
My lines in crafttweaker.zs and a screenshot of which recipes I delete.
----------
mods.thermalexpansion.Transposer.removeExtractRecipe(<minecraft:ender_pearl>);
mods.thermalexpansion.Transposer.removeExtractRecipe(<minecraft:ender_pearl>*4);
----------
![javaw_2020_09_21_10_23_08_129](https://user-images.githubusercontent.com/22012731/93741936-f093d180-fbf5-11ea-838c-500c76d95f21.jpg)

**Comment by jaredlll08** [comment]
firstly wrong repo.

secondly we have an issue template. use it.
