### ISSUE TITLE
Adding JSON recipe gives "Could not cast IData[] to List<IData>" error

### ISSUE THREAD

**Issue by keeper317** [CraftTweaker/CraftTweaker#1073]
Issue Description:
When adding a recipe for the Create mod's millstone I get the stated error.

What happens:
Error "Could not cast IData[] to List<IData>"

#### What you expected to happen:
The millstone to gain its new recipe

#### crafttweaker.log file (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.): https://pastebin.com/yG6T3Jst

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.15.2
- Forge: 31.2.37
- Crafttweaker: 6.0.0.24
- Using a server: yes
- If yes, does the client have the exact same scripts? yes
-Mod list: https://pastebin.com/iyGW4ehV

**Comment by goodtrailer** [comment]
I had a similar issue (except I was trying to make a vanilla written book with custom pages) and fixed it by importing IData:
`import crafttweaker.api.data.IData;`

Here's the script I was having trouble with, which the above solution fixed: https://pastebin.com/ndaYMveF

**Comment by jaredlll08** [comment]
Would it be possible to get a new script and log using the latest 1.16 version?

**Comment by jaredlll08** [comment]
No reply and we haven't had many reports of this lately.
