### ISSUE TITLE
[1.12.2] ERROR: [crafttweaker | SIDE_CLIENT]: Error loading {[0:crafttweaker] JEI.zs}: java.lang.NullPointerException

### ISSUE THREAD

**Issue by WestPrime** [CraftTweaker/CraftTweaker#1074]
So, I have this problem: [https://prnt.sc/umetu5](https://prnt.sc/umetu5).
Files are attached below
[crafttweaker.log](https://github.com/CraftTweaker/CraftTweaker/files/5267785/crafttweaker.log)
[JEI.txt](https://github.com/CraftTweaker/CraftTweaker/files/5267797/JEI.txt)

**Comment by jaredlll08** [comment]
Use the issue template.

**Comment by TRLWeiss** [comment]
I have the same problem and i have fixed it. Try to check your parameters,
mods.jei.JEI.hide(<extendedcrafting:lamp:*);
mods.jei.JEI.hide(<extendedcrafting:trimmed:*);
mods.jei.JEI.hide(<extendedcrafting:crafting_table);
mods.jei.JEI.hide(<extendedcrafting:guide);
mods.jei.JEI.hide(<extendedcrafting:material:*);
mods.jei.JEI.hide(<extendedcrafting:pedestal);
mods.jei.JEI.hide(<extendedcrafting:crafting_core);
you should add a >.
