### ISSUE TITLE
CraftTweaker2-1.12.2-4.1.20.589 Bug

### ISSUE THREAD

**Issue by NathaelPMCleary** [CraftTweaker/CraftTweaker#1075]
#### Intro:
This is my first time ever posting (sorry I've never used this before), but I've found a bug when trying to use CraftTweaker on version 1.12.2, 4.1.20.589.

#### Issue Description:
I get a crash notification after Phase 3 of forge  where Minecraft just stops working, and the report says it's because of this mod?

#### What happens:
Well Minecraft just stops, goes black an gives me a crash log.

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CraftTweaker2 (crafttweaker)
Exit Code: -1

#### What you expected to happen:
Minecraft to load so I can play?

#### Script used:
I don't know what this is asking?

#### crafttweaker.log file:
Where do I find this?
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2766
- Crafttweaker: 1.12.2-4.1.20.589
- Using a server: SpaceSurvivors2.aternos.me
- If yes, does the client have the exact same scripts?
Yes.

#### Your most recent log file where the issue was present:

[https://pastebin.com/nzscrTnT]

**Comment by jaredlll08** [comment]
Not a crafttweaker issue, it looks like you ran out of ram, so give your game more ram.
