### ISSUE TITLE
[JEI] Can't display wildcard metadata

### ISSUE THREAD

**Issue by SettingDust** [CraftTweaker/CraftTweaker#1077]
#### Intro:
JEI can't display the item with wildcard metadata

https://github.com/mezz/JustEnoughItems/issues/2098

#### Issue Description:
jei_1.12.2-4.16.1.302
CraftTweaker2-1.12-4.1.20.589

#### What happens:
JEI
![图片](https://user-images.githubusercontent.com/19922286/93997766-5636b800-fdc6-11ea-8daf-200a875e8510.png)

Minecraft
![图片](https://user-images.githubusercontent.com/19922286/93997815-6189e380-fdc6-11ea-8565-35aeba9498ab.png)
![图片](https://user-images.githubusercontent.com/19922286/93997831-664e9780-fdc6-11ea-92c3-cf119a1079b0.png)

#### What you expected to happen:
Craft

#### Script used (Please pastebin.com or gist.github.com your script, posting an unpasted or ungist'd script will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file):
```
val runeStone = <ebwizardry:runestone:*>;
val runeStonePedestal = <ebwizardry:runestone_pedestal:*>;

recipes.addShaped("Waystone", <waystones:waystone>, 
[
    [null,              runeStone,              null],
    [runeStone,         <waystones:warp_stone>, runeStone],
    [runeStonePedestal, runeStonePedestal,      runeStonePedestal],
]);
```

https://paste.ubuntu.com/p/8qPf8fSDNr/

#### crafttweaker.log file (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.):

https://paste.ubuntu.com/p/mZ3mm4WqJ8/

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge:
- Crafttweaker: 1.12-4.1.20.589
- JEI: 1.12.2-4.16.1.302
- Using a server: Yes
- If yes, does the client have the exact same scripts? Yes

#### Your most recent log file where the issue was present (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.):

https://paste.ubuntu.com/p/Sjb5d55P3Q/

**Comment by jaredlll08** [comment]
When you say:
> JEI can't display the item with wildcard metadata

What do you mean?
Do you mean how JEI will cycle the item it displays, like if you used a wildcard for logs it will cycle through all the different logs?

What does:
```zenscript
val runeStone = <ebwizardry:runestone:*>;
val runeStonePedestal = <minecraft:wool:*>;

recipes.addShaped("Waystone", <waystones:waystone>, 
[
    [null,              runeStone,              null],
    [runeStone,         <waystones:warp_stone>, runeStone],
    [runeStonePedestal, runeStonePedestal,      runeStonePedestal],
]);
```

produce?

**Comment by SettingDust** [comment]
> 
> 
> When you say:
> 
> > JEI can't display the item with wildcard metadata
> 
> What do you mean?
> Do you mean how JEI will cycle the item it displays, like if you used a wildcard for logs it will cycle through all the different logs?
> 
> What does:
> 
> ```zenscript
> val runeStone = <ebwizardry:runestone:*>;
> val runeStonePedestal = <minecraft:wool:*>;
> 
> recipes.addShaped("Waystone", <waystones:waystone>, 
> [
>     [null,              runeStone,              null],
>     [runeStone,         <waystones:warp_stone>, runeStone],
>     [runeStonePedestal, runeStonePedestal,      runeStonePedestal],
> ]);
> ```
> 
> produce?

JEI will display the recipe in it's gui. But the item with a wildcard meta define in CrT won't display. Like this

![](https://user-images.githubusercontent.com/19922286/93997766-5636b800-fdc6-11ea-8daf-200a875e8510.png)

But it's should be (Of course there is cycle items)
![](https://user-images.githubusercontent.com/19922286/93997815-6189e380-fdc6-11ea-8565-35aeba9498ab.png)

**Comment by jaredlll08** [comment]
Yea, can you test using vanilla items with wildcards (like wool and logs), it could be an issue with `ebwizardry` since I know for a fact that our wildcard stuff works for vanilla and all other modded items (this would be the first that I'm hearing of it causing issues)

**Comment by SettingDust** [comment]
Well. Wool is ok. And sponge I tested as well.
Why is it? How can I fix it.
Now I'm adding them to a oreDict. And it's working

**Comment by jaredlll08** [comment]
So if it works for other items, then it is definitely an issue for `ebwizardy`.

They may be doing sub items in a weird way, but there is nothing that I or JEI could do on our sides.
