### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Kangy1103** [CraftTweaker/CraftTweaker#1082]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

I am trying to create a script for a custom modpack to configure a full Akashic Tome and give it to the player but my script is giving Parsing errors.

#### What happens:
When I load the script I get the following error:
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: Akashic Tome.zs}
[INITIALIZATION][CLIENT][ERROR] [crafttweaker | SIDE_CLIENT]: Error parsing Akashic Tome.zs:186 -- ) expected

#### What you expected to happen:
The script should give a full Akashic Tome to the player

#### Script used (Please pastebin.com or gist.github.com your script, posting an unpasted or ungist'd script will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file):
https://pastebin.com/PAxkQk2Z

#### crafttweaker.log file (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.):
https://pastebin.com/NfpRvUYk

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: forge-14.23.5.2854
- Crafttweaker: 4.1.20.586
- Using a server: No
- If yes, does the client have the exact same scripts?

**Comment by kindlich** [comment]
Line 150, your string is not closed properly

**Comment by Kangy1103** [comment]
Oh my god. Thank you! I've been trawling for 2 hours trying to fix that!
