### ISSUE TITLE
[1.15.2] JEI Recipe hide

### ISSUE THREAD

**Issue by Intezium** [CraftTweaker/CraftTweaker#1084]
How i can hide recipe in JEI?
I use `mods.jei.JEI.hideItem(<item:minecraft:crafting_table>);` - dont work,
`/ct syntax` - successfully.

Forge-31.2.41
CraftTweaker-6.0.0.44
JEITweaker-1.0.1.3

**Comment by jaredlll08** [comment]
Closed in https://github.com/CraftTweaker/JEITweaker/commit/1ce9158c05cae19fd8dfcd8e5e9180e2a0b998a9
