### ISSUE TITLE
A way to remove all recipes from a whole modpack

### ISSUE THREAD

**Issue by osmanosman88** [CraftTweaker/CraftTweaker#1094]
**Feature request name**
Remove all recipes.

**Feature request description**
Removing all recipes from every single mod in a pack. 

**Feature request reason**
Two reasons.
I am making a DND campaign but its like its own game since the classes, races, weapons, and everything else will be custom. I can just tell my players to not craft but if I can just remove it from all mods with one script that would be the greatest!

**Feature request dependencies**
No Dependencies

**Game Version
1.12.2

**Comment by osmanosman88** [comment]
Sorry I just read over and forgot to add a second reason. I have thought about creating a pack before with all the recipes being there own. This would take a long time due to complete because of the amount of items in a pack but I could see it being really fun.

**Comment by kindlich** [comment]
For crafting table recipes and furnace recipes this already exists.

In 1.12, this won't exist for other mod machines.

```zenscript
furnace.removeAll();
recipes.removeAll();
```

<https://docs.blamejared.com/1.12/en/Vanilla/Recipes/Crafting/Recipes_Crafting_Table/#removeall>
<https://docs.blamejared.com/1.12/en/Vanilla/Recipes/Furnace/Recipes_Furnace/#removal>
