### ISSUE TITLE
[1.15.2] Cannot resolve utf-8 characters

### ISSUE THREAD

**Issue by friendlyhj** [CraftTweaker/CraftTweaker#1095]
#### Intro:
Cannot resolve utf-8 characters.

#### What happens:

Scripts fail loading

#### What you expected to happen:

Scripts load successfully
 
#### Script used (Please pastebin.com or gist.github.com your script, posting an unpasted or ungist'd script will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file):
```zenscript
// 注释
```

#### crafttweaker.log file (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.):

https://gist.github.com/friendlyhj/e73aa58aedfc65a729acf28251a0fd37
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.15.2
- Forge: 31.2.37
- Crafttweaker: 6.0.0.44
- Using a server: no 
- If yes, does the client have the exact same scripts?

**Comment by kindlich** [comment]
This is a ZC issue.
Could you open an issue at https://github.com/ZenCodeLang/ZenCode ?

**Comment by jaredlll08** [comment]
Fixed in https://github.com/ZenCodeLang/ZenCode/commit/c2b7e0a01177a9e56215022ac25159c1225a0c08
