### ISSUE TITLE
[1.16.3]IData can't be converted to MCblockState

### ISSUE THREAD

**Issue by raziel23x** [CraftTweaker/CraftTweaker#1099]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
when trying to make a script which require the block to be placed in world for the pure daisy to converting items for botania using addJSONRecipe to add more recipes 

#### What happens:
[17:05:17.624][DONE][CLIENT][ERROR] botania.zs:19:83 Cannot cast MCBlockState to IData, even explicitly
[17:05:17.624][DONE][CLIENT][ERROR] botania.zs:19:83 Cannot cast MCBlockState to IData, even explicitly
[17:05:17.624][DONE][CLIENT][ERROR] Scripts are invalid!

#### What you expected to happen:

the script to run and change or add a recipe to the targeted item

#### Script used (Please pastebin.com or gist.github.com your script, posting an unpasted or ungist'd script will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file):
https://gist.github.com/raziel23x/e8a14756b608b7c19449202068e72680

#### crafttweaker.log file (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.):
https://gist.github.com/raziel23x/ac6662037c3833c5623bd2c5e554e476

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.16.3
- Forge: 34.1.42
- Crafttweaker:  CraftTweaker-1.16.3-7.0.0.48
- Using a server: NO
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.):
https://gist.github.com/raziel23x/3b64a4ad6f3b4ba15beb768a5c53d8f1

**Comment by Hubry** [comment]
Going to post what I said in the CT discord after seeing this:
There is no real standard format of blockstate -> json. 
The closest thing is doing blockstate -> nbt --(converting with DFU)-> json, like
```java
		Dynamic<INBT> dyn = new Dynamic<>(NBTDynamicOps.INSTANCE, nbt);
		return dyn.convert(JsonOps.INSTANCE).getValue().getAsJsonObject();
```
and we don't even do that exactly, we rename the tags to lowercase on writing to json for consistency, as pictured [here](https://github.com/Vazkii/Botania/blob/62ff10ddca0c6fcf79355daf3e52c7a0dbaefb9e/src/main/java/vazkii/botania/common/crafting/StateIngredientHelper.java#L97-L118).
One proper way would be providing CT support, but idk if we are exactly interested in this (though it might be needed for things like the orechid...).

What is absolutely necessary though is exposing the registry name on the block so writing a good wrapper function is possible at all (I think we can turn the properties into a proper map automatically already? If no, then that would be needed too.)

**Comment by jaredlll08** [comment]
> One proper way would be providing CT support, but idk if we are exactly interested in this (though it might be needed for things like the orechid...). 

What are your issues with this?

**Comment by Hubry** [comment]
It's one more dependency to wait on during porting, and there isn't too much gain if a system like this already exists - I personally don't have much issue adding it, but I am not the decisionmaker for Botania :P 
That said, editing our recipes is a recurring topic so maybe it's worth actually looking into proper support.

**Comment by jaredlll08** [comment]
Oh, I was more asking if you had any objections to CraftTweaker support for Botania, I'm probably going to put it into a modtweaker type mod like it was in 1.12, you shouldn't need to add support yourself

**Comment by jaredlll08** [comment]
The gist files are gone and for what it's worth Botania has build in support now, so no need to mess with addJSONRecipe.

If anyone else can give me updated logs of this error still occurring we can relook at it
