### ISSUE TITLE
[1.16.4] cannot create tags

### ISSUE THREAD

**Issue by friendlyhj** [CraftTweaker/CraftTweaker#1104]
#### Intro:
Cannot create tags

#### What you expected to happen:
Can create tags

#### Script used (Please pastebin.com or gist.github.com your script, posting an unpasted or ungist'd script will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file):
```zenscript
<tag:crafttweaker:test>.createItemTag().addItems(<item:minecraft:chest>);
```

#### crafttweaker.log file (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.):
https://paste.ubuntu.com/p/W3HDWQgYth/

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.16.4
- Forge: 35.0.2
- Crafttweaker: 7.0.0.55
- Using a server: no

**Comment by drakray** [comment]
Got the same trouble with CT 7.0.0.59 and Forge 35.0.17

**Comment by jaredlll08** [comment]
It is a known issue, tags need to be reworked but I haven't had the time

**Comment by drakray** [comment]
Ok no problem, I mainly posted to get the notif and say that more recent version have it, it's not magically fixed lol
Take your time, stay healthy, your work is very important for PackMaker ;)

**Comment by TheFieryFalcon** [comment]
I have the same problem

**Comment by jaredlll08** [comment]
Make a new github issue so we can investigate your specific issue
