### ISSUE TITLE
Error executing {[0:crafttweaker]: gregtech.zs}: null

### ISSUE THREAD

**Issue by Tranquanto** [CraftTweaker/CraftTweaker#1105]
#463 ## Issue Description:
I was trying to remove the packer and compressor recipes for the Ultimate Ingot from Extended Crafting but I get an error that simply says: Error executing {[0:crafttweaker]: gregtech.zs}: null

#### What happens:

I get an error on the script gregtech.zs and the recipes aren't removed.

#### What you expected to happen:

I tried to make the packer and compressor recipes for the Ultimate Ingot from Extended Crafting remove.

#### Script used (Please pastebin.com or gist.github.com your script, posting an unpasted or ungist'd script will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file):

https://pastebin.com/MbJ1ttzv

#### crafttweaker.log file (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.):

https://pastebin.com/8jg5Kwpb
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: forge-14.23.5.2854
- Crafttweaker: CraftTweaker2-1.12-4.1.20.586
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.):

https://pastebin.com/8jg5Kwpb

**Comment by kindlich** [comment]
This is not an error in CraftTweaker, but in your script:
```
java.lang.NullPointerException
	at Gregtech.__script__(gregtech.zs:6)
```

This means that in Line 6 of gregtech.zs you tried to call a method on a `null` value.
In your context it means most likely that the recipe was not found (`.findRecipe(...)` returned null ) and therefore your call to `.remove()` errors.

**Comment by Dragon77mathbye** [comment]
I don't know what "long voltage" is either

https://docs.blamejared.com/1.12/en/Mods/GregTechCE/Machines#removing

**Comment by Tranquanto** [comment]
Ok, thanks! I'll see if I can fix my errors
