### ISSUE TITLE
hard to identify 1.12 crash

### ISSUE THREAD

**Issue by Timberlystumcain** [CraftTweaker/CraftTweaker#1107]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Crash on step 6/7, unable to identify problem

#### Script used

irrelevant, crashes identically even with no scripts, but will provide if necessary

#### crafttweaker.log file

https://pastebin.com/T021zV87

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Crafttweaker: CraftTweaker2-1.12-4.1.20.601
- Using a server: no

#### Your most recent log file where the issue was present 

https://gist.github.com/Timberlystumcain/7020b247f8027102854dc7fe8d3cf15f

**Comment by kindlich** [comment]
```
[INITIALIZATION][CLIENT][ERROR] oredict\cavesncliffs.zs:2: Could not resolve <caves_and_cliffs : copper_ore>
[INITIALIZATION][CLIENT][ERROR] oredict\cavesncliffs.zs:5: Could not resolve <caves_and_cliffs : copper_ingot>
[INITIALIZATION][CLIENT][ERROR] oredict\cavesncliffs.zs:8: Could not resolve <caves_and_cliffs : copper_block>
[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: oredict\cavesncliffs.zs}: null
```

It tells you that it cannot find these bracket handlers.
`oredict\cavesncliffs.zs:2`, file `cavesncliffs.zs` in folder `scripts/oredict`, line 2.
Make sure these items exist with the same name as they have in the game. Use `/ct hand` to get the proper name.

You can also use `/ct syntax` to validate your syntax without needing to restart the game.

**Comment by Timberlystumcain** [comment]
that's not the issue unfortunately. I just made sure and removed all scripts that error in the startup [crafttweaker.log](https://gist.github.com/Timberlystumcain/cb3c8eda3bf30e45a0036d965aea768c)

The game crashes on startup at the "finishing up" step. [this is my latest crash .txt](https://gist.github.com/Timberlystumcain/470429b2b4924793effa7c180680c10d) and [this is my latest latest.log](https://gist.github.com/Timberlystumcain/f1c61950dccf1931abcc75dea5381d4c)

**Comment by kindlich** [comment]
CraftTweaker will instruct Minecraft to recalculate its search trees after it's done.
The search trees are what is used by e.g. the recipe book in the crafting table.
Somewhere in there it errors apparently.

I'll look into it

**Comment by Timberlystumcain** [comment]
Huh.. I found that just removing FutureMC is enough to make the game boot normally. I did have a script for it, but even after removing it it still crashes.. What's especially weird to me is that I've had both CT and F MC installed for ages without updating without any problems, so I imagine it's some interaction with another mod

**Comment by fizykz** [comment]
I had the same error, tried to recreate it by taking out mods we had in common, nothing seemed to work.  Had a clean install with the same mods, excluding ItemPhysics, its library, and BedPatch, and it did work, at least until I added ItemPhysics and the library.  So that's my guess at the culprit.  Good luck!

**Comment by jaredlll08** [comment]
This was closed in https://github.com/CraftTweaker/CraftTweaker/pull/1108

You can use `#disable_search_tree` in your script and that should help
