### ISSUE TITLE
Truncated class file

### ISSUE THREAD

**Issue by hamelech2007** [CraftTweaker/CraftTweaker#1110]
**Intro:**
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

**Issue Description:**
I created a class in my scripts folder named "mystical agriculture.zs" and put my script there. When I try loading the script it gives me an error. I am very **very** new to crafttweaker and modpacks so it would probably be just a dumb issue.

**What happens:**
I get a "Java.lang.ClassFormatError: Truncated Class File" error and the script won't run.

**What you expected to happen:**
Well, I expected it to execute and do whatever it should do as stated in the code....

**Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):**
https://pastebin.com/UkkM3wKS

**Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):**
https://pastebin.com/83r9BVe6

**Affected Versions (Do not use "latest"):**
Minecraft: 1.12.2
Forge: 14.23.5.2847
Crafttweaker: 1.12-4.1.20.594
**Your most recent log file where the issue was present:**
https://pastebin.com/Qx8cWHRU

**Comment by kindlich** [comment]
Use `var seeds = [...] as IItemStack[];`

The cast for arrays can be important

**Comment by hamelech2007** [comment]
Thank you so much! It worked!
