### ISSUE TITLE
[Question] Is the GUI feature still implemented?

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#1119]
So i've got a question!
I viewed an old 2016 issue #5
And it seems it was implemented in 1.10
Has the GUI it been extended upon or is it still implemented`?

**Comment by jaredlll08** [comment]
It is implemented in 1.12, but it isn't being ported to newer versions.

Honestly just learn the language, it isn't that hard, and the gui is broken and buggy sometimes
