### ISSUE TITLE
[1.12.2] Some mod items are not hidden from JEI when staged

### ISSUE THREAD

**Issue by jorgebonafe** [CraftTweaker/CraftTweaker#1123]
**Intro:**
Some mod items are not hidden from JEI when staged

**Description:**

I'm trying to extend SevTech Ages and add OpenComputers to it. I created a stage and added all OC items to that stage. But some of the items (the floppy disks) are not hidden.

![image](https://user-images.githubusercontent.com/1023068/101982435-abaa9480-3c52-11eb-9142-5c88e71752d3.png)

This is my Script: [https://pastebin.com/1s6sp1BN](https://pastebin.com/1s6sp1BN).

The items in question are on lines 102 to 112 in the script. They all have tags, but I don't think that is necessarily the issue, because all of the other items with tags are correctly hidden. Also, when I try to not stage these items, they dont't show as "Unfamiliar Items", so the script is clearly doing something.

I also tried a simpler script just calling **mods.ItemStages.stageModItems(stage_name, modid);** to stage all OC items, and that also had the same result, hiding all OC items except for the same floppy disks.

**crafttweaker.log file:** [https://gist.github.com/jorgebonafe/50727874db0ae7b787afedfc35227857](https://gist.github.com/jorgebonafe/50727874db0ae7b787afedfc35227857)

**Affected Versions:**

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Crafttweaker: 1.12-4.1.20.574
- Jei: 1.12.2-4.15.0.283
- Using a server: No
- SevTech Ages pack version: 3.2.1

Most recent Minecraft log: [https://gist.github.com/jorgebonafe/f031ab12d6187bf9829dd159f9bd8898](https://gist.github.com/jorgebonafe/f031ab12d6187bf9829dd159f9bd8898)

**Comment by jaredlll08** [comment]
We don't help people change other people's modpacks.

**Comment by jorgebonafe** [comment]
> We don't help people change other people's modpacks.

It's for private use, and I have permission from the mod pack author. Why is that a problem?

**Comment by jaredlll08** [comment]
We don't help people change other's packs because 9 out of 10 times people don't actually know what they're doing, and combining that with whatever environment the pack author has setup (which in sevtech and skyfactory, if you don't know what you're doing, you aren't going to get very far).

Anyway, your issue isn't even with CraftTweaker, as you said the script is loading fine, it would be an issue for ItemStages / JEI.

**Comment by jorgebonafe** [comment]
I see. Thanks in any case.
