### ISSUE TITLE
MFR

### ISSUE THREAD

**Issue by byDopeMan** [CraftTweaker/CraftTweaker#1125]
So im playing on 1.12.2 and i want that the Mystical Agriculture seeds can be planted with the MFR Planter and harvested with the MFR Harvester so is there any support for this?

**Comment by jaredlll08** [comment]
Is minefactory reloaded even on 1.12?

Regardless we aren't adding any more mod support in 1.12.

**Comment by byDopeMan** [comment]
Yeah im playing on 1.12.2 https://github.com/skyboy/MineFactoryReloaded/issues/709
