### ISSUE TITLE
Compiling scripts can cause a NPE

### ISSUE THREAD

**Issue by Charnuz** [CraftTweaker/CraftTweaker#1126]
#### Issue Description:
This could be a ZenScript issue, but it might be an issue with how scripts are loaded. Using a ZenSetter on an event passed to a function causes it, but not the ZenGetter.

#### What happens:
Script throws a NPE on execution and fails, but cannot be caused by the script. Tested with only CT installed too.

[Script](https://pastebin.com/3EFzcSZ5)
[Log](https://pastebin.com/fUuAJAkC)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Crafttweaker: 1.12-4.1.20.586
- Using a server: No

**Comment by friendlyhj** [comment]
There is not a ZenSetter of `maxHealth`

**Comment by jaredlll08** [comment]
As friendly said, there is no zensetter for maxHealth

**Comment by Charnuz** [comment]
Shouldn't it have the 'No such member' error instead of this though?

**Comment by jaredlll08** [comment]
@kindlich can give more insight, but the member exists (in the form of a getter, not a setter), just not for what you want to use it for

**Comment by Charnuz** [comment]
Ah I see, the NPE does make debugging harder since it doesn't have any relevant info
