### ISSUE TITLE
[1.15.2] Using .reuse() in CT recipes causes items to duplicate

### ISSUE THREAD

**Issue by 04Slash** [CraftTweaker/CraftTweaker#1128]
#### Issue Description:
If you make a crafting table recipe with some items having .reuse() on them then it will cause these items to duplicate themselves when crafting with said item. The .reuse() items must have at least 2 items in the stack for this to happen. I have verified that these are not just ghost items. 

#### What happens:
https://imgur.com/a/bhlxk6z

#### What you expected to happen:
I expect the stacked .reuse() items to stay at the same value, not duplicate until they poof.

#### Script used (Please pastebin.com or gist.github.com your script, posting an unpasted or ungist'd script will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file):
https://pastebin.com/ai2r2x2D No other scripts are present.

#### crafttweaker.log file (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.):
https://pastebin.com/sJEuJ6s9

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.15.2
- Forge: 31.2.47
- Crafttweaker: CraftTweaker-1.15.2-6.0.0.45
- Using a server: Nope.
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.):

https://pastebin.com/kUND66GJ

This bug also happens in 1.16.4, using the exact same script.
- Forge: 35.1.13
- Crafttweaker: CraftTweaker-1.16.4-7.0.0.63

**Comment by kindlich** [comment]
Item transformers are usually meant for items with a stack size of 1.
Though i can have a look if that's something we can change easily.

**Comment by 04Slash** [comment]
Maybe this is the wrong place to ask but what would be the intended method to craft with a stackable item where said item doesn't get consumed? I'm not looking for any in depth explanation, just wondering what I should be using.

**Comment by jaredlll08** [comment]
There isn't strictly a correct way to make stackable items not be consumed, all vanilla recipes that have non consuming items only use non stacking items.

I've pushed a fix that should work, will have to see if we get any reports of it breaking, but it would be better than the dupe that was happening before.
