### ISSUE TITLE
Recipes still exists after reversing fields

### ISSUE THREAD

**Issue by NeutronSelector** [CraftTweaker/CraftTweaker#1129]
#### Resum:
Cannot delete recipe with containing armor or tool in induction smelter (of thermal expansion)
It does it for all craft with a piece of armor, a tool, or a weapon.

#### Message in game:
![image](https://user-images.githubusercontent.com/32287303/102553189-c5206600-40c2-11eb-950d-663a32e786ab.png)

#### ZS script:
```java
mods.thermalexpansion.InductionSmelter.removeRecipe(<minecraft:sand>, <minecraft:iron_helmet>);
mods.thermalexpansion.InductionSmelter.removeRecipe(<minecraft:sand>, <minecraft:iron_chestplate>);
```
I try to revert order argument like this, same message
```java
mods.thermalexpansion.InductionSmelter.removeRecipe(<minecraft:iron_helmet>, <minecraft:sand>);
mods.thermalexpansion.InductionSmelter.removeRecipe(<minecraft:iron_chestplate>, <minecraft:sand>);
```

#### CraftTweaker log
[crafttweaker.log](https://github.com/CraftTweaker/CraftTweaker/files/5712594/crafttweaker.log)
____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Crafttweaker: 2-1.12-4.1.20.586
- Using a server: No

**Comment by jaredlll08** [comment]
Firstly, this isn't an issue for Crafttweaker, it would be an issue for Modtweaker.

Secondly the error is saying that it tried to remove the recipe you provided, and the reverse of the arguments and no recipe was removed.

This basically means that your recipe is wrong / can't be removed with Modtweaker

**Comment by NeutronSelector** [comment]
OK thanks for your answer. And sorry to have posted under CraftTweaker and not ModTweaker
