### ISSUE TITLE
ERROR: [crafttweaker : SIDE_CLIENT]

### ISSUE THREAD

**Issue by TheCoolOof** [CraftTweaker/CraftTweaker#1131]
This is the error I'm having:

https://gyazo.com/0f226241f7aa750b0625ae3450e87d6b

This is the script:

https://pastebin.com/FbApVs9t

I have gone through the script but I don't understand how to fix it. If anyone can help that would be great. 

Thanks,

**Comment by democat3457** [comment]
you have a period after `null` on line 67:
`..., [<mysticalagriculture:crafting:33>, null. <mysticalagriculture:gear:5>], `

**Comment by TheCoolOof** [comment]
I didn’t even notice it was a period. Thank you
