### ISSUE TITLE
item transform/getBack stack compatibility

### ISSUE THREAD

**Issue by DunkleDoug** [CraftTweaker/CraftTweaker#1137]
**Feature request name**
item transform stack/getBack compatibility

**Feature request description**
please make it so item transforms work with stackable items

**Feature request reason**
I'm working on a project and i need to be able to craft multiple different kinds of items from one recipe. giveBack should work for this but whatever item gets that tag in the recipe just has the entire stack eaten at once, it's a real pain.

**Feature request dependencies**
for my purposes it's just going to be used with custom items from flans mod, but as far as i can guess there shouldn't be any mod dependencies involved in making this work

**Game Version**
apparently this actually works in 1.7.10 already, but i'd like this to be implemented on 1.12 specifically.

**Comment by kindlich** [comment]
TransformReplace should work.
giveBack is deprecated, as it uses an old API, that has many edge cases.

**Comment by kindlich** [comment]
Going to close this due to inactivity, please respond if this is still an issue and I will reopen it
