### ISSUE TITLE
Error Parsing MysticalAgriculture.zs:178 --] or , expected

### ISSUE THREAD

**Issue by Triple45** [CraftTweaker/CraftTweaker#1138]
Intro:
Creating a pack and error happens that i cannot see what is wrong

Issue Description:
Im making a modpack for me and my friends, and error pops up that i cannot see what is wrong

What happens:
"Error Parsing MysticalAgriculture.zs:178 --] or , expected" I have no clue what is wrong with this i need some other eyes on this.

What you expected to happen:
add recipes to astral sorcery altar to mystical agriculture seeds

Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/susVSC6d

crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/TneUaHWh

Affected Versions (Do not use "latest"):
1.12.2 forge-14.23.5.2854

**Comment by friendlyhj** [comment]
line 168 - 175
```zenscript
mods.astralsorcery.Altar.addConstellationAltarRecipe("triplepack:shaped/internal/altar/fluix_seeds",
	<mysticalagriculture:fluix_seeds>, 600, 200, 
	[<mysticalagriculture:crafting:44>, <ore:blockSuperiumEssence>, <mysticalagriculture:crafting:44>,
	<ore:blockSuperiumEssence>, <mysticalagriculture:crafting:20>, <ore:blockSuperiumEssence>, 
	<mysticalagriculture:crafting:44>, <ore:blockSuperiumEssence>, <mysticalagriculture:crafting:44>,
 
	<appliedenergistics2:fluix_stairs>, <appliedenergistics2:fluix_stairs>, <appliedenergistics2:fluix_stairs>, <appliedenergistics2:fluix_stairs>, 
	<mysticalagriculture:crafting:44>, <mysticalagriculture:crafting:44>, <mysticalagriculture:crafting:44>, <mysticalagriculture:crafting:44>,  // <---- you put an extra comma, it should be ]);
```

**Comment by Triple45** [comment]
Darn, didnt even notice i replaced a line with thin air. Oh well. Problem solved. Thanks.
