### ISSUE TITLE
1.12.2 Crashing on Startup (whether Scripts are present or not)

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#1147]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformLoader (DynamicSurroundings-1.12.2-3.6.2.1.jar)
  AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.42_mc1.12.2.jar)
  LevelUpCore (levelup2-1.5.7.jar)
  EC Core Plugin (enchcontrol-1.12.2-1.1.5-0.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.2-core.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.11-1.12.2 (1).jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.2.0.3.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  LoadingPlugin (Reskillable-1.12.2-1.13.0.jar)
  FutureMC (future-mc-1.12.2-0.2.4.1.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  midnight (themidnight-0.3.5.jar)
  Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
  WolfArmorCore (wolfarmor-1.12.2-3.7.5-universal-signed.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  TickCentral (TickCentral-2.6.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

**Time: 1/27/21 4:27 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
Caused by: java.lang.NullPointerException
	at net.minecraft.client.util.SearchTree.func_194039_a(SourceFile:48)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:48)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.reloadSearchTrees(FMLClientHandler.java:1086)
	at net.minecraftforge.fml.common.FMLCommonHandler.reloadSearchTrees(FMLCommonHandler.java:778)
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:589)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:916)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:259)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)**

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_242, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), 
	Memory: 1151779616 bytes (1098 MB) / 2661285888 bytes (2538 MB) up to 5249695744 bytes (5006 MB)
	JVM Flags: 4 total; -Xmx5632m -Xms5632m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_F5 151 mods loaded, 151 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                  | Version                  | Source                                             | Signature                                |
	|:------- |:------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA  | minecraft           | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCHIJA  | mcp                 | 9.42                     | minecraft.jar                                      | None                                     |
	| LCHIJA  | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJAE | forge               | 14.23.5.2855             | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA  | creativecoredummy   | 1.0.0                    | minecraft.jar                                      | None                                     |
	| LCHIJA  | ivtoolkit           | 1.3.3-1.12               | minecraft.jar                                      | None                                     |
	| LCHIJA  | foamfixcore         | 7.7.4                    | minecraft.jar                                      | None                                     |
	| LCHIJA  | obfuscate           | 0.4.2                    | minecraft.jar                                      | None                                     |
	| LCHIJA  | tickcentral         | 2.6                      | TickCentral-2.6.jar                                | None                                     |
	| LCHIJA  | randompatches       | 1.12.2-1.22.1.10         | randompatches-1.12.2-1.22.1.10.jar                 | None                                     |
	| LCHIJA  | bspkrscore          | 7.6.0.1                  | [1.12]bspkrsCore-universal-7.6.0.1.jar             | None                                     |
	| LCHIJA  | aiimprovements      | 0.0.1.3                  | AIImprovements-1.12-0.0.1b3.jar                    | None                                     |
	| LCHIJA  | alcatrazcore        | 1.0.4                    | alcatrazcore-1.0.4.jar                             | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCHIJA  | biomesoplenty       | 7.0.1.2444               | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar      | None                                     |
	| LCHIJA  | craftstudioapi      | 1.0.0                    | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCHIJA  | animania            | 2.0.2.26                 | animania-1.12.2-base-2.0.2.26.jar                  | None                                     |
	| LCHIJA  | antiqueatlas        | 4.5.1                    | antiqueatlas-1.12.2-4.5.1.jar                      | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA  | antiqueatlasoverlay | 1.2                      | antiqueatlas-1.12.2-4.5.1.jar                      | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA  | applecore           | 3.4.0                    | AppleCore-mc1.12.2-3.4.0.jar                       | None                                     |
	| LCHIJA  | sereneseasons       | 1.2.18                   | SereneSeasons-1.12.2-1.2.18-universal.jar          | None                                     |
	| LCHIJA  | orelib              | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA  | dsurround           | 3.6.2.1                  | DynamicSurroundings-1.12.2-3.6.2.1.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA  | embassy             | 5.0.0                    | Embassy_5.0-b20.jar                                | None                                     |
	| LCHIJA  | jei                 | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                          | None                                     |
	| LCHIJA  | appleskin           | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                        | None                                     |
	| LCHIJA  | carrots             | 1.0.0b1                  | carrotslib-mc1.12.2-1.0.0b1.jar                    | None                                     |
	| LCHIJA  | armorunder          | 1.0.0                    | armorunder-mc1.12.2-1.0.0.jar                      | None                                     |
	| LCHIJA  | autoreglib          | 1.3-32                   | AutoRegLib-1.3-32.jar                              | None                                     |
	| LCHIJA  | bacodifficulty      | 1.0.3                    | BacoDifficulty-1.0.3.jar                           | None                                     |
	| LCHIJA  | crafttweaker        | 4.1.20                   | CraftTweaker2-1.12-4.1.20.614.jar                  | None                                     |
	| LCHIJA  | base                | 3.13.0                   | base-1.12.2-3.13.0.jar                             | None                                     |
	| LCHIJA  | battletowers        | 1.6.5                    | BattleTowers-1.12.2.jar                            | None                                     |
	| LCHIJA  | baubles             | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCHIJA  | bettercaves         | 1.12.2                   | bettercaves-1.12.2-2.0.4.jar                       | None                                     |
	| LCHIJA  | bettercompass       | 1.5.0                    | bettercompass-1.12.2-1.5.0.jar                     | None                                     |
	| LCHIJA  | bettermineshafts    | 1.12.2-2.1.1             | BetterMineshaftsForge-1.12.2-2.1.1.jar             | None                                     |
	| LCHIJA  | betterpingdisplay   | 1.0                      | BetterPingDisplay-1.12.2-1.0.jar                   | None                                     |
	| LCHIJA  | bibliocraft         | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| LCHIJA  | blockdropstweaker   | 2.4                      | BlockDropsTweaker-1.12.2-2.4.jar                   | None                                     |
	| LCHIJA  | bloodmoon           | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                       | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA  | blur                | 1.0.4-14                 | Blur-1.0.4-14.jar                                  | None                                     |
	| LCHIJA  | bookshelf           | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA  | bookworm            | 1.12.2-2.5.2.1           | bookworm-1.12.2-2.5.2.1.jar                        | None                                     |
	| LCHIJA  | forgelin            | 1.8.4                    | Forgelin-1.8.4.jar                                 | None                                     |
	| LCHIJA  | bountiful           | 2.2.2                    | Bountiful-2.2.2.jar                                | None                                     |
	| LCHIJA  | campfire            | 1.2                      | campfire-1.12-v1.2.jar                             | None                                     |
	| LCHIJA  | carryon             | 1.12.3                   | carryon-1.12.2-1.12.3.15.jar                       | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LCHIJA  | chiselsandbits      | 14.33                    | chiselsandbits-14.33.jar                           | None                                     |
	| LCHIJA  | chunkpregenerator   | 2.1                      | Chunk Pregenerator V1.12-2.3.jar                   | None                                     |
	| LCHIJA  | chunkanimator       | 1.2                      | ChunkAnimator-MC1.12-1.2.jar                       | None                                     |
	| LCHIJA  | clienttweaks        | 3.1.11                   | ClientTweaks_1.12.2-3.1.11.jar                     | None                                     |
	| LCHIJA  | clumps              | 3.1.2                    | Clumps-3.1.2.jar                                   | None                                     |
	| LCHIJA  | colytra             | 1.2.0.3                  | colytra-1.12.2-1.2.0.3.jar                         | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA  | toughasnails        | 3.1.0.139                | ToughAsNails-1.12.2-3.1.0.139-universal.jar        | None                                     |
	| LCHIJA  | comforts            | 1.4.1.2                  | comforts-1.12.2-1.4.1.2.jar                        | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA  | reskillable         | 1.12.2-1.13.0            | Reskillable-1.12.2-1.13.0.jar                      | None                                     |
	| LCHIJA  | compatskills        | 1.12.2-1.17.0            | CompatSkills-1.12.2-1.17.0.jar                     | None                                     |
	| LCHIJA  | complexcrops        | v4.2.0                   | Complex+Crops+1.12.2-4.2.0.jar                     | None                                     |
	| LCHIJA  | controlling         | 3.0.10                   | Controlling-3.0.10.jar                             | None                                     |
	| LCHIJA  | ctgui               | 1.0.0                    | CraftTweaker2-1.12-4.1.20.614.jar                  | None                                     |
	| LCHIJA  | crafttweakerjei     | 2.0.3                    | CraftTweaker2-1.12-4.1.20.614.jar                  | None                                     |
	| LCHIJA  | creativecore        | 1.10.0                   | CreativeCore_v1.10.42_mc1.12.2.jar                 | None                                     |
	| LCHIJA  | custommainmenu      | 2.0.9.1                  | CustomMainMenu-MC1.12.2-2.0.9.1.jar                | None                                     |
	| LCHIJA  | darknesslib         | 1.1.0                    | DarknessLib-1.12.2-1.1.0.jar                       | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA  | deathcounter        | 1.1.0                    | DeathCounter-1.12.2-1.1.0.jar                      | None                                     |
	| LCHIJA  | ding                | 1.0.2                    | Ding-1.12.2-1.0.2.jar                              | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA  | dldungeonsjbg       | 1.13.2                   | DoomlikeDungeons-1.13.2-MC1.12.2.jar               | None                                     |
	| LCHIJA  | reccomplex          | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                       | None                                     |
	| LCHIJA  | dynamictrees        | 1.12.2-0.9.14            | DynamicTrees-1.12.2-0.9.14.jar                     | None                                     |
	| LCHIJA  | dynamictreesbop     | 1.12.2-1.4.2             | DynamicTreesBOP-1.12.2-1.4.2.jar                   | None                                     |
	| LCHIJA  | csb_ench_table      | 1.1.3                    | EnchantingTable-1.12-1.1.3.jar                     | None                                     |
	| LCHIJA  | enchdesc            | 1.1.15                   | EnchantmentDescriptions-1.12.2-1.1.15.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA  | enchcontrol         | 1.1.5                    | enchcontrol-1.12.2-1.1.5-0.jar                     | 503a793335572ddd78512349bd8048f536a62fdb |
	| LCHIJA  | endreborn           | 0.3.8                    | EndReborn [0.3.9].jar                              | None                                     |
	| LCHIJA  | enhancedvisuals     | 1.3.0                    | EnhancedVisuals_v1.3.22_mc1.12.2.jar               | None                                     |
	| LCHIJA  | erebus              | 1.0.31                   | Erebus-1.0.31.jar                                  | None                                     |
	| LCHIJA  | exp_bottling        | 1.12.2-1                 | exp_bottling-1.12.2-3.jar                          | None                                     |
	| LCHIJA  | fairylights         | 2.1.10                   | fairylights-2.2.0-1.12.2.jar                       | None                                     |
	| LCHIJA  | fastfurnace         | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                       | None                                     |
	| LCHIJA  | fastbench           | 1.7.3                    | FastWorkbench-1.12.2-1.7.3.jar                     | None                                     |
	| LCHIJA  | findme              | 1.1.0                    | findme-1.12.2-1.1.0-8.jar                          | None                                     |
	| LCHIJA  | firstaid            | 1.6.15                   | firstaid-1.6.15.jar                                | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCHIJA  | mod_lavacow         | 1.2.1                    | Fish's Undead Rising-1.2.1.jar                     | None                                     |
	| LCHIJA  | foamfix             | 0.10.11-1.12.2           | foamfix-0.10.11-1.12.2 (1).jar                     | None                                     |
	| LCHIJA  | foodtweaker         | 1.1.3                    | FoodTweaker-1.1.3.jar                              | None                                     |
	| LCHIJA  | cfm                 | 6.3.1                    | furniture-6.3.1-1.12.2.jar                         | None                                     |
	| LCHIJA  | futuremc            | 0.2.4.1                  | future-mc-1.12.2-0.2.4.1.jar                       | None                                     |
	| LCHIJA  | fxcontrol           | 0.1.14                   | fxcontrol-1.12-0.1.15.jar                          | None                                     |
	| LCHIJA  | globalgamerules     | 2.2                      | GlobalGameRules-1.12.2-2.2.7.jar                   | None                                     |
	| LCHIJA  | grapplemod          | 1.12.2-v11.1             | grapplemod-v11.1-1.12.2.jar                        | None                                     |
	| LCHIJA  | guiclock            | 1.3                      | guiclock_1.12-1.3.jar                              | None                                     |
	| LCHIJA  | hardcoredarkness    | 2.0                      | HardcoreDarkness-MC1.12.2-2.0.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA  | hardcorerevival     | 1.2.0                    | HardcoreRevival_1.12.2-1.2.0.jar                   | None                                     |
	| LCHIJA  | llibrary            | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA  | iceandfire          | 1.9.1                    | iceandfire-1.9.1-1.12.2.jar                        | None                                     |
	| LCHIJA  | ido                 | 2.0.0-B                  | ido-1.12.2-2.0.0-B.jar                             | None                                     |
	| LCHIJA  | improvedbackpacks   | 1.12.2-1.5.0.0           | ImprovedBackpacks-1.12.2-1.5.0.0.jar               | None                                     |
	| LCHIJA  | incontrol           | 3.9.16                   | incontrol-1.12-3.9.17.jar                          | None                                     |
	| LCHIJA  | infernalmobs        | 1.7.6                    | InfernalMobs-1.12.1.jar                            | None                                     |
	| LCHIJA  | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA  | letmesleep          | 1.2.1                    | LetMeSleep-v1.2.1-1.12.2.jar                       | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
	| LCHIJA  | dogslie             | 1.0.2                    | LetSleepingDogsLie-1.12.2-1.0.2.jar                | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA  | levelup2            | ${version}               | levelup2-1.5.7.jar                                 | None                                     |
	| LCHIJA  | libraryex           | 1.1.3                    | LibraryEx-1.12.2-1.1.3.jar                         | None                                     |
	| LCHIJA  | loottweaker         | 0.2.0                    | LootTweaker-0.2.0+MC1.12.2.jar                     | None                                     |
	| LCHIJA  | mcwbridges          | 1.0.4                    | mcw-bridges-1.0.4-mc1.12.2.jar                     | None                                     |
	| LCHIJA  | mtrm                | 1.2.2.30                 | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar         | None                                     |
	| LCHIJA  | mobends             | 1.0.0-beta-20.06.20      | MoBends_1.12.2-1.0.0-beta-20.06.20.jar             | None                                     |
	| LCHIJA  | mowziesmobs         | 1.5.8                    | mowziesmobs-1.5.8.jar                              | None                                     |
	| LCHIJA  | multimine           | 1.6.2                    | MultiMine-1.12.2.jar                               | None                                     |
	| LCHIJA  | multimob            | 1.0.5                    | multimob-1.0.5.jar                                 | None                                     |
	| LCHIJA  | naturescompass      | 1.8.5                    | NaturesCompass-1.12.2-1.8.5.jar                    | None                                     |
	| LCHIJA  | neat                | 1.4-17                   | Neat 1.4-17.jar                                    | None                                     |
	| LCHIJA  | netherex            | 2.1.8                    | NetherEx-1.12.2-2.1.8.jar                          | None                                     |
	| LCHIJA  | notreepunching      | 2.0.21                   | notreepunching-2.0.21.jar                          | None                                     |
	| LCHIJA  | oretweaker          | 1.0.2-1.12.0             | Ore Tweaker-1.0.2-1.12.0.jar                       | None                                     |
	| LCHIJA  | potionfingers       | r1.0-8                   | PotionFingers-r1.0-8.jar                           | None                                     |
	| LCHIJA  | pumpkincarving      | 1.4.0                    | PumpkinCarving1.12-1.4.0.jar                       | None                                     |
	| LCHIJA  | randomportals       | 1.12.2-1.8.2.3           | randomportals-1.12.2-1.8.2.3.jar                   | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
	| LCHIJA  | removehudbutnothand | 1.12.2-2.0.1.0           | RemoveHudButNotHand-1.12.2-2.0.1.0.jar             | None                                     |
	| LCHIJA  | resourceloader      | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA  | roguelike           | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
	| LCHIJA  | roughmobs           | 2.0.0                    | roughmobs2-1.12.2_2.0.15.jar                       | None                                     |
	| LCHIJA  | ruins               | 17.2                     | Ruins-1.12.2.jar                                   | None                                     |
	| LCHIJA  | silentlib           | 3.0.13                   | SilentLib-1.12.2-3.0.14+168.jar                    | None                                     |
	| LCHIJA  | scalinghealth       | 1.3.37                   | ScalingHealth-1.12.2-1.3.42+147.jar                | None                                     |
	| LCHIJA  | shieldhider         | 1.2.0                    | ShieldHider-1.2.0_1.12.jar                         | None                                     |
	| LCHIJA  | snowaccumulation    | 1.0.0                    | SnowAccumulation-1.12-1.0.0.jar                    | None                                     |
	| LCHIJA  | soundfilters        | 0.12.1_for_1.12          | SoundFilters-0.12.1_for_1.12.jar                   | None                                     |
	| LCHIJA  | spartanshields      | 1.5.4                    | SpartanShields-1.12.2-1.5.4.jar                    | None                                     |
	| LCHIJA  | spartanweaponry     | beta 1.3.8               | SpartanWeaponry-1.12.2-beta-1.3.8.jar              | None                                     |
	| LCHIJA  | spawnercontrol      | 1.6.3b                   | SpawnerControl-1.6.3b.jar                          | None                                     |
	| LCHIJA  | specialai           | 1.1.0_for_mc1.12.2       | specialai-1.1.0_for_mc1.12.2.jar                   | None                                     |
	| LCHIJA  | spiceoflife         | 1.3.12                   | SpiceOfLife-mc1.12-1.3.12.jar                      | None                                     |
	| LCHIJA  | stg                 | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                               | None                                     |
	| LCHIJA  | stygian             | 1.0.4                    | stygian-1.0.4.jar                                  | None                                     |
	| LCHIJA  | surge               | 2.0.77                   | Surge-1.12.2-2.0.77.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA  | beneath             | 1.7.0                    | The Beneath-1.12.2-1.7.0.jar                       | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA  | xat                 | 0.30                     | Trinkets and Baubles-0.30.1.jar                    | None                                     |
	| LCHIJA  | unloader            | 1.2.0                    | unloader-1.2.0.jar                                 | None                                     |
	| LCHIJA  | gvc                 | 1.2.0                    | Voice+Chat+Reloaded-1.2.4.jar                      | None                                     |
	| LCHIJA  | waystones           | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                         | None                                     |
	| LCHIJA  | wolfarmor           | 3.7.5                    | wolfarmor-1.12.2-3.7.5-universal-signed.jar        | e94e38a605842477f3ec218e6fcf781f6b3f7f89 |
	| LCHIJA  | xpfromharvest       | 1.1.0                    | xpfromharvest-1.12.2-1.1.0.jar                     | None                                     |
	| LCHIJA  | zawa                | 1.12.2-2.1.0             | zawa-1.12.2-2.1.0.jar                              | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| LCHIJA  | betteranimalsplus   | 9.0.1                    | betteranimalsplus-1.12.2-9.0.1.jar                 | None                                     |
	| LCHIJA  | dshuds              | 3.6.0.0                  | DynamicSurroundingsHuds-1.12.2-3.6.0.0.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA  | snowrealmagic       | 0.3.3                    | SnowRealMagic-0.3.3.jar                            | None                                     |
	| LCHIJA  | thebetweenlands     | 3.6.2                    | TheBetweenlands-3.6.2-universal.jar                | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCHIJA  | midnight            | 0.3.5                    | themidnight-0.3.5.jar                              | None                                     |
	| LCHIJA  | hungeroverhaul      | 1.12.2-1.3.3.jenkins148  | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar         | None                                     |

	Loaded coremods (and transformers): 
TransformLoader (DynamicSurroundings-1.12.2-3.6.2.1.jar)
  
AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CreativePatchingLoader (CreativeCore_v1.10.42_mc1.12.2.jar)
  
LevelUpCore (levelup2-1.5.7.jar)
  
EC Core Plugin (enchcontrol-1.12.2-1.1.5-0.jar)
  austeretony.enchcontrol.common.core.ECClassTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.2-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
MMFMLCorePlugin (MultiMine-1.12.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.11-1.12.2 (1).jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
ColytraLoadingPlugin (colytra-1.12.2-1.2.0.3.jar)
  c4.colytra.asm.ElytraTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
LoadingPlugin (Reskillable-1.12.2-1.13.0.jar)
  codersafterdark.reskillable.base.asm.ClassTransformer
FutureMC (future-mc-1.12.2-0.2.4.1.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
  com.therandomlabs.randompatches.core.RPTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
midnight (themidnight-0.3.5.jar)
  com.mushroom.midnight.core.transformer.MidnightClassTransformer
Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
  com.chocohead.biab.BornInABarn
WolfArmorCore (wolfarmor-1.12.2-3.7.5-universal-signed.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TickCentral (TickCentral-2.6.jar)
  com.github.terminatornl.tickcentral.asm.BlockTransformer
  com.github.terminatornl.tickcentral.asm.ITickableTransformer
  com.github.terminatornl.tickcentral.asm.EntityTransformer
  com.github.terminatornl.tickcentral.asm.HubAPITransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 461.09' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	No Tree Punching: You are not running an official build. This version will NOT be supported by the author.
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 12
	Mipmaps: 2
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 461.09
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by ghost** [comment]
I was messing with a few recipes, and suddenly it will not launch again. I've tried reverting the scrips to their old saves, or even launching without any scripts at all. It won't launch. 

Please help, I've been working on this modpack forever.

**Comment by jaredlll08** [comment]
We have an issue template for a reason. 

Fill. It. Out.

**Comment by ghost** [comment]
So sorry, I reposted with proper formating. My apologies.
