### ISSUE TITLE
1.12.2 Crashing on Startup, help very appreciated

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#1148]
#### Issue Description:

CraftTweaker crashes MC on startup.

#### What happens:

Forge gets to 6/7 steps, then crashes. Error log included below.
I was working on some recipes with MTRM and CraftTweaker, and a few small scripts. **All recent work in these scrips is the bottom few lines.**

#### What you expected to happen:

For Minecraft to work like it was 1 hour ago. It was running, it was working, now it won't launch. I'm pulling my hair out.
I've tried running without scripts too, but that doesn't work either (same crash error).

#### Script used (Please pastebin.com or gist.github.com your script, posting an unpasted or ungist'd script will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file):

MineTweakerRecipeMaker script: https://pastebin.com/gC6AHtqr
FoodTweaker script: https://pastebin.com/0FKEMj5i
Main script: https://pastebin.com/156R2s5A
Oredictionary script: https://pastebin.com/pPc3FkgF

#### crafttweaker.log file (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.):

crafttweaker.log file:  https://pastebin.com/mqMCcagG
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: **1.12.2**
- Forge: **14.23.5.2855**
- Crafttweaker: **CraftTweaker2-1.12-4.1.20.614**
- Using a server: **no**
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present (Please pastebin.com or gist.github.com your file, posting an unpasted or ungist'd file will automatically close this issue. We are **NOT** going to download files, do **NOT** upload your file to this issue, please give us a link to a paste / gist of the file.):

**Crash here**: https://pastebin.com/bYe3S0KV

**Comment by kindlich** [comment]
First, you linked this crash to CraftTweaker.
Does it also occur without CrT installed?

**Comment by jaredlll08** [comment]
Try adding `#disable_search_tree` to a script

**Comment by ghost** [comment]
> First, you linked this crash to CraftTweaker.
> Does it also occur without CrT installed?

Hm, it crashes _without_ CrT installed too.

Pastebin: https://pastebin.com/py9Zu28n

I have no idea what to do, or where to start. What could have happened?
I mean, it was _literally_ working fine for weeks. Suddenly not working with minimal changes to CrT scripts, that's it.

**Comment by jaredlll08** [comment]
IF it crashes *without* crafttweaker installed, then I don't see how this could be us at all.

**Comment by ghost** [comment]
It wasn't Crafttweaker's fault--despite the crash log saying so. Closing now.
