### ISSUE TITLE
1.12.2 adding an item to the ore dictionary only includes the item with that specific meta-id

### ISSUE THREAD

**Issue by mensreaMC** [CraftTweaker/CraftTweaker#1150]
Any item that I set to have an ore dictionary value will lose its ore dictionary value as soon as the meta-id changes. So basically if you set an iron pick to a value and then use it it loses its value.

For example I set "meleeWeapon.add(<minecraft:iron_sword>);" but then as soon as the iron sword takes one damage it loses that designation. I also tried "meleeWeapon.add(<minecraft:iron_sword:*>);" but that doesn't work at all...

I expected it to work and I'm honestly not sure why it wouldn't automatically assume that the meta ID didn't matter........

This is happening on 1.12.2 and CraftTweaker2-1.12-4.1.20.612. I have no log file to prove it happens, it's not that kind of error...

**Comment by kindlich** [comment]
Adding with the wildcard meta ID (`<minecraft:iron_sword:*>`) is the way to go.

Also, we have an issue template for a reason.
It provides us with information that we need to help you so please fill it out.

**Comment by democat3457** [comment]
And also don't forget to add the brackets around the item id - `meleeWeapon.add(<minecraft:iron_sword:*>);`

It's also likely that if you're using it as an ingredient, you'll want to use `<minecraft:iron_sword:*>.anyDamage()` since the meta of the item doesn't actually change when damaged, and instead the durability does.

**Comment by mensreaMC** [comment]
First off I'd like to apologize because when I made this report I really wasn't in the condition to do so. Second, I'd like to say that I was using "meleeWeapon.add(<minecraft:iron_sword:*>);" formatting and that it still didn't work. Third, I've now realized the items are still being tagged in my game properly and that the problem involves how I'm using the ore dictionary in my mod. 

Sorry!
