### ISSUE TITLE
Fehlercode

### ISSUE THREAD

**Issue by Danny40404** [CraftTweaker/CraftTweaker#1152]
Hey, ich habe einen Code für Crafttweaker geschrieben und habe alles so gemacht wie es im Tutorial gemacht wurde. Wenn ich auf meine Singleplayer Welt gehe kommt der Fehlercode:

 ERROR: [crafttweaker ; SIDE_CLIENT]: Error parsing crafting.zs:1 -- ; expected

Der Code ist:
`recipes.addShaped(<minecraft:diamond>),  [
[<null>, <minecraft:dirt>, <null>],
[<minecraft:dirt>, <minecraft:dirt>, <minecraft:dirt>],
[<null>, <minecraft:dirt>, <null>]]);`

Ich spiele auf der 1.12.2
Der Speicherpfad der Datei lautet: C:\Users\danny\Twitch\Minecraft\Instances\Test Modpack\scripts
Ich hoffe mir kann jemand weiterhelfen.

MfG. Danny

**Comment by jaredlll08** [comment]
Haven't a clue what you said since I don't speak German.

```zenscript
<minecraft:diamond>), 
```
Issue is the `)` after the diamond and `<null>` is meant to be `null`. 

Try:
```zenscript
recipes.addShaped(<minecraft:diamond>, [ [null, <minecraft:dirt>, null
], [<minecraft:dirt>, <minecraft:dirt>, <minecraft:dirt>], [null, <minecraft:dirt>, null]]); 
```

**Comment by Danny40404** [comment]
Thank you it worked.

**Comment by Danny40404** [comment]
Hey what did I do wrong here?

Error Code:
ERROR: [crafttweaker]: Error executing {[0:crafttweaker]: crafting.zs}: input must be an oredict String or a Block.

Script:
`mods.botania.PureDaisy.addRecipe(<minecraft:planks>,<minecraft:lapis_block>, 10);`

**Comment by friendlyhj** [comment]
Go https://discord.blamejared.com/ to get further help.
