### ISSUE TITLE
IE Metal Press addRecipe

### ISSUE THREAD

**Issue by octaarium** [CraftTweaker/CraftTweaker#1153]
#### Issue Description:
Tried to add Immersive Engineering Metal Press Recipe like shown on CT documentation website
https://docs.blamejared.com/1.16/en/mods/ImmersiveEngineering/MetalPress/#methods-2

#### What happens: 
Log Outputs [DONE][CLIENT][ERROR] metal_press.zs:5:0 No such member: addRecipe 
and the script doesn't work

#### What you expected to happen: 
To get book out of metal press :)

#### Script used: 
https://pastebin.com/jGLTjEQ0

#### crafttweaker.log file: 
https://pastebin.com/0XrD6XgC

____
#### Affected Versions:

- Minecraft: 1.16.4
- Forge: 35.1.37
- Crafttweaker: 7.1.0.110
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present:
https://pastebin.com/emrCB1Di

**Comment by jaredlll08** [comment]
update immersive engineering.

**Comment by octaarium** [comment]
> update immersive engineering.

yeah but Im making a modpack for 1.16.4 and I have the newest version of IE that supports 1.16.4

**Comment by jaredlll08** [comment]
Can't help there unfortunately, are you sure that their 1.16.5 version doesn't work on 1.16.4?

**Comment by octaarium** [comment]
> Can't help there unfortunately, are you sure that their 1.16.5 version doesn't work on 1.16.4?

Yeah tested it. But thanks anyway
