### ISSUE TITLE
Feature Request: Add a ZenGetter and Setter for Player Air

### ISSUE THREAD

**Issue by PyroFlareX** [CraftTweaker/CraftTweaker#1155]
**Feature request name**
Add a Zen Getter and Setter for Player Air

**Feature request description**
I wish for a ZenGetter and Setter for the Player Air value. 

**Feature request reason**
In a modpack I am developing, I want to have the ability to make the player use their air in a given dimension without them being underwater. This would simulate toxic air in a dimension, say the Nether. This also would allow me to require the Mekanism scuba mask or equivalent that restores player air to go into a chosen dimension, as like a progression lock of sorts. 

**Feature request dependencies**
No, it is a vanilla value, so other mods are not required for this to be useful. It does allow me in my use case to utilize the available systems of another mod however.

**Game Version
What game version do you want this feature for? (e.g. 1.12, 1.16)
1.16.4, but if it's not to hard to implement 1.12.2 would not be unwelcome.

**Comment by jaredlll08** [comment]
This already exists in 1.12

**Comment by jaredlll08** [comment]
Closed in 30756f614e48360c672d36510db3276bd7bfc3d0
