### ISSUE TITLE
Astral Sorcery

### ISSUE THREAD

**Issue by SkullHunter55** [CraftTweaker/CraftTweaker#1168]
**Feature request name**
Astral Sorcery

**Feature request description**
Could you add the features that were in the 1.12.2 version of crafttweaker

**Feature request reason**
Cause im building a modpack based around astral and nobody has compatibility with it

**Game Version
1.16.5

**Comment by friendlyhj** [comment]
https://github.com/HellFirePvP/AstralSorcery/issues/1715#issuecomment-778901867

And specific mod compat never is not the target of  CraftTweaker.

**Comment by friendlyhj** [comment]
Can be closed, as HellFirePvP/AstralSorcery#1758 is merged.
