### ISSUE TITLE
java 15 compat

### ISSUE THREAD

**Issue by friendlyhj** [CraftTweaker/CraftTweaker#1171]
#### Intro:  
java 15 compat

#### Issue Description:  
can't add JSON recipe in java 15 environment

#### Script used:  
https://paste.ubuntu.com/p/FFQVfrK5Sb/

#### crafttweaker.log file:  
https://paste.ubuntu.com/p/9Zd9VR3SQt/

____
#### Environment:  
- Minecraft Version: 1.16.5
- Forge Version: 35.1.29
- CraftTweaker Version: 7.1.0.125
- Are you using a server: no

**Comment by kindlich** [comment]
Just to make sure, in Java8 it works?

Please add `#debug` to your script and send the generated class files here.
Though I have to say, we at the moment only explicitly support Java8, so I cannot say too much.

**Comment by friendlyhj** [comment]
java8 works

[classes.zip](https://github.com/CraftTweaker/CraftTweaker/files/5996031/classes.zip)

**Comment by jaredlll08** [comment]
Try this jar please
https://cdn.discordapp.com/attachments/354745056743260172/814608643415736340/CraftTweaker-1.16.5-7.1.0.jar

Someone did confirm that it worked, but just to make sure

**Comment by friendlyhj** [comment]
It works. 😄
