### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by TYRS0** [CraftTweaker/CraftTweaker#1172]
#### Issue Description:  
CraftTweaker crashes MC on startup. Works fine without

#### What happens:  
Gets to 2/7 then Crashes

#### What you expected to happen:  
Not to crash

#### Script used:  
None

#### crafttweaker.log file:  
I don't know how to find it. The file I found was empty

____
#### Environment:  
- Minecraft Version: 1.12.2
- Forge Version:  forge-14.23.5.2855
- CraftTweaker Version: CraftTweaker2-1.12-4.1.20.586
- Are you using a server: No

#### Game log:  
https://pastebin.pl/view/6f77c535

**Comment by kindlich** [comment]
There is no mention of CraftTweaker in your given crash report.
That crash report links to OTG:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Open Terrain Generator (openterraingenerator)
```

**Comment by TYRS0** [comment]
i just realized that i gave the wrong crash report should i put in another ticket. Sry

 https://pastebin.pl/view/d3452ad9

**Comment by jaredlll08** [comment]
Update CraftTweaker

**Comment by democat3457** [comment]
have you tried upgrading your crafttweaker version to the latest beta version

lol rip github didnt update its cache

**Comment by TYRS0** [comment]
The Curseforge Launcher says that I'm using the Latest Beta already

**Comment by democat3457** [comment]
well, you arent - youre using 580-something whereas the newest is 600-something

**Comment by TYRS0** [comment]
i somehow fixed it by reinstaling the beta
thx for the help :)

**Comment by jaredlll08** [comment]
https://www.curseforge.com/minecraft/mc-mods/crafttweaker/files/3202907
