### ISSUE TITLE
[1.16.5] 7.1.0.126 string.split("...") not working properly

### ISSUE THREAD

**Issue by Terpo** [CraftTweaker/CraftTweaker#1176]
#### Intro:  
understandable

#### Issue Description:  
A script does not work after trying to migrate it from 7.0

#### What happens:  
string.split("...") has some problems as discussed on discord.

#### What you expected to happen:  
make string.split great again

#### Script used:  
https://gist.github.com/Terpo/a4ce89c03e797fbcb08b9366867e99ee script with debug

#### crafttweaker.log file:  
original error:
https://gist.github.com/Terpo/30b0575e8eff5d6ca06d42b6b29ec472 log with debug

classes folder no1 on discord: https://cdn.discordapp.com/attachments/513725278955110403/812458434230353960/classesTerpo190221-2359.zip
classes folder no2 on discord https://cdn.discordapp.com/attachments/513725278955110403/812466370812837908/classesTerpo200221-0030.zip
third version of a quickfix did not generate a classes folder at all but the log changed to:

lastest log: https://gist.github.com/Terpo/cb8eff18be771d283396d8a42823f186 with that file:
https://cdn.discordapp.com/attachments/354745056743260172/812467530958110760/CraftTweaker-1.16.5-7.1.0-2.jar

____
#### Environment:  
forge 1.16.5-36.0.40
CraftTweaker-1.16.5-7.1.0.126
https://gist.github.com/Terpo/281decfd7bb87f35aac2f99978c87b62 modlist

I am testing my script in an SP world on my client. Server tests will follow when all scripts are migrated.

#### Game log:  
http://terpo.org/debug200221-0055.txt  , reupload on gist when needed

**Comment by friendlyhj** [comment]
Can be closed.
