### ISSUE TITLE
[1.12.2] IRayTraceResult isEntity always false & entity always null

### ISSUE THREAD

**Issue by pjc21** [CraftTweaker/CraftTweaker#1178]
#### Issue Description:  
IRayTraceResult isEntity is always false & entity is always null

#### What happens:  
When calling IRayTraceResult it will get results for blocks, misses but not entities as either item entities or living entities.

#### What you expected to happen:  
For the raytrace to also give result for entities.

#### Script used:  
[raytrace.zs](https://pastebin.com/0RYPUUyL)

#### crafttweaker.log file:  
[crafttweaker-raytrace.log](https://pastebin.com/6m1dSJHe)

____
#### Environment:  
- Minecraft Version: 1.12.2
- Forge Version: 14.23.5.2854
- CraftTweaker Version: CraftTweaker2-1.12-4.1.20.618
- Are you using a server: No

#### Game log:  
[raytrace_latest.log](https://pastebin.com/mrVxMazd)

**Comment by jaredlll08** [comment]
That method only ray traces blocks.

in 1.12 there isn't an easy, reliable way to ray trace blocks and entities.
