### ISSUE TITLE
Can't call custom method from lambda

### ISSUE THREAD

**Issue by luoluo39** [CraftTweaker/CraftTweaker#1181]
#### Issue Description:  
_java.lang.IllegalAccessError_ was thrown when call an custom method from lambda.

#### What happens:  
_java.lang.IllegalAccessError_ was thrown.

#### What you expected to happen:  
script run successfully.

#### Script used:  
```zenscript
function add(a as int, b as int) as int {
	return a + b;
}

var someLambda as function() as int = () => { return add(1, 1); };

someLambda();
```

#### crafttweaker.log file:  
[https://pastebin.com/zu9HKK0N](https://pastebin.com/zu9HKK0N)

____
#### Environment:  
- Minecraft Version: 1.16.5
- Forge Version: 36.0.42
- CraftTweaker Version: 1.16.5-7.1.0.129
- Are you using a server: no

#### Game log:  
[https://pastebin.com/sTg1uMHw](https://pastebin.com/sTg1uMHw)

**Comment by friendlyhj** [comment]
add `public` before `function`. 

```zenscript
public function add(a as int, b as int) as int {
	return a + b;
}
```

**Comment by luoluo39** [comment]
> add `public` before `function`.
> 
> ```zenscript
> public function add(a as int, b as int) as int {
> 	return a + b;
> }
> ```

that's a little embarrassing. I'm wonder if there are more document about zenScript itself and built-in types like stdlib.list?

**Comment by jaredlll08** [comment]
You can find some ZC docs (they are still work in progress) here
https://docs.blamejared.com/1.18/en/zencode/ZenCode

and built in types here:
https://github.com/ZenCodeLang/StdLibs/tree/a0e740f003f6f246f0844fbe8f12edc6f974cf5e/src/main/zencode/stdlib/src
