### ISSUE TITLE
Script not Working as Expected

### ISSUE THREAD

**Issue by DarkAmulek** [CraftTweaker/CraftTweaker#1182]
#### Intro:  
exnihliosequentia-1.16-2.0.0.1 is the version of the mod I am making recipe edits for.

#### Issue Description:  
I typed up a script to modify hammer recipes for Ex Nihlo: Sequentia. Stone and Sand work as expected but cobble, gravel, and dirt won't work as modified.

#### What happens:  
braking cobblestone with a hammer produces cobblestone, braking gravel with a hammer produces gravel, braking dirt with a hammer produces dirt.

#### What you expected to happen:  
braking cobblestone with a hammer produces gravel, braking gravel with a hammer produces dirt, braking dirt with a hammer produces sand.

#### Script used:  
https://pastebin.com/vZruAzms

#### crafttweaker.log file:  
https://pastebin.com/YRevKwD7

____
#### Environment:  
8 Update 281

- Minecraft Version: 1.16.4
- Forge Version: 35.1.37
- CraftTweaker Version: 1.16.4-7.1.0.84
- Are you using a server: no
- If yes, does the client have the exact same scripts?

#### Game log:  
Not sure what this is, but if you can tell me where to find it if it is necessary for this particular instance then I will add it.

**Comment by DarkAmulek** [comment]
I should add that I have already asked for help from the discord server, they said the code should work properly, and that I should post a bug report here.

**Comment by jaredlll08** [comment]
The script works fine, you are reusing the recipe name.

```zenscript
import mods.exnihilosequentia.ZenHammerRecipe;

<recipetype:exnihilosequentia:hammer>.removeAll();

<recipetype:exnihilosequentia:hammer>.create("hammer_test_stone").setInput(<item:minecraft:stone>).addOutput(<item:minecraft:cobblestone>);
<recipetype:exnihilosequentia:hammer>.create("hammer_test_cobble").setInput(<item:minecraft:cobblestone>).addOutput(<item:minecraft:gravel>);
<recipetype:exnihilosequentia:hammer>.create("hammer_test_gravel").setInput(<item:minecraft:gravel>).addOutput(<item:minecraft:dirt>);
<recipetype:exnihilosequentia:hammer>.create("hammer_test_dirt").setInput(<item:minecraft:dirt>).addOutput(<item:minecraft:sand>);
<recipetype:exnihilosequentia:hammer>.create("hammer_test_sand").setInput(<item:minecraft:sand>).addOutput(<item:exnihilosequentia:dust>);
```
that works fine.

**Comment by DarkAmulek** [comment]
huh, i'm surprised they did not catch that on the discord. thanks, I'll remember to give recipes different names.
