### ISSUE TITLE
Mineral deposit addrecipe not wokring?

### ISSUE THREAD

**Issue by ZEROX7** [CraftTweaker/CraftTweaker#1187]
hey there i wanted to make a script to add create zinc ore to galena by first removing it then readding it with zinc in it
but somehow the addrecipe string seems to not work and for safety i tryd the sheep mineral deposit thats on the documentation and it also says that it doesnt work

**Comment by jaredlll08** [comment]
Follow the issue template.

Telling me something doesn't work, is useless, the log will tell you exactly how it doesn't work.

**Comment by jaredlll08** [comment]
You probably need to upgrade Immersive Engineering to the very latest 1.16.5.
