### ISSUE TITLE
Ct hand forge

### ISSUE THREAD

**Issue by Joshernoob** [CraftTweaker/CraftTweaker#1189]
**Feature request name**
/ct hand forge command 

**Feature request description**
This would pull the forge based tags for the item like the /ct hand command.

**Feature request reason**
Many pack maker used this mod for items ids more recently thanks to 1.13 for forge ids. Since crafttweaker using custom ids now for personal code. Would help to have an of branch of the /ct hand command to see base forge for json files and mods configs
This helps new players relying on this mod for these reason and old that used the /ct hand in the past for ids.

**Feature request dependencies**
This would require a new command and a way to pull the forge id off an item with said command.

**Game Version
1.16.5

**Comment by friendlyhj** [comment]
Are you saying datapack recipes?
Cast IItemStack or Item tags to IData.
for example, `println(<item:minecraft:apple> as IData);` `println(<tag:items:ingots/iron> as IData);`

**Comment by jaredlll08** [comment]
They are saying for use in actual datapacks, simply using CraftTweaker for it's commands and nothing else

**Comment by jaredlll08** [comment]
```
/ct hand vanilla
```
