### ISSUE TITLE
Furnace fuel burning time support

### ISSUE THREAD

**Issue by DLumina** [CraftTweaker/CraftTweaker#1191]
**Feature request name**
Furnace fuel burning time support

**Feature request description**
Add the option to change or disable fuel burning time in 1.16.

**Feature request reason**
It was already implemented in 1.12 and useful to dealing with custom fuels, but not implemented in 1.16 yet.

**Feature request dependencies**
Vanilla Minecraft

**Game Version
1.16

**Comment by jaredlll08** [comment]
![image](https://user-images.githubusercontent.com/5553605/109839571-e61f3e80-7c4f-11eb-99af-b1f5e68e5e27.png)

```
<item>.burnTime = 500;
```

https://github.com/CraftTweaker/CraftTweaker/blob/1.16/scripts/burntime.zs#L1-L2

**Comment by DLumina** [comment]
\_(:з」∠)\_ Thank you for your kind help.
