### ISSUE TITLE
[Question] Add all items of one tag to another?

### ISSUE THREAD

**Issue by ElsaTheHobo** [CraftTweaker/CraftTweaker#1192]
I looked all through the documentation and couldn't figure out how to do this in 1.16.5.

In 1.12.2 if I wanted to add all items in oredict egg to oredict listAllegg I would do this:
<ore:listAllegg>.addAll(<ore:egg>);

I can't seem to find an equivalent for this in 1.16.5; the migration page doesn't mention it, and the pages in the Vanilla/Api/Tags section don't mention anything similar either. I tried .addAll, and that doesn't exist, and doing <tag:items:forge:egg>.add(<tag:items:forge:eggs>); also caused an error.

**Comment by jaredlll08** [comment]
```zenscript
<tag:items:minecraft:planks>.add(<tag:items:forge:rods>);
```
