### ISSUE TITLE
Casting Issue with AE2 Inscriber Recipes

### ISSUE THREAD

**Issue by XerShade** [CraftTweaker/CraftTweaker#1193]
#### Issue Description:  
I'm trying to add recipes to the AE2 inscriber and it keeps giving me a casting error. I've also tried to use the example scripts on https://docs.blamejared.com/1.16/en/mods/AppliedEnergistics2/Inscriber/ copying them exactly as they appear on that page and those throw the same error.

#### What happens:  
The script implodes and does not work because of a casting error.

#### What you expected to happen:  
The recipes to be added to the game.

#### Script used:  
https://pastebin.com/HAjFdWTT

#### crafttweaker.log file:  
https://pastebin.com/40pzLC7U
____
#### Environment:  

- Minecraft Version: 1.16.5
- Forge Version: 36.0.43
- CraftTweaker Version: CraftTweaker-1.16.5-7.1.0.135
- Are you using a server: Yes
- If yes, does the client have the exact same scripts? Yes

#### Game log:  
https://gist.github.com/XerShade/3b36503504d6c5baa0e95fed7a90639a

**Comment by jaredlll08** [comment]
The script you gave has really weird issues.

```
<recipetype:appliedenergistics2:inscriber>.addInscribeRecipe("engineering_processor_press", <item:appliedenergistics2:engineering_processor_press>, <item:minecraft:diamond>, [<item:minecraft:air>,<item:minecraft:iron_block>] as IIngredi$ 
```

It shouldn't end with a `$`.

**Comment by XerShade** [comment]
Sorry about that, fixed it. Also slapped ssh because it downloaded the file wierd. New paste: https://pastebin.com/HAjFdWTT

**Comment by jaredlll08** [comment]
Ah, you seem to have the imports wrong. 

https://docs.blamejared.com/1.16/en/vanilla/api/items/IIngredient/#importing-the-class-2
And
https://docs.blamejared.com/1.16/en/vanilla/api/items/IItemStack/#importing-the-class-2 

You're missing the ".api" part

**Comment by XerShade** [comment]
That did it thanks. Google must have sent me to a different version's docs even though I typed in crafttweaker 1.16 IIngredient. XD

**Comment by jaredlll08** [comment]
You had the 1.12 name, so it probably sent you there
