### ISSUE TITLE
Different Crafttweaker.log output after ``/ct hand``

### ISSUE THREAD

**Issue by Wxrlds** [CraftTweaker/CraftTweaker#1194]
**Feature request name**
Different Crafttweaker.log output after ``/ct hand``

**Feature request description**
Currently when executing ``/ct hand`` on for example Immersive Engineering Copper Nuggets this is the output in the crafttweaker.log
```
Item: §a<item:immersiveengineering:nugget_copper>§r
§3Item Tag Entries§r
    §e-§r §b<tag:items:forge:nuggets>§r
    §e-§r §b<tag:items:forge:nuggets/copper>§r
```

It would be nice if this would be changed to not include any formatting, so without the ``§`` and the ``-`` so that the output would look like this. 
```
Item: <item:immersiveengineering:nugget_copper>
Item Tag Entries
<tag:items:forge:nuggets>
<tag:items:forge:nuggets/copper>
```

**Feature request reason**
This would come in useful when unifying/removing the tags from duplicate items as the tags could be copied directly from the log into the scripts without first removing the formatting or clicking each individual tag in the ingame chat.

**Feature request dependencies**
This feature comes in useful as soon as two mods add duplicate materials. If there are no duplicate materials unifying ores wouldn't be required anyway

**Game Version
1.16.5

**Comment by democat3457** [comment]
whats wrong with copying it from chat

**Comment by jaredlll08** [comment]
I think we should remove formatting codes from log output, can't think of a reason to have them
