### ISSUE TITLE
Vanilla Ore Generation not working

### ISSUE THREAD

**Issue by Ninezel** [CraftTweaker/CraftTweaker#1200]
#### Intro:  
Installing the latest update for CraftTweaker causes crashes within the loot table with vanilla ore spawning in the world generation.

#### Issue Description:  
When generating a new world with the new update 7.1.0.148 it causes vanilla ores not to spawn. This could a loot table issue that must be conflicting with something or if it's not the loot table then I have no idea.

#### What happens:  
I use [/lods strip around] to observe any ores that are not generated within the new world that I've created.

#### What you expected to happen:  
Well, I expected the normal vanilla ore generation. I downgraded from 148 to 145 that fixed the issue.

#### crafttweaker.log file:  

____
#### Environment:  

- Minecraft Version:
- Forge Version: 35.1.37
- CraftTweaker Version: 7.1.0.148
- Are you using a server: Yes but this test is done on Singleplayer with biomesoplenty generation default settings
- If yes, does the client have the exact same scripts?
I am not using any scripts at the moment

#### Game log:  
https://gist.github.com/Admiral-Sebastian/97b53fced82d3fcb7e07f0246dc3ccf6 [Latest.log]

**Comment by kindlich** [comment]
Could you include your crafttweaker.log file?

**Comment by Ninezel** [comment]
Sure thing https://gist.github.com/Admiral-Sebastian/a296dd1b0c7a3be8575cc3b5a9d4cd37

**Comment by Ninezel** [comment]
This is when I ran 145 and completely forgot to save the 148 log

**Comment by jaredlll08** [comment]
Can we get a modlist or something, or if you can give us the modpack that would help as well

**Comment by Ninezel** [comment]
https://www.curseforge.com/minecraft/modpacks/the-wanderers-official Download 6.2.4. Update to CraftTweaker 148 and do the command I stated in my initial comment. On that site, there is also the mod list you have stated.

**Comment by Ninezel** [comment]
This issue has now been fixed in the latest update of CraftTweaker now 151
