### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by ZCrafter** [CraftTweaker/CraftTweaker#1201]
Errors:
Could not cast MCBlockState to IIngredient
And 
Member not found

I'm getting these errors and I'm not sure how to fix them, and can not find them anywhere else

Here is the error:
https://pastebin.com/k4gVh0rh

CraftTweaker 1.16.5-7.1.0.145
Forge 36.0.46

**Comment by jaredlll08** [comment]
follow the issue template.

How are we meant to help if we can't even see the script you tried to use?
