### ISSUE TITLE
Member not found Issue

### ISSUE THREAD

**Issue by ZCrafter** [CraftTweaker/CraftTweaker#1202]
#### Intro:  
I'm creating a new modpack and I'm trying to change modded recipes.

#### Issue Description:  
I used the examples on the CraftTweaker wiki and when I load into world the chat says no member found followed by a mod name. For me it is astral sorcery and mekanism.

#### What happens:  
Upon loading into world, multiple chats saying "Member not found: modname". And then, scripts are invalid

#### What you expected to happen:  
No errors, scripts are valid and recipes are changed

#### Script used:  
Mekanism.zs     https://pastebin.com/drWAvEii
Themal.zs     https://pastebin.com/ffSTJd2y
ImmersiveEngineeing.zs     https://pastebin.com/3jkhHPY5
Botania.zs     https://pastebin.com/yRXmhCYH

#### crafttweaker.log file:  
https://pastebin.com/JN3ymPb7

____
#### Environment:  

- Minecraft Version: 1.16.5
- Forge Version: 36.0.46
- CraftTweaker Version: 7.1.0.145
- Are you using a server: No

**Comment by jaredlll08** [comment]
On line 57 of immersive engineering, you're doing
```zenscript 
mods.astralsorcery.Altar.addDiscoveryAltarRecipe("Immersive Hammer", <item:immersiveengineering:hammer>, 200, 200, [
			air, ManaSteel, imbude_slate,
			air, stick, ManaSteel,
			stick, air, air]);
```
Astral sorcery doesn't have CraftTweaker support yet.

**Comment by kindlich** [comment]
In the meanstime you can use the addJSON method to add recipes.

See this comment
<https://github.com/HellFirePvP/AstralSorcery/issues/1715#issuecomment-778901867>

**Comment by ZCrafter** [comment]
Thanks, I'm assuming mekanism is not supported yet either then? Are there any examples of JSON methods for mekanism.
