### ISSUE TITLE
[1.12.2] Problem with Meta Data

### ISSUE THREAD

**Issue by MokahTGS** [CraftTweaker/CraftTweaker#1205]
#### Issue Description:  
I'm having an issue renaming items that have meta data.  Instead of the item specified, the script renames everything with the same id even if the meta data is different.

In these two lines specifically in the script I link below:
<variedcommodities:crystal>.displayName = "Crystal Tears";
<variedcommodities:orb:10>.displayName = "Naga Queen Egg";

Those items (id gotten from /ct hand command) get their names changed as expected, but so does every other item that shares that id with different meta data.  For example, <variedcommodities:crystal:1> also gets it's name changed even though it is a different item and not specified in the script.

#### Script used:  
https://pastebin.com/AQpBvNgn

#### crafttweaker.log file:  
https://pastebin.com/TzxPktNL
____
#### Environment:  
- Minecraft Version: 1.12.2
- Forge Version: 14.23.5.2855
- CraftTweaker Version: CraftTweaker2-1.12-4.1.20.586
- Are you using a server: SP
- If yes, does the client have the exact same scripts?

**Comment by democat3457** [comment]
Use the lang file instead

**Comment by MokahTGS** [comment]
I'm unsure of what you mean.  Any chance I can get an example?...I'm trying to learn this stuff.

**Comment by MokahTGS** [comment]
The weird thing is this item is also changed and it's id is different, not just the meta data.

<variedcommodities:crystal_block> is renamed the same as <variedcommodities:crystal>

**Comment by jaredlll08** [comment]
Metadata renaming only works if the mod supports it.

In this case it doesn't, you can't even use a lang file to rename a specific orb, since they all share the same lang key.
