### ISSUE TITLE
Tetra preventing the ability to add modded tags to items

### ISSUE THREAD

**Issue by gregest** [CraftTweaker/CraftTweaker#1206]
#### Intro:  

Tetra prevents the ability to add modded/not yet existing tags to items

#### Issue Description:  

I tried adding a <tag:items:forge:ingots/osmium> tag to an item which couldn't be done as long as tetra was in the pack, as soon as tetra was removed the tag showed up properly, the pack also doesn't have an osmium ingot so osmium tags don't exist in the pack

#### What happens:  

Tag doesn't get added to item

#### What you expected to happen:  

Expected the tag to be added to the item 

#### Script used:  
https://pastebin.com/TYtFr0ms

#### crafttweaker.log file:  
https://pastebin.com/qzC5vdy0

____
#### Environment:  

- Minecraft Version: 1.16.5
- Forge Version: 36.1.1
- CraftTweaker Version: CraftTweaker-1.16.5-7.1.0.158
- Are you using a server: no
- If yes, does the client have the exact same scripts?

#### Game log:  
https://pastebin.com/1srcYPZt

**Comment by kindlich** [comment]
Are the crafttwaeker log and game log you provided with or without the mod installed?
What do you mean by "tetra prevents it"? Does the game crash? Does it just not look like something's happening?

**Comment by gregest** [comment]
the logs are provided without the mod installed and yes, it looks like nothing happened, I can give logs with the mod installed too

**Comment by kindlich** [comment]
Please also provide the logs with the mod installed.
It's oddly hard finding the error from the log when you only provide the log for the case where the error is not present 😉

**Comment by gregest** [comment]
makes sense  
ct log https://pastebin.com/rEJMpFXr 
game log https://pastebin.com/8GxkZuSN

**Comment by jaredlll08** [comment]
Fixed by https://github.com/CraftTweaker/CraftTweaker/commit/c1882882013c05dcb39f75a898d723e0771411d7
