### ISSUE TITLE
Add getAllIPlayers method

### ISSUE THREAD

**Issue by Witixin1512** [CraftTweaker/CraftTweaker#1214]
Feature request name
getAllIPlayers ZenMethod.

Feature request description
Add a ZenMethod that checks through the online player list inside an IWorld object and returns a List of IPlayers online you could manipulate then.

Feature request reason
Doesn't exist right now and keeping track with playerLoggedInEvent doesn't help when you try using it in another event.

Feature request dependencies
N/A

Game Version
1.12.2

**Comment by friendlyhj** [comment]
https://github.com/friendlyhj/ZenUtils/wiki/ZenUtilsWorld

I know there is a CraftTweaker util meme, but...
