### ISSUE TITLE
Cant remove brewing recipe

### ISSUE THREAD

**Issue by r0sso** [CraftTweaker/CraftTweaker#1216]
Hey. I tried to remove one of the potions recipes but ran into this problem. I used the "removeRecipeByOutputPotion" method and ready-made template to check on a swiftness potion.

https://pastebin.com/FmYzBssA

https://pastebin.com/MLsksAZ1
____

- Minecraft Version: - 1.16.5
- Forge Version: - 36.0.48
- CraftTweaker Version: - 7.1.0.176
- Are you using a server: - Yes
- If yes, does the client have the exact same scripts? - No. 330 lines of script works for the client without it

**Comment by jaredlll08** [comment]
Follow the issue template.

Do not post logs directly in the github issue and we can't help without a script file.

**Comment by r0sso** [comment]
okey. i fix it

**Comment by jaredlll08** [comment]
On the 3rd line of your script file, you just have the example recipe, it needs to be in a comment or removed:
```
 
Brewing.removeRecipeByOutputPotion(output as MCPotion) as void
brewing.removeRecipeByOutputPotion(<potion:minecraft:swiftness>);
```

should be:
```
 
// Brewing.removeRecipeByOutputPotion(output as MCPotion) as void
brewing.removeRecipeByOutputPotion(<potion:minecraft:swiftness>);
```
or just 
```
brewing.removeRecipeByOutputPotion(<potion:minecraft:swiftness>);
```

**Comment by r0sso** [comment]
Okay. Everytime before asking for help, I check everything carefully. and this was my first way and it didn't work. But that was in the 7.1.0.136 version of mod, and after update, I was hoping only for a new version. this is very strange and I am sorry about that. Before deleting a topic, I wanted to ask for one favor, if possible. is there a way to remove enchant recipes or am i blind again?

**Comment by r0sso** [comment]
Okay. Everytime before asking for help, I check everything carefully. and this was my first way and it didn't work. But that was in the 7.1.0.136 version of mod, and after update, I was hoping only for a new version. this is very strange and I am sorry about that. Before deleting a topic, I wanted to ask for one favor, if possible. is there a way to remove enchant book and enchant anvil recipes or am i blind again?

**Comment by jaredlll08** [comment]
So you cant remove enchantments straight up, but you can use the anvil event to cancel the recipe. 

If you join https://discord.blamejared.com we can help you with doing that.

Also just to confirm, your issue is resolved? Can I close the new issue you made?

**Comment by r0sso** [comment]
Okay! thank you for help! yes you can close all my topics
