### ISSUE TITLE
Invalid Key: 'output'! Keys must only be a single character!

### ISSUE THREAD

**Issue by ZCrafter** [CraftTweaker/CraftTweaker#1217]
#### Intro:  
I have multiple scripts and when I load the world the chat says "Invalid Key: 'output'! Keys must only be a single character!: Invalid Key: 'output'! Keys must only be a single character!" It doesn't say scripts are invalid, but none of the scripts work."

#### Issue Description:  
I'm using a custom modpack made by me. The scripts are not working

#### What happens:  
Upon loading a world, chat says, "Invalid Key: 'output'! Keys must only be a single character!: Invalid Key: 'output'! Keys must only be a single character!" and scripts do not work

#### What you expected to happen:  
No error and scripts take effect

#### Script used:  
I have 12 scripts and don't know which one the issue is in(or all of them). I can post them if they are needed

#### crafttweaker.log file:  
Got marked as offensive language by Pastebin, so below is a shortened version
https://pastebin.com/BRp46M5k

____
#### Environment:  

- Minecraft Version: 1.6.5
- Forge Version: 36.0.46
- CraftTweaker Version: 7.1.0.176
- Are you using a server: No

**Comment by jaredlll08** [comment]
We need the scripts.

From the log, your scripts have a lot of errors, with not being able to find a fluid.

The actual issue is related to astral sorcery, so that would be the main script we need.

**Comment by ZCrafter** [comment]
I only use fluids in RefinedStorage.zs, Thermal.zs, and Misc.zs

BloodMagic.zs https://pastebin.com/Lz97SX0t
Botania.zs https://pastebin.com/5kZZwVQF
Create.zs https://pastebin.com/Cj9tcmEv
ImmersiveEngineering https://pastebin.com/Ztf26yUB
ProjectRankine.zs https://pastebin.com/7HwcxUvS
MysticalAgriculture.zs https://pastebin.com/bY71jwqN
IndustrialForegoing.zs https://pastebin.com/ku6X9nq0
RefinedStorage.zs https://pastebin.com/KtnENkak
Thermal.zs https://pastebin.com/GfLzSF7m
Mekanism.zs https://pastebin.com/8gvQfP69
Misc.zs https://pastebin.com/pcGaWryH

**Comment by democat3457** [comment]
Found the error: on lines 81-82 of immersiveengineering.zs, you forgot a closing `}`, so it's reading `'output'` as a crafting key rather than part of the recipe

**Comment by democat3457** [comment]
As for the fluid errors, it would seem that either log or script isn't updated, since the log references something that isn't in the `IndustrialForegoing.zs`

**Comment by ZCrafter** [comment]
Thank you that worked! Also, craft tweaker doesn't support astral sorcery or mekanism recipe changes yet, right?

**Comment by jaredlll08** [comment]
There is a PR to add Astral Sorcery support, just waiting for them to merge it.

Mekanism has support in an unreleased version, just gotta wait for them to release it

**Comment by ZCrafter** [comment]
That's what I thought, thank you guys again!
