### ISSUE TITLE
Cant remove brewing recipe

### ISSUE THREAD

**Issue by r0sso** [CraftTweaker/CraftTweaker#1218]
#### What happens: 

 I am trying to use a script to exclude a potion recipe but I get this error.

#### What you expected to happen: 

i expect to see the third and fourth lines will work the same as other 330

#### Script used:  

https://pastebin.com/LW4b4HRN
4 line 

#### crafttweaker.log file:  

https://pastebin.com/UwZGKU8g

- Minecraft Version: 1.16.5
- Forge Version: 36.0.48
- CraftTweaker Version: 7.1.0.176
- Are you using a server: Yes
- If yes, does the client have the exact same scripts? No

#### Game log:  

https://pastebin.com/VfQN6sdX

**Comment by jaredlll08** [comment]
Firstly, you can reply to a closed issue, if I close an issue too soon and your issue isn't resolved, reply to the one I closed and I will re-open it.

Secondly did you read my reply?
https://github.com/CraftTweaker/CraftTweaker/issues/1216#issuecomment-808809569

As I explained, your line 3 isn't a valid thing in zenscript, put it in a comment or remove it.

**Comment by jaredlll08** [comment]
https://github.com/CraftTweaker/CraftTweaker/issues/1216#issuecomment-809254795
