### ISSUE TITLE
Change villager profession station

### ISSUE THREAD

**Issue by Vichoriz0** [CraftTweaker/CraftTweaker#1220]
**Feature request name**
Change station of a profession

**Feature request description**
Adding a way to change the station for different professions, even those added by other mods.

**Feature request reason**
It would allow modpack makers to further customize the experience to their liking and to diminish redudancy problems when multiple mods add a same mechanic. E.g. Three different mods add a kiln type of furnace (ceramist, environmental and charm), and one of these also adds a ceramist profession, which station is a kiln. With this feature, I could choose which one of these three kilns I want to use as the station for the ceramist profession, allowing me to get rid of the rest.

**Feature request dependencies**
It should be useful with or without other mods and shouldn't requiere any dependencies that I am aware of.

**Game Version**
1.16

**Comment by jaredlll08** [comment]
Why did you close this?

**Comment by Vichoriz0** [comment]
Oh sorry I shouldn't have? Just noticed the commit message said "Close CraftTweaker#1220". I'm really sorry if I did wrong :(

**Comment by jaredlll08** [comment]
I've looked into this a bit more, and as it stands the villager point of interest system (the stations) looks extremely fragile and I fear that if we touch it, it is going to introduce bugs or performance issues.

I'm going to close this for now, but if forge ever has an event for it or something along those lines we can relook at it.
