### ISSUE TITLE
Change /reload to /ct reload

### ISSUE THREAD

**Issue by pm065** [CraftTweaker/CraftTweaker#1225]
It would be nice if /reload was changed to /crafttweaker reload or /ct reload (maybe with a shortcut like /craftweaker r and /ct r?) for consistency and to avoid conflicts with Quark's /reload. (Quark's reload is to activate config changes without restarting.) If both CraftTweaker and Quark are installed, the game runs both commands at the same time (in my experience) when you only want to use one, which slows down reloading.

**Comment by jaredlll08** [comment]
uh
mods don't add reload commands
it is added by vanilla.
https://minecraft.fandom.com/wiki/Commands/reload

**Comment by pm065** [comment]
Oh, right. Sorry!
