### ISSUE TITLE
(1.16) Attempting to create an Ex Nihilo crooking recipe breaks custom recipes that use a modded recipe manager (or wiki is outdated)

### ISSUE THREAD

**Issue by pm065** [CraftTweaker/CraftTweaker#1226]
#### Intro:  
The wiki says you need to use
`<recipetype:exnihilosequentia:crook>.create("crook_test").setInput(<item:minecraft:oak_leaves>).addDrop(<item:minecraft:nether_star>, 1);`
to add an Ex Nihilo Sequentia crook recipe, but adding this (with modified output of course) appears to break the mod.
Either the method is broken, the wiki is wrong, or I am even more hilariously incompetent than I thought.

#### Issue Description:  
All CraftTweaker recipes that use a modded recipe manager (excepting, for some reason, the dirt to Environmental mud ENS fluid item transformation recipe I added) break if you try to create a Crooking recipe.

#### What happens:
Attempting to use the aforementioned method to create a Crooking recipe appears to cause almost all custom recipes that use a modded recipe manager (such as my custom spawn egg recipes using the Botania petal apothecary) to vanish and the custom crook recipe does not appear. An exception appears to be the ENS fluid transformation recipe I mentioned above.
Something strange also appears when you /reload: between 'CraftTweaker reload starting!' and 'CraftTweaker reload complete!', the text 'Index: 0, Size: 0 Index 0, Size: 0' appears, which does not happen normally (the double Index: 0, Size: 0 is not a typo, that's what is printed in the chat). Vanilla recipe managers seem to be unaffected: custom crafting table recipes still work.
It's possible the wiki has the wrong method documented, and I am following outdated information.
(The RemoveRecipe method for the crook still works, though.)

#### What you expected to happen:  
I expected the custom crook recipe to be successfully created, and I certainly expected it to not break all the other recipes.

#### Script used:  
https://gist.github.com/pm065/0b257ba64d354900681ccae4f0be386a
Both CT log and scripts are in this gist

#### crafttweaker.log file:  
https://gist.github.com/pm065/0b257ba64d354900681ccae4f0be386a
Both CT log and scripts are in this gist - there seems to be an issue pertaining to the crook in the log

#### Environment:  
- Minecraft Version: 1.16.5
- Forge Version: forge-36.1.3
- CraftTweaker Version: CraftTweaker-1.16.5-7.1.0.178
- Are you using a server: No

#### Game log:  
Hopefully this is the correct log:
https://gist.github.com/pm065/5f5a72e2542967ed0c4695548f4cd8b9

**Comment by jaredlll08** [comment]
Please don't change the script file when giving it to us, I spent a good few minutes trying to figure out how line 16 was causing the issue.


Report this to the exnihilo mod directly, the issue is:
https://github.com/NovaMachina-Mods/ExNihiloSequentia/blob/1.16/src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/builder/ZenCrookRecipe.java#L19
creates an empty list, and then when they do:
https://github.com/NovaMachina-Mods/ExNihiloSequentia/blob/1.16/src/main/java/novamachina/exnihilosequentia/api/crafting/crook/CrookRecipe.java#L23

it fails because well, the list is empty
