### ISSUE TITLE
Request to implement moveForward method on player

### ISSUE THREAD

**Issue by tyon2006** [CraftTweaker/CraftTweaker#1228]
**Feature request name**
Request to implement moveForward method on player

**Feature request description**
I'd like to be able to replicate this effect on a custom trait I've created with CT:
https://github.com/Coders-After-Dark/Reskillable/blob/develop/1.12.2/src/main/java/codersafterdark/reskillable/skill/agility/TraitRoadWalk.java#L17

I cannot, because it is missing the implementation of moveForward.

**Game Version
1.12.2

**Comment by democat3457** [comment]
Do you mean the moveForward variable or the moveRelative method? Or both?

**Comment by jaredlll08** [comment]
He wants both

**Comment by tyon2006** [comment]
^^ What Jared said. Only a novice sorry for the misunderstanding.

**Comment by democat3457** [comment]
Should be fixed by 59a1d4036b43604f245c76a0588853a49b5c900f
