### ISSUE TITLE
McAnvilUpdateEvent Bug

### ISSUE THREAD

**Issue by GoldenDecoder** [CraftTweaker/CraftTweaker#1230]
When using McAnvilUpdateEvent setters aren't registered causing the event not to work.

**Comment by democat3457** [comment]
How specifically does it not work? Can you send script, logs?

**Comment by GoldenDecoder** [comment]
Yeah I can get that to you here soon, I'm not home. I know Jared has some further information. I was speaking to him over on discord as he was showing me how to use it and we both got the issue so he wanted me to post the issue on here so there was a tracker of the bug. I have the script stored somewhere on discord so when I have better connection I'll get that on over.

**Comment by democat3457** [comment]
found the original post: https://canary.discord.com/channels/136877912698650625/354745056743260172/826343226344603698

**Comment by jaredlll08** [comment]
The tl;dr is, we don't register setters for expansions, only getters, I had a fix then I reset my code for some reason
