### ISSUE TITLE
Can not cast IFluidStack to MCTagWithAmount<MCFluid>

### ISSUE THREAD

**Issue by ZCrafter** [CraftTweaker/CraftTweaker#1234]
#### Intro:  
I'm trying to change a recipe in the Immersive Engineering Refinery

#### Issue Description:  
My own custom pack. Chat displays, can not cast IFluidStack to MCTagWithAmount<MCFluid>. Also, it points to the line where I try to change the recipe.

#### What happens:  
Chat says, can not cast IFluidStack to MCTagWithAmount<MCFluid>. And scripts are invalid

#### What you expected to happen:  
Recipe changed and scripts are valid

#### Script used:  
InustrialForegoing.zs  https://pastebin.com/AV990C0a

#### crafttweaker.log file:  
https://pastebin.com/XmEt9aCk

____
#### Environment:  

- Minecraft Version:
- Forge Version: 36.0.46
- CraftTweaker Version: 7.1.0.193
- Are you using a server: No

**Comment by kindlich** [comment]
Check the docs:
<https://docs.blamejared.com/1.16/en/mods/ImmersiveEngineering/Refinery/#add-recipe>

As the error message tells you, the inputs both need to be tags, not FluidStacks.
You provide  a tag and a FluidStack as input and a FluidStack as output
