### ISSUE TITLE
Game crashes during loading

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#1238]
#### crafttweaker.log file:  my game crashes so i can't add this

____
#### Environment:  

- Minecraft Version: 1.12.2
- Forge Version: forge-1.12.2-14.23.5.2854
- CraftTweaker Version: CraftTweaker2-1.12-4.1.20.607
- Are you using a server: no
- If yes, does the client have the exact same scripts?

**Comment by jaredlll08** [comment]
You are using mods that depend on tinkers construct but don't have tinkers construct installed (according to the log)

**Comment by jaredlll08** [comment]
Actually, you do have tinkers in the pack (didn't come up in my first search), but you are missing modtweaker

**Comment by ghost** [comment]
thanks, it works now
