### ISSUE TITLE
The return of /ctgui ?

### ISSUE THREAD

**Issue by DaraSilverDragon** [CraftTweaker/CraftTweaker#1242]
**Feature request name**
Update of in-game GUI features to 1.16.*+

**Feature request description**
Like it says on the tin - it would be great if the /ctgui command could be brought back from the hellscape of 1.12 and brought into the light of the latest game versions. Every addon project I've seen to do this died back in 1.12 when a native gui was added, and none of them seem to have come back in the advent of its removal. I'm sorry if this is a common request, but I saw no open requests that included it when I searched, so baseline due diligence just wasn't enough.

**Feature request reason**
While I appreciate that this is really more of a mod for big-brain dedicated pack creators who make amazing things like RLCraft, there are still smoothbrains like me who want to make small custom packs for their buddies using simple modded launchers like Gorilla/Koala, and end up just needing to make a single recipe change for the pack to work. In my particular case, for example, the NoTreePunching mod disables wooden tool recipes and replaces them with flint ones... but the Farmer's Delight mod requires a wooden shovel for its main feature block. If I could just replace that one wood shovel recipe for a flint one, that's all the pack needs to be perfectly playable... but as it stands, I apparently need a Java certification to make that one minor recipe tweak, and reading the wiki documentation for this mod makes me want to sharpen my keyboard and commit honorable sudoku.

**Feature request dependencies**
none that I'm aware of

**Game Version
1.16.*

and before anyone tries to make fun of me for coming on github and asking to be babied while knowing nothing about coding, don't waste your time - my brain is too smooth, your jabs will slide right off. It's not like this mod didn't used to be idiot-friendly in the past

**Comment by jaredlll08** [comment]
You are correct that there have been no issues about this on the github, but it has been talked a lot about in the discord (https://discord.blamejared.com)

Basically the reasoning as to why it isn't coming back is:

```
- The user interface was horrible
- like seriously horrible, no user feedback, I just assumed people would know to right click the slots and it just wasn't good. 
- The scripts it produced weren't always correct
- It was basically limited to the crafting table recipes
- The scripting language really isn't that bad, if what you want to do can be done via the GUI, then it should be extremely simple to code. 
- on the point above, it is basically adding a whole complicated system to assist in writing very basic scripts 
- Can't do anything fancy with loops
- Not easy to update scripts that have been written (if you added a recipe, then decided to change it later, there is no way to do that in the gui and the file tells you not the touch it
 ```

As for the docs, we know they need work, there just isn't enough time in the day to do everything, and I can promise you now that in the time it would take to remake ct gui, if the docs had that time then there wouldn't be an issue with them.

The discord is rather active with people helping out, so if you need help, please feel free to ask there :)
