### ISSUE TITLE
Basic Villager Trading

### ISSUE THREAD

**Issue by tikiMC** [CraftTweaker/CraftTweaker#1243]
-Basic Villager Trading.

-Need a way to remove basic villager trades to get rid of certain items that wouldn't be obtainable anywhere outside of trading.

- 1.16.5 plz and thank you

**Comment by kindlich** [comment]
That's already implemented.
Check this docs site which describes the methods
<https://docs.blamejared.com/1.16/en/vanilla/api/villager/VillagerTrades/>

**Comment by jaredlll08** [comment]
There is a BasicTrade class that we don't support for removals yet, they are asking to support that

**Comment by jaredlll08** [comment]
This apparently isn't fixed, will need to test with:
https://github.com/team-abnormals/environmental

**Comment by jaredlll08** [comment]
```zenscript
villagerTrades.removeBasicTrade(<profession:minecraft:farmer>, 1, <item:minecraft:emerald>, <item:environmental:rice>);
```
I have tested as working
