### ISSUE TITLE
removeRecipe not working with Blood Magic, maybe with other mods too...

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#1255]
#### What happens:  
RemoveRecipe not working with Blood Magic machines after updating from 7.0.1.221 to 7.0.1.223 and up.
Error from chat: `com.blamejared.crafttweaker.impl.actions.recipes.ActionRemoveRecipeByOutput.<init>(Lcom/blamejared/crafttweaker/api/managers/IRecipeManager;Lcom/blamejared/crafttweaker/api/item/IItemStack;)V: com.blamejared.crafttweaker.impl.actions.recipes.ActionRemoveRecipeByOutput.<init>(Lcom/blamejared/crafttweaker/api/managers/IRecipeManager;Lcom/blamejared/crafttweaker/api/item/IItemStack;)V`
#### Script used:  
`<recipetype:bloodmagic:arc>.removeRecipe(<item:bloodmagic:sulfur>);`
#### Environment:  
- Minecraft Version: 1.16.5
- Forge Version: 36.1.13
- CraftTweaker Version: 7.0.1.251
- Are you using a server: no

**Comment by jaredlll08** [comment]
We need the log from `/ct log` not the chat, also it needs to be in pastebin

**Comment by ghost** [comment]
https://paste.ee/p/pqRpB
