### ISSUE TITLE
[1.16] Could not down-cast

### ISSUE THREAD

**Issue by friendlyhj** [CraftTweaker/CraftTweaker#1262]
#### Intro:  
Could not down-cast

#### What you expected to happen:  
Can down-cast after instanceof check.

#### Script used and crafttweaker log
https://gist.github.com/friendlyhj/367add6a8c7ea49a9c8c596db8483227
____
#### Environment:  

- Minecraft Version: 1.16.5
- Forge Version: 36.0.42
- CraftTweaker Version: 7.1.0.257
- Are you using a server: no

**Comment by democat3457** [comment]
try only using casts on the left side for an unchecked cast

**Comment by friendlyhj** [comment]
Oh, I forgot to post error when casting only on the left side.
https://paste.ubuntu.com/p/5Cgc48bQd8/
