### ISSUE TITLE
Tooltip clearing does not work properly

### ISSUE THREAD

**Issue by IchHabeHunger54** [CraftTweaker/CraftTweaker#1264]
#### What happens:
Tooltip clearing does not work properly. See the following screenshot:
![image](https://user-images.githubusercontent.com/52419336/117029482-fe1e4780-acfe-11eb-913f-9970c5366f9e.png)

#### What you expected to happen:
For it to work properly...? This is what it looks like without that line:
![image](https://user-images.githubusercontent.com/52419336/117029188-b4356180-acfe-11eb-9d08-01ed77b3cf66.png)
The lines:
- Item Name
- Tooltip (which is the thing to be removed)
- Advanced Tooltips
- JEI Integration's Max Stack Size Information
- Mod Id (JEI)

#### Script used:
Relevant code:
`<item:cyclic:laser>.clearTooltip();`

#### crafttweaker.log file:
Log acts like everything is fine, there are no errors; this is the only line even containing "tooltip":
`[17:17:35.310][DONE][CLIENT][INFO] Clearing the tooltip for: <item:cyclic:laser>`

____
#### Environment:
- Minecraft Version: 1.16.5
- Forge Version: 36.1.0
- CraftTweaker Version: 7.1.0.252
- Are you using a server: no

**Comment by jaredlll08** [comment]
Tooltip clearing works fine.

The tooltip is all the text in the blue box, so the actual lines are just:

* Tooltip (which is the thing to be removed)

The tooltip is given to us in a `List<ITextComponent>` and we quite literally just call `.clear();` 
https://github.com/CraftTweaker/CraftTweaker/blob/98844b8cb5523a8fd500a0ffe5aaabd14cabbaef/src/main/java/com/blamejared/crafttweaker/impl/actions/items/tooltips/ActionClearTooltip.java#L23


If you want to remove specific lines of the tooltip, use `removeTooltip(String regex)`.


As for the modid, that isn't part of the tooltip, if you look at the item in your inv vs in JEI, you will see that JEI shows the modid while your inventory doesn't (shouldn't anyway).

This is how JEI does it, and why we can't clear it:

https://github.com/mezz/JustEnoughItems/blob/HEAD/src/main/java/mezz/jei/render/IngredientRenderHelper.java#L25-L26

**Comment by IchHabeHunger54** [comment]
Ok, my bad then.

**Comment by jaredlll08** [comment]
It's all good, when I was first messing with it I was also under the impression that the name / modid wasn't the *tooltip*.

As for the JEI stuff, I actually thought that was a bug until I looked into it, it is kinda weird how it is a hardcoded tooltip
