### ISSUE TITLE
removeEmeraldForItemsTrade is broken?

### ISSUE THREAD

**Issue by tikiMC** [CraftTweaker/CraftTweaker#1265]
#### Issue Description:  
Villager trades aren't being removed.

#### What happens:  
Trade isn't removed

#### What you expected to happen:  
For trades to be removed lol

#### Script used: 
https://pastebin.com/NFjU2zKd

#### crafttweaker.log file:  
https://pastebin.com/ym3DkamX

- Minecraft Version:1.16.5
- Forge Version:36.1.0
- CraftTweaker Version: 7.1.0.257
- Are you using a server: No

**Comment by jaredlll08** [comment]
Banners are `ItemsForEmeraldsTrade` trades, not `EmeraldForItemsTrade`.

Same with the Bell.

I know it is confusing and dumb, I'll look into finding a way to print the trades out with their type

**Comment by jaredlll08** [comment]
For reference, `EmeraldForItemsTrade`s are things like:
```
new VillagerTrades.EmeraldForItemsTrade(Items.WHEAT, 20, 16, 2)
```
Where the villager will buy 20 wheat, and give the player an emerald
