### ISSUE TITLE
Cant use GalacticraftCore items in crafting

### ISSUE THREAD

**Issue by ZTCraftCat** [CraftTweaker/CraftTweaker#1267]
#### Issue Description:  
Cant use GalacticraftCore items ingredients ore a recipe output when creating a recipe.

#### What happens:  
there are a lot of "red lines"(bugs).

#### What you expected to happen:  
I expected everything will work fine.

#### Script used:  
https://gist.github.com/ZTCraftCat/6acc254a4674801ff0f7aeb5ba8dbea2#file-crafting
ONLY LINES 19-47 

#### crafttweaker.log file:  
https://gist.github.com/ZTCraftCat/26f3b6c937af84bfcfc13b25f3fc8593#file-crafttweakerlog

____
#### Environment:  

- Minecraft Version:1.12.2
- Forge Version: forge-14.23.5.2854
- CraftTweaker Version: CraftTweaker2-1.12.4.1.20.646.jar
- Are you using a server: no
- If yes, does the client have the exact same scripts?

#### Game log:  
https://gist.github.com/ZTCraftCat/9b64720c2af0619eed0462523ac98eca#file-gamelog

**Comment by jaredlll08** [comment]
You have the incorrect item names.

The modid is `galacticraftcore` not `GalacticraftCore`.

Hold the items in your hand and use `/ct hand` to get the correct names.
