### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by mondis1337** [CraftTweaker/CraftTweaker#1270]
#### Intro:  

This is datapack issue

#### Issue Description:  

When I try to start my server, crafttweaker crashes
tried several versions

#### What happens:  
server crashes

#### What you expected to happen:  
for server to successfully start up

#### Script used:  

i don't have any scripts

#### crafttweaker.log file:  

https://pastebin.com/Pxu4Xx19
____
#### Environment:  

- Minecraft Version: 1.16.5
- Forge Version: 36.1.16
- CraftTweaker Version: 7.1.0.265
- Are you using a server: yes, Mohist
- If yes, does the client have the exact same scripts? yes

#### Game log:  

https://gist.github.com/mondis1337/63c8f1f75cc284736d8f0353ef6c6d67#file-gistfile1-txt-L4559

**Comment by kindlich** [comment]
That's a known issue in relation with how DynamicTrees handles reloads. 
At this point I can't say whether it's on our side or theirs, but it seems a classloading issue when both are combined.

Leaving this open until it's confirmed that it's fixed, keep a look out for new DT versions as well.

**Comment by kindlich** [comment]
A few minutes ago, the Beta8 of DynamicTrees was released.
<https://www.curseforge.com/minecraft/mc-mods/dynamictrees/files/3302576>

It was fixed by a change on their end, so I'm closing this issue.
