### ISSUE TITLE
Custom furnace recipe consumes fuel, but doesn't smelt items

### ISSUE THREAD

**Issue by joker876** [CraftTweaker/CraftTweaker#1275]
#### Intro:  
A custom furnace recipe I made doesn't work. The furnace consumes provided fuel, but the items don't get smelted. On the image below you can see the furnace burning, but the gravel not being processed. The recipe shows up in JEI correctly. I am using the standard, vanilla furnace. I also tried with a vanilla fuel, same results.
![image](https://user-images.githubusercontent.com/42680429/118320504-a355ce80-b4fc-11eb-95c1-9b17a32b45d2.png)
![image](https://user-images.githubusercontent.com/42680429/118320899-24ad6100-b4fd-11eb-8643-51736e0ac86c.png)

#### Issue Description:  
This bug occurs in the [modpack I created](https://www.curseforge.com/minecraft/modpacks/creative-skyblock). I also tested with a modpack containing only JEI and CT, with same results.

#### What happens:  
The furnace consumes provided fuel, but the items don't get smelted.

#### What you expected to happen:  
The item should be smelted normally.

#### Script used:  
```
import crafttweaker.api.FurnaceManager;

furnace.addRecipe("gravel-andesite", <item:minecraft:andesite>, <item:minecraft:gravel>, 1.0, 0);
```

#### crafttweaker.log file:  
https://pastebin.com/V7MJzCax

____
#### Environment:  
- Minecraft Version: 1.16.5
- Forge Version: 36.1.0
- CraftTweaker Version: 7.1.0.283
- Are you using a server: No

#### Game log:  
https://pastebin.com/Ke6cw4fN

**Comment by jaredlll08** [comment]
You can't make recipes with a `cookTime` of `0`, it needs to be *at-least* `1`.
