### ISSUE TITLE
what is the problem with the three first ingredients

### ISSUE THREAD

**Issue by comcomYT** [CraftTweaker/CraftTweaker#1284]
recipes.addShaped("power_stone", <infinity:power_stone>, [[<lucraftcore:injection>.withTag({Injection: "heroesexpansion:kryptonian"}).transformReplace(<lucraftcore:injection>)]), <avaritia:endest_pearl>, <lucraftcore:injection>.withTag({Injection: "heroesexpansion:kree_hybrid"}).transformReplace(<lucraftcore:injection>)])],
                                                         [<avaritia:resource:6>, <actuallyadditions:item_misc:19>, <avaritia:resource:6>],
                                                         [<avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>];

**Comment by jaredlll08** [comment]
No idea. Use the issue template, github strips formatting away, so I literally can it help you because I don't know if github has stripped stuff away or if you just never had it there in the first place.


Also discord is way more suited for questions like this.

htrps://discord.blamejared.com
