### ISSUE TITLE
Try to add Items to Loottable 

### ISSUE THREAD

**Issue by 1qa2ws3ed4rf5tg6zh** [CraftTweaker/CraftTweaker#1285]
#### Intro:  
I wanted to make a small modpack for me and my Friends. Now i try to include items from other mods to the loottable of the "chocolate quest repoured" chest. 
to help with this i´m using Loottweaker

#### Issue Description:  

Game sends a error message and don´t load the script

#### What happens:  
nothing exept a error message 
th content af the Loottable i want to change stay the same

#### What you expected to happen:
find changed Loottables after loading the game   
if i summon a chest it should have the additional items

#### Script used:  

https://pastebin.com/y8Gkw800

#### crafttweaker.log file:  

https://pastebin.com/0Kw8ni05

____
#### Environment:  

- Minecraft Version:1.12.2
- Forge Version:14.23.5.2855
- CraftTweaker Version: 1.12-4.1.20.646

**Comment by jaredlll08** [comment]
on line 22:
```zenscript
PoolClutterThaumCrystal.addItemEntryHelper(thaumCrystal[], 1, 0, 
```

It should be:
```zenscript
PoolClutterThaumCrystal.addItemEntryHelper(thaumCrystal, 1, 0, 
```
