### ISSUE TITLE
[1.16] Replacer#forOutput

### ISSUE THREAD

**Issue by friendlyhj** [CraftTweaker/CraftTweaker#1288]
**Feature request name**
Add `forOutput` method in `Replacer` to define only recipes with specific output would be replaced.

**Feature request reason**
Of course, I can use `Replacer#forRecipes`. But it needs to loop over all recipes to find all recipes with specific output. It breaks the rule that Replacer should loop only once.

**Feature request dependencies**
no

**Game Version**
1.16

**Comment by TheSilkMiner** [comment]
Added in cf100ad37c59d6a32ec41a5ed38661e7f7de0540
