### ISSUE TITLE
print all recipe names for an item

### ISSUE THREAD

**Issue by Wxrlds** [CraftTweaker/CraftTweaker#1289]
**Feature request name**
Print all recipe names for an item

**Feature request description**
Basically another argument to the ``/ct hand`` command called ``recipeName`` so you can do ``/ct hand recipeName`` and it prints out every recipe name for that item.
When an item has multiple recipes like the Botania Elven Quartz. It would print out both recipe names so in this specific example that would be "botania:elven_trade/elf_quartz" and botania:mana_infusion/elf_quartz_deconstruct".

**Feature request reason**
Most JSON recipes can only be removed when specifying the recipe name so to remove a recipe like the Polonium Pellet from Mekanism you have to use this name "mekanism:processing/lategame/polonium_pellet/from_reaction". This command would allow us to get the recipe name within a few seconds instead of typing the recipe name manually or searching the recipe name from ``/ct dump recipes``.

**Feature request dependencies**
This would definitely save time no matter if you have other mods installed or not.

**Game Version
1.16.5

**Comment by jaredlll08** [comment]
```
/ct recipes
/ct recipes hand
```
