### ISSUE TITLE
IItemStack.clearTag();

### ISSUE THREAD

**Issue by slava110** [CraftTweaker/CraftTweaker#1291]
## Feature request name
Method to remove NBT tags from itemstack

## Feature request description
Add `IItemStack.withoutTag()` or `IItemStack.clearTag()` or allow null values in `IItemStack.withTag(@Nullable tag)` to remove NBT tag from itemstack

## Feature request reason
Might be useful for recipe transformers & event handlers. For me it's useful because we want to remove empty NBT tags from items but I think there are more cases when it will be useful

## Game Version
1.12+

**Comment by friendlyhj** [comment]
1.12 `IItemStack.removeTag(null)`

**Comment by slava110** [comment]
Nice, it works! Not stated in documentation tho? Or maybe I missed it somehow?

**Comment by democat3457** [comment]
~~also `IItemStack.withEmptyTag()`~~ nvm thats what you were trying to remove lol

**Comment by slava110** [comment]
Nice, thanks again c: I'm closing this issue then (not closed automatically, probably because it's different GitHub repository)
