### ISSUE TITLE
Mirrored recipes are mirrored on all axis

### ISSUE THREAD

**Issue by jaredlll08** [CraftTweaker/CraftTweaker#1295]
I don't actually know if this is unintended behaviour, but it is something that I feel needs addressing in general.
with vanilla, a "mirrored" recipe does:
![image](https://user-images.githubusercontent.com/5553605/120943582-18997580-c730-11eb-9e79-b550cffd75d2.png)
![image](https://user-images.githubusercontent.com/5553605/120943584-19caa280-c730-11eb-92f4-5d8317c3aef4.png)
but this does not work:
![image](https://user-images.githubusercontent.com/5553605/120943586-1cc59300-c730-11eb-9766-9fb87b720e27.png)

With one of our mirrored recipes however...

![image](https://user-images.githubusercontent.com/5553605/120943589-23eca100-c730-11eb-86fd-fd0a8dec186c.png)
![image](https://user-images.githubusercontent.com/5553605/120943591-264efb00-c730-11eb-8ec4-6fc9bc5e456b.png)

It is mirrored on both axis, I feel we should probably have an option to choose *how* it is mirrored

**Comment by democat3457** [comment]
does that happen on all versions?

**Comment by jaredlll08** [comment]
probably all versions of 1.13+ that support mirrored recipes.

I don't remember if it worked like this in 1.12

**Comment by democat3457** [comment]
![image](https://user-images.githubusercontent.com/32407067/120966981-92c7fb00-c72c-11eb-904a-c195e17156ab.png)
:|

**Comment by jaredlll08** [comment]
So the question is, should it act like this? 

I was thinking about adding a param that would let you dictate how it is mirrored, would need to be after the functions though, but it would give you more control over if it is mirrored left to right, top to bottom or both

**Comment by democat3457** [comment]
> should it act like this?

probably not, no

> I was thinking about adding a param...

I was thinking the same lol, would also probably default to horizontal mirror rather than all mirror - the param could also be at the beginning before the output and all and have the default overload? i.e.,

```less
recipes.addShapedMirrored("test1", MirrorType.VERTICAL, <minecraft:diamond>, ...);
recipes.addShapedMirrored("defaults", <minecraft:dirt>, ...); // defaults to MirrorType.HORIZONTAL
```

**Comment by jaredlll08** [comment]
In the interest of not breaking stuff, I feel the default should be as it currently is now, for all we know someone was relying on this being both ways.

The overload could totally have it at the start though, would be somewhat cleaner
