### ISSUE TITLE
Garden Cloche Compatibility

### ISSUE THREAD

**Issue by marcobsidian** [CraftTweaker/CraftTweaker#1297]
Hiya, so this is about the 1.12.2 Version of the Mod. I know, many Mod Creators don't do updates on these versions anymore, but I thought I'd try anyways, hoping for an exception on this amazing tool mod.

While looking through the Wiki I saw that the IE Garden Cloche is configurable in newer versions, but not on 1.12.2. Would it be possible to add this functionality to the 1.12.2 Version of the Mod? The Garden Cloche is an amazing tool only held back by its very limited crop pool and that there is a very limited amount of Compat Mods that all are not maintained anymore.

I honestly don't even care how long i'd have to wait for this feature but I sincerely hope that -if it is possible- it could be added to some older versions to allow Modpack Creators to use it as a tool for speedy crop generation.

I personally would love to use it to quickly grow crops from Pixelmon, for example Berries or Apricorns, which there are no compat mods for at all and I personally don't know how to realise it myself.

I understand if there are no plans to further maintain 1.12.2 but I really hope for a positive response :D

Thanks for your time
~Marco

**Comment by jaredlll08** [comment]
Immersive Engineering adds their own compat, not us.

Saying that, as you said, 1.12, they are not going to backport it (if it is even possible).
