### ISSUE TITLE
[1.12.2] Crash when tweaking mob drops

### ISSUE THREAD

**Issue by v1993** [CraftTweaker/CraftTweaker#1299]
#### What happens:  
When using `addDrop` with 0 as possible value game crashes if entity is killed by non-player damage (known to happen with lava and wild wolves).

To reproduce, use script

```
<entity:minecraft:sheep>.addDrop(<minecraft:stone>, 0, 1);
```

Then set a group of sheep on fire (direct kills by player won't do). On one of deaths the game will crash.

#### What you expected to happen:  
Either script error if 0 isn't an acceptable value for `addDrop` or just normal functioning of game if it is.

____
#### Environment:  

- Minecraft Version: 1.12.2
- Forge Version: 14.23.5.2854
- CraftTweaker Version: 4.1.20.648
- Are you using a server: no
- If yes, does the client have the exact same scripts? Not using a server

#### Game log:  
Crash log: https://pastebin.com/7rciJeHT.

**Comment by jaredlll08** [comment]
Fixed by a PR
