### ISSUE TITLE
/CT Recipe Hand gives an unexpected error. 

### ISSUE THREAD

**Issue by Dandas52** [CraftTweaker/CraftTweaker#1307]
#### Issue Description:  
/CT Recipe hand gives the following error: https://imgur.com/a/cQKs6WN
The issue doesn't appear to be caused by RFTools Utility - disabling it simply moves the location of the error elsewhere. 
https://imgur.com/a/8015Fa1

#### CraftTweaker Version: 
7.1.0.314

#### Steps to reproduce: 
Hold an item in hand, and use the CT Recipe Hand command.

**Comment by jaredlll08** [comment]
Those images don't exist anymore, please can you repost them

**Comment by Dandas52** [comment]
Reposted.

**Comment by TheSilkMiner** [comment]
Fixed in ffb46e68737a81b3bf636293f7bc22d482824b38
