### ISSUE TITLE
[1.16] Recipe type of Block Transmutation from Astral Sorcery didn't work.

### ISSUE THREAD

**Issue by liuseniubi** [CraftTweaker/CraftTweaker#1308]
#### Issue Description:  
<recipetype:astralsorcery:block_transmutation> didn't work.

#### What happens:  
It just doesn't work correctly.

#### What you expected to happen:  
Make it work well.

#### Script used:  
https://paste.ubuntu.com/p/bHzSwBxpxw/
Neither of these methods works.

#### crafttweaker.log file:  
https://paste.ubuntu.com/p/kTwB8PnGqs/

____
#### Environment:  

- Minecraft Version: 1.16.5
- Forge Version: 36.1.31
- CraftTweaker Version: 7.1.0.314
- Are you using a server: No
- If yes, does the client have the exact same scripts?

#### Game log:  
https://paste.ubuntu.com/p/DcBYWRPF3W/

**Comment by jaredlll08** [comment]
Telling us it doesn't work is useless.

How doesn't it work?
What are you actually trying to do?
What happens currently?
Why is your log complaining about
```
Invalid constellation key: "astralsorcery:aevitasis"
```
on line 1 of `test.zs` but the script file you gave us doesn't mention it or even use a constellation?

**Please** be more descriptive.

**Comment by liuseniubi** [comment]
> Telling us it doesn't work is useless.
> 
> How doesn't it work?
> What are you actually trying to do?
> What happens currently?
> Why is your log complaining about
> 
> ```
> Invalid constellation key: "astralsorcery:aevitasis"
> ```
> 
> on line 1 of `test.zs` but the script file you gave us doesn't mention it or even use a constellation?
> 
> **Please** be more descriptive.

Sorry for my poor description.
I'm trying to transform Basic Table from Extended Crafting to Luminous Crafting Table. But when I put it under the crystal, just nothing happened.

**Comment by liuseniubi** [comment]
And I used [this script](https://github.com/HellFirePvP/AstralSorcery/blob/e755a5c10bd19336cc7aeed563d444e8a8460fae/src/main/resources/data/astralsorcery/scripts/astralsorcery/block_transmutation.zs) too, just nothing happened when I put it under the Floating Crystal.

**Comment by jaredlll08** [comment]
I'm unable to reproduce, using both:
```zenscript
<recipetype:astralsorcery:block_transmutation>.addRecipe("transmutation_test", <blockstate:minecraft:diamond_block>, <blockstate:minecraft:dirt>, true, 200, <resource:astralsorcery:horologium>);

<recipetype:astralsorcery:block_transmutation>.addRecipe("test1", <blockstate:astralsorcery:altar_discovery>, <blockstate:minecraft:furnace>, false, 60);
```

I can craft both recipes

I did swap out the extreme crafting table with a furnace in my test as I don't have the mod in my environment, but the first recipe should work.

I'm just checking, when you say:
> just nothing happened when I put it under the Floating Crystal.

You are linking the crystal to the block correct, not just putting it under the crystal?

**Comment by liuseniubi** [comment]
> I'm unable to reproduce, using both:
> 
> ```zenscript
> <recipetype:astralsorcery:block_transmutation>.addRecipe("transmutation_test", <blockstate:minecraft:diamond_block>, <blockstate:minecraft:dirt>, true, 200, <resource:astralsorcery:horologium>);
> 
> <recipetype:astralsorcery:block_transmutation>.addRecipe("test1", <blockstate:astralsorcery:altar_discovery>, <blockstate:minecraft:furnace>, false, 60);
> ```
> 
> I can craft both recipes
> 
> I did swap out the extreme crafting table with a furnace in my test as I don't have the mod in my environment, but the first recipe should work.
> 
> I'm just checking, when you say:
> 
> > just nothing happened when I put it under the Floating Crystal.
> 
> You are linking the crystal to the block correct, not just putting it under the crystal?

Oh, you remind me that point, I'll have a try, thanks for your help! If I still meet some troubles, I'll comment here.
