### ISSUE TITLE
.transformDamage not applied to to the mirror of mirrored recipes.

### ISSUE THREAD

**Issue by PSYberition** [CraftTweaker/CraftTweaker#1310]
### Issue description

.transformDamage() does not apply to the mirrored version of a recipe.  The recipe you specify will work as dictated, however the mirrored version will be consumed entirely.

### Script used

https://pastebin.com/hMXT2SmK

### Minecraft version

1.16

### Forge version

36.1.32

### CraftTweaker version

7.1.0.316

### Other relevant information

This is occurring in a modpack I am currently working on.  Version 0.2.9.3 [here](https://www.curseforge.com/minecraft/modpacks/psymcraft/files).

I was just informed this information isn't required for this issue, but I already typed it, so there it is... just in case.

**Comment by democat3457** [comment]
I wonder if this happens on 1.12

**Comment by jaredlll08** [comment]
It does not, fixing this now and looked at 1.12 to see if it was affected

**Comment by democat3457** [comment]
Good, lol
