### ISSUE TITLE
(1.12.2) Game freezes while finishing up CraftTweaker. 

### ISSUE THREAD

**Issue by AlexX07** [CraftTweaker/CraftTweaker#1312]
### Issue description

When I'm loading the game and it reaches phase 6 and starts loading crafftweaker it freezes. I have seen that there are people who have reported similar errors but none of their solutions works for me, I still do not understand why it does not work since I have not even added scripts yet.

### Script used

I use no scripts yet

### The crafttweaker.log file

https://gist.github.com/AlexX07/e424525f1489e132b7aedf6df6b12588

### Minecraft version

1.12

### Forge version

14.23.5.2854

### CraftTweaker version

4.1.20.652

### The latest.log file

https://gist.github.com/AlexX07/d7501b091313e795d070f37630921abd

**Comment by jaredlll08** [comment]
it should be doing basically nothing if there are no scripts loaded.

Also all the other solutions require a script to be present to use, so not sure how you tried those.

How much RAM are you allocating and can you reproduce this?

**Comment by AlexX07** [comment]
I'm stupid,  the problem was the ram, only 4gb...
