### ISSUE TITLE
Arc Furnace Recipes Not Working With JEI 

### ISSUE THREAD

**Issue by GustavoPudim** [CraftTweaker/CraftTweaker#1317]
### Issue description

When I add an **Arc Furnace** recipe, it works as expected, however when I try to open it in **JEI** the game crashes with the following message: _The game crashed whilst mouseclicked event handler
Error: java.lang.UnsupportedOperationException: null
Exit code: -1_

Forgive me if I should've posted this as a JEI issue.

### Script used

<recipetype:immersiveengineering:arc_furnace>.addRecipe("copper_ingot_from_dust", <item:thermal:copper_dust>, [<item:minecraft:air>], 100, 51200, [<item:thermal:copper_ingot>]);

### The crafttweaker.log file

https://gist.github.com/GustavoPudim/17a8eafb93c66f55f9ddee4a18384db6

### Minecraft version

1.16

### Forge version

36.1.0

### CraftTweaker version

7.1.0.349

### Other relevant information

JEI version: 7.7.1.110

### The latest.log file

https://gist.github.com/GustavoPudim/0f9246ff85e77df8d3e64ad187c64948

**Comment by jaredlll08** [comment]
Report to immersive engineering.

Also the log file you gave doesn't have any crash in it.
