### ISSUE TITLE
Mekanism scripts not working

### ISSUE THREAD

**Issue by grandogarndo** [CraftTweaker/CraftTweaker#1320]
### Issue description

When I make a script using the combiner in mekanism (located here: https://pastebin.com/XEKmp1ey ) it is recognized as invalid. crafttweaker log here: https://pastebin.com/96VyNmxg . Note that I learnt how to make that recipe from an old article, which may be the problem. I have successfully made vanilla scripts.

### Steps to reproduce

1. download crafttweaker, mekanism, compressium and compact cubes mod.
2. make a script using a mekanism machine

### Script used

https://pastebin.com/XEKmp1ey

### The crafttweaker.log file

https://pastebin.com/96VyNmxg

### Minecraft version

1.16

### Forge version

36.1.30

### CraftTweaker version

7.1.0.314

### The latest.log file

its too long for pastebin to recognize

**Comment by friendlyhj** [comment]
You are using 1.12 syntax. Did you see the error in crafttweaker.log?

**Comment by grandogarndo** [comment]
Yeah, I thought that might be the problem. But where would I find the new syntax for mekansim?

**Comment by grandogarndo** [comment]
Ok, I found this article: https://www.reddit.com/r/feedthebeast/comments/n48src/1165_mekanism_recipes_on_crafttweaker/ , and it says I can use a datapack, but how would I do that? is it even worth all the effort? I just want to make my casual modpack less easy.

**Comment by jaredlll08** [comment]
Mekanism is going to be getting built in CraftTweaker support in their next major version.

I'm not sure *when* they are going to release it (and please do not ask them for an eta).

If you don't want to wait we can help you register them using [`addJSONRecipe`](https://docs.blamejared.com/1.16/en/vanilla/api/managers/IRecipeManager/#g-addjsonrecipe) over on the discord.
https://discord.blamejared.com
