### ISSUE TITLE
Recipe not being removed

### ISSUE THREAD

**Issue by StrangerSon71** [CraftTweaker/CraftTweaker#1325]
### Issue description

Despite copy-pasting the remove a stick recipe, a bunch of errors show up.

### Script used

https://pastebin.com/CUF2RM3x
### The crafttweaker.log file

https://pastebin.com/567g87WE

### Minecraft version

1.16

### Forge version

36.1.65

### CraftTweaker version

7.1.0.350

### Other relevant information

My first script, probably missed something on the documentation (although I did check several times)

### The latest.log file

Too big for the Pastebin character limit

**Comment by jaredlll08** [comment]
We asked for a link to the script. Not for you to post the script in the text field just to have literally all the formatting that we care about be removed.

**Comment by StrangerSon71** [comment]
That's all there is to the script

**Comment by StrangerSon71** [comment]
Should I resubmit this with the link to the script?

**Comment by jaredlll08** [comment]
Github strips formatting.

```
<item:minecraft:dirt>
```
in not a code block looks like:

<item:minecraft:dirt>

pictured:
![image](https://user-images.githubusercontent.com/5553605/126730166-86de515a-d51e-4a7c-97a4-b954c8f844ac.png)



See what I mean?

Your log always mentions stuff all the way up to line 20.

You do not need to remake an issue, you can just give a link to the script file and I'll re-open this one.

**Comment by StrangerSon71** [comment]
Edited

**Comment by StrangerSon71** [comment]
https://pastebin.com/CUF2RM3x

**Comment by jaredlll08** [comment]
Your log is complaining about a file called `Untitled.zs`, is that the one that you've uploaded?

**Comment by StrangerSon71** [comment]
Yes.

**Comment by StrangerSon71** [comment]
Isn't a problem with the site, I can't remove any recipes,

**Comment by jaredlll08** [comment]
Not sure what to tell you, the log is 100% complaining about lines that don't exist in the script you gave:
```
Parser Exception @ Untitled.zs:20:51 
```
That is line 20, character 51
```
Parser Exception @ Untitled.zs:17:0
```
Line 17, character 0
etc

So you must have other content in the script that has not been uploaded.

If there is any error in the script, none of it is ran.

So are you 1000% sure that the file you gave is the ONLY script and there is nothing left out of it?

**Comment by StrangerSon71** [comment]
There might have been something else, will try to delete and see if it persists.

**Comment by StrangerSon71** [comment]
If I open it with Text Wrangler instead of TextEdit (Using Mac), I see this: https://pastebin.com/KTkmvMFg

**Comment by jaredlll08** [comment]
I have never used Mac or even heard of TextEdit, but I personally suggest that you use VSCode.
https://code.visualstudio.com/download

It is what I use.

all that other text is what is tripping the parser, delete it and it should work perfectly fine.

**Comment by StrangerSon71** [comment]
Thank you very very much!
