### ISSUE TITLE
Wandering Trader Bug

### ISSUE THREAD

**Issue by tikiMC** [CraftTweaker/CraftTweaker#1326]
### Issue description

Wandering Traders still trade modded items even when removed. ie: villagerTrades.removeWanderingTrade(1, <item:atmospheric:barrel_cactus>); still appears along with any other item from atmospheric.

This is fixed with /reload but this is very inconvenient to do every time you log into your world.

### Steps to reproduce

Load into a world, spawn in a wandering trader with an egg or /summon and behold items that shouldn't be tradeable.

If you are using the script I am the only things that should be tradeable are an allium in the first slot and gunpowder in the second.

### Script used

https://pastebin.com/99W0G3wi

### The crafttweaker.log file

https://pastebin.com/qPYr01cS

### Minecraft version

1.16

### Forge version

36.2.0

### CraftTweaker version

7.1.0.360

### The latest.log file

https://pastebin.com/2pHe8Gie

**Comment by evanbones** [comment]
I'm still having this issue on Forge 1.20.1, villagerTrades.removeWanderingTrade(1, <item:alexsmobs:banana_peel>); still causes Wandering Trades to spawn with banana peels

**Comment by jaredlll08** [comment]
Alex's mobs uses a custom trade class, there is no way for us to remove it as we don't know anything about it.
