### ISSUE TITLE
Help hide creative tabs in JEI

### ISSUE THREAD

**Issue by RECUSANT1** [CraftTweaker/CraftTweaker#1327]
### Describe the feature you'd like

Hi guys, I can't understand and find how to hide the creative tabs in JEI
When you press R to find out the craft of an item, the interface with the craft of the item pops up 
I need to remove this window, because I added another craft.

I use CraftTweaker and ConteinerTweaker.

### Minecraft version

1.12

**Comment by jaredlll08** [comment]
You can hide the category.
https://docs.blamejared.com/1.12/en/Mods/JEI/JEI/#hide-categories

**Comment by RECUSANT1** [comment]
> You can hide the category.
> https://docs.blamejared.com/1.12/en/Mods/JEI/JEI/#hide-categories

Lol, I looked everywhere, but not here. Thank you, I figured it out right away.
