### ISSUE TITLE
ERROR when replaceAllOccurences applied, with IC2's hidden recipes

### ISSUE THREAD

**Issue by lunareclipse-64** [CraftTweaker/CraftTweaker#1335]
### Issue description

When replaceAllOccurences used, this will always happen whether or not this items have anything to do with IC2
These recipenames are **the hidden recipes of IC2** , such as 3 tin ingots to a bucket.

### Steps to reproduce

When replaceAllOccurences used, whether or not this items have anything to do with IC2. The following script is just an example, any item can replace these. And the replace will not happen to any IC2 recipe ,but will happen to other recipes.

### Script used

https://paste.ubuntu.com/p/P89K4bjdYP/

### The crafttweaker.log file

https://paste.ubuntu.com/p/34ZvJZTW8j/

### Minecraft version

1.12

### Forge version

14.23.5.2855

### CraftTweaker version

4.1.20.655

### Other relevant information

Test instance, there are only 3 mods, crt, ic2(2.8.170-ex112) and jei.

### The latest.log file

https://paste.ubuntu.com/p/G9wf6pdmJZ/

**Comment by jaredlll08** [comment]
Fixed by https://github.com/CraftTweaker/CraftTweaker/commit/eb67c6b5483299e27ff4128de481134fa746ffc3
