### ISSUE TITLE
I think I found an issue in the game logs

### ISSUE THREAD

**Issue by vizthex123** [CraftTweaker/CraftTweaker#1341]
### Issue description

I've found this section at the top of the CT log:

Everything works fine though.

### Steps to reproduce

Load the game with CraftTweaker.

### Script used

https://gist.github.com/vizthex123/1e422c6d7317f122e82fd201fb7336b3

### The crafttweaker.log file

https://gist.github.com/vizthex123/1e422c6d7317f122e82fd201fb7336b3

### Minecraft version

1.16

### Forge version

36.2.0

### CraftTweaker version

7.1.0.371

### Other relevant information

The scripts load fine (as I said), so I just put the CT log in that section.

### The latest.log file

https://gist.github.com/vizthex123/9e29e3277fe8ef3022602aa307889ef1

**Comment by jaredlll08** [comment]
You didn't include the error in your post, not sure what I'm meant to be looking at.

If it is:
```
[12:39:59.871][CONSTRUCT][CLIENT][ERROR] Duplicate ZenCode Name 'mods.contenttweaker.functions.IItemRightClick' in classes 'interface com.blamejared.contenttweaker.api.functions.IItemInventoryTick' and 'interface com.blamejared.contenttweaker.api.functions.IItemRightClick'
```
That is known and I believe there is already a fix that just needs to be released

**Comment by vizthex123** [comment]
Yeah I thought I did, sorry. 

Glad it's gonna get fixed.
