### ISSUE TITLE
Allow use of any color for custom Rarities

### ISSUE THREAD

**Issue by Shadowdragon019** [CraftTweaker/CraftTweaker#1342]
### Describe the feature you'd like

Allow use of any color for custom Rarities. think of it like dying leather armor, you've got the 16 colors via dyes but if you use commands you can get your armor any color!

I don't know how to go into more detail anymore so I'll convince you.

The current system only allows for 16 different colors provided by Minecraft, which can be quite limiting. You want to try Brown? No. Want to try a slightly different Blue? No.

### Describe alternatives you've considered

I've considered KubeJS but I couldn't see anything that could replicate this

### Minecraft version

1.16

**Comment by jaredlll08** [comment]
So while it is possible to make new `Rarity`'s, you need to have a `TextFormatting`, which unfortunately is not possible to make, so you are limited to 22 `TextFormatting` options.

However, you can use the tooltip event to achieve more or less the same effect:
![image](https://user-images.githubusercontent.com/5553605/128756609-cef8eb8a-8692-4531-ade1-aeca8b53effd.png)

That is an example of what someone has done in the Discord.

Does that work for your usecase?

**Comment by jaredlll08** [comment]
Closing due to the underlying feature request being impossible.

You can achieve an effect like this by making a new rarity using the `reset` formatting (or `white`), and then overriding the item display name using the `modifyTooltip` method.
