### ISSUE TITLE
Adaptation of HBM's nuclear tech mod Reloaded

### ISSUE THREAD

**Issue by xingchengs** [CraftTweaker/CraftTweaker#1343]
### Describe the feature you'd like

It can modify the machine formula of this mod

### Describe alternatives you've considered

null

### Additional context

null

### Minecraft version

1.12

**Comment by xingchengs** [comment]
MOD：Hbm's Nuclear Tech Mod Reloaded

**Comment by jaredlll08** [comment]
I haven't a clue what you're actually asking.

If you're asking for mod support, you are years too late.
