### ISSUE TITLE
Removing a potion recipe

### ISSUE THREAD

**Issue by tikiMC** [CraftTweaker/CraftTweaker#1349]
### Issue description

Using brewing.removeRecipe(IItemstack,IItemstack,IItemstack); causes all potion recipes to be removed. At least with the potion I'm trying to remove from infernal expansion.

### Script used

https://gist.github.com/tikiMC/91e1d06073d03a8bf95e429fa63a61ca

### The crafttweaker.log file

https://gist.github.com/tikiMC/d7686ade88194dec680174d8991383ad

### Minecraft version

1.16

### Forge version

36.2.0

### CraftTweaker version

7.1.1.395

### The latest.log file

https://gist.github.com/tikiMC/260975ec9ac97e4fc825603022886897

**Comment by jaredlll08** [comment]
So basically that mod is adding their potion as a Vanilla potion recipe.

I'm not sure if this is the *correct* way to do it, but it is what they've done.

The way the vanilla recipes are done, is that all "recipes" are really a single recipe, so when my code comes along and checks for matching recipes, this one matches and removes it, thus removing all vanilla brewing recipes.

You can delete this specific recipe using the following method:
```zenscript
brewing.removeRecipe(Potion output, IItemStack reagent, Potion input)
```
like so:
```zenscript
brewing.removeRecipe(<potion:infernalexp:long_infection>, <item:minecraft:redstone>, <potion:infernalexp:infection>);
```
