### ISSUE TITLE
MCFood option to eat while fully saturated

### ISSUE THREAD

**Issue by p3lim** [CraftTweaker/CraftTweaker#1353]
### Describe the feature you'd like

An equivalent to `MCFood.setCanEatWhenFull(boolean)` just for saturation instead of health, allowing an item to be eaten while fully saturated. Something like `MCFood.setCanEatWhileSaturated(boolean)`.

### Minecraft version

1.16

**Comment by jaredlll08** [comment]
Unfortunately this isn't supported by vanilla.
