### ISSUE TITLE
Can't load a world

### ISSUE THREAD

**Issue by tikiMC** [CraftTweaker/CraftTweaker#1354]
### Issue description

With the two newest versions of craft weaker, 405 and 406 something changed, that doesn't allow me to load into a new world. Taking a brief look at the crash log, I'd say it has something to do with my villager trading scripts that worked fine in previous versions...

### Script used

https://gist.github.com/tikiMC/c61be9659d22bba8d1925fe370d29330

### The crafttweaker.log file

https://gist.github.com/tikiMC/9cb25ed3a2cbb7e7c4b4acdcfa4e57a4

### Minecraft version

1.16

### Forge version

36.2.0

### CraftTweaker version

7.1.2.406

### Other relevant information

Crash Report: https://gist.github.com/tikiMC/0f367272cb3798b8c54ad66af7a3ada4

### The latest.log file

https://gist.github.com/tikiMC/3e7e7638e27045b2602a241dd5735d5a

**Comment by tikiMC** [comment]
Okay, I figured out what was causing it. When you try to add a trade to the etched:bard villager profession it doesn't load. This is the line I deleted to get it working again. 
```zenscript
villagerTrades.addTrade(<profession:etched:bard>,1,<item:minecraft:music_disc_cat>,<item:minecraft:emerald>*8,16,3,0.05); 
```
edit:which is stupid because that works and adds the trade, but as soon as you leave the world you won't be able to join again.

**Comment by jaredlll08** [comment]
This is an issue with Etched.

I've made an issue on their tracker here:
https://github.com/jaacksondev/etched/issues/14
I'll leave this issue open until they have resolved that issue

**Comment by jaredlll08** [comment]
Yea... actually going to close this since I don't know if Etched is still being developed for 1.16 (I do see they have a 1.17 branch)

**Comment by jaredlll08** [comment]
As of https://github.com/MoonflowerTeam/etched/commit/08726b834cedba5c43a52047a98c6632d17550a6
this has been fixed
