### ISSUE TITLE
Client crashes on startup

### ISSUE THREAD

**Issue by EmiPiplu** [CraftTweaker/CraftTweaker#1363]
### Issue description

I have been trying to make my own modpack and added this mod. It keeps crashing during phase 2

### Script used

None

### The crafttweaker.log file

Empty

### Minecraft version

1.12

### Forge version

14.21.1.2387

### CraftTweaker version

4.1.11

### The latest.log file

https://pastebin.com/PnhsP9Wu

**Comment by jaredlll08** [comment]
You are more than 100 versions behind.
Stop using 1.12. Use 1.12.2
