### ISSUE TITLE
Compatibility with other mods (question)

### ISSUE THREAD

**Issue by AndyKitty8** [CraftTweaker/CraftTweaker#1369]
### Describe the feature you'd like

Does this mod work with items from other mods? For example, could I make an elytra recipe with feathers from Alex’s Mobs?

### Describe alternatives you've considered

I don’t know of any other mods that can change crafting recipes. If there are any that work for 1.17, I’d definitely be open to trying them.

### Additional context

I’ve not used this mod before, but I want to use it on a server with other mods, so I was wondering if it would work with modded items.

### Minecraft version

Other

**Comment by jaredlll08** [comment]
The mod can work with any items from any mod.

So yes, you can use modded items in recipes.

You can even add recipes for *nearly all* modded machines.
https://docs.blamejared.com/1.16/en/mods/other_mods/
