### ISSUE TITLE
Add IBlockDefinition `resistance` Getter

### ISSUE THREAD

**Issue by ubergarm** [CraftTweaker/CraftTweaker#1373]
### Describe the feature you'd like

The setter was added way back in #412 but there is still no getter for blast `resistance` like there is for mining `hardness`.

The underlying forge call to wrap is probably something like
```
data.block.getExplosionResistance(data.world, data.pos, null, null);
```

### Describe alternatives you've considered

[WAWLA](https://github.com/Darkhax-Minecraft/WAWLA/blob/1.12.2/src/main/java/net/darkhax/wawla/plugins/generic/PluginBlastResistance.java) can show a blocks resistance, but The One Probe does not have that feature as far as i can tell at least in 1.12.2.

### Additional context

I am interested in adding some items which display block resistance for my modpack [Rotten Economy](https://www.curseforge.com/minecraft/modpacks/rotten-economy/files) which has a lot of mechanics around mob griefing and explosions so it is important for players to be able to access that info to compare blocks stats.

Cheers!

### Minecraft version

1.12

**Comment by jaredlll08** [comment]
Fixed by PR
