### ISSUE TITLE
multicrafting numbers (lets say that this would be a feature request site folder, lets pretend)

### ISSUE THREAD

**Issue by InventionIO** [CraftTweaker/CraftTweaker#1392]
### Describe the feature you'd like

example: you have a crafting table and exept one item for input you would add two for a crafting and it will craft it from the two item inputs from one, basically

Better example:
craftingTable.addShaped("coaldiamond", <item:minecraft:diamond>, [
[<item:minecraft:coal_block> * 64, <item:minecraft:coal_block> * 64, <item:minecraft:coal_block> * 64], 
[<item:minecraft:coal_block> * 64, <item:minecraft:coal_block> * 64, <item:minecraft:coal_block> * 64], 
[<item:minecraft:coal_block> * 64, <item:minecraft:coal_block> * 64, <item:minecraft:coal_block> * 64]]);

Same for furnaces and other things in minecraft and mods.

pretty trully similar to hypixel skyblock but wasnt inspired from it.

### Describe alternatives you've considered

None, it aint possible cus it bugs.

### Additional context

I have added all of it up there.

for repeat:
craftingTable.addShaped("coaldiamond", <item:minecraft:diamond>, [
[<item:minecraft:coal_block> * 64, <item:minecraft:coal_block> * 64, <item:minecraft:coal_block> * 64], 
[<item:minecraft:coal_block> * 64, <item:minecraft:coal_block> * 64, <item:minecraft:coal_block> * 64], 
[<item:minecraft:coal_block> * 64, <item:minecraft:coal_block> * 64, <item:minecraft:coal_block> * 64]]);

### Minecraft version

1.16

**Comment by jaredlll08** [comment]
The crafting table does not accept more than one stack in a single slot for recipes.

**Comment by InventionIO** [comment]
Is it possible to rewrite crafting table for that function ?

**Comment by InventionIO** [comment]
But thats fine

**Comment by jaredlll08** [comment]
> Is it possible to rewrite crafting table for that function ?

You are asking me to rewrite the crafting table of every single mod that adds one?

Yea no, not possible.

**Comment by InventionIO** [comment]
i mean it could be in theory possible

**Comment by InventionIO** [comment]
if the craftings had the same code used

**Comment by InventionIO** [comment]
whitch would be modified

**Comment by friendlyhj** [comment]
Go to discord please.

**Comment by InventionIO** [comment]
ok
