### ISSUE TITLE
Missing recipetype

### ISSUE THREAD

**Issue by StrangerSon71** [CraftTweaker/CraftTweaker#1396]
### Issue description

Dragonforge recipes aren't detected, don't know if it's on his end but [this](https://github.com/Alex-the-666/Ice_and_Fire/tree/1.16.3/src/main/resources/data/iceandfire/dragonforge_recipes) is why I thought it should show up. 

### Steps to reproduce

1. Run /ct dump recipeTypes with appropriate mods installed
2. Look in crafttweaker log

### Script used

https://pastebin.com/pA7p4GV7

### The crafttweaker.log file

https://pastebin.com/zp7dvdsU

### Minecraft version

1.16

### Forge version

3.2.9

### CraftTweaker version

7.1.2.456

### The latest.log file

Not relevant (I think)

**Comment by jaredlll08** [comment]
Ice and fire don't register their recipes with the vanilla json recipe system, they have their own system for whatever reason, so they straight up just don't have a recipe type for us to use.


So everything is technically working intended on our side, if they did things correctly it would work fine.

**Comment by StrangerSon71** [comment]
That is really, really, weird. It read the same as the vanilla. Shame their's nothing I can do about it.

**Comment by jaredlll08** [comment]
Yep, they had to go out of their way to do it like this

**Comment by jaredlll08** [comment]
When it's released
https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-tweaker/files/3537573

**Comment by StrangerSon71** [comment]
So a separate addon will provide this feature? Neat! Thanks for making one!

**Comment by StrangerSon71** [comment]
Oh wow, you're the one making said addon, thanks loads!
