### ISSUE TITLE
Add recipe by regex

### ISSUE THREAD

**Issue by InventionIO** [CraftTweaker/CraftTweaker#1403]
### Describe the feature you'd like

You would basically use it like this:
craftingtable.addRegexTagRecipeShapeless( <item:minecraft:.*planks> [<item:.*log>]);

### Describe alternatives you've considered

None, or maybe just adding the recipes by hand (boring).

### Additional context

dont know how to explain it further

### Minecraft version

1.16

**Comment by InventionIO** [comment]
Should i add aditional context ?

**Comment by jaredlll08** [comment]
That is not how recipes work.

Even if I found a way to implement this it would be **horribly** slow and slow down all shapeless recipe crafting.

Just use tags and ingredient lists.

**Comment by InventionIO** [comment]
I dont think we understand themselves

**Comment by InventionIO** [comment]
I meant it otherwise

**Comment by InventionIO** [comment]
I mentioned it on discord

**Comment by InventionIO** [comment]
You here ?

**Comment by InventionIO** [comment]
It has also other context

**Comment by ikexing-cn** [comment]
go discord, don't send some of this spam, thanks
