### ISSUE TITLE
\n Tooltip Line Formatting doesn't function properly ONLY in fullscreen? Works fine in windowed mode.

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#1405]
### Issue description

**Here's the Tooltip in Windowed Minecraft Mode:**
![image](https://user-images.githubusercontent.com/71896090/144520723-196fda23-5218-411c-95b5-718c59b0f44a.png)
the \n formatting works perfectly.

<img src="https://user-images.githubusercontent.com/71896090/143823597-b2d99478-d6f0-46bc-b4c9-cb3483f58efa.png" height="90">

**Here's the Tooltip in FULLSCREEN:**
![delete ](https://user-images.githubusercontent.com/71896090/144520707-f7728a15-16b9-4d60-9dcd-6735378dbc37.png)
Suddenly, the properly-formatted \n formatting turns into ["LF" characters](https://www.google.com/search?q=lf+symbol&rlz=1C1ONGR_enUS964US964&oq=LF+symbol&aqs=chrome.0.69i59j0i512l2j0i22i30l2j0i10i22i30l5.2178j0j7&sourceid=chrome&ie=UTF-8)?

<img src="https://user-images.githubusercontent.com/71896090/143823597-b2d99478-d6f0-46bc-b4c9-cb3483f58efa.png" height="90">

Really not sure what this is like.

### Steps to reproduce

Here's my Crafttweaker example:

<minecraft:stick>.addShiftTooltip(" ", "Hold SHIFT for more info.");
<minecraft:stick>.addShiftTooltip("This should be line 1 \n and this should be line 2);

This would format properly in windowed mode, but not fullscreen?

### Script used

https://pastebin.com/nMWe54MJ

### The crafttweaker.log file

https://pastebin.com/RvLfy5LH

### Minecraft version

1.12

### Forge version

14.23.5.2855 

### CraftTweaker version

CraftTweaker2-1.12-4.1.20.614

### The latest.log file

.

**Comment by jaredlll08** [comment]
There is absolutely nothing in CraftTweaker that cares if you are in windowed or fullscreen mode, this is most likely a bug with the game / forge / another mod.
