### ISSUE TITLE
Environmental support

### ISSUE THREAD

**Issue by sauphle** [CraftTweaker/CraftTweaker#1412]
### Describe the feature you'd like

The sawmill and kiln from the abnormal's mod environmental. The kiln is a furnace designed for terracotta and clay, while the sawmill is a stonecutter used for wood recipes

### Minecraft version

1.16

**Comment by Witixin1512** [comment]
Support for other mods is already included, provided that they support datapacks already.
This page explains how you could do that in a script: <https://docs.blamejared.com/1.16/en/mods/other_mods>

**Comment by kindlich** [comment]
Closing this, as
* It is already possible to use CrT's DataPack integration to add these recipes (according to Witixin1512's answer above)
* CraftTweaker itself does not provide further integration for mods, that is something that the mod authors would need to do themselves. For Environmental there's already an issue tracking this here  
  https://github.com/team-abnormals/environmental/issues/154
