### ISSUE TITLE
Parser Exception @ cdirt2stick expected bug and JEI not showing the recipes.

### ISSUE THREAD

**Issue by EndeenUnfound** [CraftTweaker/CraftTweaker#1426]
### Issue description

everytime i join or reload a miencraft world it shows Parser Exception @ cdirt2stick expected ; expected thingy

and I dont seem to find anything in jei for some other ones i made
 
 also I'm quite new to crafttweaker and this might be like simple dumb things to you guys..

### Script used

this is the parser exception: https://pastebin.com/dTumyXGH and this is the jei not found : https://pastebin.com/KeMum7xd

### The crafttweaker.log file

gonna put this tommorrow cause i gtg and my minecraft crashed

### Minecraft version

1.16

### Modloader

Forge

### Modloader version

39.1.0

### CraftTweaker version

9.0.0

### The latest.log file

.

**Comment by jaredlll08** [comment]
You don't need to specify `as IItemStack` for everything, doing:
```zenscript
var cdirt = <item:compressed:dirt_i>```
is fine.

The parser error is because you have:
```zenscript
var stick - <item:minecraft:stick>
```
that should be a `=` not a `-`.

As for the other recipe, you are adding a shapeless recipe, but using the shaped 3x3 array, it should just be:
```zenscript
craftingTable.addShapeless(dirt, [
	bean, bean, bean,
	bean, bean, bean,
	bean, bean, bean
	]
);
```

**Comment by EndeenUnfound** [comment]
oh, thank you, well i am quite a newbie.
