### ISSUE TITLE
Doesn't work avaritia script

### ISSUE THREAD

**Issue by DreamcastERA1** [CraftTweaker/CraftTweaker#1427]
### Issue description

I wrote new crafts in ExtremeCraftingTable(Avaritia)But it doesn't work(Scripts created by Avaritia Recipe Maker)
(There are many other mods)
Version:1.12.2

### Script used

https://pastebin.com/Z8B1k5HT

### The crafttweaker.log file

https://pastebin.com/a3FQBUWa

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

14.23.5.2860

### CraftTweaker version

4.1.20.673

### Other relevant information

https://ibb.co/vxjfF54
https://ibb.co/Rcb88qC
https://ibb.co/B6ZCjHZ
(My other mods)
Ibb-pictures host

### The latest.log file

https://gist.github.com/CheatEngineUser1/6252ca868a8124a717d58967c4273422

**Comment by jaredlll08** [comment]
Line 32 is missing an ending `;`
```zenscript
recipes.remove(<bloodmagic:activation_crystal:2>);
```
