### ISSUE TITLE
No compatible methods found,

### ISSUE THREAD

**Issue by EndeenUnfound** [CraftTweaker/CraftTweaker#1428]
### Issue description

another issue cause im a noob

so, when I start a miencrat world or reload it, it says stuff2stone no compatible methods found, it does it with all other ones I've made too

### Script used

https://pastebin.com/UidXXt7C

### The crafttweaker.log file

.

### Minecraft version

1.16

### Modloader

Forge

### Modloader version

39.1.0

### CraftTweaker version

9.0.0

### The latest.log file

.

**Comment by jaredlll08** [comment]
```zenscript
craftingTable.addShapeless(dirt, [
```
`dirt` needs to be a string, like `"dirt"`

**Comment by EndeenUnfound** [comment]
just in case, is it all the vars or just the one that is made

**Comment by EndeenUnfound** [comment]
e.g. the top one, but not the one that's being made.

craftingtable added shaped and the one right after that

**Comment by jaredlll08** [comment]
actually, the issue is that your recipe needs a name, right now it doesn't have a name, so something like:
```zenscript
import crafttweaker.api.item.IItemStack;
 
var dirt = <item:minecraft:dirt> as IItemStack;
var bean = <item:pamhc2crops:beanitem> as IItemStack;
 
craftingTable.addShapeless("custom_unique_name", dirt, [
	bean, bean, bean,
	bean, bean, bean,
	bean, bean, bean
	]
);
 ```
