### ISSUE TITLE
Resonant machines break zenscript

### ISSUE THREAD

**Issue by blockgoblin31** [CraftTweaker/CraftTweaker#1429]
### Issue description

using the latest releases of crafttweaker, extended crafting, and thermal expansion for 1.12, trying to add the item <thermalexpansion:tank>.withTag({Fluid:{FluidName:"water",Amount:500000},Level:4b}) or any other item using the tag Level, will cause the loading to fail. I have other nbt tags working, but this one will not. Am i missing something, or will this just not work?(lines 22, 33, 35)

### Script used

https://pastebin.com/3veKRPHK

### The crafttweaker.log file

https://pastebin.com/LjFNPkTp

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

14.23.5.2859

### CraftTweaker version

CraftTweaker2-1.12-4.1.20.673.jar

### The latest.log file

https://pastebin.com/eZ6Mfw5W

**Comment by jaredlll08** [comment]
```
<thermalexpansion:cell>.withTag({Energy:50000000,Level:"4b"}),
``` is most likely incorrect.

It is probably meant to be:

```
<thermalexpansion:cell>.withTag({Energy:50000000,Level:4 as byte}),
```

But don't use what I just gave, hold the item in your hand, use `/ct hand` and you will get the correct tag that you are meant to use.

**Comment by blockgoblin31** [comment]
thx, I didn't know there was a command for nbt. been reading it from the additional info from actually additions.
