### ISSUE TITLE
Mod Loading Error

### ISSUE THREAD

**Issue by dannydjdk** [CraftTweaker/CraftTweaker#1434]
### Issue description

Crash during mod loading.

Crash Report: [https://pastebin.com/vermVUVe](https://pastebin.com/vermVUVe)

### Steps to reproduce

Install forge. Add CraftTweaker. Attempt to launch.

### Script used

none

### The crafttweaker.log file

none generated

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

39.0.40

### CraftTweaker version

9.0.0+30

### The latest.log file

https://pastebin.com/Q8U5mceQ

**Comment by jaredlll08** [comment]
What launcher are you using?
Where is minecraft installed?
Are you able to test using the Fabric version?

**Comment by dannydjdk** [comment]
Using AT Launcher on Mac OS.

The Minecraft instance is installed in the default location for AT Launcher on Mac which within the AT Launcher package in the applications folder. As for the actual Minecraft installation, I haven't changed any of the defaults for installation. I can dig a little deeper here if it would be helpful.

I created a Fabric instance with AT Launcher and installed just CraftTweaker and dependencies. That launched successfully. This instance was installed in the same subdirectory as the forge instance. Also, I tested a forge instance with vanilla launcher with the instance location as a subfolder of my home folder. This launched successfully as well.

So, the issue is restricted to forge in my AT Launcher environment. I first encountered the issue working on a pack in the AT Launcher with a lot of other mods. That pack launches fine without CraftTweaker. So, I created a fresh forge instance and was able to reproduce the issue there.

**Comment by jaredlll08** [comment]
Can you get me the permissions for the Forge instance folder and the fabric instance folder please

**Comment by dannydjdk** [comment]
Forge Instance:
drwxr-xr-x  12 danny  staff     384 Jan 16 18:53 .
drwxr-xr-x  10 danny  staff     320 Jan 16 22:50 ..
drwxr-xr-x   3 danny  staff      96 Jan 16 18:53 config
drwxr-xr-x   5 danny  staff     160 Jan 16 23:17 crash-reports
drwxr-xr-x   2 danny  staff      64 Jan 16 18:53 defaultconfigs
drwxr-xr-x   2 danny  staff      64 Jan 16 18:52 disabledmods
-rw-r--r--   1 danny  staff  109362 Jan 16 23:17 instance.json
drwxr-xr-x   2 danny  staff      64 Jan 16 18:52 jarmods
drwxr-xr-x   5 danny  staff     160 Jan 16 23:17 logs
drwxr-xr-x   3 danny  staff      96 Jan 16 18:53 mods
drwxr-xr-x   2 danny  staff      64 Jan 16 18:53 resourcepacks
drwxr-xr-x   2 danny  staff      64 Jan 16 18:53 saves

Fabric Instance:
drwxr-xr-x  13 danny  staff     416 Jan 16 22:51 .
drwxr-xr-x  10 danny  staff     320 Jan 16 22:50 ..
drwxr-xr-x   4 danny  staff     128 Jan 16 22:51 .fabric
drwxr-xr-x   3 danny  staff      96 Jan 16 22:51 config
drwxr-xr-x   2 danny  staff      64 Jan 16 22:50 disabledmods
-rw-r--r--   1 danny  staff  128335 Jan 16 22:51 instance.json
drwxr-xr-x   2 danny  staff      64 Jan 16 22:50 jarmods
drwxr-xr-x   4 danny  staff     128 Jan 16 22:51 logs
drwxr-xr-x   5 danny  staff     160 Jan 16 22:51 mods
-rw-r--r--   1 danny  staff     133 Jan 16 22:51 realms_persistence.json
drwxr-xr-x   2 danny  staff      64 Jan 16 22:51 resourcepacks
drwxr-xr-x   2 danny  staff      64 Jan 16 22:52 saves
drwxr-xr-x   2 danny  staff      64 Jan 16 22:51 scripts


I tried copying the entire AT Launcher package to my desktop and get the same issue. I thought perhaps one of the new over bearing security features in Mac OS might have been secretly preventing the craft tweaker log file from being generated under /Applications, but that doesn't seem to be the case. It also probably wouldn't explain why the Fabric version does work fine there.

**Comment by jaredlll08** [comment]
And you can reproduce it on the Forge instance all the time?

**Comment by dannydjdk** [comment]
Yes. It is consistent.

**Comment by dannydjdk** [comment]
Looks like this might not be the only mod having similar issues: https://github.com/ATLauncher/ATLauncher/issues/502

**Comment by jaredlll08** [comment]
I really need to read more.

So we had ran into a similar issue like this before, over here:
https://github.com/CraftTweaker/CraftTweaker/issues/1197

but apparently I completely missed where they said they used ATLauncher, just went straight to the log which doesn't mention it...

I think at this point it is safe to say that it is ATLauncher related and there isn't much I can do on my side.

It not affecting Fabric though is rather interesting though, maybe it is due to how forge loads the mods

**Comment by dannydjdk** [comment]
I posted a workaround (and a few insights) in the ATLauncher issue I linked above for anyone else who has this issue.

Thanks for your work @jaredlll08 and for asking the right questions to nail this down! :)
