### ISSUE TITLE
Won't Load Server-Side

### ISSUE THREAD

**Issue by tebbbi** [CraftTweaker/CraftTweaker#1435]
### Issue description

I am using CraftTweaker-fabric-1.17.1-8.0.0+32 and IngredientExtensionAPI-fabric-1.17.1-1.0.10, it wont load on my server. It gets to the point of loading craft tweaker and just stops. It works on client but not on my server.

Heres my modlist:

      adorn-2.3.1+1.17.1-fabric.jar  
      arcanus-1.23.jar  
      architectury-2.6.35.jar   
      backslot-1.2.2.jar    
      backslotaddon-1.0.7.jar   
      blockus-2.2.10+1.17.1.jar   
      cloth-config-5.1.40-fabric.jar    
      CraftTweaker-fabric-1.17.1-8.0.0+32.jar    
      dawn-2.0.6.jar    
      decimalCoins-fabric-1.17.1-1.3.0.jar  
      drinkbeer-v3.0.2 for 1.17.1.jar    
      DualRiders-1.17-1.0.5.jar    
      dualwielding-1.0.7.jar    
      extrakeybinds-1.17-0.1.2.jar    
      fabric-api-0.42.1+1.17.jar    
      fabric-enchantments-0.5.0.jar    
      fabric-language-kotlin-1.6.5+kotlin.1.5.31.jar   
      falling-attack-fabric-1.17.1-1.1.2.jar    
      figura-0.0.6-1.17.x.jar    
      geckolib-fabric-1.17-3.0.23.jar    
      HQM-1.17.1-5.7.2-fabric.jar  
      incantationem-1.1.2+1.17.1.jar    
      IngredientExtensionAPI-fabric-1.17.1-1.0.10.jar    
      Kambrik-1.1.0.jar    371.81 KB       
      konkrete_fabric_1.3.0_MC_1.17-1.17.1.jar          
      medievalweapons-1.1.7.jar           
      MoEnchantments-1.18.1.jar    
      mythic-mounts-1.17.1-4.0.jar   
      nyfsquivers-Fabric-0.2.6-1.17.jar    
      Origins-1.17-1.1.4.jar   
      Pehkui-2.5.3+1.14.4-1.18.jar    
      player-roles-1.4.3.jar   
      promenade-2.1.2.jar    
      spark-fabric.jar    
      taterzens-1.6.1-fabric.jar   
      trinkets-3.0.4.jar   
      voicechat-fabric-1.17.1-2.1.13.jar   
      worldedit-mod-7.2.7.jar   
      wraith-waystones-2.2.0.jar

Heres the log: https://pastebin.com/CxP9tmD8

Sorry if this not enough info, i can add more.

 

### Script used

none, do i need a script?

### The crafttweaker.log file

[22:45:30.841][INFO]: Starting building internal Registries thats all the log says

### Minecraft version

Other

### Modloader

Fabric

### Modloader version

0.12.10

### CraftTweaker version

8.0.0+32

### The latest.log file

https://pastebin.com/CxP9tmD8

**Comment by jaredlll08** [comment]
Try update fabric api?

**Comment by tebbbi** [comment]
Its the same Fabric API on the server as the client.

**Comment by tebbbi** [comment]
> Try update fabric api?

Its the same Fabric API on the server as the client.

**Comment by jaredlll08** [comment]
> 	- fabricloader@0.11.7

https://github.com/CraftTweaker/CraftTweaker/blob/1.18/Fabric/src/main/resources/fabric.mod.json#L39

Update fabric-loader, I don't even know why my entry point was attempted to be loaded when I have that line.
