### ISSUE TITLE
【forge 1.18.1/1.16.5】Incompatibillity with inventorio

### ISSUE THREAD

**Issue by AmyRose1288** [CraftTweaker/CraftTweaker#1437]
### Issue description

![image](https://user-images.githubusercontent.com/19208524/150761270-3b53876b-2cf6-4822-9a41-b7411ec5e5b4.png)
while using inventorio,inventory profile next (fixed incompatibillity)and CraftTweaker,UI is messed up

### Steps to reproduce

install CraftTweaker,Inventorio,inventory profiles next
start a new game
UI looks like what i've reported

### Script used

N/A (Deleted Mod in order to use inventorio)

### The crafttweaker.log file

N/A (Deleted Mod in order to use inventorio)

### Minecraft version

1.16

### Modloader

All

### Modloader version

39.2.0 / 0.10.2

### CraftTweaker version

7.1.2.489

### The latest.log file

N/A (Deleted Mod in order to use inventorio)

**Comment by jaredlll08** [comment]
This is the first time I'm hearing of that mod, and we do absolutely zero gui modifications, don't even have our own gui, so this is not us.
