### ISSUE TITLE
CTGUI checkboxes

### ISSUE THREAD

**Issue by blockgoblin31** [CraftTweaker/CraftTweaker#1438]
### Issue description

I cannot select any of the checkboxes on the sidebar of ctgui

### Script used

none

### The crafttweaker.log file

https://pastebin.com/D7EkYnwP

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

14.23.5.2859

### CraftTweaker version

CraftTweaker2-1.12-4.1.20.673.jar

### Other relevant information

Have modtweaker, content tweaker, and tweaker's construct installed

### The latest.log file

https://gist.github.com/tuc56/c21631d1adc2f40c5a57aa829f222f48

**Comment by jaredlll08** [comment]
Right click an item slot.

If that doesn't work, then I don't have a solution for you, the gui is no longer supported and you are advised to learn the scripting language.

**Comment by blockgoblin31** [comment]
I know how to do nbt tags, I'm just using recipies differentiated only by the material tag of the tinker's part. sorry for the second post in a couple weeks that is just me not knowing things.
