### ISSUE TITLE
Incomplete Bracket Expression at EOF causes Parser to lock up

### ISSUE THREAD

**Issue by secretmeister** [CraftTweaker/CraftTweaker#1440]
### Issue description

Craftweaker was working perfectly fine until I added the very bottom recipe in the create2 script, after which it would not make or load any worlds, and my custom server failed to load right after crafttweaker initializes. I have to force quit minecraft, or terminate in the terminal window to try again, it hardlocks minecraft. This is also my first time using pastebin, so apoligize if this is not proper formatting for that. EDIT: There was an error in the recipe that broke it, but I fixed it, as it should have been ae2:charged_certus_quartz_crystal, and I remerged the files, but it still fails to load on the preparing for world creation. Also, I tried removing that recipe that I changed, It was initially for ae2:name_press, but then it broke and I tried lot's of different items to no avail. I just removed that recipe, and it still won't load.

### Script used

https://pastebin.com/02qMx666       https://pastebin.com/eFY1z9Hk      https://pastebin.com/bF5yuA4h       https://pastebin.com/JMvvufHn

### The crafttweaker.log file

https://pastebin.com/JVS6ciNH

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

39.0.64

### CraftTweaker version

9.0.0+44

### Other relevant information

It was working perfectly fine, before I put in the final recipe in create2.zs, and that immediately stopped it and was initially in create.zs. I made create2 because I thought that might help, but it did not. I also tried this on my personal server I manually set up, and again, it stopped loading right after trying to load craftingtable.zs.

### The latest.log file

https://pastebin.com/uQpKLLDC

**Comment by kindlich** [comment]
`CraftingTable.zs`'s last recipe (recipe "namet" in lines 39+40) is not complete.
It's missing the closing `)`

As for why this completely stops CrT from doing anything else I can't say atm.
You can see in the crt log that it stuck at loading that file 😉 

@jaredlll08 You know more about the 1.18 version, could it be that we did not properly catch a parsing error?

**Comment by jaredlll08** [comment]
As kindlich said, that line is incomplete, it should be:
```zenscript
craftingTable.addShapeless("namet", <item:minecraft:name_tag>, [
<item:minecraft:lead>, <item:minecraft:paper>, <item:minecraft:black_dye>]);
```

With a `)` and a closing `>` on black_dye.

The main issue was the missing `>`, that is what caused the lockup.

I'll leave this issue open until we fix that
