### ISSUE TITLE
[1.18.1] [Fabric] Loot Chests empty with Mod Loot Extra installed

### ISSUE THREAD

**Issue by pewblaze** [CraftTweaker/CraftTweaker#1442]
### Issue description

The Loot Chests are empty when CraftTweaker & Loot Extra is installed.
Loot Extra works fine without CraftTweaker.

### Script used

https://gist.github.com/pewblaze/9d14b8dc79702b0f634e7aaeaa034547

### The crafttweaker.log file

https://gist.github.com/pewblaze/7475f34bc1df07a2f0645309e843d1ed

### Minecraft version

1.18

### Modloader

Fabric

### Modloader version

0.12.12

### CraftTweaker version

CraftTweaker-fabric-1.18.1-9.0.0+26

### Other relevant information

https://www.curseforge.com/minecraft/mc-mods/loot-extra
LootExtra-1.18-0.1.1

### The latest.log file

https://gist.github.com/pewblaze/2f445f7c0f6af631c48e19eabae112df

**Comment by jaredlll08** [comment]
This is an issue on that mod's side, their mixin basically overwrites the method.

**Comment by pewblaze** [comment]
Ah okay thanks!
