### ISSUE TITLE
Crash on 0.13.0 fabric

### ISSUE THREAD

**Issue by Sunconure11** [CraftTweaker/CraftTweaker#1443]
### Issue description

Just what it says on the tin. I have no further info to provide.

### Steps to reproduce

1. Use 0.13.0 Fabric
2. ???
3. https://pastebin.com/EfAw8Pxn

### Script used

Not applicable

### The crafttweaker.log file

Not applicable

### Minecraft version

1.18

### Modloader

Fabric

### Modloader version

0.13.0

### CraftTweaker version

9.0.45

### The latest.log file

https://pastebin.com/EfAw8Pxn

**Comment by jaredlll08** [comment]
Fixed by fb5f8c7584c7098ba84617a7791ed575fb63bf97
