### ISSUE TITLE
Crashing server

### ISSUE THREAD

**Issue by busa13** [CraftTweaker/CraftTweaker#1449]
### Issue description

Crashing server by player 

### Script used

https://pastebin.com/E2ZFgDT4

### The crafttweaker.log file

https://pastebin.com/8bnG9rkC

### Minecraft version

1.16

### Modloader

Forge

### Modloader version

36.2.26

### CraftTweaker version

1.16.5-7.1.2.491

### The latest.log file

https://pastebin.com/9gDpWtEB

**Comment by jaredlll08** [comment]
try on `7.1.2.495`

**Comment by jaredlll08** [comment]
Also what is the player doing that caused the server crash?

**Comment by busa13** [comment]
Player sends a crooked packet that crashes the server

**Comment by busa13** [comment]
Trobble at 
package com.blamejared.crafttweaker.impl.network.PacketHandler
to fix it crash there should  be check for ClintSide 
Can you fix it?

**Comment by jaredlll08** [comment]
Once again, try on that new version I listed.

**Comment by busa13** [comment]
Tried, nothing changed

**Comment by jaredlll08** [comment]
I find that very very very hard to believe considering the version I gave you removed the call to:
```
net.minecraft.util.Util$OS.func_195640_a(Ljava/lang/String;)V
```
and in fact does nothing but print out in the player log.
https://github.com/CraftTweaker/CraftTweaker/blob/aafe4274590079a5eedd0e2e8460cffa1f285eff/src/main/java/com/blamejared/crafttweaker/impl/network/PacketHandler.java#L24

So if you are saying it is still broken, I need a new log of the server using that version.

**Comment by jaredlll08** [comment]
I made it so only the server can send the packet, but once again, if you don't update, then it isn't going to magically fix itself.
