### ISSUE TITLE
JEI doesn't properly update recipes after the reload command is used

### ISSUE THREAD

**Issue by Warhand** [CraftTweaker/CraftTweaker#1455]
### Issue description

After updating a recipe via scripts, and checking to make sure the script actually functions, and using the reload command, the recipe won't properly display in JEI, and will only do so after returning to the main menu and re-opening the world.

### Steps to reproduce

It happens when using these versions of these mods

-JEIT version 3.0.0.4
-Minecraft version 1.18.1
-JEI version 9.4.1.112

### Script used

import crafttweaker.api.item.IItemStack; import crafttweaker.api.ingredient.IIngredient; import crafttweaker.api.ingredient.type.IIngredientAny; import crafttweaker.api.ingredient.type.IIngredientEmpty;  craftingTable.addShapeless("test_amethyst", <item:minecraft:amethyst_block>, [<item:minecraft:granite>, <item:minecraft:stone>]);

### The crafttweaker.log file

https://pastebin.com/5gktR0bZ

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

39.1.2

### CraftTweaker version

9.0.75

### Other relevant information

JEI 9.4.1.101 doesn't have this issue.

JEI 9.2.1.69 is the last official release of JEI, all the releases after that are betas, but version 9.4.1.101 or above is required for JER, so players are probably likely to be using at the very least that.

### The latest.log file

https://pastebin.com/zHh68i9E

**Comment by Ommina** [comment]
Have you tried JEI 9.4.1.116 (or greater, presumably)?

See also https://github.com/mezz/JustEnoughItems/issues/2733

**Comment by jaredlll08** [comment]
Unfortunately the JEI version with the fix is on 1.18.2.

Seeing as downgrading JEI versions fixes this, I don't think there is anything I can do on my side to solve it.
