### ISSUE TITLE
craftingTable.removeByModid doesn't work

### ISSUE THREAD

**Issue by totrider** [CraftTweaker/CraftTweaker#1456]
### Issue description

Remove.zs:175:0 Remove.zs:175:0: No matching method found for removeByModid:
Parameter 1: cannot cast function(name as undetermined) as undetermined to function(arg0 as string) as bool?

using:

// An array of recipe names as strings
var minecraftExclusions as string[] = [
    "acacia_slab",
    "red_bed_from_white_bed",
    "sugar_from_sugar_cane"
];

craftingTable.removeByModid("minecraft", name => {
    return name in minecraftExclusions;
});

I was using removeByModid in 1.17 version of a modpack, and I am in the process of updating it to 1.18.1

### Steps to reproduce

Make a .zs script and add:

// An array of recipe names as strings
var minecraftExclusions as string[] = [
    "acacia_slab",
    "red_bed_from_white_bed",
    "sugar_from_sugar_cane"
];

craftingTable.removeByModid("minecraft", name => {
    return name in minecraftExclusions;
});

Load minecraft world

### Script used

https://pastebin.com/z2w8P2iG

### The crafttweaker.log file

https://pastebin.com/U40RwVs5

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

39.0.88

### CraftTweaker version

1.18.1-9.0.78

### The latest.log file

https://gist.github.com/totrider/51bc8e2c0226337dde8ee2cfb05c1ae0

**Comment by jaredlll08** [comment]
Can you try:
```zenscript
// An array of recipe names as strings
var minecraftExclusions as string[] = [
    "acacia_slab",
    "red_bed_from_white_bed",
    "sugar_from_sugar_cane"
];
 
craftingTable.removeByModid("minecraft", (name as string) as bool => {
    return name in minecraftExclusions;
});
```

It should work, but at the same time your current script should also work, but I won't have time to see why it isn't for a bit, so this is a temporary workaround

**Comment by jaredlll08** [comment]
This has been fixed in the new update.
