### ISSUE TITLE
Cant ran client after I added CraftTweaker support to my mod.

### ISSUE THREAD

**Issue by Java0** [CraftTweaker/CraftTweaker#1459]
### Issue description

![EK$VG_)`%EVCCJ2{ WX4XWJ](https://user-images.githubusercontent.com/10484893/158947669-68ee1a6a-b231-434e-97b7-c475123af248.png)

Gradle Version : 7.1
ForgeGradle Version : 5.1+

### Script used

no script

### The crafttweaker.log file

no log

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

1.12.2-14.23.5.2859

### CraftTweaker version

4.1.20.674

### The latest.log file

https://gist.github.com/Java0/e7ced3f544b3f63755231cd433b7c3a5

**Comment by jaredlll08** [comment]
Show you build.gradle file please

**Comment by Java0** [comment]
> 请给你看 build.gradle 文件

https://gist.github.com/Java0/712293dcf26cb15e90850e67725c8754

**Comment by jaredlll08** [comment]
And your gradle.properties file, I need to see what versions you are using.

**Comment by Java0** [comment]
> And your gradle.properties file, I need to see what versions you are using.

https://gist.github.com/Java0/ee0ecd4cf2471361ed50cae80849f1ab

**Comment by jaredlll08** [comment]
You need
https://github.com/jaredlll08/ModTweaker/blob/1.12/build.gradle#L41

**Comment by Java0** [comment]
> You need https://github.com/jaredlll08/ModTweaker/blob/1.12/build.gradle#L41
Since version 3.0, froge gradle has not used the deobfCompile method, and I cannot build my project under the forge gradle version of 2.3-snapshot.

**Comment by jaredlll08** [comment]
Unfortunately this seems to be an issue with ForgeGradle.

CraftTweaker uses Access Transformers that are required for us to do what we do, and it seems that ForgeGradle on 1.12 has an issue applying them.

I know that the build.gradle file that I linked works for 1.12 (at-least it worked last I tried).

Unfortunately there isn't anything I can do on my side to resolve this.

**Comment by Java0** [comment]
> Unfortunately this seems to be an issue with ForgeGradle.
> 
> CraftTweaker uses Access Transformers that are required for us to do what we do, and it seems that ForgeGradle on 1.12 has an issue applying them.
> 
> I know that the build.gradle file that I linked works for 1.12 (at-least it worked last I tried).
> 
> Unfortunately there isn't anything I can do on my side to resolve this.

OK, I'll find a way by myself. Thank you very much for your help.
