### ISSUE TITLE
i keep  getting 2 error

### ISSUE THREAD

**Issue by Joaquin542** [CraftTweaker/CraftTweaker#1462]
### Issue description

ERROR: helix.zs:1 > could not find package null.

ERROR [crafttweaker]: Error executing {[0:crafttweaker]:helix.zs}: Truncated class file, caused by java.lang.ClassFormatError: Truncated class file

here is code

import craftweaker.item.IItemStack;
var stick = <minecraft:stick> as IItemStack;
var star = <minecraft:nether_star> as IItemStack;
var stone = <minecraft:stone> as IItemStack;
var ironblock = <minecraft:iron_block> as IItemStack;
var iron = <minecraft:iron_ingot> as IItemStack;
var ironnug = <minecraft:iron_nugget> as IItemStack;
var ironpick = <minecraft:iron_pickaxe> as IItemStack;
var ironsword = <minecraft:iron_sword> as IItemStack;
var ironshovel = <minecraft:iron_shovel> as IItemStack;
var ironaxe = <minecraft:iron_axe> as IItemStack;
var ironhoe = <minecraft:iron_hoe> as IItemStack;
var stonepick = <minecraft:stone_pickaxe> as IItemStack;
var stonesword = <minecraft:stone_sword> as IItemStack;
var stoneshovel = <minecraft:stone_shovel> as IItemStack;
var stoneaxe = <minecraft:stone_axe> as IItemStack;
var stonehoe = <minecraft:stone_hoe> as IItemStack;
var sandstone = <minecraft:sandstone> as IItemStack;
var sandstone1 = <minecraft:sandstone:1> as IItemStack;
var sandstone2 = <minecraft:sandstone:2> as IItemStack;
var mesa = <minecraft:red_sandstone> as IItemStack;
var mesa1 = <minecraft:red_sandstone:1> as IItemStack;
var mesa2 = <minecraft:red_sandstone:2> as IItemStack;
recipes.addShaped(ironpick, [
    [iron, ironblock, iron],
    [ironnug, stick, ironnug],
    [null, stick, null]
]
);
recipes.addShaped(ironsword, [
    [null, iron, null],
    [stick, ironblock, stick],
    [null, stick, null]
]
);
recipes.addShaped(ironshovel, [
    [null, ironblock, null],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShapedMirrored(ironaxe, [
    [null, iron, ironblock],
    [null, stick, iron],
    [null, stick, null]
]
);
recipes.addShapedMirrored(ironhoe, [
    [iron, ironblock, null],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShaped(<minecraft:stone_sword>, [
    [null, sandstone, null],
    [null, sandstone, null],
    [null, stick, null]
]
);
recipes.addShaped(<minecraft:stone_pickaxe>, [
    [sandstone, sandstone, sandstone],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShaped(<minecraft:stone_shovel>, [
    [null, sandstone, null],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShapedMirrored(<minecraft:stone_axe>, [
    [null, sandstone, sandstone],
    [null, stick, sandstone],
    [null, stick, null]
]
);
recipes.addShapedMirrored(<minecraft:stone_hoe>, [
    [null, sandstone, sandstone],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShaped(<minecraft:stone_sword>, [
    [null, sandstone1, null],
    [null, sandstone1, null],
    [null, stick, null]
]
);
recipes.addShaped(<minecraft:stone_pickaxe>, [
    [sandstone1, sandstone1, sandstone1],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShaped(<minecraft:stone_shovel>, [
    [null, sandstone1, null],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShapedMirrored(<minecraft:stone_axe>, [
    [null, sandstone1, sandstone1],
    [null, stick, sandstone1],
    [null, stick, null]
]
);
recipes.addShapedMirrored(<minecraft:stone_hoe>, [
    [null, sandstone1, sandstone1],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShaped(<minecraft:stone_sword>, [
    [null, sandstone2, null],
    [null, sandstone2, null],
    [null, stick, null]
]
);
recipes.addShaped(<minecraft:stone_pickaxe>, [
    [sandstone2, sandstone2, sandstone2],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShaped(<minecraft:stone_shovel>, [
    [null, sandstone2, null],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShapedMirrored(<minecraft:stone_axe>, [
    [null, sandstone2, sandstone2],
    [null, stick, sandstone2],
    [null, stick, null]
]
);
recipes.addShapedMirrored(<minecraft:stone_hoe>, [
    [null, sandstone2, sandstone2],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShaped(<minecraft:stone_sword>, [
    [null, mesa, null],
    [null, mesa, null],
    [null, stick, null]
]
);
recipes.addShaped(<minecraft:stone_pickaxe>, [
    [mesa, mesa, mesa],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShaped(<minecraft:stone_shovel>, [
    [null, mesa, null],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShapedMirrored(<minecraft:stone_axe>, [
    [null, mesa, mesa],
    [null, stick, mesa],
    [null, stick, null]
]
);
recipes.addShapedMirrored(<minecraft:stone_hoe>, [
    [null, mesa, mesa],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShaped(<minecraft:stone_sword>, [
    [null, mesa1, null],
    [null, mesa1, null],
    [null, stick, null]
]
);
recipes.addShaped(<minecraft:stone_pickaxe>, [
    [mesa1, mesa1, mesa1],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShaped(<minecraft:stone_shovel>, [
    [null, mesa1, null],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShapedMirrored(<minecraft:stone_axe>, [
    [null, mesa1, mesa1],
    [null, stick, mesa1],
    [null, stick, null]
]
);
recipes.addShapedMirrored(<minecraft:stone_hoe>, [
    [null, mesa1, mesa1],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShaped(<minecraft:stone_sword>, [
    [null, mesa2, null],
    [null, mesa2, null],
    [null, stick, null]
]
);
recipes.addShaped(<minecraft:stone_pickaxe>, [
    [mesa2, mesa2, mesa2],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShaped(<minecraft:stone_shovel>, [
    [null, mesa2, null],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.addShapedMirrored(<minecraft:stone_axe>, [
    [null, mesa2, mesa2],
    [null, stick, mesa2],
    [null, stick, null]
]
);
recipes.addShapedMirrored(<minecraft:stone_hoe>, [
    [null, mesa2, mesa2],
    [null, stick, null],
    [null, stick, null]
]
);
recipes.remove(<minecraft:stone_hoe>);
recipes.remove(<minecraft:stone_sword>);
recipes.remove(<minecraft:stone_pickaxe>);
recipes.remove(<minecraft:stone_axe>);
recipes.remove(<minecraft:stone_shovel>);
recipes.remove(<minecraft:iron_pickaxe>);
recipes.remove(<minecraft:iron_sword>);
recipes.remove(<minecraft:iron_axe>);
recipes.remove(<minecraft:iron_shovel>);
recipes.remove(<minecraft:iron_hoe>);
recipes.remove(<minecraft:ender_chest>);

### Script used

https://pastebin.com/5hPzL6zZ

### The crafttweaker.log file

https://pastebin.com/SERC5iXu

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

12.23.5.2859

### CraftTweaker version

4.1.20.674

### The latest.log file

https://pastebin.com/dZkqnFn2

**Comment by jaredlll08** [comment]
Your line has a wrong import.
it should be:
```zenscript
import crafttweaker.item.IItemStack;

```
