### ISSUE TITLE
Craftweaker REI Ingredient locations incorrect in Show Recipes

### ISSUE THREAD

**Issue by Cursedth** [CraftTweaker/CraftTweaker#1470]
### Issue description

I'll post this as a bug report with them as well.

Using craftTweaker making recipes that don't fill all ingredient slots don't fill correctly by Index.

This ..
`craftingTable.addShaped( "name" , <item:out> , [`
`    [<item:in>, <item:in>],`
`    [<item:in>, <item:Air>],`
`    [<item:in>, <item:in>]`
`]);`

..works correctly in the crafting table and the REI + correctly transfers the ingredients to  the right slots Indexes in the craftingtable..
But when pressing show recipe REI (only) shows this pattern..

X X X
A X X
N N N

Should show
X X N
X A N
X X N

Regards,

### Script used

na

### The crafttweaker.log file

na

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

3.91.0

### CraftTweaker version

9.1.95

### The latest.log file

NA

**Comment by Cursedth** [comment]
Something I just noticed in minecraft just after posting.
`/reload`
 doesn't seem to add  the new recipes of removed recipes back to the vanilla recipes book
using 
`/recipe give @p *`
did restore them however.

**Comment by jaredlll08** [comment]
If that is unrelated to the REI issue, please make a new issue for it.

**Comment by jaredlll08** [comment]
Shedaniel was unable to reproduce (https://github.com/shedaniel/RoughlyEnoughItems/issues/831) and CraftTweaker uses the Forge methods to dictate recipe size (Which is more likely what this would be from), so it would be on REI to fix
