### ISSUE TITLE
Tooltips not "loading" in multiplayer

### ISSUE THREAD

**Issue by Laifsyn** [CraftTweaker/CraftTweaker#1471]
### Issue description

If you open from 0 Minecraft and go into the server, the tooltips won't load until you go to Single Player to "force load" the scripts.

If it's supposed to work, then Probably is because the script to add tooltip is in NameScript1(in server) whereas for me, is in NameScript3(in client)

CraftTweaker-fabric-1.18.1-9.0.81
RoughlyEnoughItems-7.3.443

### Script used

https://pastebin.com/e3zQT3xB (This is the Client Script that adds the tooltip)

### The crafttweaker.log file

https://pastebin.com/YfpV5Kec

### Minecraft version

1.18

### Modloader

Fabric

### Modloader version

0.13.3

### CraftTweaker version

1.18.1-9.0.81

### The latest.log file

https://gist.github.com/Laifsyn/4ef08b4fc7f36e9f24eb812469595b47

**Comment by jaredlll08** [comment]
I'm not able to reproduce this.

So for starters, you aren't adding tooltips to anything in your script, a <kbd>CTRL</kbd>+<kbd>F</kbd> for `tooltip` gives absolutely nothing.

I can confirm that putting:
```zenscript
<item:minecraft:dirt>.addTooltip("I am a tooltip");
```
in a script on the server, then joining the server shows the tooltip just fine.


When you join a server, your client scripts are not ran, the server sends their scripts to the client and those scripts are ran, so anything you have in your client scripts folder may as well not be there.

From the sounds of it you only have tooltip adding code in the clients scripts folder and not the server.
