### ISSUE TITLE
[1.16] Unable to cast MCItemDefinition to IItemStack

### ISSUE THREAD

**Issue by CharlieQiu2017** [CraftTweaker/CraftTweaker#1473]
### Issue description

I have a script that provides players with extra crafting output when they use a certain recipe. It goes like this:

```
CTEventManager.register<MCItemCraftedEvent>((event) => {
  if(event.player == null) { return; }
  if (...) {
    var sz = someTag.elements.length as int;
    var idx = event.player.getWorld().random.nextInt(sz) as usize;
    var elem = someTag.elements[idx] as IItemStack;
    event.player.give(elem);
```

The extra output is randomly selected from the element list of a tag. This script works fine when using [CraftTweaker-1.16.5-7.1.2.507](https://www.curseforge.com/minecraft/mc-mods/crafttweaker/files/3737345), but breaks when using [CraftTweaker-1.16.5-7.1.2.508](https://www.curseforge.com/minecraft/mc-mods/crafttweaker/files/3737821). The error message is:

```
Bad type on operand stack
Exception Details:
Location:
j_util_function_Consumer_3.accept(Lnet/minecraftforge/event/entity/player/PlayerEvent$ItemCraftedEvent;)V @88: invokestatic
Reason:
Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'net/minecraft/item/Item'
Current Frame:
bci: @88
flags: { }
locals: { 'j_util_function_Consumer_3', 'net/minecraftforge/event/entity/player/PlayerEvent$ItemCraftedEvent', top, integer, top, integer, top, 'java/lang/Object' }
stack: { 'java/lang/Object' }
Bytecode: (omitted)
```

Further experimenting shows that this error occurs whenever I attempt to cast `MCItemDefinition` to `IItemStack`. Using `getDefaultInstance()` does not resolve this issue.

### Steps to reproduce

1. Install CraftTweaker 1.16.5-7.1.2.508
2. Put the attached script into `~/.minecraft/scripts`
3. Run Minecraft. Load any world.

### Script used

https://gist.github.com/CharlieQiu2017/5ce855efe85bb2cb50347db0fb69d2b4

### The crafttweaker.log file

https://gist.github.com/CharlieQiu2017/05fc56eee49928b969e7e6386067c2ff

### Minecraft version

1.16

### Modloader

Forge

### Modloader version

36.2.29

### CraftTweaker version

1.16.5-7.1.2.508

### The latest.log file

https://pastebin.com/MLASUr8Y

**Comment by jaredlll08** [comment]
please add `#debug` to the top of the script and then reload it, a new folder should generate called `classes`, zip that folder up and upload it here please.

**Comment by CharlieQiu2017** [comment]
https://drive.google.com/file/d/1753xJVnXn_SMmtDt5qBzGiyjM_DBocjg/view?usp=sharing

**Comment by jaredlll08** [comment]
This has been fixed by https://github.com/ZenCodeLang/ZenCode/commit/55e9a4350f4e56f17a17c4c3546a46e8c885a366 and will be in the next version.
