### ISSUE TITLE
IntData is being parsed as StringData in a map?

### ISSUE THREAD

**Issue by Witixin1512** [CraftTweaker/CraftTweaker#1476]
### Issue description

`{name:"tcr.aspect.metallum",count:4}` is being read as a StringMap, when it should be a two string keys, a string value and an int value.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/73248264/164302852-6776566f-99c8-4a40-a93c-c3aa265f4527.png)
![image](https://user-images.githubusercontent.com/73248264/164302868-a3d27652-952d-4733-887b-48af47434102.png)

### Script used

https://gist.github.com/Witixin1512/3b9140b98509e8586616de56afb45d8c

### The crafttweaker.log file

None

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.0.45

### CraftTweaker version

9.1.103

### Other relevant information

Reminder to see if Stan's refactor fixes it.

### The latest.log file

None

**Comment by jaredlll08** [comment]
This can not longer be reproduced, so I assume it is fixed on newer versions.

If anyone runs into an issue like this again please create a new issue for it.
