### ISSUE TITLE
Strange error with even newer builds of Fabric

### ISSUE THREAD

**Issue by Sunconure11** [CraftTweaker/CraftTweaker#1480]
### Issue description

https://pastebin.com/6aT0MY4P

### Steps to reproduce

1. Try to boot up the game
2. ???
3. https://pastebin.com/6aT0MY4P

### Script used

Not applicable

### The crafttweaker.log file

Not applicable

### Minecraft version

1.18

### Modloader

Fabric

### Modloader version

1.14.3

### CraftTweaker version

CraftTweaker-fabric-1.18.2-9.1.116.jar

### The latest.log file

https://pastebin.com/6aT0MY4P

**Comment by jaredlll08** [comment]
If you remove CraftTweaker do you still crash?

**Comment by Sunconure11** [comment]
I turned off CraftTweaker. I think something got fucked on Fabric 0.14.3.

**Comment by Sunconure11** [comment]
Fabric 0.14.2 seems to be booting up fine

**Comment by jaredlll08** [comment]
Just to confirm, on 0.14.3, without CraftTweaker, you run into the same issues?

**Comment by Sunconure11** [comment]
No, which is odd. I haven't found the mod culprit yet, if it is another mod doing this.

**Comment by jaredlll08** [comment]
This should be fixed by fabric loader 0.14.4, please test and get back to me

**Comment by kindlich** [comment]
Can this issue be marked as done, then?

@Sunconure11 we did not hear back from you, is this still an issue?

**Comment by Sunconure11** [comment]
Not an issue anymore
