### ISSUE TITLE
Newest Version of CraftTweaker won't load

### ISSUE THREAD

**Issue by LeonKappaX** [CraftTweaker/CraftTweaker#1488]
### Issue description

I forgot to post it here too, but it seems like the newest version of Quark isn't working with CT (tested it on the last 3 versions and for me it always fails to load). Since I am not so good with all the code stuff and not fully sure if it is an issue with Quark, I want to share it here too.

Crashlog (Not Enough Crashes): https://pastebin.com/gpkYcqBE

Latest Log: https://pastebin.com/mQdpmAwz

I hope it helps! 

### Steps to reproduce

List of Mods used is included in the Crashlog.

### Script used

/

### The crafttweaker.log file

/

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.1.19

### CraftTweaker version

9.1.133

### Other relevant information

/

### The latest.log file

https://pastebin.com/mQdpmAwz

**Comment by jaredlll08** [comment]
This is an issue between Quark and https://github.com/YeetmanLord/So-Many-Enchants, the only reason that CraftTweaker triggers it is because we load a class earlier than it would otherwise be loaded (which is by villagers when they figure out what they are going to trade).
