### ISSUE TITLE
defining a var inside a loop will cause the var to be unusable even if outside the loop

### ISSUE THREAD

**Issue by Laifsyn** [CraftTweaker/CraftTweaker#1496]
### Issue description

I had no clue what are the actually needed imports, so I'll just share them all
[crafttweaker.log](https://github.com/CraftTweaker/CraftTweaker/files/8783907/crafttweaker.log)
edit: Acclaration, It will say that the variable already exists, so you can't use the same variable for another for-loop

### Script used

https://pastebin.com/GAfe75Cw

### The crafttweaker.log file

nan

### Minecraft version

1.18

### Modloader

Fabric

### Modloader version

0.14.4x

### CraftTweaker version

9.1.140

### The latest.log file

-

**Comment by kindlich** [comment]
Easier script to reproduce:
```zs
var range = 0 .. 10;
for i in range {
    var j = i + 1; 
    println(j);
}

for i in range {
    var j = i + 1;  // Errors: "Duplicate variable name: j"
    println(j);
}
```

**Comment by jaredlll08** [comment]
This has been fixed by https://github.com/ZenCodeLang/ZenCode/commit/ab2c02ef7c11ec1d9ecb7137e29d5013906e52f6
