### ISSUE TITLE
No compatible methods found and No such member removeRecipe

### ISSUE THREAD

**Issue by KentukySG** [CraftTweaker/CraftTweaker#1507]
### Issue description

After updating the mod from 1.16.5 to 1.18.2 my "recipes.zs" stopped working.

When I log in it shows the same message "No compatible methods" and "No such member removeRecipe".

and the "craftingTable.addShapedMirrored" stopped working as well.

### Script used

https://gist.github.com/KentukySG/1bfbab9a0699fe982cd776fdf81c80e5

### The crafttweaker.log file

https://gist.github.com/KentukySG/1bfbab9a0699fe982cd776fdf81c80e5

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.1.51

### CraftTweaker version

9.1.153

### The latest.log file

https://gist.github.com/KentukySG/1bfbab9a0699fe982cd776fdf81c80e5

**Comment by Laifsyn** [comment]
That's because syntax has changed, for instance to remove a recipe is ``craftingTable.remove(<item:minecraft:crafting_table>);``

**Comment by KentukySG** [comment]
> That's because syntax has changed, for instance to remove a recipe is `craftingTable.remove(<item:minecraft:crafting_table>);`

This worked for remove, but for anyone in the future to use addShapedMirrored you have to import and add MirrorAxis in the script.
e.g.
 My original script was
```
import crafttweaker.api.recipe.SmithingRecipeManager;
import crafttweaker.api.recipe.CraftingTableRecipeManager;

craftingTable.remove(<item:waystones:waystone>);
craftingTable.addShapedMirrored("waystones", <item:waystones:waystone>, [
       [<item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:air>],
       [<item:minecraft:ender_pearl>, <item:minecraft:stick>, <item:minecraft:air>],
       [<item:minecraft:air>, <item:minecraft:stick>, <item:minecraft:air>]]);
```
My new script with the MirrorAxis
```
import crafttweaker.api.recipe.SmithingRecipeManager;
import crafttweaker.api.recipe.CraftingTableRecipeManager;
import crafttweaker.api.recipe.MirrorAxis;

craftingTable.remove(<item:waystones:waystone>);
craftingTable.addShapedMirrored("waystones", MirrorAxis.ALL, <item:waystones:waystone>, [
       [<item:minecraft:ender_pearl>, <item:minecraft:ender_pearl>, <item:minecraft:air>],
       [<item:minecraft:ender_pearl>, <item:minecraft:stick>, <item:minecraft:air>],
       [<item:minecraft:air>, <item:minecraft:stick>, <item:minecraft:air>]]);
```
For more info: [https://docs.blamejared.com/1.18/en/vanilla/api/recipe/MirrorAxis#mirroraxis](url)
