### ISSUE TITLE
Modrinth Support

### ISSUE THREAD

**Issue by Ecorous** [CraftTweaker/CraftTweaker#1509]
### Describe the feature you'd like

Post CraftTweaker on Modrinth. This would be useful because it could then be included in Modrinth modpacks

### Describe alternatives you've considered

You could, write in the CF description, and give it explicit permission to be used in Modrinth packs

### Modloader

All

**Comment by jaredlll08** [comment]
I currently have no interest in my mods being uploaded to Modrinth.

My files are already available to third parties via the CurseForge API.

This project is licensed under the MIT license which states that you don't need explicit permission to redistribute.

**Comment by Enderteck** [comment]
Hi, still no interest in releasing on Modrinth ?
