### ISSUE TITLE
Add Ability Modifier function will not have any ability slot requirements

### ISSUE THREAD

**Issue by KoiFeeish** [CraftTweaker/CraftTweaker#1511]
### Issue description

The Tinkers' Construct add ability modifier doesn't make the recipe require any ability slots no matter what number you set the requirement to. Everything else works fine but the ability slots required does not work and always requires no ability slots to apply.

### Script used

https://pastebin.com/8teDsz9C

### The crafttweaker.log file

https://pastebin.com/PXqyefwt

### Minecraft version

1.16

### Modloader

Forge

### Modloader version

36.2.34

### CraftTweaker version

7.1.2.511

### The latest.log file

https://gist.github.com/KoiFeeish/76f06589f920d2e95d681c8129f7d96c

**Comment by jaredlll08** [comment]
You will need to ask the tinkers construct devs about this, the support is in their mod and unless I'm misreading the code, the ability slots get passed just fine to the rest of their code, so I'm guessing that they would have the same issue if it was a datapack recipe.
