### ISSUE TITLE
[1.12.2] Startup Crash when script is present

### ISSUE THREAD

**Issue by Tcoffma1** [CraftTweaker/CraftTweaker#1512]
### Issue description

Making a personal pack for friends, made a really basic script that just deletes and adds different recipes. 

Put in a Stone Kiln recipe, loaded up everything fine, then bam, weird unknown mod crash.
This crash doesn't occur when a zs file isn't present, everything works fine until I put the script in.

![dude](https://user-images.githubusercontent.com/107629782/174091257-7ac650f2-a977-4403-8064-f3aaf916eb5d.PNG)

### Script used

https://pastebin.com/iGaHx91X

### The crafttweaker.log file

https://pastebin.com/pFet0x6i

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

14.23.5.2855

### CraftTweaker version

4.1.20.675

### The latest.log file

https://gist.github.com/Tcoffma1/f6fab3f27a572e6b04204ab162efbd20

**Comment by jaredlll08** [comment]
Remove these lines:
```zenscript
GraniteAnvil.addRecipe("copdust_from_ore", copdust, copore, 12, "pickaxe");
IroncladAnvil.addRecipe("copdust_from_ore", copdust, copore, 12, "pickaxe");
 
GraniteAnvil.addRecipe("copplate_from_ing", copplate, copingot, 12, "hammer");
IroncladAnvil.addRecipe("copplate_from_ing", copplate, copingot, 12, "hammer");
```
and see if it still crashes?

**Comment by Tcoffma1** [comment]
It actually loaded, is there like a limit or something to the amount of recipes I can add? Or is there something wrong with those recipes on Pyrotech's side.

**Comment by friendlyhj** [comment]
The recipe name should be unique. That is pyrotech's problem.

**Comment by Tcoffma1** [comment]
Alright, this is fixed, giving the recipes different names from each other works, thank you all for your time :D
