### ISSUE TITLE
[Feature Request] (...).removeByInput supports IItemStack[]

### ISSUE THREAD

**Issue by Laifsyn** [CraftTweaker/CraftTweaker#1513]
### Describe the feature you'd like

furnace.removeByInput supports IItemStack[]
blastFurnace.removeByInput supports IItemStack[]
https://docs.blamejared.com/1.18/tr/vanilla/api/recipe/manager/IRecipeManager#removeByInput

### Minecraft version

1.18

### Modloader

All

**Comment by jaredlll08** [comment]
This doesn't make sense, it implies that there can be multiple input for a single recipe and will be confusing for users.

You can do the same with a loop (which is exactly how it would be implemented anyway):

```zenscript
for item in game.items {
    furnace.removeByInput(item);
}```
