### ISSUE TITLE
Unending loop

### ISSUE THREAD

**Issue by Laifsyn** [CraftTweaker/CraftTweaker#1514]
### Issue description

```
val Textmyarray = [ "torch", "coal"] as string[];
for index in 0 .. Textmyarray.length {
    craftingTable.removeByName(Textmyarray[index]);
    craftingTable.addShapeless("test_" + Textmyarray[index] ,<item:minecraft:${Textmyarray[index]}>,[<item:minecraft:dirt>, <item:minecraft:torch>]);
    continue;
}
```

### Script used

*

### The crafttweaker.log file

*

### Minecraft version

1.18

### Modloader

Fabric

### Modloader version

0.14.7

### CraftTweaker version

9.1.153

### The latest.log file

*

**Comment by jaredlll08** [comment]
Will be tracked here:
https://github.com/ZenCodeLang/ZenCode/issues/99

It seems any usage of `continue` will lead to this, not sure why you are using it here though, it is the end of the loop, so it would do nothing anyway.

Your code should look like:
```zenscript
val Textmyarray = [ "torch", "coal"] as string[];
for index in 0 .. Textmyarray.length {
    craftingTable.removeByName(Textmyarray[index]);
    craftingTable.addShapeless("test_" + Textmyarray[index] ,<item:minecraft:${Textmyarray[index]}>,[<item:minecraft:dirt>, <item:minecraft:torch>]);
}
```

Actually, it could even look like:
```zenscript
val Textmyarray = ["torch", "coal"] as string[];
for text in Textmyarray {
    craftingTable.removeByName(text);
    craftingTable.addShapeless("test_" + text, <item:minecraft:${text}>, [<item:minecraft:dirt>, <item:minecraft:torch>]);
}
```

**Comment by Laifsyn** [comment]
About that, I was kinda lazy to comment out the unneeded second half of the loop, so I just threw a ``continue;`` there to simulate commenting that out

**Comment by jaredlll08** [comment]
Ah in that case you could do

```zenscript
val Textmyarray = ["torch", "coal"] as string[];
for text in Textmyarray {
    craftingTable.removeByName(text);
    craftingTable.addShapeless("test_" + text, <item:minecraft:${text}>, [<item:minecraft:dirt>, <item:minecraft:torch>]);
    if false {
    // other code here
    }
}
```

`if false` will never pass so the code will never run
