### ISSUE TITLE
[Feature Request] KeyPress to give items in REI

### ISSUE THREAD

**Issue by Laifsyn** [CraftTweaker/CraftTweaker#1515]
### Describe the feature you'd like

Creative tab allows you to press an inventory slot keybind on top of an item, and it will give you a stack of said item in the said slot.

Since it's more comfortable to search for items using REI, how about simulate a similar behavior instead of just raw giving you the item?

### Modloader

All

**Comment by jaredlll08** [comment]
Either I'm misunderstanding this, or you meant to make this issue on the REI issue tracker. 

This feature has nothing to do with CraftTweaker.
