### ISSUE TITLE
[1.18] ArmoreableMobs: Multiple Overrides Don't Work

### ISSUE THREAD

**Issue by Rythox** [CraftTweaker/CraftTweaker#1516]
### Issue description

Using more than two overrides per ArmorGroup causes every override for the group to cease functioning. Mobs spawning on the chosen blocks (i.e. <blockstate:minecraft:soul_sand>) do not receive the armor in the override(s). Using only two overrides (or just one) successfully applies both/it.

### Steps to reproduce

1. Create an ArmorGroup.
2. Attach more than two overrides to the ArmorGroup.
3. Mobs will spawn with the original armor set.

### Script used

https://pastebin.com/cZSzcA80

### The crafttweaker.log file

https://gist.github.com/Rythox/658e5a9405f15abd95b119c5d0e4c9dd

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.1.51

### CraftTweaker version

9.1.155

### Other relevant information

Immersive Armors - for the armor. This goes for any armor, however.
ArmoreableMobs version 1.0.4

### The latest.log file

https://gist.github.com/Rythox/edfe205dd3670e124fd041a8e48721e5

**Comment by jaredlll08** [comment]
Wrong repo, report to https://github.com/Buuz135/ArmoreableMobs/issues
