### ISSUE TITLE
Add support for GTCE:U

### ISSUE THREAD

**Issue by Nostras** [CraftTweaker/CraftTweaker#1517]
### Describe the feature you'd like

CraftTweaker supports GregTech Community Edition (the vanilla one, let's say) but does not support the new continuation of it, GregTech Community Edition: Unofficial.
I'm particularly interested in adding lossless cables (taken from Omnifactory), but this doesn't work as CraftTweaker fails to register the new cables.

[22:37:36] [Client thread/INFO] [minecraft/GuiNewChat]: [CHAT] §cERROR: PortedMaterials.zs:6 > No such static member in mods.gregtech.material.MaterialRegistry: createIngotMaterial

GTCE: https://www.curseforge.com/minecraft/mc-mods/gregtechce
GTCE:U: https://www.curseforge.com/minecraft/mc-mods/gregtech-ce-unofficial

Script snippet:
`#loader gregtech
import mods.gregtech.material.MaterialRegistry;
var materialList = MaterialRegistry.getAllMaterials();
val conductiveIron = MaterialRegistry.createIngotMaterial(700, "conductive_iron", 0xf7b29b, "shiny", 2);
pulsatingIron.setCableProperties(8, 1, 0);`

### Minecraft version

1.12

### Modloader

Forge

**Comment by jaredlll08** [comment]
CraftTweaker itself does not support Gregtech at all, it is all added by GregTech themselves.

Both of those mods have CraftTweaker related code in their repositories:
<https://github.com/GregTechCE/GregTech/tree/master/src/main/java/gregtech/api/recipes/crafttweaker>
<https://github.com/GregTechCEu/GregTech/tree/master/src/main/java/gregtech/api/recipes/crafttweaker>

Any issue you have with it will need to be reported to them.
