### ISSUE TITLE
Scalacube hosted Sky Odyssey not loading recipes

### ISSUE THREAD

**Issue by Talidorn** [CraftTweaker/CraftTweaker#1518]
### Issue description

The pastebin from their crafttweaker.log file is https://pastebin.com/z6YASnmz

It has a number of errors and they don't seem to think it is there issue, but I've run the pack on my home system and the changed recipes load and work as expected.

Any suggestions to give them to fix their deployment?

### Steps to reproduce

start a sky odyssey server on scalacube.com

### Script used

https://pastebin.com/Z9AvbkQu

### The crafttweaker.log file

https://pastebin.com/z6YASnmz

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

forge-1.12.2-14.23.5.2847-universal

### CraftTweaker version

CraftTweaker2-1.12-4.1.20.574

### Other relevant information

Any suggestion to allow this to become playable is appreciated.

### The latest.log file

https://pastebin.com/D9Sk1rZZ

**Comment by jaredlll08** [comment]
If you can self host the modpack on your machine just fine, then the issue is with the server host (or modpack author).

**Comment by kindlich** [comment]
Looks like their server does not have modtweaker installed.
Make sure their deployment is up-to-date with whatever changes are playable.

Get in contact with them and compare the list of mods as well as their versions.
Make sure all mods are also for 1.12 and not for another version of MC.

But as Jared already mentioned, that's hardly something we can assist with.
