### ISSUE TITLE
[Feature Request] You can choose where to insert the tooltip

### ISSUE THREAD

**Issue by Laifsyn** [CraftTweaker/CraftTweaker#1519]
### Describe the feature you'd like

An additional option that lets you choose at what index to push into the tooltip
![image](https://user-images.githubusercontent.com/99366187/175472680-04e1f40d-b404-4564-93ca-02a7d53cb840.png)

### Modloader

All

**Comment by kindlich** [comment]
This is already possible using tooltip functions:
<https://docs.blamejared.com/1.18/en/vanilla/api/item/IItemStack#modifyTooltip>

Something like
```zs
import stdlib.List;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.item.TooltipFlag;
import crafttweaker.api.text.Component;


<item:my:item>.modifyTooltip((stack as IItemStack, tooltip as List<Component>, flag as TooltipFlag) => {
    var index = 2;
    tooltip.insert(index, "my_tooltip");
});
```
