### ISSUE TITLE
Cannot join LAN worlds: "Failed to deserialize ingredient"

### ISSUE THREAD

**Issue by KxttyKxt** [CraftTweaker/CraftTweaker#1524]
### Issue description

I have not created any ZenScripts. When I try to join a LAN world, or when someone tries to join my lan world, an error pops up saying "Failed to deserialize ingredient..."

I am not the only person to have this issue with CraftTweaker on the Fabric loader. Removing CT fixes the issue.

### Steps to reproduce

Install CraftTweaker (and dependencies? I did it through CurseForge), run your modpack, and try to join a LAN world, even a localhost. You will fail to join and it will generate an error.

### Script used

No script was used.

### The crafttweaker.log file

https://gist.github.com/KxttyKxt/46eb8e9ca504b496dea16b22873862b5

### Minecraft version

1.18

### Modloader

Fabric

### Modloader version

0.14.8

### CraftTweaker version

1.18.2-9.1.164

### Other relevant information

Fabric API Version: 0.57.0+1.18.2

The relevant crash is in the latest.log on line 1063. This information does not show up when someone fails to join you, only when YOU fail to join someone. This does not crash the game most times.

### The latest.log file

https://gist.github.com/KxttyKxt/552785d4197b7e1b5132b371e53855d2

**Comment by KxttyKxt** [comment]
This issue might actually be caused by Ingredient Extension API, which was automatically downloaded alongside CraftTweaker when installing CraftTweaker via curseforge.

**Comment by jaredlll08** [comment]
>  Removing CT fixes the issue.

Can you remove CT and leave the ingredient extension API installed and see if that works?

**Comment by KxttyKxt** [comment]
Upon removing CT and leaving ingredient extension API, the issue persists. I will post this issue to their github repo instead.
Thank you for your time, Jared. :sparkles:
