### ISSUE TITLE
replace function not working

### ISSUE THREAD

**Issue by menguele** [CraftTweaker/CraftTweaker#1535]
### Issue description

Trying to replace anything with `recipes.replaceAllOccurrences()` results in error

### Script used

https://gist.github.com/menguele/e3e55fb92739f4dbe38ff31cf7e6f6b2

### The crafttweaker.log file

https://gist.github.com/menguele/dea0fe7bd23d53b08df91675a41c3408

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

14.23.5.2860

### CraftTweaker version

4.1.20.678

### Other relevant information

I use OpenJ9, with Hotspot or GraalVM it says `[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: test.zs}: Truncated class file` on line 34, the rest seems the same

### The latest.log file

https://gist.github.com/menguele/e0b09708d5efe79e53fce96aeb7a60b0

**Comment by friendlyhj** [comment]
`recipes.replaceAllOccurences`, you typed double R.
I know `Occurrences` is proper spelling...

**Comment by menguele** [comment]
Man, I don't really know how that got inserted bc I was getting the same error even after #1533 , then I just copy-pasted the first example from the Wiki and didn't work, VSCode auto-correcting misspelling maybe?

Turns out using `null` instead of `<minecraft:air>` was the answer, should probably add this to the documentation (maybe it's already in there but I haven't read all of it yet).

Thank you very much.

**Comment by jaredlll08** [comment]
> `recipes.replaceAllOccurences`, you typed double R. I know `Occurrences` is proper spelling...

We could add a new method that fixes the typo?

**Comment by menguele** [comment]
> > `recipes.replaceAllOccurences`, you typed double R. I know `Occurrences` is proper spelling...
> 
> We could add a new method that fixes the typo?

that would be nice, but isn't that bloat?

**Comment by jaredlll08** [comment]
not that much bloat.
