### ISSUE TITLE
All drops contain diamonds??

### ISSUE THREAD

**Issue by NetheriteNinja10** [CraftTweaker/CraftTweaker#1543]
### Issue description

For some weird inexplicable reason whenever i break blocks with this mod it drops diamonds, same with entities.  I initially realized this in my modpack then i used this mod on its own and it was JUST THIS MOD causing the issue.  I am trying to use this on my server but it will cause the economy to crash if I do.  I could not get an easier mod to do this.  Please fix it.

### Steps to reproduce

Break any blocks or kill any mobs

### Script used

i didnt even have a script going

### The crafttweaker.log file

it was blank

### Minecraft version

1.18

### Modloader

Fabric

### Modloader version

0.14.8

### CraftTweaker version

9.1.185

### The latest.log file

This was also blank I have no clue why

**Comment by NetheriteNinja10** [comment]
Looking through it now, the mod looks like its a recipe based backdoor.  Dirt work as wood plank??  Diamonds can be made from rails dirt and a log or another piece of dirt???  These were added by THIS MOD

**Comment by jaredlll08** [comment]
You must have ran `/ct examples` which generates example files.

We do absolutely nothing without a script existing telling us to do it, so just remove the files in `scripts/examples` and you'll be good
