### ISSUE TITLE
Support for 1.19?

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#1544]
### Describe the feature you'd like

**Support for 1.19**

### Minecraft version

Other

### Modloader

Fabric

**Comment by xR4YM0ND** [comment]
we need 1.19.x <3

**Comment by Looodon** [comment]
> we need 1.19.x <3

we do!

**Comment by Mrbysco** [comment]
It's being worked on (See https://github.com/CraftTweaker/CraftTweaker/discussions/1557)
