### ISSUE TITLE
[1.7.10] [Forge Server]

### ISSUE THREAD

**Issue by Gargule** [CraftTweaker/CraftTweaker#1545]
### Issue description

I know, 1.7.10 dead and everything, but on forge server this:
```
/* 
////////////Made by Gargule
*/
```
turns into this:
```
/////////////* 
////////////Made by Gargule
*/
```
which causes script to be invalid.
KCauldron and other "third party" servers works well, altrough. Bug appears only with Forge Server.
Also this bug kill any cyrilic symbols in the script.

### Steps to reproduce

1. Make a forge server with CT and some other mods (Or maybe with my WHOLE MODPACK, i'm not sure)
2. Connect to it from client
3. Done. Now your scripts from both client and server is scrambled

### Script used

https://pastebin.com/XH4yvs7G

### The crafttweaker.log file

https://gist.github.com/Gargule/4b490050da3244aad11e7e4146fb7e3e

### Minecraft version

Other

### Modloader

Forge

### Modloader version

10.13.4.1614

### CraftTweaker version

3.1.0-legacy

### Other relevant information

My modpack is here:
https://github.com/MaintainersOfMine1-7-10/MinecraftModpack1710
And yes, because it's in dev i didn't added credits and other stuff about used mods yet
Hope i added proper logs cuz i'm too tired now and really need to have some sleep before running Minecraft again.
Also, this is logs from client, but i'll add logs from server after sleep.

### The latest.log file

https://gist.github.com/Gargule/2f350b5a3ec9abbb8f291bf52a49e9fd

**Comment by jaredlll08** [comment]
1.7 isn't supported, on top of that, 1.7 has been used so much that this is extremely highly unlikely to actually be an issue with any mod (we would have been told about it, it wouldn't take years before someone found an issue this "big"), and is most likely an issue with how you are uploading the files to the server, or the files being saved with a weird encoding.

**Comment by Gargule** [comment]
Well, thanks for pointing where might be my mistake then. I'll check encodings later and will close this if it will be wrong.
But anyways, WHY at the first place CT writes in scripts files? And why only when on forge server?
(Maybe i'm an idiot and my encoding breaked when i changed KCauldron to Forge)

**Comment by jaredlll08** [comment]
We don't write to the script files, you do or the modpack you're using does, as for why it only breaks on a Forge server, the answer lies with whatever you did, it works fine for literally everyone else (you're the first to report issues about it not working)
