### ISSUE TITLE
Error when Creating Custom Recipe: An ingredient entry needs either a tag or an item

### ISSUE THREAD

**Issue by Jurklein** [CraftTweaker/CraftTweaker#1547]
### Issue description

I'm trying to create a generic recipe for the fabric mod "farmer's delight", just for testing purposes; it could be any other mod.

When trying to add the recipe, I get the error "An ingredient entry needs either a tag or an item".

### Script used

https://gist.github.com/Jurklein/f38eb44c34aa6f11b9b64d12c485c27e

### The crafttweaker.log file

https://gist.github.com/Jurklein/ffc4fc7a5fd9c0f2f0f7ed85c683c889

### Minecraft version

1.18

### Modloader

Fabric

### Modloader version

0.14.8

### CraftTweaker version

9.1.177

### The latest.log file

https://gist.github.com/Jurklein/8c688c84efd727535a7f908be2d3593b

**Comment by Jurklein** [comment]
The json should  be as described here: https://github.com/vectorwing/FarmersDelight/wiki/Cutting-Board-Recipes

**Comment by jaredlll08** [comment]
You are looking at the ***forge*** version, not the ***fabric*** version, this recipe from the fabric version does what you want I believe:
https://github.com/newhoryzon/farmers-delight-fabric/blob/master/src/main/resources/data/farmersdelight/recipes/cutting/acacia_door.json#L8-L11

**Comment by Jurklein** [comment]
Yes, that solved it. Thanks!
