### ISSUE TITLE
[1.12.2] Problems removing crafting mods

### ISSUE THREAD

**Issue by Kellmyru** [CraftTweaker/CraftTweaker#1548]
### Issue description

I use the command to remove the recipe from the Advanced Rocketry modification and I can't do it. Returns error: ERROR:project.zs:7 > No such member > advancedRocketry ERROR:[craftweaker]: Error executing {[0:craftweaker]: project.zs} : Truncated class file, caused by java.lang.ClassFormatError:Truncated class file
Mods: 
AdvancedRocketry-1.12.2-2.0.0-13
LibVulpes-1.12.2-0.4.2-25-universal
jei_1.12.2-4.16.1.302
modelloader-1.1.7
CraftTweaker2-1.12-4.1.20.679

### Script used

mods.advancedRocketry.lathe.removeRecipe(<libvulpes:productrod:10>);  //I used this command in My project.zs file

### The crafttweaker.log file

14 days: https://dropmefiles.com/ewKEk

### Minecraft version

1.12

### Modloader

All

### Modloader version

modelloader-1.1.7

### CraftTweaker version

CraftTweaker2-1.12-4.1.20.679

### Other relevant information

I tried to install ARTweacker and mods+Craftweaker of other versions, there is no removal of crafting for machines of this mod

### The latest.log file

14 days: https://dropmefiles.com/uwEco

**Comment by jaredlll08** [comment]
Upload your files to pastebin.com or gist.github.com, I'm not downloading files.

**Comment by Kellmyru** [comment]
https://gist.github.com/Kellmyru/b903b906bf5399daae156496f33dd05c URL

**Comment by jaredlll08** [comment]
```
mods.advancedRocketry.lathe.removeRecipe(libvulpes:productrod:10); //I used this command in My project.zs file


```
should be:
```
mods.advancedrocketry.lathe.removeRecipe(libvulpes:productrod:10); //I used this command in My project.zs file
```
The case matters

**Comment by Kellmyru** [comment]
@jaredlll08  im use and "advancedrocketry" , in the position of specifying the mod, the problem still remained. Craftweaker just doesn't see the mod, no matter how I write it.I even rummaged through the mod files to find out how to correctly specify the mod itself, but without results!

**Comment by Kellmyru** [comment]
I perfectly understand the syntax and the fact that the big and small letters matter, if that was the case, I wouldn't have written the ticket

**Comment by jaredlll08** [comment]
Do you have https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry-tweaker installed?

**Comment by Kellmyru** [comment]
I tried with and without AR Tweaker installed.  With AR Tweaker installed, it just crashes if you write the commands that AR Tweaker offers, without it, what happens is what is written at the very beginning of the appeal

**Comment by jaredlll08** [comment]
Okay, I'm only using the information that you have given me, and that information is:
1) This log file which does not mention ARTweaker: <https://gist.github.com/Kellmyru/b903b906bf5399daae156496f33dd05c>
2) `project.zs:7 > No such member: advancedRocketry`, which has a capital `R`.

So install ARTweaker, make sure that the case is correct on your lines and then if it still has an issue, give me *that* log file

**Comment by Kellmyru** [comment]
Well, when I install ARTweaker and write everything correctly, the usual crash of the launcher occurs when I try to boot.  I will ship within 16 hours

**Comment by Kellmyru** [comment]
https://gist.github.com/Kellmyru/391d840d0b8c933461ada1e7f5000d0d

**Comment by jaredlll08** [comment]
Okay so basically what has happened is that after ARTweaker made their release, Advanced Rocketry made a breaking change, so the issue is with ARTweaker, they would need to update or you could downgrade Advanced Rocketry to a version that works (unfortunately I can't help there).

**Comment by Kellmyru** [comment]
Okay, ok, can you then add the necessary functionality to craftweaker to work with Advanced Rocketry mod recipes?

**Comment by jaredlll08** [comment]
No, I'm bit touching 1.12 and even if I was I have no interest in more mod support, modtweaker ruined that for me.

**Comment by Kellmyru** [comment]
The Craftweaker mod is used to make changes to the game's resources, including crafting. It is a pity that the only tool that would allow this to be done does not support the modifications for which Craftweaker is most often used. The Advanced Rocketry mod has more than 16 million downloads and the mod deserves, in my opinion, to have support from Craftweaker. Advanced Rocketry has not complicated .class components, but alas, my java knowledge was not enough to work with it, I found Craftweaker and it turned out to be a non-working option in the end, it's very sad.

**Comment by jaredlll08** [comment]
Just to be extremely clear here, CraftTweaker works fine, the issues are that advanced rocketry made a breaking change mid version, breaking their addon mods, and then ARTweaker never updated for those breaking changes.

I have no control over that and frankly I find it a bit disrespectful that you're demanding the support from me instead of demanding it from them, my mod has 100 million downloads, does it not deserve for *them* to add support themselves? 

Also the fact that they made breaking changes on a version that is over 5 years old that not many modders touch anymore just cements the fact that I'm not touching their code in fear it would break every 2 months.

If you want support, go complain to them, or the ARTweaker guys, because I am already struggling to keep up with porting everything to new versions, while adding new features, and here you want me to spend time on an old version.
