### ISSUE TITLE
Crafttweaker conflicts with craafttweaker jei support?

### ISSUE THREAD

**Issue by Seentro** [CraftTweaker/CraftTweaker#1551]
### Issue description

i wanted to start up minecraft like yesterday (it worked fine), but it crashed a bunch of times. heres the crash report https://pastebin.com/r7aLN0ah

### Script used

https://pastebin.com/v7Bhy6iM

### The crafttweaker.log file

https://pastebin.com/r7aLN0ah

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

14.23.5.2854

### CraftTweaker version

4.1.20.680

### Other relevant information

nothing really, it worked fine just yesterday

### The latest.log file

theres no log file

**Comment by jaredlll08** [comment]
From the looks of it, there is an issue creating the `crafttweaker.log`, try deleting the file if it exists and make sure you have permission to make the file wherever it is trying to make the file.

What launcher are you using?

**Comment by Seentro** [comment]
Nvm restarting my laptop fixed it lol

pon., 5 wrz 2022, 18:24 użytkownik Jared ***@***.***> napisał:
