### ISSUE TITLE
1.16 not available MCLevelChangeEvent

### ISSUE THREAD

**Issue by Gu-meng** [CraftTweaker/CraftTweaker#1553]
### Issue description

CTEventManager.register<crafttweaker.api.event.entity.player.xp.MCLevelChangeEvent>(event => {});
This error will occur when this is used -> https://pastebin.com/3B1eNGZn

### Script used

https://pastebin.com/tu1ig2Fz

### The crafttweaker.log file

https://pastebin.com/5jmR81XW

### Minecraft version

1.16

### Modloader

Forge

### Modloader version

forge-36.2.34

### CraftTweaker version

7.1.2.511

### The latest.log file

log exceeded the maximum size of 512 kilobytes.

**Comment by jaredlll08** [comment]
Closed by https://github.com/CraftTweaker/CraftTweaker/commit/c8c28102129bceaef16a0f704055d3a3f2feddba
