### ISSUE TITLE
BlockToolInteractEvent not working

### ISSUE THREAD

**Issue by LaidBackSloth** [CraftTweaker/CraftTweaker#1554]
### Issue description

Using BlockToolInteractEvent always creates an error, even without doing anything in that event:
Cannot invoke "Object.equals(Object)" because "instanced" is null

### Script used

https://gist.github.com/LaidBackSloth/d538646ebaf0a121e630d7312d017798

### The crafttweaker.log file

https://gist.github.com/LaidBackSloth/922a31a46d5b306cf6770d2b3503db57

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.1.80

### CraftTweaker version

9.1.189

### The latest.log file

https://gist.github.com/LaidBackSloth/f0dede57dae4a4b76d843b6f61b7b372

**Comment by jaredlll08** [comment]
Closed by 6cb293594821a0dda2cddb4e8acd07069a16ac00
