### ISSUE TITLE
Null Error message while using .setHarvestTool

### ISSUE THREAD

**Issue by ItoKyoshiro** [CraftTweaker/CraftTweaker#1559]
### Issue description

I'm setting the Harvest Tool as Pickaxe for this Blocks & Panes (Vanilla Glass, Modded Glass & Smithing Table).

In game got the error message: "Error running scripts: null" but no more information is provided.

Asking over the Discord the issue seems to be that one of those blocks didn't have a harvest level before and was advised to create a report for this.

### Steps to reproduce

Not sure if necessary, but in case: 
Add the script.
Place the block in question.
Use /reload.

### Script used

https://gist.github.com/ItoKyoshiro/8f26ec19feb0e424bf6efaf52eac7998

### The crafttweaker.log file

https://gist.github.com/ItoKyoshiro/29f9ee9e36784ec7e8081c463f655812

### Minecraft version

1.16

### Modloader

Forge

### Modloader version

36.2.34

### CraftTweaker version

1.16.5-7.1.2.512

### Other relevant information

Mods used for this:
Create - create-mc1.16.5_v0.3.2g
Macaw's Windows - mcw-windows-2.0.3-mc1.16.5
Quark - Quark-r2.4-323

### The latest.log file

https://gist.github.com/ItoKyoshiro/40fa1f3cdf648e15c0edc8e0e731a5f9

**Comment by jaredlll08** [comment]
fixed by https://github.com/CraftTweaker/CraftTweaker/commit/716d89e5a9e3255bf68aecb0ad327c03228184af
