### ISSUE TITLE
[1.12.2] Astral Sorcery isn't being found

### ISSUE THREAD

**Issue by FlamingTundra** [CraftTweaker/CraftTweaker#1560]
### Issue description

I'm making a modpack and want to make a recipe for an item which is created via Astral Sorcery Alter (Highest Level) but when I try it, it says it doesn't find the mod. Can someone help me with this problem? I've checked many things and was looking at the Crafttweaker wiki but that didn't help me.

### Script used

https://drive.google.com/file/d/1jMQhWDM4aXQGJrzCY6zbCTEZTqS-Xml2/view?usp=sharing

### The crafttweaker.log file

https://drive.google.com/file/d/1QHRwGplmjs6TqcNpEgou9_s27r8vw9OL/view?usp=sharing

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

14.23.5.2860

### CraftTweaker version

4.1.20.680

### Other relevant information

Astral Sorcery Version is 1.10.27

### The latest.log file

https://drive.google.com/file/d/1ExYGSBxIXPLLGs-S-a0zKzSWLMY_JFC5/view?usp=sharing

**Comment by jaredlll08** [comment]
Please don't upload files to google drive.


At the end of line `9` you have: `astralsorcery.constellation.vicio`, that should probably be: `"astralsorcery.constellation.vicio"`
