### ISSUE TITLE
[1.18.2] /ct dump_brackets does not create biome file

### ISSUE THREAD

**Issue by drakray** [CraftTweaker/CraftTweaker#1562]
### Issue description

As the title say, using CT 9.1.192 for 1.18.2
Using /ct dump biomes output the list in the log file
Using /ct dump_brackets create the other files, but no biome.txt

### Steps to reproduce

start game
use `/ct dump_brackets`
goto folder
no biome.txt files

### Script used

no script, just command

### The crafttweaker.log file

n/a

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.1.80

### CraftTweaker version

9.1.192

### The latest.log file

n/a

**Comment by jaredlll08** [comment]
`/ct dump_brackets` only dumps things that can be used as a bracket like: `<item:minecraft:dirt>`, `<block:minecraft:dirt>`, which you cannot do with biomes.

**Comment by drakray** [comment]
Ah ok I understand, thank you :)
