### ISSUE TITLE
Updated but not functional on 1.19.2

### ISSUE THREAD

**Issue by Zelioth** [CraftTweaker/CraftTweaker#1563]
### Issue description

just added to my pack and instantly failed to load in. removing it fixed the crash. 
[crash-2022-10-11_23.06.58-fml.txt](https://github.com/CraftTweaker/CraftTweaker/files/9761436/crash-2022-10-11_23.06.58-fml.txt)

### Script used

N/A

### The crafttweaker.log file

N/A

### Minecraft version

1.19

### Modloader

Forge

### Modloader version

43.1.34

### CraftTweaker version

10.0.0.2

### The latest.log file

Applied above

**Comment by jaredlll08** [comment]
You are using the 1.18 version of JEITweaker.
