### ISSUE TITLE
Craft Tweaker automatically installs older verison of JEITweaker when installing CT 

### ISSUE THREAD

**Issue by Zelioth** [CraftTweaker/CraftTweaker#1564]
### Issue description

Installing 1.19.2 Craft Tweaker automatically installs 1.18 version of JEITweaker. 

Forge 43.1.34

### Script used

na

### The crafttweaker.log file

n/a

### Minecraft version

1.19

### Modloader

All

### Modloader version

43.1.34

### CraftTweaker version

10.0.2

### The latest.log file

n/a

**Comment by jaredlll08** [comment]
This is more an issue with the curse launcher, since we don't automatically install mods, but I'll remove the dep for now
