### ISSUE TITLE
1.19.2 Crash

### ISSUE THREAD

**Issue by Looodon** [CraftTweaker/CraftTweaker#1565]
### Issue description

Crafttweaker was working normally, but once I updated it to the latest version and as I was setting up my modpack suddenly it's crashing. Thankfully, It generated a crash report I attached here, which has all the extra details. Crafttweaker on Curseforge says "
JEITweaker" is a Required Dependency, but it was working all day without it so I feel like that is not the reason as to why this is happening. I assumed I wouldn't need JEITweaker since it's not updated to 1.19.2, but now I'm unsure

### Script used

https://pastebin.com/9q2hHF12

### The crafttweaker.log file

https://pastebin.com/7ve0fGyy

### Minecraft version

1.19

### Modloader

Forge

### Modloader version

43.1.34

### CraftTweaker version

10.0.3

### The latest.log file

https://pastebin.com/YUz6ENNC

**Comment by jaredlll08** [comment]
Remove JEITweaker, it is using the 1.18 version, curseforge auto installs it.

**Comment by Looodon** [comment]
It worked! thank you :)
