### ISSUE TITLE
[1.19.2] Game do not load with Mekanism present

### ISSUE THREAD

**Issue by hodo1962** [CraftTweaker/CraftTweaker#1569]
### Issue description

If the mod Mekanism is present, the game crashes during the load process.

### Steps to reproduce

Tested with Mekanism version 10.33.470 and 10.34.471.
Same result

### Script used

no script used

### The crafttweaker.log file

https://pastebin.com/fDLTSf8B

### Minecraft version

1.19

### Modloader

Forge

### Modloader version

43.1.23

### CraftTweaker version

10.0.12

### Other relevant information

Without Mekanism, Minecraft with the Crafttweaker mod load without any problems.

### The latest.log file

https://paste.ee/p/nSxh2

**Comment by jaredlll08** [comment]
Mekanism needs to fix it on their side. 
https://github.com/mekanism/Mekanism/issues/7638
