### ISSUE TITLE
Crash on Startup 1.19

### ISSUE THREAD

**Issue by IchigoGames** [CraftTweaker/CraftTweaker#1570]
### Issue description

The Game crashes on start it's Probably a mod conflict but im not sure what mod do not see it in any of the logs this is a modpack but i am the modpack creator and its on a test not public version.

### Steps to reproduce

does it only a few secs after starting 

### Script used

n/a

### The crafttweaker.log file

https://pastebin.com/gwLmRX8y

### Minecraft version

1.19

### Modloader

Forge

### Modloader version

43.1.43

### CraftTweaker version

CraftTweaker-forge-1.19.2-10.0.12

### The latest.log file

crash report https://pastebin.com/HhyK50T6 

https://gist.github.com/IchigoGames/5878634df541a44c6ddee9b66ceacc31 log

**Comment by jaredlll08** [comment]
Mekanism needs to fix it on their side. https://github.com/mekanism/Mekanism/issues/7638

**Comment by IchigoGames** [comment]
oh ok
