### ISSUE TITLE
Hopefully you can add a recipe that removes the smithing_table

### ISSUE THREAD

**Issue by yuankun1** [CraftTweaker/CraftTweaker#1571]
### Describe the feature you'd like

I hope to add a smithing that can delete the original version_ Synthetic formula of table

### Describe alternatives you've considered

smithing.removeRecipe("recipe_name", <item:minecraft:smithing_table> , <item:minecraft:diamond_helmet> , <item:minecraft:netherite_ingot>);

### Minecraft version

1.16

### Modloader

Forge

**Comment by jaredlll08** [comment]
If I understand what you're asking, it's on the docs:
https://docs.blamejared.com/1.16/en/vanilla/api/managers/SmithingManager#removeRecipe
or
https://docs.blamejared.com/1.16/en/vanilla/api/managers/SmithingManager#removeByName
