### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by vrork** [CraftTweaker/CraftTweaker#1573]
### Issue description

I am having a crash on launch and it only happens when i am enable CT.

### Steps to reproduce

Just have it enabled

### Script used

none

### The crafttweaker.log file

https://gist.github.com/vrork/261b7110174e6eb6d1fa98cf16249b77

### Minecraft version

1.19

### Modloader

Forge

### Modloader version

43.1.43

### CraftTweaker version

10.0.12

### Other relevant information

- Mod List: 
		saturn-mc1.19.2-0.0.1.jar                         |Saturn                        |saturn                        |0.0.1               
		YungsBetterDungeons-1.19.2-Forge-3.2.1.jar        |YUNG's Better Dungeons        |betterdungeons                |1.19.2-Forge-3.2.1  
		supermartijn642configlib-1.1.6b-forge-mc1.19.jar  |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.6b              
		nether-s-exoticism-1.19.2-1.2.0.jar               |Nether's Exoticism            |nethers_exoticism             |1.2.0               
		HammerLib-1.19.2-19.1.27.jar                      |HammerLib                     |hammerlib                     |19.1.27             
		rubidium-0.6.2.jar                                |Rubidium                      |rubidium                      |0.6.2               
		NyfsQuiver-1.19.2-0.7.4.jar                       |Nyf's Quiver                  |nyfsquiver                    |1.18.1-0.7.0        
		modnametooltip-1.19-1.19.0.jar                    |Mod Name Tooltip              |modnametooltip                |1.19.0              
		create_jetpack-2.1.0.jar                          |Create Jetpack                |create_jetpack                |2.1.0               
		IronJetpacks-1.19.2-6.0.1.jar                     |Iron Jetpacks                 |ironjetpacks                  |6.0.1               
		laserio-1.5.0.jar                                 |LaserIO                       |laserio                       |1.5.0               
		YungsApi-1.19.2-Forge-3.8.2.jar                   |YUNG's API                    |yungsapi                      |1.19.2-Forge-3.8.2  
		hiddenrecipebook_1.19.2-3.0.jar                   |Hidden Recipe Book            |hiddenrecipebook              |3.0                 
		rangedpumps-1.0.0.jar                             |Ranged Pumps                  |rangedpumps                   |1.0.0               
		macawsbridgesbop-1.19.2-1.0.jar                   |Macaw's Bridges - BOP         |macawsbridgesbop              |1.19.2-1.0          
		guardvillagers-1.19.2-1.5.2.jar                   |Guard Villagers               |guardvillagers                |1.19.2-1.5.2        
		DarkUtilities-Forge-1.19.2-13.1.3.jar             |DarkUtilities                 |darkutils                     |13.1.3              
		balm-4.5.3.jar                                    |Balm                          |balm                          |4.5.3               
		cloth-config-8.2.88-forge.jar                     |Cloth Config v8 API           |cloth_config                  |8.2.88              
		stackrefill_1.19.2-3.2.jar                        |Stack Refill                  |stackrefill                   |3.2                 
		shetiphiancore-1.19-3.11.0.jar                    |ShetiPhian-Core               |shetiphiancore                |3.11.0              
		supplementaries-1.19.2-2.2.9.jar                  |Supplementaries               |supplementaries               |1.19.2-2.2.9        
		upgradednetherite-1.19.2-5.1.0.2-release.jar      |Upgraded Netherite            |upgradednetherite             |1.19.2-5.1.0.2-relea
		mcw-trapdoors-1.0.7-mc1.19.2.jar                  |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.7               
		supermartijn642corelib-1.0.19a-forge-mc1.19.jar   |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.19a             
		YungsBridges-1.19.2-Forge-3.1.0.jar               |YUNG's Bridges                |yungsbridges                  |1.19.2-Forge-3.1.0  
		spark-1.9.42-forge.jar                            |spark                         |spark                         |1.9.42              
		curios-forge-1.19.2-5.1.1.0.jar                   |Curios API                    |curios                        |1.19.2-5.1.1.0      
		copperoverhaul-MC1.19.2-22.10.11.jar              |Copper Overhaul               |copperoverhaul                |22.10.11            
		advgenerators-1.4.0.3-mc1.19.2.jar                |Advanced Generators           |advgenerators                 |1.4.0.3             
		YungsExtras-1.19.2-Forge-3.1.0.jar                |YUNG's Extras                 |yungsextras                   |1.19.2-Forge-3.1.0  
		antighost-1.19.1-forge42.0.1-1.1.2.jar            |AntiGhost                     |antighost                     |1.19.1-forge42.0.1-1
		abundant_atmosphere-1.19.2-0.2.1.jar              |Abundant Atmosphere           |abundant_atmosphere           |0.2-1.19.2          
		mcw-roofs-2.2.1-mc1.19.2-forge.jar                |Macaw's Roofs                 |mcwroofs                      |2.2.1               
		littlelogistics-mc1.19.2-v1.3.0.jar               |Little Logistics              |littlelogistics               |1.3.0               
		cfm-7.0.0-pre34-1.19.jar                          |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre34         
		refinedcooking-3.0.1.jar                          |Refined Cooking               |refinedcooking                |3.0.1               
		refinedstorage-1.11.0.jar                         |Refined Storage               |refinedstorage                |1.11.0              
		ExtraStorage-1.19.2-3.0.1.jar                     |Extra Storage                 |extrastorage                  |3.0.1               
		mcw-furniture-3.0.2-mc1.19.2.jar                  |Macaw's Furniture             |mcwfurnitures                 |3.0.2               
		extendedflywheels-1.2.2-1.19.2-0.5.f.jar          |Extended Flywheels            |extendedflywheels             |1.2.2-1.19.2-0.5.f  
		FastLeafDecay-30.jar                              |FastLeafDecay                 |fastleafdecay                 |30                  
		CodeChickenLib-1.19.2-4.3.0.470-universal.jar     |CodeChicken Lib               |codechickenlib                |4.3.0.470          
		YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar      |YUNG's Better Mineshafts      |bettermineshafts              |1.19.2-Forge-3.2.0  
		geckolib-forge-1.19-3.1.27.jar                    |GeckoLib                      |geckolib3                     |3.1.27              
		NekosEnchantedBooks-1.19-1.8.0.jar                |Neko's Enchanted Books        |nebs                          |1.8.0               
		DarkPaintings-Forge-1.19.2-13.1.2.jar             |DarkPaintings                 |darkpaintings                 |13.1.2              
		mcw-lights-1.0.4-mc1.19.2.jar                     |Macaw's Lights and Lamps      |mcwlights                     |1.0.4               
		elytraslot-forge-6.0.0+1.19.2.jar                 |Elytra Slot                   |elytraslot                    |6.0.0+1.19.2        
		StylishEffects-v4.3.2-1.19.2-Forge.jar            |Stylish Effects               |stylisheffects                |4.3.2               
		rechiseled-1.0.10c-forge-mc1.19.jar               |Rechiseled                    |rechiseled                    |1.0.10c             
		mining_helmet-1.19-2.1.1.jar                      |Mining Helmet                 |mining_helmet                 |2.1.1               
		harvestwithease-1.19.2-4.0.0.2-forge.jar          |Harvest with ease             |harvestwithease               |4.0.0.2             
		jei-1.19.2-forge-11.3.0.271.jar                   |Just Enough Items             |jei                           |11.3.0.271          
		archbows-1.1.1-1.19.2.jar                         |Arch Bows                     |archbows                      |1.1.1-1.19.2        
		AttributeFix-Forge-1.19.2-17.1.3.jar              |AttributeFix                  |attributefix                  |17.1.3              
		tesseract-1.0.27b-forge-mc1.19.jar                |Tesseract                     |tesseract                     |1.0.27b             
		caelus-forge-1.19.2-3.0.0.6.jar                   |Caelus API                    |caelus                        |1.19.2-3.0.0.6      
		bdlib-1.24.1.4-mc1.19.2.jar                       |BdLib                         |bdlib                         |1.24.1.4            
		shutupexperimentalsettings-1.0.5.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.5               
		phosphophyllite-1.19.2-0.6.0-beta.5.jar           |Phosphophyllite               |phosphophyllite               |0.6.0-beta.5        
		farmingforblockheads-forge-1.19-11.1.0.jar        |Farming for Blockheads        |farmingforblockheads          |11.1.0              
		Guide-API-VP-1.19.2-2.2.4.jar                     |Guide-API VP                  |guideapi_vp                   |2.2.4               
		CraftTweaker-forge-1.19.2-10.0.12.jar             |CraftTweaker                  |crafttweaker                  |10.0.12             
		Mekanism-1.19.2-10.3.4.471.jar                    |Mekanism                      |mekanism                      |10.3.4              
		ExtraDisks-1.19.2-2.2.0.jar                       |Extra Disks                   |extradisks                    |1.19.2-2.2.0        
		EdivadLib-1.19.2-1.2.0.jar                        |EdivadLib                     |edivadlib                     |1.2.0               
		forge-1.19.2-43.1.43-universal.jar                |Forge                         |forge                         |43.1.43             
		silent-gear-1.19.2-3.0.4.jar                      |Silent Gear                   |silentgear                    |3.0.4               
		mcw-paths-1.0.1-mc1.19.2.jar                      |Macaw's Paths and Pavings     |mcwpaths                      |1.0.1               
		ironchest-1.19.2-14.2.7.jar                       |Iron Chests                   |ironchest                     |1.19.2-14.2.7       
		ZeroCore2-1.19-2.1.26.jar                         |Zero CORE 2                   |zerocore                      |1.19-2.1.26         
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              
		radon-0.8.2.jar                                   |Radon                         |radon                         |0.8.2               
		theoneprobe-1.19-6.2.2.jar                        |The One Probe                 |theoneprobe                   |1.19-6.2.2          
		appliedenergistics2-forge-12.8.3-beta.jar         |Applied Energistics 2         |ae2                           |12.8.3-beta         
		TerraBlender-forge-1.19.2-2.0.1.128.jar           |TerraBlender                  |terrablender                  |2.0.1.128           
		BiomesOPlenty-1.19.2-17.1.1.162.jar               |Biomes O' Plenty              |biomesoplenty                 |17.1.1.162          
		MouseTweaks-forge-mc1.19-2.23.jar                 |Mouse Tweaks                  |mousetweaks                   |2.23                
		Female-Gender-Mod-forge-1.19.1-3.0.1.jar          |Wildfire's Female Gender Mod  |wildfire_gender               |1.19-3.0.0          
		commonality-1.19.2-4.2.0.jar                      |Commonality                   |commonality                   |4.2.0               
		ImmersiveEngineering-1.19.2-9.0.0-153.jar         |Immersive Engineering         |immersiveengineering          |1.19.2-9.0.0-153    
		spectrelib-forge-0.10.0+1.19.jar                  |SpectreLib                    |spectrelib                    |0.10.0+1.19         
		pipez-1.19.2-1.0.0.jar                            |Pipez                         |pipez                         |1.19.2-1.0.0        
		flywheel-forge-1.19.2-0.6.7-8.jar                 |Flywheel                      |flywheel                      |0.6.7-8             
		ecologics-forge-1.19.2-2.1.10.jar                 |Ecologics                     |ecologics                     |2.1.10              
		Xaeros_Minimap_22.16.0_Forge_1.19.1.jar           |Xaero's Minimap               |xaerominimap                  |22.16.0             
		Croptopia-1.19.2-FORGE-2.1.0.jar                  |Croptopia                     |croptopia                     |2.1.0               
		polymorph-forge-0.45.0+1.19.2.jar                 |Polymorph                     |polymorph                     |0.45.0+1.19.2       
		AutoRegLib-1.8-54.jar                             |AutoRegLib                    |autoreglib                    |1.8-54              
		almostunified-forge-1.19.2-0.2.0.jar              |AlmostUnified                 |almostunified                 |1.19.2-0.2.0        
		entityculling-forge-1.5.2-mc1.19.1.jar            |EntityCulling                 |entityculling                 |1.5.1               
		FastFurnace-1.19.2-7.0.0.jar                      |FastFurnace                   |fastfurnace                   |7.0.0               
		portabletanks-1.1.6-forge-mc1.19.jar              |Portable Tanks                |portabletanks                 |1.1.6               
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        
		Vampirism-1.19.2-1.9.0-alpha+20221003-1811.jar    |Vampirism                     |vampirism                     |1.9.0-alpha+20221003
		VampirismIntegrations-1.19.2-1.7.0-alpha+20220918-|Vampirism Integrations        |vampirism_integrations        |1.7.0-alpha+20220918
		Werewolves-1.19.2-1.1.0.0-alpha+20221010-1906.jar |Werewolves                    |werewolves                    |1.1.0.0-alpha+202210
		PuzzlesLib-v4.3.11-1.19.2-Forge.jar               |Puzzles Lib                   |puzzleslib                    |4.3.11              
		Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13.jar |Oh The Biomes You'll Go       |byg                           |2.0.0.13            
		macawsroofsbyg-1.19.2-1.0.jar                     |Macaw's Roofs - BYG           |macawsroofsbyg                |1.19.2-1.0          
		Aquaculture-1.19.2-2.4.7.jar                      |Aquaculture 2                 |aquaculture                   |1.19.2-2.4.7        
		extremesoundmuffler-3.33_forge-1.19.x.jar         |Extreme Sound Muffler         |extremesoundmuffler           |3.33_forge-1.19.2   
		rsrequestify-2.3.0.jar                            |RSRequestify                  |rsrequestify                  |2.3.0               
		hexerei-0.2.5.jar                                 |Hexerei                       |hexerei                       |0.2.5               
		YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar       |YUNG's Better Witch Huts      |betterwitchhuts               |1.19.2-Forge-2.1.0  
		AdvancedPeripherals-0.7.21b.jar                   |Advanced Peripherals          |advancedperipherals           |0.7.21b             
		YungsBetterOceanMonuments-1.19.2-Forge-2.1.0.jar  |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.19.2-Forge-2.1.0  
		sophisticatedcore-1.19.2-0.5.13.134.jar           |Sophisticated Core            |sophisticatedcore             |1.19.2-0.5.13.134   
		glassential-forge-1.19-1.2.4.jar                  |Glassential                   |glassential                   |1.19-1.2.4          
		mcwfurnituresbop-1.19.2-1.0.jar                   |Macaw's Furnitures - BOP      |mcwfurnituresbop              |1.19.2-1.0          
		darkness-forge-mc119-2.0.98.jar                   |True Darkness                 |darkness                      |2.0.98              
		XaerosWorldMap_1.28.1_Forge_1.19.1.jar            |Xaero's World Map             |xaeroworldmap                 |1.28.1              
		cookingforblockheads-forge-1.19.2-13.2.3.jar      |CookingForBlockheads          |cookingforblockheads          |13.2.3              
		Controlling-forge-1.19.2-10.0+6.jar               |Controlling                   |controlling                   |10.0+6              
		Placebo-1.19.2-7.0.0.jar                          |Placebo                       |placebo                       |7.0.0               
		citadel-1.13.3-1.19.jar                           |Citadel                       |citadel                       |1.13.3              
		alexsmobs-1.20.2.jar                              |Alex's Mobs                   |alexsmobs                     |1.20.2              
		Bookshelf-Forge-1.19.2-16.1.9.jar                 |Bookshelf                     |bookshelf                     |16.1.9             
		sophisticatedbackpacks-1.19.2-3.18.29.719.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.19.2-3.18.29.719  
		buildinggadgets-3.16.1-build.15+mc1.19.2.jar      |Building Gadgets              |buildinggadgets               |3.16.1-build.15+mc1.
		mcw-doors-1.0.7-mc1.19.2.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.7               
		MekanismGenerators-1.19.2-10.3.4.471.jar          |Mekanism: Generators          |mekanismgenerators            |10.3.4              
		macawsroofsbop-1.19.2-1.2.jar                     |Macaw's Roofs - BOP           |macawsroofsbop                |1.19.2-1.2          
		dragonmounts-1.19.2-1.1.4a.jar                    |Dragon Mounts: Legacy         |dragonmounts                  |1.1.4a              
		twilightforest-1.19-4.2.1421-universal.jar        |The Twilight Forest           |twilightforest                |4.2.1421            
		mob_grinding_utils-1.19.2-0.4.46.jar              |Mob Grinding Utils            |mob_grinding_utils            |1.19.2-0.4.46       
		mcw-bridges-2.0.5-mc1.19.2forge.jar               |Macaw's Bridges               |mcwbridges                    |2.0.5               
		FarmersDelight-1.19-1.2.0.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.0          
		rebornstorage-1.19.2-5.0.0.jar                    |RebornStorage                 |rebornstorage                 |5.0.0               
		ItShallNotTick-1.0.11-build.35.jar                |It Shall Not Tick             |itshallnottick                |1.0.11-build.35     
		getittogetherdrops-1.16-1.2.jar                   |Get It Together, Drops!       |getittogetherdrops            |1.2                 
		mcw-fences-1.0.6-mc1.19.2.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.6               
		mcwfencesbop-1.19.2-1.0.jar                       |Macaw's Fences - BOP          |mcwfencesbop                  |1.19.2-1.0          
		mcwfencesbyg-1.19.2-1.0.jar                       |Macaw's Fences - BYG          |mcwfencesbyg                  |1.19.2-1.0          
		fuelgoeshere-1.19.2-0.1.0.0.jar                   |Fuel Goes Here                |fuelgoeshere                  |1.19.2-0.1.0.0      
		simplylight-1.19.2-1.4.5-build.42.jar             |Simply Light                  |simplylight                   |1.19.2-1.4.5-build.4
		modelfix-1.8.jar                                  |Model Gap Fix                 |modelfix                      |1.8                 
		SolarFluxReborn-1.19.2-19.1.3.jar                 |Solar Flux Reborn             |solarflux                     |19.1.3              
		Patchouli-1.19.2-77.jar                           |Patchouli                     |patchouli                     |1.19.2-77           
		ars_nouveau-1.19.2-3.4.3.jar                      |Ars Nouveau                   |ars_nouveau                   |3.4.3               
		collective-1.19.2-5.11.jar                        |Collective                    |collective                    |5.11                
		elevatorid-1.19-1.8.7.jar                         |Elevator Mod                  |elevatorid                    |1.19-1.8.7          
		ftb-ultimine-forge-1902.3.5-build.65.jar          |FTB Ultimine                  |ftbultimine                   |1902.3.5-build.65   
		YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.19.2-Forge-3.2.0  
		Runelic-Forge-1.19.2-14.1.3.jar                   |Runelic                       |runelic                       |14.1.3              
		MekanismTools-1.19.2-10.3.4.471.jar               |Mekanism: Tools               |mekanismtools                 |10.3.4              
		deeperdarker-1.0.0b-1.19.2.jar                    |Deeper And Darker             |deeperdarker                  |1.0.0b              
		architectury-6.2.46-forge.jar                     |Architectury                  |architectury                  |6.2.46              
		ftb-library-forge-1902.3.9-build.144.jar          |FTB Library                   |ftblibrary                    |1902.3.9-build.144  
		ftb-industrial-contraptions-1900.1.7-build.212.jar|FTB Industrial Contraptions   |ftbic                         |1900.1.7-build.212  
		myrtrees-forge-1.2.0-build.31.jar                 |Myrtrees                      |myrtrees                      |1.2.0-build.31      
		ftb-teams-forge-1902.2.9-build.61.jar             |FTB Teams                     |ftbteams                      |1902.2.9-build.61   
		cc-tweaked-1.19.2-1.100.10.jar                    |CC: Tweaked                   |computercraft                 |1.100.10            
		moreoverlays-1.21.3-mc1.19.jar                    |More Overlays Updated         |moreoverlays                  |1.21.3-mc1.19       
		create_crystal_clear-0.1e-1.19.2.jar              |Create: Crystal Clear         |create_crystal_clear          |0.1e                
		trashcans-1.0.15b-forge-mc1.19.jar                |Trash Cans                    |trashcans                     |1.0.15b             
		bwncr-forge-1.19.2-3.14.0.jar                     |Bad Wither No Cookie Reloaded |bwncr                         |3.14.0              
		polylib-forge-1900.0.2-build.27.jar               |PolyLib                       |polylib                       |1900.0.2-build.27   
		letmedespawn-1.18.x-1.19.x-forge-1.0.3.jar        |Let Me Despawn                |letmedespawn                  |0.0NONE             
		BetterAdvancements-1.19.2-0.2.2.142.jar           |Better Advancements           |betteradvancements            |0.2.2.142           
		MoreMekanismProcessing-1.19.2-3.0.jar             |More Mekanism Processing      |moremekanismprocessing        |3.0                 
		inventorysorter-1.19.2-21.0.4.jar                 |Simple Inventory Sorter       |inventorysorter               |21.0.4              
		rhino-forge-1902.2.1-build.242.jar                |Rhino                         |rhino                         |1902.2.1-build.242  
		kubejs-forge-1902.6.0-build.98.jar                |KubeJS                        |kubejs                        |1902.6.0-build.98   
		biggerreactors-1.19.2-0.6.0-beta.5.1.jar          |Bigger Reactors               |biggerreactors                |0.6.0-beta.5.1      
		RootsClassic-1.19.2-1.1.31.jar                    |Roots Classic                 |rootsclassic                  |1.19.2-1.1.31       
		Delightful-1.19-3.1.1.jar                         |Delightful                    |delightful                    |3.1.1               
		Cucumber-1.19.2-6.0.2.jar                         |Cucumber Library              |cucumber                      |6.0.2               
		betteranimalmodels-1.19-5.6.0-forge.jar           |Cyber's Better Animal Models  |betteranimalmodels            |1.19-5.6.0          
		AE2WTLib-12.8.4-beta.jar                          |AE2WTLib                      |ae2wtlib                      |12.8.4-beta         
		additionallanterns-1.0.1a-forge-mc1.19.jar        |Additional Lanterns           |additionallanterns            |1.0.1a              
		platforms-1.19-1.10.0.jar                         |Platforms                     |platforms                     |1.10.0              
		Tiny-Coal-Forge-1.19.2-1.0.1.jar                  |Tiny Coal                     |tinycoal                      |1.0.1               
		create-1.19.2-0.5.0.f.jar                         |Create                        |create                        |0.5.0.f             
		createdeco-1.2.11-1.19.2.jar                      |Create Deco                   |createdeco                    |1.2.11-1.19.2       
		createplus-1.19.2_v0.5.2a.jar                     |Create Plus                   |createplus                    |1.19.2_v0.5.2a      
		ars_creo-1.19.2-3.0.0.jar                         |Ars Creo                      |ars_creo                      |3.0.0               
		waystones-forge-1.19-11.1.0.jar                   |Waystones                     |waystones                     |11.1.0              
		Structory-1.19-v1.3.jar                           |Structory                     |structory                     |1.0.1               
		mcw-paintings-1.0.4-mc1.19.2.jar                  |Macaw's Paintings             |mcwpaintings                  |1.0.4               
		FastSuite-1.19.2-4.0.0.jar                        |Fast Suite                    |fastsuite                     |4.0.0               
		Clumps-forge-1.19.2-9.0.0+11.jar                  |Clumps                        |clumps                        |9.0.0+11            
		comforts-forge-6.0.2+1.19.2.jar                   |Comforts                      |comforts                      |6.0.2+1.19.2        
		configured-2.0.1-1.19.2.jar                       |Configured                    |configured                    |2.0.1               
		DimStorage-1.19.2-7.2.0.jar                       |DimStorage                    |dimstorage                    |7.2.0               
		betteranimalsplus-1.19-11.0.7-forge.jar           |Better Animals Plus           |betteranimalsplus             |1.19-11.0.7         
		ftbbackups2-forge-1.19.2-1.0.14.jar               |FTB Backups 2                 |ftbbackups2                   |1.0.14              
		mcjtylib-1.19-7.0.3.jar                           |McJtyLib                      |mcjtylib                      |1.19-7.0.3          
		rftoolsbase-1.19.1-4.0.3.jar                      |RFToolsBase                   |rftoolsbase                   |1.19.1-4.0.3        
		rftoolspower-1.19-5.0.1.jar                       |RFToolsPower                  |rftoolspower                  |1.19-5.0.1          
		rftoolsbuilder-1.19.1-5.0.4.jar                   |RFToolsBuilder                |rftoolsbuilder                |1.19.1-5.0.4        
		deepresonance-1.19-4.0.4.jar                      |DeepResonance                 |deepresonance                 |1.19-4.0.4          
		rftoolsstorage-1.19-4.0.2.jar                     |RFToolsStorage                |rftoolsstorage                |1.19-4.0.2          
		rftoolscontrol-1.19-6.0.1.jar                     |RFToolsControl                |rftoolscontrol                |1.19-6.0.1          
		YungsBetterDesertTemples-1.19.2-Forge-2.2.1.jar   |YUNG's Better Desert Temples  |betterdeserttemples           |1.19.2-Forge-2.2.1  
		ToastControl-1.19.2-7.0.0.jar                     |Toast Control                 |toastcontrol                  |7.0.0               
		blueprint-1.19.2-6.1.0.jar                        |Blueprint                     |blueprint                     |6.1.0               
		woodworks-1.19.2-2.1.0.jar                        |Woodworks                     |woodworks                     |2.1.0               
		Compat-O-Plenty-1.19.2-1.6.0.jar                  |Compat O' Plenty              |compatoplenty                 |1.19.2-1.6.0        
		berry_good-1.19.2-6.0.1.jar                       |Berry Good                    |berry_good                    |6.0.1               
		mininggadgets-1.13.0.jar                          |Mining Gadgets                |mininggadgets                 |1.13.0              
		EnderStorage-1.19.2-2.10.1.181-universal.jar      |EnderStorage                  |enderstorage                  |2.10.1.181          |
		ftb-chunks-forge-1902.3.9-build.168.jar           |FTB Chunks                    |ftbchunks                     |1902.3.9-build.168  
		friendsandfoes-forge-mc1.19.2-1.5.11.jar          |Friends&Foes                  |friendsandfoes                |1.5.11              
		chococraft-1.19.2-0.5.2.jar                       |Chococraft 4                  |chococraft                    |0.5.2               
		rftoolsutility-1.19-5.0.2.jar                     |RFToolsUtility                |rftoolsutility                |1.19-5.0.2          
		moonlight-1.19.2-2.1.1.jar                        |Moonlight Library             |moonlight                     |1.19.2-2.1.1        
		PlayerPlates-1.0.7-build.17+mc1.19.2.jar          |Player Plates                 |playerplates                  |1.0.7-build.17+mc1.1
		titanium-1.19.2-3.7.0-23.jar                      |Titanium                      |titanium                      |3.7.0               
		EnigmaticGraves-1.19.2-1.7.4.jar                  |Enigmatic Graves              |enigmaticgraves               |1.19.2-1.7.4        
		silent-lib-1.19.2-7.0.3.jar                       |Silent Lib                    |silentlib                     |7.0.3               
		additionaladditions-5.1.0.jar                     |Additional Additions          |additionaladditions           |5.1.0               
		another_furniture-forge-2.1.2-1.19.2.jar          |Another Furniture             |another_furniture             |2.1.2-1.19.2        
		Quark-3.3-371.jar                                 |Quark                         |quark                         |3.3-371             
		create-stuff-additions1.19.2_v2.0.1c.jar          |Create Stuff & Additions      |create_sa                     |2.0.1               
		PigPen-Forge-1.19.2-11.1.2.jar                    |PigPen                        |pigpen                        |11.1.2              
		FastWorkbench-1.19.2-7.0.1.jar                    |Fast Workbench                |fastbench                     |7.0.1               
		IKnowWhatImDoing-5.1.1-forge.jar                  |I Know What I'm Doing         |iknowwhatimdoing              |5.1.1               
		upgradedcore-1.19.2-4.1.0.0-release.jar           |Upgraded Core                 |upgradedcore                  |1.19.2-4.1.0.0-relea
		quartz-1.19.2-0.1.0-beta.jar                      |Quartz                        |quartz                        |0.1.0-beta          
		engineersdecor-1.19.2-forge-1.3.26.jar            |Engineer's Decor              |engineersdecor                |1.3.26              
		SoL-Carrot-1.19.2-1.14.0.jar                      |Spice of Life: Carrot Edition |solcarrot                     |1.19.2-1.14.0       
		functionalstorage-1.19.2-1.0.6.jar                |Functional Storage            |functionalstorage             |1.19.2-1.0.6        
		apexcore-1.19.2-7.3.0.jar                         |ApexCore                      |apexcore                      |7.3.0               
		fantasyfurniture-1.19.2-6.5.0.jar                 |Fantasy's Furniture           |fantasyfurniture              |6.5.0               
		BetterF3-4.0.0-Forge-1.19.2.jar                   |BetterF3                      |betterf3                      |4.0.0               
		refinedstorageaddons-0.9.0.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.9.0               
		bushierflowers-0.0.2-1.19.2.jar                   |Bushier Flowers               |bushierflowers                |0.0.2-1.19.2        
		Applied-Mekanistics-1.3.2.jar                     |Applied Mekanistics           |appmek                        |1.3.2               
		AEAdditions-1.19.2-4.0.2.jar                      |AE Additions                  |ae2additions                  |4.0.2               
		megacells-forge-1.5.2-1.19.2.jar                  |MEGA Cells                    |megacells                     |1.5.2-1.19.2        
		flickerfix-1.19.1-3.1.0.jar                       |FlickerFix                    |flickerfix                    |3.1.0               

### The latest.log file

https://gist.github.com/vrork/2d3e7d55d95450f886059f158c42cdd8

**Comment by jaredlll08** [comment]
Duplicate:
https://github.com/mekanism/Mekanism/issues/7638
https://github.com/CraftTweaker/CraftTweaker/issues/1570
https://github.com/CraftTweaker/CraftTweaker/issues/1569
