### ISSUE TITLE
1.19.2 fabric TranslatableComponent API PLZ!

### ISSUE THREAD

**Issue by PIPILAN** [CraftTweaker/CraftTweaker#1584]
### Describe the feature you'd like

crafttweaker.api.text.TranslatableComponent !

### Describe alternatives you've considered

none

### Additional context

none

### Minecraft version

1.19

### Modloader

Fabric

**Comment by jaredlll08** [comment]
Not quite sure what you're asking for, if you're asking how to make a translatable component now, this is how:
```
Component.translatable("key", ["args"]);
```
https://docs.blamejared.com/1.19/en/vanilla/api/text/Component#translatable

**Comment by PIPILAN** [comment]
This is not what I want.I'd like a local key.Just like `xxx.xxxxxxxx.tooltip`, so that I can create my own language resource pack to do multi-language adaptation.
