### ISSUE TITLE
[1.12.2] Recipes not loading on client side

### ISSUE THREAD

**Issue by nerdman0** [CraftTweaker/CraftTweaker#1588]
### Issue description

The recipes on the serverside load and work, but the client side do not, despite the log saying that they loaded.
Additionally, the recipes did load yesterday, but do not today despite no changes being made.

### Script used

https://pastebin.com/3SPuKCn4

### The crafttweaker.log file

https://pastebin.com/V1qSF8MG

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

14.23.5.2860

### CraftTweaker version

4.1.20.681

### Other relevant information

All mods are on the modpack [Warpack](https://www.curseforge.com/minecraft/modpacks/warpack-but-better) As previously stated, the scripts work on the server but not on the client

### The latest.log file

https://gist.github.com/IPlayMinecraftYT/f8f5d004d8a4793932ddd860f694190f

**Comment by jaredlll08** [comment]
Just for confirm, the client has the exact same scripts as the server?

When loading single player do the scripts load and work fine?

**Comment by nerdman0** [comment]
The client has the exact same scripts as the server (I imported them directly from the client files) the scripts do not work in singleplayer either

**Comment by jaredlll08** [comment]
is that log from joining single player or joining a server?

Have you tried crafting the item instead of looking at it in JEI?

Looking at your log file, open computers is causing a few issues with JEI, try remove open computers and see if it works?

**Comment by nerdman0** [comment]
The log is from opening minecraft.

Crafting the item will not give you the item in singleplayer, and will give you a stack of diamonds that magically transforms into the item you are trying to craft in multiplayer.

removing opencomputers caused a lot of my mods to get disabled and did not fix the issue.

**Comment by jaredlll08** [comment]
Okay, so my guess is that it is a mod in your modpack, because no one else is reporting an issue like this.

Try reproduce with just CraftTweaker and see if it still happens, if it doesn't, then you need to go through all the mods in your modpack, removing them one by one and testing until the issue is fixed, it should tell you what mod is causing the issue.

I would start with these mods:
```
Yet Another Recipe Conflict Fixer (YARCF)
https://www.curseforge.com/minecraft/mc-mods/vanillafix
https://www.curseforge.com/minecraft/mc-mods/performant
https://www.curseforge.com/minecraft/mc-mods/foamfix-optimization-mod
https://www.curseforge.com/minecraft/mc-mods/fastworkbench
```

I think the best coarse of action would be to remove mods and test in single player until the issue stops occurring

**Comment by nerdman0** [comment]
Something I just noticed is that I haven't had a new log added since yesterday. So all the logs are from when crafttweaker worked.

My most recent log is from 12:00 AM and it is currently 1:39 PM

**Comment by jaredlll08** [comment]
Are you playing on the curseforge launcher?

**Comment by nerdman0** [comment]
Yes

**Comment by xmlshr** [comment]
> Okay, so my guess is that it is a mod in your modpack, because no one else is reporting an issue like this.

I have the same problem. Yesterday everything was fine with the game, and tonight the recipes for some mods stopped working. At least crafting for sky_orchards mod doesn't work like it did yesterday.

**Comment by jaredlll08** [comment]
There are reports that the launcher is currently giving issues, you can try repair the instance and that may help
![image](https://user-images.githubusercontent.com/5553605/200421271-11ab3c8e-f58c-432c-9a90-3b6573eb4002.png)

**Comment by nerdman0** [comment]
YESS IT WORKS

**Comment by nerdman0** [comment]
ok, interesting revelation, I have to repair my profile every time I want crafttweaker to work

**Comment by fronczek7f** [comment]
Ok, but it won't work on me. It stop working after I update MC launcher and before that all working normaly, after update launcher today, all zs scripts stop working, ct.log stop logging in my external instance and only update in .minecraft on a System partition

**Comment by nerdman0** [comment]
im not sure how to fix that then

**Comment by jaredlll08** [comment]
Either move to a different launcher, or wait for curseforge to issue a fix, regardless there is absolutely nothing I can do on my side to fix this.
