### ISSUE TITLE
Scripts folder path change

### ISSUE THREAD

**Issue by IC-Dyllac** [CraftTweaker/CraftTweaker#1589]
### Issue description

After a launcher update, the "scripts" folder path changed from the set game directory (installation) to the default .minecraft directory. Even though the mod is located in the "installation" directory.

### Script used

None

### The crafttweaker.log file

https://gist.github.com/IC-Dyllac/2090dcf32a46681a6b5695494a31b119

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

1.12.2 - 14.23.5.2860

### CraftTweaker version

1.12 - 4.1.20.681

### Other relevant information

Minecraft "Official" Launcher version: 2.3.481-1.1.28

This is most likely a minecraft launcer "issue".  Since it appeared right after the launcher updated.

Nothing on the logs looks out of the ordinary

I'm almost sure this isn't a CT issue, since other than the scripts/logs now defaulting to the appdata .minecraft folder everything works as intended. If this is the case, let me know and I'll close the issue

### The latest.log file

https://gist.github.com/IC-Dyllac/9f554bb05108e8ef8bcbd846db9318e7

**Comment by IC-Dyllac** [comment]
Probably a duplicate of #1588 or is somehow related to it?
In either case, I'll be more than willing to close this since it doesn't seem to be related to CT mod.

**Comment by fronczek7f** [comment]
Solution from me, before this will be fixed the best way is make shortcut in our instance other then .minecraft and put all zs scripts into .minecraft/scripts folder and make <our_external_instance>/<shortuct_scripts_folder>

**Comment by AechtRob** [comment]
If anyone has any clever workarounds that work it would be lovely to know. Using the .minecraft folder for scripts means that the scripts will be used by all installations we try to run, which will break the modpacks.

**Comment by ChiefArug** [comment]
You should be able to use the `-Duser.dir="C:\Path\To proper instance\directory"` java argument to redirect minecraft back to the correct folder.

**Comment by AechtRob** [comment]
Nice idea, though it doesn't work sadly, and the folders (scripts and crafttweaker.log) remain pointed wrongly. I have noticed the game is also putting the logs into the wrong folder location as well.

**Comment by ChiefArug** [comment]
The launcher update that broke this has been rolled back. Everything should be back to how it was before.

**Comment by IC-Dyllac** [comment]
I can confirm what ChiefArug said. The issue is no longer there. At least not with the official launcher rollback from 2.3.481-1.1.28 to 2.3.462 - 1.1.28.

With that, I'll close the issue. Thank you all for your comments and advice.
