### ISSUE TITLE
Changing Loottables like Loottweaker | Being able to make Enchantments Treasure

### ISSUE THREAD

**Issue by notIkibo** [CraftTweaker/CraftTweaker#1594]
### Describe the feature you'd like

As stated in the title.

Being able to do something like this:
mods.ltt.LootTable.removeGlobalItem("minecraft:saddle");

And some enchantments from mods are fairly strong and I don't want my friends to get strong so easily >:(
But devs don't make it easily configurable. I don't want them to be able to get them for 6 levels on the enchanting table. If they find it, that's alright.

### Describe alternatives you've considered

doing nothing

### Additional context

I am trying to build a modpack for my friends on Aternos so they play though I gave it a lot of work, made saddles, horse armor and name tags craftable so I don't need/want them in any chests. 
I made tweak datapacks so betterend infusion pedestal makes other enchantment books from mods. I try to convince devs to make things configurable so I can do my own balancing which is way better bc apparently either it's (secret) op, non functional or too weak.

Anyway, I probably need some advice on Crafttweaker too. I've never done anything like this though I learn in an okay speed

### Minecraft version

1.19

### Modloader

Fabric

**Comment by jaredlll08** [comment]
For loot look at `/ct examples`, it has an example of adding an item to all loot drops (which can easily be changed to remove an item from all loot drops).

As for enchanting, you cannot edit enchants with CraftTweaker, so you won't be able to block those enchantments from the table.

As for getting advice for CraftTweaker, you should checkout the discord server, https://discord.blamejared.com
