### ISSUE TITLE
[1.18] Method to create empty ListData

### ISSUE THREAD

**Issue by vertexcubed** [CraftTweaker/CraftTweaker#1596]
### Describe the feature you'd like

Simple method to create an empty ListData, as the default constructor for it is broken.

Example implementation in ZC:
```ZenScript
public expand ListData {
    public static create() as ListData => {
        val data = [""] as ListData;
        data.clear();
        return data;
    }
```

### Describe alternatives you've considered

Alternative is to tell people to manually implement something along the lines of this every time someone asks, or backport the fix which could be a breaking change

### Minecraft version

1.18

### Modloader

Forge

**Comment by kindlich** [comment]
> as the default constructor for it is broken.

What exactly about the ctor is broken?

In any case, there are 2 ctors exposed to ZC.
Which of these does not work and what is the error you get?
```zs
val listData1 = new ListData();
val listData2 = new ListData([]);
```

**Comment by vertexcubed** [comment]
The first ctor with no parameters doesn't seem to work, refer to [this discord thread](https://discord.com/channels/136877912698650625/929770828286029914/1046109874255314956) for more context. I'm not sure what the exact bug/issue is but Jared should know

**Comment by jaredlll08** [comment]
Closed by https://github.com/CraftTweaker/CraftTweaker/commit/68e4d5f4b2ec4856ad1699d3b6fe3d82957fb3ff
