### ISSUE TITLE
[1.16.5] Need Industrial Foregoing support

### ISSUE THREAD

**Issue by Mineablechn** [CraftTweaker/CraftTweaker#1599]
### Describe the feature you'd like

Could you please add ZenScript for Industrial Foregoing, to add and remove recipes from Crusher, Dissolution Chamber, Fluid Extractor and Stonework Generate? Thanks a lot.

### Minecraft version

1.16

### Modloader

Forge

**Comment by jaredlll08** [comment]
https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing-tweaker
