### ISSUE TITLE
[1.16.5] Non-OPs can use Examples Command

### ISSUE THREAD

**Issue by VanyaBaou** [CraftTweaker/CraftTweaker#1600]
### Issue description

You can use /ct examples, without op, on a server
And it generates example files

### Steps to reproduce

New instance with just CraftTweaker (latest at time, CraftTweaker-1.16.5-7.1.2.515)
Start server with just CraftTweaker
Dont have op/cheats
Use /ct examples
Reload
Example scripts are loaded

### Script used

None

### The crafttweaker.log file

https://pastebin.com/rJAEAbSx

### Minecraft version

1.16

### Modloader

Forge

### Modloader version

1.16.5-forge-36.2.33

### CraftTweaker version

CraftTweaker-1.16.5-7.1.2.515

### The latest.log file

https://pastebin.com/khMMXwEP

**Comment by jaredlll08** [comment]
Fixed by https://github.com/CraftTweaker/CraftTweaker/commit/8bfe038dbcf4ffe20f38c6e016813bb5b5ac872d
