### ISSUE TITLE
[1.18_Forge]I hope to add the event of ice melting

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#1603]
### Describe the feature you'd like

It seems that there is no event that can respond to ice melting in the current version, so I hope to add an event triggered when the ice melts.

### Minecraft version

1.18

### Modloader

Forge

**Comment by jaredlll08** [comment]
Forge doesn't have any event for ice melting, so unfortunately there is nothing for us to expose to scripts.
