### ISSUE TITLE
[1.18_Forge]I hope to add hidden recipes as in previous versions

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#1604]
### Describe the feature you'd like

In version 1.12, I can use addHiddenShapeless or addHiddenShaped to add hidden recipes. There is no such function in 1.18, so I want to add similar functions. If there are other ways to achieve this in 1.18, please let me know.

### Minecraft version

1.18

### Modloader

Forge

**Comment by jaredlll08** [comment]
You can add a recipe and then use 
https://docs.blamejared.com/1.18/en/mods/JEITweaker/API/JEI#hideRecipe
to hide it.
