### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by blockgoblin31** [CraftTweaker/CraftTweaker#1605]
### Issue description

Jared told me to open an issue after I asked about this on discord.
After a reload, `[ERROR] Duplicate key WrapperRecipe{recipe=crafttweaker:signalum}: Duplicate key WrapperRecipe{recipe=crafttweaker:signalum}`
shows in chat.
I'm linking tags.zs because it's mentioned in the stacktrace in crafttweaker.log, it's unchanged since before and after the error started popping up.

### Script used

https://gist.github.com/tuc56/44561102025b56e31a3badef80d2a38a

### The crafttweaker.log file

https://gist.github.com/tuc56/738edabf453d916584447028f9254651

### Minecraft version

1.16

### Modloader

Forge

### Modloader version

36.2.34

### CraftTweaker version

7.1.2.516

### Other relevant information

I have a bunch of other mods, I think this html is still correct
https://github.com/tuc56/processing-pack/blob/main/modlist.html

### The latest.log file

https://gist.github.com/tuc56/12018a977f31c88b553a4e5e62ac3deb

**Comment by jaredlll08** [comment]
Do you mean a recipe called `signalum` anywhere?

Can you reliably reproduce this issue?

**Comment by blockgoblin31** [comment]
yes, I do have a recipe called signalum, and yes, it happens every reload

**Comment by jaredlll08** [comment]
Can you upload your scripts as a zip file please

**Comment by blockgoblin31** [comment]
just checked my literal last other file, it also has a recipe called signalum, im guessing thats the problem

**Comment by blockgoblin31** [comment]
one was from 2 and a half months ago, one was from last week
