### ISSUE TITLE
[1.18.2] Custom Player Heads don't have respective skin in JEI until /reload is run

### ISSUE THREAD

**Issue by ChaosDogG** [CraftTweaker/CraftTweaker#1610]
### Issue description

When I give a recipe containing a specific user's player head, it won't render the skin in the JEI menu until /reload is run, which is quite annoying

### Steps to reproduce

1. Create recipe using custom player head
2. Open JEI
3. Look for custom recipe
4. Behold, a skin-less player head when there should be a skin

### Script used

https://gist.github.com/ChaosDogG/2a52032337b7133158d8aa3dee564e2c

### The crafttweaker.log file

https://gist.github.com/ChaosDogG/d6c75da09bd0110be1f44b233ea4dbb0

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.2.0

### CraftTweaker version

9.1.198

### Other relevant information

Recipes shown are made with CreateTweaker and work as intended without reloading, but with the lack of the proper skins, users may have trouble telling which head drops what

### The latest.log file

https://gist.github.com/ChaosDogG/f432407b6c39df41ac81276cd19975f1

**Comment by jaredlll08** [comment]
I want to say that this is an issue with JEI, can you try and add a datapack recipe that outputs a player head and see if that shows up?

**Comment by ChaosDogG** [comment]
I cannot because I'm specifically calling for a specific user's head and
datapacks cannot do that w recipes

**Comment by jaredlll08** [comment]
This is an issue with JEI.

Forge adds a nbt ingredient that lets you use nbt in datapacks, so you can use:
```json
{
  "type": "minecraft:crafting_shaped",
  "key": {
    "#": {
      "type": "forge:nbt",
      "item": "minecraft:player_head",
      "nbt": {
        "SkullOwner": "YelloWool"
      }
    }
  },
  "pattern": [
    "# #",
    "###"
  ],
  "result": {
    "item": "minecraft:apple"
  }
}
```
which gives:
![image](https://user-images.githubusercontent.com/5553605/216135474-567d8112-fa23-4011-99d0-7ab2295395c7.png)
after reloading:
![image](https://user-images.githubusercontent.com/5553605/216135561-393c5344-e363-4d14-8ca8-567d2ff84d59.png)
