### ISSUE TITLE
1.16.5 Modded Server Crashing

### ISSUE THREAD

**Issue by RockeyWereWolf** [CraftTweaker/CraftTweaker#1614]
### Issue description

I am not sure that issue is caused by CraftTweaker, so my apologizes if there is no problem with CraftTweaker. Only thing that i could to figure out from latest.log is that the last mod loaded there was CraftTweaker and a lot of warnings before process ended, so if you want you can firstly read this log from the end. 
I also reported this on forge forums, but as i understand 1.16.5 is not supported there anymore. Whatever they have not answered me yet.

### Script used

i am not sure what you mean by this

### The crafttweaker.log file

https://pastebin.com/aJvEqQvH

### Minecraft version

1.16

### Modloader

Forge

### Modloader version

 36.2.39 

### CraftTweaker version

Error ocurred both on 1.16.5-7.1.2.516 and 7.1.2.515,  i tried to update from 515 to 516 to fix issue

### Other relevant information

here i will provide a screenshot of other mods used here. Hope that there are all mods 
![image](https://user-images.githubusercontent.com/55295920/215869130-1b7939c7-b797-4895-a792-cb1015e8926a.png)

### The latest.log file

https://pastebin.com/1UUZ6hRc

**Comment by jaredlll08** [comment]
please upload your crafttweaker jar file here

**Comment by RockeyWereWolf** [comment]
> please upload your crafttweaker jar file here

I hope you can download it from here. https://1drv.ms/u/s!Au7HZGNR20GJoTtmXrx2CF4X1rSA?e=hsaWar

**Comment by jaredlll08** [comment]
Can you try and run the game using Java 8 instead of Java 11 and see if the issue still persists

**Comment by RockeyWereWolf** [comment]
> Can you try and run the game using Java 8 instead of Java 11 and see if the issue still persists

Thank you, issue is solved!

**Comment by RockeyWereWolf** [comment]
So, i think i can close this issue.

**Comment by RockeyWereWolf** [comment]
> Can you try and run the game using Java 8 instead of Java 11 and see if the issue still persists

Can you tell what mod caused this issue? Java 8 performance is not so good, I would like delete it and upgrade to newer java again.

**Comment by jaredlll08** [comment]
No idea what mod specifically, as far as I was aware, Forge only supports Java 8 on 1.16.5, so it would be Forge itself, try just using Forge on Java 11, and slowly add mods until it stops working.
