### ISSUE TITLE
Better villager trading system

### ISSUE THREAD

**Issue by blockgoblin31** [CraftTweaker/CraftTweaker#1621]
### Describe the feature you'd like

I would like the ability to replicate vanilla style villager trades(specifically the random price and enchants) on 1.16. My specific use case is that having access to diamond items from villages is progression breaking and lore breaking in my modpack, so I'd like to replace those trades with equivalent ones that give steel items.

### Describe alternatives you've considered

For my use case, being able to use a replacer would also work

### Minecraft version

1.16

### Modloader

Forge

**Comment by jaredlll08** [comment]
Did you see the latest release?
https://github.com/CraftTweaker/CraftTweaker/commit/3c3aecbfe904cffeec8d390603049464e80fb0f9

I believe you can do what you want using that?

**Comment by blockgoblin31** [comment]
yes, I can... thats what I get for not checking patch notes
