### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by dDanber** [CraftTweaker/CraftTweaker#1625]
### Issue description

Can't join my local server with mod installed. *Everyrhing works without mod*
![scr](https://user-images.githubusercontent.com/127247219/223534238-1cc760b1-2636-453b-acaa-8223dc935330.PNG)

### Script used

none

### The crafttweaker.log file

none

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.2.1

### CraftTweaker version

9.1.205

### The latest.log file

none

**Comment by jaredlll08** [comment]
Provide the latest.log file from both the client and the server please.

**Comment by dDanber** [comment]
*From latest-client looks like some problems with Mekanism mod*
(latest-server -- oginal log file, debug-server -- DeLogger mod log file)

[latest-server.log](https://github.com/CraftTweaker/CraftTweaker/files/10915477/latest-server.log)
[latest-client.txt](https://github.com/CraftTweaker/CraftTweaker/files/10915478/latest-client.txt)
[crafttweaker-server.log](https://github.com/CraftTweaker/CraftTweaker/files/10915480/crafttweaker-server.log)
[debug-server.log](https://github.com/CraftTweaker/CraftTweaker/files/10915481/debug-server.log)

GL btw. @jaredlll08

**Comment by jaredlll08** [comment]
Are ***ALL*** the scripts on both the client and the server?

From the looks of it, the script file `examples\mekanism_custom_chemicals.zs` is loading on the server (you didn't give the client crafttweaker.log file, so I can't check there), which adds new registry objects to the game.

**Comment by dDanber** [comment]
Yeap, thx for help! I had no example files on a client. Now everything(+-) works.
