### ISSUE TITLE
entity.type cause error

### ISSUE THREAD

**Issue by Raw-fish** [CraftTweaker/CraftTweaker#1627]
### Issue description

`var awa=entity.getType();` works
`var awa=entity.type;` cause error

### Script used

https://gist.github.com/Raw-fish/24d3cb3e5fdc53b3633ca4ad8c84dfa6

### The crafttweaker.log file

https://gist.github.com/Raw-fish/0ad031d7bc30d15dc1c119aaa46f75b6

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.1.73

### CraftTweaker version

9.1.205

### The latest.log file

https://gist.github.com/Raw-fish/2bc663cdd68464fe041feae6ca463a96

**Comment by jaredlll08** [comment]
This has been fixed in newer versions, fixing in older versions my potentially be a breaking change.
