### ISSUE TITLE
The number of items is not consumed

### ISSUE THREAD

**Issue by yuankun1** [CraftTweaker/CraftTweaker#1629]
### Issue description

Change the synthesis so that the item will not consume quantity when crafting

### Steps to reproduce

craftingTable.addShaped("coal_compression", <item:minecraft:diamond_block>, [
    [<item:minecraft:coal_block>, <item:minecraft:coal_block> * 3, <item:minecraft:coal_block>],
    [<item:minecraft:coal_block>, <item:minecraft:diamond>, <item:minecraft:coal_block>],
    [<item:minecraft:coal_block>, <item:minecraft:coal_block> * 3, <item:minecraft:coal_block>]]);

### Script used

null

### The crafttweaker.log file

null

### Minecraft version

1.16

### Modloader

All

### Modloader version

36.2.39

### CraftTweaker version

1.16.5-7.1.2.519

### Other relevant information

null

### The latest.log file

null

**Comment by jaredlll08** [comment]
All vanilla machines strictly use single item inputs, not stacked.
