### ISSUE TITLE
Edit Protection Values of Equipment / Damage Values of Weapons

### ISSUE THREAD

**Issue by ereese99** [CraftTweaker/CraftTweaker#1632]
### Describe the feature you'd like

A lot of mods already have it in configs, but a lot also don't. You'd be able to edit toughnesss, armor value, knockback resistance etc. and then for weapons attack speed, attack damage, etc.

### Describe alternatives you've considered

Only alternatives is to force every other mod dev to include it in their config

### Minecraft version

1.19

### Modloader

Fabric

**Comment by jaredlll08** [comment]
You can do it via https://docs.blamejared.com/1.19/en/vanilla/api/ingredient/IIngredient#addGlobalAttributeModifier

**Comment by ereese99** [comment]
I tried implementing it (made sure to import everything and format it corrctly), and all I get upon load and reload is "No such member: addGlobalAttributeModifier"
"Scripts are invalid!"
