### ISSUE TITLE
addGlobalAttributeModifier not working

### ISSUE THREAD

**Issue by ereese99** [CraftTweaker/CraftTweaker#1634]
### Issue description

Upon loading in I get this:
"No such member: addGlobalAttributeModifier"
"Scripts are invalid!"

### Steps to reproduce

Put a line of code into my script.zs

### Script used

<tag:items:mythicmetals:aquarium_ingots>.addGlobalAttributeModifier("845db27c-c624-495f-8c9f-6020a9a58b6b", "Armor modifier", 1, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:feet>]);

### The crafttweaker.log file

https://gist.github.com/ereese99/46f62cf146b897c098f6d297fd197a15

### Minecraft version

1.19

### Modloader

Fabric

### Modloader version

0.14.17

### CraftTweaker version

10.1.39

### The latest.log file

https://gist.github.com/ereese99/fb42b54f09540569a415625190663f3a

**Comment by jaredlll08** [comment]
Upload your script to pastebin, like the issue template asked for.

**Comment by ereese99** [comment]
https://gist.github.com/ereese99/eff810c0a5b88d843d2a9e7da553b192

**Comment by jaredlll08** [comment]
```zenscript
<tag:items:mythicmetals:aquarium_ingots>asIIngredient().addGlobalAttributeModifier("845db27c-c624-495f-8c9f-6020a9a58b6b", "Armor modifier", 1, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:feet>]);
```

You need to do it like this

**Comment by ereese99** [comment]
Will try it now!

**Comment by ereese99** [comment]
https://gist.github.com/ereese99/f5abd1c77ab62f468aa4f8f011dce5ca 

Missing semicolon somehow

**Comment by jaredlll08** [comment]
```zenscript
<tag:items:mythicmetals:aquarium_ingots>.asIIngredient().addGlobalAttributeModifier("845db27c-c624-495f-8c9f-6020a9a58b6b", "Armor modifier", 1, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:feet>]);
```
I made a typo, this one should work

**Comment by ereese99** [comment]
Working! Thanks!
