### ISSUE TITLE
[1.19.2/Forge] Ability to create Treasure Maps for loot tables/result of crafting recipes 

### ISSUE THREAD

**Issue by thelegitdolt** [CraftTweaker/CraftTweaker#1636]
### Describe the feature you'd like

By Treasure Maps, I mean maps created as a result of https://docs.blamejared.com/1.19/en/vanilla/api/villager/trade/type/TreasureMapForEmeralds 

For my modpack, I would like to place treasure maps that leads to an ancient city in various loot tables. But, as far as I've seen, there is no way to create treasure maps except using this method to put them as villager trades. I would appreciate a way to do this using crafttweaker. Thank you!.

### Describe alternatives you've considered

Buried Treasure maps in vanilla loot tables are hardcoded and will only work with buried treasures. 

### Minecraft version

1.19

### Modloader

Forge

**Comment by CogentRedTester** [comment]
Do you know how to create (or find) a ResourceLocation for a modded Structure? I have been trying to create maps to 'When Dungeons Arise' structures, but I haven't had any success.
