### ISSUE TITLE
[1.12.2] Setter for IItemStack rarity

### ISSUE THREAD

**Issue by xJon** [CraftTweaker/CraftTweaker#1639]
### Describe the feature you'd like

As the title describes, would be awesome for 1.12.2 (Forge) specifically.
Feel free to close if uninterested.

**Comment by friendlyhj** [comment]
https://beta.curseforge.com/minecraft/mc-mods/zsrarity

**Comment by xJon** [comment]
@friendlyhj 
- It does not set rarity but just changes the item color
- It does not support a lot of modded items (e.g. IC2C jetpack).

**Comment by friendlyhj** [comment]
Unfortunately, the rarity is hardcoded in `getRarity` method implememtation. There is no such a field to set. I think it is impossible unless ASM or Mixin is used.

**Comment by xJon** [comment]
Closing (due to @ACGaming)
