### ISSUE TITLE
Update for 1.19.3 PLEASE.

### ISSUE THREAD

**Issue by breeece** [CraftTweaker/CraftTweaker#1642]
### Describe the feature you'd like

I would really like this to be updated to 1.19.3 for forge so I can disable a bunch of modded item recipes. Looking everywhere and can't find anything that would work. Really really need an update. Thanks!.

### Describe alternatives you've considered

Nothing as I can't find anything.

### Minecraft version

1.19

### Modloader

Forge

**Comment by breeece** [comment]
Interested in disabling recipes from multiple mods that aren't on the supported mod list. Is it possible to disable recipes from mods that you haven't added support to ?

**Comment by GoldenFurredFox** [comment]
Don't wanna create a duplicate issue, but just want to confirm that absolutely no recipe tweaker mods exist for 1.19.3. Some jumped straight from .2 to .4 and others simply haven't passed .2, so I'm trying to gather a list of crafttweaker alternative mods so I can call their mod devs to action and see if they'll make versions for 1.19.3.

Edit: Also, not sure if this mod is available for Fabric or not, but I actually need one for Fabric. I didn't check if alternatives exist for Forge or Quilt. Whoops.

A similar post for Polymorph exists at [https://github.com/illusivesoulworks/polymorph/issues/204](url). Please go give it some love.

**Comment by jaredlll08** [comment]
The mod is being ported, and it will be ported to 1.19.3 for both Forge and Fabric.

I am currently focussing on some other projects that don't get as much love because I am spending time on this project.

I'm sorry but I don't have an ETA for this, but I will update this issue when it is released.

**Comment by breeece** [comment]
> The mod is being ported, and it will be ported to 1.19.3 for both Forge and Fabric.
> 
> I am currently focussing on some other projects that don't get as much love because I am spending time on this project.
> 
> I'm sorry but I don't have an ETA for this, but I will update this issue when it is released.

Thank you for something. I appreciate your response.

**Comment by Rogenar** [comment]
I'm waiting for version 1.19.3 too.

**Comment by Rogenar** [comment]
I'm also waiting for fabric version 1.19.3.

**Comment by jaredlll08** [comment]
The mod has been updated to 1.19.3

**Comment by breeece** [comment]
Oooooooo no way!!!!! Yess finally

**Comment by Rogenar** [comment]
and now we are waiting for it to be updated to version 1.20.1.

**Comment by jaredlll08** [comment]
Yes, porting mods take time, I'm nearly done with the 1.19.4 port, you will not have to wait long for a 1.20.1 port.
