### ISSUE TITLE
No Recipe on JEI

### ISSUE THREAD

**Issue by SikiciBebek** [CraftTweaker/CraftTweaker#1643]
### Issue description

After adding my script (which works) JEI wont show me the recipe for that anymore.
but Iam still able to craft it.
Could u help me with that pls.

Another question: Is there a way to reset all the custom recipes?

### Script used

https://pastebin.com/Q88V4P4k

### The crafttweaker.log file

https://pastebin.com/CeBY3HMn

### Minecraft version

1.16

### Modloader

Forge

### Modloader version

36.2.29

### CraftTweaker version

7.1.2.520

### Other relevant information

If u want to try it u can install the Modpack on Curseforge 
Modpack name: KOTD

### The latest.log file

https://gist.github.com/SikiciBebek/5e7656ccbc620630861cce7691efe0e2

**Comment by jaredlll08** [comment]
Is that latest.log file from a client or a server?

Regardless I would like the full latest.log file from the client please, not a snippet of it.

**Comment by SikiciBebek** [comment]
iam playing on my server 
the log is the server log

sure i can post it
https://gist.github.com/SikiciBebek/b26def2d19b869c80ddb41ce26e9c5a1    : Server
https://gist.github.com/SikiciBebek/8caf072dafd3568288c0d1fc2bb03381      : Client

**Comment by jaredlll08** [comment]
Your modpack has multiple broken recipes that are unrelated to CraftTweaker.

Do a search for `Found a broken recipe:` in your client latest.log file and you will see them.

From the looks of it, they are all from Agricraft, if you remove that mod does the original issue still happen?

**Comment by SikiciBebek** [comment]
I removed it and restartet client+server without it
it still doenst show me the recipe
but the recipe works

**Comment by jaredlll08** [comment]
can I get a new client log file please

**Comment by SikiciBebek** [comment]
Sure ^^
https://gist.github.com/SikiciBebek/7a38f9c253f05d15e1e20f9cf68c4a0c

**Comment by jaredlll08** [comment]
There are still JEI issues, from the looks of it it seems it is related to "jeienchantmentinfo" and "jeresources".

These issues can cause JEI to not update correctly.

Try remove the mods and see?
You can also look in the log yourself with a search of `at mezz.jei`, if you see that string, it most likely means that jei failed to reload something.

**Comment by SikiciBebek** [comment]
Ty ^^ it was Jeienchantmentinfo
Have a great day :D

**Comment by jaredlll08** [comment]
Going to close this then

**Comment by SikiciBebek** [comment]
Hey ^^
Yesterday it worked but now i have the same issue again.
It works in my singleplayer map but not on the server.
After removing jeienchantmentinfo and deleting the configs everything worked fine till now.
Server log:
https://gist.github.com/SikiciBebek/c03a031e5dc50fca3057a252ed590ee6

**Comment by SikiciBebek** [comment]
It kinda makes no sense but after deleting the server config file of JEI
( 
["cheat mode"]
	#Enable Cheat Mode for Operators (/op)
	enableCheatModeForOp = true
	#Enable Cheat Mode for users in Creative Mode
	enableCheatModeForCreative = true
	#Enable Cheat Mode for users who can use /give
	enableCheatModeForGive = false
)
And the jeresources + jeresources-comman config file
it works without again.
what could be the reason?

**Comment by jaredlll08** [comment]
I'm really not sure, this would be something to report to Just Enough Resources, it really has nothing to do with CraftTweaker (besides the fact that it breaks CraftTweaker).

**Comment by SikiciBebek** [comment]
kk Thank you anyways for your help ^^
