### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Copernicium282** [CraftTweaker/CraftTweaker#1647]
### Issue description

my 1.12.2 modpack crashes on startup, and by looking at the log file, I have no clue whether it is modular machinery or crafttweaker causing the crash, but the main line says that it was crafttweaker.

### Script used

this is probably the script that was causing the issue cause after this script it failed to load others https://pastebin.com/cbi37MG8

### The crafttweaker.log file

https://pastebin.com/ixVaS2aw

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

1.12.2 - 14.23.5.2859

### CraftTweaker version

CraftTweaker2-1.12-4.1.20.687

### Other relevant information

Modular Machinery version: 
modularmachinery-1.12.2-1.10.0.

### The latest.log file

https://pastebin.com/qwGdw3Vq

**Comment by jaredlll08** [comment]
I believe this should be reported to them, they shouldn't crash when trying to get the display name of their items.
