### ISSUE TITLE
Cannot remove villager trades from Thermal Cultivation

### ISSUE THREAD

**Issue by browsetheseventh** [CraftTweaker/CraftTweaker#1649]
### Issue description

I'm creating a modpack using CraftTweaker. I have both Thermal Cultivation and Farmers Delight installed, which both have tomatoes. I am trying to remove the tomato seed trade from the farmer villager, but when I check the trade with Just Enough Resources, it is still there. I tested it on a separate modpack to make sure it wasn't some odd combination of mods, and the same effect happened. I've tried multiple variations, all of which are shown in the script along with any errors found from them. The ones on that cause errors are put in comments. I am most likely doing something completely wrong with the code, so pardon me if I am a complete idiot.
In case it causes any confusion, |line number| means the to insert the line number of the code.

### Script used

https://pastebin.com/MMBYJkgL

### The crafttweaker.log file

https://pastebin.com/wsQUrYm9

### Minecraft version

1.19

### Modloader

Forge

### Modloader version

43.2.10

### CraftTweaker version

10.1.44

### Other relevant information

CoFH Core 10.2.1.40
JEI 11.6.0.1015 (optional)
JEP 2.0.2 (optional)
JER 1.2.2.200 (optional)
Thermal Cultivation 10.2.0.17
Thermal Foundation 10.2.0.47

### The latest.log file

https://pastebin.com/8pmnUMAd

**Comment by jaredlll08** [comment]
Please just provide the script files used, and the log file, with absolutely no changes made.

Are you sure you have the item names correct? looking at the source, I believe what you want is:
```zenscript
villagerTrades.removeTradesSelling(<profession:minecraft:farmer>, 2, <item:thermal:tomato>);
```
not, `tomato_seeds`

also please test by spawning in new villagers, this could also be an issue with just enough resources

**Comment by jaredlll08** [comment]
Closing due to no reply, and after confirming that:
```zenscript
villagerTrades.removeTradesSelling(<profession:minecraft:farmer>, 0, <item:thermal:tomato>);
```
does in fact remove the trade.
