### ISSUE TITLE
[1.19.2 FORGE] CraftTweaker has failed to load correctly

### ISSUE THREAD

**Issue by Limit-sest** [CraftTweaker/CraftTweaker#1650]
### Issue description

I don't have a clue what could be causing it, crashes on startup of the server

### Steps to reproduce

Install crafttweaker

### Script used

none

### The crafttweaker.log file

https://gist.github.com/Limit-sest/9b73bb8114f46326278ed777c80c2c1b

### Minecraft version

1.19

### Modloader

Forge

### Modloader version

43.2.10

### CraftTweaker version

10.1.44

### The latest.log file

https://gist.github.com/Limit-sest/44997010e0e7db996f50e9ab5398d172

**Comment by jaredlll08** [comment]
I think you are missing
https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items-hacks
from the server.

**Comment by Limit-sest** [comment]
Okay, I have now installed but the error stays the same. Any other ideas?

**Comment by jaredlll08** [comment]
Use JEI instead of REI would be the only suggestion right now until I get enough time to fix the actual issue

**Comment by Limit-sest** [comment]
Thanks

**Comment by jaredlll08** [comment]
this has been fixed in the latest version of JEITweaker
