### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by AKVindication** [CraftTweaker/CraftTweaker#1651]
### Issue description

I Am using the minecraft modpack Progress: create and need help changing the crafting recipe for the AE2 Vibration chamber, it is supposed to have a recipe but it does not, please help. (i thought crafttweaker was ment to be able to change recipes) Version: 1.19.2

### Steps to reproduce

download the minecraft modpack Progress: create from curseforge and look for the Vibrstion chamber recipe.

### Script used

https://pastebin.com/18EXHaiE

### The crafttweaker.log file

https://pastebin.com/18EXHaiE

### Minecraft version

Other

### Modloader

Fabric

### Modloader version

0.14.12

### CraftTweaker version

10.1.36

### Other relevant information

AE2 Version: 12.9.5

### The latest.log file

https://pastebin.com/18EXHaiE

**Comment by jaredlll08** [comment]
You have provided basically no information (not even the minecraft version)

For starters, I'm not downloading a modpack to debug an issue.
Secondly you haven't provided any script file or latest.log file, and the crafttweaker.log file that you provided 3 times is missing information.
and lastly, based on your issue and the fact that you aren't listed as the modpack developer on curseforge, I don't think you made the modpack. 

The first line of the issue template is:

> If this bug occurs in a modpack, please report this to the modpack author.

The modpack author most likely removed the recipe intentionally, judging by line 434 of the crafttwaeker.log file:
> ```[14:29:58.064][INFO]: Removing "minecraft:crafting" recipe with names that match the regex: "ae2:network.*energy_vibration_chamber"```

**Comment by AKVindication** [comment]
I am sorry, but most of the things in the fill areas did not make sense, I apologize for the inconvenience. (And no, the vibration chamber was ment to have a recipe, the quest by the mod developer said to use it).
________________________________

**Comment by jaredlll08** [comment]
Then that is a bug with the modpack, as the log shows, they are specifically removing the vibration chamber:
```
[14:29:58.064][INFO]: Removing "minecraft:crafting" recipe with names that match the regex: "ae2:network.*energy_vibration_chamber"
```
So make an issue with the modpack author
