### ISSUE TITLE
Crash with Nomifactory NuclearCraft.

### ISSUE THREAD

**Issue by GavinFF-SS** [CraftTweaker/CraftTweaker#1653]
### Issue description

When loading CraftTweaker it crashes because net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CraftTweaker2 (crafttweaker)
Caused by: java.lang.NoClassDefFoundError: nc/recipe/BasicRecipeHandler. This is fixed in NC:O but the patch is not available for NC:O so I cant use it.

### Steps to reproduce

Load minecraft with NC(Nomifactory Patch).
Wait till step 2.
Not Profits...

### Script used

No scripts. This is just normal Minecraft.

### The crafttweaker.log file

Doesn't reach that point.

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

14.23.5.2860

### CraftTweaker version

1.12-4.1.20.687

### Other relevant information

I don't think there is any other information to be had.

### The latest.log file

https://gist.github.com/gavinops/0245f50964cdd06cbb7c4afbababec1e

**Comment by GavinFF-SS** [comment]
Quantum Nuclear Physics might be why. I'll close this issue if removing it works.

**Comment by jaredlll08** [comment]
This is not an issue with CraftTweaker, one of the mods that adds crafttweaker support is referencing a class that does not exist, unfortunately there isn't an easy way to debug this, you will have to remove mods to figure out which one causes the crash.
