### ISSUE TITLE
Tool References Not Working (addAllWithOreDropsBonus())

### ISSUE THREAD

**Issue by Khofonyx** [CraftTweaker/CraftTweaker#1654]
### Issue description

When trying to use a loot modifier to change the drops/drop rates of a block with fortune, It's as if the tool doesn't get referenced or accounted for. Was told to report it as a bug on the discord, as everything that references tools is broken ATM.

more specifically, I was trying to do this, the syntax is correct according to the 1.18 wiki:

<block:contenttweaker:scrap_ore>.addLootModifier("addscrapdrops",CommonLootModifiers.addAllWithOreDropsBonus(<enchantment:minecraft:fortune>,<item:contenttweaker:scrap>));

### Script used

https://pastebin.com/VXTahpFA

### The crafttweaker.log file

https://gist.github.com/Sawyer033/aea89a09e10ea9060e8f0076093f0b28

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.2.9

### CraftTweaker version

1.18.2-9.1.207

### The latest.log file

https://gist.github.com/Sawyer033/6ee18010b4fb5090cad9efd4dc8ca6f2

**Comment by jaredlll08** [comment]
This has been closed by https://github.com/CraftTweaker/CraftTweaker/commit/891226945eea4cc60780c8cc3a041835ab7a7a65
