### ISSUE TITLE
Implement entity related events in the legacy branch

### ISSUE THREAD

**Issue by kutschkem** [CraftTweaker/CraftTweaker#1658]
### Describe the feature you'd like

I am trying to modify entity drops based on the dimension they are killed in. In 1.7.10. Crafttweaker would seem the most feasible way - that is, if the entity drop events were implemented.

### Describe alternatives you've considered

I tried using Accidentally circumstantial events instead, which also has a dimension condition. But the condition didn't work as expected, drops were removed regardless of the dimension.

### Additional context

I am using version 3.1.0-legacy.

What I am ultimately after is this: Adding roguelike dungeons to the witchery spirit world. These contain enderman spawners. I don't want them to drop ender pearls in the spirit world (but everywhere else as normal).

### Minecraft version

Other

### Modloader

Forge

**Comment by jaredlll08** [comment]
It is marked legacy for a reason, we are not going to update versions that old, I doubt we can even setup an environment for it nowadays.

Unfortunately you're going to need to find a different mod to achieve what you need.
