### ISSUE TITLE
Improper Holder used for damage sources

### ISSUE THREAD

**Issue by pupnewfster** [CraftTweaker/CraftTweaker#1659]
### Issue description

I am fairly certain that the [holders used](https://github.com/CraftTweaker/CraftTweaker/blob/1.20.1/Common/src/main/java/com/blamejared/crafttweaker/natives/world/damage/ExpandDamageSource.java#L24-L30) when creating damage sources are incorrect and not the desired holder type to be used. It seems that in all `DamageSource` constructors vanilla passes `Holder.Reference` impls instead of a `Holder.Direct`. Passing a direct holder may lead to problems as they always return false in their `is` implementations, which means if someone were to query `is(TagKey)` or `is(ResourceKey<DamageType>)` on the `DamageSource` they would get false as the result.

### Script used

N/A

### The crafttweaker.log file

N/A

### Minecraft version

Other

### Modloader

Forge

### Modloader version

47.0.45

### CraftTweaker version

14.0.6

### Other relevant information

MC version: 1.20.1

### The latest.log file

N/A

**Comment by jaredlll08** [comment]
Closed by https://github.com/CraftTweaker/CraftTweaker/commit/c401dcd6711d5ec247e0a939d072f1a7474c760b
