### ISSUE TITLE
It's not possible to get the ingredients of smithing recipes. [1.19.3-1.19.4]

### ISSUE THREAD

**Issue by laserman120** [CraftTweaker/CraftTweaker#1661]
### Issue description

As Jared wished here is the reminder to fix this in 1.19.3 to 1.19.4:

`for recipe in smithing.getAllRecipes() {
    println("> " + recipe.id);
    
    //Recipe.ingredients will always be empty
    for ingredient in recipe.ingredients {
        println(ingredient.toString());
    }
}`

### Script used

https://pastebin.com/2Wfjnrj8

### The crafttweaker.log file

https://pastebin.com/ij6mF8tq

### Minecraft version

1.20.1

### Modloader

All

### Modloader version

43.2.10

### CraftTweaker version

10.1.46

### The latest.log file

https://gist.github.com/laserman120/e9eae0711c83accce063e4aa53b1e244

**Comment by jaredlll08** [comment]
This has been resolved
