### ISSUE TITLE
[Mod Page Issue] Modrinth link to wiki just links to the Modrinth mod page.

### ISSUE THREAD

**Issue by bellyrose** [CraftTweaker/CraftTweaker#1662]
### Describe the feature you'd like

Just an issue with the [Modrinth page](https://modrinth.com/mod/crafttweaker); the Wiki link just links to the mod page on Modrinth, which is the page the link is on. I assume it's supposed to link [here](https://docs.blamejared.com/1.20.1/en/index) instead.

### Minecraft version

None

### Modloader

All

**Comment by jaredlll08** [comment]
Thanks! Just fixed it
