### ISSUE TITLE
Compatibility with Immersive Engineering for 1.19.4

### ISSUE THREAD

**Issue by darthvader45** [CraftTweaker/CraftTweaker#1663]
### Describe the feature you'd like

As support has extended up to 1.18.2 so far, and Immersive Engineering is released for 1.19.4 and likely will be soon for 1.20, I think support for this mod should also be extended to those Minecraft versions.  The reasoning for this is that modpack makers would be able to adjust the recipes for crushing as well as growing crops in cloches to allow for other crops to be supported, such as Mystical Agriculture's essence and resource seeds.

### Describe alternatives you've considered

I have looked for alternatives to edit cloche recipes and as of yet have found none.

### Minecraft version

1.19.4

### Modloader

Forge

**Comment by jaredlll08** [comment]
Immersive engineering adds their own CraftTweaker support, and I believe they support CraftTweaker on 1.19.4.

I do not know if this support is documented anywhere, it would be best to ask the developers of that mod.
