### ISSUE TITLE
[InvHandler] Have a way to randomize the slotIndex

### ISSUE THREAD

**Issue by ItoKyoshiro** [CraftTweaker/CraftTweaker#1665]
### Describe the feature you'd like

A way to randomize the slotIndex for InvHandler

### Describe alternatives you've considered

I tried using (random.nextInt(40) + 9) for getting a random slot in the player's inventory but is not allowed

### Additional context

Would also be cool to have the details on the Documentation page for each slot. I did my own testing and came to this:
· Fill (-1)
· Hotbar (0-8)
· Inventory (9-35)
· First Row (9-17)
· Second Row (18-26)
· Third Row (27-35)
· Offhand (40)
· Armor (36-39)
· Helmet (39)
· Chestplate (38)
· Leggings (37)
· Boots (36)
(Edited format)

### Minecraft version

1.20.1

### Modloader

Forge

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/InitialInventory/commit/1ddc035ebdf9d97fbeea016d5c18b5cab2f06d3a
