### ISSUE TITLE
Mirror-shaped recipes don't work

### ISSUE THREAD

**Issue by 300f20t** [CraftTweaker/CraftTweaker#1666]
### Issue description

When creating a mirror-shaped recipe, it does not work and the script throws the following error:
![2023-08-07_10 20 42](https://github.com/CraftTweaker/CraftTweaker/assets/93136063/e5960b74-626b-4d47-b0ef-ef38753434ce)
Apart from the craft tweaker, nothing is installed. Forge version 1.19.4 45.1.16.
Even the script from the documentation doesn't work, but I don't think it's the problem.

### Script used

https://gist.github.com/300f20t/65493c1ece1d14c16bdb450e5d3e69d0

### The crafttweaker.log file

https://gist.github.com/300f20t/f7a5e19a84c9995834efd3d4604e129f

### Minecraft version

1.19.4

### Modloader

Forge

### Modloader version

45.1.16

### CraftTweaker version

12.0.2

### The latest.log file

https://gist.github.com/300f20t/1a9686b86c937dfc890b00025d5c8992

**Comment by jaredlll08** [comment]
You need to import crafttweaker.api.recipe.MirrorAxis

Just add ```zenscript
import crafttweaker.api.recipe.MirrorAxis;
```
To the top of your script.
