### ISSUE TITLE
The string is truncated when the /ct hand command is used and copied to the clipboard

### ISSUE THREAD

**Issue by tiehu** [CraftTweaker/CraftTweaker#1668]
### Issue description

After printing the item NBT to the chat bar using ct hand and clicking Copy, I found that the copied string was truncated.

This problem occurs on some items that contain a lot of NBT data.

The same problem occurs with the /ct nbt command.

### Steps to reproduce

1. Hold an item that contains a lot of NBT data (such as a full backpack in some mods).

2. Print the NBT data to the chat bar by using the /ct hand command.

3. Click Copy in the chat bar.

4. Some strings are truncated.

### Script used

N/A

### The crafttweaker.log file

N/A

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

14.23.5.2860

### CraftTweaker version

1.12-4.1.20.690

### Other relevant information

The problem can be repeated without installing any other mods.

### The latest.log file

N/A

**Comment by jaredlll08** [comment]
can you try just running `/ct hand` and then `ctrl +v` somewhere and see if it is truncated?

I vaguely remember this being an issue with vanilla in some way but I don't fully remember

**Comment by tiehu** [comment]
> can you try just running `/ct hand` and then `ctrl +v` somewhere and see if it is truncated?
> 
> I vaguely remember this being an issue with vanilla in some way but I don't fully remember

Yes, it will.

**Comment by jaredlll08** [comment]
Yes it will as in it is still truncated?

**Comment by tiehu** [comment]
> Yes it will as in it is still truncated?

Yes, the string will still be truncated.

**Comment by jaredlll08** [comment]
So the actual issue at hand is that in 1.12, there was no built in copy on click function in Minecraft, so when you click the text, it runs a command to copy it, which is limited by the chat length limit.

If you just run `/ct hand` while holding an item and paste the text (without clicking the text) into somewhere else like VSCode, it works fine.

I have confirmed this to work with over 4000 characters.

If this still doesn't work, then there is nothing I can do to resolve the issues, it must be an issue with another mod or your operating system.

**Comment by tiehu** [comment]
> So the actual issue at hand is that in 1.12, there was no built in copy on click function in Minecraft, so when you click the text, it runs a command to copy it, which is limited by the chat length limit.
> 
> If you just run `/ct hand` while holding an item and paste the text (without clicking the text) into somewhere else like VSCode, it works fine.
> 
> I have confirmed this to work with over 4000 characters.
> 
> If this still doesn't work, then there is nothing I can do to resolve the issues, it must be an issue with another mod or your operating system.

I'm sorry that I misunderstood your meaning.

I thought you wanted me to confirm that the problem wasn't caused by something other than the /ct hand command, I didn't know it would automatically copy the string to the clipboard without clicking it.And in this case the string will not be truncated.

I apologize for wasting your time.Thank you for your help.
