### ISSUE TITLE
[1.19.2] Crashes with CreateSifting

### ISSUE THREAD

**Issue by Meatwo310** [CraftTweaker/CraftTweaker#1670]
### Issue description

Put CraftTweaker and CreateSifter together and the game crashes.

### Steps to reproduce

On Forge 43.2.21 (Minecraft 1.19.2), `create-1.19.2-0.5.1.c.jar`, `createsifter-1.19.2-1.7.3.c-36.jar`, `CraftTweaker-forge-1.19.2-10.1.49.jar` in the mods folder, the game throws `java.lang.reflect.InvocationTargetException` error at startup.

### Script used

not used

### The crafttweaker.log file

https://gist.github.com/Meatwo310/b0d91bcd4288572fb5e1304429b9ca5c

### Minecraft version

Other

### Modloader

Forge

### Modloader version

43.2.21

### CraftTweaker version

1.19.2-10.1.49

### Other relevant information

Crash report: https://mclo.gs/0mTkZsL

This crash occurs with CreateSifter version 1.7.X, not with 1.6.1.

### The latest.log file

https://mclo.gs/pzpkfhd

**Comment by jaredlll08** [comment]
Install CreateTweaker, that mod requires CreateTweaker and CraftTweaker for their support.
