### ISSUE TITLE
Thermal Expansion bug 

### ISSUE THREAD

**Issue by Siqust** [CraftTweaker/CraftTweaker#1671]
### Issue description

I tried to make an multiservo press recipe: (1.19.2 version)
<recipetype:thermal:press>.removeRecipe(<item:thermal:signalum_coin>);
<recipetype:thermal:press>.addRecipe("matter", [<item:thermal:signalum_coin>], <fluid:minecraft:empty>, [<item:mekanism:bio_fuel>], 100000000);
but it said 
"crafts.zs1:0: there is no such Member: removeRecipe"
"crafts.zs1:0: there is no such Member: addRecipe"

### Steps to reproduce

install Forge-1.19.2-10.1.49
craft tweaker Forge-1.19.2-10.1.49
thermal series - 10.2.0.5
thermal expansion - 10.2.021
thermal foundation - 10.2.0.47
write following script

### Script used

https://pastebin.com/88kqAJ5R

### The crafttweaker.log file

https://pastebin.com/crwS3VjF

### Minecraft version

1.19.2

### Modloader

All

### Modloader version

1.19.2-43.2.21

### CraftTweaker version

Forge-1.19.2-10.1.49

### Other relevant information

thermal series - 10.2.0.5
thermal expansion - 10.2.021
thermal foundation - 10.2.0.47

### The latest.log file

https://pastebin.com/crwS3VjF

**Comment by jaredlll08** [comment]
Thermal expansion does not have CraftTweaker support in that version, if you want to modify their recipes, you will need to use `addJsonRecipe`, there is more info on how you can do that on this page:
https://docs.blamejared.com/1.19/en/mods/other_mods
