### ISSUE TITLE
[1.12.2] some recipe of Thermal Dynamics missing or disappre after Crt update

### ISSUE THREAD

**Issue by zeng-github01** [CraftTweaker/CraftTweaker#1681]
### Issue description

Most of the mod's energy pipe recipes disappeared after the Crt update. It looks like Crt did not modify these pipes in this modpack.

ModPack: modified SkyFactory4 on my pc 

### Steps to reproduce

Update CrT to **CraftTweaker2-1.12-4.1.20.693** from **CraftTweaker2-1.12-4.1.20.574** 

### Script used

none

### The crafttweaker.log file

https://gist.github.com/zeng-github01/87038d312cdb43d951bf88acdcc321ee

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

forge-1.12.2-14.23.5.2860

### CraftTweaker version

CraftTweaker2-1.12-4.1.20.693

### Other relevant information

It is theoretically possible to use the original SF4 to reproduce, but **Prestige** needs to be deleted. Because there was a typo in the namespace of the original pre-update Crt. will cause this mod to crash

[https://github.com/JarHax/Prestige/blob/ceaecb41234b08a9c54bb7be97a16bcde593feea/src/main/java/com/jarhax/prestige/compat/crt/CRTRewards.java#L7C37-L7C37](url)

### The latest.log file

https://gist.github.com/zeng-github01/2cbd947ac5751c9bc8aebdfbf1ab7045

**Comment by jaredlll08** [comment]
We don't help with modifying other people's modpacks, there may be a reason that the modpack is using an older CraftTweaker version that we don't know about, and I'm not going to waste my time debugging something that was working perfectly fine, if you need this fixed, report it to the modpack author.
