### ISSUE TITLE
[1.18.2/Forge] Failed to load on launch

### ISSUE THREAD

**Issue by HonzaVinCZ** [CraftTweaker/CraftTweaker#1682]
### Issue description

I have updated my mods to latest versions, especially Create and its addons. After updating these mods, CraftTweaker throws crash on launch. 

### Script used

Irrelevant

### The crafttweaker.log file

Attached

### Minecraft version

1.20.1

### Modloader

Forge

### Modloader version

40.2.10

### CraftTweaker version

9.1.209

### Other relevant information

[latest.log](https://github.com/CraftTweaker/CraftTweaker/files/12729040/latest.log)
[debug.log](https://github.com/CraftTweaker/CraftTweaker/files/12729043/debug.log)
[crash-2023-09-26_16.43.26-fml.txt](https://github.com/CraftTweaker/CraftTweaker/files/12729046/crash-2023-09-26_16.43.26-fml.txt)
[crafttweaker.log](https://github.com/CraftTweaker/CraftTweaker/files/12729050/crafttweaker.log)

### The latest.log file

Attached

**Comment by HonzaVinCZ** [comment]
Update: Cause seems to be CreateTweaker 2.0.0.19 crashing with Create 0.5.1e

**Comment by jaredlll08** [comment]
Update CreateTweaker / downgrade CreateTweaker.
