### ISSUE TITLE
[1.20.1] LootModifiers doesn't seems to work for entities

### ISSUE THREAD

**Issue by Bwapt** [CraftTweaker/CraftTweaker#1683]
### Issue description

Loot modifiers doesn't work for entities, entities won't drop any different loot than the based one.

### Steps to reproduce

1. Run Minecraft only with CraftTweaker (and Fabric ofc)
2. Create a script to create a LootModifiers for entities
3. /reload
4. Kill a mob

### Script used

https://pastebin.com/cvN9bCYB

### The crafttweaker.log file

https://pastebin.com/S4iqAj0G

### Minecraft version

1.20.1

### Modloader

Fabric

### Modloader version

0.14.22

### CraftTweaker version

14.0.17

### Other relevant information

I tried to modify the loot of a blaze, that is why I've first tried this :

`<entitytype:minecraft:blaze>.addLootModifier("blaze_no_killed_by_player_condition", CommonLootModifiers.addWithChance(<item:minecraft:diamond> % 100));`

But this didn't work, the blaze wasn't dropping anything new. That's why the admin Silk advised me to try with a global modifier (the script I pasted). This explained some things :

- This is not a modpack incompatibility as I tried only with this mod
- LootModifiers doesn't probably work only with entities as blocks are dropping.

### The latest.log file

https://pastebin.com/Tc1AWbZR

**Comment by jaredlll08** [comment]
Close by https://github.com/CraftTweaker/CraftTweaker/commit/eb8bc8ce5d1e9f94b9e1b4fd90d52e716af9c51f.
