### ISSUE TITLE
[1.18.2] CraftTweaker Keeps causing game to crash when CreateTweaker is installed

### ISSUE THREAD

**Issue by XxSIBxX** [CraftTweaker/CraftTweaker#1691]
### Issue description

I have a modpack I'm developing consisting of 61 mods, and when I add CreateTweaker to this modpack it crashes on launch.

### Script used

No scripts are in the folder

### The crafttweaker.log file

Unable to get (due to game crashing)

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.2.10

### CraftTweaker version

9.1.207

### Other relevant information

CreateTweaker 2.0.0.19
Create 1.18.2 0.5.1.f

### The latest.log file

https://pastebin.com/qKQUcDKz

**Comment by jaredlll08** [comment]
Update CreateTweaker.
https://www.curseforge.com/minecraft/mc-mods/createtweaker/files/4770434

**Comment by XxSIBxX** [comment]
oh, I was using the Modrinth version, which I guess has an older version. Thank you!
