### ISSUE TITLE
Latest build has bad version

### ISSUE THREAD

**Issue by Syndaryl** [CraftTweaker/CraftTweaker#1693]
### Issue description

Affected file: ``CraftTweaker-forge-1.20.1-14.0.24.jar``

The mods.toml has the version ``version = "${file.jarVersion}"`` - this breaks everything that depends on the mod.

### Steps to reproduce

Create a small Forge pack with CraftTweaker, Create, and CreateTweaker. 
Load.

### Script used

N/A - no script required to create this issue

### The crafttweaker.log file

N/A - Load failed before created

### Minecraft version

1.20.1

### Modloader

Forge

### Modloader version

47.2.6

### CraftTweaker version

14.0.24

### The latest.log file

https://gist.github.com/Syndaryl/e61d9a0d7477dd0d85824727981ed490

**Comment by jaredlll08** [comment]
Make sure the mod is *actually* installed and upload a screenshot of your mods folder please.

That version is what is expected to be there by Forge, it pulls the actual version from the manifest file, if you check some other mods it should be the same thing.

**Comment by jaredlll08** [comment]
I can confirm that this version is working perfectly fine 
![image](https://github.com/CraftTweaker/CraftTweaker/assets/5553605/88abe2ab-1d3a-4abf-8c21-d6649545903d)
Try reinstall the mod.
