### ISSUE TITLE
[1.12.2] Forge freezes when finishing mod

### ISSUE THREAD

**Issue by agabeluga** [CraftTweaker/CraftTweaker#1697]
### Issue description

When loading my modpack, the game freezes when CraftTweaker2 is getting finished

### Script used

no script

### The crafttweaker.log file

https://gist.github.com/agabeluga/19aac5a739a44da299b1d8a9a179e4bf

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

14.23.5.2860

### CraftTweaker version

4.1.20.697

### The latest.log file

https://gist.github.com/agabeluga/063e2b7e97e26687c983cdb25c20be2c

**Comment by jaredlll08** [comment]
Can you reliably reproduce this?
If you can, can you make a script file and add `#disable_search_tree` and see if that changes anything?

**Comment by agabeluga** [comment]
As a text document?

**Comment by agabeluga** [comment]
It helped. Thanks!!

**Comment by jaredlll08** [comment]
did it help as in get rid of the issue completely, or just make it not take *as long* as it was?

**Comment by agabeluga** [comment]
It fixed it, though know I have problems with another mod. It's always like this.

**Comment by agabeluga** [comment]
Also I might be a bit late, but happy New Year!!!
