### ISSUE TITLE
OptiFine and Cleanroom keep zs error reporting from showing up in the chat bar!

### ISSUE THREAD

**Issue by ztblat** [CraftTweaker/CraftTweaker#1698]
### Issue description

Only OptiFine, Cleanroom and CraftTweaker are installed.
![ZGHV5KW5KL4A`T49_~%@GDW](https://github.com/CraftTweaker/CraftTweaker/assets/101653075/dd204555-9786-493c-9f94-a738824db1be)

### Script used

https://gist.github.com/ztblat/089ad5d8ad7166a44468743c21be0787

### The crafttweaker.log file

https://gist.github.com/ztblat/5227f47948826cfce15ba0e322cdd615

### Minecraft version

1.12.2

### Modloader

Forge

### Modloader version

cleanroom-15.24.0.3024

### CraftTweaker version

4.1.20.696

### The latest.log file

https://gist.github.com/ztblat/7091d0e2b26e7fc040ce5238fa9d5200

**Comment by jaredlll08** [comment]
CraftTweaker 1.12.2 is designed for Forge, I don't know *exactly* what Cleanroom is / does, but from what I can tell, it seems to be some sort of fork of Forge, as such it is unsupported.

If you can reproduce this error with just actual Forge, no optifine or Cleanroom, then maybe I can look into it.
