### ISSUE TITLE
forge 47.2.0 minecraft 1.20.1

### ISSUE THREAD

**Issue by Thunderrock424242** [CraftTweaker/CraftTweaker#1704]
### Issue description

without using any scripts it uses a lot of the server thread

### Script used

none

### The crafttweaker.log file

not revelent

### Minecraft version

1.20.1

### Modloader

Forge

### Modloader version

47.2.0

### CraftTweaker version

14.0.30

### Other relevant information

without using any scripts it uses 4%
![Screenshot 2024-01-28 171613](https://github.com/CraftTweaker/CraftTweaker/assets/119463825/d418f93b-c6a6-4712-9966-831989e22503)

### The latest.log file

https://mclo.gs/CFaX2gb

**Comment by jaredlll08** [comment]
Thanks for the report, this has now been fixed by this commit: https://github.com/CraftTweaker/CraftTweaker/commit/fb4baca02ca65a437c8db81b6adb7a7141a4f557
