### ISSUE TITLE
IngredientExtensionAPI is not required after Fabric's Custom Ingredient API

### ISSUE THREAD

**Issue by Witixin1512** [CraftTweaker/CraftTweaker#1705]
### Issue description

After Fabric [merged](https://github.com/FabricMC/fabric/pull/2586) the custom ingredient API, IngredientExtensionAPI is no longer required on Fabric above 1.19.3.

This means that mod hosting sites must be updated / fixed to reflect this change.

### Script used

-

### The crafttweaker.log file

-

### Minecraft version

1.19.4

### Modloader

Fabric

### Modloader version

-

### CraftTweaker version

-

### The latest.log file

-

**Comment by jaredlll08** [comment]
Fixed by referencing commits.
