### ISSUE TITLE
CraftTweaker2 Gregcraft  Crash

### ISSUE THREAD

**Issue by caniplzjustlogin4godsakesthistakesforev** [CraftTweaker/CraftTweaker#1706]
### Issue description

Crashed whilst starting the game, See log and crash report

### Script used

No Script was used

### The crafttweaker.log file

Crafttweaker log not found, game crashed on start-up

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

Forge - 14.23.5.2860

### CraftTweaker version

1.12.2-4.1.10.698

### The latest.log file

https://gist.github.com/caniplzjustlogin4godsakesthistakesforev/f463d05c5d69ac283ed58d6819a108e3

**Comment by jaredlll08** [comment]
This is not an issue caused by CraftTweaker, this is an issue with one of your mods trying to register a class that doesn't exist.

Unfortunately I don't know what mod is trying to do that, you are going to need to disable mods until it works to figure it out.

**Comment by iamtyroon** [comment]
if you could state which mod caused this error cause im having trouble launching my instance coz of incompatibility issues with craft tweaker

**Comment by jaredlll08** [comment]
Like I said, I do not know which mod, you need to disable mods until it stops crashing

**Comment by glektarssza** [comment]
@iamtyroon Looks like this might be an issue with Multiblock Tweaker. Found this issue filed with them: eutro/MultiblockTweaker#37
