### ISSUE TITLE
Script that adds crafting table recipes doesn't work, everything else does

### ISSUE THREAD

**Issue by The-Goat-HUN** [CraftTweaker/CraftTweaker#1707]
### Issue description

Every line of script seems to be working fine, except the ones that add crafting table recipes.

### Steps to reproduce

Unkown. All I did was reorganize the lines into alphabetical order. No new ones were added nor any was removed. Everything worked previously.

### Script used

https://pastebin.com/WaYpECiY

### The crafttweaker.log file

https://pastebin.com/u6R57afJ

### Minecraft version

1.19

### Modloader

Forge

### Modloader version

43.3.8

### CraftTweaker version

1.19.2-10.1.53

### The latest.log file

https://pastebin.com/m8C2xr9f

**Comment by kindlich** [comment]
Intended behavior.

Scripts are executed from top to bottom.
In line 118 you add a recipe from mud bricks.
In line 129 you remove all recipes that return mud bricks.
Line 129 also removes the recipe added by line 118.

I recommend that you always put all remove calls before any add calls to avoid such issues.
