### ISSUE TITLE
[1.20.1] CraftTweaker has a hard dependency on CreateTweaker, when Create is in

### ISSUE THREAD

**Issue by Normal69** [CraftTweaker/CraftTweaker#1708]
### Describe the feature you'd like

Symphtom:
CraftTweaker has a hard dependency on CreateTweaker, when Create is in.
[CTW](https://www.curseforge.com/minecraft/mc-mods/createtweaker)

Advised fix:
Mention it in the docs, the config file as a comment, and the dependecy configs here as a feature. ;)
Took a bit of time to discover, usually I look the above first.

Accountable mods:
```
CraftTweaker-forge-1.20.1-14.0.32.jar
create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.7.h.jar
create_mechanical_extruder-1.20.1-1.5.7.e-22.jar
create_mechanical_spawner-1.20.1-0.0.14.e-22.jar
create-1.20.1-0.5.1.f.jar
CreateCasing-1.20.1-1.6.0.jar
create-new-age-forge-1.20.1-1.1.2.jar
createoreexcavation-1.20-1.4.2.jar
createsifter-1.20.1-1.8.1.e-22.jar
create-stuff-additions1.20.1_v2.0.4a.jar
CreateTweaker-forge-1.20.1-4.0.7.jar
```

Feel free to scorn me, still thank you for your hobby! <3

### Describe alternatives you've considered

Using ItemBlocker to forbid some of them, but I cannot be sure it it could be ciscumvented with automation, never entering player inventory.

### Minecraft version

1.20.1

### Modloader

Forge

**Comment by Witixin1512** [comment]
CreateSifter is the one that has a hard dependency on CreateTweaker. See: https://github.com/oierbravo/createsifter/issues/47

CraftTweaker works fine with Create when both are installed.
