### ISSUE TITLE
Brewing Recipes should be supported?

### ISSUE THREAD

**Issue by Ch3225** [CraftTweaker/CraftTweaker#1709]
### Describe the feature you'd like

Seems adding brewing recipes are not supported yet. 

### Minecraft version

None

### Modloader

Forge

**Comment by jaredlll08** [comment]
Brewing recipes are already supported?

https://docs.blamejared.com/1.20.4/en/forge/api/recipe/brewing/Brewing#addRecipe

**Comment by Ch3225** [comment]
I used in-game command like /crafttweaker recipes manager <...>, and I there is auto-complete about crafting or smelting but no brewing
![image](https://github.com/CraftTweaker/CraftTweaker/assets/49605433/e1884e89-5dc9-40c3-a4cc-aee357ed5d88)
I also checked crafttweaker.log and find nothing about brewing and I thought brewing is not supported
Thank you for your link, I will check the wiki

**Comment by jaredlll08** [comment]
Brewing isn't a recipe manager as they are not done via datapacks.
