### ISSUE TITLE
Sequences appear to tick four times as fast as they should

### ISSUE THREAD

**Issue by ChiefLogan3010** [CraftTweaker/CraftTweaker#1711]
### Issue description

When running the script provided, you would assume the sequence will sleep for 2400 ticks (2 minutes), however it appears to sleep for only 600 ticks (30 seconds).

### Steps to reproduce

Can be tested by placing a spruce log on top of a stonecutter and timing how long it takes to break into planks.

### Script used

https://gist.github.com/ChiefLogan3010/e19a74967bcd4f99f92eaccfaedd6a0a

### The crafttweaker.log file

https://gist.github.com/ChiefLogan3010/85903308441bf44ed95be6189974ca30

### Minecraft version

1.19

### Modloader

Forge

### Modloader version

43.3.2

### CraftTweaker version

10.1.53

### The latest.log file

https://gist.github.com/ChiefLogan3010/918e4c5f9f2924e38f072bc51aa7671a

**Comment by jaredlll08** [comment]
Fixed by https://github.com/CraftTweaker/CraftTweaker/commit/72644c3df9e0a0b3e31b36f6fda8ec14bc90c307
