### ISSUE TITLE
Crash on mod load: java.lang.ClassNotFoundException: com.blamejared.createtweaker.recipe.manager.base.IProcessingRecipeManager

### ISSUE THREAD

**Issue by jlbrewer** [CraftTweaker/CraftTweaker#1714]
### Issue description

I'm working on a self-built modpack in 1.20.1, Forge 47.2.20, CraftTweaker-forge-1.20.1-14.0.36. This error appeared after I updated Forge and a bunch of mods in the CurseForge client...unfortunately I didn't keep track of everything that changed. I tried backing Forge down to 47.2.0 (the minimum version that's comparable with my mod list) and I tried a few versions of CraftTweaker back to .30 with no difference. The crash log output is non-obvious to me and I'm hoping it will be more obvious to someone here.

[crash-2024-02-29_10.37.43-fml.txt](https://github.com/CraftTweaker/CraftTweaker/files/14450343/crash-2024-02-29_10.37.43-fml.txt)

### Script used

N/A

### The crafttweaker.log file

https://gist.github.com/jlbrewer/40d245d30bc5fc463282571a35745fdf

### Minecraft version

1.20.1

### Modloader

Forge

### Modloader version

47.2.20

### CraftTweaker version

1.20.1-14.0.36

### The latest.log file

https://gist.github.com/jlbrewer/4e40b2e493f6a472fe6aacb4029ec741

**Comment by Witixin1512** [comment]
This is a CreateSifter issue. Install CreateTweaker or remove it:
https://github.com/oierbravo/createsifter/issues/47

**Comment by jlbrewer** [comment]
Installing CreateTweaker did the trick, thanks!
