### ISSUE TITLE
IDataOps.convertTo for String values leaves extra Quotation marks

### ISSUE THREAD

**Issue by Dragon-Seeker** [CraftTweaker/CraftTweaker#1716]
### Issue description

For the `STRING` branch of the switch the call for `input.asString` should be `input.getAsString` to prevent quotation marks from being in the returned string. Found due to owolib's use of a custom format to handle Codec<->Endec interop

### Script used

https://pastebin.com/9EXAAWjh

### The crafttweaker.log file

https://pastebin.com/4WvwSk64

### Minecraft version

1.20.4

### Modloader

Fabric

### Modloader version

0.15.3

### CraftTweaker version

17.0.12

### The latest.log file

https://pastebin.com/AybcDJd8

**Comment by kindlich** [comment]
For reference - This is the issue that dragon-seeker mentioned:
https://github.com/wisp-forest/alloy-forgery/issues/129

---

The referenced CodeLine is part of [`IDataOps#convertTo`](https://github.com/CraftTweaker/CraftTweaker/blob/72644c3df9e0a0b3e31b36f6fda8ec14bc90c307/common/src/main/java/com/blamejared/crafttweaker/api/data/op/IDataOps.java#L72)
```java
    @Override
    public <U> U convertTo(final DynamicOps<U> outOps, final IData input) {
        //... snip ...//
        
        return switch(input.getType()) {
            //... snip ...//
            case STRING -> outOps.createString(input.asString());
            case EMPTY -> outOps.empty();
        };
    }
```
