### ISSUE TITLE
Game crashes when installing with Kemonocraft

### ISSUE THREAD

**Issue by 167OSS** [CraftTweaker/CraftTweaker#1717]
### Issue description

[crash-2024-03-12_21.45.42-client.txt](https://github.com/CraftTweaker/CraftTweaker/files/14573825/crash-2024-03-12_21.45.42-client.txt)

### Script used

no

### The crafttweaker.log file

no

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

14.23.5.2860

### CraftTweaker version

4.1.20.698

### Other relevant information

no

### The latest.log file

no

**Comment by jaredlll08** [comment]
Kemonocraft is not properly regstering their items.
