### ISSUE TITLE
why doesnt this work???

### ISSUE THREAD

**Issue by AMRRIDER** [CraftTweaker/CraftTweaker#1718]
### Issue description

it keep saying no such member only with this line

### Steps to reproduce

 just write the skript used

### Script used

<recipetype:thermal:smelter>.addrecipe("smelter_test", [<item:thermal:silver_ingot> % 100, <item:thermal:silver_ingot> %100],[<tag:items:forge:ingot/iron_ingot>, <tag:items:forge:ingot/lead_ingot>], 20, 500);

### The crafttweaker.log file

https://pastebin.com/qc0xU5u0

### Minecraft version

1.19.3

### Modloader

Forge

### Modloader version

43.2.22

### CraftTweaker version

10.1.54

### The latest.log file

https://gist.github.com/AMRRIDER/49586bb74784c0df12daf4bfc93264ca

**Comment by jaredlll08** [comment]
somewhere in your script file, you have
<tag:forge
but that needs to be <tag:items:forge

There are a few other issues, however I think the [discord](https://discord.blamejared.com) is a better place to ask for help with those.

**Comment by AMRRIDER** [comment]
ik that bc i forgot to copy the last part

**Comment by AMRRIDER** [comment]
this is my last wayt to learn how to fix this since i cant use discord

**Comment by jaredlll08** [comment]
If you want help, we need the full script file on gist.github.com, but based on the script you gave, you are using older thermal code for newer minecraft, for new versions of minecraft, you need to use this method of adding recipes https://docs.blamejared.com/1.19.3/en/mods/other_mods
