### ISSUE TITLE
crash when adding crafttweaker to my modpack

### ISSUE THREAD

**Issue by tinyzooseven** [CraftTweaker/CraftTweaker#1721]
### Issue description

im working on creating a custom modpack and the game crashes on startup when adding crafttweaker to the pack 

### Steps to reproduce

add crafttweaker to the mods folder
launch game
crash 

### Script used

None (first time install)

### The crafttweaker.log file

https://pastebin.com/t88BAYWQ

### Minecraft version

1.20.1

### Modloader

Forge

### Modloader version

47.2.0

### CraftTweaker version

1.20.1-14.0.38

### The latest.log file

https://pastebin.com/NS24N8JV

**Comment by jaredlll08** [comment]
Not our issue.
https://github.com/oierbravo/createsifter/issues/47

You can fix it by installing CreateTweaker as well
