### ISSUE TITLE
GBook mod not see CT resipes

### ISSUE THREAD

**Issue by vaniOK20** [CraftTweaker/CraftTweaker#1723]
### Issue description

If in the Guide Book mod you create a book in which to show the craft added by CraftTweaks, an error will appear

### Script used

https://pastebin.com/RUcvNwXy

### The crafttweaker.log file

https://pastebin.com/6Gvjm5bM

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

14.23.5

### CraftTweaker version

1.0.10-150

### The latest.log file

https://pastebin.com

**Comment by jaredlll08** [comment]
the pastebin you linked for the latest.log file is not valid.

**Comment by jaredlll08** [comment]
Closing due to no reply, and no log file to see what the error is.
