### ISSUE TITLE
Draconic Evolution on newer versions Support

### ISSUE THREAD

**Issue by MrFesli** [CraftTweaker/CraftTweaker#1730]
### Describe the feature you'd like

Draconic Evolution on newer versions like, 1.18, 1.19 etc. support would be really nice, espesialy when there was in 1.16

### Additional context

I Really like draconic evolution and when i was making a modpack for 1.16 I really liked the fact that there was Draconic Evolution Support, I tried to add some recipies in a newer verison (1.18) and there is no support for it there, which is pretty sad if you ask me.

### Minecraft version

1.18

### Modloader

All

**Comment by jaredlll08** [comment]
You can use `addJsonRecipe` to add recipes without explicit support.

https://docs.blamejared.com/1.18/en/mods/other_mods

At some point I may make an addon that adds explicit support, but for now you will need to use `addJSONRecipe`°

**Comment by MrFesli** [comment]
one key moment missed
![image](https://github.com/CraftTweaker/CraftTweaker/assets/67827264/c13a3d1e-ca12-422d-891d-f4e98042273f)

**Comment by jaredlll08** [comment]
Now that is interesting, I'm guessing they are not registering their RecipeType.

Can you try using the `recipes` global instead: https://docs.blamejared.com/1.18/en/vanilla/api/recipe/manager/GenericRecipesManager#addJsonRecipe

It *should* work
