### ISSUE TITLE
1.20.1 Fabric Server NBT Ingredients show null

### ISSUE THREAD

**Issue by azavier-a** [CraftTweaker/CraftTweaker#1731]
### Issue description

I have a dedicated server set up for vanilla 1.20.1 fabric with JEI and CraftTweaker installed.

When loading the script, it gives me the following error:
`[13:05:39.825][WARN][CraftTweaker]: Shapeless recipe with ID 'crafttweaker:book_to_crafting_table' contains null or empty ingredients, removing entries!`

However, if I load up the same script in single-player, it loads just fine.

I had similar issues when trying to make recipes that require specific potions. While it didn't throw this error, the ingredients with NBT data showed up as air instead. The crafting recipe still loaded, so it would work if you put in the correct item, it just displayed as air with no errors.

also, I was originally using REI but switched to see if that was the issue..

### Steps to reproduce

1. Use a dedicated server with 1.20.1 Fabric loader and CraftTweaker (also a recipe viewer)
2. Try to make a recipe with any sort of NBT data for an ingredient
3. It wont load or it will render as air in the recipe viewer

### Script used

https://pastebin.com/MfBir8Cm

### The crafttweaker.log file

https://pastebin.com/9gBpQsMB

### Minecraft version

1.20.1

### Modloader

Fabric

### Modloader version

0.15.10

### CraftTweaker version

14.0.38

### The latest.log file

https://pastebin.com/1Q3zecTL

**Comment by kindlich** [comment]
Hey there,

it looks like the crafttweaker.log file got truncated.
Could you re-upload the complete crafttweaker.log file?

**Comment by azavier-a** [comment]
Sorry about that.

https://pastebin.com/6qzgnjQf

Here you can see the log from when I load up the game to when I join, and the error thrown by the given script on the server. The same script continues to function as intended in singleplayer

**Comment by jaredlll08** [comment]
Fixed by https://github.com/CraftTweaker/CraftTweaker/commit/0294391541c83f7181880dae6545fa8ca93a626c
