### ISSUE TITLE
.addshifttooltip sses crouch keybind rather than shift key

### ISSUE THREAD

**Issue by D1scoball** [CraftTweaker/CraftTweaker#1733]
### Issue description

Whenever using the .addshifttooltip function it uses whatever the crouch keybind is set to over the shift key itself

### Script used

Any use of .addshifttooltip

### The crafttweaker.log file

-

### Minecraft version

1.20.1

### Modloader

Forge

### Modloader version

47.1.30

### CraftTweaker version

14.0.27

### The latest.log file

-

**Comment by jaredlll08** [comment]
Closed by https://github.com/CraftTweaker/CraftTweaker/commit/6e09cb9bd0afefc30ab6f5efcc9593dbc6a33be4
