### ISSUE TITLE
1.20.1 | Crash with attribute-edited armor and Cold Sweat

### ISSUE THREAD

**Issue by skall0900** [CraftTweaker/CraftTweaker#1736]
### Issue description

While editing attributes of armor pieces, sometimes, when closing inventory while pointing at the armor), the server crashes, while crashlog blames CraftTweaker and Cold Sweat. I've reported the issue to CS developer, they said to report it there.

### Steps to reproduce

1) Open Minecraft
2) Open World
3) Load .zs script that adds attributes to one armor (in this scenario: Heavy Iron Armor set)
4) Wait (roughly 5-25 minutes, it occurs randomly)
5) Wear armor
6) Open inventory, point the cursor at the armor and close inventory // Wear armor, open inventory and close inventory
7) Crash the server

### Script used

https://pastebin.com/WtemK694 (attributes) // https://pastebin.com/dUr7eJAn (other crafts)

### The crafttweaker.log file

https://pastebin.com/9ATfQUcD

### Minecraft version

1.20.1

### Modloader

Forge

### Modloader version

47.2.30

### CraftTweaker version

14.0.40

### Other relevant information

Mods used in this scenario: *(theres 100+ other mods; I'll send the full list if needed)*
- Cold Sweat (ver. **2.3-b03f** (2.3-b03e could work too, the "f" version can be found [here](https://github.com/Momo-Softworks/Cold-Sweat/issues/305)); [curseforge page](https://www.curseforge.com/minecraft/mc-mods/cold-sweat)
- Lucky's Armory (ver. **0.4.0.1**); [curseforge page](https://www.curseforge.com/minecraft/mc-mods/luckys-armory)
- Pufferfish's Attributes (ver. **0.2.0**); [curseforge page](https://www.curseforge.com/minecraft/mc-mods/puffish-attributes)

### The latest.log file

https://pastebin.com/wKh1TVkX (cut the point of restart where crash happened, as the original latest.log has 2.78MB of text there)

**Comment by jaredlll08** [comment]
Can you reproduce with just CraftTweaker and Cold Sweat?

**Comment by skall0900** [comment]
Yes, I did reproduce it on isolated build with just all the suspected mods (6 of them) and the used attributes script. (though I edited it a bit, [heres the new version](https://pastebin.com/gM5uaAnz); I changed the AttributeOperation)
[Crash log here](https://pastebin.com/myv17PTn)

edit: It even took roughly 30 seconds to do so, with just inventory closing/opening with armor on.
edit 2: I doubt it was the fault of PA or LA, I added Fancy Menu because it did crash once because of it, but I wasn't able to reproduce the crash on newer version of FM.

**Comment by skall0900** [comment]
Oh, and theres [crafttweaker](https://pastebin.com/i1D5vLiN) and [latest](https://pastebin.com/hZDFhCD7) logs

**Comment by skall0900** [comment]
Speaking of FancyMenu... I did reproduce the [crash](https://pastebin.com/sub3KMGN) on newer version, and it happens sometimes when hovering over armor, not just closing inventory. Still it relies on "java.util.ConcurrentModificationException: null", but this is not server crash, its client crash. If theres no CraftTweaker's fault, I'll move the entry to FancyMenu issue tracker then.

If another CT or latest log needed, reply.
I'll update this line if I reproduce same crash on isolated buildr: oops, forgot. Reproduced!
**Way to reproduce**: Just hover over armor that you wear, and with some chance, it crashes.

EDIT: FM seems to appear only if it registers the inventory screen when crash happens, as most of the time, when crash happens mid-game (= fancyMenu already registered inv. screen), crashlog can't blame FM

**Comment by jaredlll08** [comment]
I'm unable to reproduce this error using the mods you listed.

Regardless there really isn't much I can do here, the only way that an error like this can occur is if some other mod is running things in parallel, such as 2 different events being ran at once, or the same event being ran twice at once, both of these are unsupported by CraftTweaker and the majority of other mods.

What would really help is if you can get me a list of the proper minimum required mods to reproduce, since each log file you give me has different mods compared to the mods you say you are running, in my test I used the mods listed in this crash log https://github.com/CraftTweaker/CraftTweaker/issues/1736#issuecomment-2143428506 as it was the fewest amount of mods required, but I was unable to cause a crash on either a server or a client.
