### ISSUE TITLE
crashes on 1.20.6

### ISSUE THREAD

**Issue by MCBEModder2020** [CraftTweaker/CraftTweaker#1738]
### Issue description

crash durinmg launch

### Steps to reproduce

idk? download mods from my list

### Script used

none

### The crafttweaker.log file

none

### Minecraft version

Other

### Modloader

Fabric

### Modloader version

5.11?

### CraftTweaker version

19.0.8 and 19.0.7

### Other relevant information

im using a custom polymc build for 1.20.6
[PolyMc-5.6.1+1.20.6.jar.zip](https://github.com/user-attachments/files/15749403/PolyMc-5.6.1%2B1.20.6.jar.zip)
u can build urself by building pr of dep required, polymc prob not even related to this tho

### The latest.log file

https://gist.github.com/TheKidThatCodes/b81a0dbb4ece05081e0343fdb92ccda5

**Comment by jaredlll08** [comment]
Fix by https://github.com/FauxMC/Faux-Custom-Entity-Data/commit/691b2540f4957b449de573eb48442631f82aca6e

Please update Faux-Custom-Entity-Data
