### ISSUE TITLE
Craft Tweaker has failed to load correctly

### ISSUE THREAD

**Issue by GrandmaPork** [CraftTweaker/CraftTweaker#1739]
### Issue description

I've tried using 14.0.40-14.0.35 and the issue persists.
My modpack wont launch with crafttweaker installed. works fine without it.
Unable to determine the cause through logs

If these don't help, i can do a binary check

### Steps to reproduce

Install crafttweaker
Launch game (with my modpack)

### Script used

none

### The crafttweaker.log file

[crafttweaker.log](https://github.com/user-attachments/files/15839857/crafttweaker.log)

### Minecraft version

1.20.1

### Modloader

All

### Modloader version

47.1.3

### CraftTweaker version

14.0.35

### Other relevant information

I've been using 14.0.38 on the same mc and forge versions just fine up until this modpack. I am sure a mod is causing it but I cannot tell from logs

### The latest.log file

[crash-2024-06-14_11.02.16-fml.txt](https://github.com/user-attachments/files/15839854/crash-2024-06-14_11.02.16-fml.txt)

**Comment by Witixin1512** [comment]
The issue is caused by CreateSifter, as you can see here: https://github.com/oierbravo/createsifter/issues/47.

CreateSifter requires [CreateTweaker](https://www.curseforge.com/minecraft/mc-mods/createtweaker) when CraftTweaker is installed.

**Comment by GrandmaPork** [comment]
ty
