### ISSUE TITLE
Craft Tweaker / Amendments Crash with Cauldrons

### ISSUE THREAD

**Issue by Lonemind** [CraftTweaker/CraftTweaker#1741]
### Issue description

Minecraft 1.20.1
Amendments 1.2.4
Moonlight 2.11.41
Supplementaries 2.8.15
CraftTweakrer 14.0.40

If there are scripts in the Scripts folder for Craft Tweaker and you toss items into a cauldron Minecraft crashes with this [crashlog](https://mclo.gs/cSZJLja).

The latter crashlog was generated with nothing but the aforementioned mods installed. It didn't point at any suspected mods but in my full modpack I get this [crashlog](https://mclo.gs/JGCavi7) that points to Amendments and CraftTweaker as the suspected mods. (And Recipe Essentials but I get the crash even when removing that mod).

I'm posting this issue both on the Amendments Github and CraftTweaker. I'll edit each post to crosslink the issues.

Edit: https://github.com/MehVahdJukaar/amendments/issues/91

### Script used

https://mclo.gs/ISMc8Rw

### The crafttweaker.log file

https://mclo.gs/GbHhv7y

### Minecraft version

1.20.1

### Modloader

Forge

### Modloader version

47.3.1

### CraftTweaker version

14.0.40

### The latest.log file

https://mclo.gs/OzFrzXf

**Comment by kindlich** [comment]
The first crash log you sent complains about moonlight missing.
```
Mod amendments requires moonlight any
		Currently, moonlight is not installed
```

As for the server crash log, I'd have to check a bit more from the crash log I'd say there may be an issue in how CraftTweaker calculates if a mirrored shaped recipe matches.

**Comment by kindlich** [comment]
I see the issue on amendments side.

https://github.com/MehVahdJukaar/amendments/blob/8533389fcdde10d51bffc9ec86e460755e66329b/common/src/main/java/net/mehvahdjukaar/amendments/common/recipe/DummyContainer.java#L21

They create a dummy container to check for stew crafting recipes. That container has dimensions that are larger than the container itself which breaks the contract that containers have a rectangular size. 

CraftTweaker expects that `container.size() == container.height() * container.width()` which does not hold true for amendments dummy container unless the number of items in the cauldron is a square number.

**Comment by jaredlll08** [comment]
Closing due to the issue not being on our side.
