### ISSUE TITLE
[1.20.1] Recipes work in Singleplayer, not on Server

### ISSUE THREAD

**Issue by nothingtown** [CraftTweaker/CraftTweaker#1742]
### Issue description

So, first-ish time using Crafttweaker since 1.12.1, and I've written up some scripts for a server I'm running. The recipes show up and work in singleplayer, yet when I upload them to the server they just don't work. 

When I run /ct syntax, it says an error occurred while loading scripts, but I'm not sure what that could be since they work in singleplayer and are the exact same in the server files.

(To be fair, this could be a mod conflict, we're using a pretty large modpack...)

### Steps to reproduce

1. Make scripts, put 'em in your scripts folder
2. Put them in the server's script folder
3. They don't work 

### Script used

https://gist.github.com/nothingtown/1e6851f214724d0145cc9f460ff966a0

### The crafttweaker.log file

https://gist.github.com/nothingtown/38fcd1b44d2d1b0e6686a79f601ca95d

### Minecraft version

1.20.1

### Modloader

Fabric

### Modloader version

0.15.11 (i believe?)

### CraftTweaker version

14.0.40

### Other relevant information

Genuinely not very sure what could be going on. I found something on GitHub about Amendments causing an issue, but I removed but still no dice... The server doesn't crash either.

### The latest.log file

https://gist.github.com/nothingtown/171dcde73aeef49919c38333e6ec7ac8

**Comment by jaredlll08** [comment]
Not our issue, SophisticatedCore is using client only classes on the server.
https://github.com/Salandora/SophisticatedCore/issues/3#issuecomment-2182094037
