### ISSUE TITLE
how can i get this to run server side only on 1.21 fabric

### ISSUE THREAD

**Issue by MCBEModder2020** [CraftTweaker/CraftTweaker#1745]
### Describe the feature you'd like

how can i get this to run server side only on 1.21

### Describe alternatives you've considered

kubejs is not on 1.21 yet, idk how to patch mod to do this

### Minecraft version

1.21

### Modloader

Fabric

**Comment by jaredlll08** [comment]
Thsi mod is required on both the client and the server, there is no server side only mode.

**Comment by MCBEModder2020** [comment]
ive managed to get this to run server side only before, why doesent it work in 1.21 anymore

**Comment by jaredlll08** [comment]
The last time this mod was possibly able to run only on the server was during 1.12, over 7 years ago.

A lot has changed sinced 1.12.

**Comment by MCBEModder2020** [comment]
that was just a few weeks ago on 1.20.4

**Comment by jaredlll08** [comment]
I just tested the following, using Fabric on the server and the latest version of CraftTweaker for each version, the client had absolutely no mods, not even Fabric..

On 1.20.1, you can join a server using CraftTweaker, provided that there are no script files, as soon as a script file is added, you can no longer join.

On 1.20.4, you can join a server using CraftTweaker, provided that there are no script files, as soon as a script file is added, you can no longer join.

On 1.21, you can join a server using CraftTweaker, provided that there are no script files, as soon as a script file is added, you can no longer join.

CraftTweaker cannot work without script files, therefore it does not work on a server without the clients having the mod as well.

**Comment by MCBEModder2020** [comment]
https://github.com/CraftTweaker/CraftTweaker/issues/1724 and the one after it are when i was doing this, i was using scripts

**Comment by MCBEModder2020** [comment]
would polymer and polymc affect it?

**Comment by jaredlll08** [comment]
I don't know what to tell you, but the way that we sync script files is by registering them as recipes, so as soon as you have a single script file, we try and send it to the client, and the client receives an unknown recipe and prevents the login.

There is no way around that.

It is possible it is polymc, this is the first time I've heard of that project (horrible horrible name, when I google it I get the PolyMC launcher...), so I don't know what they actually do.

**Comment by MCBEModder2020** [comment]
not the launcher, the fabric mods on vanilla server mod by theepicblock

**Comment by jaredlll08** [comment]
Like I said, I know it isn't the launcher, I looked at the mod, and I don't know if it is that, all I know is, is that my mod does not have a server only mode, if another mod patches the game to not send unknown content to the client, then it is possible that CraftTweaker can work server side only, however it would be completely unsupported by me.

**Comment by Patbox** [comment]
If it syncs things as recipes , then yes PolyMc would make it run server side. And with the name, the mod as actually way older than the launcher, but the launcher just got more popular.
