### ISSUE TITLE
Removing a recipe with a mod that gives alternative recipes for the removed recipe keeps the recipe you removed

### ISSUE THREAD

**Issue by Vorimexilo** [CraftTweaker/CraftTweaker#1746]
### Issue description

 I'm not experienced with scripting or using GitHub in general, so I apologize if this is a repeat issue, an already known one, or if it can be fixed.
 I am using Terralith, and I want to remove pistons that come from Minecraft itself. However, despite writing craftingTable.removeByName("minecraft:piston"); inside of the .txt file located in the scripts folder and then later changing it into a .zs file, the Terralith recipe for pistons allow pistons to still be craftable.

### Script used

craftingTable.removeByName("minecraft:piston");

### The crafttweaker.log file

N/A

### Minecraft version

1.20.1

### Modloader

Forge

### Modloader version

47.3.0

### CraftTweaker version

14.0.40

### The latest.log file

N/A

**Comment by jaredlll08** [comment]
```zenscript
craftingTable.removeByName("minecraft:piston");
```
Can only remove a single recipe by its name, if you want to remove *all* recipes for pistons, you would do:
```zenscript
craftingTable.remove(<item:minecraft:piston>);
```
which will remove terralith's as well.

Alternatively, you can do:
```zenscript
craftingTable.removeByName("minecraft:piston");
craftingTable.removeByName("terralith:piston_alt");
```
to achieve the same thing.

**Comment by Vorimexilo** [comment]
Thank you so much! :)
