### ISSUE TITLE
1.21 | Vanilla Rarities override modifyTooltip function

### ISSUE THREAD

**Issue by ValeriaeWasTaken** [CraftTweaker/CraftTweaker#1748]
### Issue description

If an item has a rarity with a colored name any attempts to modify its tooltip will not work

### Steps to reproduce

Change an items rarity, then try to use modifyTooltip() on it

### Script used

https://pastebin.com/K1w9Dz9S

### The crafttweaker.log file

https://gist.github.com/ValeriaeWasTaken/8bad8857b42329ce964a4185f8679c7f

### Minecraft version

1.21

### Modloader

NeoForge

### Modloader version

21.0.42

### CraftTweaker version

20.0.13

### The latest.log file

https://gist.github.com/ValeriaeWasTaken/8bad8857b42329ce964a4185f8679c7f

**Comment by jaredlll08** [comment]
I'm unable to reproduce this, I used the following script:
```
<item:minecraft:gold_nugget>.definition.setJsonComponent(<componenttype:minecraft:rarity>, "uncommon");
<item:minecraft:gold_nugget>.modifyTooltip((stack, tooltip, context, flag) => {
    tooltip.insert(1, Component.literal("This is a new line"));
});
```
which gives:
![image](https://github.com/user-attachments/assets/d0562f9a-f99d-4095-8067-b2255abe936f)

Just a note that the script you provided is invalid, as `.getDefaultInstance()` does not exist on `IItemStack`, you want to replace that with `.definition` instead.
