### ISSUE TITLE
Recipe JSON File Only Working on Client Side, Server Throws "Unknown recipetype" Error

### ISSUE THREAD

**Issue by SunIAver** [CraftTweaker/CraftTweaker#1755]
### Issue description

I'm experiencing an issue where a recipe in JSON format for CraftTweaker is only working on the client side. When running the server, it throws the following error:

`error while running scripts: Crimson Decoded.zs:1:0: Unknown recipetype`

**_Details:_**
**Client Behavior**: The recipe works perfectly on the client.
**Server Behavior:** The server encounters the above error, and the recipe does not work.
Additional Information:

Testing: I tested the recipe by holding the item in my hand and using the command /ct recipes hand, which generated the log below.

### Script used

https://gist.github.com/KickOfSilver/2d808826313ad7d04b4ce5e2c408006e

### The crafttweaker.log file

https://gist.github.com/KickOfSilver/8ec2d215ae98a9144743d96c230a5182

### Minecraft version

1.20.1

### Modloader

Forge

### Modloader version

forge-1.20.1-47.3.5-installer.jar

### CraftTweaker version

CraftTweaker-forge-1.20.1-14.0.40.jar

### Other relevant information

appliedenergistics2-forge-15.2.11.jar
CraftTweaker-forge-1.20.1-14.0.40.jar
jei-1.20.1-forge-15.8.2.23.jar

### The latest.log file

https://gist.github.com/KickOfSilver/53833dc838d5574d83326b299eb60ab8

**Comment by jaredlll08** [comment]
Are you sure that you have applied energistics on the server?

Please provide a mod list and full debug.log file from the server

**Comment by SunIAver** [comment]
@jaredlll08 

[video ](https://youtu.be/qFh-LqUFCzI)
[debug.log](https://gist.github.com/KickOfSilver/5ca02f71674e1a1a5966a8529c945861)

**Comment by KickOfSilver** [comment]
using another method that they taught me on discord I was able to add

recipes.addJsonRecipe("fix_test_recipe",{
  "type": "ae2:inscriber",
  "ingredients": {
    "bottom": {
      "item": "ae2:printed_silicon"
    },
    "middle": {
      "item": "minecraft:diamond"
    },
    "top": {
      "item": "ae2:printed_calculation_processor"
    }
  },
  "mode": "press",
  "result": {
    "item": "ae2:calculation_processor"
  }
});

//https://docs.blamejared.com/1.20/en/mods/other_mods

**Comment by SunIAver** [comment]
using another method that they taught me on discord I was able to add

https://gist.github.com/KickOfSilver/ba07c987a2901fd8560769a95bf6d332

**Comment by jaredlll08** [comment]
This is an issue with AE2, you can read more about it here:
https://github.com/CraftTweaker/CraftTweaker/issues/1770#issuecomment-2456049288
