### ISSUE TITLE
Mixin Compatibility Issue

### ISSUE THREAD

**Issue by FCWYzzr** [CraftTweaker/CraftTweaker#1756]
### Issue description

I'm developing a mod using Mixin. Yet during testing, error occurred.
It seems like mixins applied to LivingEntity may crush the Crt

I've searched Issue list, yet no resolution was found. Should I apply some tweaks to my mod? Or it's none of my business?

### Steps to reproduce

using a mod which applies mixins to net.minecraft.world.entity.LivingEntity

### Script used

no script used

### The crafttweaker.log file

[pastebin Hw1RnZQQ](https://pastebin.com/Hw1RnZQQ)

### Minecraft version

1.21

### Modloader

NeoForge

### Modloader version

21.0.0-beta

### CraftTweaker version

20.0.20

### The latest.log file

[pastebin TCr45rQ8](https://pastebin.com/TCr45rQ8)

**Comment by jaredlll08** [comment]
Can I get a link to your mods source code please

**Comment by FCWYzzr** [comment]
[here](https://github.com/FCWYzzr/Food-Talks/tree/main)

**Comment by jaredlll08** [comment]
I've cloned your repository and tested both in dev and in production and I am unable to reproduce the error.

How are you testing?

**Comment by FCWYzzr** [comment]
weird, I refactor my code before push them.
yet the only change i applied to mixin class is, i take out the nested mixin class. it can not be the reason...
never mind, i ll just ingore it

**Comment by jaredlll08** [comment]
> i take out the nested mixin class. it can not be the reason...

That is exactly the reason, I have ran into this issue before here:
https://github.com/TeamLapen/Vampirism/issues/840

You aren't allowed to have non `@Mixin` classes in a mixin package, and the outer class is not a `@Mixin` class, so it ends up erroring.

**Comment by FCWYzzr** [comment]
> > i take out the nested mixin class. it can not be the reason...
> 
> That is exactly the reason, I have ran into this issue before here: [TeamLapen/Vampirism#840](https://github.com/TeamLapen/Vampirism/issues/840)
> 
> You aren't allowed to have non `@Mixin` classes in a mixin package, and the outer class is not a `@Mixin` class, so it ends up erroring.

well......thanks for your information
