### ISSUE TITLE
CraftTweaker not working on server, but works on singleplayer

### ISSUE THREAD

**Issue by Mysticpotato355** [CraftTweaker/CraftTweaker#1757]
### Issue description

I am able to have CraftTweaker work in my single player world, but for some reason it errors when put onto a server.

I even tried to remove the scripts and it still errors before loading any scripts.
The scripts work in singleplayer, so I am not entirely sure what is the issue.

### Steps to reproduce

Start Fabric server with CraftTweaker installed to cause error.

### Script used

https://gist.github.com/Mysticpotato355/dfb92b2de6974114ae63ed847ae3bea9

### The crafttweaker.log file

https://gist.github.com/Mysticpotato355/5976415c37bff959dd05eb8c3b8311ec

### Minecraft version

1.20.1

### Modloader

Fabric

### Modloader version

0.15.11

### CraftTweaker version

14.0.40

### The latest.log file

https://gist.github.com/Mysticpotato355/acf2465d6875ec9963fe19ebb1a8b515

**Comment by jaredlll08** [comment]
This is an issue with Sophisticated Core, there is more information here:
https://github.com/Salandora/SophisticatedCore/issues/3
