### ISSUE TITLE
Having difficulty removing recipes for HBM 

### ISSUE THREAD

**Issue by TravyParadox** [CraftTweaker/CraftTweaker#1760]
### Issue description

TLDR I'm making a Voltz like pack and I want to remove some of the more op items from HBM's crafting but I don't know where I went wrong.

### Script used

https://pastebin.com/YGXLxZMu

### The crafttweaker.log file

https://pastebin.com/0RsfXuxq

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

14.23.5.2860

### CraftTweaker version

4.1.20.700

### The latest.log file

https://gist.github.com/TravyParadox/2b877650b758f7a407378f427a7b710b

**Comment by jaredlll08** [comment]
You are missing a `;` on line 196

**Comment by TravyParadox** [comment]
> You are missing a `;` on line 196

Thank you, I love you it works
