### ISSUE TITLE
Issue with Botania Manasteel Helmet

### ISSUE THREAD

**Issue by TearfulBobcat66** [CraftTweaker/CraftTweaker#1766]
### Issue description

When i tried to change the recipe for the Manasteel helmet, crafttweaker couldn't combine iitemstack with iitemstack.

### Steps to reproduce

craftingTable.remove(<item:botania:manasteel_helmet>);

craftingTable.addShaped("manasteel_helmet1", <item:botania:manasteel_helmet>, [
    [<item:botania:manasteel_ingot>, <item:botania:manasteel_ingot>, <item:botania:manasteel_ingot>],
    [<item:botania:manasteel_ingot>, <item:botania:manaweave_helmet>, ]<item:botania:manasteel_ingot>,
    [<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);

### Script used

https://pastebin.com/26djaU9U - Line 714

### The crafttweaker.log file

https://pastebin.com/bCJJh3Ls

### Minecraft version

1.19

### Modloader

Forge

### Modloader version

43.4.2

### CraftTweaker version

10.1.55

### The latest.log file

Too big for pastebin

**Comment by jaredlll08** [comment]
on line 716, you placed the `]` in the wrong place, this script should work:
```zenscript
craftingTable.addShaped("manasteel_helmet1", <item:botania:manasteel_helmet>, [
    [<item:botania:manasteel_ingot>, <item:botania:manasteel_ingot>, <item:botania:manasteel_ingot>],
    [<item:botania:manasteel_ingot>, <item:botania:manaweave_helmet>, <item:botania:manasteel_ingot>],
    [<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);
```
