### ISSUE TITLE
Not registering AE2 recipetypes on Dedicated Server

### ISSUE THREAD

**Issue by AzrannAVANA** [CraftTweaker/CraftTweaker#1770]
### Issue description

When running scripts that touch to Applied Energistics 2's recipetypes like charging or transform on a dedicated server - CraftTweaker does not register them.
![image](https://github.com/user-attachments/assets/631f533d-ef65-4ddc-8435-95e24e670ef5)

### Steps to reproduce

Create any script involving AE's recipetypes
Run it on a dedicated 1.20.1 server
Observe missing recipetypes

### Script used

https://gist.github.com/AzuryxxVortex/816c62a1d85c867e48218e9d6e5ed4ab

### The crafttweaker.log file

https://gist.github.com/AzuryxxVortex/e75f70ebd72c228f8a9fb89b0624c454

### Minecraft version

1.20.1

### Modloader

Forge

### Modloader version

47.3.11

### CraftTweaker version

14.0.43

### The latest.log file

https://gist.github.com/AzuryxxVortex/648d8b1678b9cb80b9fd587e63d998c6

**Comment by jaredlll08** [comment]
This is an issue with AE2.

When this method of theirs is called:
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/forge/1.20.1/src/main/java/appeng/init/InitRecipeTypes.java#L23
the list that it iterates over is empty, so they end up not registering any of their types.

There is nothing that can be done to fix this on our side.
