### ISSUE TITLE
Add back '/ct reload' as its own separate command to save time

### ISSUE THREAD

**Issue by Catomax262** [CraftTweaker/CraftTweaker#1771]
### Describe the feature you'd like

Using the default '/reload' command makes it so it's pretty much a slower time reloading CraftTweaker scripts on large modpacks. On some modpacks, it may take up to 5 minutes to reload the world's mod datapacks.

### Describe alternatives you've considered

Make the '/reload' a separate entry.

### Minecraft version

1.19

### Modloader

Forge

**Comment by jaredlll08** [comment]
Unfortunately the way that we load scripts relies on the vanilla reload command to happen, otherwise recipes and tags are not reset.

The mods that cause it to take 5 minutes to reload should probably fix that...
