### ISSUE TITLE
Mod crash

### ISSUE THREAD

**Issue by tapoffers** [CraftTweaker/CraftTweaker#1772]
### Issue description

https://gist.github.com/tapoffers/f062634252cf00151425c80d98810b83

### Steps to reproduce

Occurs while server is trying to load up

### Script used

https://1drv.ms/u/s!AlG83QTffbrjhMACFK7rPda0LjXvsA?e=oagSiE

### The crafttweaker.log file

It's empty

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

forge-1.12.2-14.23.5.2860

### CraftTweaker version

CraftTweaker2-1.12-4.1.20.700

### The latest.log file

https://gist.github.com/tapoffers/ccf2f24a274626d03f701a13de8a8ae1

**Comment by jaredlll08** [comment]
This is an issue with either Gregtech or whatever mod adds CraftTweaker support for Gregtech.
