### ISSUE TITLE
global attribute modifications not working on fabric 1.21.1

### ISSUE THREAD

**Issue by ConqAra** [CraftTweaker/CraftTweaker#1779]
### Issue description

crafttweaker says its applying the global modifications in the script, but it doesn't look like it's working? no indication of the extra attributes applying to the gear like adding hp, atk speed, etc. I'm not getting any errors from the crafttweaker logs.
![image](https://github.com/user-attachments/assets/b92ea0be-7939-4dd7-ac5d-44989ca8ac77)
![image](https://github.com/user-attachments/assets/fe4680c1-6059-4f2f-9301-bca8b2ce1f2c)

### Script used

https://pastebin.com/tW31esDQ

### The crafttweaker.log file

https://paste.bot.blamejared.com/136877912698650625/1253211465645686824/1304729620729434165/message.txt#L3415

### Minecraft version

1.21.1

### Modloader

Fabric

### Modloader version

0.16.9

### CraftTweaker version

21.0.7

### Other relevant information

Only mods i used while testing/encountering the bug
![image](https://github.com/user-attachments/assets/21bbe58a-b2f7-41f9-8d2d-68878917f656)

### The latest.log file

https://pastebin.com/kWru68fX

**Comment by jaredlll08** [comment]
In 1.21 the attribute system moved to being component based, and I forgot to remove those methods, I'm sorry that you wasted time trying them out.

This is the new method https://docs.blamejared.com/1.21.1/en/vanilla/api/item/ItemDefinition#addAttributeModifier
and this is how you can use it
```zenscript
<item:minecraft:golden_sword>.definition.addAttributeModifier(<attribute:minecraft:generic.attack_speed>, AttributeModifier.create(<resource:minecraft:golden_sword>, -2, <constant:minecraft:attribute/operation:add_value>), <constant:minecraft:equipmentslot/group:mainhand>);
```


I will be removing those old methods shortly
