### ISSUE TITLE
Error while trying to remove assembler recipe in 1.12.2

### ISSUE THREAD

**Issue by ilov3gam3z** [CraftTweaker/CraftTweaker#1780]
### Issue description

I have been trying to remove/add recipes in a GTCEu modpack i am making. I have copied a good bit of code from NomifactoryCEu and after alot of troubleshooting i cant get findRecipe to work. I am trying to change the assembler crafting table recipe.

### Script used

https://pastebin.com/GfiWgJ47

### The crafttweaker.log file

https://pastebin.com/NUdpL1Sb

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

14.23.5.2859

### CraftTweaker version

CraftTweaker2-1.12-4.1.20.700.jar

### Other relevant information

Mod is running with a few other blocktweaker addons and a bunch of mods like GTCEu, IC2, Avaritia and most of the other mods you see in packs like Nomifactory and such.

### The latest.log file

Log is too long for pastebin. If required you could tell me what to paste, but i cant figure out exactly what rn.

**Comment by jaredlll08** [comment]
You're going to need to figure out which mod adds gregtech support and speak to their author to get help.

**Comment by ilov3gam3z** [comment]
??? GTCEu natively has gregtech support and CraftTweaker natively has support for GTCEu aswell.

**Comment by jaredlll08** [comment]
> CraftTweaker natively has support for GTCEu

No, we do not.

GTCEu may have native support for CraftTweaker, but we have absolutely no native support for them, I really cannot tell you what is wrong with your script, you need to speak to the authors of GTCEu and ask them what is wrong.
