### ISSUE TITLE
[Request] version request

### ISSUE THREAD

**Issue by DrowningFish233** [CraftTweaker/CraftTweaker#1785]
### Describe the feature you'd like

Can you add compatibility for 1.20.1 Neoforge? When I use the version CraftTweaker-forge-1.20.1-14.0.44.jar on 1.20.1 Neoforge, the hot reload function stops working. Other functions can operate normally.

### Minecraft version

1.20.1

### Modloader

NeoForge

**Comment by DrowningFish233** [comment]
Correction, the failure to reload is due to a mod conflict issue, and I am currently troubleshooting it.

**Comment by jaredlll08** [comment]
I can confirm that the latest CraftTweaker version for Forge works perfectly fine on 1.20.1 NeoForge, there is nothing for me to do and you have provided no logs so I can't even help you debug the unrelated mod conflict.

**Comment by DrowningFish233** [comment]
Yes, I understand. I'll let you know when I find out which mod is really causing this. Sorry for the disturbance.

**Comment by DrowningFish233** [comment]
@jaredlll08 I think I've identified which mod is causing the issue. Below is the method to reproduce it. 1. Install neoforge version 1.20.1 build 47.1.106 2. Install create-1.20.1-0.5.1.j 3. Install deepdrilling version 1.1.1+forge compatible with Minecraft forge version 1.20.1 4. Install CraftTweaker-forge-1.20.1-14.0.44 5. Enter the world 和 execute the command "/reload". I apologize for the disturbance, but I am not sure if this is an issue with CraftTweaker or Deep Drilling.

**Comment by jaredlll08** [comment]
Yea I'm going to say this is on them.
https://github.com/NotSoEpic/deepdrilling/issues/13

**Comment by DrowningFish233** [comment]
ok, I understand. Sorry for disturbing you.
