### ISSUE TITLE
CraftTweaker gives errors when importing, script does not run

### ISSUE THREAD

**Issue by jeremyfortytwo** [CraftTweaker/CraftTweaker#1787]
### Issue description

The script is intended to remove two recipes and add a new one. Despite showing no issues in VSCode, recipes are untouched.
Before the Import-Errors, I was given errors for the recipes which did not mention the imports at all.

### Steps to reproduce

- Create mc instance
- Install forge
- Add "Complicated crafting table", "CraftTweaker", "Just Enough Items (JEI)", and "Primitive Start"
- Import script
- Reload/Create and join a world

### Script used

https://gist.github.com/JustYourEverdayUser/561e127314d0aba172fae59962c31c95

### The crafttweaker.log file

https://pastebin.com/xDR6NYNb

### Minecraft version

1.20.1

### Modloader

Forge

### Modloader version

47.3.12

### CraftTweaker version

14.0.44

### Other relevant information

Originally done with a larger collection of mods (not a modpack) which I removed to see if that would solve the issue, which it did not. The logs are from that second, less inflated instance.
The launcher used is ATLauncher.
Complicated crafting table version is 1.2.0
JEI version is 15.20.0.105
Primitive Start version is 2.0.0

### The latest.log file

https://pastebin.com/KhaHNCBe

**Comment by jaredlll08** [comment]
You are using 1.12 syntax on 1.20.1.

Take a look at this page
https://docs.blamejared.com/1.20.1/en/tutorial/Recipes/Crafting/ShapedRecipes

**Comment by jeremyfortytwo** [comment]
Still giving red error over an issue with the import, but everything seems to be working now! Thank you ^^

**Comment by jaredlll08** [comment]
You are using a vscode plugin that only works on 1.12.2, 1.13+ was a major rewrite so no script from 1.12.2 will work out of the box.

**Comment by jeremyfortytwo** [comment]
I see. o.O Do you happen to know of any extensions for later versions?

**Comment by jaredlll08** [comment]
There is a list here
https://docs.blamejared.com/1.20.1/en/tutorial/Software#vscode-plugins

You are using the one by yesterday17.

Unfortunately none of the other plugins support syntax checking, they just do syntax highlighting, so it won't report errors.

**Comment by jeremyfortytwo** [comment]
Just found it. ._. I opened the wiki with a link from someone else, and it was auto-set to 1.12. I hadn't noticed until I compared it with yours. Thank you again :) I wasn't expecting such a quick response-time!
