### ISSUE TITLE
Crafttweaker + Ad Astra

### ISSUE THREAD

**Issue by Deimos1054** [CraftTweaker/CraftTweaker#1788]
### Describe the feature you'd like

Could it be possible to add the machines from Ad Astra into the crafttweaker recipes? like, so you can use the compressor, and other machines

### Describe alternatives you've considered

N/A (Havent came up with any...)

### Additional context

this is a request to add the Ad Astra as editable recipes... like how it is with, lets say, create... or other mods that work with CT...

### Minecraft version

1.20.1

### Modloader

Forge

**Comment by Deimos1054** [comment]
hope its understandable enough... am bad at communicating... lol...

**Comment by jaredlll08** [comment]
Mods don't need explicit CraftTweaker support if they use the vanilla datapack recipe system, which it appears that Ad-Astra does.

You can read more about that on this page https://docs.blamejared.com/1.20.1/en/mods/other_mods
and an example of how one of their recipes may look:

```zenscript
<recipetype:ad_astra:alloying>.addJsonRecipe("diamond_hoe_reusing", {
  "type": "ad_astra:alloying",
  "cookingtime": 100,
  "energy": 20,
  "ingredients": [
    {
      "item": "minecraft:iron_ingot"
    },
    {
      "tag": "minecraft:coals"
    }
  ],
  "result": {
    "count": 1,
    "id": "ad_astra:steel_ingot"
  }
}
);

```

You can find more of their recipes jsons here https://github.com/terrarium-earth/Ad-Astra/tree/1.20.x/common/src/main/generated/resources/data/ad_astra/recipes

**Comment by Deimos1054** [comment]
Thx
