### ISSUE TITLE
[Suggestion/Question] Custom Advancements

### ISSUE THREAD

**Issue by Skillotic0703** [CraftTweaker/CraftTweaker#256]
Are you going to add the ability to make custom advancements in 1.12?

**Comment by Astavie** [comment]
You can already do this in vanilla... Just look up a tutorial for custom advancements.

**Comment by codetaylor** [comment]
I would recommend using the mod Triumph. It allows you to fully manipulate advancements and is quite robust.

Here is a link:
https://minecraft.curseforge.com/projects/triumph

**Comment by cosmicdan** [comment]
> You can already do this in vanilla... Just look up a tutorial for custom advancements.

It's per-world, though. Unless I'm missing something it's not possible to do it in a modpack/resourcepack.

> I would recommend using the mod Triumph

Which is closed-source. An open-source alternative doesn't exist, apparently.

**Comment by jaredlll08** [comment]
Not going to be a thing in 1.12, could maybe be a thing in 1.14 but no promises. I also recommend you use triumph.
