### ISSUE TITLE
[1.12] v4.0.1 Players disconnected from server with 'Fatally missing blocks and items' error

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#277]
#### Issue Description:
After creating a valid crafttweaker zs recipe and restarting the server, when attempting to connect to the server, players are disconnected with a 'Fatally missing blocks and items' error. Mods being used include Actually Additions and Mystical Agriculture.

#### What happens:
I add the script to the scripts directory and restart the server. When I attempt to reconnect to the server, it kicks me out with "Fatally missing blocks and items".

#### What you expected to happen:
I expected to connect to the server successfully and see the new recipe in JEI / craft it.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/8eSgcAD6

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/c9GZZzRg

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- Forge: forge-1.12-14.21.1.2423-universal
- Crafttweaker: Crafttweaker2-1.12-4.0.1

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Are the scripts on the client?

**Comment by ghost** [comment]
Addendum: I tested it with the script on the client and was able to successfully connect to the server.

Is that going to be a requirement with 1.12, or is there a way to bypass that? Because it's going to be a bit awkward to push a pack update for every single script...

**Comment by jaredlll08** [comment]
No way to bypass that, sorry

**Comment by ghost** [comment]
Damn, alright. Thanks anyway.
