### ISSUE TITLE
MC 1.12 remove furnace recipe doesn't work properly

### ISSUE THREAD

**Issue by winnetrie83** [CraftTweaker/CraftTweaker#278]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:
recipe does not get removed entirely!

#### What you expected to happen:
recipe to be removed entirely

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/YHKLwPX2

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/D8BYGFbH

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- Forge: 14.21.1.2423
- Crafttweaker: CraftTweaker2-1.12-4.0.1

#### Your most recent log file where the issue was present: 
https://pastebin.com/R4i5NyP5

**Comment by jaredlll08** [comment]
Use the proper issue template.

**Comment by winnetrie83** [comment]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.


#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.


#### What happens:
recipe does not get removed entirely!



#### What you expected to happen:
recipe to be removed entirely



#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/YHKLwPX2


#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/D8BYGFbH


____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- Forge: 14.21.1.2423
- Crafttweaker: CraftTweaker2-1.12-4.0.1

#### Your most recent log file where the issue was present: 
https://pastebin.com/R4i5NyP5

**Comment by winnetrie83** [comment]
There you go

**Comment by winnetrie83** [comment]
I tried this: furnace.remove(<minecraft:iron_ingot>);
in the first place, yet you can still smelt iron grit into iron ingots in the furnace.
So my guess is that immersive engineering loads after crafttweaker.
EDIT:
When i try this: 
`furnace.remove(<minecraft:iron_ingot>, <immersiveengineering:metal:18>);`
I get this as message:
[WARNING] No furnace recipes for <minecraft:iron_ingot>
It doesn't recognize it for some reasons.
If i look at the code from IE they add the smelting recipe like this:
`FurnaceRecipes.instance().addSmeltingRecipe(new ItemStack(IEContent.itemMetal,1,18), new ItemStack(Items.IRON_INGOT), 0.7F);`
So i wonder why crafttweaker can't see it

**Comment by winnetrie83** [comment]
I can confirm that this only happens in MC 1.12. I just tested the same thing in MC 1.11.2 with crafttweaker and it works properly. I hope this helps you in any way. If not, just ask. Sorry for not filling in the template. I had not read it, i thought it was some advertisement stuff or something lol. So sorry about that!
