### ISSUE TITLE
not all of the items are given from the initial inventory script

### ISSUE THREAD

**Issue by Aaronstar-McClure** [CraftTweaker/CraftTweaker#279]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
i made a script for a starting inventory, but only the first entry is getting run. there is no crafttweaker.log in any folder.

#### What happens:
only the items for the first entry appear

#### What you expected to happen:

all the items to be spawned

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/ig9UeHSZ

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/pm2Hqq8Q
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.10.2
- Forge:12.18.3.2185
- Crafttweaker: 1.10.2-3.0.15

#### Your most recent log file where the issue was present: 

https://gist.github.com/Aaronstar-McClure/06495f15ed4265a6813ec8a8685d405c

**Comment by jaredlll08** [comment]
First of all, this is the wrong repo, you should use the initial inventory repo. 
Second of all, you crafttweaker is horribly outdated, update crafttweaker to the latest.
