### ISSUE TITLE
request for integration

### ISSUE THREAD

**Issue by kain184** [CraftTweaker/CraftTweaker#280]
hello i am not truly filing an issue. i am wondering if there is a way to get psi and blood magic integration somewhere. i have a mod pack where i need to edit some recipies and it would make it a lot easier

**Comment by kain184** [comment]
i have been trying but cannot get the blood magic altar to add or remove recipies the code i have been trying to use is mods.bloodmagic.Altar.addRecipe(<minecraft:prismarine_shard>, <bloodmagic:ItemBloodShard>, 5, 5000 ,20,20);

**Comment by jaredlll08** [comment]
Fill the form.

I have never played with PSI, but from what I've seen, there isn't really much for me to support
