### ISSUE TITLE
TechReborn Issue. 

### ISSUE THREAD

**Issue by FiberSprite** [CraftTweaker/CraftTweaker#281]
#### Issue Description:

Im currently trying to remove a recipe from the tech reborn rolling machine and the code will not initiate. I added the print around the code to see if it would do anything in the log and nothing appears besides the print around it. 

#### What happens:
The iron bars recipe won't remove it self using the code from the rolling machine

#### What you expected to happen:
The recipe for iron bars to be removed from the rolling machine

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
rollingMachine

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
http://wolfbrotech.com/admin/pastebin/view/0dff6326

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2422
- Crafttweaker: 1.10.2-3.0.26

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
1) That is not a pastebin to your script
2) We don't support TechReborn, they add support themselves. Report it to them.
