### ISSUE TITLE
CraftTweaker ThermalExpansion Issue

### ISSUE THREAD

**Issue by FiberSprite** [CraftTweaker/CraftTweaker#283]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Trying to add a recipe using http://crafttweaker.readthedocs.io/en/latest/Mods/Modtweaker/ThermalExpansion/InductionSmelter/ giving me a weird error.

#### What happens:
http://i.imgur.com/0IRHRqd.png
Gives me a error saying thermal expansion is not a real thing

#### What you expected to happen:
Add a recipe to the Induction Smelter on line 36

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/hN7K0esr

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/siQhvBAg

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge:12.8.3.2422
- Crafttweaker: 1.10.2-3.0.26

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
That wiki is only for 1.12 and it is modtweaker support.
Thermal Expansion doesn't have support in 1.10.2
