### ISSUE TITLE
[1.12] /ct recipes errors when used

### ISSUE THREAD

**Issue by Marioluigi7896** [CraftTweaker/CraftTweaker#285]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

Unable to dump all recipes to crafttweaker log
#### What happens:
Typing /ct recipes Gives an error message "An unknown error occurred while attempting to preform this action" while /ct recipes furnace works just fine

#### What you expected to happen:
It would put all the recipes in the game to the craft tweaker log

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://gist.github.com/Marioluigi7896/0136c9b40e8c3baf8c744ccbb7354af6

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/Marioluigi7896/a0a8a39ef350c3fa0d3c078202219ae7

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- Forge:  14.21.1.2426
- Crafttweaker: 1.12-4.0.1

#### Your most recent log file where the issue was present: 

https://gist.github.com/Marioluigi7896/31e7be7ffe0b1a99033bef9320ca76f7

**Comment by jaredlll08** [comment]
Fixed in dev
