### ISSUE TITLE
[1.11.2] /CTGUI 2 crashes built-in server, freezes client.

### ISSUE THREAD

**Issue by jonqrandom** [CraftTweaker/CraftTweaker#286]
#### Issue Description:
Attempting to use the command /CTGUI 2 in minecraft 1.11.2 causes the built-in server to crash ("ticking player" error) and the client to freeze, requiring forced termination. Used fresh install and world to test forge latest (2429) and stable (2386).

/CTGUI 1 works fine. In 1.12, /CTGUI 2 works fine.

#### What happens:
As above.

#### What you expected to happen:
I expected the CraftTweaker furnace GUI to open.

#### Script used
No script, just the command /CTGUI 2 .

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://hastebin.com/ajicexuxev.md (same for both versions of forge tested)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 13.20.1.2429, 13.20.1.2386
- Crafttweaker: 1.11.2-3.0.26

#### Your most recent log file where the issue was present: 

https://hastebin.com/econinobig (forge 2386)
https://hastebin.com/edapazudak (forge 2429)

**Comment by jaredlll08** [comment]
1.11.2 isn't supported anymore
