### ISSUE TITLE
Crashing trying to open vanilla crafting guide book.

### ISSUE THREAD

**Issue by Kinomora** [CraftTweaker/CraftTweaker#287]
#### Issue Description:
I am playing a custom modpack but have narrowed the issue down to crafttweaker with the help of a few others. We determined the issue is caused by removing the crafting recipe for an item and adding back in a custom one. This only causes a crash when trying to view the book in your inventory, sometimes at a vanilla crafting table, and at a TiCon crafting station with an inventory attached. I was able to get it to not crash at a vanilla crafting table after testing on a locally hosted server and swapping between SMP and SSP but I haven't figured out the right pattern yet.

#### What happens:
When opening the vanilla crafting guide, the pack crashes giving me a "Updating screen events" issue with this error: `java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: <snip>`

#### What you expected to happen:
Success in opening the crafting guide (I really don't care too much for it, I can totally just use JEI, but I keep accidentally clicking on it in my inventory/at a crafting table and relaunching the modpack is a hassle.)

#### Script used:
We have 3 scripts, but the one causing the issue is this one, and the specific issue is line 20/21
https://pastebin.com/YNjiBAuJ

#### Minetweaker.log file:
(I don't have a minetweaker.log, but I do have a craftweaker.log which looks like what you're looking for)
https://pastebin.com/2QnRinbk

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.0
- Forge: 14.21.1.2423
- Crafttweaker: 1.12-4.0.2

#### Your most recent log file where the issue was present: 
Crash report: https://pastebin.com/C46jnkC4
Log: (It's too long for pastebin or hatebin, here's the log.gz) http://s000.tinyupload.com/index.php?file_id=53378590193333226774
Server error when client crashes: https://pastebin.com/zGKQC5TJ (server does not crash)

**Comment by Kinomora** [comment]
We discussed this issue with TiCon already here: https://github.com/SlimeKnights/TinkersConstruct/issues/3080

**Comment by jaredlll08** [comment]
try this please
http://ci.blamejared.com/job/Crafttweaker-1.12/239/artifact/build/libs/CraftTweaker2-1.12-4.0.3.239.jar

**Comment by oitsjustjose** [comment]
That fixed it for us :)

**Comment by SkyBlade1978** [comment]
Hi Jared,

I was wondering if you could help, I'm removing a vanilla recipe in a mod I'm trying to fix up for 1.12 and am having the exact same bug when opening the crafting guide, I've tried moving the recipe removal to postinit but to no avail, if you could point me in the right direction it would be much appreciated..
