### ISSUE TITLE
Two kinds of scripts don't work in the latest Crafttweaker of 1.11.2

### ISSUE THREAD

**Issue by 5igm** [CraftTweaker/CraftTweaker#289]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:
Scripts:
furnace.setFuel(input, burnTime);
furnace.getFuel(item); 
Don't work in CraftTweaker-1.11.2-3.0.26.

I have tried the example offered from your wiki
furnace.setFuel(<minecraft:rotten_flesh>, 100);
But rotten_flesh still cannot be treated as a fuel.

#### What you expected to happen:
Let's these scripts work.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/MXYCgPxe

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/UY0ub80f

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: forge-1.11.2-13.20.1.2393
- Crafttweaker: CraftTweaker-1.11.2-3.0.26.

#### Your most recent log file where the issue was present: 
lastest.log
https://pastebin.com/iiwrhyhx

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Forge added code that made vanilla items fuel value unchangeable, nothing I can do. It has been fixed in 1.12
