### ISSUE TITLE
Unable to load into singleplayer world

### ISSUE THREAD

**Issue by Breadabix** [CraftTweaker/CraftTweaker#291]
This is in a modpack I am hoping to release at some point. I cannot load into a singleplayer world, logging into a server I have not been able to test. The game doesnt crash, just goes back to the menu screen.

This is a download for the scripts, there are quite a few and thought it would be easier to do this:
https://www.mediafire.com/file/ht41uwr9r76tzqd/scripts.rar

Minetweaker.log: https://pastebin.com/RFGnU7g0
____

- Minecraft: 1.7.10
- Forge: 10.13.4.1614
- Crafttweaker: 1.7.10-3.0.13
- ModTweaker: 2-0.9.6 (If this affects it)

fml-client-latest.log download: https://www.mediafire.com/file/aozs5d3a9q6e1ri/fml-client-latest.log
The file is too big for pastebin.

**Comment by Ommina** [comment]
"ERROR: Error loading Avaritia.zs: stanhebben.zenscript.parser.TokenException: Invalid character at null:112"

suggests that there is something amuck with your avaritia.zs file.  I'm not sure what the 112 represents (line, character, token?), but either way, it seems there's a character in there that shouldn't be.

**Comment by jaredlll08** [comment]
112 is the line, the null is a code bug that got fixed in later versions... Speaking of later versions... 1.7.10 is no longer supported

**Comment by Breadabix** [comment]
I have the latest version available for 1.7.10. I dont want to be rude, but this was no help at all. I had figured that it was something to do with that script, and I have checked through it and there isnt anything wrong with it. If I delete the last line of the script, line 112, it says the same error for line 111,and the same thing happens if I delete, for example, 40 lines.

**Comment by kindlich** [comment]
@Breadabix 
Reason why your script is not working is because every single line is commented out.
In Line1 you started a multiline comment with `/*` and then never closed it off (using `*/`)

You'll need to add ` */` as line 14.
I recommend you using a text editor other than windows notepad, as you can install syntax highlighting addons for these.

@jaredlll08 
Feature suggestion:
Add an error warning when a script ends before a multiline comment is closed

**Comment by jaredlll08** [comment]
well with all due respect:
1) scripts are not on pastebin / gist, you just said you knew which script it was, that is all I need, I don't want to download your scripts, that is dangerous for me to do as the rar file could contain anything and may even be a zipbomb. (gist can support multiple files and doesn't really care about full size much)
2) 1.7.10 isn't supported, it is 5 versions old now (not counting sub versions)
3) the later versions comment was regarding later MC versions, which the "null" part was fixed.

**Comment by Breadabix** [comment]
Thanks kindlich, Ill go through all of the scrips and check this. I dont understand why @jaredlll08 would stop supporting 1.7.10, as although it is old now, it is still a big part of the modding community.

**Comment by jaredlll08** [comment]
well, tell me, Microsoft XP is also old, but it is a huge part of Microsoft's legacy, yet they stopped support for it. I cannot support 5 versions at a time, and those are only major ones, lets count all the major-minor ones (that forge was on and that has mods released)
1) 1.7
2) 1.7.2
3) 1.7.10
4) 1.8
5) 1.8.8
6) 1.8.9
7) 1.9
8) 1.9.4
9) 1.10
10) 1.10.4
11) 1.11
12) 1.11.2
13) 1.12
14) 1.12.1

So you want me to support ALL 14 versions. Yea... NO dev is going to do that.
