### ISSUE TITLE
[Suggestion] Add String functions

### ISSUE THREAD

**Issue by nmarshall23** [CraftTweaker/CraftTweaker#292]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:

I would like to have several utility String functions. 
 * StartsWith 
 * Substring

Currently there is no length field on Strings, or I would write my own zenscript implementation.

I would use this to match an ingot with it's matching plate and ore. Then I can change the ratio of outputs in a machine. 

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:
- Forge:
- Crafttweaker: 

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Closed by PR #296
