### ISSUE TITLE
Client crash on start up due to Exception from crafttweaker for 1.12

### ISSUE THREAD

**Issue by Kryyss** [CraftTweaker/CraftTweaker#294]
#### What happens:
When attempting to start Minecraft the game crashes with an error report:

11:42:37 | game | UCH	minecraft{1.12} [Minecraft] (minecraft.jar)
11:42:37 | game | UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
11:42:37 | game | UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2387.jar)
11:42:37 | game | UCH	forge{14.21.1.2387} [Minecraft Forge] (forge-1.12-14.21.1.2387.jar)
11:42:37 | game | UCE	crafttweaker{4.0.2} [CraftTweaker2] (CraftTweaker2-1.12-4.0.2.jar)
11:42:37 | game | UCE	ctgui{1.0.0} [CT-GUI] (CraftTweaker2-1.12-4.0.2.jar)
11:42:37 | game | [10:42:37] [main/FATAL] [FML]: The following problems were captured during this phase
11:42:37 | game | [10:42:37] [main/ERROR] [FML]: Caught exception from crafttweaker (java.lang.NoClassDefFoundError: net/minecraftforge/event/furnace/FurnaceFuelBurnTimeEvent)
11:42:37 | game | [10:42:37] [Forge Version Check/INFO] [ForgeVersionCheck]: [forge] Found status: UP_TO_DATE Target: null

#### Affected Versions (Do *not* use "latest"):
- Minecraft: 1.12
- Forge: 1.12-14.21.1.2387
- Crafttweaker: both CraftTweaker2-1.12-4.0.3 and CraftTweaker2-1.12-4.0.2

**Comment by jaredlll08** [comment]
update forge.
