### ISSUE TITLE
[1.10.2] Crash when changing Seeds with Biomes o Plenty

### ISSUE THREAD

**Issue by Spazmunki13** [CraftTweaker/CraftTweaker#297]
#### Issue Description:
I removed the seed drops listed when using the /mt seeds command, and the game crashes with mentions of Biomes o Plenty.

#### What happens:
I load up a world, it generates for a bit and crashes.

#### What you expected to happen:
The world to load up and not crash.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/HscSj584

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/zRP22ghU

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2316
- Crafttweaker: 3.0.26

#### Your most recent log file where the issue was present: 

https://pastebin.com/B3Eyxqjn

**Comment by jaredlll08** [comment]
Forge issue that has been fixed in 1.11/1.12
