### ISSUE TITLE
[Suggestion for 1.13] Load scripts from datapacks

### ISSUE THREAD

**Issue by vico93** [CraftTweaker/CraftTweaker#298]
Well, seems like in 1.13 Data Packs [will be a thing](https://minecraft.gamepedia.com/1.13#General).

> Like resource packs but for servers or worlds. They have stuff like loot tables or advancements, instead of textures and clientside stuff.

![image](https://user-images.githubusercontent.com/3485505/29252151-47b9f0bc-8038-11e7-99de-35a9df609e43.png)

What about add support for load scripts from datapacks? For example, everything under craftweaker's namespace folder would be parsed (for example: `awesome_data_pack\scripts (or crafttweaker)\<scripts here>`)

It would be a great way to organize things on MC directory (both client and server), being in a more vanilla feel.

**Comment by kindlich** [comment]
Unfortunately, it won't be possible to load scripts received via DataPacks, as the recipe registry is frozen after PostInit.
It might however be possible to load scripts contained inside DataPacks serverside, if Forge 1.13 will allow the synchronization of the recipe registry from server to client

**Comment by jaredlll08** [comment]
this isn't something we are going to worry about right now as mojang is known to change their minds about things and 1.13 isn't released
