### ISSUE TITLE
[1.12]CTGUI Made Recipes not working v4.0.4

### ISSUE THREAD

**Issue by MokahTGS** [CraftTweaker/CraftTweaker#303]
I use the command /CTGUI 1 and get the nifty new GUI for editing recipes.  I removed the original recipe and then added a new one for the Project E philosopher's stone.  I saved and exited the game, reloaded and nothing has changed.  Do I need to do something more?

Here is the recipes.zs file text as made by the CTGUI command:  https://pastebin.com/hJmVtu8Q

**Comment by jaredlll08** [comment]
Use the template
