### ISSUE TITLE
[1.12] Feature request: new function to remove recipe by targeting the resource name

### ISSUE THREAD

**Issue by Lothrazar** [CraftTweaker/CraftTweaker#307]
#### Intro:
This is a feature request.  Please consider it, it would be useful for me and many users!  Or maybe the feature is already ! That would be cool, if so let me know

#### Issue Description:
As of 1.12 each recipe has a resource location ID.  I was thinking it could be very helpful to remove recipes by targeting that recipe id.  For example i will add a screenshot here, the recipe is conversions/emerald_to_diamond and the mod is 'projecte' 

So maybe a function like 

`recipes.removeTargeted('projecte:conversions/emerald_to_diamond');`

#### What happens:
Mod is fantastic! I know there are ways to do this by targeting input and output and things like that.

#### What you expected to happen:
I would love this extra feature! Please consider it

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
No script, this is a request.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- Forge:14.22.0.2459
- Crafttweaker: CraftTweaker2-1.12-4.0.4

#### Your most recent log file where the issue was present: 

No log, this is a feature request.
![recipe id](https://user-images.githubusercontent.com/621529/29491972-b04716a8-8521-11e7-90b0-1fd9bf0b33e9.PNG)

**Comment by kindlich** [comment]
http://crafttweaker.readthedocs.io/en/latest/Vanilla/Recipes/Recipes_Crafting_Table

Feature does already exist.
You can use one of the two:
```
recipes.removeByRegex("name[1-9]");
recipes.removeByRecipeName("name123");
```

**Comment by Lothrazar** [comment]
Oh awesome. thanks @kindlich  for info. i must have been on the super old wiki http://minetweaker3.powerofbytes.com/wiki/Main_Page
