### ISSUE TITLE
[1.12] Error for LAN Players "Fatally Missing Blocks or Items"

### ISSUE THREAD

**Issue by MokahTGS** [CraftTweaker/CraftTweaker#309]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:
When the host machine changes the recipes.zs file by adding a new recipe via the CTGUI 1 function, other players in a LAN environment cannot join the world due to an error saying "Fatally missing blocks or items."

Giving LAN players the updated version of the script file fixes this issue.

#### What you expected to happen:
Script files from the host machine should be propagated to any connecting machine.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- Forge: 2443
- Crafttweaker: 4.0.4

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Scripts need to be on both client and server, give the other client the script.

**Comment by phit** [comment]
@jaredlll08 thats not true, Lex fixed this in Forge 14.22.0.2456 https://github.com/MinecraftForge/MinecraftForge/commit/28e341002f7f338bb9cc490ef3a7270c7b9c99f6

@MokahTGS update your Forge version!

**Comment by MokahTGS** [comment]
So pretty sure forge 2443 is the latest for 1.12. 

If you mean update to 1. 12. 1 then that won't happen until more mods are there.

**Comment by phit** [comment]
99% of the mods that are on 1.12 work on 1.12.1, if you have a premade modpack you will have to wait, doubt Forge for 1.12 will get any more updates
