### ISSUE TITLE
[Question] Dynamic Item Names

### ISSUE THREAD

**Issue by Magi1053** [CraftTweaker/CraftTweaker#313]
So this is what I have so far
```
val metals = ["brass","bronze","coldiron","copper","cupronickel","electrum","gold","invar","iron","lead","mithril","nickel","platinum","silver","starsteel","steel","tin","zinc"] as string[];
for metal in metals {
	var item as IItemStack;
	val item = <"basemetals:"~metal~"_plate">;
}
```
I want to be able to remove all items for all my metal plates, and then redo the recipe for them using the same pattern, with their respective metal ingots.

**Comment by jaredlll08** [comment]
the issue tracker is for issues.

Questions go here:
https://discord.gg/CPpKYfV

**Comment by Magi1053** [comment]
Thanks for answering my question
