### ISSUE TITLE
[1.12.1] Crash on dedicated server startup with Doggy Talents and 4.0.4

### ISSUE THREAD

**Issue by b0bst3r** [CraftTweaker/CraftTweaker#315]
#### Issue Description:
Dedicated server crash on startup using Crafttweaker 4.0.4 and DoggyTalents 1.14.2.298, works fine with CT 4.0.3.  Reported to author of Doggy Talents first https://github.com/ProPercivalalb/DoggyTalents/issues/54

#### What happens:
Server crashes on startup

#### What you expected to happen:
Server not to crash on startup

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
N/A

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
N/A

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.1
- Forge: 1.12.1-14.22.0.2467
- Crafttweaker: 4.0.4

#### Your most recent log file where the issue was present: 

Crash Log - http://pastebin.ubuntu.com/25473086/

**Comment by jaredlll08** [comment]
This is an issue with doggy talents

**Comment by b0bst3r** [comment]
That's why I reported it there first, if you look at the linked issue they suggested I report it here.

**Comment by percivalalb** [comment]
Issue fixed, will be available when I release another version of DT. It was a simple fix that only took 5 mins just I hadn't had time to look at it.
