### ISSUE TITLE
[1.12.1] Client crash - Caused by: java.lang.NoClassDefFoundError: betterwithmods

### ISSUE THREAD

**Issue by ProsperCraft** [CraftTweaker/CraftTweaker#317]
#### Issue Description:
Client crashes on load.  Better with mods is a dependency?

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

No scripts

___
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.1
- Forge: 14.22.0.2474
- Crafttweaker: CraftTweaker2-1.12-4.0.5

#### Your most recent log file where the issue was present: 

https://gist.github.com/ProsperCraft/a2d11a83719e708f20346b3fd693a759

**Comment by jaredlll08** [comment]
Already fixed in dev. Read the issue sbefore making a new one. This was reported twice.
