### ISSUE TITLE
Minecraft 1.12.1 server crash

### ISSUE THREAD

**Issue by Realever** [CraftTweaker/CraftTweaker#319]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### What happens:
Minecraft server 1.12.1 crash on startup since i update your mod to CraftTweaker2-1.12-4.0.6 

#### What you expected to happen:
that the server run

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):i don´t know where the file is

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.1
- Forge:1.12.1-forge1.12.1-14.22.0.2474
- Crafttweaker: 4.0.6

#### Your most recent log file where the issue was present: 

pastbin: https://pastebin.com/6rzQNFcx

**Comment by Realever** [comment]
edit: i don´t know why but the client starts fine but only the server crash

**Comment by BloodWorkXGaming** [comment]
Try to update your malisis core and malisis blocks/doors mod, if it is on the latest build then please report back.

**Comment by BloodWorkXGaming** [comment]
Should have been resolved by this commit;
https://github.com/Ordinastie/MalisisCore/commit/8f46ca35feaf87babe0737ed1e46aa02abe24501

**Comment by Realever** [comment]
hi,
i have the latest version from malis core , malis doors and MalisisSwitches

**Comment by SalmonSays** [comment]
I came here to confirm, running the latest versions of Malisis Core/Blocks/Switches/Doors alongside CraftTweaker2 4.0.6 results in a server-side only crash for me.

Edit: Just tested to make sure, 4.0.4-4.0.6 all crash, 4.0.3 is the last version that still works alongside Malisis mods

**Comment by jaredlll08** [comment]
MalisisCore hasn't updated on curse to include the new code (their last update was the 6th of August while the commit was made on the 21st of August),
