### ISSUE TITLE
.reuse doesn't work

### ISSUE THREAD

**Issue by ulk-underscore** [CraftTweaker/CraftTweaker#321]
#### Issue Description/What happens:
Using the .reuse item transformer as described in the wiki doesn't add a recipe and instead throws an error.

#### What you expected to happen:
A crafting recipe for a golden apple that keeps the input apple.

#### [Minetweaker.log](https://pastebin.com/AApgKatD)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.1
- Forge: 14.22.0.2474
- Crafttweaker: 1.12-406

#### Your most recent log file where the issue was present: 

https://gist.github.com/ulkunderscore/58a8382788ef4354697581b95e434dc0

**Comment by jaredlll08** [comment]
`reuse` has been replaced with `giveBack` as they offer the same functionality

**Comment by OrdinatorStouff** [comment]
Please update documentation at https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Items/Item_Transformers/

it still lists "reuse" as a valid transformer
