### ISSUE TITLE
Client does not get a crafting recipe by joining

### ISSUE THREAD

**Issue by 0x4A-0x41-0x4B** [CraftTweaker/CraftTweaker#324]
I made a server with Crafttweaker and the mods i listed below. The problem is whenever a player joins he dont get the the recipe he first must do /mt reload but i have PermissionsEX on the server and i don't know to give a member the permission to do that. The other problem is that i become a huge ERROR message when i do /mt reload (btw i have OP).

Can you say me what the name of the permission is and how to fix the ERROR in the chat? Or please help me to find the problem that players can join and don't "auto" uses  /mt reload

Script: https://pastebin.com/fwLJayDW

1.7.10
Forge Version: 10.13.4.1614
CraftTweaker-1.7.10-3.0.13.jar
and MineTweaker2 is also in the server and client : ModTweaker2-0.9.6.jar

LOG: https://pastebin.com/gCnLeTk3

**Comment by jaredlll08** [comment]
1.7.10 isn't supported
