### ISSUE TITLE
Better with mods anvil script not working

### ISSUE THREAD

**Issue by TadeasSvetlik** [CraftTweaker/CraftTweaker#325]
#### Issue Description:
Hello
Im trying to modifie recipes in Better with mods Soulforged Steel Anvil using scripts from CraftTweaker wiki and it doesnt load saying "No such member: Anvil"

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/tN6qvTYJ

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/6taCcfsR

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 1.11.2-13.20.1.2454
- Crafttweaker: 1.11.2-7.1.9

**Comment by jaredlll08** [comment]
Wrong repo.

You need Modtweaker.

**Comment by TadeasSvetlik** [comment]
I have Modtweaker (version 3.0.2) and im already using scripts Saw from BWM, only issue from what i have found is Anvil

**Comment by jaredlll08** [comment]
You are still on the wrong repo.

**Comment by TadeasSvetlik** [comment]
Im sorry so i should report it to Modtweaker issues?

**Comment by jaredlll08** [comment]
yes...
