### ISSUE TITLE
[Feature] Integration between CTGUI and JEI

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#326]
#### Intro:
I very much like the new CTGUI feature, but it is somewhat limited. Would it be possible to add integration with JEI?

#### Issue Description:
I was thinking along these lines:
When looking up a recipe in JEI, add a button or key to populate that recipe into the CTGUI.
Also add the ability to remove recipes by name with this.
I do think this should be toggle-able with a config-option to make sure end-users cannot mis/ab-use this.

**Comment by jaredlll08** [comment]
@mezz is it even possible to do something like this? adding a button to all recipe wrappers (without me having to wrap a recipe wrapper)?

**Comment by mezz** [comment]
The stuff JEI is displaying is just data based on the original recipe, there's no guarantee that you can get the original recipe data from any of the wrappers. There is `ICraftingRecipeWrapper#getRegistryName` which is used for the advanced tooltips to show the recipe registry name, but I'm not sure how you could hook into that automatically.

**Comment by jaredlll08** [comment]
as mezz said, there isn't exactly a safe way to do this. sorry.
