### ISSUE TITLE
[Question/Request] Keep an ingredient in the crafting table after crafting

### ISSUE THREAD

**Issue by MysticAura** [CraftTweaker/CraftTweaker#327]
#### Intro:
Wasn't there recipe function which kept an ingredient in the crafting table after applying damage to it for each use? 
I thought that's what reuse did.

#### Issue Description:
My question is:
Is there a way to keep an ingredient in the crafting table after use?

#### What happens:
I guess my confusion is. default behavior without using any added functions, uses up the ingredients and returns the result; giveBack or transformDamage return the result and the specified item to the player. 

#### What you expected to happen:
Couldn't reuse to allow us to ...reuse an ingredient in the recipe without it being returned?
Format Example:

`item.transformDamage().reuse()`

Without reuse the ingredient would return to the player (as it currently does). With reuse it'd stay put after applying the damage.

**Comment by jaredlll08** [comment]
That caused an unfixable dupe bug, so I had to change how it worked.
