### ISSUE TITLE
[Documentation] Found a minor mistake in the Crafttweaker Documentation

### ISSUE THREAD

**Issue by Quarris** [CraftTweaker/CraftTweaker#328]
#### Intro:
Writing some scripts with the help of the documentation and came across this.

#### Issue Description:
Within the `Empowerer` page the actual title states `Atomic Reconstructor`.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): N/A

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: N/A
- Forge: N/A
- Crafttweaker:  N/A

#### Your most recent log file where the issue was present: I guess I'll post the link here.
http://crafttweaker.readthedocs.io/en/latest/#Mods/Modtweaker/ActuallyAdditions/Empowerer/

**Comment by kindlich** [comment]
https://github.com/jaredlll08/CraftTweaker-Documentation/issues/15

Will be fixed as soon as I PR, but I need to change some things before I can PR ^^
Please report issues regarding the wiki on the wiki github issue tracker.

I believe this can be closed ^^

**Comment by Quarris** [comment]
Sorry, I didn't realise the Documentation had its own github. My bad
