### ISSUE TITLE
CTGUI Recipe Issues

### ISSUE THREAD

**Issue by Boolyman** [CraftTweaker/CraftTweaker#333]
1.12.1
Furnace recipes input using CTGUI 2 aren't working.  I input recipe, reload game, recipe doesn't work.  Syntax looks fine, especially since it was put in by CTGUI 2.

Also, how are we supposed to designate an oreDictionary item in the CTGUI 1 interface, the checkboxxes at the left of the screen seem to just be cosmetic, and don't actually let you check them.

**Comment by jaredlll08** [comment]
Use the issue template.

**Comment by Boolyman** [comment]
You couldn't even answer my question about the ore Dictionary? Your template doesn't even have the option for questions to be asked.

**Comment by jaredlll08** [comment]
Well don't try and combine 2 issues / questions into a single issue...

**Comment by Boolyman** [comment]
LOL... whatever dude, ill look elsewhere for assistance.
