### ISSUE TITLE
[Issue] Removing specified Shaped Recipes remove every recipe of that item

### ISSUE THREAD

**Issue by Quarris** [CraftTweaker/CraftTweaker#335]
#### Issue Description:
I'm trying to remove certain shaped recipe from the game. 

#### What happens:
I've tried many methods including using `removeShaped` with wildcards and without, `removeByRecipeName` and I even tried /CTGUI 1 all seperately and everytime it removes every single recipes of that item instead of the one I specify.
Link to a screenshot of the /CTGUI 1 that I used.
http://prntscr.com/gp5g8r

#### What you expected to happen:
Remove the recipe of an item with the inputs I specified.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://gist.github.com/Quarris/7378456973f5e677f633ac8c0d531aa2

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/Quarris/ac5ab6506fe052c3b150e2e3e6011ab1

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.1
- Forge: 14.22.0.2474
- Crafttweaker: 1.12-4.0.7

#### Your most recent log file where the issue was present: 
https://gist.github.com/Quarris/d6e71decb2a0ce8c72fdbabc55108f45
[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
I'm surprised that this fell through the cracks for this long. Thanks!

**Comment by Quarris** [comment]
No worries. You might hear from me for a while since Im working on a pack and might have more issues. I assume that the fix will be available in the next version of the mod.

**Comment by Quarris** [comment]
I've updated to the newest version of ct (4.0.8) and now instead of the shaped recipes removing all recipes it doesn't remove any recipes at all. Here is the script and the log: https://gist.github.com/Quarris/b1002f2324dca6e0378eb976e2be7214
I'm not sure if either I'm doing something wrong with it, or if its still not fully fixed.

**Comment by QuantumStatement** [comment]
Looks like this issue is still exist in Crafttweaker

Minecraft: 1.12.2
Forge: 14.23.4.2705
Crafttweaker: 4.1.8

[Recipe Script](https://gist.github.com/QuantumStatement/b59cd81494acc399cd5ae263e4910efa)
[Crafttweaker.log](https://gist.github.com/QuantumStatement/cc650805d88abc82be6abda03f8543c6)
[Latest log](https://gist.github.com/QuantumStatement/57ed7aaf6a113dccac7e305a6ac8dc32)
