### ISSUE TITLE
Problems with Illegal Classes

### ISSUE THREAD

**Issue by Chenjox** [CraftTweaker/CraftTweaker#336]
#### Intro:
I'm trying to make a modpack with a progression line and started with the machine casings

#### Issue Description:
I made the script, syntax-checked it (said it was okay), and started up.

#### What happens:
I get this line in the chat upon opening a world:
ERROR: [crafttweaker]: Error executing {[0:crafttweaker]:CasingLine.zs}: Illegal class name ".CasingLine" in class file /CasingLine.zs

#### What you expected to happen:
Well, I thought using a function would reduce the amount of lines I have to take care of.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/N3BrYxq3

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/BgPPEqxS

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.0.2486
- Crafttweaker: Crafttweaker2-1.12-4.0.7

#### Your most recent log file where the issue was present: 
https://pastebin.com/LGQyHUG1

Thank you in advance
-Chenjox

**Comment by kindlich** [comment]
Will be fixed as soon as #337 is merged
