### ISSUE TITLE
CT 4.0.7 does not work with server.

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#338]
1.12.2, forge 2489

My script:

recipes.remove(<<mekanism:anchorupgrade>>);
recipes.remove(<<opencomputers:upgrade:4>>);

It works in the singleplayer. On the server recipe not removed. No errors in the console. Players in the JEI still see "removed" recipes.

CT log:

[INITIALIZATION][SERVER][INFO] CraftTweaker: Building registry
[INITIALIZATION][SERVER][INFO] CraftTweaker: Successfully built item registry
[INITIALIZATION][SERVER][INFO] Loading scripts
[INITIALIZATION][SERVER][INFO] [crafttweaker]: Loading Script: {[0:crafttweaker]: recipes.zs}
[POSTINITIALIZATION][SERVER][INFO] Removing all recipes for <mekanism:anchorupgrade>
[POSTINITIALIZATION][SERVER][INFO] Removing all recipes for <opencomputers:upgrade:4>

**Comment by kindlich** [comment]
Please use the issue template

**Comment by ghost** [comment]
LOL

**Comment by jaredlll08** [comment]
Yea? I went out of my way to make an issue template to help you quickly. And you go out of your way to just delete it. Don't complain about us closing your issue when you just delete the questions asking you for the info we need.

**Comment by ghost** [comment]
All info was inside the issue.

**Comment by jaredlll08** [comment]
In a hard to read format, the issue template we have helps us figure the issue out.

**Comment by ghost** [comment]
ok ok
