### ISSUE TITLE
SCripts Not Being Called or Loaded in 1.10.2 3.0.26 Version of Craft Tweaker

### ISSUE THREAD

**Issue by ThelianTech** [CraftTweaker/CraftTweaker#340]
#### Intro:
Hi Im a Small Time Modpack Dev working on my latest 1.10.2 Modpack 

#### Issue Description:
Not sure if I am having script errors or of the Mod is not recognizing that I have scripts in my scripts folder in the instance scripts folder.

#### What happens:
Builds item Registry and does not call on any scripts in folder to be loaded in.

#### What you expected to happen:
it should be calling up the scripts before FML goes to the next mod in the loading process.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): https://pastebin.com/rfsmWiJf

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.8.3.2488
- Crafttweaker: 3.0.26

#### Your most recent log file where the issue was present: 
 https://pastebin.com/dH1jV9yN

**Comment by jaredlll08** [comment]
docs.blamejared.com
http://minetweaker3.powerofbytes.com/wiki/Main_Page

**Comment by ThelianTech** [comment]
so its a scripting error from my coding then?

**Comment by jaredlll08** [comment]
well I don't even know if you scripts are even a .zs file or in the right place.

**Comment by ThelianTech** [comment]
its alright I figured out my problem it was a barackets issue.
