### ISSUE TITLE
1.10.2 Shapeless recipe parsing error

### ISSUE THREAD

**Issue by NightW0lf93** [CraftTweaker/CraftTweaker#341]
#### Issue Description:

Trying to get some shapeless scripts to work, I followed the wiki point to point, and the parsing error I get confuses me. I only had one ) and a ; at the end to begin with.

#### What happens:

Parsing error of the scripts

#### What you expected to happen:

Working scripts

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

Two different scripts https://pastebin.com/QWvX9eg6

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/k299JKc9
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2488
- Crafttweaker: 1.10.2-3.0.26

#### Your most recent log file where the issue was present: 

https://pastebin.com/47rfAjNP

**Comment by jaredlll08** [comment]
your lines need to end with ";"
and you are missing your angled brackets `< and >`

**Comment by NightW0lf93** [comment]
Alright, thank you!
