### ISSUE TITLE
Recipe with multiple outputs of the same item isn't working

### ISSUE THREAD

**Issue by NightW0lf93** [CraftTweaker/CraftTweaker#342]
#### Issue Description:
I must be an idiot or something...
For the past few days I've been trying to create a recipe that would let me convert Magma Blocks to Magma Creams, and Vector plates to a previous speed tier, i.e Extreme to Fast, but have been unable to thus far.
What am I doing wrong?
Also, sorry if I'm wasting your time...

#### What happens:

Scripts aren't working.

#### What you expected to happen:

Scripts to work.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

Lines 7-10 are variations I tried https://pastebin.com/7rV9FCve
Lines 10-17 are variations I tried https://pastebin.com/wzG6x3At

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/NyeJrqN7
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2488
- Crafttweaker: 3.0.26

#### Your most recent log file where the issue was present: 

https://pastebin.com/RZGPikcd

**Comment by jaredlll08** [comment]
Please read the wiki correctly
http://minetweaker3.powerofbytes.com/wiki/Tutorial:Basic_Recipes

The problem is that you are not using an array

**Comment by NightW0lf93** [comment]
It worked!
Thank you so much!!!
