### ISSUE TITLE
Help with error

### ISSUE THREAD

**Issue by Sixdd6** [CraftTweaker/CraftTweaker#343]
#### Issue Description:
I've assigned an array and am trying to iterate through it to print an array of block ids.

#### What happens:
I get an error in the log and it does not print.

#### What you expected to happen:
I expected it to print the array to the log.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): https://pastebin.com/E3fBDEyq

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.0.2491
- Crafttweaker: 4.0.7

#### Your most recent log file where the issue was present: 

Which log goes here exactly?
[fml_client_latest](https://gist.github.com/Sixdd6/e9ae511b7b9ce7540b5d1e8bc7cb1bc3)

**Comment by jaredlll08** [comment]
You need to define what the array is.

**Comment by Sixdd6** [comment]
wow I feel dumb now, thank you
