### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by leytilera** [CraftTweaker/CraftTweaker#345]
#### Issue Description:
My server crashes with crafttweaker.

#### What happens:
My server crashes with crafttweaker and the crashlog says, that crafttweaker errored.

#### What you expected to happen:
The server should run.

#### Scripts
https://gist.github.com/MineProjectZ/e30ae6ce466e0fbc0153392c307defc9

#### Minetweaker.log file 
https://pastebin.com/US7ZM1Jx

____
#### Affected Versions
- Minecraft: 1.7.10
- Forge: 1614
- Crafttweaker: 3.0.13

#### Your most recent log file where the issue was present: 

crashreport: https://pastebin.com/PY1ufJ5J
latest log: https://pastebin.com/DYg7RT2i
forge server log: https://pastebin.com/zwJZXVNY

**Comment by jaredlll08** [comment]
1.7.10 is no longer supported
