### ISSUE TITLE
CTGUI recipe removal not working on specific recipe

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#351]
Issue Description:

Attempting to remove a chest recipe from Better With Mods doesn't work.
Note: CTGUI generated slabWood as the ore dictionary value when I wanted sidingWood. Attempting to change it to sidingWood manually results in the same effect

What happens:

Removed a chest recipe using CTGUI, Recipe still exists and all scripts following do not work

What you expected to happen:

CTGUI has the ability to choose between multiple oredict values, recipe is removed

Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/i0FPm2jN

Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/rUVfeuyt

Affected Versions (Do not use "latest"):

Minecraft: 1.12.2
Forge: 2512
Crafttweaker: 4.0.8
Your most recent log file where the issue was present:

https://pastebin.com/FyUKTYGh

**Comment by jaredlll08** [comment]
When CTGUI can't remove a recipe, it usually means that the recipe doesn't exist, recipe removal for me is working fine
