### ISSUE TITLE
CTGUI furnace recipe removal not working

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#352]
Issue Description:

Removing the furnace recipe for ceramics Porcelain Brick does not work

What happens:

Removing the furnace recipe for porcelain brick using CTGUI and it did not remove it

What you expected to happen:

Make a change using CTGUI and on next world load the recipes should be changed.

Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/W9FL41iH

Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/jRLj3jde

Affected Versions (Do not use "latest"):

Minecraft: 1.12.2
Forge: 2512
Crafttweaker: 4.0.8
Your most recent log file where the issue was present:

https://pastebin.com/GXe3vk7a

**Comment by jaredlll08** [comment]
I can't reproduce. make sure you have the right items
