### ISSUE TITLE
[1.12.2] Syntax error with Actually Additions

### ISSUE THREAD

**Issue by tjsd** [CraftTweaker/CraftTweaker#353]
#### Issue Description:
Actually Additions - Crusher  - Remove Recipe
This has the syntax mixed up, you are not able to remove recipes based on input, but you have to put in output you want to remove.

#### What happens:
`mods.actuallyadditions.Crusher.removeRecipe(<ore:oreGold>);`
That should remove gold from being able to be processed in the crusher but it does not work.
`mods.actuallyadditions.Crusher.removeRecipe(<immersiveengineering:metal:19>);`
You instead have to do like that and remove the specific dust output. oredict does not work either.

#### What you expected to happen:
I expect it to work with removal of input stack and support oredict.

#### Script used: 
The line is referenced under "what happens"

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2505
- Crafttweaker:  CraftTweaker2-1.12-4.0.8

**Comment by jaredlll08** [comment]
1) wrong repo
2) ore dictionary is for input only.

**Comment by tjsd** [comment]
![image](https://user-images.githubusercontent.com/7138125/31862661-cef9718e-b741-11e7-8520-cc4ad9344087.png)

That uses that example, also the ducumentation is on http://crafttweaker.readthedocs.io/en/latest/#Mods/Modtweaker/ActuallyAdditions/Crusher/

How can it be wrong repo? it says crafttweaker there

edit: ahh, I seeit its for modtweaker, want me to move the issue?
