### ISSUE TITLE
java.lang.NullPointerException?

### ISSUE THREAD

**Issue by Habeeb-M** [CraftTweaker/CraftTweaker#355]
**Issue Description:**
Playing with [these mods](https://imgur.com/a/ovOjI) in a test world

**What happens:**
When I load my script, it says in chat 'Error loading hatchet.zs: java.lang.NullPointerException'

**What you expected to happen:**
I expected it to work perfectly and let me craft a Tinkers' hatchet with a piece of flint, a piece of string, and a stick.

**Script used:**
https://pastebin.com/67Qt8eDa

**Minetweaker.log file:**
https://pastebin.com/6JcC7pkG

**Affected Versions:**

- Minecraft: 1.10.2
- Forge: 12.18.3.2511
- Crafttweaker: CraftTweaker-1.10.2-3.0.26 (1)

**Your most recent log file where the issue was present:** 
https://pastebin.com/AfT3SjVS

I used InfiniTiC to create string parts so I could make this hatchet. The hatchet part of the script is exaclty what it said in chat.

**Comment by jaredlll08** [comment]
1.10.2 isn't supported anymore.

**Comment by Habeeb-M** [comment]
But any ideas why it didn't work?

**Comment by jaredlll08** [comment]
you forgot a `;`
