### ISSUE TITLE
[1.12.2] Custom recipes not showing on client despite the scripts matching the server

### ISSUE THREAD

**Issue by Tencao** [CraftTweaker/CraftTweaker#356]
#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): https://paste.ee/r/gkn77

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.0.2512
- Crafttweaker: 1.12-4.0.8

#### Your most recent log file where the issue was present: 
https://paste.ee/r/YECbw

**Comment by jaredlll08** [comment]
server scripts and logs?

**Comment by Tencao** [comment]
Sorry, after looking into this closer on my own, I've found this was an error with something else on the server which I've since fixed, so going to close this issue as it's invalid
