### ISSUE TITLE
[1.12.2] [Question] Is there any way to do the following?

### ISSUE THREAD

**Issue by GazbonicAcid** [CraftTweaker/CraftTweaker#357]
MC: 1.12.2
Is there any way to do the following?

Also, if I only specified one tag on Y with .withTag would it work with any instance of Y with that tag regardless of the other nbt tags?

Replace every instance of item X as an ingredient in all recipes with item Y.withTag(...)

[CurseForge](https://minecraft.curseforge.com/projects/crafttweaker?comment=225)

**Comment by GazbonicAcid** [comment]
I need to be able to do this so that I can not just replace vanilla tools with tinker's in what players use,
but do so in other mod's crafting recipe's as well.

**Comment by jaredlll08** [comment]
1) Yes.

2) No
