### ISSUE TITLE
Recipe Functions don't Work (mismatched parameters error)/Documentation out of date

### ISSUE THREAD

**Issue by Timeslice42** [CraftTweaker/CraftTweaker#358]
I've spent some time trying to get recipe functions to work, and finally just gave up and tried the examples from the wiki. The examples do not work, with CT failing to recognize the anonymous functions as ZenTypeNative

Scripts: 
[scripts.zip](https://github.com/jaredlll08/CraftTweaker/files/1429325/scripts.zip)

#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.0.2515
- Crafttweaker: 1.12-4.0.8

#### Your most recent log file where the issue was present: 

CraftTweaker Log:  https://paste.ee/p/rlq2c
Forge Log: 
[latest.zip](https://github.com/jaredlll08/CraftTweaker/files/1429334/latest.zip)

**Comment by Timeslice42** [comment]
Without the recipe functions the examples work just fine.

**Comment by kindlich** [comment]
You'll need to also add a name for the Optionals to work...
ZS thing, dunno why but adding the name usually makes em work for me :wink:

**Comment by trienow** [comment]
What do you mean with adding a name? I'm not sure I understand...

**Comment by kindlich** [comment]
I mean that you should add a string as first parameter so `recipes.addShaped(out,ins,functionA, functionB)` becomes `recipes.addShaped(name,out,ins,functionA, functionB)`

**Comment by trienow** [comment]
Thanks

**Comment by Timeslice42** [comment]
What does naming a recipe allow you to do?

**Comment by jaredlll08** [comment]
naming a recipe was introduced in 1.12.2, to you, it has no use, just give it a random name that is unique to that recipe
