### ISSUE TITLE
Mekanism PRC recipe broken?

### ISSUE THREAD

**Issue by Quarris** [CraftTweaker/CraftTweaker#360]
#### Issue Description:
I added a recipe for a mekanism machine and it is acting weird. 
I post it in here instead of ModTweaker since the documentationo doesn't have it in ModTweaker part.

#### What happens:
After adding the recipe, it shows in JEI fine and as intended but when trying to put it in the machine it does not activate.

#### What you expected to happen:

The machine activate when the recipe has been put in.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

At the bottom.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

At the bottom.
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.1
- Forge: 14.22.1.2485
- Crafttweaker: 1.12 - 4.0.9

#### Your most recent log file where the issue was present: 

This links to the pictures, script and the ct log.
https://gist.github.com/Quarris/8fa8a521397a8eaac6e000d5854eb419

**Comment by jaredlll08** [comment]
We don't add mekanism support. Speak to them.
