### ISSUE TITLE
Renaming does not work with liteloader installed

### ISSUE THREAD

**Issue by tgstyle** [CraftTweaker/CraftTweaker#361]
#### Issue Description:
I have a renaming script that runs, but it only works if liteloader is removed.

#### What happens:
The script loads with no error. The items do not get renamed.

#### What you expected to happen:
Items get renamed. I am guessing this is happening because liteloader initializes after forge.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.0.2522
- Crafttweaker: 4.0.9

**Comment by jaredlll08** [comment]
nothing I can do, that is all on liteloaders side.
