### ISSUE TITLE
New Shaped Recipe Not Working

### ISSUE THREAD

**Issue by SamuelDancing** [CraftTweaker/CraftTweaker#362]
#### Intro:
i'm a pack dev and sometimes i just make a pack for fun and i tried CraftTweaker and it failed

#### Issue Description:
i'm trying to add an elytra recipe to minecraft but i get an error every time i open the world and when i look in JEI no recipe shows up for it

#### What happens:
elytra recipe doesn't show when i use JEI and i get this error message on world startup
![2017-11-02_15 54 42](https://user-images.githubusercontent.com/20360872/32352483-03213ebc-bfe7-11e7-838b-354dd3f129a4.png)

(In case you don't see it)
ERROR: [crafttweaker : SIDE_CLIENT]: Error parsing recipes.zs:1 -- ] expected

#### What you expected to happen:
i wanted the elytra recipe to be used and for it to appear in JEI

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/T7mGmtyz (Note: i used notepad to make this script)

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/jk6249JC

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.0.2515
- Crafttweaker: 4.09

#### Your most recent log file where the issue was present: 

https://pastebin.com/fTystsYg

**Comment by jaredlll08** [comment]
You are missing `,` between your input arrays
