### ISSUE TITLE
`.onlyWithTag()` - Returning null item.

### ISSUE THREAD

**Issue by FusionLord** [CraftTweaker/CraftTweaker#363]
`.onlyWithTag()` is not working in 1.10.2 or I am writing it incorrectly.

#### What happens:
Crafttweaker fails to add recipe when using the above method.

#### What you expected to happen:
Get a recipe that only check for a specific tag, ignoring other tags.

#### Script used:
https://pastebin.com/Q5MZbzax

#### Minetweaker.log file:
https://pastebin.com/UtUGX9JV

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: Clients: 12.18.3.2477 Server: 12.18.3.2511
- Crafttweaker: 3.0.26

#### Your most recent log file where the issue was present: 
https://pastebin.com/eXsfTxfu

**Comment by jaredlll08** [comment]
Not an issue with crafttweaker, 1.10.2 isn't supported anymore
