### ISSUE TITLE
Truncated class file error

### ISSUE THREAD

**Issue by SnowShock35** [CraftTweaker/CraftTweaker#364]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:

When loading up the world with the given script the script loads perfectly fine, however the print statements don't get printed to the log and chat presents me with the error below.

https://pastebin.com/WbgDzUZB

#### What happens:

I just told you? 

#### What you expected to happen:

For it to work and not break? 

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/KLcZjnjE

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/jxjDd8Z9

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.0.2521
- Crafttweaker: 4.0.9
- ModTweaker: 4.0.4
- MTLib: 3.0.1

#### Your most recent log file where the issue was present: 

https://pastebin.com/Ngb3MpAY

**Comment by jaredlll08** [comment]
you aren't casting the array
