### ISSUE TITLE
Can't Resolve Names For Vic's Modern Warfare Mod

### ISSUE THREAD

**Issue by TheQKnight** [CraftTweaker/CraftTweaker#365]
#### Issue Description:
I am using version 1.12.2 of CraftTweaker.

#### What happens:
 When i try to add or remove a recipe for an item from the mod Vic's Modern Warfare, it says it cannot resolve the name. Here is my script:

recipes.remove(<mw:transistor>);

This seems to happen for every item in this mod, but no other item in any other mods.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
Here's my log:
https://pastebin.com/dxwjV6pJ

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.0.2528
- Crafttweaker: 1.12-4.0.9

#### Your most recent log file where the issue was present: 

https://pastebin.com/dxwjV6pJ

**Comment by kindlich** [comment]
You need to use the [Item Bracket Handler](http://crafttweaker.readthedocs.io/en/latest/#Vanilla/Brackets/Bracket_Item/) for this:

`<mw:transistor>`

Just hold the item in your hand, use `/ct syntax` and then click on the name. It will copy a usable string into your clipboard, then go to your script and hit CTRL+V

**Comment by TheQKnight** [comment]
i think you meant /ct hand, but it still doesn't work. Please re open this issue. I've tried all the different types of syntax, but nothing works. it gave me <mw:diode> when i did /ct hand and /ct syntax just says the syntax is correct, nothing is wrong.

**Comment by jaredlll08** [comment]
It's not getting reopened, firstly you didn't use pastebin for your script,
and secondly, any issue like this is user error, or mod error, they may be
registering their items too late.

**Comment by TheQKnight** [comment]
am i supposed to use pastebin for a 1 line script lol?

**Comment by TheQKnight** [comment]
I even used the gui editor and it still gave an error
