### ISSUE TITLE
Crash while using /ctgui craftingtable

### ISSUE THREAD

**Issue by Steamoonkie** [CraftTweaker/CraftTweaker#366]
#### Issue Description:
I am using latest public version of CraftTweaker availible at Curse page. Also using ModTweaker, JEI,...
Game crashed while trying to use /ctgui craftingtable intended way.

#### What happens:
Game crashed when I tried to use /ctgui craftingtable and inputting "Enchanted Book" without any enchants into gui left center slot. Was using blank one book given by JEI. Placed it, that worked. Then I did try to right click there, game crashed.

#### What you expected to happen:
Expected to be availible to right click on book so its setting are copied on upper window with text of id's, NBT data's etc.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
Not used yet cause couldnt create one.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Building registry
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Successfully built item registry
[INITIALIZATION][CLIENT][INFO] Loading scripts
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: Test.zs}
[SERVER_STARTED][CLIENT][INFO] Fixed the RecipeBook

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: forge-14.23.0.2517
- Crafttweaker: 1.12 - 4.0.9 

#### Your most recent log file where the issue was present: 
https://pastebin.com/LF7twLgK

**Comment by jaredlll08** [comment]
![image](https://user-images.githubusercontent.com/5553605/32759683-623cf322-c8f3-11e7-8532-135039cbf195.png)
I can't reproduce...
