### ISSUE TITLE
[Question] [1.12.2] unknown recipe type for <ic2:forge_hammer> ???

### ISSUE THREAD

**Issue by Krougal** [CraftTweaker/CraftTweaker#369]
I realize IC2 support is not in Modtweaker currently, but I expected this to be a vanilla crafting recipe.
Just trying to do the "usual" replace sticks with crafted sticks in forge hammer recipe.
recipes.remove(<ic2:forge_hammer>);
recipes.addShaped(<ic2:forge_hammer>, [[<ore:ingotIron>, <ore:ingotIron>, null], [<ore:ingotIron>, <ore:treatedStick>, <ore:treatedStick>], [<ore:ingotIron>, <ore:ingotIron>, null]]);
recipes.addShaped(<ic2:forge_hammer>, [[null, <ore:ingotIron>, <ore:ingotIron>], [<ore:treatedStick>, <ore:treatedStick>, <ore:ingotIron>], [null, <ore:ingotIron>, <ore:ingotIron>]]);

Remove recipe works as expected. Add is not. Items are all valid, syntax correct, etc.

If I remove my script (so default IC2 recipe)
ct recipes hand outputs // unknown recipe type for <ic2:forge_hammer>

Anyone have any ideas? If I need to wait for IC2 support to go back into Modtweaker then that is fine, the only thing I can come up with is because the forge hammer is special the crafting recipe is special too.

**Comment by jaredlll08** [comment]
use the issue template.
