### ISSUE TITLE
Porting from 1.11 to 1.12

### ISSUE THREAD

**Issue by mcenderdragon** [CraftTweaker/CraftTweaker#370]
I added Minetweaker/crafttweaker support  to my mod in 1.11. But now in 1.12 alot of methods are gone and all classes have been renamed at first why?, Is there any big reason or just because of old name -> new name? And also back in 1.11 I used minetweaker.MineTweakerAPI#registerClassRegistry(String) to regsiter everything... what has happend with this method and how do I fix this ?

**Comment by jaredlll08** [comment]
1) The api changed, the old api was semi based on reloading, which is no longer a thing, so big changes had to be made.

you can use @ZenRegister to automatically register the class.

Take a look at existing examples :)
https://github.com/jaredlll08/ModTweaker/blob/1.12/src/main/java/com/blamejared/compat/actuallyaddition/AtomicReconstructor.java

**Comment by mcenderdragon** [comment]
SO @ZenRegister works alot like @Mod or @JEIPlugin ?

**Comment by jaredlll08** [comment]
yes
