### ISSUE TITLE
Recipes don't work and don't show in JEI

### ISSUE THREAD

**Issue by Davoleo** [CraftTweaker/CraftTweaker#371]
#### Issue Description:
the issue is just that some recipes I wrote don't show up in jei and they don't work too

#### What happens:
some recipes I wrote don't show up in jei and they don't work too

#### What you expected to happen:
I expected recipe to work... 

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/X7Nu4gHZ

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/5KrFBz9v

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.0.2531
- Crafttweaker: 1.12 - 4.0.9

#### Your most recent log file where the issue was present: 
There isn't a log file where you can see the issue

**Comment by jaredlll08** [comment]
That can't be your full log, it is missing too much stuff

**Comment by Davoleo** [comment]
yeah, I don't know why, it was like that before restarting another time... now it has given me this log
https://pastebin.com/7846Qntq
it seems it stops working just while loading a certain recipe :/
@jaredlll08

**Comment by Davoleo** [comment]
So, is this going to be fixed in the next version? 
Or did I do something wrong in posting the issue?
