### ISSUE TITLE
Mekanism Smelter AddRecipe not adding recipe

### ISSUE THREAD

**Issue by lomira** [CraftTweaker/CraftTweaker#372]
Hello ! 

#### Issue Description:
FYI, I'm using the "All the mod 3" for minecraft 1.12, but probably unrelated.

I want to add receipes to mekanism : 
1. Crusher : red floxer > green dye 
2. Smelter : stone > wool 

#### What happens:
The one for the crusher works.
The one for the smelter doesnt.

#### What you expected to happen:
Both should work :)

#### Script used 
[https://pastebin.com/vFutFVw9](https://pastebin.com/vFutFVw9)

#### Minetweaker.log file : Look for "Niclomag" to get in the right place
[https://pastebin.com/iELZLAUK](https://pastebin.com/iELZLAUK)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.0.2531
- Crafttweaker: 1.12-4.0.9

#### Your most recent log file where the issue was present: 
[https://drive.google.com/file/d/1noj5nP6H7De3HKF0iLX78x_BsBkXCZwh/view?usp=sharing](https://drive.google.com/file/d/1noj5nP6H7De3HKF0iLX78x_BsBkXCZwh/view?usp=sharing)

**Comment by kindlich** [comment]
Please try the same methods with only the necessary script files (i.e. remove all scripts but the one that is erroring)

Also, Neither Craft- nor ModTweaker adds mekanism support, that is implemented by mekanism itself, so if the issue persists, you could try [opening an issue there or check if one already exists](https://github.com/aidancbrady/Mekanism/issues)

**Comment by jaredlll08** [comment]
As kindlich said, we don't support mekanism

**Comment by lomira** [comment]
Ok. Quick suggestion then : adding [obsolete/no direct support] or something to the [CT wiki](http://crafttweaker.readthedocs.io/en/latest/#Mods/Mekanism/Chemical_Crystallizer/) on mekanism to make it clear.

Have a good day !

**Comment by jaredlll08** [comment]
Well the way the wiki is done is like this:

Anything in the "mods" section is stuff that isn't native to Crafttweaker, support is added in other mods.
Meaning you should report it to them.
