### ISSUE TITLE
Scripts not loading

### ISSUE THREAD

**Issue by iamcarrotmaster** [CraftTweaker/CraftTweaker#373]
#### Issue Description:
My scripts i am making arent loading, they're not wrong because i check on the wiki and i am using MTRM to write them.

#### What happens:
I do the recipe, click ok, then i check with jei and the recipe doesnt work, it used to.

#### What you expected to happen:
I expect it to load the recipe.

#### Script used
[MineTweakerRecipeMaker.txt]
(https://github.com/jaredlll08/CraftTweaker/files/1472795/MineTweakerRecipeMaker.txt)

#### Minetweaker.log file 
[minetweaker.log]
(https://github.com/jaredlll08/CraftTweaker/files/1472799/minetweaker.log)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.10.2
- Forge:12.18.
- Crafttweaker:3.0.26.3.2185

#### Your most recent log file where the issue was present: 
[latest.log]
(https://github.com/jaredlll08/CraftTweaker/files/1472803/latest.log)

**Comment by jaredlll08** [comment]
1.10.2 isn't supported

Your scripts are being loaded fine according to the log.

**Comment by iamcarrotmaster** [comment]
thats why i was confused

**Comment by iamcarrotmaster** [comment]
ok turns out the problem was with jei not showing it the crafting works, sorry for wasting your time
