### ISSUE TITLE
Truncated class file error with Array

### ISSUE THREAD

**Issue by The-Arcanian** [CraftTweaker/CraftTweaker#374]
#### Issue Description:
Trying to create an array for a loop in a script and CraftTweaker gives a "Truncated class file" error.

#### What happens:
CraftTweaker gives a "Truncated class file" error.

#### What you expected to happen:
To not get an error.

#### Script used:
https://gist.github.com/The-Arcanian/ed6de20733786d8e64fc253243936427

#### Minetweaker.log file:
https://gist.github.com/The-Arcanian/23795d6ba6f9c9bc67b7cdd5f79c508f

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.0.2529
- Crafttweaker: 4.0.9

#### Your most recent log file where the issue was present: 
https://gist.github.com/The-Arcanian/91edc8467210ae08f4f63f68ef551e6d

**Comment by jaredlll08** [comment]
you are meant to cast it to "IOreDictEntry[]" on line 8

**Comment by The-Arcanian** [comment]
Ok, so the readthedocs is wrong. Its example said `var test = <ore:ingotIron> as IOreDictionary;`.
