### ISSUE TITLE
crafttweaker/api/oredict/IOreDictEntryAny error with Array

### ISSUE THREAD

**Issue by The-Arcanian** [CraftTweaker/CraftTweaker#375]
#### Issue Description:
Trying to create an array for a loop and CraftTweaker gives a "crafttweaker/api/oredict/IOreDictEntryAny" error.

#### What happens:
Crafttweaker gives a "crafttweaker/api/oredict/IOreDictEntryAny" error.

#### What you expected to happen:
To not get an error.

#### Script used:
https://gist.github.com/The-Arcanian/5ade03e16aa3e2be1549870b12cc46b4

#### Minetweaker.log file:
https://gist.github.com/The-Arcanian/23795d6ba6f9c9bc67b7cdd5f79c508f

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.0.2529
- Crafttweaker: 4.0.9

#### Your most recent log file where the issue was present: 
https://gist.github.com/The-Arcanian/91edc8467210ae08f4f63f68ef551e6d

**Comment by jaredlll08** [comment]
Yea... you got your scripts and logs mixed up anyway, I think that the comment on the other issue will fix this one as well

**Comment by The-Arcanian** [comment]
The first link is the script the second is the log. They just both happened in the same CT log. The third one may not have been necessary though... Maybe that is what you meant.

Linking the other issue for anyone the googles.
https://github.com/jaredlll08/CraftTweaker/issues/374
