### ISSUE TITLE
Suggestion Errors/Warnings to log only

### ISSUE THREAD

**Issue by tgstyle** [CraftTweaker/CraftTweaker#378]
Could they stop spamming the chat console and just put in informational line in chat that says -

Crafttweaker scripts errored click [Here] to open log
Crafttweaker scripts had warnings click [Here] to open log

or something on the likes of that?

**Comment by jaredlll08** [comment]
Nope, this will just encourage people leaving issues in, and with how much spam is in the chat from other mods, the message will most likely get lost.

**Comment by tgstyle** [comment]
How about as a config option ?

**Comment by jaredlll08** [comment]
Once again, my point stands, even with a Config option, it will still
happen.
Also crafttweaker doesn't have any Config options, and I don't plan on
adding any anytime soon
