### ISSUE TITLE
Failure to remove stone chisel recipe with blank NBT tag

### ISSUE THREAD

**Issue by gencydefen** [CraftTweaker/CraftTweaker#379]
#### Issue Description:
I am trying to use CraftTweaker to remove the stone chisel from Chisels and Bits.  I have read the documentation and I have written a variety of scripts to that end, none of which succeed in removing the recipe. I have also used the /CTGUI interface. Both my scripts and the CTGUI script files are included here. I have added the /ct syntax errors to those lines that produce them. I'm certain that the blank NBT is part of the problem but every variation I've tried has failed.
If this is a case of user error, I apologize in advance. I have found your mod incredibly useful and I very much appreciate your work and your time in reviewing this issue.

#### What happens:

The stone chisel recipe is not removed.

#### What you expected to happen:

The stone chisel recipe to be removed.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

[https://gist.github.com/gencydefen/2031e0e7bfdbc322c532c669088f98da](https://gist.github.com/gencydefen/2031e0e7bfdbc322c532c669088f98da)

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

[https://gist.github.com/gencydefen/b30b5a01e557d5f8a9aa12759a002764](https://gist.github.com/gencydefen/b30b5a01e557d5f8a9aa12759a002764)
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.0.2544
- Crafttweaker: 4.0.9

#### Your most recent log file where the issue was present: 

[https://gist.github.com/gencydefen/17443ea553e4ceee60830b1fbef1f581](https://gist.github.com/gencydefen/17443ea553e4ceee60830b1fbef1f581)

**Comment by jaredlll08** [comment]
Can you remove it via the name?

**Comment by gencydefen** [comment]
I did try both `recipes.removeByRecipeName("chisel_stone");` on line 27 of my script and in case the syntax was incorrect, `recipes.removeByRecipeName("chiselsandbits/chisel_stone");` on line 29. Both failed to remove the recipe.
Thank you for your response and attention to this issue.

**Comment by gencydefen** [comment]
Had a look at the Discord channel and it turns out that this
`recipes.removeByRecipeName("chiselsandbits:chisel_stone");`
removes the recipe. I was so close yet so far, but the seventeenth time was the charm. Closing this issue, thanks for your attention and work on this mod again.
