### ISSUE TITLE
Cannot remove Mekanism or Tinkers recipes from Furnace

### ISSUE THREAD

**Issue by tgstyle** [CraftTweaker/CraftTweaker#381]
#### Issue Description:
Script to remove ingots for these mods does nothing. I have even tried specifying the items manually instead of using the ore dictionary.

#### What happens:

Nothing, they do not even show up in the log (only the manual recipes do, and still don't work).

#### What you expected to happen:

Removal of the recipes from the furnace.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://gist.github.com/tgstyle/afadd80622af71e2e71b906cd93d386f

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://gist.github.com/tgstyle/1ce9d2a9f7c61a76c567c525270d1b06
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.0.2549
- Crafttweaker: 4.0.10

#### Your most recent log file where the issue was present: 

https://gist.github.com/tgstyle/4c0efc8b7246fc489f7a4601418ff71c

**Comment by jaredlll08** [comment]
can't reproduce.
tested with:
```
furnace.remove(<tconstruct:ingots:1>);
```

**Comment by tgstyle** [comment]
Did you try mekanism?

**Comment by tgstyle** [comment]
Also why wouldn't the ore dictionary work for tinkers?

**Comment by tgstyle** [comment]
Mekanism for lead and silver seems to register a random recipe for the dusts to another mods ingots since it has no ingots for those. I have tried every silver and lead ingot to get rid of them it to no avail.
