### ISSUE TITLE
[suggestion] Removal of brewing stand potion recipes

### ISSUE THREAD

**Issue by stohun01** [CraftTweaker/CraftTweaker#386]

**Comment by kindlich** [comment]
This is supported since the latest CT build!
Read the documentation here:
http://crafttwaeker-docu.readthedocs.io/en/latest/#Vanilla/Recipes/Recipes_Brewing_Stand/

Jei still shows them but they won't be brewable


EDIT: jared just told me it isn't released yet...

**Comment by Placid-Storm** [comment]
Will the brewing stand recipes work with 1.7.10? I was trying to use it for Ars Magica 2. I have witchery and refuse to update my server until Bewitchment is released to a playable version.

**Comment by kindlich** [comment]
1.7.10 is not supported any longer, so there won't be a backport.
Too much code has changed!
