### ISSUE TITLE
Request: add PneumaticCraft: Repressurized recipes to wiki

### ISSUE THREAD

**Issue by desht** [CraftTweaker/CraftTweaker#387]
Not a problem report, just a docs request...

PneumaticCraft: Repressurized (https://minecraft.curseforge.com/projects/pneumaticcraft-repressurized) now has native CraftTweaker support for several of its machines.  I wonder if you'd be able to add that information to the CraftTweaker wiki.

The recipes are currently documented at https://github.com/TeamPneumatic/pnc-repressurized/wiki, but it would be nice to have them in a central location at the official wiki on https://crafttweaker.readthedocs.io/, since I noticed a few other mods with native support are listed there.

Anyway please let me know if you need any more information.  Thanks in advance!

**Comment by jaredlll08** [comment]
The wiki actually has it's own repo https://github.com/jaredlll08/CraftTweaker-Documentation, so you could make a PR for your documentation :)

**Comment by desht** [comment]
Ah OK! I will do that :)
