### ISSUE TITLE
[Feature Request] Allow GameModes

### ISSUE THREAD

**Issue by KingDan27** [CraftTweaker/CraftTweaker#392]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:

Since ftbtweaks is dead for 1.12.2 is it possible to add a config option for normal and expert mode?

Expert mode would read from a different folder called say escripts for example and normal mode would read from scripts. Then pack makers can set a expert crafting mode and player/serverowners would be able to select which mode they want to play on by adjusting 1 config. This would allow the scripts to load before the game loads up and let us add extra modes to the pack.

Sorry if this has been requested already didn’t find the post. 
 

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:
- Forge:
- Crafttweaker: 

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by kindlich** [comment]
This is already a CT addon:
Read about it here:
http://crafttweaker.readthedocs.io/en/latest/#Mods/GameStages/GameStages/

**Comment by jaredlll08** [comment]
https://minecraft.curseforge.com/projects/packmode
