### ISSUE TITLE
[Suggestion] Recipes start unlocked when doLimitedCrafting is true

### ISSUE THREAD

**Issue by davqvist** [CraftTweaker/CraftTweaker#396]
#### Issue Description:
In my pack I want to use doLimitedCrafting but CT recipes are locked on creation and I want to have them unlocked by default.

#### What happens:
CT recipes start locked by default

#### What you expected to happen:
A config option or an optional parameter for scripts that changes this behaviour.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2561
- Crafttweaker: 4.0.10

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
we don't do anything special for this, like our recipes are added exactly the same as other mod recipes and "isHidden" returns false on our recipes, so I'm not sure how we can "fix" this
