### ISSUE TITLE
[1.12.2] Suggestion: Make Log Files Human Readable

### ISSUE THREAD

**Issue by Morpheus1101** [CraftTweaker/CraftTweaker#400]
The crafttweaker logfile is so difficult to navigate through since it prints each out in 1 big clump rather than a human readable format, is it possible to have each output on its own line by chance?

**Comment by jaredlll08** [comment]
screenshot of what the file looks like to you.

**Comment by Morpheus1101** [comment]
https://puu.sh/yKg1e/4304091b66.png

**Comment by Morpheus1101** [comment]
I forgot windows was using standard Win Notepad rather than Notepad++ for .log files

**Comment by jaredlll08** [comment]
Use a real text editor.
