### ISSUE TITLE
/ctgui 1 -> Invalid ID!

### ISSUE THREAD

**Issue by mainrs** [CraftTweaker/CraftTweaker#402]
#### Issue Description:
I am tryng to open the in-game GUI to create a custom recipe for the Fluid Transposer in TE. But neither `/ctgui 1` or `/ctgui 2` open any dialogue. The only response I get is a message in the console saying `Invalid ID!`.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
None.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.1.2566
- Crafttweaker: 4.0.10
- ModTweaker: 4.0.5

#### Your most recent log file where the issue was present: 
Checked logs, no error message in crafttweaker.log and latest.log.
[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Syntax changed, look at the wiki.

**Comment by mainrs** [comment]
Oh, sorry that I missed this :smile:. Thanks for the reply.

**Comment by Boolyman** [comment]
Can you at least link to the correct wiki somewhere in a sensible location for people to notice when they come to this github... your wiki button takes us to some old out of date wiki which makes no reference to the new CTGUI changes.  I had to google and hunt down the "readthedocs" site to get the right answer.

**Comment by jaredlll08** [comment]
You mean like here:
![image](https://user-images.githubusercontent.com/5553605/36815745-5e2cf2e2-1ce4-11e8-9606-98da344adb27.png)
or here?
![image](https://user-images.githubusercontent.com/5553605/36815759-6b92ef5e-1ce4-11e8-9fef-f935c876abe5.png)
Maybe here?
![image](https://user-images.githubusercontent.com/5553605/36815836-a17e462c-1ce4-11e8-967d-cce2be5db27b.png)


What about my website?
![image](https://user-images.githubusercontent.com/5553605/36815870-c63e39b8-1ce4-11e8-89d8-b0cb3299f92a.png)

Maybe even a repo under the same github organization as this one?
![image](https://user-images.githubusercontent.com/5553605/36815930-fb0454b6-1ce4-11e8-905b-b7c8538932e1.png)

**Comment by Syndaryl** [comment]
The github wiki link at the top of the page does NOT take you to readthedocs... and frankly that's the place I look for in a project - it's usually the one people bother to update.

If you don't want to maintain the github wiki, that's cool - but I recommend replacing the landing page with a link to the ReadTheDocs.

**Comment by jaredlll08** [comment]
I forget we even had that "wiki" up there, changed it to link to the new docs, but my point still stands, the wiki is linked on nearly every single page that relates to Crafttweaker, it's not like it is being hidden from the public or anything like that.
