### ISSUE TITLE
Mod Script refusing to work after re-creation

### ISSUE THREAD

**Issue by PTVoltz** [CraftTweaker/CraftTweaker#403]
#### Issue Description:
I'm not entirely sure. As far as I can tell, it should work. But it doesn't. Can you see where I went wrong?
I created the script a couple of days ago, but deleted it by accident. When I re-created it, it suddenly refused to work - despite having (As far as I can tell) exactly the same wording.

#### What happens:

I get an error: "ERROR: Error Parsing My Nice Additions.zs:11 --: expected"

#### What you expected to happen:

I hoped - and was able, for a while - to replace a few recipes from Tough As Nails and Thermal Foundation to allow the mods to co-exist with similar items (Allowing both Freeze Rods AND Blizz Rods to make the Cooling Coil, for example).

#### Script used:
https://pastebin.com/q3mYaVD7

#### Minetweaker.log file :
https://pastebin.com/kZCKJFK6
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 13.20.1.2530
- Crafttweaker: 3.0.26

#### Your most recent log file where the issue was present: 

https://pastebin.com/amuLX7WS

**Comment by kindlich** [comment]
Line 8, you are missing a semicolon (`;`)
Edit: You know, you can't add multiple items to an oreDict using `add`, you'll need to create an array and use `addItems`

**Comment by PTVoltz** [comment]
1) OK, thanks!
2) Yeah, that bit was something I was testing to see if it worked - I didn't know, however, as the rest of it broke beforehand... XP

*Edit:* Yeah, it seems to be working now... Sorta... I found some new errors, but at least I know how to fix these. =3
*Edit 2:* Yep, everything's working now. I feel really silly - I specifically searched for any missing semi-colons before making this post, and yet I STILL managed to miss one... Ah well.
