### ISSUE TITLE
JEI on clients not updating to server scripts

### ISSUE THREAD

**Issue by Daniel-I-Am** [CraftTweaker/CraftTweaker#405]
#### Intro:
Hello, I am a server admin running the new 1.12 direwolf 20 pack (this pack is currently running CraftTweaker2-1.12-4.0.10). During the setup of the new server, the decision was made to add custom recipes to the game to enhance our experience, we have also done this on FTB Beyond.

#### Issue Description:
The pack that is being run is Direwolf20 1.12, made by FTB.
Server sided crafttweaker configs do not load on client JEI's.

#### What happens:
When adding a recipe, checking syntaxing (and using common sense), I come to the conclusion recipes should work. When checking JEI later on, the recipes do not want to load. Trying to make the recipe that does show up in JEI, yields into a failure.

#### What you expected to happen:
I expected JEI to show proper recipes, like on previous version

#### Evidence for my claims:
![2017-12-23_23 00 59](https://user-images.githubusercontent.com/34800550/34323009-6b461a8a-e837-11e7-9746-317b548bbb45.png)
![2017-12-23_23 01 00](https://user-images.githubusercontent.com/34800550/34323010-6c76a064-e837-11e7-991a-0d87cabcfe9b.png)
![2017-12-23_23 19 42](https://user-images.githubusercontent.com/34800550/34323023-c3c94510-e837-11e7-90bb-bc05ec0be073.png)

#### Script used 
https://pastebin.com/XFJWBXEQ

#### Minetweaker.log file
https://pastebin.com/TJJy6kPM

____
#### Affected Versions:

- Minecraft: Minecraft Version 1.12.2
- Forge: forge-14.23.1.2555
- Crafttweaker: CraftTweaker2-1.12-4.0.10

#### Your most recent log file where the issue was present: 
https://pastebin.com/FuaTxHFT

**Comment by jaredlll08** [comment]
Scripts do not sync anymore. nothing can be done about this.

**Comment by Daniel-I-Am** [comment]
Thanks for the quick response, unfortunate that nothing can be done about this. I guess this means we need to find an alternate way to spread the recipe information.
