### ISSUE TITLE
Recipe with liquid in bucket does not show properly in JEI

### ISSUE THREAD

**Issue by mvdhoning** [CraftTweaker/CraftTweaker#408]
#### Issue Description:
A custom recipe involving liquids in a bucket do not show up properly in jei
The recipe does work as intented requiring a filled bucket.

#### What happens:
In Jei the recipe shows an empty bucket in the recipe.

#### What you expected to happen:
In Jei the recipe shows an filled bucket with the specified liquid

#### Script used:
`recipes.addShaped(<primal:torch_wood>*12, [[<minecraft:wool:*>, <forge:bucketfilled>.onlyWithTag({FluidName: "creosote", Amount: 1000}),null], [<minecraft:stick>, <minecraft:stick>, <minecraft:stick>]]);`

#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.1.2555
- Crafttweaker: 1.12-4.0.12
- Crafttweaker-JEI-support 2.0.0
- JEI 1.5.1.36

**Comment by jaredlll08** [comment]
https://github.com/jaredlll08/CraftTweaker/issues/407#issuecomment-353806820

**Comment by mvdhoning** [comment]
#### fixed script:
`recipes.addShaped(<primal:torch_wood>*12, [[<minecraft:wool:*>, <forge:bucketfilled>.withTag({FluidName: "creosote", Amount: 1000}).onlyWithTag({FluidName: "creosote", Amount: 1000}),null], [<minecraft:stick>, <minecraft:stick>, <minecraft:stick>]]);`

#### conclusion:
feels wierd having to suppy the tag info twice

PS: oops i totally missed that issue of the only 9 there were.
