### ISSUE TITLE
craftingtables removes/addings doesn't work anymore?

### ISSUE THREAD

**Issue by Leftorius** [CraftTweaker/CraftTweaker#409]
#### Intro:
I updated Crafttweaker from CraftTweaker2-1.12-4.0.10 to CraftTweaker2-1.12-4.0.12

#### Issue Description:
I updated Crafttweaker from CraftTweaker2-1.12-4.0.10 to CraftTweaker2-1.12-4.0.12 and my any recipes (craftinttable) I made, didn't work anymore. it doesn't matter if I use remove or adding stuff.
Modded machine still working, only happens on **craftingtables!**

#### What happens:
updated to CraftTweaker2-1.12-4.0.12

#### What you expected to happen:
working files, I look through changelog and found nothing special about "breaking" old scripts.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
it's a whole Modpack
https://minecraft.curseforge.com/projects/minecraft-engineer
there are a lot of files.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/7Kq4aa8k

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: .2573
- Crafttweaker: CraftTweaker2-1.12-4.0.12 + CraftTweaker2-1.12-4.0.11

#### Your most recent log file where the issue was present: 
https://pastebin.com/7Kq4aa8k

If I use CraftTweaker2-1.12-4.0.10 all my scripts are working!

**Comment by jaredlll08** [comment]
I'm not going to go on some magic hunt to find your script files and then figure out which one.

Post an example.
