### ISSUE TITLE
Crafttweaker not Changing the Craft in JEI 

### ISSUE THREAD

**Issue by berni1212** [CraftTweaker/CraftTweaker#410]
#### Intro:
Hello !
I tryed to make new Recieptes for the Draconic evolution mod for my Server all works fine the Crafting works but its not showing the new Reciepts in Jei any reason why its not working ? 

#### Issue Description:
FTB Direwold20 Pack Offical  MC 1.12.2 FTB 1.4.0
Shouldn't be a Issure from it 

#### What happens:
JEI doesn't load the Files for the Crafting so u can see it if u press R on the Draconium Block 

#### What you expected to happen:
That Jei loads the Crafting files into and shows it u press R on it 

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
http://paste.creeperhost.net/view/01d7582b

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.6.0
- Crafttweaker:  CraftTweaker2-1.12-4.0.10.jar

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
scripts aren't sent to the client.

**Comment by berni1212** [comment]
so it means the Server can't send the user the New File from the Recieptes so every user would need to download it manual ?

**Comment by berni1212** [comment]
So there is no Possible way to change Crafting? to be showed in JEI ?

**Comment by jaredlll08** [comment]
The players need to have the scripts the server has. If they don't, then there will be JEI desymcs.

**Comment by berni1212** [comment]
ahhh okay thats bad thanks 

So its not possible to change it on a public server so everyone sees it -.- 

Well thanks for your Respond

**Comment by berni1212** [comment]
There is no way it Syncs with the Client right ?

**Comment by jaredlll08** [comment]
there is no way.
