### ISSUE TITLE
[Compat/Bug] Some <ore>.remove don't work

### ISSUE THREAD

**Issue by drakray** [CraftTweaker/CraftTweaker#413]
#### Issue Description:
I try to remove oreDict from Harvestcraft, but it's still registered/show in JEI

#### What happens:
`<ore:cropPumpkin>.remove(<minecraft:pumpkin>);` don't log, and is still usable in crafting/JEI

#### What you expected to happen:
`<ore:cropPumpkin>.remove(<minecraft:pumpkin>);` to log and remove recipe from crafting/JEI

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/jWzg3Esq (relevant lines: 242-245)

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/LmJiDqDb (relevant line: 270)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2582
- Crafttweaker: 4.0.12

#### Your most recent log file where the issue was present: 

https://www.dropbox.com/sh/w6qfzbte9khkdbl/AAB1c5Xu3MBXEF9UzJJ_VIzJa?dl=0

**Comment by jaredlll08** [comment]
Harvest craft registers their ores too late.
