### ISSUE TITLE
[1.12.2] Unable to add recipes for the Extreme Crafting table from Avaritia

### ISSUE THREAD

**Issue by Spearkiller** [CraftTweaker/CraftTweaker#420]
#### Issue Description:
I am unable to get Mine Tweaker to add recipes for items using the 9x9 crafting table from Avaritia, though am having no issues removing the recipes. One Recipe is shapeless, and one is shaped, both are available below from the pastebin. I was discussing this issue with one of my friends who is pretty familiar with Craft/Mod Tweaker, but we were unable to fix this issue. They came to the conclusion that there may not be Avaritia support, and if so, I guess this entire post is pointless :/ but according to https://ftb.gamepedia.com/Using_MineTweaker_and_Avaritia there was support at one point, so now I'm just lost and confused.

#### What happens:
I have two recipies using the Extreme Crafting table, and when I open the game I am greeted with two errors in chat, both almost exactly the same. Removing the recipes has worked however, as both items are now uncraftable. The log says "a method available but none matches the parameters" so my hopes is that I've just typed something wrong.

#### What you expected to happen:
I expected no errors and for my recipes to show up in JEI,

#### Script used 
https://pastebin.com/PuJTwQPS

#### Minetweaker.log file 
https://pastebin.com/S8pTQvAX

____
#### Affected Versions
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.1.2555
- Crafttweaker: 1.12-4.0.12

#### Your most recent log file where the issue was present: 
https://pastebin.com/S8pTQvAX

**Comment by jaredlll08** [comment]
I dont add avaritia support, go complain to avaritia directly.

**Comment by Morpheus1101** [comment]
If you go visit the Avaritia mod page you will see all the information on using CraftTweaker
