### ISSUE TITLE
[Feature Request] Customize block settings

### ISSUE THREAD

**Issue by SergGrey** [CraftTweaker/CraftTweaker#421]
Author, could you make the settings of the drop from blocks and the possibility of breaking the block with only certain tools or changing the speed of breaking

**Comment by jaredlll08** [comment]
I believe this has been implemented thanks to the big api PR from @kindlich

**Comment by hologer** [comment]
Is there a guide for how to create a custom drop for block? i can't find anything in the documentation about this

**Comment by jaredlll08** [comment]
You never asked for that. There is an open issue regarding block drops.
