### ISSUE TITLE
OR condition in ingredients

### ISSUE THREAD

**Issue by narralord** [CraftTweaker/CraftTweaker#422]
#### Issue Description:
I want to add recipe with two different ingredients in one craft square, looks like a oreDictionary. I found ".or" method in IIngredient class. I try to use this method in my *.zs file. 

#### What happens:
Nothing. No crashes, no bugs. But recipe is not Added.

#### What you expected to happen:
my script add one recipe with different ingredient in one square, looks like a oreDictionary.

#### Script used:
`val qqq = <minecraft:redstone>;
val www = <minecraft:glowstone>;
val eee = qqq.or(www);

recipes.addShaped(<minecraft:stick>, 
	[[eee, null],
	 [www,  null]
]);`

#### Minetweaker.log file:
[crafttweaker.log](https://gist.github.com/narralord/021457d258b036498eb3db08906d8f05)
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.1.2554
- Crafttweaker: 1.12 - 4.0.12

**Comment by jaredlll08** [comment]
is the recipe not added, or is it not showing in JEI?

**Comment by narralord** [comment]
it is not showing in JEI, but i can craft it. And the ingredients are not wasted

**Comment by jaredlll08** [comment]
![image](https://user-images.githubusercontent.com/5553605/34836704-6627f69e-f701-11e7-9581-0e7214e5116a.png)

http://crafttweaker.readthedocs.io/en/latest/#Vanilla/Variable_Types/IIngredient/#or-ing-an-iingredient

**Comment by narralord** [comment]
ok. thanks
