### ISSUE TITLE
[Feature Request] Send scripts from server to client

### ISSUE THREAD

**Issue by Sir-Will** [CraftTweaker/CraftTweaker#423]
Hey,
can we please get a way to send scripts from the server to the client back?

This feature is important and was used on every server to
- Add/Adjust recipes for items which are not accessible in the server environment
- Fix broken recipes for modpacks which are no longer getting updated
- Add warnings via tooltips
- Add missing recipes
- Remove recipes of broken items
...

**Comment by jaredlll08** [comment]
It wasn't removed by choice.
https://www.reddit.com/r/feedthebeast/comments/6oxjtd

**Comment by Sir-Will** [comment]
What about one of those solutions?
- Server sends the scripts to the client, the client saves them and loads them with the next client restart.
- Server sends the scripts to the client, the mod on the client shows the recipes only visually instead of adding them to the game.
