### ISSUE TITLE
[Feature Request] removeDescription on JEI

### ISSUE THREAD

**Issue by justinrusso** [CraftTweaker/CraftTweaker#425]
Hello Jared/Kindlich/etc,

Would it be possible to add a function to be able to remove the JEI description on an item? A mod adds a description on where to find it in the world, but that does not exist anymore, so it makes no sense for it to have that as it only confuses the player.

Thanks!

**Comment by jaredlll08** [comment]
unfortunately there is no way to remove them in JEI itself, maybe @Mezz can add it? (This can be reopened if mezz adds it)
