### ISSUE TITLE
CraftTweaker returns ERROR

### ISSUE THREAD

**Issue by JWTHDYTWA** [CraftTweaker/CraftTweaker#426]
#### Intro:
Script with recipes i've been creating returns an error. I couldn't notice anything that would be cause of this.

#### Issue Description:
In general, my script can't be loaded and i have no idea why. Error being returned in chat isn't bound to any string.

#### What happens:
I created a script that's not being loaded and returns an error.

#### What you expected to happen:
Correct work.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://gist.github.com/Warrock3280/b7a2b8acbb0a8d6ea7ebdf67e3838160

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/Warrock3280/638c1bca45e25a46e233993d1e1d62e4

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.1.2573
- Crafttweaker: 4.0.12

#### Your most recent log file where the issue was present: 

https://gist.github.com/Warrock3280/21255d2bfbd311207c66402d67bba9f8

**Comment by JWTHDYTWA** [comment]
Forgot to mention that it's an edited FTB Revelation modpack, but because i've created script by myself, i think it doesn't matter.

**Comment by jaredlll08** [comment]
you are trying to call an item that doesn't exist, on line 142
