### ISSUE TITLE
Truncated Class File Error?

### ISSUE THREAD

**Issue by kd8lvt** [CraftTweaker/CraftTweaker#427]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
When loading my script, I get a "Java.lang.ClassFormatError: Truncated Class File" error. It only happens with this script, dealing with CC: Tweaked (ComputerCraft fork). I have one other script that works fine that deals with CC: Tweaked in the same modpack.

#### What happens:
I get a "Java.lang.ClassFormatError: Truncated Class File" error, and the affected script cancels execution. Other scripts load fine afterwards.

#### What you expected to happen:
I expected the script to run as normal; removing and changing the recipes for several CC: Tweaked blocks, using a loop to remove. 

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
Affected Script: [computercraft.zs](https://pastebin.com/fejkkuaj)

Script that involves CC: Tweaked but runs fine: [pneumaticAge.zs](https://pastebin.com/VUHMYrWY)

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
[craftweaker.log](https://pastebin.com/E3V9cMU5)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.1.2600
- Crafttweaker: 1.12-4.0.12

#### Your most recent log file where the issue was present: 

[fml-client-latest.log](https://gist.github.com/kd8lvt/41b38863c8267c698842f48fa42eeb6c)

**Comment by jaredlll08** [comment]
You aren't importing IItemstack.
