### ISSUE TITLE
ArrayIndexOutOfBoundsException error when using /ct recipes

### ISSUE THREAD

**Issue by smcnabb** [CraftTweaker/CraftTweaker#429]
#### Intro:
I'm putting together a custom modpack and running in to an issue getting recipe information with the /ct recipes command. I realize it might be due to one of the mods I have added or the amount of mods/items. I tried a quick test with just CraftTweaker, JEI and FTB Utils and it worked fine. So hoping you might have come across this before and know a fix.

If you think it might be a particular mod then I can try to find some time at the weekend and see if I can rule it down to which one it is. And feel free to ask me to try anything else you might think could help track it down.

#### Issue Description:
When I try using the /ct recipes command I get an ArrayIndexOutOfBoundsException in the latest log and no recipes are written to the crafttweaker.log file.

#### What happens:
No recipes get written to the log file.

#### What you expected to happen:
Recipes get written to the log file.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
I don't have any CT scripts yet.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/anonymous/2dec9271252810a33980474ab725d54d

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.1.2600
- Crafttweaker: CraftTweaker2-1.12-4.1.0.jar (same thing happened with 4.0.12 so upgraded to see if that would help)
- Mod list: https://gist.github.com/anonymous/707432d898e52f0d181545788a991c7f

#### Your most recent log file where the issue was present: 

The exception is at the end:
https://gist.github.com/anonymous/1fbc45acd274b781e28851e03e0af4e1

**Comment by jaredlll08** [comment]
yea... some mod is doing a recipe really weird, and I'm not sure how we can safeguard against this, is there any chance you could narrow the modlist down to figure out which mod?

**Comment by smcnabb** [comment]
I went back to test it again and it had stopped happening. I'd since updated some mods, so went back and tracked it down to OpenBlocks.

If you create a pack with just these mods it causes the exception:
```
CraftTweaker2-1.12-4.1.2.jar
OpenBlocks-1.12.2-1.7.4.jar
OpenModsLib-1.12.2-0.11.4.jar
```
If you update to the latest OpenBlocks versions it's fine:
```
CraftTweaker2-1.12-4.1.2.jar
OpenBlocks-1.12.2-1.7.5.jar
OpenModsLib-1.12.2-0.11.5.jar
```

So yeah probably nothing to worry about since it's fixed but figured this might be useful info. Feel free to close this out unless you want to investigate.

**Comment by jaredlll08** [comment]
well it appears to be fixed, if it comes up again, I'll take a proper look at it
