### ISSUE TITLE
blockHardness fieldException

### ISSUE THREAD

**Issue by WesTroy** [CraftTweaker/CraftTweaker#431]
#### Issue Description:

Just playing with hardness settings - setting it works fine, no errors, and in-game the hardness is changed. Retrieval of hardness errors out (please see links below). This did seem to occur way back in 2016, where a fix was made, but no later issues noted.

#### What happens:

Simple print() test of *.hardness returns UnableToFindFieldException on blockHardness.

#### What you expected to happen:

Block should be successfully queried and hardness # returned (unless my expectation is erroneous).

#### Script used:

https://pastebin.com/exV5dhtr

#### Minetweaker.log file:

https://pastebin.com/VxJvPK8F

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.1.2555
- Crafttweaker: 1.12-4.1.0

#### Your most recent log file where the issue was present: 

https://pastebin.com/wQsV8njS

**Comment by kindlich** [comment]
jaredlll08, you might wanna add the obfuscated field name in the reflection helper as well.

<https://github.com/jaredlll08/CraftTweaker/blob/476735b2a88835573e5cd28591cd87ff2f6a0bb1/CraftTweaker2-MC1120-Main/src/main/java/crafttweaker/mc1120/item/MCItemStack.java#L105>
