### ISSUE TITLE
Command /ct hand only shows stone when looking at any blocks with an empty hand

### ISSUE THREAD

**Issue by KAfable** [CraftTweaker/CraftTweaker#432]
#### Issue Description:
/ct hand shows only stone whenever I look at any block with an empty hand

#### What happens:
![image](https://user-images.githubusercontent.com/26587049/35475765-d0d44c96-0371-11e8-8523-9b6ee57c135f.png)

#### What you expected to happen:
Instead I was expecting it to show <minecraft:iron_block> at 202 51 3.

#### Script used:
/ct hand

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2594
- Crafttweaker: 4.1.0

#### Your most recent log file where the issue was present: 

https://hastebin.com/enuzehoruj.md
(Don't think there's anything relevant to that on there though)

**Comment by jaredlll08** [comment]
![image](https://user-images.githubusercontent.com/5553605/35476538-5f53e6aa-03ba-11e8-932c-12224153799c.png)
![image](https://user-images.githubusercontent.com/5553605/35476545-7207f476-03ba-11e8-8910-65420a0f6860.png)

can't reproduce
