### ISSUE TITLE
Unable to use reuse and Pam's harvestcraft?

### ISSUE THREAD

**Issue by GamerCoke** [CraftTweaker/CraftTweaker#434]
#### Intro:
Having a some trouble making my script work, I don't really know if it's just because I don't know what I'm doing, or that I'm working with old code or something along the lines of that. I haven't really been able to find any help, with the problems I've experienced, so far.

#### Issue Description:
My latest code is not doing anything, and failing to... execute? It is annoying and as it has worked up untill now. It was as soon as I started to work with Pam's harvestcraft and .reuse() that I've experienced the code failing me. 
The code that isn't working for me are 5 code lines, which is either about <harvestcraft:crackersitem> or <harvestcraft:flouritem>

#### What happens:
The code doesn't do anything in game.

#### What you expected to happen:
I expected it to change the recipe, so I didn't have to use a salt from Harvestcraft that OreDict removed.

#### Script used:
https://pastebin.com/nmrEX0MR

#### Minetweaker.log file:
not sure if I'm doing this part right, but this was the best I could do so far
https://pastebin.com/nHY8bjwn

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.1.2599
- Crafttweaker: Minetweaker2 - 1.12 - 4.0.12

#### Your most recent log file where the issue was present: 
https://pastebin.com/SZDvQkac

**Comment by kindlich** [comment]
There is no `reuse()` in 1.12, you can use `giveBack()` instead.
Most of the bakeware items should have set themselves as containerItem though, so you probably won't even need reuse or giveBack

**Comment by GamerCoke** [comment]
Thanks for the help, I've fixed the majority of the code, and ended up removing the last bit of code, as it didn't really matter in the end. 
final code: https://pastebin.com/pjUWeDyM
