### ISSUE TITLE
[help!] Adding a fluid transposer recipe and getting an error

### ISSUE THREAD

**Issue by KirbyQK** [CraftTweaker/CraftTweaker#437]
#### Issue Description:
I'm trying to add a script to craft cinnabar with rich slag and destabilised restone in a fluid transposer, but I'm getting errors from crafttweaker that I haven't been able to work out, and haven't been able to find any useful/comparable threads online that I could use to figure out what knowledge I'm missing.

#### What happens:
I created a file that I called scripts.zs in the scripts folder with my recipe included in it, and crafttweaker appears to recognise and attempt to parse the script, but throws an error. I've looked at the documentation and I _think_ I've set it up correctly.

#### What you expected to happen:
New recipe!

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://gist.github.com/KirbyQK/a9895cfb71cf1f73190ac47f2658714a

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://gist.github.com/KirbyQK/d89e27ff519fba2600c2862c0c70e69d

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.1.2587
- Crafttweaker:  1.12-4.0.12

#### Your most recent log file where the issue was present: 

https://gist.github.com/KirbyQK/b9de1c835a4d80687ba0b84a12a88953

**Comment by kindlich** [comment]
The issue is your destabilized Redstone, [liquid Bracket Handlers](http://crafttweaker.readthedocs.io/en/latest/#Vanilla/Brackets/Bracket_Liquid/) require `<liquid:name>`.

Use [`/ct liquids`](http://crafttweaker.readthedocs.io/en/latest/#Vanilla/Commands/#liquids) to print a list of all registered liquids to the Crafttweaker.log file
