### ISSUE TITLE
Issues with recipes when in server (1.10.12 - 3.0.26)

### ISSUE THREAD

**Issue by Fireztonez** [CraftTweaker/CraftTweaker#438]
#### Intro:
I make multiple change on recipes for crafting table and for the furnace. I try every recipes on my single player world and everything work's great, but when I play on my server (The same scripts files on both sides) and I get an error on the load on 2 files can't be execute...

#### Script used:
https://gist.github.com/Fireztonez/a8909b769055f34946a482dcb4ece539
https://gist.github.com/Fireztonez/a4ecb2641d4120888bc5cf33145b6c78
...
If needed I can post the others scripts files, but I don't see any error message about that other files

#### Issue Description:
On the chat is said Error NULL...

#### What happens:
When I try to craft one of the recipes (I can see the craft in JEI), so I make the recipe on the crafting table, I see the output, so I click to pick-up, and the item imediatelly disapear and  the items for the craft return imediatelly on the crafting table...

#### What you expected to happen:
Have the recipe work's like supposed and like on the single player world!!

This bug is appen on my Own Modpack (Epixcraft Modpack) in the latest stable version.
https://www.curseforge.com/minecraft/modpacks/epixcraft-modpack

#### Minetweaker.log file
https://gist.github.com/Fireztonez/9dfb3985f9c4b94ed6b3812090a7d4eb

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2511
- Crafttweaker: 3.0.26

#### Your most recent log file where the issue was present: 
https://gist.github.com/Fireztonez/0a79c037c80ee262f57814eefca93195

**Comment by jaredlll08** [comment]
1.10.2 isn't supported anymore

**Comment by Fireztonez** [comment]
You can't just look for me, what the problem can do?? If the problem is with my scripts or anything else??

Realy, i'm disappointed...

You do not have any suggestion for try to fix my issues, you just close that...

**Comment by jaredlll08** [comment]
well I mean, you have a crash log, that shows you what the error is, so sure, I can look at the crash log for you...

Oh crashlog says it is the mod, oh well... nothing I can do.

**Comment by Fireztonez** [comment]
Thank's, but I finally found the problem... So that issues is FIXED 👍  !!

The problem is all the lines
`mods.jei.JEI.hide(<mod:item>);`
If I comment all this lines, that fix the problem. So, well that is line from the CraftTweaker wiki, but, anyway's is not needed for thge server side, and on the client side is not really working anyways...

If some one else have this issues, just comment this lines and, possibly that work's for you!!

Thank's Jared
FireZtoneZ
