### ISSUE TITLE
[1.12.2] Recipes don't work

### ISSUE THREAD

**Issue by armuell** [CraftTweaker/CraftTweaker#439]
#### Issue Description:
Crafttweaker scripts load without errors and appear to register recipes. The recipes show up in JEI but when you attempt to craft them nothing happens (there is no item in the output of crafting table). This happens on both single player and servers. I am the developer of this mod pack and the problem can be easily reproduced but installing and trying to craft one of the recipes I added in recipes.zs: https://minecraft.curseforge.com/projects/peace-of-mind/files/2524242

#### What happens:
Recipes don't work

#### What you expected to happen:
Recipes to work

#### Script used:
https://pastebin.com/PnWZFJHp
https://pastebin.com/Gb1k4yTp
https://pastebin.com/0ctiLq8Q
https://pastebin.com/T2LPcX1a

#### Minetweaker.log file:
https://pastebin.com/XbnzvrkS

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.1.2577
- Crafttweaker: 4.1.0
- Contenttweaker: 4.4.0
- LootTweaker: 0.0.6.5

#### Your most recent log file where the issue was present: 

linked above? unless I am misunderstanding something

**Comment by armuell** [comment]
You can also download any previous versions of the pack linked above and see that the recipes worked just fine before updating crafttweaker/contenttweaker. I have not changed anything regarding the recipes I've added between versions.

**Comment by jaredlll08** [comment]
I actually downloaded your pack which is something I never do, because of how weird this was... and I can't reproduce it.


![image](https://user-images.githubusercontent.com/5553605/35636278-56db2f9a-06b9-11e8-9d40-ea6cb0c30b9c.png)

![image](https://user-images.githubusercontent.com/5553605/35636323-7a44c7d4-06b9-11e8-9968-937d3abba238.png)

![image](https://user-images.githubusercontent.com/5553605/35636350-8dcc290a-06b9-11e8-988c-b59f0f15739d.png)

![image](https://user-images.githubusercontent.com/5553605/35636387-9ef1b646-06b9-11e8-96d0-d79497dd0774.png)

**Comment by armuell** [comment]
are you 100% sure you used version 1.8.0 of the pack? It's marked as beta so you might have downloaded the previous version @jaredlll08

**Comment by armuell** [comment]
Also as I stated in the OP, JEI will display the recipes but when you actually go to craft the items it does not work.

**Comment by jaredlll08** [comment]
Then it is another mod messing with it. If JEI AND the vanilla recipe book are picking up the item, then another mod is messing with the creation of it.
![image](https://user-images.githubusercontent.com/5553605/35637106-e240b814-06bb-11e8-8138-f023e8ca9044.png)

**Comment by armuell** [comment]
Interesting. I will load up the previous version of the pack and only update CraftTweaker and ContentTweaker. If the problem still persists then we know the issue is with the CT but if it doesn't then we know another mod is causing the issue. I'll report back soon.

**Comment by armuell** [comment]
Alright I just did the above and the recipes worked. So you are correct that a different mod is interfering which is annoying because I have no clue how to track this down lol. Thank you for your help. If you have any suggestions let me know.

**Comment by tyler489** [comment]
Binary search. Update 1 mod at a time until it breaks. Then roll back and just use crafttweaker and that mod if it breaks that m9d causes isue. If not its 2 mods cauising issues
