### ISSUE TITLE
ItemDestroySpeed crash while attempting to evaluate null property

### ISSUE THREAD

**Issue by pyure** [CraftTweaker/CraftTweaker#440]
#### What happens:
When tool including attached script attempts to mine a block, MC instantly crashes.

#### What you expected to happen:
Test for null and successfully return a float w/o crashing

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
Script is incomplete, but kindlich is aware of the specifics.
https://pastebin.com/WGq022SY

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/b33AeK6M

#### Affected Versions (Do *not* use "latest"):
N/A

#### Your most recent log file where the issue was present: 
N/A

**Comment by jaredlll08** [comment]
Wrong repo. You want ContentTweaker, not Crafttweaker
