### ISSUE TITLE
[Suggestion] Set living entity can despawn

### ISSUE THREAD

**Issue by KorDum** [CraftTweaker/CraftTweaker#442]
#### Issue Description:
Is it possible to make creature can despawn? For parrots, rabbits etc.
For Minecraft 1.12.2

**Comment by jaredlll08** [comment]
wat. this makes no sense.

**Comment by KorDum** [comment]
Why? If I use OTG generation with mob spawn settings and set parrots into embients. I need this feature.

**Comment by jaredlll08** [comment]
I don't even know what you are asking.

**Comment by KorDum** [comment]
https://takahikokawasaki.github.io/minecraft-resources/javadoc/forge/1.8-11.14.1.1320/net/minecraft/entity/EntityLiving.html#canDespawn()
Method exists in latest Forge 1.12.2 too

**Comment by jaredlll08** [comment]
Yes... there is a PROTECTED method in forge, doesn't help me understand what you want...

**Comment by KorDum** [comment]
I apologize for the misunderstanding. Can I allow animals like Parrots, Rabbits etc to despawn from CraftTweaker scripts? I need this in order for the emerging custom environment animals to disappear and appear again and don't load the server with their huge amount. Is it possible? It would be so cool to have such an opportunity without having to install additional tools to control the spawn

**Comment by KorDum** [comment]
OpenTerrainGenerator allows you to specify lists of environment mobs in a particular biome, but mobs that can not despawn remain in the biome forever. And to them there are more and more new.

**Comment by jaredlll08** [comment]
That makes more sense...

**Comment by KorDum** [comment]
Oh thanks!

**Comment by jaredlll08** [comment]
On further investigation, there isn't a "setCanDespawn" or anything of the like, so there is nothing I can do. sorry :(

**Comment by KorDum** [comment]
Very sorry. Thank you very much for trying.
