### ISSUE TITLE
furnace.getFuel() seems to always return -1

### ISSUE THREAD

**Issue by Insane96** [CraftTweaker/CraftTweaker#443]
#### Issue Description:
`furnace.getFuel()` always return -1

#### What happens:
`furnace.getFuel()` always return -1

#### What you expected to happen:
`furnace.getFuel()` should return actual time for the fuel

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/nWF1yTzU

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/zPUM2cSW

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.2.2611
- Crafttweaker: 4.1.2
- MTLib: 3.0.1

**Comment by jaredlll08** [comment]
So this is an issue with how Forge changes furnace fuel times, there is nothing I can do to fix it fully, but I have added some code which should make it a bit more reliable
