### ISSUE TITLE
removeAndHide JEI Function working inconsistently

### ISSUE THREAD

**Issue by 99Blocks** [CraftTweaker/CraftTweaker#444]
#### Issue Description:
When creating my .zs using the removeAndHide function, certain items are hidden whilst others are not.

#### What happens:
Everything I have added up to a certain point in the script is hidden whilst items after that point are not

#### What you expected to happen:
Consistent hiding using the "removeAndHide" function for JEI
I have attempted to use the function after rolling back the CraftTweaker version with no luck.

#### Script used
https://pastebin.com/YG7MY71D
Everything up until line 300 is successfully hidden. I have added a commented line in Pastebin to show where the error starts

#### Minetweaker.log file
https://pastebin.com/ygtTnpTR

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.2.2611
- Crafttweaker: 1.12-4.1.2

#### Your most recent log file where the issue was present: 
https://pastebin.com/0dFcaVGc

**Comment by jaredlll08** [comment]
@mezz do you have any idea? it is erroring over here: https://github.com/ForestryMC/Binnie/blob/master-MC1.12/genetics/src/main/java/binnie/genetics/item/ItemSequence.java#L131

**Comment by mezz** [comment]
It looks like you are disabling some important items from Binnie's genetics in the .zs but Binnie's doesn't handle it properly? Does removeAndHide remove the item from the game or just from JEI?

**Comment by jaredlll08** [comment]
@mezz removeAndHide removes the recipe and hides the item (equivalent to `recipes.remove(x); JEI.hide(x);`).

@darkosto has been using it in his pack for months now without issue

**Comment by mezz** [comment]
I think in this case they are removing an item that is required for Binnie's to work. Without the item, it just crashes.

**Comment by 99Blocks** [comment]
Sorry for the late response. Thanks for looking at this for me!
I've been playing around a bit and the Binnies Config has an option to disable the genetics module but whether that is on or off, the items still appear in JEI.
However attempting to use any of them with it disabled causes a crash so I can only assume that it is an issue with the Binnie mod itself.
I'll open up a ticket over there and see what can be done on their side of things, feel free to close this off now and thanks again for looking into it for me!

Keep up the good work folks!

**Comment by jaredlll08** [comment]
@mezz keep in mind, removeAndHide only removes the RECIPE and HIDES it from JEI, the item is still very much ingame, but I'll close the issue based on what you said.
