### ISSUE TITLE
[Question/Request] Information attached to Ingredients

### ISSUE THREAD

**Issue by ElvenChaos** [CraftTweaker/CraftTweaker#446]
Is there a way for me to add an informational tooltip to an item being used as a crafting ingredient in a new recipe? To clarify, I'm not looking to attach a tooltip to all instances of a particular item, nor am I trying to require a certain NBT or Lore tag on a crafting ingredient -- I'm just trying to communicate information to players who are viewing the recipe in JEI.

Example uses would be if I were trying to communicate whether a recipe consumes the bucket from a bucket of liquid used in a recipe or not, or if a recipe accept all valid NBT's of an item that may not seem obvious like a dmg transformer on a tcon tool used to affect an item.
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2611
- Crafttweaker: 4.1.2

**Comment by Ferrocn** [comment]
I also wondered this. Since .onlyWithTag() gives the correct recipe functionality, it doesn't show up in JEI.
Whereas .withTag() shows all details in JEI, the recipe doesn't respect nbt.

**Comment by jaredlll08** [comment]
There is no way to do this since we can't tell when an item is being views in JEI

**Comment by ElvenChaos** [comment]
Thank you for taking a look at the request! :D
