### ISSUE TITLE
Error parsing hello.zs:12 -- ; expected

### ISSUE THREAD

**Issue by Brainslime1** [CraftTweaker/CraftTweaker#450]
#### Issue Description:
the issue is that i followed what the tutorial said but it keeps giving me the error 
Error parsing hello.zs:12 -- ; expected

#### What happens:
Error parsing hello.zs:12 -- ; expected

https://pastebin.com/vzM6b3Yu

and here is the minetweaker log
https://www.dropbox.com/s/9yclssxp9mgmp0m/minetweaker.log?dl=0

____
note im new to github and doing error reports.

- Minecraft:1.10.2
- Forge:12.18.3.2511
- Crafttweaker: 1.10.2-3.0.26

**Comment by Cazadorsniper** [comment]
line 10 needs a ; at the end: val myEntry = (<ore:myOwnEntry>);
also, the ore:myOwnEntry.add should be myEntry.add

**Comment by jaredlll08** [comment]
as @Cazadorsniper said, your syntax is wrong.
