### ISSUE TITLE
[suggestion/question] view mekanism recipes

### ISSUE THREAD

**Issue by Entayan** [CraftTweaker/CraftTweaker#451]
Would it be possible to output a list of mekanism recipes like it could be done with minetweaker and modtweaker? This may already be a feature but I can't seem to find reference for it anywhere nor do any commands for this seem to work in-game.

Example:
/ct mekanism
//This would output all recipes added by mekanism

I've been bumbling through trying to adjust a few machine recipes but I'm definitely missing something and it would be very useful to be able to see the recipes in zenscript.

**Comment by jaredlll08** [comment]
Use /ct recipes

**Comment by Entayan** [comment]
Sorry, I realize I didn't really clarify what I was asking. The regular crafting recipes will show up, but I'm looking specifically for the machine recipes (chemical dissolution chamber, crystallizer etc). Is there a way to get these?

**Comment by Entayan** [comment]
I'm asking because I'm trying to add a dissolution chamber recipe but I can't seem to set the amount of gas that the recipe produces. I was thinking that looking at the recipes would give some insight on how to proceed since I can't find what I'm looking for on the wiki.

**Comment by jaredlll08** [comment]
Mekanism adds its own support, so go ask them

**Comment by Entayan** [comment]
I didn't know that, thanks for the info
