### ISSUE TITLE
crash on boot

### ISSUE THREAD

**Issue by Sunekaer** [CraftTweaker/CraftTweaker#453]
Hey

Im trying to add a recipe for `<chickens:spawn_egg>.withTag({ChickenType: {id: "chickens:logchicken"}})`, then i try to boot up a server with `recipes.addShaped(<chickens:spawn_egg>.withTag({ChickenType: {id: "chickens:logchicken"}}), [[<ore:logWood>, <ore:logWood>, <ore:logWood>], [<ore:logWood>, <minecraft:egg>, <ore:logWood>], [<ore:logWood>, <ore:logWood>, <ore:logWood>]]);`
in the script, the server crash on boot up.
Clients with this in the script loads fine and works fine in single player

Script
https://pastebin.com/A2FELgCW

Minetweaker log 
https://pastebin.com/qvGaGvq0

Crash log
https://pastebin.com/NDn1U6zq

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.2.2616-universal
- Crafttweaker: 4.1.3

**Comment by jaredlll08** [comment]
Speak to the author of Chickens, they are calling client side code in a universal method.
