### ISSUE TITLE
[Question] How to remove recipe from ThermalExpansion Induction Smelting by ore dict?

### ISSUE THREAD

**Issue by KorDum** [CraftTweaker/CraftTweaker#454]
#### Issue Description:
I have ImmersiveEngineering and ThermalExpansion (+Foundation of course) and 2 recipes for nickel ore:
![image](https://user-images.githubusercontent.com/1331559/36339609-a3585c98-13da-11e8-8891-7c4ac0f20c3c.png)
![image](https://user-images.githubusercontent.com/1331559/36339615-c4fa6378-13da-11e8-87c5-db1924c10dba.png)

How can I remove these recipes? I getting some errors:
![image](https://user-images.githubusercontent.com/1331559/36339676-023bf296-13dc-11e8-9057-424586b8038f.png)

#### Script used:
I tryed this https://gist.githubusercontent.com/KorDum/74a556c0c27eca5e495a2554555ea586/raw/2325dbb8fb12b662bfa20ded8513b0843b31f3d8/gistfile1.txt

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.2.2611
- Crafttweaker: 4.1.3
- Modtweaker: 4.0.7

**Comment by jaredlll08** [comment]
Report it to the modtweaker repo
