### ISSUE TITLE
[Suggestion] Use script name as part of the tag for auto-generated recipes?

### ISSUE THREAD

**Issue by KAfable** [CraftTweaker/CraftTweaker#457]
#### Issue Description:
So most of the time, the name auto-generated from crafttweaker doesn't have much utility. Would it be possible if custom recipes added by script include the name of the script adding them in? Sometimes in larger packs it's hard to track down which script does what, leading to some awkward script sorting systems when making a pack.

#### What happens:
For example if I have the following script called `Minecraft.zs`:
```
recipes.addShaped(<minecraft:bookshelf>, [
      [<minecraft:gold_ingot>, <minecraft:gold_ingot>, <minecraft:gold_ingot>],
      [<minecraft:gold_ingot>, null, <minecraft:gold_ingot>],
      [<minecraft:gold_ingot>, <minecraft:gold_ingot>, <minecraft:gold_ingot>]]);

```
#### What you expected to happen:
Normally it would result in `ct_shaped-1231231444` etc. It would be a lot more helpful if the recipe name was something along the lines of `<scriptname>-12123331`. So in this case it'll be `Minecraft-12321122` or something along those lines.

**Comment by jaredlll08** [comment]
unfortunately, due to how scripts are loaded, we can't really just add it on, we don't know where they are loaded from
