### ISSUE TITLE
[Question] server side for jei

### ISSUE THREAD

**Issue by sathelate** [CraftTweaker/CraftTweaker#464]
#### Intro:
Hi, sorry to create a request on the issue tracker, its more of an question to crafttweaker devs :)
I have looked at the wiki (wich is not clear on some little major points or im too dumb to figure out where to look) and cant seem to find the specific questiopn im looking for ;)

All of this is using standard minecraft crafting table of course :)

Im a modded server owner and i play with a lil dozens of my friends, and while im using multiMC which is not really a modpack updater but more of an instances importer, i want to know clearly if in minecraft 1.12.2 using latest recommended 2611 forge edition, i could have the recipe script only on server side and makes JEI update to those new recipes ?
And if yeah, i would appreciate some help :)

Let me clarify my question.
As an exemple, the fuel pomp on MTS mods is way too easy to create using the mod owner recipe, i wanna tweak it to use immersive engineering mod, exta utilities 2 and Thermal's suite
I then add this little example script to the server side : 

`recipes.addShaped(<mts:fuelpump>, [[<extrautils2:decorativeglass:2>, <thermalfoundation:meter>, <immersiveengineering:connector:13>],[<immersiveengineering:connector:12>, <immersivepetroleum:metal_device>, <thermaldynamics:duct_16:6>], [<thermalexpansion:machine:8>, <immersiveengineering:metal_device0:5>, <thermalexpansion:device:6>]]);
`

Wich work perfectly as a ghost recipe (not showned of JEI)

Now wanna remove the standard recipe of the MTS mod owner as an example with the same fuel pump again

`recipes.removeShaped(<mts:fuelpump>, [[<minecraft:dye:1>, <minecraft:glass_pane>, <minecraft:dye:1>],[<minecraft:dye>, <minecraft:iron_ingot>, <minecraft:dye>], [<minecraft:stone_slab>, <minecraft:stone_slab>, <minecraft:stone_slab>]]);
`

Wich stop minecraft client side from being able to create that recipe on my server, but still can make it on single player wich is logic ;) >>> (but still showned in JEI).

>>> Now that it works flawlessly, what i wanna do is to hide the original recipe from JEI and show the new recipe.

Cant find anything that work UNLESS i put this exact little script in my client side and restart the whole game as it should now with 1.12.+.

This time after a full restart, i got exaclty what i want without entering ANY other command. JEI just hide the original method which even if i try to craft it single player, or on my server, doesnt work like it should. Logic
And if i try the new recipe, everything work as it should in single player AND in server.

>>> Good, now that this basic understanding of mine is out of the way, i repeat my question.

Is it possible to hide that recipe from JEI and Show the new one instead using ONLY server side script?
Or it is entirely normal behavior and ill need to send to my friend every tweak script i do over the time every time ? (yeah i know, if i need to send them the script everytime, i will then consider creating a real modpack wich update it automatically )

Again, sorry if it was asked, but with tons of latest implementation im just wondering if im too dumb and need dev/community help to do what i wanna do, or if it is intended considering how both mod work apart :)

Huuuuge thanks :D 

Using Minecraft 1.12.2
Forge LR 2611 (Latest Recommended)
Crafttweaker2-1.12-4.1.4 
and modtweaker4.0.7 (which is irrelevant i think in this question)

**Comment by BloodWorkXGaming** [comment]
If I understand your question correctly you want to add a recipe on the server side and have to work on the client as well?
This doesn't work on 1.12+ anymore (same reason as /ct reload getting removed) and the recipes aren't getting synced to the client anymore

Due to this you gotta have to have the same scripts on the client and on the server

**Comment by sathelate** [comment]
exact,
there you go, so no way to comfortably do this anymore without having the exact same script on the client side as well i guess ?
Tyvm ^_^
I then need to figure out how to do an auto aupdater modpack or something :P 
This would make it easier :)

Thank you again :) 

Edit : is there is a way to open ctgui diorectly from the server or do i have to switch to single player each time i wanna use the GUI for adding or removing a recipe ?

**Comment by jaredlll08** [comment]
CT GUI is only client side, it doesn't function on servers.
