### ISSUE TITLE
[Question] Replace an ingredient in the crafting table with another ingredient upon crafting

### ISSUE THREAD

**Issue by NotAVerb** [CraftTweaker/CraftTweaker#466]
#### Issue Description:
I'm intending on creating recipes that use special compound containing vials from another mod. Is it possible to replace the vial in the crafting table with a glass bottle upon crafting? Or atleast give the player a glass bottle in addition to the result of crafting?
____
#### Versions in Use
- Minecraft: 1.12.2
- Crafttweaker: 4.1.4

**Comment by jaredlll08** [comment]
Read the docs.
http://crafttweaker.readthedocs.io/en/latest/#Vanilla/Items/Item_Transformers/
