### ISSUE TITLE
ICraftingInfo in IRecipeFunction is not working

### ISSUE THREAD

**Issue by Weisstrieb** [CraftTweaker/CraftTweaker#468]
#### Issue Description:
If the parameter 'cinfo' (ICraftingInfo) is called, script is not working.

#### What happens:
**(Case I)**
![sublime_text_2018-02-27_01-12-14](https://user-images.githubusercontent.com/16723572/36681339-37c87408-1b10-11e8-8bb0-509fc524052f.png)

**(Case II)**
![sublime_text_2018-02-27_01-18-55](https://user-images.githubusercontent.com/16723572/36681540-c95fdc62-1b10-11e8-9144-9a718f29022e.png)

**(Case III)**
Just in case, since world method in ICraftingInfo is likely to return null so that remote method cannot process, I remove the line 13 `print(cinfo.world.remote as string)`, but same result above.

#### What you expected to happen:
In Case 2, IRecipeFunction should work, printing player's id and isRemote() result.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
**[Attached on screenshots]**

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
```
[SERVER_STARTED][CLIENT][INFO] Fixed the RecipeBook
[SERVER_STARTED][CLIENT][INFO] New transform function is running. It'll return minecraft:apple
[SERVER_STARTED][SERVER][INFO] New transform function is running. It'll return minecraft:apple
```
(Case I. Initialization log is omitted since there is nothing special)

```
[SERVER_STARTED][CLIENT][INFO] Fixed the RecipeBook
```
(Case II & III. Initialization log is also omitted.)
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.2.2618
- Crafttweaker: 4.1.5

#### Your most recent log file where the issue was present: 

https://pastebin.com/ZQQL8Lbk

**Comment by kindlich** [comment]
@Estiv 
Are you in the CrT discord or anything so I can send you something to test?

**Comment by Weisstrieb** [comment]
I'll join CrT Discord
