### ISSUE TITLE
BUG unable to remove recipe with crafttweaker

### ISSUE THREAD

**Issue by collwee** [CraftTweaker/CraftTweaker#472]
#### Issue Description:
i can remove recipe from other mods with crafttweaker without problem but with sg craft the recipe cannot be removed

#### What happens:

the recipe are not removed

#### What you expected to happen:

the recipe to be removed

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): https://pastebin.com/FzeuKhcd

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.2
- Forge:14.23.2.2613
- Crafttweaker: 1.12-4.1.5
-sgcraft: SGCraft-1.14.3-mc1.12.2  http://solder.almuramc.com/downloads/SGCraft-1.14.3-mc1.12.2.jar

#### Your most recent log file where the issue was present: 

https://gist.github.com/collwee/38a2498ec61f5507689d4f8473f7a19f

**Comment by collwee** [comment]
[https://github.com/AlmuraDev/SGCraft/issues/8](url)

**Comment by collwee** [comment]
https://github.com/AlmuraDev/SGCraft/issues/8

**Comment by jaredlll08** [comment]
Replied on the other thread.
