### ISSUE TITLE
[1.12.2]Some issue with removing some projecte recipes

### ISSUE THREAD

**Issue by NanayaQ** [CraftTweaker/CraftTweaker#473]
#### Intro:
I was trying to remove the original recipes from projecte and try making it harder to craft some of the items for late game purposes using /mtrm and/or /ctgui.

#### Issue Description:
Adding new recipes and remove some recipes (some from tinkers) works fine, however I am not able to remove the original recipes from projecte: **projecte:item.pe_philosophers_stone**, **projecte:transmutation_table**, and **projecte:item.pe_transmutation_tablet**, I tried it with both /mtrm and /ctgui to remove it however it cannot be remove. I also check projecte .conf file there was a **B:altCraftingMat=false** I set it to true and still nothing.

#### What happens:

Removing the original recipes from some item in projecte.

#### What you expected to happen:

the original recipes should have been remove.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

From MTRM
https://pastebin.com/TqkwYAat

From CTGUI Craftingtable
https://pastebin.com/e06jB51G

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

crafttweaker.log
https://pastebin.com/3RPZJQiQ

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.2.2619
- Crafttweaker: 1.12-4.1.5

#### Your most recent log file where the issue was present: 
^**above**^
P.S I am assuming projecte recipe is hardcoded/register? I don't know for sure since everything else work fine... or maybe it doesnt play well with the dragon egg?

Edit: Just want to make sure if it isn't CT then I will go bug with projecte after triple checking with the recipes again...

Edit2: Ah yes I forgot to mention same issue with inventory pets mod as well...

**Comment by jaredlll08** [comment]
Try using just `recipes.remove()` instead of `recipes.removeShaped()`

**Comment by NanayaQ** [comment]
I just tried now it throws out some errors:

CT logs
https://pastebin.com/05KpU3Mu

ctgui (going to assume the same is going to happen with /mtrm)
https://pastebin.com/94LRpYry

**Comment by jaredlll08** [comment]
read the wiki. `recipes.remove()` just takes the output item, no input items

**Comment by NanayaQ** [comment]
ooof, I goof... It works perfectly now.

I probably will just use that method for now on then relying the gui commends for now on for removing recipes.

Thanks! Solved
