### ISSUE TITLE
item not being added to oredict entry

### ISSUE THREAD

**Issue by dancc7t** [CraftTweaker/CraftTweaker#474]
#### Issue Description:
Hello, i am creating a new modpack but many items  of several mods are not oredicted properly (who knows why but that is troublesome to me, its wasting a lot of my time to make the modpack), so i have to use the IOreDictEntry add fuction to add them to their oredicts

#### What happens:
The item i added (copper ingot)  to oredict doesn't have an oredict

#### What you expected to happen:
when i use /ct hand on a copper ingot i expect to see an oredict for that item

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/Uqch6697

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/MJcW3kWi

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: forge1.12.2-14.23.2.2619
- Crafttweaker:  CraftTweaker2-1.12-4.1.5

#### Your most recent log file where the issue was present: 
https://pastebin.com/byLQdCeB

(i removed the rest of my scripts which changed a lot of recipes, that explains all that crafttweaker messages)

Thanks.

**Comment by jaredlll08** [comment]
Can't reproduce.

```
<ore:ingotIron>.add(<minecraft:diamond>);
```

![image](https://user-images.githubusercontent.com/5553605/36931945-868c0aac-1ec9-11e8-8605-fcbff07827d7.png)

![image](https://user-images.githubusercontent.com/5553605/36931952-e0865cba-1ec9-11e8-9a03-6993777ea5eb.png)
