### ISSUE TITLE
CraftTweaker JEI support is added even if JEI is not present

### ISSUE THREAD

**Issue by NotAVerb** [CraftTweaker/CraftTweaker#486]
#### Issue Description:
CraftTweaker JEI support is added to instances that do not have JEI installed.

#### What you expected to happen:
I expected CT2 to only add JEI support if JEI was installed.

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 2623
- Crafttweaker: 4.1.4

**Comment by jaredlll08** [comment]
The JEI support is being moved to modtweaker anyway.
