### ISSUE TITLE
Vanilla Recipe Book search breaks when CraftTweaker is installed

### ISSUE THREAD

**Issue by NotAVerb** [CraftTweaker/CraftTweaker#487]
#### What happens:
Entering in any characters to the recipe book's search bar empties the screen of recipes.

#### What you expected to happen:
I expected using the search bar to return relevant recipes rather than nothing.

#### Script used
This issue occurs without any scripts being loaded.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2623
- Crafttweaker: 4.1.4

#### Your most recent log file where the issue was present: 
https://gist.github.com/NotAVerb/1bdd0913eef6ef4ce5f3b50a04920bba

**Comment by jaredlll08** [comment]
update crafttweaker.

**Comment by NotAVerb** [comment]
Ah, My apologies. I missed the update.
Testing.

The issue still seems to be present.

**Comment by laserlemons** [comment]
I had this same problem on version 1.12-4.1.5 but it seems to have gone away since reinstalling my mod pack. It doesn't make sense because the mod pack has never used any version previous to 4.1.5.

**Comment by jaredlll08** [comment]
There is no fix to this, the recipe book it horribly coded and it just isn't made to be changed.
