### ISSUE TITLE
Parsing error loading built-in advancement

### ISSUE THREAD

**Issue by Tollainmear** [CraftTweaker/CraftTweaker#490]
#### Issue Description:

-    I setup the crafttweaker in Minecraft server 1.12.2, after editing `MineTweakerRecipeMaker.zs` I restart the server, and the server throw a tons of exceptions witch start with 'Parsing error loading built-in advancement' whill world loading.

#### What happens:

-    Exceptions appeared but recipes was indeed modified, so I think these exceptions may not made any mistakes. The matter is why the exceptions appeared.

#### What you expected to happen:

-    I think too many exceptions thrown was not a good appearance, I want to know why and how to make it clear.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

[MineTweakerRecipeMaker.zs](https://gist.github.com/Tollainmear/b9382f34139438e8dcc741bf2bb8e3fc)

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

[crafttweaker.log](https://gist.github.com/Tollainmear/dacce2b1cee198000544266708de4c72)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:  1.12.2
- Forge: 14.23.2.2611
- Crafttweaker: 4.1.5

#### Your most recent log file where the issue was present: 

[latest.log](https://gist.github.com/Tollainmear/6c02935b3881358d9b269d122c577c35)

#### Tips:
-    Ignore the Chinese characters please XD

**Comment by jaredlll08** [comment]
This is caused by the recipe needed for advancements not being there. There isn't much that we can do.

**Comment by Tollainmear** [comment]
@jaredlll08 , maybe we could give it a un-normal recipe, like a necessary stuff was generated by crafttweaker but could not get in normal, so if there were no recipe and we detect it, we create a new recipe for this could not craft item, so there do have a recipe, but player will never collect them in survival mode, then we solve the exceptions error and make no effect with crafttweaker‘s function.

**Comment by Tollainmear** [comment]
and I also found that, the client could not update the script with the server, it make a trouble that client could also check the recipes from client‘s’ JEI but could not craft them in crafting table , so many player will ask the server owner why that happend, so why don‘t update the script when join to server?

**Comment by jaredlll08** [comment]
Other mods replace the deleted recipe with a new recipe and it breaks things.

Scripts are not sent to the client anymore due to Forge changes. Nothing we can do about that.
