### ISSUE TITLE
Crash in combination with tinkers tool crafting

### ISSUE THREAD

**Issue by Henri1992** [CraftTweaker/CraftTweaker#492]
#### Issue Description:
To be able to remove the floating islands, I needed to add a few recipes into the game. I am not to familiar with changing recipes, but I think I done it the right way?

#### What happens:
Whenever I try to craft a tool with tinkers, the game crashes

#### What you expected to happen:
That tinkers would give me a tool

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue): 
https://pastebin.com/v1gHxtr6

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/u5yhQxLt

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.2.2623
- Crafttweaker: 4.1.5

#### Your most recent log file where the issue was present: 

https://pastebin.com/YPnP7333

**Comment by kindlich** [comment]
Most likely fixed in dev

**Comment by Henri1992** [comment]
It is fixed in 4.1.6, I will close the issue. Thanks for the fix!
