### ISSUE TITLE
[1.12.2] Forestry Workbench incorrectly shows the recipe if it has been changed through a СraftTweaker

### ISSUE THREAD

**Issue by KorDum** [CraftTweaker/CraftTweaker#493]
#### Issue Description:
Forestry Workbench incorrectly shows the recipe if it has been changed through a СraftTweaker.
I posted this into Forestry issue tracker: https://github.com/ForestryMC/ForestryMC/issues/2029
They said that the problem is not in Forestry.

#### What happens:
I changed some recipes with CraftTweaker script and and got a visual bug in Worktable. For examples see screenshots: 2 different recipes don't show me result (but left mouse click can craft it correctrly). Displayed as 64 diamonds.

In singleplayer there is no bug. But if multiplayer + server — there is a bug.
I created simple modpack (without ModTweaker)

Example screenshot:
![image](https://user-images.githubusercontent.com/1331559/37250735-c9004d9e-2513-11e8-845d-b0294d7e28af.png)

#### Script used
https://gist.github.com/KorDum/2bc595d2de81f10351dfa50593bb105a

#### Minetweaker.log file
https://gist.github.com/KorDum/fe5212b8619cf2752a2289e4ebe29501

____
#### Affected Versions (Do *not* use "latest"):

- Forge 14.23.2.2611
- Forestry 5.8.0.250
- CraftTweaker 4.1.5
- MTLib 3.0.3

**Comment by Ommina** [comment]
You are ensuring that the script is installed on both the server and the client?

**Comment by KorDum** [comment]
Yes.

**Comment by kindlich** [comment]
Most likely fixed in dev

**Comment by KorDum** [comment]
In new version it's fixed. Thanks!
