### ISSUE TITLE
Could Not Resolve?

### ISSUE THREAD

**Issue by DonMegel** [CraftTweaker/CraftTweaker#494]
#### Issue Description:
I created the mod pack. The problem is I can not remove or edit any recipes from Vics Modern Warefare Mod. https://minecraft.curseforge.com/projects/vics-modern-warfare-mod

#### What happens:
Series of "Could not resolve" errors but also a host of 00s and other nonsense in the log file.

#### What you expected to happen:
I wanted to change the recipes and or remove them. For testing I reduced it to a single item, a bullet

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/itDr5KME

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/mj4vKX5E

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.2.2619
- Crafttweaker: 1.12-4.1.5

#### Your most recent log file where the issue was present: 
I'm not sure which log you want, my latest fml client log said it exceeded pastebin size limits

**Comment by jaredlll08** [comment]
Vics modern warfare mod isn't supported. They don't do anything at the right time.
