### ISSUE TITLE
Suggestion: Additional Furnace Tweaks

### ISSUE THREAD

**Issue by Kazerima** [CraftTweaker/CraftTweaker#496]
I'm working on a modpack lately, and I've run into a roadblock involving some furnace balance changes I'd like to make.
Could functionality be added to change the cook time of items in the furnace, and to allow players to use null recipes? By default you can only modify fuel burn times and cannot set up furnaces to burn fuel without an item in the top slot.

**Comment by jaredlll08** [comment]
It isn't possible to have some items cook for shorter or longer amount of times, the furnaces runs at a set time.

You can't have recipes that have a null input, that is a limitation set by the furnace.
