### ISSUE TITLE
Trying to retrieve mod.version results in Invalid expression, last token: version

### ISSUE THREAD

**Issue by Guinaro** [CraftTweaker/CraftTweaker#501]
#### Issue Description:
Trying to use the IMod.version Zengetter results in an invalid expression

#### What happens:
Error parsing test.zs:2 -- Invalid expression, last token: version

#### What you expected to happen:
Being able to use version as documented at https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Game/Mods/#imod

Logs and script: https://gist.github.com/Guinaro/0426d82f5034502f3dfcccc30d908262

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.2.2618
- Crafttweaker: 1.12-4.1.6

**Comment by kindlich** [comment]
Should be fixed since at least the latest CrT release, can you confirm?

**Comment by jaredlll08** [comment]
Fixed in latest
