### ISSUE TITLE
Integrated Dynamics CT integration breaking in recent CT versions

### ISSUE THREAD

**Issue by rubensworks** [CraftTweaker/CraftTweaker#502]
#### Issue Description:
I received a report that ID's CT integration is breaking: https://github.com/CyclopsMC/IntegratedDynamics/issues/563

Nothing has changed to the integration for a long time; https://github.com/CyclopsMC/IntegratedDynamics-Compat/tree/master-1.12/src/main/java/org/cyclops/integrateddynamicscompat/modcompat/minetweaker/handlers

Only CT itself seems to have changed, so I _assume_ something broke on your end. Or I did something wrong before, which only now seems to break. Eitherway, I need some pointers, as the error doesn't help me much...

#### What happens:

A `Bad type on operand stack` error occurs when loading the script. I assume this has something to do with the `@Optional`s I use. These used to work just fine before, so I have no idea why they are not working now anymore. As far as I can see, this should work. Please correct me if I'm wrong.

#### What you expected to happen:

Backwards compatiblity 😢 

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://github.com/CyclopsMC/IntegratedDynamics/wiki/MineTweaker

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/RZQPvnQb

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.2.2624
- Crafttweaker: CraftTweaker2-1.12-4.1.6

#### Your most recent log file where the issue was present: 

https://pastebin.com/RZQPvnQb

**Comment by jaredlll08** [comment]
You're right, this is a CrT change.

@Optionals should only be at the end of a method, infact they only work at the end of the method, so we decided to alert people about that, since right now, your optionals are actually all required.
