### ISSUE TITLE
File path issues on linux with .zip

### ISSUE THREAD

**Issue by justinrusso** [CraftTweaker/CraftTweaker#504]
https://gist.github.com/justinrusso/8d4fe7ff1393fc03a6a249a9aee87cf8

**Comment by Bendder** [comment]
Adding to this with my crafttweaker log.  Currently not able to have users connect to my Sevtech Server because of this (I believe):
[crafttweaker.log](https://github.com/CraftTweaker/CraftTweaker/files/1844707/crafttweaker.log)

**Comment by BloodWorkXGaming** [comment]
Have you tried unzipping the file and just having it run from the files itself?
If you try that keep in mind to move the zip file out of the /scripts/ folder.

**Comment by justinrusso** [comment]
@BloodWorkXGaming That fixes it, We've already pushed out a patch that just has the scripts extracted

**Comment by BloodWorkXGaming** [comment]
Awesome, have you noticed any major increase of file size or performanceloss to make it worth investigating this issue further?

**Comment by justinrusso** [comment]
Its about 1 MB vs 200KB. I think for the sake of saving headaches we'll just keep it unzipped.
