### ISSUE TITLE
Can't remove Netherending Ores OreDict entries

### ISSUE THREAD

**Issue by trabpukcip** [CraftTweaker/CraftTweaker#505]
#### Issue Description:
Trying to remove an Ore Dictionary entry for Netherending Ores.

#### What happens:
Fails to remove the ore dictionary entry and writes errors to the CraftTweaker log.

#### What you expected to happen:
Remove the ore dictionary entry as requested.

#### Minetweaker.log file: https://gist.github.com/trabpukcip/61c7d07aed07b4cb2bf4fdbc19215929

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.2.2611
- Crafttweaker: CraftTweaker2-1.12-4.1.6.jar

#### Your most recent log file where the issue was present: 

fml-junk-earlystartup.log: https://gist.github.com/trabpukcip/bb4c341a4ea8f2c0e95d7e93acb15fb7
latest.log: https://gist.github.com/trabpukcip/93becec00f4ab7e6283a608dc81d92cd
fml-client-latest.log: https://gist.github.com/trabpukcip/6ab59873fdfdb6d15058853bb669584e

#### Notes:

Alpha version for current NetherendingOres (as used in testing, with -a1 suffixed): https://github.com/ICannt/Netherending-Ores/releases/tag/1.1.2-a1
Repo: https://github.com/ICannt/Netherending-Ores
Official Builds: https://minecraft.curseforge.com/projects/netherending-ores
Have tried many locations for loading the OreDict, currently hangs off entity loading to load early as possible. Preinit crashes as blocks and items are using registry events, Init and PostInit simply don't help.
I could be doing something entirely dumb >.> <.<

**Comment by kindlich** [comment]
You are tryint to remove from an [IItemStack](http://crafttweaker.readthedocs.io/en/latest/#Vanilla/Items/IItemStack/) which is not possible, you can only remove from an [IOreDictEntry](http://crafttweaker.readthedocs.io/en/latest/#Vanilla/OreDict/IOreDictEntry/)

You need to use something like
```
val ore = <ore:oreQuartz>;
ore.remove(<netherendingores:ore_other_1>);
```
