### ISSUE TITLE
My N00B problems (No such member: mekanism) (Truncated class file)

### ISSUE THREAD

**Issue by Sibith** [CraftTweaker/CraftTweaker#507]
#### Intro:
I'm gonna be honest: I'm a complete n00b to crafttweaker and have no freaking idea what i'm doing. I tried to follow the tutorial on the wiki because i wanted to change a couple crafting recipes in my mod pack, but the tutorial on the wiki isn't all that straight forward :/ So I'm using the portal gun mod, the mekanism mod, and the techgun mod. I wanted to make it so ender pearl dust for the portalguns could be made in the crusher from the mekanism mod instead of the furnace. I successfully got rid of the original furnace recipe. (I was pumped to see I got a script to work). The problem came when I attempted to make a script that would let me make ender pearl dust from ender pearls in the crusher. I tried to add a crusher recipe script but ended up with some weird errors that probably make me look like a n00b.

#### Issue Description:
I get the "No such member: mekanism" ERROR
and the "Truncated class file" ERROR

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue): The script giving me issues:
https://pastebin.com/MWRzmP38

The other script I'm using in case it's causing problems(Don't think it is, just thought I'd include it):
https://pastebin.com/5qFD1PUd

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): https://pastebin.com/uTAJkAkB

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.2
- Forge:14.23.2.2611
- Crafttweaker: 1.12-4.1.6

#### Your most recent log file where the issue was present: 
https://pastebin.com/eeWyHrng

**Comment by jaredlll08** [comment]
We don't add mekanism support. Make an issue with them.
