### ISSUE TITLE
[1.11] JEI.hide on server throws NPE

### ISSUE THREAD

**Issue by Terpo** [CraftTweaker/CraftTweaker#508]
#### Issue Description:
JEI.hide does not seem to be working as expected.

#### What happens:
I have a private modpack and try to hide some items from JEI. When I was creating my script in singleplayer everything is working perfectly. After copying the script to the server and joining it I am getting a chat message with a "null" exception. I already added a vanilla item to make sure it is not a mod problem.

#### What you expected to happen:
No error on serverside and the idems should be hidden.

#### Script used:
https://gist.github.com/Terpo/b613006f22e3ea5f23498afb85aa3d47

#### Minetweaker.log file:
https://gist.github.com/Terpo/c5a91a7682fdf82f0516192edb4ddab0

____
#### Affected Versions:

- Minecraft: 1.11.2
- Forge: 13.20.1.2563
- Crafttweaker: CraftTweaker-1.11.2-3.0.26.jar
- JEI: jei_1.11.2-4.5.1.296.jar

**Comment by jaredlll08** [comment]
1.11 isn't supported anymore.
