### ISSUE TITLE
Error could not find scripts

### ISSUE THREAD

**Issue by Yarden-zamir** [CraftTweaker/CraftTweaker#510]
#### Issue Description:
I have two files, one is _Botania.zs and one is functions.zs. and when i call a function from the functions file using scripts.functions.test(); it says in the log ```ERROR: _Botania.zs:22 > could not find scripts```
#### What happens:
The script crashes and throws an error (see log)

#### What you expected to happen:
I expect the function (```
function test(){
  print("test");
}```) to be called as per the [docs](http://crafttweaker.readthedocs.io/en/latest/#AdvancedFunctions/Cross-Script_Reference/) and print "test"

#### Script used
[_Botania.zs.txt](https://github.com/CraftTweaker/CraftTweaker/files/1872182/_Botania.zs.txt)
[functions.zs.txt](https://github.com/CraftTweaker/CraftTweaker/files/1872184/functions.zs.txt)
(I added .txt so that i can upload them here)
#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
[crafttweaker.log](https://github.com/CraftTweaker/CraftTweaker/files/1872178/crafttweaker.log)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.2.2651
- Crafttweaker: 4.1.6
- modtweaker: 4.0.9
#### Your most recent log file where the issue was present: 
[latest.log](https://github.com/CraftTweaker/CraftTweaker/files/1872208/latest.log)

**Comment by kindlich** [comment]
Either rename your functions script or use a priority preprocessor.
Your botania script is executed before the functions scripts so latter cannot access the prior.

**Comment by Yarden-zamir** [comment]
Can I use folders for that? edit: iirc in the wiki it says they are loaded in "no particular order"

**Comment by Yarden-zamir** [comment]
Ok, I fixed it by adding the functions script into a folder called _first. Is there a better way to do this that will also look elegant? I don't like doing scripts._First.functions.test(); tho its only a pet peeve at this point. edit ok sorry i skipped the part where you say "or use a priority preprocessor" im gonna look into that

**Comment by BloodWorkXGaming** [comment]
Add `#priority 100` to the script

Yarden zamir <notifications@github.com> schrieb am Di., 3. Apr. 2018, 18:11:
