### ISSUE TITLE
[Question] Radiation Effect?

### ISSUE THREAD

**Issue by DonMegel** [CraftTweaker/CraftTweaker#512]
Would it be possible to simulate radiation by giving someone a potion effect when they are holding uranium ore or ingots? Would it be something like this? 

`(<minecraft:thingy>.withTag({Potion: "minecraft:poison"})`

**Comment by jaredlll08** [comment]
wat

**Comment by DonMegel** [comment]
So, is that a "no, you can't do this?"

**Comment by jaredlll08** [comment]
this is a "I don't know what you and you've given no info as to what you actually want"

**Comment by DonMegel** [comment]
My apologies. I would like to simulate the effect of radiation by causing the player to get a potion effect when they pick up certain ores or items, specifically Uranium. I am not sure if that is possible with CT and if it is possible, how would I do that?

**Comment by DonMegel** [comment]
What additional information is needed?

**Comment by DonMegel** [comment]
I might be able to use events.onplayerpickup
