### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by HurtsAsHell** [CraftTweaker/CraftTweaker#513]
`recipes.removeShaped(<immersiveengineering:metal:30>, [[<ore:ingotCopper>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:31>, [[<ore:ingotAluminum>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:32>, [[<ore:ingotLead>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:33>, [[<ore:ingotSilver>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:34>, [[<ore:ingotNickel>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:35>, [[<ore:ingotUranium>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:36>, [[<ore:ingotConstantan>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:37>, [[<ore:ingotElectrum>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:38>, [[<ore:ingotSteel>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:39>, [[<minecraft:iron_ingot>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:40>, [[<minecraft:gold_ingot>, <immersiveengineering:tool>]]);`

Do these lines mean to remove a certain recipe?

**Comment by jaredlll08** [comment]
Read the wiki. It explains what those lines do.

**Comment by HurtsAsHell** [comment]
But as far as it can be written on the wiki, it does not solve my problem; written the recipes to remove, in the game are still visible and, even if I'm not very good in English and I use the google translator, I did not seem to see how to solve the problem; so, would you be so kind to help me or will you continue in your rudeness?

**Comment by jaredlll08** [comment]
You asked if the lines remove a recipe, that is what they are coded to do, I don't know what is wrong, I don't know what you expect to happen, I don't know what doesn't happen, you haven't even given me a game version or the log file that was asked for in the template, all you've given me is a bunch of lines, and asked if they are meant to remove a recipe.

what is your primary language? we may have an intermediary (I know we have people who speak German, and there is even a wiki for simplified Chinese)

**Comment by HurtsAsHell** [comment]
I speak italian; [https://www.dropbox.com/s/ibfpycetqwqkcsj/crafttweaker.log?dl=0](url) ; the game version is 1.12.2
I want to remove the certain recipes that I am going to list below
recipes.removeShaped(<immersiveengineering:metal:30>, [[<ore:ingotCopper>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:31>, [[<ore:ingotAluminum>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:32>, [[<ore:ingotLead>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:33>, [[<ore:ingotSilver>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:34>, [[<ore:ingotNickel>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:35>, [[<ore:ingotUranium>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:36>, [[<ore:ingotConstantan>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:37>, [[<ore:ingotElectrum>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:38>, [[<ore:ingotSteel>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:39>, [[<minecraft:iron_ingot>, <immersiveengineering:tool>]]);
recipes.removeShaped(<immersiveengineering:metal:40>, [[<minecraft:gold_ingot>, <immersiveengineering:tool>]]);


Can u tell me what is the problem?
