### ISSUE TITLE
Client/Server Crash , java.lang.NoClassDefFoundError: betterwithmods/common/registry/bulk/recipes/CauldronRecipe

### ISSUE THREAD

**Issue by ProsperCraft** [CraftTweaker/CraftTweaker#514]
#### Issue Description:
Server crash, and client crash relating to better with mods.

___
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.2.2628-universal.jar, and forge-1.12.2-14.23.2.2654-universal.jar
- Crafttweaker: CraftTweaker2-1.12-4.1.6.jar
- BetterWithMods-1.12-2.1.0

#### Your most recent log file where the issue was present: 
Client Crash-
https://gist.github.com/ProsperCraft/503d56dc1bfe1f663efc73e2638a927f
Server Crash-
https://paste.fedoraproject.org/paste/4KfDgrbK7Ucv-kKqQsAkWg
https://gist.github.com/ProsperCraft/1282029a38b514e5de2e4cb395e2ede3 - updated forge.

**Comment by jaredlll08** [comment]
don't use alpha versions -_-

update modtweaker.
