### ISSUE TITLE
stack cannot be null [1.12.2]

### ISSUE THREAD

**Issue by Ninjakili** [CraftTweaker/CraftTweaker#515]
#### Issue Description:
I've got a problem with 1.12.2: I want to change the recipes of ender IO items in the crafting table (remove and add) but the error: "Error excecuting {[0:crafttweaker]:recipes.zs}: stack cannot be null"
appears.

#### What happens: When I load in a minecraft world
It just says: "ERROR: [crafttweaker]: Error excecuting {[0:crafttweaker]:recipes.zs}: stack cannot be null" inthe chat

#### What you expected to happen:
I expect to not get any errors and that the recipes are changed

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/n87teqsN

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/tLKP97Ez

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: forge-14.23.2.2654
- Crafttweaker: 1.12-4.1.6

#### Your most recent log file where the issue was present: 
https://pastebin.com/KjK6pUM5

[pastebin/gist/etc link here]

**Comment by kindlich** [comment]
No not use `<minecraft:air>` use `null`
