### ISSUE TITLE
Can u help me?

### ISSUE THREAD

**Issue by HurtsAsHell** [CraftTweaker/CraftTweaker#516]
I just need to know what I skipped, following the guide I do not understand what is missing;

mods.immersiveengineering.Excavator

//Exavetor addRecipe
//mods.immersiveengineering.Excavator.addMineral(String name, int mineralWeight, double failChance, String[] ores, double[] chances, @Optional int[] dimensionWhitelist, @Optional boolean blacklist);
mods.immersiveengineering.Excavator.addMineral("Iron Ore", 25, 0.5,["btt:deep_iron_ore"], [0.02]);

**Comment by jaredlll08** [comment]
We don't add immersiveengineering support, so I can't tell you where you went wrong.
