### ISSUE TITLE
scripts are not displayed in jei

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#517]
#### Intro:
After I wrote to the makers of Jei, they said I should report here. namely, it is that jei does not display the scripts that are on the server but are not present in the client. we ourselves have some servers. Since we have made some minor changes but these are not displayed in the client itself, since they do not have script itself.

https://github.com/mezz/JustEnoughItems/issues/1163

At that time with minetweaker / nei everything had worked wonderfully. but not today. could not you implement that again?

#### Script used 
All scripts

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2 - 1.12.2
- Forge: no need
- Crafttweaker: all version

**Comment by ghost** [comment]
people who have the scripts, so from our launcher itself, see this here: https://screen.ilikepudding.tk/x38a16uos9.png

the others do not see it, because the script does not exist on the client itself. although the server passes on the information that it can not be crafted, but only if you try to craft it.

**Comment by jaredlll08** [comment]
The server no longer sends the script to the client, blame forge.
