### ISSUE TITLE
Recipes by UniDict not being removed by CraftTweaker

### ISSUE THREAD

**Issue by TheDeviantCrafter** [CraftTweaker/CraftTweaker#518]
#### Issue Description:

When disabling most items with CraftTweaker, the recipe and the corrosponding JEI entry are removed as expected. Recipes added by UniDict, however, do not get removed.

#### What happens:

Both recipes for Thermal Foundation's iron plate are still enabled, even though the script is supposed to remove them.

#### What you expected to happen:

I expected the script to disable all shapeless crafting recipes for Thermal Foundation's iron plate.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/n0peBULb

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/AhcpfAkd
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.2.2654
- Crafttweaker: 4.1.6

#### Your most recent log file where the issue was present: 

https://pastebin.com/vVRJiAQx

![image](https://user-images.githubusercontent.com/18755309/38763223-6a1a44ac-3f5c-11e8-9a08-aa6a92b1e401.png)

**Comment by TheDeviantCrafter** [comment]
Also posted this to UniDict's issues page: https://github.com/WanionCane/UniDict/issues/89

**Comment by jaredlll08** [comment]
Unidict adds recipes after we remove them.
