### ISSUE TITLE
transformDamage() not working

### ISSUE THREAD

**Issue by septemberWaves** [CraftTweaker/CraftTweaker#521]
#### Issue Description:
The item transformer ".transformDamage()" does not work.

#### What happens:
An item with the ".transformDamage()" transformer defined in the recipe gets consumed when the recipe is crafted, like any other crafting component. I have tested both with and without a damage amount defined in the brackets; both cases result in the entire item being consumed.

#### What you expected to happen:
An item with the ".transformDamage()" transformer defined in the recipe _should_ only be damaged for one point of damage, or for the amount of damage defined inside the brackets.

#### Script used:
https://pastebin.com/XwCkfSJ2

Note: I've only pasted the imports, and the recipe that causes the problem. The rest of the file is just removing and adding vanilla crafting table recipes; all of that functionality works flawlessly and the only problem is the item transformer failing to function.

#### Minetweaker.log file:
https://pastebin.com/mTSAjmP0

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.2.2654
- Crafttweaker: 1.12-4.1.6

#### Your most recent log file where the issue was present: 
https://pastebin.com/qtvdCJD0

If this is the wrong log file (it's the most recent log file from the "logs" folder), let me know where to find the correct one and I will create a pastebin link for it.

**Comment by jaredlll08** [comment]
this may be an issue with the IE hammer, they may use NBT for damage
try it with another item (like a diamond pickaxe)

**Comment by jaredlll08** [comment]
Can't reproduce.

```

recipes.addShapeless("diamonds", <minecraft:diamond>, [<minecraft:diamond_sword>.transformDamage(),<minecraft:stone>]);
```
