### ISSUE TITLE
Top 2 commands from /ct help get cut off of chat

### ISSUE THREAD

**Issue by GazbonicAcid** [CraftTweaker/CraftTweaker#522]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.
When I used /ct help, /ct biomes and /ct blockinfo got cut/dropped off by chat history limit and don't show up

#### What happens:
after scrolling all the way up, only goes up to /ct blocks

#### What you expected to happen:
after scrolling all the way up, go up to the first command /ct biomes

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
Not Applicable

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/GazbonicAcid/fa69359cb8140667607feeff2c824266

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2655
- Crafttweaker: CraftTweaker2-1.12-4.1.6

#### Your most recent log file where the issue was present: 

Not Applicable

P.S. As this is a compatibility issue with the base Minecraft game, you will need to tweak the /ct help command to either do pages (such as "/ct help 1"), or action click browsing of the same.

**Comment by jaredlll08** [comment]
Vanilla issue, can't do anything about it, and just isn't worth the development time, with mods able to add their own sub "/ct" commands.

Also there is always the docs (http://docs.blamejared.com) that list them all.

**Comment by GazbonicAcid** [comment]
Apparently you didn't read my "P.S.", which shows you **_can_** do something to fix it.
And doing my suggestion to fix it would be more worth the development with a bunch of mods that add to /ct help

> P.S. As this is a compatibility issue with the base Minecraft game, _you will need to tweak the /ct help command to either **do pages (such as "/ct help 1"), or action click browsing of the same**_.

**Comment by BloodWorkXGaming** [comment]
shouldn't be too hard to fix...

**Comment by jaredlll08** [comment]
I believe the latest pr from @BloodWorkXGaming fixed this
