### ISSUE TITLE
Crash with CT / JEI

### ISSUE THREAD

**Issue by brisingraerowing** [CraftTweaker/CraftTweaker#523]
#### Issue Description:
Crash between CT and JEI
#### What happens:
Crash

#### What you expected to happen:
Game loads

#### Minetweaker.log file
See Crash Log Gist below

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2669
- Crafttweaker:  4.1.7

#### Your most recent log file where the issue was present: 
[Crash Log / CT Log](https://gist.github.com/BrisingrAerowing/d4c1303f12896235ad46357a809b3b25)

**Comment by jaredlll08** [comment]
update CRT.
