### ISSUE TITLE
Crafttweaker not visible in commands list in permissions plugin

### ISSUE THREAD

**Issue by prokopiy** [CraftTweaker/CraftTweaker#524]
#### Issue Description:
LuckPerms fo SpongeForge plug-in does not allow you to set permissions for your mod version for 1.11.2. Crafttweaker not visible in commands list. For version 1.12.2 it works correctly. Please fix it.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/YW8czw8N
https://pastebin.com/azt6MPQb

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 2476
- Crafttweaker: 3.0.26

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
https://pastebin.com/AhAJq6Kj

**Comment by jaredlll08** [comment]
We don't do anything with permission nodes, and we don't support 1.11.2

**Comment by prokopiy** [comment]
I am use 1.11.2 because in 1.12.2 version not supported JEI integration (do not change the recipes in JEI). With this can be that the do?
