### ISSUE TITLE
Why recipes are not updated?

### ISSUE THREAD

**Issue by prokopiy** [CraftTweaker/CraftTweaker#525]
#### Issue Description:
After restart server recipes works on craftingtable, but it does not appear in JEI.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/NHri4Vv5

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/vB3G6Ryh

#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2611
- Crafttweaker: CraftTweaker2-1.12-4.1.6.jar, modtweaker-4.0.10.jar, MTLib-3.0.4.jar

#### Your most recent log file where the issue was present: 

https://pastebin.com/7bWTnMnS

**Comment by kindlich** [comment]
Recipes are no longer synced from client to server, you need to put them not only on the server but on the client as well.
