### ISSUE TITLE
CraftTweaker2-1.12-4.1.6 creates an empty minetweaker.log at server start, then never uses it

### ISSUE THREAD

**Issue by UnixRonin** [CraftTweaker/CraftTweaker#527]
#### Issue Description:
CraftTweaker2-1.12-4.1.6 creates an empty minetweaker.log at server start, then never uses it

#### What happens:
See above.  Both minetweaker.log and crafttweaker.log are created, but only crafttweaker.log is ever used.

#### What you expected to happen:
CraftTweaker2 uses crafttweaker.log now.  It shouldn't be still creating minetweaker.log as well.

#### Script used:
n/a

#### Minetweaker.log file
n/a

#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.3.2655
- Crafttweaker: 1.12-4.1.6

#### Your most recent log file where the issue was present: 
n/a

**Comment by jaredlll08** [comment]
No we don't.
