### ISSUE TITLE
Client aren't receiving server defined tooltips

### ISSUE THREAD

**Issue by LemADEC** [CraftTweaker/CraftTweaker#528]
#### Issue Description:
As of CraftTweaker2-1.12-4.1.6, clients are receiving server side updates, including recipes, tooltips, etc.

#### What happens:
when hosting a public FTB modpack (Revelation in our case here), we can't inform players through tooltips or fix issues by changing recipes anymore.

#### What you expected to happen:
Being able to inform players of changed recipes without relying to signs and books.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
n/a

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/Q15Jn5uu

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.3.2655
- Crafttweaker: 1.12-4.1.6

#### Your most recent log file where the issue was present: 
n/a

**Comment by jaredlll08** [comment]
Scripts aren't sent to the client anymore, blame Forge.

**Comment by LemADEC** [comment]
Please share the bug report to forge then

**Comment by jaredlll08** [comment]
It's not a bug, they lock the registry before the main menu, we can't do
stuff after the Manu is shown anymore.

**Comment by LemADEC** [comment]
so the issue was never reported to them?

**Comment by jaredlll08** [comment]
It was a "feature" they added, this isn't going to get "fixed".

**Comment by LemADEC** [comment]
even if recipes are readonly registry, we should still be able to synchronize other properties like tooltips, no?

**Comment by jaredlll08** [comment]
That is just asking for a mess to happen.

**Comment by LemADEC** [comment]
I understand they're not against it. Maybe try discussing with them on Discord would help?

**Comment by jaredlll08** [comment]
Dude. I am not add g back server to client stuff, it will break everything and it is not worth it. You are the only person in the past year that has complained about it this much and doesn't understand that it is a Forge issue and isn't going to be changed.

**Comment by LemADEC** [comment]
https://discord.gg/UvedJ9m
