### ISSUE TITLE
Logs in logs folder, please!

### ISSUE THREAD

**Issue by LemADEC** [CraftTweaker/CraftTweaker#529]
#### Issue Description:
Mod is generating logs in the root folder.

#### What happens:
Pollution of modpack root folder.

#### What you expected to happen:
Logs file in the logs folder where it should be

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
n/a

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
n/a
____
#### Affected Versions (Do *not* use "latest"):
Minecraft: 1.12.2
Forge: 1.12.2-14.23.3.2655
Crafttweaker: 1.12-4.1.6

#### Your most recent log file where the issue was present: 
n/a

**Comment by LemADEC** [comment]
Also, on a side note, the issue template refers to the hold log file name minetweaker.log

**Comment by jaredlll08** [comment]
Won't change, it's been there too long to change without causing confusion
