### ISSUE TITLE
"/CTGUI" is unknown command.

### ISSUE THREAD

**Issue by shelbykauth** [CraftTweaker/CraftTweaker#530]
#### Intro:
I am new to CraftTweaker.  I'm trying to get it functional.  Small things, like a wool->string recipe and a way to get more ender pearls.  But I'm having a hell of a time with this.  It doesn't help that I'm trying to use LuckPerms, and the permissions for each mod aren't listed and I don't have permission to run the "/help" command.  But that is not the problem I'm facing.  That's "You don't have permission."  This is "Unknown command."

And yes, I am aware that I have to restart the game to see the changes.  That has been made quite clear from the many posts I've found while trying to look up why I can't use /ctgui.  I am aware that I can use the scripting language.  But I would like to use the gui because to make the ender pearls more difficult (but not impossible), I want to use a bunch of stuff from different mods, and I'm having trouble finding the ids and such.  And to top it all off, I'm using vim to edit any files on my server.  The only saving grace with that is '/ct syntax', which I am so grateful for.

#### Issue Description:
'/ctgui' does nothing.  It is marked as an unknown command.

#### What happens:
"Unknown command.  Try /help for a list of commands."

#### What you expected to happen:
Open a grid to make a crafting recipe

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
N/A

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
Um... I have "crafttweaker.log", not "minetweaker.log"  And it takes forever to load, but here you go. http://termbin.com/oj6t
____
#### Affected Versions (Do *not* use "latest"):
- Minecraft: 1.12.2
- Forge: 14.23.2.2611
- Crafttweaker: CraftTweaker2-1.12-4.1.8.jar

#### Your most recent log file where the issue was present: 
http://termbin.com/atdu

**Comment by BloodWorkXGaming** [comment]
Are you on a server?
If ye, then that's the issue, the command doesn't exist there.

shelbykauth <notifications@github.com> schrieb am Sa., 28. Apr. 2018, 23:49:

**Comment by shelbykauth** [comment]
Oh.
...
That sucks.  Thank you for the quick reply.  That explains a lot.
Can this be a feature request then?  Or is there a reason why it doesn't work so well on servers?

**Comment by jaredlll08** [comment]
It saves files, which just gets messy with client and servers.
Not even HQM allowed server side editing
