### ISSUE TITLE
Immersive Enginiring 1.7.10

### ISSUE THREAD

**Issue by AlexRover** [CraftTweaker/CraftTweaker#531]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
I have a question whether it is possible to make a percentage loss of the MAIN processing product in the crusher, or even without a byproduct, and how to register a new ore vein for the excavator, the version of Minecraft 1.7.10 version of Immersive Enginiring 0.7.7

#### What happens:
Do not appear new veins at the excavator

#### What you expected to happen:
I expected that in the journal of the engineer there will appear veins prescribed by me and the excavator will be able to dig them. And I would also like that the crusher would give me not a whole product, but only with a certain chance, depending on the size of the veins 20%, 40%, 60%, 80% and 200% respectively

#### Script used 
// Excavator Veins

mods.immersiveengineering.Excavator.removeMineral("Bauxite");
mods.immersiveengineering.Excavator.removeMineral("Coal");
mods.immersiveengineering.Excavator.removeMineral("Copper");
mods.immersiveengineering.Excavator.removeMineral("Galena");
mods.immersiveengineering.Excavator.removeMineral("Gold");
mods.immersiveengineering.Excavator.removeMineral("Iron");
mods.immersiveengineering.Excavator.removeMineral("Lapis");
mods.immersiveengineering.Excavator.removeMineral("Lead");
mods.immersiveengineering.Excavator.removeMineral("Magnetite");
mods.immersiveengineering.Excavator.removeMineral("Nickel");
mods.immersiveengineering.Excavator.removeMineral("Platinum");
mods.immersiveengineering.Excavator.removeMineral("Pyrite");
mods.immersiveengineering.Excavator.removeMineral("Quartzite");
mods.immersiveengineering.Excavator.removeMineral("Silver");
mods.immersiveengineering.Excavator.removeMineral("Uranium");
// ================================================================================

// Excavator Mineral

mods.immersiveengineering.Excavator.addMineral("Bismuthinite", 50, 10, ["terrafirmacraft:item.Ore:7"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Cassiterite", 100, 10, ["terrafirmacraft:item.Ore:5"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Garnierite", 50, 10, ["terrafirmacraft:item.Ore:8"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Hematite", 50, 10, ["terrafirmacraft:item.Ore:3"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Limonite", 50, 10, ["terrafirmacraft:item.Ore:11"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Magnetite", 50, 10, ["terrafirmacraft:item.Ore:10"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Malachite", 50, 10, ["terrafirmacraft:item.Ore:9"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Native Copper", 100, 10, ["terrafirmacraft:item.Ore:10"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Native Gold", 50, 10, ["terrafirmacraft:item.Ore:1"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Native Silver", 50, 10, ["terrafirmacraft:item.Ore:4"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Native Platinum", 50, 10, ["terrafirmacraft:item.Ore:2"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Sphalerite", 100, 10, ["terrafirmacraft:item.Ore:12"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Tetrahedrite", 100, 10, ["terrafirmacraft:item.Ore:13"], [100], [0], false);

mods.immersiveengineering.Excavator.addMineral("Bituminous Coal", 100, 10, ["terrafirmacraft:item.Ore:14"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Borax", 50, 10, ["terrafirmacraft:item.Ore:32"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Cinnabar", 50, 10, ["terrafirmacraft:item.Ore:27"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Cryolite", 50, 10, ["terrafirmacraft:item.Ore:28"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Graphite", 50, 10, ["terrafirmacraft:item.Ore:20"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Kaolinite", 50, 10, ["terrafirmacraft:item.Ore:16"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Kimberlite", 20, 10, ["terrafirmacraft:item.Ore:21"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Lapis Lazuli", 50, 10, ["terrafirmacraft:item.Ore:34"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Lignite", 50, 10, ["terrafirmacraft:item.Ore:15"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Saltpeter", 50, 10, ["terrafirmacraft:item.Ore:29"], [100], [0], false);
mods.immersiveengineering.Excavator.addMineral("Sylvite", 50, 10, ["terrafirmacraft:item.Ore:31"], [100], [0], false);
// ================================================================================

//Crusher

// Magnetite
mods.immersiveengineering.Crusher.addRecipe(<tfctech:item.Wrought Iron Dust> * 0.20, <terrafirmacraft:item.Small Ore:10>, 2000); 
mods.immersiveengineering.Crusher.addRecipe(<tfctech:item.Wrought Iron Dust> * 0.40, <terrafirmacraft:item.Ore:59>, 2500);
mods.immersiveengineering.Crusher.addRecipe(<tfctech:item.Wrought Iron Dust> * 0.60, <terrafirmacraft:item.Ore:10>, 3000);
mods.immersiveengineering.Crusher.addRecipe(<tfctech:item.Wrought Iron Dust> * 0.80, <terrafirmacraft:item.Ore:45>, 3500);
mods.immersiveengineering.Crusher.addRecipe(<tfctech:item.Wrought Iron Dust> * 2, <terrathaumcraft:item.transmutedore:10>, 4500, <tfctech:item.Wrought Iron Dust>, 1.00);
// ================================================================================

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.7.10
- Forge: 10.13.4.1614
- Crafttweaker: 3.0.13

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by AlexRover** [comment]
I know that the recipe for a crusher is not correct, it's just that I would show what I want to get

**Comment by kindlich** [comment]
1) Minecraft 1.7.X is no longer supported.
2) [This site](https://ftb.gamepedia.com/Using_MineTweaker_and_Immersive_Engineering) should still be 1.7-friendly
3) You will need to supply the OreDict names to the excavator, no item names.
