### ISSUE TITLE
Craft Tweaker not removing defualt ProjectE recipes, however adding custom ProjectE recipes has no issues. 

### ISSUE THREAD

**Issue by Boostem** [CraftTweaker/CraftTweaker#533]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
When trying to add custom recipes to ProjectE-1.12-PE1.3.0 on Forge 1.12 - 14.21.1.2387, the default ProjectE recipes will not be removed. However, every added recipe works just fine.

#### What happens:
Default Project E recipes are not being removed, while the custom ones are being added just fine.

#### What you expected to happen:
For default recipes to be removed.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/dL6JpPXW

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/BkzdDax7

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: Forge 1.12 - 14.21.1.2387
- Crafttweaker: CraftTweaker2-1.12-4.1.8

#### Your most recent log file where the issue was present: 

https://www.dropbox.com/s/vrqdgqympewnu4p/latest.log?dl=0 (due to the max limit of text share sites, I am personally hosting it on dropbox)

**Comment by jaredlll08** [comment]
There is nothing we can do if a recipe can't be removed. it usually means that the mod author is doing something wrong.

**Comment by Boostem** [comment]
Okay sounds good. I also posted this to ProjectE’s github and awaiting a response! I just wanted to make sure this wasnt an issue with my Version of CT or somehow my syntax. Thank you!
