### ISSUE TITLE
Feature Suggestion - Swap Item Syntax

### ISSUE THREAD

**Issue by Boolyman** [CraftTweaker/CraftTweaker#535]
In the last couple packs I have made, I had the need to replace a certain item in all recipes which it appeared in, and could not find an easy way to do it. 

For instance... if I wanted all recipes which use leather, to use wool instead, I would have to manually recreate all of the recipes using wool.  May I recommend a way to "swap" instances of an item within all recipes at once?  

Something like:

**recipes.replace(<minecraft:leather>, <minecraft:wool>);**

**Comment by jaredlll08** [comment]
You mean like this?
http://crafttweaker.readthedocs.io/en/latest/#Vanilla/Recipes/Crafting/Recipes_Crafting_Table#replace-all-item-ingredients-with-another-one

**Comment by Boolyman** [comment]
Yes!  Man, you added that feature quick!


j/k  thanks!
