### ISSUE TITLE
Unedited, locally-built CraftTweaker NPEs on a server

### ISSUE THREAD

**Issue by Baughn** [CraftTweaker/CraftTweaker#536]
#### Issue Description:

Unedited,  locally-built CraftTweaker NPEs on a server.

#### What happens:

On building and running a server from source:

```
git clone https://github.com/CraftTweaker/CraftTweaker.git ct --recurse-submodules
cd ct
gradle assembleMC1120
cp build/libs/CraftTweaker2-1.12-4.1.7.jar /path/to/server/mods/
<run server>
```

The server crashes with an NPE in JEI integration.

#### What you expected to happen:

Fewer crashes.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

None.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

http://ix.io/19CB

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.3.2655
- Crafttweaker: 6454933b886f3c489a6f3c0e2cf8a936420ad8f4

#### Your most recent log file where the issue was present: 

https://madoka.brage.info/crash-reports/crash-2018-05-07_00.42.19-server.txt

**Comment by jaredlll08** [comment]
Fixed in dev, possible I didn't push, but it is fixed.

**Comment by Baughn** [comment]
Then please push? I can't try to debug my other issue without working code.

**Comment by jaredlll08** [comment]
done, what is your other issue?

**Comment by Baughn** [comment]
A string too long error on login, which I think is provoked by using crafttweaker in a heavily modded setting with plenty of scripts. I wanted to confirm that before reporting, though.

**Comment by jaredlll08** [comment]
We don't send any data from the server to the client or vice versa in 1.12,
so I doubt it is us.

**Comment by Baughn** [comment]
Oh, but you do. Via chat.

I had a suspicion it was that, and it seems to have been borne out; commenting out all the chat commands fixes the bug. Well, since I've got this open anyway, I'm going to see if I can't make my bug report in the form of a PR.
