### ISSUE TITLE
I can't craft

### ISSUE THREAD

**Issue by NullFlower** [CraftTweaker/CraftTweaker#538]
please，i need help

//nuclearCraft

//remove
recipes.remove(<nuclearcraft:manufactory_idle>);

//add 
recipes.addShaped(<nuclearcraft:manufactory_idle>,[[<ore:ingotLead>,<ore:dustRedstone>,<ore:ingotLead>],[<ore:itemFlint>,<ore:chassis>,<ore:itemFlint>],[<ore:ingotLead>,<ore:solenoidCopper>,<ore:ingotLead>]]);

version：CraftTweaker2-1.12-4.1.8
server version：spongeforge-1.12.2-2655-7.1.0-BETA-3064
client YES
server NO
Clients can make but the server can't make

**Comment by jaredlll08** [comment]
Use the full issue template.
