### ISSUE TITLE
[1.12.2]

### ISSUE THREAD

**Issue by Geethebluesky** [CraftTweaker/CraftTweaker#539]
#### Issue Description:
Command /ct biomes doesn't work.

#### What happens:
Output in chat is "An unknown error occurred while attempting to perform this command."
Output in crafttweaker.log is simply the line "Biomes:" with no output after it, there is nothing relevant to the error in that log.

#### latest.log file excerpt
[https://gist.github.com/Geethebluesky/5f4993670d6438e79d3e9f22f80c8b7d](url)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.3.2678-universal.jar
- Crafttweaker: CraftTweaker2-1.12-4.1.8.jar

**Comment by kindlich** [comment]
Possibly related:
#526 which is fixed in dev

**Comment by jaredlll08** [comment]
fixed by that commit anyway
