### ISSUE TITLE
Null Pointer Exception.

### ISSUE THREAD

**Issue by ThunderBolt6** [CraftTweaker/CraftTweaker#540]
#### Issue Description:
Adding recipe to "vic´s modern warfare" causes to not recognize the craft, exactly the ak47 but its any recipe incluiding ".add" "ore:oredic.add" "addshaped." ".additems" etc. (side note: in 1.10.2 the crafting can be changed sucesfully).

#### What happens:
crafttweaker log gives null pointer exception

#### What you expected to happen:
to work like in 1.10.2

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
`recipes.addShaped(<mw:ak47>, [[<minecraft:fish>, <minecraft:fish>, <minecraft:fish>], [<minecraft:bread>, <minecraft:bread>, <minecraft:bread>], [<minecraft:cactus>, <minecraft:cactus>, <minecraft:cactus>]]);`
This script for the test.
[https://pastebin.com/ZWiEriyX](url)
This one from the custom modpack (ftb revelation)and extracted from my previus custom modpack(ftb beyond) that worked.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
[https://pastebin.com/XfAM9tf0](url)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.3.2679
- Crafttweaker: 4.18

#### Your most recent log file where the issue was present: 
Ignore the other mods present, they are irrelevant and tested without em with same results.
[https://pastebin.com/C1zRmfEx](url)

**Comment by jaredlll08** [comment]
That mod isn't supported.

**Comment by jaredlll08** [comment]
https://twitter.com/search?q=vic4games%20recipes&s=09

Should give a good idea why.
