### ISSUE TITLE
Problem with searching JEI for ore dictionary tags added to items by crafttweaker.

### ISSUE THREAD

**Issue by TeetoKaziim** [CraftTweaker/CraftTweaker#541]
#### Issue Description:

Cross posted here at the suggestion of mezz in the interest of fostering cooperation and harmony!
https://github.com/mezz/JustEnoughItems/issues/1214

Basically, if I add an ore dictionary tag to an item, and turn on JEI's ``requires_prefix`` for oredictionary searching, JEI can't seem to find those items under that ore dictionary tag, even though it continues to be able to find items by ore dictionary tags they were "born" with.

Deleting JEI's config folder and restarting the client seems to temporarily fix it. But then restarting the client causes the issue to arise again, unless I delete JEI's config folder every time.

#### What happens:

* When I use the rad script below to add the cool tag ``ore:testStoneDictThing`` to ``minecraft:cobblestone``, I am unable to find the cobblestone in JEI by searching for that ore dictionary tag. 

* I am, however, still able to find it by way of its boring tag ``ore:cobblestone``.

#### What you expected to happen:

To be able to use JEI to search for any and all ore dictionary tags of an item, wether it was born with it, or wether it was added by crafttweaker.

#### Script used 

https://gist.github.com/TeetoKaziim/1dc1ac4619520f11fce26efc1b9c51a9

#### Minetweaker.log file 

https://gist.github.com/TeetoKaziim/ff2e1aceecc22cfc89e748df6b43b6d8
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.3.2681
- Crafttweaker: 4.1.8 

- JEI: 4.9.1.175

#### Your most recent log file where the issue was present: 

debug.log https://gist.github.com/TeetoKaziim/f9f6311cee56d8ae0c3dd453ef8397e6
latest.log: https://gist.github.com/TeetoKaziim/cb167ff05dbb9a196243ee14484e8c77

Thank you for your time and consideration.

**Comment by jaredlll08** [comment]
So this is fixed, for everything but mirror, that one I can't fix due to how it is done
