### ISSUE TITLE
Truncated class file

### ISSUE THREAD

**Issue by YaibaToKen** [CraftTweaker/CraftTweaker#542]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:
Expected the script to compile

#### What you expected to happen:
Script errors with Truncated class file

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://gist.github.com/YaibaToKen/8bab7f7368e7d8702053d8e1abbb27e6

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://gist.github.com/YaibaToKen/56bab444801a825c462d390ddb84609e
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.3.2679
- Crafttweaker: 1.12-4.1.8

#### Your most recent log file where the issue was present: 

https://gist.github.com/YaibaToKen/9b00e0b79b3555052b6b08e78ed18c23

**Comment by codetaylor** [comment]
Import IOreDictEntry.

**Comment by jaredlll08** [comment]
As @codetaylor said

**Comment by YaibaToKen** [comment]
Could've sworn I was importing that and not IOreDict >.>
