### ISSUE TITLE
Recipes not being removed

### ISSUE THREAD

**Issue by YaibaToKen** [CraftTweaker/CraftTweaker#547]
#### Issue Description:
Wrote a script using recipes.replace, recipes.remove, recipes.removeShaped, recipes.removeShapeless, recipes.addShaped and recipes.addShapeless and according to the output from the script, recipes are being replaced/removed/added accordingly, yet remain in the game...

#### What happens:

Some crafting recipes aren't being removed when they should.

#### What you expected to happen:

Expected recipes to be removed.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://gist.github.com/YaibaToKen/8bab7f7368e7d8702053d8e1abbb27e6

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://gist.github.com/YaibaToKen/56bab444801a825c462d390ddb84609e
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.3.2679
- Crafttweaker: 1.12-4.1.8

#### Your most recent log file where the issue was present: 

https://gist.github.com/YaibaToKen/9b00e0b79b3555052b6b08e78ed18c23

**Comment by MentalMouse** [comment]
IIRC there's a warning in the docs to the effect that removing recipes doesn't always work.  Hopefully your scripts will help the devs improve the situation.

**Comment by YaibaToKen** [comment]
> IIRC there's a warning in the docs to the effect that removing recipes doesn't always work. Hopefully your scripts will help the devs improve the situation.

Thanks, I honestly didn't notice. If there's any kind of call I can make in the script to help with debug, I'm more than willing to do so.

**Comment by Lgk2** [comment]
I've got the same problem but in my crafttweaker log i got an error regarding ActionRemoveShapedRecipes.

https://pastebin.com/jwPadvL4

**Comment by jaredlll08** [comment]
okay, I need scripts, not long ones, and not ones that use items from mods, I need something that I can put in my dev environment and test it, without that, I really can't do much. 

@Lgk2 your issue is different, so I need your scripts as well as @YaibaToKen's scripts please.

**Comment by Lgk2** [comment]
https://pastebin.com/WMxvEyJJ - Script
https://pastebin.com/9rmjgtFu - Log

Apparently one of my issues was that i removed Blutonium from ore:ingotPlutonium and then tried to remove a shaped recipe with <ore:ingotPlutonium> even though it contains no ingots. Maybe it can be useful for improved error log.

**Comment by YaibaToKen** [comment]
Honestly, to test my script you need any mod that adds basic ores like copper, tin, lead and the like. Either just base metals or thermal foundation will do, though I'd recommend immersive engineering. The only mod item I'm directly referencing is The Engineer's Hammer from IE. The script used is the one in the first post in this issue. If you want me to shorten the script, mind telling me what exactly do you want me to keep?

**Comment by jaredlll08** [comment]
just 1 example that doesn't work, like your script is huge, I don't even know where to start looking, so 1 example using vanilla (adding mods to dev environments doesn't always work so great), items where removing their recipe doesn't work

**Comment by YaibaToKen** [comment]
I think I understand what you're asking for. Updated the script in the gist to be a lot shorter and only used vanilla stuff.

**Comment by jaredlll08** [comment]
so I just loaded your script into my dev environment and it errored because you aren't defining "rod", after removing that line, the recipe removals work fine, I really don't know where your error is coming from, but not no one else is really reporting it.

**Comment by YaibaToKen** [comment]
Apologies, didn't have time to test the shortened script. I'll give another try asap and will get back to you. Chances are it's a mod adding recipes after CT removes them.
