### ISSUE TITLE
CraftTweaker Issues (Recipe) with AE2

### ISSUE THREAD

**Issue by Oleksandrigo** [CraftTweaker/CraftTweaker#548]
http://keep4u.ru/image/St81r  <-- this is bug(screen)
https://pastebin.com/W19xq2ri <-- log minetweaker
https://pastebin.com/iMmDzfxU  <-- this my script.zs
https://pastebin.com/cF1aWMDc  <-- latest log minecraft

I can not add silicone to recipes. This error is shown as in the picture above.
____

- Minecraft 1.12.2
- Forge: 14.23.3.2679
- Crafttweaker2 1.12   4.1.8
- modtweaker 4.0.12
- AE2 rv5-stable-11

**Comment by jaredlll08** [comment]
we don't add support for Applied Energistics
