### ISSUE TITLE
Modtweaker :((

### ISSUE THREAD

**Issue by CommanderTvis** [CraftTweaker/CraftTweaker#549]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:

Modtweaker recipes aren't working.

#### What you expected to happen:

... modtweaker scripts to work

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/kxEfZ2EA

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/QbJJh4Nd
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.3.2698
- Crafttweaker: 4.1.8
(Modtweaker: 4.0.12)

#### Your most recent log file where the issue was present: 

[latest.log](https://github.com/CraftTweaker/CraftTweaker/files/2019674/latest.log)

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Stop acting like a kid.
Wrong repo.
Tell me what is going wrong.
Read the actual issue.
