### ISSUE TITLE
[Suggestion] Make it able to custom fluid interaction outputs.

### ISSUE THREAD

**Issue by Yesterday17** [CraftTweaker/CraftTweaker#550]
#### Intro:
A suggestion. Make it able to custom fluid interaction outputs.

#### Issue Description:
I'm working on a modpack to generate resources in the way like the cobblestone generator, but I find it is impossible to custom the output product. I hope it can be implemented officially.

**Comment by kindlich** [comment]
There's already a CrT addon that does that, called [Alfinivia](https://minecraft.curseforge.com/projects/alfinivia)
