### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by johnstudent76** [CraftTweaker/CraftTweaker#551]
Error Parsing Recipes

I've looked over every inch of my script to find any errors in my syntax but I can't find anything. Maybe I'm missing something obvious but I'm pretty certain that it's all correct, as I've looked at other examples.

Whenever I load the world it says Error Parsing extremecrafting.zs:5 -- ] expected

Here is the script in question: https://pastebin.com/nKnyzV8u

The issue is occurring in MC 1.12.2, CraftTweaker 1.12-4.1.8, and Forge 14.23.3.2702

**Comment by codetaylor** [comment]
You are missing multiple commas in the script at the end of each line starting at the end of line 4.

Yours looks like this:

```javascript
mods.avaritia.ExtremeCrafting.addShaped("catalyst",<avaritia:resource:5>,[[][][][][][][][][]]);
```

Should look like this:

```javascript
mods.avaritia.ExtremeCrafting.addShaped("catalyst",<avaritia:resource:5>,[[],[],[],[],[],[],[],[],[]]);
```

**Comment by johnstudent76** [comment]
It's so obvious! Can't believe I missed that. Thanks!

**Comment by jaredlll08** [comment]
Seems to be fixed
