### ISSUE TITLE
Strange cross-compat error with mystcraft

### ISSUE THREAD

**Issue by Sunconure11** [CraftTweaker/CraftTweaker#553]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### What happens:

Server crashes on startup

https://pastebin.com/ZcVd4Dbz

#### What you expected to happen:

Server to run normally

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

This is not a script issue

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/yBmWkw7c
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2703
- Crafttweaker: 1.12-4.1.8

#### Your most recent log file where the issue was present: 

https://pastebin.com/ZcVd4Dbz

**Comment by jaredlll08** [comment]
Mystcraft is calling client side code on a method that is called from both sides.
getSubItems used to be client only, and is now called on both client and server. Nothing I can do to fix, it's on their side.
