### ISSUE TITLE
JEI does not display changes I made in the .zs File

### ISSUE THREAD

**Issue by IBriXXI** [CraftTweaker/CraftTweaker#556]
#### Issue Description:
JEI doesn't show changes in the recipe of the Scale Armor (Hexxit Gear)
(The recipe works fine)
Also it displays Items which I removed

#### What happens:
 JEI does not display changes I made in my .zs file

#### What you expected to happen:
JEI adapting the changes

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/VYar5A5b

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/GpanHV6s

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.3.2675
- Crafttweaker: 1.12-4.1.8 

#### Your most recent log file where the issue was present: 

[https://pastebin.com/MZqbcntM
![screenshot1](https://user-images.githubusercontent.com/39710321/40627409-220589fc-62bf-11e8-866e-31a47dac00a4.png)
![screenshot_2](https://user-images.githubusercontent.com/39710321/40627410-23226eea-62bf-11e8-994c-044e93072c75.png)

]

**Comment by jaredlll08** [comment]
Try a normal crafting table

**Comment by jaredlll08** [comment]
Wait, are you on a server? If so, does the client have the scripts?

**Comment by IBriXXI** [comment]
yes I am on a server, and no, they donthave the script. I`ll test it, thanks ^^

**Comment by jaredlll08** [comment]
Servers don't send the scripts to the client anymore.

**Comment by IBriXXI** [comment]
So the crafting recipe change appeared now, thanks ^^
But JEI is still showing removed Items (but I am fine)
