### ISSUE TITLE
vanilla.seeds.removeSeed(<minecraft:wheat_seeds>); not working

### ISSUE THREAD

**Issue by ilvrak** [CraftTweaker/CraftTweaker#559]
#### What happens:
seeds drop from tall grass

#### What you expected to happen:
seed not drop from tallgrass

#### Script used:
`vanilla.seeds.removeSeed(<minecraft:wheat_seeds>);`

#### crafttweaker.log file:
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Building registry
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Successfully built item registry
[INITIALIZATION][CLIENT][INFO] Loading scripts
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: seeds.zs}
[INITIALIZATION][CLIENT][INFO] Completed script loading in: 316ms
[POSTINITIALIZATION][CLIENT][INFO] Removing seeds <minecraft:wheat_seeds>
[SERVER_STARTED][CLIENT][INFO] Fixed the RecipeBook

____
#### Affected Versions (Do *not* use "latest"):
- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- Crafttweaker: 1.12-4.1.8
- jei_1.12.2-4.9.2.196

**Comment by jaredlll08** [comment]
Can't reproduce.
