### ISSUE TITLE
Visual Recipe Result Showing Incorrectly Intermittently 

### ISSUE THREAD

**Issue by yepidoodles** [CraftTweaker/CraftTweaker#560]
#### Issue Description:
I believe this is a multiplayer only issue (possibly even exclusive to SpongeForge), and thus I do not expect much to come of this report, I am just doing my due diligence by reporting it. It's also visual only.

#### What happens:
Sometimes custom recipes will show the result as a stack of 64 diamonds (however it will always return the correct item when you take them). Sometimes it stays as diamonds until you close/open the inventory, most of the time it changes when you take it out of the crafting table. It only does it on the custom recipes, hence why I believe this is a CraftTweaker issue.
[![Screenshot from Gyazo](https://gyazo.com/bb5ef19deb50376e95c96ce2f1656e43/raw)](https://gyazo.com/bb5ef19deb50376e95c96ce2f1656e43)

#### What you expected to happen:
Recipes display as usual.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://www.dropbox.com/s/asxgztmgmpwj1v5/Dragon-Industries-3.3-scripts.zip?dl=0
I zipped them as I have 17 (Both Client and server scripts are identical).

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/yepidoodles/9f3bfb44af9908059760dd9bd20eb41c

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2707
- Crafttweaker: 4.1.8
- Using a server: SpongeForge 3135
- If yes, does the client have the exact same scripts? Yes

#### Your most recent log file where the issue was present: 
My latest log is 156k lines long, I won't bother uploading it unless you want it, or let me know if you want the client one.

**Comment by jaredlll08** [comment]
Can you reproduce this in ssp or without spongeforge?

**Comment by yepidoodles** [comment]
I did spend 15 minutes or so in Single player crafting different custom recipes and it never happened, hence why I believe it's multiplayer only. Unfortunately I can't test to see if it does it without SpongeForge as I don't have the spare server space to run a test server, and my running servers are public and active.

**Comment by jaredlll08** [comment]
Seeing as your log doesn't mention diamond, I'm going to have to say that this isn't crafttweaker / it's a spongeforge issue, as you said, it didn't happen in SSP, and I havn't seen this in normal SMP forge.

**Comment by yepidoodles** [comment]
Alright, I'll send the issue over to them :)

**Comment by derplordofdeath** [comment]
this is not a sponge forge issue im running a normal server without spongeforge or bukkit or anything like that and i still get the issue with my friends

**Comment by jaredlll08** [comment]
Okay, well nowhere in the CraftTweaker code do we even reference diamonds, so there must be a common mod that you guys have in your modpacks, it has been nearly 4 years, so I don't know if @yepidoodles still has their modlist, if they do maybe you can compare, but I can assure you that if we had a bug like this, we would have gotten more reports about it.

**Comment by derplordofdeath** [comment]
im just gonna bite the bullet and go through my mods all 377 mods... i want to die :)

Thank you for the quick response
