### ISSUE TITLE
"/ct names desc" does not work as described by "/ct help"

### ISSUE THREAD

**Issue by GazbonicAcid** [CraftTweaker/CraftTweaker#561]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
/ct help says 
```
/ct names desc
Adds the Display name of the Item to the output
```
But it doesn't

#### What happens:
Outputs the list of items but **_not_** their display names

#### What you expected to happen:
Output the list of items **_with_** their display names

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
Not Applicable

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
[crafttweaker.log](https://gist.github.com/GazbonicAcid/dbd4c9b974fd2d47d8545463337bf034)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.3.2669
- Crafttweaker: 1.12-4.1.8
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 
[latest.log](https://gist.github.com/GazbonicAcid/73c196ac7040b06489bad83d82c09398)
[debug.log](https://gist.github.com/GazbonicAcid/d65adeefe16274e411871077a6a967a9)
[pastebin/gist/etc link here]

**Comment by BloodWorkXGaming** [comment]
You can specify the amount of info you want to have. So you can make like
/ct names unloc display modid

To get those Infos.
Check here for full  info
http://crafttweaker.readthedocs.io/en/latest/#Vanilla/Commands/#names


GazbonicAcid <notifications@github.com> schrieb am Do., 7. Juni 2018, 01:25:

**Comment by GazbonicAcid** [comment]
Before hand, this is sent from email.
The url you gave does not exist.
ReadTheDocs gives me the "found a maze" can-not-be-found page when I use
that link.

**Comment by GazbonicAcid** [comment]
>
> Wait, now I am confused....

Tried it again and it worked the second time.

**Comment by GazbonicAcid** [comment]
>
> Sorry for so many posts,

But the maze thing was because my email app does something to invalidate
the url when I click it directly from the email.
