### ISSUE TITLE
[Question] Add recipe with damaged inputs

### ISSUE THREAD

**Issue by Ashendale** [CraftTweaker/CraftTweaker#562]
#### Issue Description:
I am trying to set recipes using damaged items. While still going to understand the script language and syntax, I'm using examples on the documentation and making my own changes. Two problems present themselves right now.

1- My recipe, which is almost an exact copy of one that works, does not. That is, it shows on JEI but there is now output on the crafting table.
2- The JEI recipe does not illustrate the fact that the item needs to be damaged. Or even that the item could have any damage (where the item in the recipe would show varying damage bars).

#### What happens:
Recipe shown does not allow for an output. JEI recipe does not show varying damage bar.

#### What you expected to happen:
I expected the recipe to work, and the anyDamage() to be illustrated on the recipe.

#### Script used:
https://pastebin.com/eDuY8JcP First script allows no output. Neither show the varying NBT data.

#### crafttweaker.log file:
https://pastebin.com/Kw7AqgJJ

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- Crafttweaker: 1.12-4.1.8
- Using a server:  No

#### Your most recent log file where the issue was present: 
https://pastebin.com/aGzkbpk4

**Comment by jaredlll08** [comment]
You are using a condition function, which JEI can't see, you need to specify the condition as part of the recipe, like `<minecraft:golden_pickaxe:0>` for JEI to show.
