### ISSUE TITLE
Count of Inputstacks of Furnacerecipes is being ignored

### ISSUE THREAD

**Issue by IcedReaper** [CraftTweaker/CraftTweaker#564]
#### Issue Description:
The count of the Inputstack of furnace recipes is ignored.

#### What happens:
I've created some new furnace recipes to require four dusts for one ingot.
TE's Redstone Furnace works as expected. The vanilla furnace and all other furnaces, which are based on the vanilla recipes, only require one dust.
JEI shows the correct input of four dusts.

#### What you expected to happen:
The furnace should require the defined input :)

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/wjj45HP7

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/rdE16xUK
(Only CraftTweaker and JEI were in this test)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2707
- Crafttweaker: 4.1.8
- Using a server: no - still in development phase.
- If yes, does the client have the exact same scripts?

I would like to know if this is possible or if the vanilla furnace recipe mechanisms prevent this?
And if it's possible if it's a bug in my scripts or if there's a problem in the CraftTweaker furnace recipe handling.

FYI: If I change the input to one and the output to 5 it works fine.
furnace.addRecipe(<minecraft:netherbrick> * 5, <minecraft:netherrack>);

Thanks in advance.
Cheers, IcedReaper.

**Comment by jaredlll08** [comment]
The vanilla furnace just doesn't work like that.
