### ISSUE TITLE
Insert Directly From JEI

### ISSUE THREAD

**Issue by Draskh** [CraftTweaker/CraftTweaker#566]
#### Issue Description:
I tried to use the GUI to add recipes with JEI but I'm unable to insert recipes directly from JEI. I think that was possible in the past. I have to gather every single item in creative, that is very annoying. Has JEI support dropped off?

#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2075
- Crafttweaker: 4.1.8
- Using a server: no

**Comment by jaredlll08** [comment]
That was never a thing and isn't too possible because it is a client side gui compared to server side

**Comment by Syndaryl** [comment]
Not sure if there's a terminology problem here. @Sanofus did you mean the way you can click in JEI and have it put your items in the crafting grid?

**Comment by jaredlll08** [comment]
From what ***I*** gathered, he is talking about CT GUI, and not normal crafting table recipes

**Comment by Draskh** [comment]
@Syndaryl Yes, I mean click on a recipe to insert it in the CT GUI.
