### ISSUE TITLE
.clearTooltip() broken

### ISSUE THREAD

**Issue by MineWitherMC** [CraftTweaker/CraftTweaker#567]
#### Issue Description:
.clearTooltip() function removes item description and such, but not the tooltip.

#### What happens:
![image](https://user-images.githubusercontent.com/18210824/41656025-5c5997ee-7497-11e8-94ab-bd9eaf51f434.png)
The screenshot parts are combined with graphical editor. Interestingly enough, this even removes things like Advanced Tooltips' item IDs and WAILA mod IDs.

#### What you expected to happen:
Tooltips are properly removed: Sand has `Sand` name, `Flux Dust` has name, both items have Advanced Tooltips' IDs. 

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
http://codepad.org/mKdg4x6o

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
http://codepad.org/j8H4i5pa

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- Crafttweaker: 1.12-4.1.8
- Using a server: No

**Comment by kindlich** [comment]
Er...
Do I understand you correctly, you want that the `clearTooltip` method does not clear the item's tooltip?

**Comment by MineWitherMC** [comment]
No.
I want it to not work like this: 
![image](https://user-images.githubusercontent.com/18210824/41657626-ab3f252c-749c-11e8-92bb-1ff9ba84e4d8.png)
This item at least should have its name.

If this is not what function is intented to do, it would be nice to have a function that removes *actual* tooltips (e.g, FN Flux has "Obtained when throwing redstone into lava" tooltip, which I tried to remove).

Sorry for my crappy language, I'm not English :)

**Comment by jaredlll08** [comment]
As the documentation said, and as I have said about it before, clearToolTip clears EVERYTHING on the tool tip.

It isn't really possible to remove specific parts and keep others, the name is part of the tool tip
