### ISSUE TITLE
Readthedocs typo in Orechid page

### ISSUE THREAD

**Issue by warrenvan** [CraftTweaker/CraftTweaker#568]
#### Issue Description:
There is a typo in the [Orechid description page on the readthedocs website.](http://crafttweaker.readthedocs.io/en/latest/#Mods/Modtweaker/Botania/Recipes/Orechid/#orechid)

In the "Find all registered recipes" heading, the doc says "You can find all registered ElvenTrade recipes" when it should say "You can find all registered Orechid recipes"
Sorry if this is the wrong place to submit this. :+1:

**Comment by jaredlll08** [comment]
https://github.com/CraftTweaker/CraftTweaker-Documentation/issues
