### ISSUE TITLE
/ct hand gets truncated on click-to-copy

### ISSUE THREAD

**Issue by dragonpaw** [CraftTweaker/CraftTweaker#569]
#### Issue Description:
While holding a complex object like a TConstruct tool, the `/mt hand` command correctly shows the tag info for the item. The tooltip says that clicking the description will copy it to the clipboard. But the copied version is truncated.

#### What happens:
You get the first 100 characters or so.

Screenshot shows the truncation:
<img width="484" alt="2018-06-24 04_05_14-nvidia geforce overlay" src="https://user-images.githubusercontent.com/74992/41818426-d49ca97a-7763-11e8-894f-0aa45d5c5dec.png">

#### What you expected to happen:

The entire text to be copied.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

None. Just ran `/ct hand` while holding a TConstruct tool.

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

N/A, issue isn't caused by running a script, so no entries in log.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2707
- Crafttweaker: 2-1.12-4.1.8
- Using a server: Yes
- If yes, does the client have the exact same scripts? N/A

**Comment by jaredlll08** [comment]
so when you run the command, it is actually copied to your clipboard automatically, no need to press the button. The button truncating it is a vanilla chat issue.
