### ISSUE TITLE
recipes.removeShaped() function ignores "inputs" field

### ISSUE THREAD

**Issue by QuantumStatement** [CraftTweaker/CraftTweaker#571]
#### Issue Description:

Looks like issue #335 still exist in Crafttweaker

#### What happens:

`recipes.removeShaped` function ignores `inputs` field and removes all recipes for given `output`

#### What you expected to happen:

`recipes.removeShaped` only removes recipes with specified input

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

[Recipe Script](https://gist.github.com/QuantumStatement/b59cd81494acc399cd5ae263e4910efa)

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

[Crafttweaker.log](https://gist.github.com/QuantumStatement/cc650805d88abc82be6abda03f8543c6)
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- Crafttweaker: 4.1.8, 4.1.9
- Using a server: No

#### Your most recent log file where the issue was present: 

[Latest log](https://gist.github.com/QuantumStatement/57ed7aaf6a113dccac7e305a6ac8dc32)

**Comment by jaredlll08** [comment]
Ic2 may use a custom IRecipe, please try and reproduce on a vanilla item / recipe

**Comment by Ashendale** [comment]
I can get you the details on mine, but I've just had the issue trying to remove the cake's recipe using Natura's barley flour (and only that one recipe).

Edit: I feel dumb. I could've just posted mine...

```
recipes.removeShaped(<minecraft:cake>,
 [[<minecraft:milk_bucket>, <minecraft:milk_bucket>, <minecraft:milk_bucket>],
  [<minecraft:sugar>, <minecraft:egg>, <minecraft:sugar>],
  [null, <natura:materials:1>, null]]);
```

**Comment by QuantumStatement** [comment]
With vaniila items (I tested cake recipes added by Forestry) function works fine. Maybe it's really IC2 problem. But instead I found some other problems:
1. Sometimes `recipes.removeShaped()` don't remove mirrored recipes
2. `recipes.removeShaped()` don't remove recipes with certain input if in original recipe this input is wildcarded or oredicted. Instead function remove this recipe completely (although maybe it's not a problem)

[Script and crafttweaker.log](https://gist.github.com/QuantumStatement/dd544a0aa4f0de31370e27a59fc12267)

**Comment by jaredlll08** [comment]
1) Make sure you are removing the right mirror side
1.1) Make sure that the recipe is actually a mirrored recipe and not 2 recipes

2) got any examples?

**Comment by QuantumStatement** [comment]
1. Recipes for vanilla axes are mirrored or not? (script example is [here](https://gist.github.com/QuantumStatement/dd544a0aa4f0de31370e27a59fc12267#file-recipes-zs))
2. First two recipes in [this script](https://gist.github.com/QuantumStatement/dd544a0aa4f0de31370e27a59fc12267#file-recipes-zs)

**Comment by acook** [comment]
I'm experiencing this issue too with Quark:

```csharp
val quark_iron_rust = <quark:iron_plate:1>;
val mcv_iron_ingot = <minecraft:iron_ingot>;

recipes.removeShaped(quark_iron_rust, [
    [mcv_iron_ingot,mcv_iron_ingot,mcv_iron_ingot],
    [mcv_iron_ingot,<minecraft:water_bucket>,mcv_iron_ingot],
    [mcv_iron_ingot,mcv_iron_ingot,mcv_iron_ingot]
]);
```

The above also deletes the recipe which converts `<quark:iron_plate:0>` into `<quark:iron_plate:1>` clearly ignoring the input constraint.
