### ISSUE TITLE
Crash on launch of a modpack

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#572]
#### Intro:
As soon as I launch my modpack with the new version of crafttweaker it crashes my modpack

#### Issue Description:
Crash Happens on new crafttweaker 

#### What happens:
Crashes to desktop

#### What you expected to happen:
It to be fixed

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://gist.github.com/TacticalUniverse/f573816f30bf179f9317ba56236d6377

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2713
- Crafttweaker: 4.1.9
- Using a server: 
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
How am I meant to fix this if I don't have a log?

**Comment by jaredlll08** [comment]
ugh, please don't include both of them in the same link.

**Comment by pupnewfster** [comment]
https://github.com/TheIllusiveC4/ConstructsArmory/issues/71
