### ISSUE TITLE
Immersive Engineering Blueprint Issue

### ISSUE THREAD

**Issue by LjeDamos** [CraftTweaker/CraftTweaker#577]
#### Intro:

Immersive Engineering crafting with Blueprint Issue

#### Issue Description:

For some reason, while i adding recipe that making other mod item to blueprint it unable to craft.
It shows recipe but it cant be crafted.

#### What happens:

IE workbench unable to craft another mod items

#### What you expected to happen:

IE workbench able to craft another mod items

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

script file: https://pastebin.com/5fqatEH7

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

Log file: https://pastebin.com/KuuHuTir

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: forge-14.23.4.2725
- Crafttweaker: CraftTweaker2-1.12-4.1.9
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

Log file: https://pastebin.com/KuuHuTir

**Comment by jaredlll08** [comment]
We don't add support for IE, they add support themselves
