### ISSUE TITLE
1.12.2 CraftTweaker Crashes (Phase two start)

### ISSUE THREAD

**Issue by PulseBeat02** [CraftTweaker/CraftTweaker#579]
**Information you should know first:**

I am creating a modpack that has many mods in it and this mod (CraftTweaker) is one of the mods I am including. I have looked at past issue similar like this (crash on startup #316), but they are outdated. I have found that there may be some mods interfering with it, and I was wondering if someone can provide a fix.

Also, this is my first time posting an issue, so if there are any problems of what I'm posting wrong, please tell me!

**What happens:**

Game crashes while loading in forge, phase 2 start

**What you expected to happen:**

Load the game normally without any issues.

**Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):**

Not Available 

**Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):**

Not Available 

**Affected Versions (Do not use "latest"):**

This problem takes place in Minecraft 1.12.2

**Forge Version: 14.23.4.2726**

Crafttweaker Version: 1.12-4.1.9

**crash report:** 

EDIT THIS HAS BEEN FIXED

Can someone tell me if there is anything wrong?

**Comment by jaredlll08** [comment]
Issue with conarm (construct armory) they may have an update. If not, wait for one.

**Comment by PulseBeat02** [comment]
@jaredlll08 Hi, I was also wondering what the issue about conarm is so maybe I can find a fix,

**Comment by jaredlll08** [comment]
They have a fix already, not sure if it is released though

**Comment by PulseBeat02** [comment]
@jaredlll08 I have found the solve to my problem. I updated ContentTweaker to the latest and it fixed my problem. Although your solution didn't work, thanks for trying to help solve my problem.
