### ISSUE TITLE
CraftTweaker and RotaryCraft combo causing added furnace recipes to not work

### ISSUE THREAD

**Issue by Dreamkiller50** [CraftTweaker/CraftTweaker#581]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Crafttweaker not working with furnace recipes when ReactorCraft and dragonAPI are added.

#### What happens:
I want to make it clear that I know that Reika disallows any modification of his mods or the recipes used to make the blocks. That is not my goal; I only need RotaryCraft because it's needed for ReactorCraft that of which I have no intentions of modifying either. So I've been attempting to add RotaryCraft to a modpack which includes CraftTweaker by default but have found RotaryCraft to be somewhat disabling CraftTweaker. I say somewhat because both mods load and I can use the commands for CraftTweaker but the problem is that RotaryCraft seems to be disabling any CraftTweaker furnace recipes. I've isolated industrial craft and CraftTweaker and all seems to work well but when I add RotaryCraft and dragonAPI, furnace recipes added by CraftTweaker stop working. The strange thing is that the furnace recipes work when I join a world or server for the first time but after that, only crafting table recipes work. I've read that Minetweaker and RotaryCraft "should be compatible", is this problem the exception? Am I missing something or have I not read enough about either of these mods?

#### What you expected to happen:
All recipes to work as intended.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
[1.zs](https://gist.github.com/Dreamkiller50/084f5c53c6c7bd32bca8013888170dc6)

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
[MineTweaker](https://gist.github.com/Dreamkiller50/1c730e325e9971397511de2f4425b694)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.7.10
- Forge: forge-1.7.10-10.13.4.1614-1.7.10-universal
- Crafttweaker: CraftTweaker-1.7.10-3.0.12
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

[Latest Log](https://gist.github.com/Dreamkiller50/a597d0bf0cb9c4f0eae1affff830e8fe)

**Comment by kindlich** [comment]
I'm sorry, but 1.7 is no longer supported
