### ISSUE TITLE
Removing Recipe for Angel Ring not working.

### ISSUE THREAD

**Issue by Nawor3565** [CraftTweaker/CraftTweaker#582]
#### Issue Description:
Recipes for the Extra Utilities Angel Ring are not being removed. I have confirmed that the recipes are shaped, not mirrored or shapeless.

#### What happens:
The Angel Ring and it's variants can be crafted normally. No errors are given.

#### What you expected to happen:
That the recipes would stop working.

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): https://pastebin.com/6gQLZ626

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2708
- Crafttweaker: 1.12-4.1.9
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://pastebin.com/tX0Qjkce

**Comment by Nawor3565** [comment]
Looks like it's a problem with how ExtraUtilities2 handles blockIDs. This [reddit user](https://www.reddit.com/r/feedthebeast/comments/7hdfk6/things_i_like_and_dont_like_about_extra_utilities/dqqkdyx/) gave a way to get it working:

> `recipes.remove(<extrautils2:machine>.withTag({Type: "extrautils2:generator_overclock"}), true);`

**Comment by Nawor3565** [comment]
By changing line 4 in recipes.zs to `recipes.remove(<extrautils2:angelring>.withTag({Type: "extrautils2:angelring:1"}), true, [[<minecraft:feather>, <minecraft:gold_ingot>, <minecraft:feather>],[<minecraft:gold_ingot>, <extrautils2:chickenring:1>, <minecraft:gold_ingot>], [<extrautils2:goldenlasso>, <minecraft:gold_ingot>, <extrautils2:goldenlasso:1>]]);`, I was able to get CraftTweaker to recognize the item, but it said the recipe is wrong. I'll try and find the correct recipe.

**Comment by jaredlll08** [comment]
EXU2 uses nbt, use /ct hand to get the item names, and you can also use /ct recipes to dump all of them to the log
