### ISSUE TITLE
Thermal Expansion Redstone Furnace Recipes

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#583]
#### Issue Description:
Trying to add a recipe into ThermalExpansion Redstone Furnace. 
i used a line straight from the DireWolf 1.12.2 default.zs script
The DireWolf Modpack works fine, Im assuming its because it uses lower version of ThermalExpansion

My ThermalExpansion version is 5.5.0.29, DireWolf is 5.4.2.27

#### What happens:

Minecraft chat produces long error stating No Such Member: thermal expansion

#### What you expected to happen:

Add the recipe into Thermal Expansions Redstone Furnace

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/dUgZWLNs

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/BXF0VbiE
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2729
- Crafttweaker: 4.1.9 + 4.1.8
- Using a server: NO
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 
https://pastebin.com/ZNeZLKRD

**Comment by jaredlll08** [comment]
You need modtweaker.
