### ISSUE TITLE
False error message

### ISSUE THREAD

**Issue by Darkpixel797** [CraftTweaker/CraftTweaker#585]
#### Intro:
I'm making a pack and I'm getting an error that incorrectly describes my problem

#### Issue Description:
It says I'm missing a close parenthesis but I checked all of my parenthesis and they are correct

#### What happens:
"ERROR: Error parsing recipes.zs:9 -- ) expected" shows up in chat and nothing I did had any effect in game

#### What you expected to happen:
remove recipes for screwdriver, wiredebugger, datacard, steel ingot
remove melting chainmail into steel for TiC
remove fire crafting recipes for chainmail
add new crafting recipe for screwdriver
add melting chainmail to iron for TiC

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/wGZvR09E

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
couldn't find crafttweaker.log, there is a minetweaker.log tho
https://pastebin.com/1zEAF3pj
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.7.10
- Forge: 10.13.4.1614
- Crafttweaker: 3.0.13
- Using a server: no
- If yes, does the client have the exact same scripts? N/A

**Comment by jaredlll08** [comment]
Firstly 1.7.10 isn't supported

secondly on line 9 you forgot to wrap your output in `<>`

**Comment by Darkpixel797** [comment]
I know 1.7 .10 isn't supported and I wan't asking you to resume support, but I just wan't seeing my syntax error, so thanks.
