### ISSUE TITLE
[Question] Can CT be used to cause a type of item to have an enchantment?

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#586]
I've been reading through the docs, and I'm not sure if this would work.

I'd like to cause some items to automatically have an enchantment effect, like all lapis hammers having fortune. I know I can create crafting recipes that craft enchanted items, but Sparks Hammers doesn't have CT support for the workbench (it has json customization that doesn't include this feature). Can I change the item definition so that the enchantment is part of the base item?

**Comment by jaredlll08** [comment]
No

**Comment by ghost** [comment]
It was worth a shot. Thanks.
