### ISSUE TITLE
Modded liquids in modded recipe types fail to load (ghost liquid)

### ISSUE THREAD

**Issue by nepphhh** [CraftTweaker/CraftTweaker#587]
#### Issue Description:
Modded liquids (Primal's brine, Rustic's ironberry juice) do not properly load into a modded machine's ct custom recipes.

#### What happens:
The modded liquids are replaced in the recipe by water.

Script: https://pastebin.com/gUsUzxFP
Relevant crafttweaker.log: https://pastebin.com/fyneV4dj

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- Crafttweaker: 4.1.9
Single player custom pack.

**Comment by jaredlll08** [comment]
report to primal.

I don't even know what a ghost liquid is.

**Comment by kindlich** [comment]
@jaredlll08 Ghost liquids and items are the result of ill-gotten Bracket handlers in combination with CoT.

CoT adds ghost items and liquids to allow the usage of Bracket handlers within CoT scripts if necessary (they simply store the id and try to load that when called).

@nepphhh Most likely scenario is that you are using the incorrect fluid id, use `/ct liquids` to get a list of all accessible liquid ids and their bracket counterparts
