### ISSUE TITLE
Add method for hiding a catalyst in Just Enough Items

### ISSUE THREAD

**Issue by axieum** [CraftTweaker/CraftTweaker#589]
When disabling machines or "catalyst" items from the game, when a mod doesn't remove it's recipes (such as Thermal Expansion), the catalyst/category still shows. It would be nice to be able to remove/hide a catalyst/tab/category so it doesn't show impossible recipes.

E.g. `mods.jei.JEI.hideCatalyst(<*>);`

In reference to mezz/JustEnoughItems#1298

**Comment by jaredlll08** [comment]
We don't have access to that, there isn't a method for it.

**Comment by Rikshy** [comment]
Now you have :)

https://github.com/mezz/JustEnoughItems/blob/4b483f7102af464c50a62b1f52d604975df32e23/src/api/java/mezz/jei/api/IRecipeRegistry.java#L141-L159

**Comment by axieum** [comment]
Hurray!

**Comment by axieum** [comment]
Any updates on this feature? I might see about getting around to submitting a pull request when I get time in the next month or so...

**Comment by jaredlll08** [comment]
No update, I've been busy.

**Comment by jaredlll08** [comment]
was closed by this: https://github.com/CraftTweaker/CraftTweaker/commit/27ea91c40aeee14b9181274d8cadc81406219296

apparently I used JEI's issue number though
