### ISSUE TITLE
Crash when loading with 'Better With Mods'

### ISSUE THREAD

**Issue by Pabilo8** [CraftTweaker/CraftTweaker#590]
#### Issue Description:
Game crashes on loading. 

#### What happens:
When trying to load the game, it stops and immediately crashes.

#### What you expected to happen:
Game continues loading, because Better With Mods has a Crafttweaker compat.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
None, no files in 'scripts' folder.

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
File exists, but nothing inside, size: 0kB.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.4.2738
- Crafttweaker: 1.12-4.1.9
- Better with Mods: 1.12-2.3.2
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 
https://pastebin.com/Wjqk1nry

**Comment by jaredlll08** [comment]
Update modtweaker....
