### ISSUE TITLE
Error while applying actions

### ISSUE THREAD

**Issue by andrebpessoa** [CraftTweaker/CraftTweaker#591]
This error appears on crafttweaker.log file.

Full log [here](https://pastebin.com/47bn8qD3)

Scripts: [1](https://pastebin.com/4eXX5cQ3), [2](https://pastebin.com/wTSbdcg7), [3](https://pastebin.com/UcmwEHpr)

- Minecraft: 1.12.2
- Forge:  14.23.4.2705
- Crafttweaker: CraftTweaker2-1.12-4.1.9
- Using a server: No

**Comment by jaredlll08** [comment]
Your items are not valid items, it can't find them ingame thus is defaulting to null
