### ISSUE TITLE
[1.12.2] transformReplace does not seem to work

### ISSUE THREAD

**Issue by SanAndreaP** [CraftTweaker/CraftTweaker#592]
#### Issue Description:
I'm trying to add an alternate recipe for Immersive Engineering treated wood planks with Forestry cans filled with creosote oil. The filled can has .transformReplace() including an empty can (```<forestry:can>```). Despite that, it does not leave me an empty can, it is simply consumed.

#### What happens:
The Forestry filled can is consumed without leaving an empty can behind.

#### What you expected to happen:
I craft the treated wood planks with a filled can and get an empty can in addition to the treated wood planks.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://gist.github.com/SanAndreasP/3b107114ccce47ad818ab1c2d2b9c702

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/SanAndreasP/f5bfb3062facb6366654892b58529b1b

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2739
- Crafttweaker: 4.1.9
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://gist.githubusercontent.com/SanAndreasP/90d9fc81350699ec592c848d0385fe74/raw/7a290b523fd885f7bc0abcb028392f1936951dae/latest.log

**Comment by kindlich** [comment]
Make sure that it's this recipe that's being used, as it might also be possible that the ImmersiveEngineering recipe does accept the cans as well and thus this recipe is never used.

You can check that by either first removing the old recipe, or by adding a crafting function that prints something to the log so that you see if the recipe is used.

**Comment by SanAndreaP** [comment]
I'll try that and report back once I get home, thanks.

**Comment by SanAndreaP** [comment]
Okay, that was the issue, something already did this recipe (w/o specifying to give back the empty can). I removed the recipe before registering my own and it works now.

Thanks again :)
