### ISSUE TITLE
Recipes do not show up in JustEnoughItems(JEI)

### ISSUE THREAD

**Issue by NovaViper** [CraftTweaker/CraftTweaker#594]
#### Issue Description:
With CraftTweaker2, none of the crafting recipes (except for smelting ones strangely) do not seem to appear in the crafting showing gui within JEI. I'm using JEI v4.11.0.202

#### What happens:
Added custom recipes to Minecraft via CraftTweaker, right/left click on an item within the item menu in JEI, none of the added recipes show up.

#### What you expected to happen:
The recipes should show up like all of the other vanilla (and even the custom smelting) recipes

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/zWTzq3ei

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/0MEB0gdm

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.22.2
- Forge: 14.23.4.2739
- Crafttweaker: 4.1.9
- Using a server: No
- If yes, does the client have the exact same scripts? N/A

#### Your most recent log file where the issue was present: 
https://pastebin.com/WEGJCKB6

**Comment by kindlich** [comment]
Try with only CrT and JEI installed.
Since you are the only one who submitted such an issue (to my knowledge) I suppose that this is due to a mod interaction.
Please see if it works with only those two mods installed, and if it does, see which mod causes the issue.

**Comment by NovaViper** [comment]
Nope.. it doesn't show up still

**Comment by alex450** [comment]
These problem also happens when u join a server without script on your clinet thought the server has script
But when i was using minetweaker3 and nei on 1.7.10 this doesn`t happen 
i am curioused what caused this

**Comment by jaredlll08** [comment]
@alex450 that isn't this issue, and that happens because scripts are no longer synced.

**Comment by alex450** [comment]
@jaredlll08 allright,but it would be extremly strange if the server modified the scripts

**Comment by Naxdar** [comment]
I had a similar issue, in my case it was caused by IGCM (InGameConfigManager) breaking everything.

**Comment by jaredlll08** [comment]
I don't think this has to do with CRT, or else we would have had more issues about it.

**Comment by NovaViper** [comment]
I think it had to do with IGCM. I no longer have this issue
