### ISSUE TITLE
crafttweaker.event.PlayerRightClickBlockEvent is missing

### ISSUE THREAD

**Issue by Efimero** [CraftTweaker/CraftTweaker#595]
- Minecraft: 1.12.2
- Forge: 2739
- Crafttweaker: 4.1.9

`import crafttweaker.event.PlayerRightClickBlockEvent;`
fails with
```
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: events.zs}
[INITIALIZATION][CLIENT][ERROR] events.zs:5 > No such member: PlayerRightClickBlockEvent
[INITIALIZATION][CLIENT][ERROR] events.zs:5 > Not a valid type
```
and the entry for the class is missing from the dump

**Comment by kindlich** [comment]
It's called `crafttweaker.event.PlayerInteractBlockEvent` now, gonna be fixed in the wiki soon

**Comment by Efimero** [comment]
but then that's inconsistent with the `onPlayerRightClickBlock` function that does exist???

**Comment by kindlich** [comment]
First the event was called playerRightClickBlockEvent, later it was then renamed to playerInteractBlockEvent.
During that time I may have forgotten to rename the method as well...
I'll add such a method soon, so I'll reopen this issue so that I am reminded that this exists

**Comment by jaredlll08** [comment]
Closed by PR
