### ISSUE TITLE
Crafttweaker erroring on startup

### ISSUE THREAD

**Issue by Fakeiman** [CraftTweaker/CraftTweaker#596]
#### Intro:
I have been tweaking and adding extra mods to the FTB Revelation pack, and i have encountered and error with Crafttweaker that I am unable to resolve on my own.

#### Issue Description:
MC Launcher goes through the loading/initialization process, sometime during this process the launcher crashes and nothing happens. Crash report says Crafttweaker errored. 

#### What happens:
I launch the MC client, then part-way through the initialization of the mods, the launcher closes, nothing happens. I checked the crash report, it says Crafttweaker errored during the launch. Not sure why, cant figure out why, came here for people who know more about it.
I tried versions 4.1.9, 4.1.8, 4.1.7, and 4.1.6. Result did not change between those versions.

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

Crafttweaker.log file - completely blank?

MC Crash Report - https://pastebin.com/ggQy8MNp

Latest.log file - https://pastebin.com/fBhZUqT1

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: v1.12.2
- Forge: v2.4.2.60
- Crafttweaker: v4.1.8, v4.1.9, v4.1.7, v4.1.6
- Using a server: No

#### Your most recent log file where the issue was present: 

MC crash report - https://pastebin.com/ggQy8MNp

**Comment by jaredlll08** [comment]
Don't download mods from 9minecraft (the inspirations jar file you are using uses the exact same naming scheme)
