### ISSUE TITLE
Recipes Not Being Removed

### ISSUE THREAD

**Issue by WACriminalG2** [CraftTweaker/CraftTweaker#598]
#### Issue Description:
Used CTGUI to remove several crafting recipes from the game, then did some reorganizing in the script file -- just moving lines around, not changing anything. On next bootup, recipes can still be crafted.

#### What happens:
I can still craft jelly using a saucepan, fruit, and sugar.

#### What you expected to happen:
Jelly should only be craftable via a processor I implemented with Modular Machinery. The Modular Machinery processor is working, but the original recipe is still present.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/ucykAYSG

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/YximgEus

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2739
- Crafttweaker: 1.12-4.1.9
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://gist.github.com/MessyConfessor/e50b84c3f1d75076483f2fbeba8a0aef

**Comment by jaredlll08** [comment]
As the file header said. Don't touch the file. You forgot a `>`

**Comment by WACriminalG2** [comment]
Derp. Thanks.
