### ISSUE TITLE
Unable to remove some recipes...

### ISSUE THREAD

**Issue by EngineerXL** [CraftTweaker/CraftTweaker#601]
#### Affected Versions :
- Minecraft: 1.12.2
- Forge: 2749 and 2750
- Crafttweaker: 4.1.9
- Using a server: Nope

**Comment by jaredlll08** [comment]
Firstly follow the template. We do t accept scripts not in links! 


Secondly, we don't add support for IE, they do it themselves, so if it isn't working, you need to report to them, not us.

**Comment by EngineerXL** [comment]
This issue occurs also with another mods

**Comment by jaredlll08** [comment]
I'm just dealing with what you gave me.

**Comment by EngineerXL** [comment]
Ok. sorry. I'm unable to remove Desh ingot from melting in furnace. Furnace has native CraftTweaker support. Script: recipes.remove(<galacticraftplanets:item_basic_mars:2>);

**Comment by jaredlll08** [comment]
Please read what I initially said. We do not accept scripts not uploaded to
gist or pastebin. Make a new issue with ALL the information, using the
template fully.

**Comment by CommanderTvis** [comment]
😄
