### ISSUE TITLE
Unable to remove some recipes

### ISSUE THREAD

**Issue by EngineerXL** [CraftTweaker/CraftTweaker#602]
#### What happens: Nothing 
![image](https://user-images.githubusercontent.com/37447286/44151024-f88f5bb0-a0a9-11e8-9370-995a6f5a0fa0.png) 
![image](https://user-images.githubusercontent.com/37447286/44151053-09739946-a0aa-11e8-9631-78283863c65f.png)

#### Affected Versions:
- Minecraft: 1.12.2
- Forge: 2749 and 2750
- Crafttweaker: 4.1.9
- Using a server: Nope

**Comment by jaredlll08** [comment]
Galactic craft is adding their recipes way too late, doing it in post init, after we have removed recipes.

**Comment by EngineerXL** [comment]
So, why titanium ingot recipe removing works?

**Comment by jaredlll08** [comment]
What mod adds titanium?

**Comment by EngineerXL** [comment]
GalactiCraft

**Comment by jaredlll08** [comment]
Well how are you removing it? Oredict or what, I can't help if I don't know
what you're doing

**Comment by EngineerXL** [comment]
Script: https://pastebin.com/Z9Csj1fe
CraftTweaker.log: https://pastebin.com/RfkBJxG6

Also works with <ore:ingotTitanium>

**Comment by jaredlll08** [comment]
I honestly don't know.

All I know is that it works with all other mods and items, meaning that the issue has to be with galacticraft
