### ISSUE TITLE
Is the mod and scripts Server side?

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#603]
#### Issue Description:
I have a Question is Craftweaker Sever sided and/or the scripts?

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.2
- Forge:1.12.2-14.23.4.2747
- Crafttweaker: 1.12-41.9
- Using a server: Yes
- If yes, does the client have the exact same scripts? Yes

**Comment by jaredlll08** [comment]
Both the mod and all the scripts need to be installed on both the client and the server.
