### ISSUE TITLE
Avaritia supprot

### ISSUE THREAD

**Issue by MoeShimaKaze** [CraftTweaker/CraftTweaker#605]
i want to use the Dire Crafting Table to custom my repice.
However,MineTweaker support this in 1.7.10,but now in 1.12.2,CraftTweaker dont support
and When i use the Avaritia's Scripts,he message me:

> a method available but §4none§r matches the parameters (ZenTypeNative: crafttweaker.item.IItemStack, any[])\nThis is §ousually§r an error in your script, not in the mod\naddShaped(§rstring, §rZenTypeNative: crafttweaker.item.IItemStack, §rZenTypeNative: crafttweaker.item.IIngredient[][])

i hope you can add support to this nice mod,thanks

**Comment by jaredlll08** [comment]
No.
I have never supported <insert any mod name that has a crafting table bigger than 3x3 here> and never will. Ask whoever makes the mod to do it (like it was done in the past)

**Comment by EngineerXL** [comment]
Moe, CraftTweaker supports DireCrafting. Error says that you've done a mistake in script
