### ISSUE TITLE
1.12.2 Craft Tweaker Crashing server in Modpack, works fine on client only.

### ISSUE THREAD

**Issue by Darkmega18** [CraftTweaker/CraftTweaker#606]
#### Issue Description:
I'm the author of a modpack called transcendence. I've got a server of it that I run for myself and friends to play on. In my recent version I installed craftweaker off curse to do some recipe rebalances and use it as a way to get entity names and stuff while tweaking other things. But after making my update and copying my config, mods and scripts folder same as they are from the client to the server to update it as I normally do the server crashes with the following errors and issues.

client side, the recipes would be removed and overwritten fine as far as I could tell.

#### What happens:
Server crashes soon after starting. Something about Itoasts.

#### What you expected to happen:
it to run fine and be able to play.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
recipes.zs, made using the ingame recipe maker.
https://pastebin.com/2gw5tawr

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
server side, theres nothing in it.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: v14.23.4.2705
- Crafttweaker: CraftTweaker2-1.12-4.1.9
- Using a server: YES, and yes I transferred the scripts over.

#### Your most recent log file where the issue was present: 
latest log on the server at the time of crash which has the crash log inside it seems
https://pastebin.com/XxM6CmS2

[pastebin/gist/etc link here]
crash log
[crash-2018-08-17_08.24.13-server.txt](https://github.com/CraftTweaker/CraftTweaker/files/2297225/crash-2018-08-17_08.24.13-server.txt)
.

**Comment by jaredlll08** [comment]
modlist please

**Comment by Darkmega18** [comment]
it's in the crash log I uploaded? or even the modpack that I named? :V
https://minecraft.curseforge.com/projects/transcendence/files/2604508

**Comment by jaredlll08** [comment]
https://github.com/Tschipp/Linear/blob/master/src/main/java/tschipp/linear/compat/crafttweaker/LinearCT.java

Linear contains client side code in a class that is called on both sides, make a report on their issue tracker.

**Comment by Darkmega18** [comment]
Roger that. I'll reference this one and see whats up.
