### ISSUE TITLE
Duplicate files META-INF/* in jar

### ISSUE THREAD

**Issue by bothie** [CraftTweaker/CraftTweaker#607]
I just noticed that CraftTweaker2-1.12-4.1.9.jar contains these files:

```
[...]
      876  06-24-2018 21:56   META-INF/crafttweaker_at.cfg
    76958  06-24-2018 21:56   META-INF/fml_cache_annotation.json
    16447  06-24-2018 21:56   META-INF/fml_cache_class_versions.json
[...]
      876  06-24-2018 21:56   META-INF/crafttweaker_at.cfg
     5007  06-24-2018 21:56   META-INF/fml_cache_annotation.json
      865  06-24-2018 21:56   META-INF/fml_cache_class_versions.json
[...]
```

Those ```crafttweaker_at.cfg``` files are the same (I diffed them) the others already differ in filesize. Obviously, this is an error, the jar shouldn't contain two versions of the same file.

**Comment by jaredlll08** [comment]
This is because there are 2 minecraft mod included, and forge generates those, and then we merge the jars, this isn't a huge issue as it doesn't actually cause any issues (to my knowledge), and will be fixed in 1.13 when the JEI support is moved out.
