### ISSUE TITLE
Help! Can't craft Creative Energy Cube from Mekanism

### ISSUE THREAD

**Issue by onyxromero** [CraftTweaker/CraftTweaker#608]
#### Intro:

I'm trying to make a Nether-Based Survival pack and I'm trying to make creative items from Mekanism craftable and I haven't had any luck with getting the creative energy cell's recipe to work. It shows up JEI and I know JEI can't show NBT data so that's not the problem, what the problem is I cannot craft the dang thing no matter how many times I try. I've tried 3 different methods in the actual crafting recipe itself not the output: ".withOnlyTag", ".withTag", and ".onlyWithTag" and I have had no luck with any of them. Can I please have some help with this? Thank you.

#### Issue Description:

Can't craft Creative Energy Cube

#### What happens:

Recipe shows up in JEI, but isn't usable and there's nothing showing up in the log to indicate what's wrong

#### What you expected to happen:

Craft Mekanism Creative Energy Cell

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/u1XymrJ8

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/sZPQS6De

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- Crafttweaker: 4.1.9
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://pastebin.com/sZPQS6De

**Comment by jaredlll08** [comment]
I don't support Avaritia. complain to them.
