### ISSUE TITLE
[SOLVED]No such static member

### ISSUE THREAD

**Issue by darknat** [CraftTweaker/CraftTweaker#610]
#### Intro:
Hi, I'm creating a script to change recipes at Better With mods and I have a little problem with recipe in Item like Cauldron.
#### Issue Description:

In my script : 
`mods.betterwithmods.Cauldron.removeRecipe(<minecraft:gunpowder>);
mods.betterwithmods.Cauldron.removeRecipe(<betterwithmods:material:28>); 
mods.betterwithmods.Cauldron.removeRecipe(<betterwithmods:material:29>);`

Logs say : 
`[INITIALIZATION][CLIENT][ERROR] explosives.zs:16 > No such static member in mods.betterwithmods.Cauldron: removeRecipe
[INITIALIZATION][CLIENT][ERROR] explosives.zs:17 > No such static member in mods.betterwithmods.Cauldron: removeRecipe
[INITIALIZATION][CLIENT][ERROR] explosives.zs:18 > No such static member in mods.betterwithmods.Cauldron: removeRecipe
...
...`
#### 

I don't understand because this line works : 
`mods.immersiveengineering.Crusher.removeRecipe(<betterwithmods:material:26>);` 

#### Script used 

https://pastebin.com/va3p1WUa

#### crafttweaker.log 

https://pastebin.com/Zbdau7TH
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2757
- Crafttweaker: 4.1.9
- Using a server: no
- If yes, does the client have the exact same scripts?

**Comment by kindlich** [comment]
- It's `mods.betterwithmods.Cauldron.remove(IItemStack[] outputs);` See [here (link to the wiki)](https://crafttweaker.readthedocs.io/en/latest/#Mods/Modtweaker/BetterWithMods/Cauldron/)
- This is the CrT issue tracker, BWM support is added by Modtweaker, the issue tracker for MoT is [here](https://github.com/jaredlll08/ModTweaker/issues)

**Comment by darknat** [comment]
Thank you ! 👍
