### ISSUE TITLE
getSubItems method can throw null pointer

### ISSUE THREAD

**Issue by Charnuz** [CraftTweaker/CraftTweaker#613]
#### Issue Description:
The [getSubItems method in MCItemDefinition](https://github.com/CraftTweaker/CraftTweaker/blob/14a2dd2e0f8b04d4fb4f09eb4e981c4f47b60667/CraftTweaker2-MC1120-Main/src/main/java/crafttweaker/mc1120/item/MCItemDefinition.java#L123) can sometimes throw a null pointer exception. 
I have tried some tests to find the source of the issue, but it seems kind of inconsistent.
[My test script](https://pastebin.com/57DPyjUZ).

#### What happens:
It will sometimes throw this [exception](https://pastebin.com/Px5x2KSq), which will cause the script to crash.

#### What you expected to happen:
The behavior to be consistent, or catch the null pointer.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/57DPyjUZ

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
[Log output from test script](https://pastebin.com/NSVVFH5w)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2756
- Crafttweaker: 4.1.9
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 
My entire log file is 165k lines long, but I can find a way to post it if needed.

**Comment by kindlich** [comment]
I'll assign.this to me, not sure when I will be able to actually look into it.
