### ISSUE TITLE
"ERROR: [crafttweaker]: Error Executing{[0:crafttweaker]:recipes.zs}:null"

### ISSUE THREAD

**Issue by ehmitchell3** [CraftTweaker/CraftTweaker#614]
#### Intro:
Two issues:
1. Cannot click any of the left side buttons on CTGUI
      (Literally, I place everything in the left 3x3 and the expected item in the right 1x1, and the only 
      clickable buttons are the mirrored/shaped/non-shaped)
2. **(MAIN)** Error when using CTGUI on item.

#### What happens: 
Used CTGUI to create recipe for Advanced Solar's Ult Hybrid helm. CTGUI creates recipe.zs file properly, and most all of the script checks out.

When entering the game, however, the following error occurs:

> ERROR: [crafttweaker]: Error Executing{[0:crafttweaker]:recipes.zs}:null

#### What you expected to happen:
Recipes created in CTGUI work in crafting tables and the like.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
[recipe.zs](https://gist.github.com/ehmitchell3/35b4f96a2ac5f88b916e344dc069c7b3)

#### crafttweaker.log file 

[Crafttweaker.log](https://gist.github.com/ehmitchell3/5a8111fadec9488a3aecf4718b923246)

____
#### Affected Versions (Do *not* use "latest"):

- **Minecraft**: 1.12.2
- **Forge**: 14.23.4.2755
- **Crafttweaker**: CT2 1.12-4.1.9
- **Using a server**: Creating scripts in Single player to push to server

#### Your most recent log file where the issue was present: 

[latest.log](https://gist.github.com/ehmitchell3/50fcfccfcf4c6d944a4caacdd7a89114)

Thanks, everyone!

**Comment by jaredlll08** [comment]
If you couldn't click the buttons I'm going to assume that you wrote "anyDamage" in the scripts yourself, that is what is causing the error.

As for the buttons, right click the slot you want to edit and the buttons will work. I know it is bad design.
