### ISSUE TITLE
Documentation error on ICommandManager

### ISSUE THREAD

**Issue by WACriminalG2** [CraftTweaker/CraftTweaker#615]
#### Issue Description:
Documentation at https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Commands/ICommandManager/ instructs users to import crafttweaker.commands.ICommandManager. However, in ICommandManager.java, it is actually "command" singular, rather than plural.

#### What happens:
Crashes when importing crafttweaker.commands.ICommandManager. Does not crash when importing crafttweaker.command.ICommandManager.

#### What you expected to happen:
The opposite.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
import crafttweaker.commands.ICommandManager;

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
[INITIALIZATION][CLIENT][ERROR] events.zs:3 > No such member: commands
[INITIALIZATION][CLIENT][ERROR] events.zs:3 > Not a valid type

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: Unsure
- Crafttweaker: Unsure
- Using a server: 
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 
This was discussed in Discord by NitroToxin2

**Comment by kindlich** [comment]
I believe you fixed that in your PR to the wiki:
https://github.com/CraftTweaker/CraftTweaker-Documentation/pull/91
