### ISSUE TITLE
[Feature Request:] Better IBlockState Support

### ISSUE THREAD

**Issue by TheFloydman** [CraftTweaker/CraftTweaker#616]
For mods that have CraftTweaker support and require an IBlockState argument, it would be useful to have a simple way to write out a block and it's state. The only way I currently know of doing this is with the line `<minecraft:diamond_block>.asBlock().definition.defaultState`. This works very well for defining a block's default state, but there is no way to select another state.

**Comment by jaredlll08** [comment]
Closed by PR
