### ISSUE TITLE
[Feature Request] Reloading scripts with Minecraft still running.

### ISSUE THREAD

**Issue by Jkosio23** [CraftTweaker/CraftTweaker#617]
Would there be any way to make a command that reloads the scripts without shutting down the world? I feel this could be very useful for people trying to debug their scripts so they wouldn't have to launch minecraft over and over while tweaking them.

**Comment by jaredlll08** [comment]
No.

**Comment by jaredlll08** [comment]
https://www.reddit.com/r/feedthebeast/comments/6oxjtd/lets_talk_crafttweaker_reload/

**Comment by Jkosio23** [comment]
That's completely reasonable, and hey, now if people haven't seen that post and come here to suggest it again they'll (hopefully) see this one closed and stop themselves.

**Comment by jaredlll08** [comment]
I wish that was the case, I constantly have people asking / being salty
when I say no, regardless of reading the post or not.

**Comment by mckzstudios** [comment]
> https://www.reddit.com/r/feedthebeast/comments/6oxjtd/lets_talk_crafttweaker_reload/

Must be cause you are a shit dev mate.. Fuck
