### ISSUE TITLE
java.lang.NullPointerException on attempting to add Astral Sorcery recipes

### ISSUE THREAD

**Issue by terabyte37** [CraftTweaker/CraftTweaker#619]
#### crafttweaker.log file: https://gist.github.com/terabyte37/30dcd1cc07f465af377e3891d655efef

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: Release 1.12.2-Forge1.12.2-14.23.4.2703
- Crafttweaker: CraftTweaker2-1.12-4.1.9
- Using a server: No

**Comment by kindlich** [comment]
Your forgot the `;` at the last line
