### ISSUE TITLE
JEI.hide() does not hide items from mods (StorageDrawers in this case)

### ISSUE THREAD

**Issue by Husky110** [CraftTweaker/CraftTweaker#620]
#### Issue Description:
Hello folks,
I'm having problems hiding items in the JEI-mod. I'm trying to setup my own modded citybuild-server and create my own modpack for that.
For test purposes I try to hide the item storagedrawers:upgrade_storage_gold (got the name out of the recipe-list) so I tried the following (according to the documentation):
`mods.jei.JEI.hide(<storagedrawers:upgrade_storage_gold>);`
But I get the following error:
`[crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: storagedrawers.zs}
[INITIALIZATION][CLIENT][ERROR] storagedrawers.zs:61: Could not resolve <storagedrawers : upgrade_storage_gold>
[INITIALIZATION][CLIENT][ERROR] storagedrawers.zs:61 > 2 methods available but none matches the parameters (any)
This is usually an error in your script, not in the mod
hide(ZenTypeNative: crafttweaker.item.IItemStack)
hide(ZenTypeNative: crafttweaker.liquid.ILiquidStack)`

I know that the error might be on my side, but using a string didn't work either. And I don't see my error at the moment.

#### What happens:
Error message.

#### What you expected to happen:
The Gold-Update is not visible in the JEI

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

[https://pastebin.com/0xM3UrEe](https://pastebin.com/0xM3UrEe)

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
[https://pastebin.com/twyxzuDr](https://pastebin.com/twyxzuDr)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2760 (with sponge - spongeforge-1.12.2-2705-7.1.0-BETA-3361)
- Crafttweaker: CraftTweaker2-1.12-4.1.9
- Using a server: yes
- If yes, does the client have the exact same scripts?: yes

#### Your most recent log file where the issue was present: 

[https://pastebin.com/LZGSeBZW](https://pastebin.com/LZGSeBZW)

**Comment by kindlich** [comment]
You are using an incorrect item name, (hence the `could not resolve <storagedrawers : upgrade_storage_gold>` Part → It tells you that it has no idea what `<storagedrawers : upgrade_storage_gold>` means (no spaces, in handlers for example))

Hold the upgrade item in your hand and do `/ct hand` and it'll show you the correct syntax. You can even click on it to copy it to your clipboard.

**Comment by Husky110** [comment]
Thank you - I will try to use your advice. :)
