### ISSUE TITLE
game.setLocalization Issue

### ISSUE THREAD

**Issue by Freebi85** [CraftTweaker/CraftTweaker#621]
Huhu Guys ;-) ✌️ 

I think i found and Issue with the localizations parameter.

Examples:

//This Line works fine. (Gold Ingot)
game.setLocalization(<minecraft:gold_ingot>.definition.name + ".name", "Shiny Ingot");

//This Line dosent work. (Invar Ingot from Thermal Expansion)
game.setLocalization(<thermalfoundation:material:162>.definition.name + ".name", "Strong Ingot");

Any suggestions ❓

**Comment by jaredlll08** [comment]
Follow the template is my first suggestion.


Also mods like TE ignore the localization that we set sometimes, nothing we can do.
