### ISSUE TITLE
[Feature Request] - Replace in recipe function

### ISSUE THREAD

**Issue by Peach774** [CraftTweaker/CraftTweaker#623]
Essentially, it would be nice if there was a script function you could call to replace all of a specified item in a specific recipe with another item. This would function similar to the replace all, but for a specified recipe instead of ALL recipes.

**Comment by axieum** [comment]
Can't agree more, it would be great to be able to loop through a mod's recipes and perform a replace command.

**Comment by axieum** [comment]
Top bloke @kindlich; really appreciated!
