### ISSUE TITLE
new to crafttweaker, recipes not loading

### ISSUE THREAD

**Issue by Spenny519** [CraftTweaker/CraftTweaker#625]
[scripts.zip](https://github.com/CraftTweaker/CraftTweaker/files/2422737/scripts.zip)

#### Intro: I am new to scripting and crafttweaker so I based 95% of my scripts on age of engineering and none of the scripts loaded correctly. I don't know what I am doing wrong. Help would be greatly appreciated.
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description: none of the recipes loaded correctly
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens: no recipes were changed
[scripts.zip](https://github.com/CraftTweaker/CraftTweaker/files/2422740/scripts.zip)

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):  https://gist.github.com/Spenny519/d5c1d069099be597ff3e73df6a6eb426

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.2
- Forge:12.23.4.2739
- Crafttweaker: 1.12.2 4.1.9
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here] My most recent log file is the crafttweaker.log file that I added in gist

**Comment by BloodWorkXGaming** [comment]
If you copied the scripts you have all mods present with which they were
created...
I assume you removed/didn't add a lot of those...
Actually additions, enderio, mekanism, advanced generators to name few.

Spenny519 <notifications@github.com> schrieb am Do., 27. Sep. 2018, 08:37:

**Comment by Spenny519** [comment]
I have all the mods that are installed but almost none of the recipes loaded. very few recipes changed

**Comment by Spenny519** [comment]
I figured out what was wrong. The item id's changed between 1.10 and 1.12
