### ISSUE TITLE
Tinkers' Construct smeltery recipe problems

### ISSUE THREAD

**Issue by UltraEmailMan** [CraftTweaker/CraftTweaker#628]
#### Intro:
Firstly, I want to say this is my first time doing this, so I am sorry for any errors that may be in this post. Now, I am setting up a medium sized modpack for a private server, and I want to add the ability to melt down the vanilla chain armor into molten steel in a TConstruct smeltery. I believe I have followed the Crafttweaker documentation successfully, but the recipe will not work. I have no experience whatsoever with coding/scripting, so I am assuming that the problem lies with my attempt to add the recipe. As such, I decided to ask on here so that someone with a bit more experience could hopefully spot my error.

#### Issue Description:
I added in the lines that I needed to according to the Crafttweaker documentation, but the recipe does not work.

#### What happens:
When I log into the game, I see "Could not resolve minecraft : chain_chest" and "Could not resolve liquid : molten_steel." When I place the chain armor into a smeltery, it has a grey progress bar and does not melt.

#### What you expected to happen:
The chain armor should melt into molten steel.

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): https://pastebin.com/AUMujbvd

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- Crafttweaker: 4.1.9
- Using a server: Not yet, I am testing it on SP before I add it.
- If yes, does the client have the exact same scripts? When it is fixed, I will ensure that both sides have the same scripts.

#### Your most recent log file where the issue was present: 

I am unsure which log file this is asking for.

**Comment by jaredlll08** [comment]
your item and fluid names are wrong, use 

/ct hand

to get the correct names.

**Comment by UltraEmailMan** [comment]
Thank you very much. That helped with the chainmail, but how do I /ct hand a liquid? When I try to give myself the liquid with JEI it puts it into a bucket.

EDIT: I messed around with the commands and found /ct liquid. Thanks again for your help!

**Comment by jaredlll08** [comment]
Read the wiki page on commands, I believe there is something like /ct liquids
