### ISSUE TITLE
Export script from the mod archive to the script folder.

### ISSUE THREAD

**Issue by MrLador** [CraftTweaker/CraftTweaker#629]
I'm looking for a way to transfer scripts that are located in the mod so that they are exported to the script folder. Is there a way to export script files from the mod archive to the script folder?

**Comment by jaredlll08** [comment]
You got an example of what you're trying to do?

**Comment by MrLador** [comment]
I wanted to put the file in .......zs archives its mod and when the mod is in the mod Assembly it imports the file .......zs to the scripts folder in the Assembly.

**Comment by jaredlll08** [comment]
I don't even know why you would want that, so can't help you there.
