### ISSUE TITLE
Cannot setup development workspace with Gradle project

### ISSUE THREAD

**Issue by axieum** [CraftTweaker/CraftTweaker#633]
#### Issue Description:
When importing the Gradle project, it fails on `Configure build`.

#### What happens:
The following error is shown:
```
Project with path ':ZenScript' could not be found in project ':CraftTweaker2-API'.
```

#### To reproduce:
Clone the repository, and import the Gradle project(s).

____
#### Affected Versions (Do *not* use "latest"):

- Branch: 1.12
- As of: https://github.com/CraftTweaker/CraftTweaker/tree/ef29ecb6c93394ecb81b921fb179fd5396a9891a

**Comment by BloodWorkXGaming** [comment]
You probably didn't pull the submodule correctly in git.

_Axieum <notifications@github.com> schrieb am Fr., 5. Okt. 2018, 04:32:

**Comment by jaredlll08** [comment]
As blood work said, you need to use pull the submodule, https://git-scm.com/book/en/v2/Git-Tools-Submodules
