### ISSUE TITLE
Mekanism Recipe Issues

### ISSUE THREAD

**Issue by NielsPilgaard** [CraftTweaker/CraftTweaker#634]
#### Issue Description:
This bug occurs in the modpacks Enigmatica 2: Expert & Enigmatica 2: Expert Skyblock, both of which I am maintaining.

#### What happens:
All Mekanism items with the word "Basic" in them have no crafting recipe, and any recipe that requires an item with the word Basic in it does not work.

Downgrading to CraftTweaker 1.12-2.4.1.9 fixes the issue.

#### What you expected to happen:
The items to have their normal recipe.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://gist.github.com/NillerMedDild/08837b60ffbec6303b26e204e3982ad1
I don't think the script is relevant.

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/NillerMedDild/b36bf0874d41da63899082e6af349ad3

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2751
- Crafttweaker: 1.12-2.4.1.10
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://gist.github.com/NillerMedDild/ab5147bac3be8fc0d5c9084a61cd4c79

**Comment by jaredlll08** [comment]
so you're saying, just by having CraftTweaker and mekanism in the same instance mekanism recipes get removed?

**Comment by NielsPilgaard** [comment]
No, cause it seems to be unique to my modpacks, so it's probably an error in my scripts somewhere. 

I opened this issue in the hope that you had changed something related to Mekanism in the 2.4.1.9-2.4.1.10 update, so my error hunting would be easier ^^'

**Comment by Thiana** [comment]
Given the same scripts work as expected with 1.12-2.4.1.9 but not 1.12-2.4.1.10, it seems more likely that the problem is in CT's .10 changes?
