### ISSUE TITLE
Using TCon parts in crafting recipes suddenly broken

### ISSUE THREAD

**Issue by Nachtflame** [CraftTweaker/CraftTweaker#636]
#### Issue Description:
Have scripting in place to use Tinkers' Construct parts in normal crafting recipes for some tools and weapons from other mods.  Until recent update to version listed below, scripting/recipes all worked fine.  After the update, recipe behavior of recipes using tool rods & heads in seems to have become much more fluid than it should be.

#### What happens:
Any material that has a hammer recipe in that script, will craft from either Normal or Tough Wooden Tool Rods, and a Pick head of that material.
Using JEI to verify recipes, shows 0 crafting table uses for pick heads (with the exception of the intentional Stone & Iron head uses), and shows all hammer recipes to correctly require Tough Wooden Tool Rods + TCon Hammer Head of material.
I have no scripting that adds oreDict tags to TCon parts

#### What you expected to happen:
Scripting behavior/results to not change radically?

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
Script used to modify DungeonTactics weapons to craft from Tinkers' Construct parts - https://pastebin.com/dwafMe7L

Script used to modify Geolosys Prospectors pick to craft from Tinkers' Construct parts - https://pastebin.com/GGfDcMbi 

Script used to modify vanilla Iron Pick to craft from Tinkers' Construct parts - https://pastebin.com/edEc1uyN

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
Latest load on Single-player, confirmed issue persists there. - https://pastebin.com/bgqBh55Z

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.4.2765
- Crafttweaker: 4.1.10
- Using a server: Yes
- If yes, does the client have the exact same scripts? Yes

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
you're only using "withTag" instead of using both "withTag" and "onlyWithTag", can you try doing that and get back to us (preferably with screenshots of what currently happens and what *should* happen)

**Comment by kindlich** [comment]
Another thing: which version of CrT were you using before the update to 4.1.10?

**Comment by Nachtflame** [comment]
The tags were based on what came up when using '/ct hand' while holding a TCon Part.  
Honestly the tags don't _seem_ to be the issue, I did some other testing.  You'll see in the screen shots.  This **really** has me confused.  It's acting like the only parts of the recipe that matter is the .nbt tag.

Previously had been using 4.1.9

Screenshots - https://imgur.com/a/qb3E82Q
