### ISSUE TITLE
Recipe working in previous versions no longer working

### ISSUE THREAD

**Issue by Water-Cat1** [CraftTweaker/CraftTweaker#637]
#### Intro:
Custom recipe for a quantum storage disk worked in previous versions but not in the current version

#### Issue Description:
I have a custom recipe for a quantum storage disk for use in a refined storage system (from QuantumStorage mod). It worked in previous crafttweaker versions (a week and a bit ago) but now no longer works. Everything displays fine in JEI, and can be auto-moved into crafting grid. Crafting bench moves everything, while a refined storage crafting grid excludes the cursed lasso with NBT (which is where my suspicions lie)

Other custom recipes still working.

#### What happens:
Placing required ingredients (4*Ender anchor, max storage part, interdimensional upgrade, storage house, opinium core (perfected) and cursed lasso with NBT for an Enderman) does not produce a product (quantum storage/fluid disk) that can be crafted.

(relevant mods are RandomThings, Refined Storage, and ExtraUtils2)

#### What you expected to happen:
Placing required ingredients produces a product to be crafted.

#### Script used
[WaterPack.zs](https://gist.github.com/Water-Cat1/957aac40608f325cccdbade254e38df5#file-waterpack-zs-L56)
relevant lines are 56 and 57

#### crafttweaker.log file
[crafttweaker.log](https://gist.github.com/Water-Cat1/957aac40608f325cccdbade254e38df5#file-crafttweaker-log)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: forge-14.23.4.2765
- Crafttweaker: CraftTweaker2-1.12-4.1.10
- Using a server: No (Tested in singleplayer, first noticed on a server)
- If yes, does the client have the exact same scripts? Yes

#### Your most recent log file where the issue was present: 
[Latest.log](https://gist.github.com/Water-Cat1/957aac40608f325cccdbade254e38df5#file-latest-log)
(sorry this log is a bit long, I was playing a while. Relevant for startup and near the end where I went into singleplayer and encounterd the issue.)

**Comment by jaredlll08** [comment]
Combine `withTag` with `onlyWithTag`, so use both, each with the same params, like so:

```
recipes.addShaped(<quantumstorage:quantumstoragediskfluid>, [[<randomthings:enderanchor>, <extrautils2:opinium:8>, <randomthings:enderanchor>],[<refinedstorage:upgrade:5>, <refinedstorage:fluid_storage_part:3>, <refinedstorage:storage_housing>], [<randomthings:enderanchor>, <extrautils2:goldenlasso:1>.withTag({Animal: {id: "minecraft:enderman"}}).onlyWithTag({Animal: {id: "minecraft:enderman"}}), <randomthings:enderanchor>]]);
```

**Comment by Water-Cat1** [comment]
[WaterPack.zs](https://gist.github.com/Water-Cat1/235ecbf6937fa82efd35beecfbaa4205#file-waterpack-zs)
Updated with the changes suggested, but I still cannot craft the quantum disk.
Other NBT tag requirements in my script work fine, although those items only have that 1 tag to match, whereas the cursed lasso always comes with many NBT tags, just I only want to check that its an enderman.

**Comment by jaredlll08** [comment]
Try with the latest version on curseforge (4.1.11)

**Comment by Water-Cat1** [comment]
Still not working with latest version. Tested both how it was and including the .onlyWithTag. I will try to some more thorough testing tomorrow to double check it is the lasso.

**Comment by Water-Cat1** [comment]
It is definitely the cursed lasso. Have not had any luck identifying why its not working though.
