### ISSUE TITLE
[1.12.2] Java Null Pointer Execption [Maybe CoFH?]

### ISSUE THREAD

**Issue by Draskh** [CraftTweaker/CraftTweaker#639]
#### Intro:
While I was creating some scripts, I encountered an issue. I don't know where the error is. but it results in a crash. It might be that the TE sawmill is broken. I does not seems that there is an error in the scripts.

#### What happens:

https://pastebin.com/uwt7cC08 //crash report

#### What you expected to happen:

Loading the game properly.

#### Scripts used 

01 https://pastebin.com/xfm9vtjm
02 https://pastebin.com/btMT7Ev7
03 https://pastebin.com/82zZi6v2
extra https://pastebin.com/4StcNxvH
extra2 https://pastebin.com/dqGTf133

#### crafttweaker.log file 

https://pastebin.com/47k1tvtA   //The next step would to be adding additional pulverizer recipes. That works well before I added some oredictionary changes in script 03.
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2765
- Crafttweaker: 4.1.11
- Using a server: No.
- CoFH Core: 4.6.1.22
- Thermal Expansion: 5.5.2.39
- Thermal Foundation: 2.6.1.22
- CCL: 3.2.2.353

#### Your most recent log file where the issue was present: 

[latest.txt](https://github.com/CraftTweaker/CraftTweaker/files/2456502/latest.txt) [File size was to large for pastebin, do not blame me.]

**Comment by Draskh** [comment]
I tested around. 

> recipes.replaceAllOccurences(<minecraft:obsidian>, <ore:obsidian>); 

This one is producing the crash.

**Comment by jaredlll08** [comment]
just uh confirming, you're using CraftTweaker 4.1.12 right?

**Comment by Draskh** [comment]
No, 4.1.11. Was a typo, sorry for that.

**Comment by kindlich** [comment]
@NickelHub Try removing all your calls to `replaceAllOccurences` I think that may be the reason why there are suddenly null inputs in shapeless recipes. (Remove file 3, oredictionary.zs)

I can add a null hceck there but honestly nulls in shapeless should never occur in the first place, and it can't be caused by an addShapeless as that nullchecks

**Comment by Draskh** [comment]
I removed everything new. Only if I try to replace obsidian, the game crashes.
I removed replacing obsidian for now., so there is no crash anymore..

But I'm not sure what causes a recipe to be Null. Maybe the thing that I did to the Mekanism machines in 02?

**Comment by kindlich** [comment]
Is this still an issue with the latest CrT version?

**Comment by Draskh** [comment]
> Is this still an issue with the latest CrT version?

Yes. 
[crash-2019-01-04_22.28.27-client.txt](https://github.com/CraftTweaker/CraftTweaker/files/2728610/crash-2019-01-04_22.28.27-client.txt)

**Comment by Draskh** [comment]
Latest means 4.1.13?

**Comment by DelviousCrafts** [comment]
No longer crashing the game at least, but throwing "Error while applying actions" and failing to load the rest of the script. Using latest version 4.1.15. or at least similar issue with replaceAllOccurrences
Script in question [unification.txt](https://github.com/CraftTweaker/CraftTweaker/files/2933226/unification.txt) starting @ line 217

[crafttweaker.log](https://github.com/CraftTweaker/CraftTweaker/files/2933213/crafttweaker.log) throwing error starting @ line 389
Script was working 4.1.14

**Comment by Draskh** [comment]
@DelviousCrafts How do you know? I still get same crash if I try to replace obsidian.

**Comment by jaredlll08** [comment]
Can you try with the latest on curseforge, 4.1.18 iirc, we may have inadvertently fixed this.

**Comment by Draskh** [comment]
[crash-2019-05-31_21.51.50-client.txt](https://github.com/CraftTweaker/CraftTweaker/files/3242704/crash-2019-05-31_21.51.50-client.txt)
https://pastebin.com/BRNRiW2F

**Comment by jaredlll08** [comment]
Can you reproduce with only CRT and thermal?

**Comment by jaredlll08** [comment]
no reply, was never able to reproduce
