### ISSUE TITLE
 [Suggestion] Need to use CraftTweaker Utils to execute commands from the server [Jared said to put this here]

### ISSUE THREAD

**Issue by Goldenlion5648** [CraftTweaker/CraftTweaker#641]
#### Issue Description:
You have to use the ct Utils mod to execute commands from the server

#### What happens:

commands cannot be run from the server

#### What you expected to happen:

I thought there would be a way to do this using just crafttweaker

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.2
- Forge: forge-14.23.4.2765
- Crafttweaker: 4.1.9
- Using a server: no
- If yes, does the client have the exact same scripts?

**Comment by kindlich** [comment]
After the PR is merged, you can do somethign like this in the next release:
`server.commandManager.executeCommand(server, "difficulty 3");`

Jsut use the global keyword server, or player.server in a function or whatever way you want to use to get the server
