### ISSUE TITLE
force new recipes to be visible in JEI [NBT data]

### ISSUE THREAD

**Issue by TimGoll** [CraftTweaker/CraftTweaker#643]
I don't know if it is a bug, a feature request or if I'm just unable to figure it out.

It's basically the following problem. I want to create a recipe for an item with a specific NBT tag. And this recipe should be shown in JEI.
EG: Tinkers Construct creates and lists multiple Part Builders. Everytime it's the same block ID, but the NBT data is different. Now I want to add a new one. The added recipe does work:
![image](https://user-images.githubusercontent.com/13639408/46756270-57e53f00-ccc7-11e8-909c-c889f33e84b8.png)
But the item is not listed in JEI. Is there a way to force it beeing listed? Thanks in advance

forge-1.12.2-14.23.4.2760
CraftTweaker2-1.12-4.1.11

**Comment by kindlich** [comment]
```
mods.jei.JEI.addItem(item);

//Wiki example:
mods.jei.JEI.addItem(<minecraft:stone>.withTag({display:{Name: "Pickle",Lore:["What once was stone", "Is stone no more"]}}));
```

<https://crafttweaker.readthedocs.io/en/latest/#Mods/JEI/JEI/>

**Comment by TimGoll** [comment]
Thank you!
Ahh, I haven't clicked on mods in the docs. My bad. Thanks again! I've literally brwsed through the docs for 20 minutes ...

**Comment by kindlich** [comment]
I guess this can be closed then, if not just answer
