### ISSUE TITLE
Avaritia crafting recipes not working

### ISSUE THREAD

**Issue by Buffbud96** [CraftTweaker/CraftTweaker#648]
####Intro:
I'm making my own custom modpack, including custom recipes, and, you guessed it, Avaritia...

####Issue Description:
This is 99% my fault not a bug, but I've searched everywhere else on the internet i can think of... the Minetweaker wiki, FTB forums, other github articles, but I still cant find a solution. I've been trying to make my own modpack, custom configs, custom crafting, etc. But now that i'm trying to figure out the custom recipes, i'm coming up short... I've never made custom recipes before, so i decided to just start simple my trying to remove the recipes form Avaritia and replace them with something simple until i learned how to use it... So i tried to remove the infinity sword, and replace the recipe with some singularities (if this worked i'd replace it with proper items). I Started by reading the wiki on how to do this: 
mods.avaritia.ExtremeCrafting.remove(target) to delete the current recipe, followed by mods.avaritia.ExtremeCrafting.addShaped(output, ingredients) to add the new recipe (as you can see with the pastebin) but it doesn't work. I've done everything I can think of... Please help me understand what i'm doing wrong!

####What happens:
The "vanilla" recipe for the sword stays the same.

####What you expected to happen:
The "Vanilla" recipe should've been removed, and replaced with my custom one.

####Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/bk32tNdE 

####crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/vUnJbjig

####Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.27.69
- Crafttweaker: 1.12-4.1.1

- Using a server: No
- If yes, does the client have the exact same scripts?
N/A

#### Your most recent log file where the issue was present: 

https://pastebin.com/6787zymY

**Comment by kindlich** [comment]
Hello Buffbud96,

this issue tracker is the wrong place to ask because it is meant for CrT issues and not a place for users to ask for help with their scripts (otherwise this tracker would explode).
Alsp, we don't add Avaritia support, they do that themselves.

I currently can't look at your scripts myself but I recommend that you join the CrT discord <http://discord.blamejared.com> since its more likely that you get help there.

**Comment by jaredlll08** [comment]
We don't support avaritia.
