### ISSUE TITLE
[1.12][bug?] crafttweaker itemstages NBT tags are mandatory and * doesn't work

### ISSUE THREAD

**Issue by mensreaMC** [CraftTweaker/CraftTweaker#649]
#### Issue Description:
When using itemstages to restrict an item crafttweaker will not ignore NBT data. Even though this issue involves itemstages I thought it might be relevant to post it here due to it seemingly ignoring CT's default stance on NBT items "Sometimes you want your ingredients to need a specific NBT-Tag. The recipe doesn’t care if your item has NBT-Tags other than the ones specified, So a pickaxe with a specific lore may also be enchanted!" -from the CT wiki entry on NBT tags

#### What happens:
Neither mods.ItemStages.addItemStage("Small Guns 90", <flansmod:rifle_sniper762:*>); and mods.ItemStages.addItemStage("Small Guns 90", <flansmod:rifle_sniper762>); will restrict a player from using <flansmod:rifle_sniper762> because by default this item has numerous NBT tags. Only if I include the exact NBT tag from the item does this work. This isn't feasible due to the thousands of different NBT combos for even one item.

#### What you expected to happen:
I expect players not to be able to use <flansmod:rifle_sniper762>

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/Cuh2NpfR

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): 

https://pastebin.com/PCdViAJt

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- Forge: 14.23.5.2770
- Crafttweaker: 4.1.11
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://pastebin.com/QakNbRKu

**Comment by jaredlll08** [comment]
Itemstages does full nbt tag checking, the wiki entry is regarding crafting recipes.

**Comment by mensreaMC** [comment]
So this is definitely an itemstages issue?
