### ISSUE TITLE
Error when hitting a monster and using PlayerAttackEntityEvent

### ISSUE THREAD

**Issue by Alan19** [CraftTweaker/CraftTweaker#656]
#### Issue Description:
When I hit any monster, `Class ZenClass4 does not implement the requested interface crafttweaker.util.IEventHandler` is printed in the chat instead of printing the name of the monster hit.

#### What happens:
`Class ZenClass4 does not implement the requested interface crafttweaker.util.IEventHandler` is printed in the chat and nothing specified in the event block is done.

#### What you expected to happen:
When I hit any Illager (Invoker, Vindicator, and Illusioner) `"You seem to have found a mansion. Trollagers may now spawn."` should be printed in the chat.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/RapvWvfR

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/Alan19/f5bcd20642d67b9d696c92e253528578

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Crafttweaker: 1.12-4.1.11
- Using a server: No

#### Your most recent log file where the issue was present: 

https://paste.ee/p/CF9rO

**Comment by kindlich** [comment]
This is most likely caused by an unforeseen loader conflict in which two loaders use the same class name. 

This will be fixed, for now try to see if it works without Contenttweaker so I can validate that it's coming from that issue?

**Comment by Alan19** [comment]
There's too many scripts that use contentweaker to see which file is causing it in the pack

**Comment by kindlich** [comment]
Did you try it with the latest CrT release?

**Comment by Alan19** [comment]
The console spam stopped in the latest CrT release
