### ISSUE TITLE
Crafting Table Moveable Shaped Recipe (I explain this better in the issue itself)

### ISSUE THREAD

**Issue by ALPHANUMERIC1** [CraftTweaker/CraftTweaker#658]
**Feature request name**
Crafting Table Movable Shaped Recipe

**Feature request description**
Say I was trying to make Spooky Biomes planks create 4 sticks and I wanted to shorten the file. Here's how you would add the recipes normally:

```
recipes.addShaped(<minecraft:stick> * 4, [[<spookybiomes:ghostly_planks>, null, null],[<spookybiomes:witchwood_planks>, null, null], [null, null, null]]);
recipes.addShaped(<minecraft:stick> * 4, [[null, <spookybiomes:ghostly_planks>, null],[null, <spookybiomes:witchwood_planks>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stick> * 4, [[null, null, <spookybiomes:ghostly_planks>],[null, null,<spookybiomes:witchwood_planks>], [null, null, null]]);
recipes.addShaped(<minecraft:stick> * 4, [[null, null, null],[<spookybiomes:ghostly_planks>, null, null], [<spookybiomes:witchwood_planks>, null, null]]);
recipes.addShaped(<minecraft:stick> * 4, [[null, <null, null],[null, <spookybiomes:ghostly_planks>, null], [null,<spookybiomes:witchwood_planks>, null]]);
recipes.addShaped(<minecraft:stick> * 4, [[null, null, null],[null, null,<spookybiomes:ghostly_planks>], [null, null,<spookybiomes:witchwood_planks>]]);
```

 If you were clever, you could try to use Mirrored recipes, but that's confusing to keep track of in itself and often leads to redundancy. Is there a way to add shaped recipes that can be moved across the Crafting Table?

Example of how it might work: `recipes.addShapedMoveable(<minecraft:stick> * 4, [[<spookybiomes:ghostly_planks>, null, null],[<spookybiomes:witchwood_planks>, null, null], [null, null, null]]);`

Resulting in these recipes:
<a href="https://imgbb.com/"><img src="https://image.ibb.co/bt4S0q/Screen-Shot-2018-10-27-at-11-33-41-AM.png" alt="Screen-Shot-2018-10-27-at-11-33-41-AM" border="0"></a> <a href="https://imgbb.com/"><img src="https://image.ibb.co/frV0Lq/Screen-Shot-2018-10-27-at-11-34-31-AM.png" alt="Screen-Shot-2018-10-27-at-11-34-31-AM" border="0"></a> <a href="https://imgbb.com/"><img src="https://image.ibb.co/kmFBRV/Screen-Shot-2018-10-27-at-11-34-52-AM.png" alt="Screen-Shot-2018-10-27-at-11-34-52-AM" border="0"></a> <a href="https://imgbb.com/"><img src="https://image.ibb.co/hpYLLq/Screen-Shot-2018-10-27-at-11-37-54-AM.png" alt="Screen-Shot-2018-10-27-at-11-37-54-AM" border="0"></a> <a href="https://imgbb.com/"><img src="https://image.ibb.co/fvaBRV/Screen-Shot-2018-10-27-at-11-38-25-AM.png" alt="Screen-Shot-2018-10-27-at-11-38-25-AM" border="0"></a> <a href="https://imgbb.com/"><img src="https://image.ibb.co/i0YbtA/Screen-Shot-2018-10-27-at-11-38-48-AM.png" alt="Screen-Shot-2018-10-27-at-11-38-48-AM" border="0"></a><br />

**Feature request reason**
This would be useful because it'd make it easier to make recipes that can be moved to different places across the crafting table such as the recipe for sticks.

**Feature request dependencies**
I don't believe it would require any dependencies, though it would be useful with or without other mods.

**Comment by jaredlll08** [comment]
If you just do,
```
recipes.addShaped(output, [[input1], [input2]]);
```

It will do what you want.

**Comment by ALPHANUMERIC1** [comment]
Thanks.
