### ISSUE TITLE
"addTooltip" and  "addShiftTooltip" didn't work

### ISSUE THREAD

**Issue by RusBrook** [CraftTweaker/CraftTweaker#660]
## Issue Description:

Client-side and server-side does not syncronize for `addTooltip` and `addShiftTooltip`.

### What happens:

The client-side item does not show `§6Hello!` when writing '<minecraft:iron_sword>.addTooltip("§6Hello！");' in 'scripts` in the server-side. I would have to write '<minecraft:iron_sword>.addTooltip("§6Hello！");' in the client side for it to show up.  
The same happens for `addShiftTooltip`.

### What you expected to happen:

The client side will display '§6Hello!' if '<minecraft:iron_sword>.addTooltip("§6Hello！");' or '<minecraft:iron_sword>.addShiftTooltip("§6Hello！");'
is set in the server side 'scripts'.

'crafttweaker.log' :
```
[PREINITIALIZATION][SERVER][INFO] Current loaders after merging: [[preinit]]
[PREINITIALIZATION][SERVER][INFO] Loading scripts for loader with names [preinit]
[PREINITIALIZATION][SERVER][INFO] [preinit | SIDE_SERVER]: Skipping file {[0:crafttweaker]: abc.zs} as we are currently loading with a different loader
[PREINITIALIZATION][SERVER][INFO] Completed script loading in: 2ms
[INITIALIZATION][SERVER][INFO] CraftTweaker: Building registry
[INITIALIZATION][SERVER][INFO] CraftTweaker: Successfully built item registry
[INITIALIZATION][SERVER][INFO] Current loaders after merging: [[preinit], [recipeevent | crafttweaker]]
[INITIALIZATION][SERVER][INFO] Loading scripts for loader with names [crafttweaker | recipeevent]
[INITIALIZATION][SERVER][INFO] [crafttweaker | SIDE_SERVER]: Loading Script: {[0:crafttweaker]: abc.zs}
[INITIALIZATION][SERVER][INFO] Adding tooltip for <minecraft:iron_sword>: Hello！
[INITIALIZATION][SERVER][INFO] Completed script loading in: 819ms

**Comment by kindlich** [comment]
You need the same scripts on both server and client.
No scripts are synchronized between client and server.

**Comment by RusBrook** [comment]
Older versions can be synchronized

Will synchronization between client and server be added later?

**Comment by kindlich** [comment]
Most likely not in 1.12.

Recipes can no longer be synchronized due to a change in MC.
Reloading was the main cause of issues in the MT/CrT GH repository due to caching and it drastically increased server join time. (In some larger packs you couldnt even join the server cause you timed out before you received all the CrT scripts from the server)
