### ISSUE TITLE
NBT on input items seems to need being exact.

### ISSUE THREAD

**Issue by FallenEagle1** [CraftTweaker/CraftTweaker#662]
#### Intro:
This bug may be just something of misunderstanding of how nbt checking is supposed to work on inputs of custom recipes, but this seemed to work before so wanted to report it. The understanding was that with the inputs you could specify which nbt tags were important to be the same, but if there were others attached to the item they would be ignored.

#### Issue Description:
~~Note: If this bug occurs in a modpack, please report this to the modpack author.~~
I am one of the dev's for the modpack in question.

The issue that is appearing is that when a recipe is trying to be crafted in game, unless the full nbt of one of the input items is specifically written in the recipe cannot be crafted. The recipe show correctly in JEI, but when trying to craft it with the exact items it won't work. This used to work in the previous modpack version, which had Crafttweaker 4.1.9 in it, but with this latest update, with Crafttweaker 4.1.11 it won't allow items with extra nbt anymore.

The pics below show a crafting station from tinker's construct, but this was tested with a vanilla crafting table as well.

There is a mix of `withTag` and `onlyWithTag`, but both of the recipes worked prior and now neither work

#### What happens:

![image](https://user-images.githubusercontent.com/22630113/47765765-2392ec00-dc91-11e8-8481-9aa93e68fcaf.png)

#### What you expected to happen:

![image](https://user-images.githubusercontent.com/22630113/47765753-18d85700-dc91-11e8-8d0c-c4b6200df1b1.png)

#### Script used:
https://pastebin.com/Qi3JxXDz
Line 56-64 Is the Mek Jetpack recipe itself,
`<mekanism:gastank>.withTag({tier: 3,mekData:{}})` Is the full name that seems to have to be used, was `<mekanism:gastank>.withTag({tier: 3})` before the update of the modpack and worked fine

Another example:
https://pastebin.com/3SDGfVdb
Line 106 is the recipe in question.
```val resonatingCrystal = <deepresonance:resonating_crystal>.withTag({efficiency:100.0f,strength:100.0f,purity:100.0f,power:100.0f}).onlyWithTag({efficiency:100.0f,strength:100.0f,purity:100.0f,power:100.0f,version:2b});``` Is the tag that needs to be used for it to work, used to work with ```val resonatingCrystal = <deepresonance:resonating_crystal>.withTag({efficiency:100.0f,strength:100.0f,purity:100.0f,power:100.0f}).onlyWithTag(strength:100.0f,purity:100.0f,power:100.0f});``` before update

#### crafttweaker.log file
https://pastebin.com/kP3Q1fbi
Line 1129 is where the jetpack recipe is loaded in.
Line 1076 is where the energy core recipe is loaded in.

____
#### Affected Versions
- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Crafttweaker: 4.1.11
- Using a server: Found on server in modpack, but tested on client with just specific mods used in script.

#### Your most recent log file where the issue was present: 

https://gist.github.com/FallenEagle1/47f63336941f9ff37a4496b3542e2710

**Comment by NielsPilgaard** [comment]
I have the same issue in several different modpacks.
