### ISSUE TITLE
ERROR: system: Huge is already defined in that package

### ISSUE THREAD

**Issue by Maxwelljones** [CraftTweaker/CraftTweaker#663]
#### Issue Description:
ERROR: system: Huge is already defined in that package
ERROR: system: Big is already defined in that package

#### What happens:
Error messages are triggered as chat messages.

#### What you expected to happen:
Not sure where this comes from. Can you please help?

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
scripts: none

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
Crafttweaker Log : https://pastebin.com/1vrqD5cv

____
#### Affected Versions (Do *not* use "latest"):
- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Crafttweaker: 4.1.11
- Using a server: no

#### Your most recent log file where the issue was present: 
https://pastebin.com/FrFKkgWK

**Comment by jaredlll08** [comment]
Mod list?

**Comment by jaredlll08** [comment]
Found the mod, complain to Bigger Crafting Tables, they are registering their classes twice

**Comment by Maxwelljones** [comment]
okay, thank you @jaredlll08 <3

**Comment by WanionCane** [comment]
I am registering them just once through **@ZenRegister**
how I am supposed to register them? =/
edit: on dev, it works fine.

**Comment by jaredlll08** [comment]
That is the right way, it is possible another mod is using the same zen
class as you, or your class is being registered twice (may be a corrupt
build or something?)

**Comment by WanionCane** [comment]
@jaredlll08 you were right, after setting everything up again, cleaned the build folder, and so on.. everything works now, thanks a lot! =P

**Comment by Maxwelljones** [comment]
Lovely, thank you guys !
