### ISSUE TITLE
Help with loops, or conditional statement. Unsure what to do. 

### ISSUE THREAD

**Issue by HentaiHamster** [CraftTweaker/CraftTweaker#665]
#### Issue Description:
I do not have a bug I just don't know where to go for help or guidance on making a script. I wish to clean up my script a bit and somehow use a loop or condition statement to get rid of repetition. The repeated part I wish to condense is adding multiple blocks to an oredict. They're all the concrete powder blocks but with certain meta numbers at the end for either the colorful ones or the gray/black/white ones.  how would I loop the addition of new blocks to the oredict without having to continuous type all the blocks and their individual meta numbers out? 

#### Script used:
https://pastebin.com/s6ziV8kA

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions:
- Minecraft: 1.12.2
- Forge: forge1.12.2-14.23.5.2768
- Crafttweaker:  4.1.11
- Using a server: no

**Comment by jaredlll08** [comment]
Ask here:
https://discord.blamejared.com
