### ISSUE TITLE
Recipe scripts not recognizing ore dictionary

### ISSUE THREAD

**Issue by MidoriMushrooms** [CraftTweaker/CraftTweaker#666]
#### Issue Description:

I'm trying to solve a recipe conflict between quark and prefab, but I can't get craft tweaker to recognize the ore dict name for planks. I know the /ctgui craftingtable command works, because it worked fine when the crafting material is set to spruce planks specifically. I want it to recognize _any_ plank though, and I don't want to sit there and manually do it for every single plank added by mods.

#### What happens:

Recipes from recipes.zs won't load if the recipe contains the oredict names. I obtained the oredict names from http://mce626.wixsite.com/odnlist/list

#### What you expected to happen:

Not only did I expect the recipe to work, but I expected the /ctgui craftingtable command to let me tick the ore dictionary box, which it didn't. I thought it was just me not knowing how to use the in-game GUI so I tried to edit the oredict name for wood planks in normally, that didn't work either. This leads me to believe crafttweaker isn't recognizing oredict for some reason, or I'm not inputting the name in correctly?

#### Script used

Generated by /ctgui (and edited manually to replace scruce planks with anything that registers as planks in the ore dictionary):
https://pastebin.com/jUR9CsNj

Manually created script file:
https://pastebin.com/jgcyVCyQ

#### crafttweaker.log file

https://pastebin.com/5Q03TaUL
____
#### Affected Versions):

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Crafttweaker: 2-1.1.12-4.1.11
- Using a server: Both server and client.
- If yes, does the client have the exact same scripts? Yes

#### Your most recent log file where the issue was present: 

https://gist.github.com/Kazekai/f2ae04843db3505d9a1f49fbb44b9654#file-gistfile1-txt

**Comment by jaredlll08** [comment]
Post your full script.

**Comment by MidoriMushrooms** [comment]
Updated issue (also I forgot to include the craft tweaker version, sorry, edited.)

This is my full script as generated by ctgui and edited by me to try and add the oredict recipes:
https://pastebin.com/jUR9CsNj

This is the raw tweaks.zs file that I attempted to create without using ctgui.
https://pastebin.com/jgcyVCyQ

On the latter link, the first script for removing recipes works fine, but anything to do with ore dictionaries does not.

**Comment by MidoriMushrooms** [comment]
I deleted all the files associated with craft tweaker and reinstalled it clean, then tried to add ore dict values again. I did actually manage to get CTGUI to properly display tick boxes for me, but it still isn't registering the ore dict name for wood, since reloading the game doesn't actually make the recipes appear. (But again, it does still work with individual planks.)

I tried making a recipe for sponge as well, using the ore dict name for fish, but this also does not work. It does work for individual fish though.

Here's a screenshot of my game. (I did individually mark ore dictionary on each individual plank but it only shows one highlighted right now.)
![2018-11-08_16 52 44](https://user-images.githubusercontent.com/9657399/48230514-47cd8780-e379-11e8-8478-fe57a90ea16c.png)

Edit: Here's the pastebin for the new recipes.zs script.
https://pastebin.com/L4ENf0qX

**Comment by jaredlll08** [comment]
Please try write the script yourself, and don't use ctgui, right now I don't know if this is a ctgui issue or base crafttweaker.

**Comment by MidoriMushrooms** [comment]
> Please try write the script yourself, and don't use ctgui, right now I don't know if this is a ctgui issue or base crafttweaker.

I did actually try to write the script myself, it still wouldn't recognize ore dictionary. It would work with specifics though, and both manually writing the script and CTGUI will recognize the "any metadata" function which is what I did for a workaround.

It really is just the ore dictionary stuff not working, tested with both the oredict for planks and fish, wrote both manually before trying CTGUI, and I tried to write them manually once again to make sure it wasn't just me.

**Comment by jaredlll08** [comment]
I can't reproduce.

Looking at your script with the `<ore:fish>`, there is no oredict with that name, which just ignores the item.

**Comment by MidoriMushrooms** [comment]
I obtained my ore dictionary names from here:
http://mce626.wixsite.com/odnlist/list

Is this source incorrect, and can you point me to a better one?

**Comment by jaredlll08** [comment]
Hold the item in your hand.

run
`/ct hand`

it will give you the correct oredict.
