### ISSUE TITLE
replaceAllOccurences Bug

### ISSUE THREAD

**Issue by TimGoll** [CraftTweaker/CraftTweaker#667]
#### Issue Description:
I think there's a bug in `replaceAllOccurences`. Yesterday I added this line to my scriptfile: `recipes.replaceAllOccurences(<minecraft:iron_ingot>, <ore:ingotIron>);`. It didn't throw any error, but it fucked my game completely up. Cklicking items in the GUI randomly duplicated them or deleted them. Adding items in the crafting grid results in no recipe, even if no iron is included in this recipe (at least for all crafttweaker recipes). JEI shows the recipe as defined in the script file.
Strange thing is, something like `recipes.replaceAllOccurences(<minecraft:bookshelf>, <ore:bookshelf>);` works perfectly fine.
I wouln't bother reporting this, because the added line isn't necessary at all, but I have reported a bug to ContructsArmory about item duplication a while ago (https://github.com/TheIllusiveC4/ConstructsArmory/issues/121). This was before the bugged line but behaves exactly the same. Sort of. There are random item duplications if you add the item to a crafting grid, but not always. But it doesn't happen as ofen, there are no item removals and the other recipes still work.

#### crafttweaker.log file:
https://gist.github.com/TimGoll/e5b72202ed44e277201475ee8fc7c862

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: *.68
- Crafttweaker: 4.1.11 
- running on client

#### Your most recent log file where the issue was present: 
https://gist.github.com/TimGoll/313328bb8b7240f561284e981878525c

**Comment by TimGoll** [comment]
Another remark. I noticed that reloading a map after adding/removing the replacement line changes A LOT of recipes (quark shows the affected recipes at the top edge corner)

**Comment by jaredlll08** [comment]
Try it with just crafttweaker installed and see if you can reproduce.

**Comment by TimGoll** [comment]
It does not happen with only crafttweaker, JEI, my mod, animania and optfine

I know, I have to test it until I know which mod it is. I have no time today, maybe tomorrow

**Comment by jaredlll08** [comment]
Not an issue in Crafttweaker then.
