### ISSUE TITLE
[Bug/Question] Add Recipe with name

### ISSUE THREAD

**Issue by TimGoll** [CraftTweaker/CraftTweaker#668]
I'll add more information in case this is a bug.

I tried to add a recipe in minecraft 1.12.2 with a recipe name with this command `recipes.addShaped("gold_fiber", <naturesaura:gold_fiber> *4, [[<farmsteadforest:worm>, <farmsteadforest:resin>, <farmsteadforest:worm>], [<farmsteadforest:resin>, <primal:thatching_dry>, <farmsteadforest:resin>], [<farmsteadforest:worm>, <farmsteadforest:resin>, <farmsteadforest:worm>]]);`. There was no error, but the recipe was not shown ingame. It works without a name.

**Comment by jaredlll08** [comment]
Use. The. Template.

**Comment by TimGoll** [comment]
In case you are talking about the docu, I used it. You have written there `recipes.addShaped(name,output,inputs,function,action);`

**Comment by TimGoll** [comment]
Ah, I know what you are talking about. I didn't use it because I only wanted to ask a question. If it is a bug, I'll add the missing information like I stated above
