### ISSUE TITLE
[Bug/Question] Add Recipe with name

### ISSUE THREAD

**Issue by TimGoll** [CraftTweaker/CraftTweaker#669]
#### Intro:
Here's the same thing again with the template. Sorry for the inconvenience, I thought I only need the template fpr bugs and not for questions.

#### Issue Description:
I want to give my recipe a specific name to be compatible with [Patchouli](https://github.com/Vazkii/Patchouli). All my previous scripts add recipes without a specific name and are therefore using the builtin recipe name generator.

#### What happens:
When I use these two lines
```
recipes.remove(<naturesaura:farming_stencil>);
recipes.addShaped("farming_stencil", <naturesaura:farming_stencil>, [[<ore:plankWood>, <naturesaura:infused_iron>, <ore:plankWood>], [<ore:plankWood>, <naturesaura:infused_iron>, <ore:plankWood>], [<ore:plankWood>, <ore:plankWood>, <ore:plankWood>]]);
``` 
nothing happens. No error and no registered recipe. It gets removed though.

#### What you expected to happen:
Registering the recipe with a specific name

#### Script used 
see above

#### crafttweaker.log
https://gist.github.com/TimGoll/190cd201c26a3eea4b0c968d57be8a59

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: *.68
- Crafttweaker: 4.1.11
- running on client

#### Your most recent log file where the issue was present: 
https://gist.github.com/TimGoll/d464b0cde3a4b1638f6b0f6a65804ba6

**Comment by kindlich** [comment]
The recipe is registered as the log says.

Did you try putting the items in a crafting table?

**Comment by kindlich** [comment]
Also, generally, such issues are discussed in jared's discord, the issue tracker is more for bugs, and I currently cannot see any issue unless you prove me wrong.

<http://discord.blamejared.com>

**Comment by TimGoll** [comment]
No, I only checked it in JEI.
Yes, thats's why I only wanted to ask a question and not report a bug. Thanks for the discord link though.

**Comment by jaredlll08** [comment]
If the game says it is registered, it should be registered, JEI isn't always the best way to tell if something is registered, you should try actually crafting the item.
