### ISSUE TITLE
Gregtechce script error

### ISSUE THREAD

**Issue by mightydanp** [CraftTweaker/CraftTweaker#672]
#### Intro:
I am having a issue with gregtech scripts.

#### Issue Description:
when running the script it gives me a error even thiugh it seems that my scrept is correct.

#### What happens:
the recipe didnt work and gave me a error

#### What you expected to happen:
the recipe to work

#### Script used
https://pastebin.com/EnV3iyEG

#### crafttweaker.log file 
https://pastebin.com/044GeVxG

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.2
- Forge:latest
- Crafttweaker: latest
- Using a server: not
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 
[latest.log](https://github.com/CraftTweaker/CraftTweaker/files/2593173/latest.log)

**Comment by jaredlll08** [comment]
We don't add support for Gregtech.

Your script is not write, you are trying to call oredict as variables.
