### ISSUE TITLE
Build jar file has duplicated file names in META-INF

### ISSUE THREAD

**Issue by ichttt** [CraftTweaker/CraftTweaker#674]
Ok I don't even know how you did this, but somehow your build jar files contains two identical files called crafttweaker_at.cfg in your META-INF folder of the jar, and two fml_cache_annotations and fml_cache_class_versions (again same name, same folder), but they have different content... one has the jei stuff, and the other has the main stuff.

This causes forge to not find the mod annotation when using json cache (-Dfml.enableJsonAnnotations=true)

Affects CraftTweaker2-1.12-4.1.13
Thanks in advance!

**Comment by jaredlll08** [comment]
This is due to us combining 2 mod jars, being the Jei mod support and the main mod, it will be fixed in 1.13 (removing it now would cause issues for people who use the Jei support)
