### ISSUE TITLE
[Feature Request] /ct food

### ISSUE THREAD

**Issue by PCSpinner** [CraftTweaker/CraftTweaker#676]
**Feature request description**
Describe what you would like added
An ingame command similar to `/ct blocks` that outputs a list of all edible items to the crafttweaker.log.

**Feature request reason**
Why do you need this? / Why do you think this would be useful?
For mass editing of food properties. To add all foods to a recipe/oredict entry. 

**Feature request dependencies**
Does the feature request require anything to be implemented? / Will this feature request only be useful when combined with another mod?
None that I can think of.

**Comment by Syndaryl** [comment]
A thousand thanks for implementing this!
