### ISSUE TITLE
NumberFormatException: Crafting Station Crash

### ISSUE THREAD

**Issue by NielsPilgaard** [CraftTweaker/CraftTweaker#678]
#### Issue Description:
This issue is occuring in Enigmatica 2 Expert, of which I am the developer.

#### What happens:
Crash when an item is placed in a Tinkers Construct Crafting Station.

#### What you expected to happen:
No crash.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
Not script related.

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/X6yGB6qX

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2768
- Crafttweaker: 1.12-4.1.13
- Using a server: Yes
- If yes, does the client have the exact same scripts?
Yes
#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
I hope the crash log will suffice, I will ask for additional logs if not.

**Comment by kindlich** [comment]
You are definitely using scripts, since this happens when comparing to a CrT-Recipe

**Comment by NielsPilgaard** [comment]
[AllScripts&LatestLog&CrafttweakerLog.zip](https://github.com/CraftTweaker/CraftTweaker/files/2614554/AllScripts.LatestLog.CrafttweakerLog.zip)
That zip contains the latest.log, crafttweaker.log and all scripts.
It appears to only be certain items - IndustrialCraft items in particular. The recipes for the items that produce the crash are not modified.

**Comment by NielsPilgaard** [comment]
I saw MouseTweaks in the stacktrace and asked about it here: https://github.com/YaLTeR/MouseTweaks/issues/14#issuecomment-441554194
They believe the issue stems from a Crafttweaker misconfiguration.

**Comment by NielsPilgaard** [comment]
Downgrading to `CraftTweaker-1.12-4.1.9` resolves the issue.

**Comment by kindlich** [comment]
First, try to remove 
```
# Dimension Builder
	recipes.remove(<rftoolsdim:dimension_builder>);
	recipes.addShapeless("Dimension Builder", 
	<rftoolsdim:dimension_builder>, 
	[<botania:specialflower>.withTag({type: "orechid"}),<environmentaltech:void_ore_miner_cont_6>,<avaritia:endest_pearl>,
	<avaritia:resource:5>, <draconicevolution:awakened_core>, <mekanism:machineblock:4>,
	<rftools:shape_card:3>,<environmentaltech:void_res_miner_cont_6>.anyDamage(),<industrialforegoing:laser_base>.anyDamage()]);
```

That should be the one causign issues.
Also, check again what `/ct hand` tells you for the orechid item's NBT, it might be a number

**Comment by NillerMedDild** [comment]
The output of `/ct hand` while holding the Orechid is `<botania:specialflower>.withTag({type: "orechid"})`
Removing the recipe did however seem to fix the issue!

Thank you for your help, once again :)

**Comment by NielsPilgaard** [comment]
The output of `/ct hand` while holding the Orechid is `<botania:specialflower>.withTag({type: "orechid"})`
Removing the recipe did however seem to fix the issue!

Thank you for your help, once again :)
