### ISSUE TITLE
Relicensing to MIT

### ISSUE THREAD

**Issue by jaredlll08** [CraftTweaker/CraftTweaker#679]
So currently the code is licensed under a custom license, which has caused some issues because it isn't technically open source, it is more visible source, and I want to change that.

# How to give consent:
Simply reply to this issue stating the following:

> I `<username>` consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license.

If a change is a trivial change (<5 line bug fixes, white space changes or the change doesn't exist in the code base anymore) then your consent isn't required, but you can respond here before the 31st of December 2018 and your contributions can be removed

Accepted | Username | Consent
------------ | -------------|-----------|
Yes|@Jaredlll08|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-443695056)
Yes|@kindlich|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-443698222)
Yes|@stanhebben|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-443695738)
Yes|@BloodWorkXGaming|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-443697719)
Yes|@Tawling|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-444236333)
Yes|@SkySom|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-443765918)
Yes|@darkhax|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-443835622)
Yes|@bculkin2442|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-444501111)
Yes|@skydark|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-443698047)
Yes|@ZenDarva|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-443906338)
Yes|@GoryMoon|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-443708879)
Yes|@Techlone|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-444587060)
Yes|@mezz|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-444539579)
Yes|@fluffle|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-444232620)
Yes|@Hubry|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-443863873)
Yes|@Xfel|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-443697933)
?|@The-Arcanian|Trivial (doesn't exist anymore)
Yes|@Baughn|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-445561677)
?|@BoredAndTalented|Trivial 
Yes|@Mohron|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-443763545)
?|@NotAModder|Trivial 
?|@al132|Trivial
?|@tommyTT|Trivial (doesn't exist anymore)
Yes|@andrewminer|[Consent](https://github.com/CraftTweaker/CraftTweaker/issues/679#issuecomment-444238573)
?|@Yulife|Trivial (doesn't exist anymore)
?|@skaviouz|Trivial (doesn't exist anymore)

**Comment by jaredlll08** [comment]
I @jaredlll08 consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license.

**Comment by stanhebben** [comment]
I @stanhebben consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license.

**Comment by BloodWorkXGaming** [comment]
I @BloodWorkXGaming consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license.

**Comment by Xfel** [comment]
I @Xfel consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license.

**Comment by skydark** [comment]
I @skydark consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license.

**Comment by kindlich** [comment]
I @kindlich consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license.

**Comment by GoryMoon** [comment]
I @GoryMoon consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license.

**Comment by Mohron** [comment]
I @Mohron consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license.

**Comment by SkySom** [comment]
I @SkySom consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license.

**Comment by Darkhax** [comment]
I @darkhax consent to the re-licensing of my constributions to the CraftTweaker project under the MIT license.

**Comment by Hubry** [comment]
I @Hubry consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license.

**Comment by ZenDarva** [comment]
I @ZenDarva  consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license.

**Comment by fluffle** [comment]
I @fluffle consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license.

**Comment by Tawling** [comment]
I @Tawling consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license.

**Comment by andrewminer** [comment]
I @andrewminer consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license.

**Comment by bculkin2442** [comment]
I bculkin2442 consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license

**Comment by mezz** [comment]
I @mezz consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license.

**Comment by Techlone** [comment]
I @Techlone consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license.

**Comment by Baughn** [comment]
I @Baughn consent to the re-licensing of my contributions to the CraftTweaker project under the MIT license.
