### ISSUE TITLE
Server crash on load - NPE ItemBlock.getCreativeTab

### ISSUE THREAD

**Issue by ProsperCraft** [CraftTweaker/CraftTweaker#680]
___
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2775
- Crafttweaker:  4.1.13
- Using a server:  Yes
- If yes, does the client have the exact same scripts? Yes

#### Crashlog-
https://gist.github.com/ProsperCraft/9f44d4b818b802a07bcf2c3590d20366

**Comment by jaredlll08** [comment]
Someone is registering their itemblocks badly, nothing I can do.
