### ISSUE TITLE
rename resetts by reloading textures

### ISSUE THREAD

**Issue by Mari023** [CraftTweaker/CraftTweaker#682]
#### Issue Description:
renaming resetts when reloading texturepacks

#### What happens:
I have a script, which automatically rename items. When I start minecraft, the item has the name it should get from the script. when I press F3+T to reload the textures, the renamed items get their old name.
(this happens because the lanfuage file is also part of the texturepack, and since mc doesn't know about the renaming of craftTweaker, the name will be the "default")

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2772
- Crafttweaker: 1.12-4.1.11
- Using a server: no
- If yes, does the client have the exact same scripts?

**Comment by kindlich** [comment]
This is due to the fact that 
A) CrT can't be reloaded and
B) CrT uses a deprecated method to rename and localize strings. I am not sure if we're going ti fix this.

Can't you just use a .lang file?

Like, use CrT to generate the entries and then just copy them to a resource language file?
