### ISSUE TITLE
IRecipeActions for different recipes are mixed up

### ISSUE THREAD

**Issue by Prunoideae** [CraftTweaker/CraftTweaker#688]
#### Issue Description:
IRecipeAction function in one recipe will call other IRecipeAction functions in recipes.

#### What happens:
This is a function in a recipe:
![tim 20181223231035](https://user-images.githubusercontent.com/24620047/50384976-f9493200-0707-11e9-8417-979af39f9fb9.jpg)
This is the other one:
![tim 20181223232104](https://user-images.githubusercontent.com/24620047/50385058-77f29f00-0709-11e9-8463-fd27e1b990dc.jpg)
![tim 20181223232120](https://user-images.githubusercontent.com/24620047/50385061-80e37080-0709-11e9-9f59-a08909cd313a.jpg)

When I crafted the dirt-glowstone-stone recipe, both sendChat were executed.
![tim 20181223232611](https://user-images.githubusercontent.com/24620047/50385110-25fe4900-070a-11e9-9127-b3adbdb72815.jpg)
and the tag was also updated.
![tim 20181223232722](https://user-images.githubusercontent.com/24620047/50385121-4fb77000-070a-11e9-9f07-dfe26a46827c.jpg)

#### What you expected to happen:
These two function should work separately, it makes no sense if all IRecipeAction functions will be executed when any of the recipes were crafted.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
Container.zs (where the dirt-glowstone-stone recipe is):
https://pastebin.com/cMw8v33J

PackedExamples.zs (the only call of addExpShapeless function at line 101):
https://pastebin.com/hJn1mvwA

FunctionPacket.zs (where the addExpShapeless function is, from line 104 to line 142):
https://pastebin.com/sMFZ9Tqv

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/5iXWtJ2W
This is not a issue about why the scripts crashed, so the log has no error.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.2
- Forge:14.23.5.2796
- Crafttweaker: 1.12-4.1.13
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://pastebin.com/hsnSmUXv

As you can see, I'm Chinese and it's about 00:00 AM in China now, so I'm afraid that I can't respond to you immediately as I'm gonna sleep now, sorry. :-P

**Comment by kindlich** [comment]
Probably due to the way we test some things.
Can you check if this persists if you use different output items (not stone in both cases)?

**Comment by Prunoideae** [comment]
Well, I changed the recipe to output glowstone, and the issue is gone.
