### ISSUE TITLE
"/ct discord" causes disconnect on Linux.

### ISSUE THREAD

**Issue by duckinator** [CraftTweaker/CraftTweaker#689]
#### Issue Description:

Running `/ct discord` causes the client to disconnect.

Server and client are both running on Linux. (Server = Ubuntu, client = Fedora.)

#### What happens:

1. Start Minecraft.
2. Run `/ct discord`.
3. Get disconnected with error `A fatal error has occurred, this connection is terminated.`

#### What you expected to happen:

The Discord link to open in my browser. (... or at least for it not to disconnect me. :joy: )

#### Script used:

(None)

#### crafttweaker.log file:

https://gist.github.com/duckinator/b44f039130c6ce518a9fee3503c2d763

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2796
- Crafttweaker: 4.1.13
- Using a server: Yes
- If yes, does the client have the exact same scripts? Yes. (There were none on either.)

#### Your most recent log file where the issue was present: 

See above crafftweaker.log gist. (If this is referring to something else, let me know and I'll try to find it.)

**Comment by duckinator** [comment]
UPDATE: I have now reproduced this with the following commands:

- `/ct bugs`
- `/ct docs`
- `/ct discord`
- `/ct wiki`

**Comment by jaredlll08** [comment]
So that second log it was referring to was the game log, that is where the
info I need is

**Comment by duckinator** [comment]
Here's the client log: https://gist.github.com/duckinator/71c59ac724e6ec309ea4aa985509b527
