### ISSUE TITLE
[Feature Request] IEntityLivingBase settings maxHealth

### ISSUE THREAD

**Issue by YiChenCraft** [CraftTweaker/CraftTweaker#690]
Can you add a way to set maxhealth?

**Comment by kindlich** [comment]
That is not something we can do simply from within CrT as each mod can implement `getMaxHealth` differently.

Why would you need to set maxHealth anyways?

**Comment by jaredlll08** [comment]
This 100% won't be a thing in 1.12, doubt it will be a thing in 1.14, but who knows.
