### ISSUE TITLE
[1.12.2] Can't remove anything from Railcraft

### ISSUE THREAD

**Issue by Draskh** [CraftTweaker/CraftTweaker#691]
I tried to remove recipes from Railcraft but it don't work. It seems that Railcraft recipes can't be removed. 
Here is a simple script. -> https://pastebin.com/WuEMQhp2

Both commands did not work. recipes.remove and recipes.removeByRecipeName. 

Forge: 2796
Crafttweaker: 4.1.13
Railcraft: 12.0.0 Beta 2

See also: https://github.com/Railcraft/Railcraft/issues/1610

**Comment by jaredlll08** [comment]
Issue with other mod.
