### ISSUE TITLE
Downloading Crafttweaker gives minetweaker, Unable to use GUI, Recipes not Working

### ISSUE THREAD

**Issue by Rositchi** [CraftTweaker/CraftTweaker#693]
#### Issue Description:
I'm trying to play the 7 Days to Mine mod for minecraft. I've already run in to many issues and have messaged the developer, just waiting for a response and fixes (he is working alone so I know it will take time). I decided to see if I could add some of my own recipes, as progression is halted due to many crafting conflicts in the mod, by using CraftTweaker since there weren't any versions of MineTweaker I could use.

#### What happens:
I downloaded the CraftTweaker(2) mod and ModTweaker from curse forge. MultiMC reads it as MineTweaker and ModTweaker wants Crafttweaker. Without ModTweaker, everything works except I can't use the /ct gui command. All commands use /mt or /minetweaker only. The /mt rm also didn't work. There's no crash, just things not working.

https://imgur.com/a/cmxST2m
https://imgur.com/lahOEaJ
https://imgur.com/a/aImUZmi

#### What you expected to happen:
To have the actual Crafttweaker mod if possible or how to use the gui with minetweaker. Removal and addition of script recipes.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/cy7yZ0C1

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/a0D5YDZn
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.8.9
- Forge: 11.15.1.1808
- Crafttweaker: CraftTweaker-Customized-1.8.9-3.0.7, CraftTweaker-Mod-1.8.9
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

[https://pastebin.com/XdS6bcMc]

**Comment by jaredlll08** [comment]
1.8.9 isn't supported anymore.

You're probably reading the wiki for 1.12.2, which is different.
