### ISSUE TITLE
.noReturn doesn't work with <minecraft:milk_bucket>

### ISSUE THREAD

**Issue by dredhorse** [CraftTweaker/CraftTweaker#696]
#### Intro:
trying to add a recipe for converting minecraft milk into animania milk.

#### Issue Description:
crafting a vanilla milk bucket to animania milk bucket returns the animania milk bucket and leaves an empty bucket in the grid.

#### What happens:
see above

#### What you expected to happen:

crafting a vanilla milk bucket to animania milk bucket returns only animania milk bucket and consumes the original bucket

#### Script used 

val onlyMilk = <minecraft:milk_bucket>.noReturn();
recipes.addShaped(<forge:bucketfilled>.withTag({FluidName: "milk_jersey", Amount: 1000}), [[onlyMilk]]);
or
recipes.addShapeless( <forge:bucketfilled>.withTag({FluidName: "milk_friesian", Amount: 1000}),[<minecraft:milk_bucket>.noReturn()]);

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
not of relevance, no error in logs

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2784
- Crafttweaker:  4.1.13
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

if really required I can post it.

**Comment by jaredlll08** [comment]
Complete the template. We don't accept scripts not in a pastebin / gist.
I ALWAYS require the log, if I didn't, I wouldn't have made it a section.

**Comment by dredhorse** [comment]
crafttweaker. log https://gist.github.com/dredhorse/8ea702ac6cfa1c3f1c266cc2d4ec5718
lastest.log https://gist.github.com/dredhorse/0381d8df04d703fadb4415fe88c74e2d
full script: https://gist.github.com/dredhorse/b9a4f64a34afc27430000f8390b71c49
anything else?

**Comment by dredhorse** [comment]
@jaredlll08  do I need to open up a new issue?
