### ISSUE TITLE
JEI Category GameStages Support

### ISSUE THREAD

**Issue by NielsPilgaard** [CraftTweaker/CraftTweaker#699]
**Feature request name**
JEI Category GameStages Support

**Feature request description**
I'd like to request GameStages compatibility for the CraftTweaker function mods.jei.JEI.hideCategory(string category), in order to hide tabs that the player doesn't have access to, until the appropriate GameStage.
I imagine it would work like hideCategory, but with an addition string like so:

mods.jei.JEI.hideCategory(string stage, string category);

**Feature request reason**
- This feature would most likely reduce player confusion in the early game for my upcoming pack, aswell as reduce the time players need to spend searching through JEI.

**Feature request dependencies**
- JEI

**Comment by jaredlll08** [comment]
This is a request for gamestages, not us.

**Comment by NielsPilgaard** [comment]
Alright, thanks.
