### ISSUE TITLE
[Feature Request] Drops specific to entities killed by fire

### ISSUE THREAD

**Issue by ZeroLevels** [CraftTweaker/CraftTweaker#709]
**Feature request name**
Cooked Entity Drops

**Feature request description**
A drop function that replaces an existing item from an entity's drops with another assuming the mob dies by fire.

**Feature request reason**
The drops functionality seems incomplete without a more simple method to do this.

**Feature request dependencies**
I don't think so.  The functionality exists within vanilla when killing mobs with fire, such as cows, pigs, and chickens.

**Comment by jaredlll08** [comment]
You can use the damage source given from the EntityLivingDeathEvent to determine if it was killed by fire, and drop different items.
