### ISSUE TITLE
Support Overwrite of Recipe based on RecipeNames

### ISSUE THREAD

**Issue by dredhorse** [CraftTweaker/CraftTweaker#710]
**Feature request name**
Overwriting of Recipe based on  RecipeNames

**Feature request description**
ATM if I remove a Recipe By Name it looks like the Advancement which triggers on that name breaks. So I would like to be able to Overwrite a Recipe based on the RecipeName.

**Feature request reason**
If I want to make a default recipe harder I need to replace it. I replace it by removing the original recipe by name and then creating a new one. ATM, it doesn't seem to work to add the original recipename into the function.

**Feature request dependencies**
Don't know.

**Comment by jaredlll08** [comment]
When you replace a recipe, Forge throws a fit and complains in the console, java io is slow, so I don't really want to cause a bunch of slow downs doing something that forge doesn't like.

**Comment by dredhorse** [comment]
well that wouldn't be very good, it was just an idea.
