### ISSUE TITLE
Game crashes on startup when removing Ex Compressum recipes

### ISSUE THREAD

**Issue by Insane96** [CraftTweaker/CraftTweaker#712]
#### Issue Description: 
Game crashes on startup when removing Ex Compressum recipes

#### What happens: 
Game crashes on startup

#### What you expected to happen: 
Game should run properly

#### Script used: 
https://hastebin.com/owejoxoqep.css

#### crafttweaker.log file: 
https://hastebin.com/avoguvitiw.md

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2768
- Crafttweaker: 4.1.14
- Using a server: No

#### Your most recent log file where the issue was present: https://hastebin.com/yatazerezo.makefile

**Comment by jaredlll08** [comment]
Report to ex compression.
