### ISSUE TITLE
issue removing icbm classic recipes

### ISSUE THREAD

**Issue by Nbgreen** [CraftTweaker/CraftTweaker#713]
hi I'm not sure what I doing wrong but here is what I'm doing to removed the recipe

recipes.removeShaped(<icbmclassic:explosives:22>, 
 [[<minecraft:nether_star>, <ore:netherStar>, <ore:netherStar>], 
  [<minecraft:nether_star>, <icbmclassic:explosives:15>, <ore:netherStar>], 
  [<minecraft:nether_star>, <minecraft:nether_star>, <ore:netherStar>]]);

I can add recipes just fine but removing them I cant get to work any help would be appreciated.
im using
CraftTweaker2-1.12-4.1.13
ICBM-classic-1.12.2-3.3.0b60

**Comment by jaredlll08** [comment]
Follow the template.
