### ISSUE TITLE
ERROR: Sysem: TileEntity is already defined in that package (Occurs while no scripts are present)

### ISSUE THREAD

**Issue by CelestialPhoenix** [CraftTweaker/CraftTweaker#715]
#### Issue Description:
Upon loading a world, the following appears in chat:
ERROR: Sysem: TileEntity is already defined in that package

/ct syntax does not reveal any errors, and this issue is repeatable even with no files/folders in .minecraft/scripts.
Exiting and reloading the world causes the message to appear twice, then 3 time, 4 times ect...

This also appears in the first line of the CrafterTweaker log.
#### Script used 
All scripts removed and the issue still occurs.

#### crafttweaker.log file 
https://pastebin.com/YPA9HyF0
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 12.23.5.2779
- Crafttweaker: 4.1.14
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://raw.githubusercontent.com/CelestialPhoenix/Blood-Sweat-and-Gears-1.12.2/master/error%20log

**Comment by jaredlll08** [comment]
update contenttweaker.
