### ISSUE TITLE
placed seed doesn't count as block?

### ISSUE THREAD

**Issue by MSandro** [CraftTweaker/CraftTweaker#716]
#### Issue Description:
I am not sure if this is a bug in ModTweaker but I have troubles to set a recipe where I have to define a block and I whant to set this variable to a placed seed. If a player places a seed it is automaticaly minecraft:weat. So CraftTweaker says "Input Block is not a block. Did not add recipe.".

#### What happens:
I can not add a SkyResources Liveinfusion recipe with a input block with "minecraft:wheat" because it is a item.

#### What you expected to happen:
I thought "minecraft:wheat" counts as a block too because it is a placed seed.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
```
//mods.skyresources.infusion.addRecipe(IItemStack output, IItemStack inputStack, IItemStack inputBlock, int health);
mods.skyresources.infusion.addRecipe(<minecraft:wheat>, <actuallyadditions:item_fertilizer>, <minecraft:wheat>, 10);
```

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2808
- Crafttweaker: 4.1.14
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 
https://gist.github.com/MSandro/cac7dc26173c6890843bf09ed4ae0fac

**Comment by jaredlll08** [comment]
We don't add support for SkyResources, so I don't know what they are looking for, you would get better help if you reported it to their repo.

**Comment by Syndaryl** [comment]
Try dumping the list of blocks and see what you get for it.
