### ISSUE TITLE
Suggestion - Fluid displayName ZenSetter

### ISSUE THREAD

**Issue by nephatrine** [CraftTweaker/CraftTweaker#718]
**Feature request name**
Fluid displayName ZenSetter

**Feature request description**
I would like the ability to change a fluid's displayName via CraftTweaker.

**Feature request reason**
This would be useful for all the same reasons changing an item's displayName would be useful. For instance if I have multiple mods that add Honey with different registry names I could give them different displayNames as well to allow them to be differentiated in-game. Or if multiple mods add molten metals with different naming conventions and I'd like to make them consistent. Or if dramatically changing the purpose of a liquid like changing Inspiration's Beetroot Soup to be Beetroot Juice and using Soot's Boiling Beetroot Soup as the normal Beetroot Soup liquid.

**Feature request dependencies**
If it's possible at all (and I realize the lack of one already may be a sign that it isn't) then I don't think there'd be any other mods or anything needed to make use of this aside from Forge itself.

**Comment by jaredlll08** [comment]
Fluids don't really have a way to change their name like ItemStacks do, a workaround would be changing the localization of the fluid's unlocalized name?
