### ISSUE TITLE
ERROR: [crafttweaker | SIDE_CLIENT]

### ISSUE THREAD

**Issue by ThunderBolt6** [CraftTweaker/CraftTweaker#721]
#### Issue Description:
Trying to add item to oredict(probably nothing relative to CT and more due to the other mod)
mods: CT, Foamfix, Journeymap, JEI, Vics ModernWarfare(maybe the issue is from this and not from CT)

#### What happens:
Cant add to oredict

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

ore:wireCopper.add(<mw:copperwiring>);

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

[URL](https://pastebin.com/vGzjvdEA)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Crafttweaker: 4.1.14
- Using a server: no

#### Your most recent log file where the issue was present: 

[URL](https://pastebin.com/HCi5WqXi)

**Comment by jaredlll08** [comment]
We don't support vics modern warfare. The author doesn't care about crafttweaker support and does extremely stupid things with his code.
