### ISSUE TITLE
/CTGUI craftingtable responds with "unknown command"

### ISSUE THREAD

**Issue by TenTonBlue** [CraftTweaker/CraftTweaker#722]
#### Issue Description:
The /CTGUI craftingtable and /CTGUI furnace commands do not pull up a GUI and i get an "unknown command" response. This is in a modpack(Resonant Rise 4) however it seems very specific to CraftTweaker. I have spent a couple of hours googling for answers and havent been able to find a single one. I have looked through the 33 help pages to see if i have the command format wrong but I am copying it exactly as it appears on the CraftTweaker Wiki page and I dont even see the /CTGUI command listed in /help.

I am running the server with McMyAdmin I have double checked that the mod exists on both client and server. I have Opped myself and double checked the McMyAdmin settings to make sure i have access to all commands.

#### What happens:
"unknown command" after using /CTGUI craftingtable and/or /CTGUI furnace

#### What you expected to happen:
A GUI to open.

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):<script src="https://pastebin.com/embed_js/mRPY7p2v"></script>

____
#### Affected Versions (Do *not* use "latest"):
1.10.2
- Minecraft:
- Forge: forge-1.10.2-12.18.3.2511-universal
- Crafttweaker: 
- Using a server: McMyAdmin - Running off home desktop with Windows 10
- If yes, does the client have the exact same scripts?
Yes
#### Your most recent log file where the issue was present: 
I have checked for a log file and cannot find one for CraftTweaker
[pastebin/gist/etc link here]
https://pastebin.com/embed_js/mRPY7p2v

**Comment by kindlich** [comment]
The ctgui command only works in single player.
It is not supposed to be run in Multiplayer, just edit the recipes locally and copy the scripts to the server ^^
