### ISSUE TITLE
Work only last script in avaritia 

### ISSUE THREAD

**Issue by alesha229** [CraftTweaker/CraftTweaker#733]
Works last only the last script when crafting Avaritia.If you change the order of the scripts, the latter will always work, and the rest will not.Vanilla recipes are fine.

[avaritiarecipemakeroutput.txt](https://github.com/CraftTweaker/CraftTweaker/files/2860259/avaritiarecipemakeroutput.txt)

**Comment by jaredlll08** [comment]
Follow the template.
we don't support Avaritia.
I'm not downloading some random ass file.
