### ISSUE TITLE
Ghost Recipes Added by ExtraUtils still show in JEI when using replaceAllInstanceOf

### ISSUE THREAD

**Issue by KAfable** [CraftTweaker/CraftTweaker#734]
#### Intro:
Bit of a weird one, sorry if my description is subpar. Extra Utilities 2 adds vanilla convenience recipes such as 8 logs in a crafting grid in a hollow box shape make 4 chests. 

There are configs to turn them off, which work perfectly fine until we started using replaceAllInstanceOf in our script to replace all ingots with plates. Script here: https://gist.github.com/Vyraal1/35fd602b6c2fbe666558faac6ab31c6d

It runs at a higher priority because it also handles some of the other ore dictionary unification issues before other scripts get thrown into the mix.

For what it's worth, yes we also do recipes.remove(<minecraft:chest>) as well, but they still show up, all relevant chest recipes are here in minecraft.zs: https://gist.github.com/Vyraal1/96585fa56f324624ef0fe7ff90f2f0c3

This is how JEI looks like in the game: 
![image](https://user-images.githubusercontent.com/26587049/52818655-552f9780-3075-11e9-849e-c907b81dcb81.png)

The recipe itself does not craft, but JEI still holds it.

#### Issue Description:
Ghost recipe shows up in JEI for Extra Utils 2 recipes additions when we started using replaceAllInstanceOf, after commenting it out, the chest recipe removals worked as intended.

#### What happens:
The ghost recipes show up in JEI when they shouldn't, the recipes are not valid and do not craft anything, but are still misleading to players.

#### What you expected to happen:
For the ghost recipes to go away, and for the JEI output to look like this: 
![image](https://user-images.githubusercontent.com/26587049/52818737-8e680780-3075-11e9-8e3f-113f693cb132.png)
which was only possible after commenting out all lines of script that had replaceAllInstanceOf

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
Scripts were linked above with gist.

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/Vyraal1/d9d7dd7447b85077922314156ad8073b

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2e
- Forge: 2795
- Crafttweaker: 4.1.14
- JEI: 4.14.4.264
- Using a server: Yes, also happens on client
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://gist.github.com/Vyraal1/714562110ef0be1056bcc841af6bfb84

**Comment by jaredlll08** [comment]
XU2 is doing really weird stuff with these recipes specifically, I'm guessing some of that weird stuff is causing issues, not much I can do on my side.
