### ISSUE TITLE
crafttweaker.world.IFacing returns all north

### ISSUE THREAD

**Issue by geezmolycos** [CraftTweaker/CraftTweaker#735]
#### Issue Description:
All IFacing seems to be IFacing.north() and IFacing.fromString() is unavailable

#### What happens:
I can't access IFacing.up(), IFacing.south() ... except for IFacing.north().
Because all of them returns the value that is identical to IFacing.north().
When I tried to access them by fromString method of IFacing, I found it unavailable.

#### What you expected to happen:
IFacing.up(), IFacing.south(), IFacing.east(), etc. should return different values representing the real direction.

#### Script used:
[Script](https://pastebin.com/cPDJZPts)

#### crafttweaker.log file:
[Log](https://pastebin.com/FTSSxxPv)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.5.2811
- Crafttweaker: 4.1.14
- Using a server: No

#### Your most recent log file where the issue was present: 

[Log](https://pastebin.com/FTSSxxPv)

**Comment by jaredlll08** [comment]
fixed in PR
