### ISSUE TITLE
Underwater Detection

### ISSUE THREAD

**Issue by kaylee-kiako** [CraftTweaker/CraftTweaker#737]
**Feature request name**
Underwater Detection

**Feature request description**
The function to detect if an entity is fully submerged in water. Currently we have `isInWater` and `getAir()`, which come close though do not fully and efficiently include what I would want. Particularly, this only truly to detect if the underwater breathe meter should appear or not.

Side note; it would also be handy to be able to see how submerged something is, like “is submerged  45% of entity height” so one could perform a function if they’re knee deep, waist-deep, etc, though this isn’t needed (at least for my purposes, yet).

**Feature request reason**
Personally I was just going to burn out all the torches and perhaps ruin foodstuffs, etc, when the player was fully submerged in water, though many things could be done depending on the modpack maker’s creativity.

**Feature request dependencies**
For my main intended purpose, it’s only handy with Realistic Torches included, but that’s not really a _necessary_ dependency per se.

**Comment by jaredlll08** [comment]
The way vanilla does it is:


```java
this.isInsideOfMaterial(Material.WATER)
```
which is a method that already exists in ZS

```
entity.isInsideOfMaterial(crafttweaker.block.IMaterial.air())
```
