### ISSUE TITLE
[SUGGESTION] more guis....

### ISSUE THREAD

**Issue by Archilyte** [CraftTweaker/CraftTweaker#739]
**Moar GUIs please????????**
The name for the feature request, something short and descriptive, example: "Blockstate Support"

**GUIs for machines and other stuff from other mods, please?**
Describe what you would like added

**I am asking for this because some people like me hava a very hard time with zscriptings, so this would make mine (and many others) life easier**
Why do you need this? / Why do you think this would be useful?

**This will be useful when used with other mods**
Does the feature request require anything to be implemented? / Will this feature request only be useful when combined with another mod?

**Comment by jaredlll08** [comment]
Not a valid request.

No other GUIs will be added, it is a simple scripting language. Learn it.
