### ISSUE TITLE
Importing EnderIO Package Error

### ISSUE THREAD

**Issue by triffman33** [CraftTweaker/CraftTweaker#742]
#### What happens:

importing enderio package returns an error.
(Unsure if this is an EnderIO issue so posting here to begin with)

#### What you expected to happen:

Importing the enderio package correctly.

#### Script used:

import mods.enderio.SagMill;

#### crafttweaker.log file

https://pastebin.com/tiKzet3T
____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: forge-14.23.5.2815
- Crafttweaker: CraftTweaker2-1.12-4.1.14
- EnderIO: EnderIO-1.12.2-5.0.40
- Using a server: No

**Comment by jaredlll08** [comment]
Don't change the log files -.-
Upload your whole script.
