### ISSUE TITLE
Importing EnderIO Package Error [Re-Upload]

### ISSUE THREAD

**Issue by triffman33** [CraftTweaker/CraftTweaker#743]
#### What happens:
importing enderio package returns an error.
(Unsure if this is an EnderIO issue so posting here to begin with)

#### What you expected to happen:
Importing the enderio package correctly.

#### Script used:
https://pastebin.com/SqR47r4M
(Don't judge I'm new to this)

#### Crafttweaker.log file
https://pastebin.com/7zuvmB0E

____
#### Affected Versions:
Minecraft: 1.12.2
Forge: forge-14.23.5.2815
Crafttweaker: CraftTweaker2-1.12-4.1.14
EnderIO: EnderIO-1.12.2-5.0.40
Using a server: No

**Comment by kindlich** [comment]
Do you have EnderTweaker installed?
Neither EIO, nor ModTweaker add the support, that's a 3rd party addon.

**Comment by triffman33** [comment]
Oh sorry didn't realise I needed an addon for the EnderIO support 😅  thank you for letting me know, it works now! 👍
