### ISSUE TITLE
Items hidden with JEI.hide() show when textures reload (F3+T)

### ISSUE THREAD

**Issue by justinrusso** [CraftTweaker/CraftTweaker#744]
#### Issue Description:
When hiding an item using `mods.jei.JEI.hide(toHideItem);`, the item will be hidden in JEI but will be visible when a texture reload is down (F3+T). This behaviour does not seem to exist with JEI's blacklist.

#### What happens:
When reloading textures, the items are visible in JEI.

#### What you expected to happen:
The items will remain hidden through reloads.

#### Script used:
https://pastebin.com/sDeRM7sR

#### crafttweaker.log file:

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2815
- Crafttweaker: 4.1.14
- Using a server: No

**Comment by jaredlll08** [comment]
Already fixed
