### ISSUE TITLE
Script is literally doing nothing

### ISSUE THREAD

**Issue by Sweddy** [CraftTweaker/CraftTweaker#745]
#### Issue Description:
I have created what might just be the simplest script ever. All it is supposed to do is remove one recipe from a mod. But it doesn't. The recipe remains, even though the crafttweaker.log file claims that the script has been read. The main.zs file is definitely a .zs file, because I copied the recipe.zs created by the /ct gui command (which also doesn't work), removed its contents, renamed the file to main.zs, and wrote my one string of code.

#### What happens:
Nothing. The recipe remains and is craftable despite the script reading that it should be removed.

#### What you expected to happen:
That the recipe be removed.

#### Script used:
https://gist.github.com/Sweddy/12ebeca246905c83e3aac11246ac396e

#### crafttweaker.log file:
https://gist.github.com/Sweddy/eb9e141a994ad83903f2f1a779209505

____
#### Affected Versions:
- Minecraft: 1.12.2
- Forge: release 1.12.2-forge1.12.2-14.23.5.2814
- Crafttweaker: CraftTweaker2-1.12-4.1.15
- Using client, not a server.

#### Your most recent log file where the issue was present: 
https://gist.github.com/Sweddy/eb9e141a994ad83903f2f1a779209505
It's the same crafttweaker.log file.

**Comment by jaredlll08** [comment]
The log file it asks for is the game log file...

**Comment by jaredlll08** [comment]
other mod doesn't know how to follow convention.
