### ISSUE TITLE
Add an EntityLivingThrowItemEvent

### ISSUE THREAD

**Issue by Jummit** [CraftTweaker/CraftTweaker#751]
Add an EntityLivingThrowItemEvent.

This event would be triggered if you throw a snowball, an egg or Biomes o' Plenty mud, etc.
This would be usefull because it would be easier to access the entity being created after the throw.

**Comment by jaredlll08** [comment]
There isn't an event in forge for when an entity throws something like that, there is an event for when a thrown entity impacts something, not sure if this is what you want though, if it is, make another issue..

**Comment by MentalMouse** [comment]
Is there an event for entity creation in general?  If so, you could maybe get at the snowball there.
