### ISSUE TITLE
ILoadedMods parse error

### ISSUE THREAD

**Issue by BasieBrinkie** [CraftTweaker/CraftTweaker#753]
#### Intro:
In Crafttweaker 4.1.14 I had a for loop for all mods but since I have updated to 4.1.15 it errors when used in a for loop.

#### Issue Description:
My particular for loop was a little bigger but the same happens when you'd run the for loop with ILoadedMods in it from the crafttweaker docs

#### What happens:
It outputs the following error: 

> Error parsing line 1:23 - ; expected

#### What you expected to happen:
I expect that the for loops runs and prints all item names

#### Script used 
https://gist.github.com/BasieBrinkie/5184d38184ef5efa64caa027cdb8f241

#### crafttweaker.log file
https://gist.github.com/BasieBrinkie/ecff9172cb9faf598d0ce5378981480b

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2821
- Crafttweaker: 4.1.15
- Using a server: No

**Comment by jaredlll08** [comment]
fixed in dev.
