### ISSUE TITLE
replace all occurance not working

### ISSUE THREAD

**Issue by galyfray** [CraftTweaker/CraftTweaker#754]
#### Issue Description:
1: the wiki says something wrong or
2: the recipes.replaceAllOccurences isn't working
trying to use a code part copy from the wiki

#### What happens:

not working at all

#### What you expected to happen:

"replaces in recipes for any recipe output except tnt" just as the wiki says:

https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Recipes/Crafting/Recipes_Crafting_Table/
 in the "Replace all item ingredients with another one" part 

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://gist.github.com/galyfray/d12aca74266fbbe07338267a09e913fb

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://gist.github.com/galyfray/b9f352360af3208bf8f9340317df0b65
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12
- Forge: 14.23.5.2768
- Crafttweaker: 4.1.9
- Using a server: no
- If yes, does the client have the exact same scripts?

**Comment by kindlich** [comment]
You might want to update CraftTweaker (you are on 4.1.9 as per your statement whereas the latest release is 4.1.16)
