### ISSUE TITLE
[Suggestion] command to print all available attributes to log

### ISSUE THREAD

**Issue by xkforce** [CraftTweaker/CraftTweaker#756]
**Feature request description**
Similar to the other commands that print a collection of things to the log like recipes, entities, potions etc. I am proposing that a command be added that allows you to do the same with attributes.

**Feature request reason**
It'd make it a lot easier to test and use different attributes available in a pack; especially larger more complex ones.

**Comment by jaredlll08** [comment]
Attributes?

**Comment by xkforce** [comment]
Examples would be generic.movementSpeed and generic.attackDamage.  The vanilla ones are easy to obtain but if you've got a large pack with a large number of mods, it can be problematic to assess the full extent of what you actually have access to.

**Comment by jaredlll08** [comment]
There isn't a global attribute map unfortunately.
