### ISSUE TITLE
crafting recipes are not getting removed

### ISSUE THREAD

**Issue by lyratcm** [CraftTweaker/CraftTweaker#758]
#### Issue Description:
crafting recipes are not getting removed
I am playing po3 and some recipes are meant to be roved to be replaced by different custom ones but the recipes are not getting removed. Although the new ones are being added they are not actually craftable. have verified that all the script are there

#### What happens:
recipes were not removed 

#### What you expected to happen:
only the new recipes to be able to be crafted and viewed

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/dCqzgG0p
https://pastebin.com/kAfYstUJ
there are quite a few more files for the different script for different mods etc. but didn't feel them be relevant
#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/tjs8qpX3
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.2
- Forge:14.23.5.2808
- Crafttweaker: 1.12-4.1.14
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 
https://gist.github.com/dan3401/a27a6fb443443c34331950fd1daffda7

**Comment by jaredlll08** [comment]
As the description at the top said, if you're playing a pack and are having issues, report it to the pack author.

If the pack author still thinks it is an issue then they can report it to me.

Also you're using an old crafttweaker version, update that and try again
