### ISSUE TITLE
More info in liquid dumps

### ISSUE THREAD

**Issue by lynaevm** [CraftTweaker/CraftTweaker#760]
**Feature request name**
"More info when getting dumps, like /ct liquids"

**Feature request description**
I would like to be able to get the temperature or viscosity values for fluids already in the pack.

**Feature request reason**
When defining new fluids (and other items/blocks as well I'm sure), especially on things like viscosity or temperature that can have a broad range, it is important to put them in relation to already existing items.  So to be able to say something is cooler than lava but hotter than water, for example.  Useful when making them available to thermoelectric generators, for example.

**Feature request dependencies**
It seems like it could apply to a number of different things on vanilla factory blocks and fluids.

**Comment by Syndaryl** [comment]
I'd also suggest logging which mod registered the fluid, if that information is available.
