### ISSUE TITLE
Syntax for changing display name of items with nbt data that aren't produced by crafting

### ISSUE THREAD

**Issue by xkforce** [CraftTweaker/CraftTweaker#761]
As far as I can tell, there isn't really a good way of renaming an item with nbt data on it that isn't produced through crafting. eg. tipped arrows produced by firing an arrow through a lingering potion cloud of a custom potion.  Normally I would modify/apprend nbt data on to the item in question to rename it (like an anvil does) but this only works for items that are crafted in some fashion.  Alternatively modifying the lang file would allow for certain items like certain potions to be renamed but again, this only works for items that have specific listings in the lang file.  It doesn't work for higher levels of potions or "uncraftable" tipped arrows that are produced from shooting arrows through a custom potion lingering cloud.  I've tried various means of using displayName to attempt to do this but that doesn't appear to work either.  I've also entertained the idea of trying to modify what arrows are produced from shooting arrows through lingering potion clouds but this has proved to be... problematic.

**Comment by jaredlll08** [comment]
god damn that wall of text.


There is no way to 100% of the time set an item name, mods can override the name to always be something, regardless of lang or nbt.

If setting it via lang, or via NBT doesn't work, then nothing will.
