### ISSUE TITLE
Furnace Enhancements

### ISSUE THREAD

**Issue by SwordsmanJoe** [CraftTweaker/CraftTweaker#763]
You know how players can get a bucket of water from smelting a sponge? Is there already a way to add furnace recipes like that? If not, this would be cool to have for some creators I'm certain

**Comment by kindlich** [comment]
First, please follow the Issue templates, there is a reason for the feture request template.

Second, as far as I know, that behaviour is hard-coded to only work for sponges and the empty bucket.
