### ISSUE TITLE
botania daisy command returns error

### ISSUE THREAD

**Issue by lynaevm** [CraftTweaker/CraftTweaker#765]
#### Issue Description:
command "/ct botania daisy" misbehaving

#### What happens:
"An unknown error occurs while attempting to perform this command" is returned ingame but the crafttweaker log does in fact show a list of recipes.

#### What you expected to happen:
List Generated and link to log

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2815
- Crafttweaker: CraftTweaker2-1.12-4.1.15
- Using a server:  No
- If yes, does the client have the exact same scripts?

**Comment by jaredlll08** [comment]
Can't help if we don't have a log.
