### ISSUE TITLE
Craft Tweaker problem with ae2

### ISSUE THREAD

**Issue by BedrockLegends** [CraftTweaker/CraftTweaker#767]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
It would seem any time I add a Variable for Storage Component using Crafttweaker that it does not work and gives an error of Error: [crafttweaker | SIDE_Client]; Error Parsing when it is setup to like all the other Variables in the script and those work but none of the Storage Component or Storage cells can use a custom Variable to make a custom script. Ae2 team sent me your way

#### What happens:

I take my script posted below and add the following in a custom variable for <appliedenergistics2:material:37> and change it to 16kCrafting but then it throws the error above on anything that has a crafting component or storage cell. This is why in my script u will see the ones that dont use variables are the ones that do not work and throw the same error above

#### What you expected to happen:
Away to have it looked into or fixed

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://gist.github.com/SacrificialFlame/d5d45daf8ab2284c9bfa4d02d2114c75

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2808
- Crafttweaker: 1.12-4.4.17 and below
- Using a server: no not yet
- If yes, does the client have the exact same scripts? yes

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by BedrockLegends** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3980

**Comment by kindlich** [comment]
Could you also add the crafttweaker.log file?
We can't help you much without it.

Also, could you please isolate the error into a simpler file, like with only one or two variable declarations to rule out other influences?

**Comment by jaredlll08** [comment]
Where's the log files?

**Comment by BedrockLegends** [comment]
I can provide the Crafttweaker.log file after I reset up the script so it throws the error its been doing here in a few mins

https://gist.github.com/SacrificialFlame/9e8a36d43fc28f5536f4790321d817d2 Log but does not show error

This is what is saying is broken in the script but its matches everything else     var 16kCraftingComp = <appliedenergistics2:material:37>;

**Comment by BedrockLegends** [comment]
![2019-03-31_13 12 17](https://user-images.githubusercontent.com/48525410/55292989-9e823f00-53b6-11e9-869c-4c0c0411ed54.png)

**Comment by jaredlll08** [comment]
can you post your scripts and the log at the same time, the line numbers are off, so we don't actually know what the issue is

**Comment by BedrockLegends** [comment]
Here's the log and script combined as I am not sure what ur asking.
https://gist.github.com/SacrificialFlame/f4f35164ee328af08d5ec9633edbb868

**Comment by kindlich** [comment]
You may not start a variable name with a digit.
Either a letter (a-z or A-Z) or an underscore

**Comment by jaredlll08** [comment]
Just for future reference, please don't give us different scripts and logs, the script you gave us in the initial report doesn't have the issue you are even reporting.
