### ISSUE TITLE
1.12.2 Can not be used forge-1.12.2-14.23.5.2815-installer

### ISSUE THREAD

**Issue by G0dLy** [CraftTweaker/CraftTweaker#768]
[crash-2019-04-05_13.53.32-server.txt](https://github.com/CraftTweaker/CraftTweaker/files/3046555/crash-2019-04-05_13.53.32-server.txt)
forge-1.12.2-14.23.5.2815-installer

**Comment by jaredlll08** [comment]
Follow the template.

Also you are using an old crafttweaker.
