### ISSUE TITLE
/ct give doesnt include some of NBT data

### ISSUE THREAD

**Issue by Secretname2009** [CraftTweaker/CraftTweaker#769]
#### Issue Description:

I was trying to give myself an item with specific NBT data using /ct give and i used the line below.
<tconstruct:large_plate>.withTag({Material: "infinity_avaritia_plustic"})

#### What happens:
I get a Large Plate with material tag in it without its data which was supposed to be the material above

#### What you expected to happen:

I expected to get a Infinity Large Plate

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/XP81QQPv

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/wFRHPAhR

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge:14.23.5.2824
- Crafttweaker: 4.1.17
- Using a server: No

#### Your most recent log file where the issue was present: 
I cannot provide the log as its too big for pastebin. The issue does not reflect on the latest.log as i can see.

**Comment by jaredlll08** [comment]
Your pastebin links have expired.

can you upload them to gist.github.com?

**Comment by Secretname2009** [comment]
Here are the gist links to the log and the script file.

Main Recipes.zs (Script File used)
https://gist.github.com/Secretname2009/ae0d641d5032760bb0a51f66b6c2aad3

Crafttweaker.log
https://gist.github.com/Secretname2009/ced1c7a6311b6630b980f7851b641fe3
