### ISSUE TITLE
Expose ThrowableImpactEvent as an event

### ISSUE THREAD

**Issue by Jummit** [CraftTweaker/CraftTweaker#770]
Maybe ProjectileImpactEvent could be exposed aswell.
My use case: spawn baby slimes when an egg hits the ground.
ProjectileImpactEvent could also be used to set blocks on fire that are hit by a flaming arrow.

EDIT: I just noticed that ThrowableImpactEvent is deprecated and that there is [a subclass for ProjectileImpactEvent,](https://github.com/MinecraftForge/MinecraftForge/blob/633fd9bd2eea06abd2eb42484439a5250236435b/src/main/java/net/minecraftforge/event/entity/ProjectileImpactEvent.java#L92) which makes this easier.

**Comment by jaredlll08** [comment]
I am hesitant to add new features as 1.12 is already at the end of the life cycle, anything I add now won't be supported (as I'm moving to 1.14 fully), so unfortunately this won't happen
