### ISSUE TITLE
Recipes not showing

### ISSUE THREAD

**Issue by BadKaiPanda** [CraftTweaker/CraftTweaker#771]
#### Intro:
Creating a mod pack and recipes not linking with JEI, same as https://github.com/CraftTweaker/CraftTweaker/issues/684

#### Issue Description:
Recipes created in CT don't show up in JEI on modded items

#### What happens:
On modded items/Mods it does not show new recipes created with CT

#### What you expected to happen:
Show the recipes in JEI

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/cu2BesfM

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/LaNCikmQ

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge:
- Crafttweaker: CraftTweaker2-1.12-4.1.17.jar
- Using a server: Yes
- If yes, does the client have the exact same scripts?
Should have but shouldn't it sync client users can mess with local.

#### Your most recent log file where the issue was present: 
no possible at the mo.

**Comment by jaredlll08** [comment]
I'm going to need a more concrete answer to if the clients have the same scripts.


Does it work fine in single player?

**Comment by BadKaiPanda** [comment]
Yes they are the same but are you saying as a mod pack/server own the scripts are able to be messed with ?

**Comment by jaredlll08** [comment]
What.

Scripts are not synced from the server to the client, they need to be exactly the same on both sides.

Also does it work in single player?

**Comment by BadKaiPanda** [comment]
I am reloading it now to test local play 4 you I comment back in about 5 mins

**Comment by BadKaiPanda** [comment]
I updated the script not to use the ore dir and it seems to fixed it, I think the problem was not with your tool but minetweaker as I told it not to use ore in the first place I will pass this on to that dev.

**Comment by BadKaiPanda** [comment]
![2019-04-18_19 28 24](https://user-images.githubusercontent.com/10765013/56382804-2c13ba80-6210-11e9-92f3-16054d7d3d93.png)
 Nevermind I was wrong it's still showing the old recipe

Local is the same
![2019-04-18_19 32 15](https://user-images.githubusercontent.com/10765013/56383025-b52af180-6210-11e9-922d-ca79c1daff75.png)

**Comment by kindlich** [comment]
If the recipe you are trying to remove is the only recipe for that item, why not instead just use 
```
recipes.remove(<uncraftingtable:uncrafting_table>);
```
?

**Comment by BadKaiPanda** [comment]
> If the recipe you are trying to remove is the only recipe for that item, why not instead just use
> 
> ```
> recipes.remove(<uncraftingtable:uncrafting_table>);
> ```
> ?

I will give a try with this item at least should fix that but I had a few problems with other mods with it in the past but it's all trial and error at this point thanks for the tip I give it a try soon.

**Comment by jaredlll08** [comment]
@BadKaiPanda any update?

**Comment by BadKaiPanda** [comment]
The uncrafting table one was fixed but I not sure if I am messing up with the code or what but the diamond vanilla pickaxe wont remove,  yes both configs are the same
`recipes.removeShaped(<minecraft:diamond_pickaxe>, [[<minecraft:diamond>], [<minecraft:diamond>], [<minecraft:diamond>],[null, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.removeShaped(<minecraft:diamond_pickaxe>, [[<ore:gemDiamond>], [<ore:gemDiamond>], [<ore:gemDiamond>],[null, <ore:stickWood>, null], [null, <ore:stickWood>, null]]);`
https://pastebin.com/1jxzCuc4

I have not fully removed the diamond recipe because the recipe I want is already defined in another mod and I really see it pointless having to redefine it, plus the iron pickaxe as removed it's the diamond one that's just not playing ball.

**Comment by BadKaiPanda** [comment]
@jaredlll08 still unable to remove the default recipe stated above.

**Comment by jaredlll08** [comment]
The recipes you just posted are the wrong format, using: 
```
recipes.removeShaped(<minecraft:diamond_pickaxe>, [[<ore:gemDiamond>, <ore:gemDiamond>, <ore:gemDiamond>],[null, <ore:stickWood>, null], [null, <ore:stickWood>, null]]);
```

I can remove the diamond pickaxe from my game.


If you can't remove other recipes, it is most likely another mod adding the recipe *after* we remove recipes, which is not something I can fix.

**Comment by jaredlll08** [comment]
update?

**Comment by jaredlll08** [comment]
Closing due to no update. How am I meant to know if it's fixed if I don't get told?

**Comment by BadKaiPanda** [comment]
It seems i didn't get told about this update, also the UI seemed to do that so OK I will go and look at the codes again and make sure there not adding everything in to another bracket.

Sorry for the late reply I didn't see no notification
