### ISSUE TITLE
Feature request: JEI recipe hiding without removing the recipes or hiding the items.

### ISSUE THREAD

**Issue by LumberWizard** [CraftTweaker/CraftTweaker#772]
**Feature request name**
JEI recipe hiding.

**Feature request description**
A method that hides a recipe in JEI by recipe name, without hiding the result item, or other recipes to craft it.

**Feature request reason**
Why I want it: EnderIO adds recipes to make vanilla blocks and items that use iron bars, with its iron alloy, but it adds them in a way that its JEI integration shows the recipe cycling between iron bars and EnderIO's fake iron. I want JEI to stop showing the vanilla recipes, and only show the EnderIO recipes, without removing the vanilla recipes because then the log complains about the advancements missing or something.
Why it could generally be useful: It could be useful for pack makers wanting to have items visible in JEI, whose recipes are secret and found some other way.

**Feature request dependencies**
It will only be useful when combined with JEI.

**Comment by jaredlll08** [comment]
The method to hide a recipe is deprecated and says it shouldn't be used, so unfortunately I can't do this.
