### ISSUE TITLE
Crash when crafting an item using a recipe from another mod

### ISSUE THREAD

**Issue by justinrusso** [CraftTweaker/CraftTweaker#773]
#### Issue Description:
Crash when attempting to craft an item from a different mod. This recipe is staged using recipe stages.

https://pastebin.com/c3mKJLTX
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2831
- Crafttweaker: 4.1.17
- Using a server: Both

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by kindlich** [comment]
Oh cmon, you know the drill, script, CrT log etc

**Comment by jaredlll08** [comment]
Fixed by a commit
