### ISSUE TITLE
[Bug] JEI hiding does not hide certain items

### ISSUE THREAD

**Issue by Skillotic0703** [CraftTweaker/CraftTweaker#774]
#### Issue Description:
When using a script to hide all items in JEI, some items still remain visible.

#### What happens:
Most items are hidden but not all of them.
![image](https://user-images.githubusercontent.com/12701912/56437908-72851a00-62e1-11e9-9caf-329dd94576ea.png)

#### What you expected to happen:
I expected that all items would be hidden.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/Aq9KfCxL

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/B0W5fpq2

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge:14.23.5.2836
- Crafttweaker: 4.1.17
- Using a server: no

**Comment by Skillotic0703** [comment]
I know I can use the blacklist in JEI's configs but I thought you would like to know

**Comment by JoelZBub** [comment]
Your script is doing exactly what it is supposed to do, which is remove all items registered as ingredients.  The remaining items have no recipes, nor are they ingredients in any recipe.
To remove them, you'll need to `import crafttweaker.item.IItemStack;` and remove them individually as IItemStack items.

'''
static itemRemovalJEI as IItemStack[] = [
	<minecraft:barrier:0>,
	<minecraft:bedrock>,
	<minecraft:repeating_command_block:0>,
	<minecraft:structure_block:0>,
	<minecraft:structure_void:0>
];

for item in itemRemovalJEI {
	mods.jei.JEI.hide(item);
}
```

**Comment by JoelZBub** [comment]
Your script is doing exactly what it is supposed to do, which is remove all items registered as ingredients. The remaining items have no recipes, nor are they ingredients in any recipe.
To remove them, you'll need to import crafttweaker.item.IItemStack; and remove them individually as IItemStack items.

Here is an example script:
https://pastebin.com/Nktbwb4k

Edit : The water and lava are ILiquidStack
mods.jei.JEI.hide(<liquid:water>);
mods.jei.JEI.hide(<fluid:lava>);

**Comment by jaredlll08** [comment]
The way that we find items for mods require that the items can be found in the creative menu, which none of those items can be unfortunately.

You can however use:
```
game.items
```
to get a list of all items that crafttweaker can reference in a bracket with no metadata (top level, so `<minecraft:wool>` will show, but `<minecraft:wool:1>` won't show.
