### ISSUE TITLE
Unknown error on server

### ISSUE THREAD

**Issue by BadKaiPanda** [CraftTweaker/CraftTweaker#776]
#### Intro:
[00:05:14] [Server thread/ERROR] [uncraftingtable]: findMatchingRecipes :: Unknown IRecipe implementation crafttweaker.mc1120.recipes.MCRecipeShaped for item wwl:wwlidiamondswordblade
[00:05:14] [Server thread/ERROR] [uncraftingtable]: findMatchingRecipes :: Unknown IRecipe implementation crafttweaker.mc1120.recipes.MCRecipeShaped for item wwl:wwlidiamondswordblade

#### Issue Description:
Place item in uncrafting table and we get this error

#### What happens:
I put the item in the uncrafting table what I do with other items created in crafttweaker and this one gives errors not sure why

#### What you expected to happen:
Give the items recipe like it does for the rest

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/0GW22pVV

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.235.2824
- Crafttweaker: 4.1.17
- Using a server: Yes
- If yes, does the client have the exact same scripts?
yes

I can't find any information on what the bug is also the wiki no longer shows any recipes.add options it's just about other scripting I am little lost are we meant to still use the old MT3 wiki for that?

**Comment by BadKaiPanda** [comment]
Also forgot to state that items as no recipe from it's mod at this time.

**Comment by kindlich** [comment]
That error lies in the uncrafting table mod.
We use a custom IRecipe implementation to create the recipes, but however mods use them is not up to us.

Also, the uncraftingTable mod seems to offer a special way of adding recipes that are supposed to be uncraftable:
<https://github.com/crazysnailboy/UncraftingTable/blob/master/src/main/java/org/jglrxavpok/mods/decraft/integration/crafttweaker/CraftTweakerIntegration.java>



As for your other question, the crafting recipes can be found here:
<https://docs.blamejared.com/en/#Vanilla/Recipes/Crafting/Recipes_Crafting_Table/>

**Comment by BadKaiPanda** [comment]
> That error lies in the uncrafting table mod.
> We use a custom IRecipe implementation to create the recipes, but however mods use them is not up to us.
> 
> Also, the uncraftingTable mod seems to offer a special way of adding recipes that are supposed to be uncraftable:
> https://github.com/crazysnailboy/UncraftingTable/blob/master/src/main/java/org/jglrxavpok/mods/decraft/integration/crafttweaker/CraftTweakerIntegration.java
> 
> As for your other question, the crafting recipes can be found here:
> https://docs.blamejared.com/en/#Vanilla/Recipes/Crafting/Recipes_Crafting_Table/

I am updating my mod to include a recipe for that items but for other items I will try there version of the recipe adder, thanks.

Also thanks for the link they are they same so far but just in case it changes :) thanks, Will close this one and chork it up to mod conflict/implementation :)

**Comment by jaredlll08** [comment]
Nothing we can do about other mods not liking our recipes.

**Comment by jaredlll08** [comment]
To add to this, that mod should be checking for Forge's IShapedRecipe as well.
