### ISSUE TITLE
Potion recipie not working

### ISSUE THREAD

**Issue by FlamingFox5** [CraftTweaker/CraftTweaker#777]
#### Issue Description:
Trying to create a custom brewing recipe for a modded potion. I followed it exactly like how it does on the wiki (minus the < > around the items, that throws an error), and it gives me the error below even though there is a closing parenthesis at the end.

#### What happens:
im thrown the error 
Error parsing nic.zs:1 -- ) expected

#### What you expected to happen:
expected the recipe to work (code looks like it does on the wiki)

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):https://pastebin.com/5jKwNXwr

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2814
- Crafttweaker: 1.12-4.1.17
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 
https://pastebin.com/5jKwNXwr
[pastebin/gist/etc link here]

**Comment by kindlich** [comment]
Okay, first.
The `<>` are there for a reason, don't just remove them that makes it even worse

Second:
Your BHs are incorrect as you need to specify an itemStack not a potion object.
Hold the potion in your hand and use `/ct hand` to get what you need to insert as potion.
