### ISSUE TITLE
Craft tweaker error Help

### ISSUE THREAD

**Issue by ExRush** [CraftTweaker/CraftTweaker#781]
Intro:
I done a script and an error came up

Issue Description:
This error comes up https://pastebin.com/dyLrDc28

What happens:
the recipe doesnt work 

What you expected to happen:
I expected to make a recipe for ender pearls

Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/8SsiLbaG

 crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/GRvtjXnP

____
Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.2
- Forge:forge-14.23.5.2836
- Crafttweaker:CraftTweaker2-1.12-4.1.17

**Comment by kindlich** [comment]
Read how to use item Bracket handlers:
```
<minecraft:iron_ingot>
```

NOT
```
minecraft:iron_ingot
```
