### ISSUE TITLE
NegativeArraySizeException

### ISSUE THREAD

**Issue by Insane96** [CraftTweaker/CraftTweaker#783]
#### Issue Description:
Script gives NegativeArraySizeException for no reasons apparently?
Reported to WirelessUtilities too: https://github.com/SirStendec/WirelessUtilities/issues/12

#### What happens:
Script gives NegativeArraySizeException for no reasons apparently?

#### What you expected to happen:
To give no errors

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://hastebin.com/osuzuhidav.cs
I've reduced the Script to: https://hastebin.com/ehayovujif.cs, This still gives the error

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://hastebin.com/isepotagil.md

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2824
- Crafttweaker: 1.12-4.1.17
- Using a server: No

#### Your most recent log file where the issue was present:
https://hastebin.com/hayijujexe.md

**Comment by kindlich** [comment]
I can't see the script, so I cannot help you...

**Comment by Insane96** [comment]
Shoot. Hastebin pastes expire ...
I'll reopen this if I find the logs again.

**Comment by jaredlll08** [comment]
Just use https://gist.github.com, it is much better than hastebin imo
