### ISSUE TITLE
ArmoreableMobs/CraftTweaker2 error: identifier expected

### ISSUE THREAD

**Issue by ReeCodes** [CraftTweaker/CraftTweaker#785]
#### Issue Description:
When joining a world the following error shows up...

#### What happens:
Getting this InGame error:
[CHAT] ERROR: [crafttweaker | SIDE_CLIENT]: Error parsing customArmor\main_customMobs.zs:7 -- identifier expected

#### What you expected to happen:
That the script would work flawlessly and that I could get info on what to do to fix this error.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
script directory:
scripts\customArmor\["both scripts"]

zenscripts files:

#1 called "_base": 
https://pastebin.com/aQS4HsSc

#2 called "main_customMobs": 
https://pastebin.com/c4qn5LEw

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
crafttweaker.log: https://gist.github.com/ReeCodes/38c549155717a13a4a850ece6745f950

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2815
- Crafttweaker: 4.1.17
- Using a server: No!
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

latest.log: https://gist.github.com/ReeCodes/104772df77f124ea9cb42d8d14b945ab

**Comment by kindlich** [comment]
Check the wiki for the priority preprocessor and make sure that the base file is loaded first.

**Comment by kindlich** [comment]
Are you sure your scripts are the same as the ones you uploaded?
I cannot seem to see an issue at second glance.

**Comment by kindlich** [comment]
Jared just hinted to me that your file name and the import name of yours mismatch:
The log states your file is called `0_base` whereas you stated in this issue that the file is called `_base` and even import `_base`.

Try renaming your file, since an import cannot contain a folder/script whose name starts with a `0`

**Comment by kindlich** [comment]
Is this still an issue?

**Comment by jaredlll08** [comment]
closing due to activity
