### ISSUE TITLE
[Feature Request] More JEI

### ISSUE THREAD

**Issue by JWTHDYTWA** [CraftTweaker/CraftTweaker#786]
What about possibility of making JEI schematics like ExtraUtilities2 do. Something like
`mods.jei.JEI.addSchematic(IItemStack, IBlock[[[]]]);`

**Comment by jaredlll08** [comment]
We have a template.

Also what is a Jei schematic?

**Comment by kindlich** [comment]
I would think he's talking about a ExtUtils2 specific JEI handler.
<https://github.com/rwtema/Extra-Utilities-2-Source/blob/master/1.10.2/src/main/java/com/rwtema/extrautils2/crafting/jei/BlockPatternHandler.java>

Maybe that one?

**Comment by JWTHDYTWA** [comment]
I've found out that it's related to ExtraUtils2, not JEI itself. That's some structure render, demonstrating how to use smth:
![EU2](https://user-images.githubusercontent.com/30724185/57853551-3f667580-7810-11e9-898d-4866d8e7ad01.png)
(It's rotating!)

**Comment by jaredlll08** [comment]
Yea unfortunately I can't add support for something like that.
