### ISSUE TITLE
[Feature Request] Tooltip before modname and Shift tooltip text

### ISSUE THREAD

**Issue by IronPiston** [CraftTweaker/CraftTweaker#788]
**Feature request name**
Shift tooltip functionality and tooltip appending before modname

**Feature request description**
Using item.addShiftTooltip() should have an optional parameter to add shift text, indicating that holding shift will display additional info. 

On a similar note, tooltips should be appended before the modname. 
![ss1](https://user-images.githubusercontent.com/11603684/57965803-7de25a00-790e-11e9-9e84-26772d50c25e.png)

**Feature request reason**
Currently, an item has no indication that it has shift text. Maybe individual words should be recolorable, to emulate how mods like Thermal Expansion display a yellow italic "Shift".
![ss2](https://user-images.githubusercontent.com/11603684/57965804-7fac1d80-790e-11e9-95b2-31c169a5820b.png)

Tooltips appended before the mod name would be consistent with all other items with a native tooltip.

**Feature request dependencies**
Shouldn't have any dependencies.

**Comment by jaredlll08** [comment]
With the way tooltips work, it isn't that easy to add stuff before the mod name unless it is your own item
