### ISSUE TITLE
Recipe book display issue

### ISSUE THREAD

**Issue by WarlordWossman** [CraftTweaker/CraftTweaker#789]
#### Issue Description:
I made a 2x2 shaped crafting recipe which does only work with the vanilla recipe book if you have enough items to craft it at least once in your inventory. If you have less than 4 items in your inventory the recipe book will wrongly display the blueprint of the recipe.

#### What happens:
![ct_bug_1](https://user-images.githubusercontent.com/16925725/58006232-e173af80-7ae7-11e9-8f6b-185419193246.PNG)

#### What you expected to happen:
![ct_bug_2](https://user-images.githubusercontent.com/16925725/58006257-f3555280-7ae7-11e9-97c4-a369b8c47c9f.PNG)
Note: I can get the blueprint to work like the actual recipe with an altered script that uses null entries but that's not a sollution to my problem since it makes crafting this recipe in the player 2x2 grid impossible.
What I expect to happen is if you don't have enough items to craft the recipe it should display the blueprint right instead of putting the netherrack items in the wrong order (first picture).

#### Script used:
https://pastebin.com/u73Jvv8Q
(recipe of interest at line 38)

#### crafttweaker.log file:
https://pastebin.com/Er0UY8R2
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2836
- Crafttweaker: 4.1.17 

#### Your most recent log file where the issue was present: 
https://pastebin.com/RZwRNWhD

**Comment by jaredlll08** [comment]
I can't reproduce this.

I used the same script, but replaced the quark item with a diamond.

With a single piece of netherrack in my inv:
![image](https://user-images.githubusercontent.com/5553605/58026923-e0f30d00-7b17-11e9-9291-62ade40560d2.png)

With no netherrack in my inv:
![image](https://user-images.githubusercontent.com/5553605/58026942-e7818480-7b17-11e9-9d41-d81ab27cb3d2.png)


With 4 netherrack in my inv after clicking the recipe

![image](https://user-images.githubusercontent.com/5553605/58026997-fd8f4500-7b17-11e9-989e-9a14e03ef38e.png)
