### ISSUE TITLE
Can' remove Vanilla recipes

### ISSUE THREAD

**Issue by Reinay97** [CraftTweaker/CraftTweaker#792]
#### Intro:
My English is not that great but i try it. 
I write the comman "/CTGUI craftingtable" to get the gui. Next i put the items for example the diamond swort in it and click remove. The scriot shows that its removed but its still there. Why?

#### Issue Description:

I cant remove the recipe. 

#### What happens:

the script shows the "recipes.removeShaped(<minecraft:diamond_sword>, [[null, <minecraft:diamond>, null],[null, <minecraft:diamond>, null], [null, <minecraft:stick>, null]]);"
but its still there and i cant remove it.

#### What you expected to happen:

to remove the recipe from the game

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge:14.23.5.2838
- Crafttweaker: 1.8.8
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by paulgb434** [comment]
Restart your game

**Comment by jaredlll08** [comment]
As Paul said, restart your game.

You havne't given logs or a proper script, so I can't help you more than that.
