### ISSUE TITLE
CraftTweaker recipe with Item giveBack AE2 Autocraft incompatibility

### ISSUE THREAD

**Issue by Fireztonez** [CraftTweaker/CraftTweaker#793]
Hello,
I have report to AE2 the fact of the autocraft system doesn't work with GiveBack and transformDamage recipe added by Crafttweaker, using item hoe is not pre-register for, and the issue have been closed because of the `slightly hacky` way CraftTweaker does this, so I want to know if this is possible to look that with AE2 dev possibly, question to get a fix for that, because this is really anoying and I'm pretty sure there have a way to get that fixed, without too mutch `major performance issues`, like Yueh say in is reply...

So, heres the issue I have open about that: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4047

After all, AE2 is into a lot of modpacks and Crafttweaker is in most good modpack, having a big issue like that closed without any change bothers me. So I think, question to get this fix, cooperation between AE2 dev and Crafttweaker dev can be good.

Thank's
Fireztonez

**Comment by kindlich** [comment]
Transfered this issue to CraftTweaker since it's not related to the documentation

**Comment by Fireztonez** [comment]
:o yeah my bad, I just see the Crafttweaker Github link goes to Documentations issue tracker...
Sorry for that!

**Comment by jaredlll08** [comment]
What crafttweaker github link? curseforge goes to the right place.

**Comment by Fireztonez** [comment]
@jaredlll08 I click on the GitHub link on the wiki, I just didn't think it will go on a documentation issue tracker. I will know for next time! I always have the crafttweaker wiki open, but the curseforge website I have to open and search for Crafttweaker. But anyways, this is not the subject of this issue!

**Comment by jaredlll08** [comment]
I don't think there is a good way to deal with this in 1.12 as it stands, anything we add now would need to be supported and I just can't offer that support anymore (since I'm moving to 1.14, so no more 1.12 versions)
