### ISSUE TITLE
java.lang.NullPointerException when creating shaped recipe

### ISSUE THREAD

**Issue by jkolbly** [CraftTweaker/CraftTweaker#794]
#### Issue Description:
I tried to create a simple script to add a recipe for lava buckets, but I get an error in chat upon entering the world, and the recipe doesn't work.

#### What happens:
I try to enter the world, and I get the following printed to chat:
`ERROR: [crafttweaker]: Error executing {[0:crafttweaker]: recipes\recipes.zs}: crafttweaker/mc1120/recipes/MCRecipeShaped`
Also, the recipe fails to work in a crafting table.

#### What you expected to happen:
A recipe to be added to the game, where I can surround a bucket with 8 blaze rods to get a lava bucket.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
[https://pastebin.com/KKz41hRb](https://pastebin.com/KKz41hRb)

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
[https://pastebin.com/pp8eGqfS](https://pastebin.com/pp8eGqfS)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- Forge: 14.21.1.2426
- Crafttweaker: 4.1.11
- Using a server: No
- If yes, does the client have the exact same scripts? N/A

#### Your most recent log file where the issue was present: 
[https://pastebin.com/CCiNyF3r](https://pastebin.com/CCiNyF3r)

**Comment by jaredlll08** [comment]
You are in an insanely old version of Forge.
Your crafttweaker is old as well.
We only support 1.12.2, not 1.12, saying that, the latest 1.12.2 version should work on 1.12,so update to that.
