### ISSUE TITLE
Remove all recipes containing a given input

### ISSUE THREAD

**Issue by VariableVixen** [CraftTweaker/CraftTweaker#795]
**Feature request name**
Remove (vanilla) recipes that contain a specific input

**Feature request description**
The ability to remove any vanilla workbench recipe that contains, in the input matrix, a given `IIngredient`. For instance, looping over an array returned by `recipes.getRecipesUsing(IIngredient)` or something similar.

**Feature request reason**
My particular use case _arose_ in that I have an item that can be crafted into three different things [depending on the layout of the shaped input matrix](https://i.imgur.com/w2HgrH0.png), which I am moving into a different mechanic entirely - the Thermal Expansion Centrifugal Separator - where all three outputs are possible with varying weights. I am moving the other specific recipes using it as well, but I would now like to remove recipes that contain this item, regardless of other items or outputs.

**Feature request dependencies**
Requires a new method on the global `recipes` object, either removing recipes that contain the given `IIngredient` as an input or returning all recipes that use it to be looped over. No other mods need be loaded for this to be used.

**Comment by jaredlll08** [comment]
This won't be added, it is very similar to replaceAllOccurance, which is horribly broken and inefficient.
I don't even want replaceAllOccurances to be a thing, so I don't necessarily want to add another very similar thing.
