### ISSUE TITLE
A small Error v 1.12.2

### ISSUE THREAD

**Issue by Arttie** [CraftTweaker/CraftTweaker#802]
#### Intro:
I'm trying to make some coins from one of my mods craftable, and that part i did fine. It's the crafting back from coins that seems to be throwing me errors no matter what I do.

#### What happens:
Load into a world with the full script and I get
https://pastebin.com/zALGEFHK

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue): https://pastebin.com/5aktJRRj

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2836
- Crafttweaker: CraftTweaker2-1.12-4.1.18
- Using a server: Yes
- If yes, does the client have the exact same scripts? Yes

**Comment by kindlich** [comment]
You cannot use an ore dictionary as recipe output.

**Comment by Arttie** [comment]
Thank you.

**Comment by VariableVixen** [comment]
You can use `oreDictEntry.firstItem` to grab whatever the first item is from the dictionary, at least.
