### ISSUE TITLE
recipes.replaceAllOccurences Misspelling

### ISSUE THREAD

**Issue by Kalbintion** [CraftTweaker/CraftTweaker#804]
#### Issue Description:
recipes.replaceAllOccurences contains a common misspelling. the word 'Occurence' is a common misspelling of 'Occurrence' (two r's) - not a major thing, but something I noticed and double checked myself on the spelling before opening this issue.

#### What happens:
recipes.replaceAllOccurrences does not exist

#### What you expected to happen:
recipes.replaceAllOccurrences to exist

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Crafttweaker: 4.1.19

**Comment by jaredlll08** [comment]
Not much we can do about it now, sure we can add the correct spelling, but removing the old one will break scripts.

Also for something that is being removed for 1.14, I don't know if I want to be adding new methods for it.
