### ISSUE TITLE
Railcraft support

### ISSUE THREAD

**Issue by winnetrie83** [CraftTweaker/CraftTweaker#807]
**Feature request name**
Railcraft support
**Feature request description**
I would like to see railcraft support for various machines. So we can add or remove recipes
**Feature request reason**
The reason is simple: Railcraft is a very popular mod and there isn't any support for it. I'm aware there is someone working on railcrafttweaker, but they aren't responding. Looks like it is abandoned.

**Feature request dependencies**
Railcraft api will be required, nothing else

**Comment by jaredlll08** [comment]
1) wrong repo
2) railcraft is still a buggy mess
3) they updated as soon as 1.12 was starting to die, I'm focusing on 1.14 right now, so 1.13 is in bug fixing mode mainly, no more big content.
4) if the other mod exists, and then got abandoned, there is probably a reason for it, that I don't want to have to deal with.
