### ISSUE TITLE
Old versions supported server only

### ISSUE THREAD

**Issue by BadKaiPanda** [CraftTweaker/CraftTweaker#810]
#### Intro:
I have used the older version in the past server only but it seems this version does not, is there a reason for this or is it a bug? 

#### Issue Description:
Install it as part of a vanilla client supported server but this is the only mod that does not let me  connect

#### What happens:
Vanilla clients are not allowed to connect.

#### What you expected to happen:
Load and let vanilla clients connect

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2824-universal
- Crafttweaker: CraftTweaker2-1.12-4.1.19
- Using a server: Yes
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Due to forge changes, Server -> client syncing is no longer a thing.

So the mod is needed on both sides.
