### ISSUE TITLE
Poissible to weight multiple outputs for furnace recipes?

### ISSUE THREAD

**Issue by xkforce** [CraftTweaker/CraftTweaker#813]
I suspect that vanilla furnaces wouldn't be able to do this unless they were replaced/coremodded but I thought I'd see if it's even possible to do this.

**Feature request name**
furnace recipe output weight support

**Feature request description**
Support for output weights like crafting table recipes have.  eg. 50% chance of distilling a speed I potion to a glass bottle and 50% to speed II potion

**Feature request reason**
A vanilla-ish way to distill containers with liquids like potions or alcoholic drinks?

**Feature request dependencies**
Ideally wouldn't need other mods

**Comment by kindlich** [comment]
The Vanilla Furnace is a 1:1 Map, there is no way of having it chance based without rewriting the whole furnace registry or replacing the furnace with something else.

I suggest you look for a mod that allows what you want to do.
If you want to "distill" items in a vanilla-style way, why not use the Brewing stand?

**Comment by jaredlll08** [comment]
As kindlich said, not possible.
