### ISSUE TITLE
Request for setting item at the given index within IPlayer's inventory. 

### ISSUE THREAD

**Issue by friendlyhj** [CraftTweaker/CraftTweaker#814]
**Feature request name**
a ZenMethod to set item in player's inventory and hotbar.

**Feature request description**
`IPlayer.setInventoryStack(item, index)`  and `IPlayer.setHotbarStack(item, index)` to set item at given index within player's inventory/hotbar, like `/replaceitem` command in vanilla.

**Feature request reason**
I want to use a item to consume other items and do something.

**Feature request dependencies**
It's just like a vanilla command, so don't need any other things.

**Comment by jaredlll08** [comment]
unfortunately this won't be a thing in 1.12, it is too late in the 1.12 lifecycle to add something like this, as the next release of the mod for 1.12 I am hoping is the last for 1.12, so I don't want to add new methods that I won't be able to provide support for.
