### ISSUE TITLE
Scripts not removing recipes after adding mods

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#816]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Ok, so i am playing Engimatica 2 Expert. Everything was going ok, and the most notable recipe change was that logs only give 2 planks. So, i played, but when i added some new mods (Armory expansion, Refined Storage), the original crafting table recipes would not be removed. When i would play the game again, it would still show the 1 log = 2 planks recipe, but also the regular 1 log = 4 planks recipe. This was because the original recipe was not removed. When i would try to craft planks, it would give me 4 instead of the regular 2.

#### What happens:
^^^

#### What you expected to happen:
I expected everything to go as normally before, and 1 log = 2 planks, and everything the scripts did, like make the recipes harder.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/vTjqUti8

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

I can't really post it, because pastebin limits the file sizes to 512KB, and mine was 2305 KB.

Another thing that might be important is when i hovered over the script recipes, it would say
"crafttwealer:uninitializedrecipename

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: v2386
- Crafttweaker: 1.12-4.1.17
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Don't change modpacks if you don't know how to fix them.

pastebin isn't the only paste site, gist.gthub.com is another one, and we can't help at all without a log file.

**Comment by ghost** [comment]
Alright, sorry about that. Anyways, i fixed it by replacing the script files with new ones. I think the problem was there was an error in one of the script files, because when i added new mods like armory, it had removed the item. It couldn't find the item which the mod that i added had removed.
