### ISSUE TITLE
CRAFTTWEAKER: Recipe add error: please help!!!

### ISSUE THREAD

**Issue by Babo357** [CraftTweaker/CraftTweaker#817]
Issue Description:
Hi, I'm getting a script error, I looked other Issues a couldn't find answers to mine,
Sorry is this don't belong here or if already responded
I read the wiki about this but still getting this error

https://imgur.com/a/3BVT93n

**What happens:**
[INITIALIZATION][CLIENT][ERROR] Pumkin1.zs:14 > Cannot cast ZenTypeNative: crafttweaker.item.IItemStack to ZenTypeNative: crafttweaker.item.IIngredient[]

**What you expected to happen:**
Craft a new <minecraft:pumkin> recipe

**Script used:**
https://pastebin.com/yf4pUmHF

___
**Affected Versions:**:

- Minecraft: 1.12.2
- Forge: 14.23.4.2739
- Crafttweaker: CraftTweaker2-1.12-4.1.9

**Your most recent log file where the issue was present:** 
https://pastebin.com/UGc8m6V8

**Comment by jaredlll08** [comment]
Your recipe array is wrong, you need [[]], but you have []

**Comment by Babo357** [comment]
Thanks, resolved!!!
