### ISSUE TITLE
[1.14] IRecipeType as a bracket handler, along with all that entails.

### ISSUE THREAD

**Issue by Darkhax** [CraftTweaker/CraftTweaker#818]
With 1.14 I think it would be cool to have a bracket handler for IRecipeType. In 1.14 all recipes (crafting, furnace, moded) share a central registry based on IRecipeTypes, which are namespaced. This would allow for some of the existing recipe functions in CrT such as removeAll to be broadly applied to all recipe systems.

For example, this would allow for people to do `recipes.removeAll(<recipes:darkutils:slime_food>);` or even `<recipes:darkutils:slime_food>.clearAll()`. 

By adding this feature you will be giving users much more control and flexibility over the recipe system. You will also be adding blanket support to remove entries from any recipe registry which make use of the standard vanilla recipe system.

**Comment by jaredlll08** [comment]
Forgot to close this :)
