### ISSUE TITLE
Woot Stygian Anvil support

### ISSUE THREAD

**Issue by kobliznik** [CraftTweaker/CraftTweaker#820]
Hello

**Feature request name**
Stygian Iron Anvil recipe support

**Feature request description**
I would like to edit recipes in Stygian Iron Anvil from Woot, so I want to ask if somebody can make support for this device.

**Feature request reason**
Cause I want be able to edit or completely remove recipes from stygian iron anvil from Woot mod.

**Comment by jaredlll08** [comment]
This wouldn't go on this repo, it would go on the modtweaker repo.
