### ISSUE TITLE
Blast Furnace Issue

### ISSUE THREAD

**Issue by Erwan13430** [CraftTweaker/CraftTweaker#821]
#### Intro:
Hello. After several attempts, I was unable to remove a recipe from the Blast Furnace of the Immersive Engineering mod.

#### Issue Description:
When I modify my script to delete the original recipe for the steel ingot in Blast Furnace, the /ct syntax command does not display any errors while the recipe is not deleted.

#### What happens:
The recipe is not deleted.

#### What you expected to happen:
Steel cannot be made in Blast Furnace.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
Recipe_removed.zs : [https://paste.ubuntu.com/p/SyT9zMyXSr/](url)

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
latest.log : [https://paste.ubuntu.com/p/PXQM9VnhpZ/](url)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Crafttweaker: 1.12-4.1.18
- Using a server: NO
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 
[https://paste.ubuntu.com/p/PXQM9VnhpZ/](url)

**Comment by jaredlll08** [comment]
We don't add immersive engineering support.
