### ISSUE TITLE
Furnace Recipes Not Being Added?

### ISSUE THREAD

**Issue by vizthex123** [CraftTweaker/CraftTweaker#823]
#### CraftTweaker Log: https://pastebin.com/cBeDvyyb

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.28.38
- Crafttweaker: v4.1.19
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

[https://pastebin.com/cBeDvyyb]

**Comment by jaredlll08** [comment]
no idea why I didn't see this  sooner, but I cant produce
