### ISSUE TITLE
Script not producing identical results when used on a server

### ISSUE THREAD

**Issue by DoomRater** [CraftTweaker/CraftTweaker#831]
#### Issue Description:
A script that successfully removed a broken recipe causing axe duplication and replaced it with a working version still produces duplicated axes when used with a server.

#### What happens:
In a single player world, I attempt to craft chopped logs by crafting an axe and some wood together.  I get 8 logs and the axe recieves one point of damage.
I uploaded these scripts to a server also running the same modpack, then attempted to craft some chopped logs.  My inventory fills up with duplicate axes, one for each crafting operation.
(edit: I thought the issue didn't happen with the added axes, but it seems to occur with even the new axes.)

#### What you expected to happen:
The script should work exactly the same on a single player world and on a server. I would expect the recipe on the server to not give back a duplicated axe.

#### Script used:
https://pastebin.com/i6axC5Yn

#### crafttweaker.log file:
https://pastebin.com/pvnUbRt6

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Crafttweaker: CraftTweaker2-1.12-4.1.19
- Using a server: Yes
- If yes, does the client have the exact same scripts? Yes

**Comment by jaredlll08** [comment]
I have never heard of this and I can't reproduce it with vanilla items.

Possibly another mod is causing the actual issue.
