### ISSUE TITLE
Truncated Class File

### ISSUE THREAD

**Issue by corgiblu** [CraftTweaker/CraftTweaker#832]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

scripts give truncated class file error. this issue occurs with 2 of my scripts.

#### What happens:

scripts dont load fully if at all.

#### What you expected to happen:

scripts load without error

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/h4iHc5Ms
https://pastebin.com/pHtUp3DT

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/ksvqAsQb
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2836
- Crafttweaker: 1.12-4.1.19
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://gist.github.com/beanaboston/2683fe424d41807dbb9941aba2fb3087

**Comment by corgiblu** [comment]
looked at other truncated class file errors here on github and comparing my log to theirs and the fix you gave i couldn't figure out what i needed to do to fix it. so i'm hoping you can help.

**Comment by kindlich** [comment]
I'm a little short on time the next few days.
Can you try to find out what line is causting the issue?

Like, try commenting out parts of your script until you have found the smallest script that still produces the error and then send that instead?


From skimming over your script files it should work, you could try adding the `as IItemStack[]` or `as IOreDictEntry[]` to some array declarations, but ZS should be able to infer that (still try to add them to be sure)

**Comment by corgiblu** [comment]
Worked on salad.zs first because it was shorter and adding as IItemStack[] fixed the issue with that script. Now i've gotta find where the issue is in the other one!

**Comment by corgiblu** [comment]
Added as IOreDictEntry[] to the one ore dictionary array (couldn't figure what to do with it, that's why it didn't have it) and that fixed the problem on the other script. Thanks for the help!
