### ISSUE TITLE
Raw resource calculation

### ISSUE THREAD

**Issue by 0xlsca** [CraftTweaker/CraftTweaker#833]
**Feature request name**
Item Material Cost Calculation

**Feature request description**
I'd love to see an ingame command which calculates the cost of an item, meaning that it checks the items needed to craft an item and goes down the road until it reaches "raw" materials that can be specified (for instance iron ingot instead of iron nuggets).

The output would be sent to the player's chat and / or copied to the clipboard.

**Feature request reason**
This is especially useful for modpack authors who wish to compare recipe variations based on the absolute material expenses

**Feature request dependencies**
This would require another command to be implemented as well as a way to specify terminal-resources, which can be done via a config entry.

**Comment by jaredlll08** [comment]
This is out of the scope for this project.
There are a few other mods which already do this as well.
