### ISSUE TITLE
Make more detailed zsdump of GlobalRegistry

### ISSUE THREAD

**Issue by Prunoideae** [CraftTweaker/CraftTweaker#835]
**Feature request name**
Make more detailed zsdump of GlobalRegistry

**Feature request description**
To add augment types of the methods in any class in GlobalRegistry. For example in IFurnaceManager:
Before: "addRecipe": {}
After: "addRecipe": [["IItemStack", "IIngredient", "int"], [["IItemStack", "IIngredient"]]

**Feature request reason**
Generally speaking, this is for making recipe modifications on some low-end computers, as there is not enough memory to run too many processes parallely, and it's easier for modpack makers to check the usage of methods offline, and cut off the possibility to restart minecraft for a several times just because a mistake in augment type.
And for a more private reason, a friend of mine is maintaining an extension of ZenScript, which works like this:
![image](https://user-images.githubusercontent.com/24620047/62347562-b1577c80-b52c-11e9-994a-07bb8b5bf9e5.png)
But it could be much better if the serializer can dump more things about the registries, then it could remind users about the augment they typed when they are coding on this.

**Feature request dependencies**
This feature should not require any dependencies.

**Comment by Prunoideae** [comment]
Fine, I wrote a serializer myself, sorry for disturbing you.

**Comment by jaredlll08** [comment]
🤷‍♂️
I've had absolutely no free time this past week.

You could have also made a PR if you were willing to write code yourself.
