### ISSUE TITLE
CraftTweaker 1.8.9 Port

### ISSUE THREAD

**Issue by jhmaster2000** [CraftTweaker/CraftTweaker#836]
**Feature request name**
CraftTweaker 1.8.9 Port

**Feature request description**
Why is there no 1.8.9 version for CraftTweaker? All the 1.8.9 releases on the CraftTweaker curseforge page are actually just MineTweaker disguised as CraftTweaker.

**Feature request reason**
I need JEI support on 1.8.9 which MineTweaker doesn't have

**Feature request dependencies**
Just Enough Items and 1.8.9 MC version

**Comment by jhmaster2000** [comment]
@jaredlll08 care to at least explain why such a fast denial? :|

**Comment by jaredlll08** [comment]
https://twitter.com/jaredlll08/status/1159228438185689090
