### ISSUE TITLE
Build fails when downloading main repository

### ISSUE THREAD

**Issue by hjae78** [CraftTweaker/CraftTweaker#840]
When downloading the main 1.12 branch as .zip the ZenScript folder is empty and so the build fails. Fixed by going into the ZenScript repository and downloading that as .zip and extracting into the empty folder.

**Comment by jaredlll08** [comment]
You can't download it as a zip because the ZenScript folder is a sub module, so you need to clone with recursive submodules.

Just out of interest, why do you want to build it yourself?

**Comment by hjae78** [comment]
Want to try and implement the extended crafting tables for ctgui, fairly new to this so not very experienced with gradle yet and couldn't figure out how to make it work.

**Comment by kindlich** [comment]
If you want to write an addon for CrT, I recommend you using the maven repository instead.


Though in the case of ExtendedCrafting, doesn't it already have a block to create these table recipes?

**Comment by hjae78** [comment]
It has an item which can create a recipe based on what's inside the table but it's nowhere near as user friendly as ctgui is.
