### ISSUE TITLE
Crash when switching in/out of fullscreen with CT-GUI open

### ISSUE THREAD

**Issue by trpg1** [CraftTweaker/CraftTweaker#843]
#### Issue Description:
When CT-GUI is open if you switch in/out of fullscreen the GUI glitches out and crashes

#### What happens:
The GUI glitches out then, crashes

#### What you expected to happen:
The GUI to work like normal 

#### Script used
No script was used

#### crafttweaker.log file
https://paste.dimdev.org/onequyuwok.md

____
#### Affected Versions (Do *not* use "latest"):
- Minecraft: 1.12.2
- Forge: 14.23.5.2844
- Crafttweaker: 4.1.19
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 
https://paste.dimdev.org/ekixamikak.sql

**Comment by jaredlll08** [comment]
can't reproduce.

Also CTGUI really shouldn't be used, just learn the script language.
