### ISSUE TITLE
Some recipes won't remove

### ISSUE THREAD

**Issue by JohnnyDabb2** [CraftTweaker/CraftTweaker#844]
#### Issue Description:
I created a ZS file with nothing besides the following code...

`recipes.removeAll();`

#### What happens:
It removes only some of the recipes, not all of them.  I noticed very specific things were staying while others weren't.  Vanilla potion-tipped arrows remained, while most vanilla things like wooden planks didn't.  Some mods, like Improved Backpacks, Doggy Talents, and Rustic left recipes in.  There are probably more but I am too lazy to keep clicking through JEI.

#### What you expected to happen:
I expected the code to remove all of the recipes.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
N/A (I already stated the one line of code above)

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

pastebin.com/KV9PBrux

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2846
- Crafttweaker: 4.1.19
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://gist.github.com/JohnnyDabb2/508f4e5a775703fa3ed30e7b7039dc70

<img width="872" alt="picture" src="https://user-images.githubusercontent.com/47069417/64483513-b3f66300-d1b7-11e9-88f2-faaf1a117e13.PNG">

**Comment by jaredlll08** [comment]
As I said on discord. There isn't a fix.
```zenscript
recipes.removeAll()
```
removes everything in the recipe map at post init, here's the code:
https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-MC1120-Main/src/main/java/crafttweaker/mc1120/recipes/MCRecipeManager.java#L762-L764
there is nothing special, just iterate the list and add the names to a list to remove

The vanilla tipped arrow recipes are custom vanilla recipes, very very hacky and annoying, I don't know about the other mods, but there isn't anything I can do about it, like there is no special code I could use to fix it.
