### ISSUE TITLE
I have a crash problem

### ISSUE THREAD

**Issue by RingingAsp98** [CraftTweaker/CraftTweaker#846]
I have a problem when I start the game, it crash instantly and say: 
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: crafttweaker Failed load class: crafttweaker.mc1120.CraftTweaker

How can I resolve this problem?

**Comment by jaredlll08** [comment]
use the template.
