### ISSUE TITLE
I have a crash problem when I start the game.

### ISSUE THREAD

**Issue by RingingAsp98** [CraftTweaker/CraftTweaker#847]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
I have a problem when I start the game, it crash instantly give me an error message.

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): there is no log,

____
#### Affected Versions (Do *not* use "latest"): 

- Minecraft: 1.12.2
- Forge:  forge-14.23.5.284
- Crafttweaker: 4.1.19
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://pastebin.com/zg1Y19rJ

**Comment by jaredlll08** [comment]
Don't download my mod from unofficial sources -_-

(I don't use the naming format that you have in your log file.)
