### ISSUE TITLE
[1.12] java.lang.IncompatibleClassChangeError when using onlyWithTag()

### ISSUE THREAD

**Issue by Insane96** [CraftTweaker/CraftTweaker#850]
#### Issue Description:
Trying to copy NBT from input to output crashes the game when using onlyWithTag in function

#### What happens:
Trying to copy NBT from input to output crashes the game when using onlyWithTag in function

#### What you expected to happen:
To not crash

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/a9AJAZaZ

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/NWp27Rrb

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Crafttweaker: 4.1.19
- Using a server: No

#### Your most recent log file where the issue was present: 
https://pastebin.com/UUL1cSG3

**Comment by kindlich** [comment]
You cannot condition an output.
You need to use `withTag`
