### ISSUE TITLE
[1.12.x] Crafttweaker recipe stops working after looking up recipe in JEI

### ISSUE THREAD

**Issue by Insane96** [CraftTweaker/CraftTweaker#851]
#### What happens:
I have this recipe setup in a script, and it works until I look it up in JEI. Don't know if it's JEI's fault or CT fault, reporting it here too. https://github.com/mezz/JustEnoughItems/issues/1734
This happens on SMP too but the output works, is only invisible.

#### Script Used:
https://pastebin.com/RdFGZLfN

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/Bz80k0jC

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Crafttweaker: 4.1.19
- Using a server: No

#### Your most recent log file where the issue was present: 
https://pastebin.com/zb46VUtP

**Comment by jaredlll08** [comment]
I honestly don't think this is me, it may not even be JEI, could be another mod that is messing things up, but if you look at it like this:

It doesn't happen on other recipes and no one else is reporting it, so I don't even know where to start with even trying to reproduce this let alone fix this.

**Comment by Insane96** [comment]
Hopefully 1.14 "fixes" this

Il Sab 7 Dic 2019, 16:56 Jared <notifications@github.com> ha scritto:

**Comment by jaredlll08** [comment]
I'm sorry but I'm not sure what to say, you gotta take a few things into consideration:

We haven't gotten any other reports about this or people asking about it in the discord

Other recipes are fine.

With all the modpacks using crafttweaker, if there was an actual issue with the mod, I am sure we would have had other reports by now.

I know it isn't a nice answer, but I don't have an answer that can fix it.
