### ISSUE TITLE
Tinkers melting and casting recipes not showing up in game.

### ISSUE THREAD

**Issue by keeper317** [CraftTweaker/CraftTweaker#854]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description: When adding recipes to tinkers only a few additions work correctly.
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/fMjdWWAb
https://pastebin.com/krX6fnuE

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/keeper317/c0f58e8614412403d9cc53ce8f19781b

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- Forge: 14.23.5.2847
- Crafttweaker: 4.1.18
- Tinkers Construct: 2.12.0.135
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Your log is riddled with issues, try fix those first.

Don't steal scripts if you have no idea how to actually write scripts.

**Comment by justinrusso** [comment]
> Don't steal scripts if you have no idea how to actually write scripts.

This.

I do thank you for bringing to my attention the fact that we left some debug logging left in our code in SkyFactory 4 though 👍
