### ISSUE TITLE
Error parsing 00-recipes.zs:162 -- } or ,

### ISSUE THREAD

**Issue by binary404** [CraftTweaker/CraftTweaker#855]
i get a error when ever i load minecraft saying that there is a client side issue in my main script.

script https://pastebin.com/ssC2Fza8

crafttweaker.log https://pastebin.com/sgCr7MWT

version CraftTweaker2-1.12-4.1.19.jar

**Comment by jaredlll08** [comment]
Line 151, you forgot to end the quote on ghast

You can see it much better using gist, since that has Syntax highlighting 

https://gist.github.com/jaredlll08/6d66d01598be420fd913a20994dea7cc

Everything after line 151 is blue, since it is technically all in a string
