### ISSUE TITLE
Adding an alloy recipe.

### ISSUE THREAD

**Issue by mitchngwen** [CraftTweaker/CraftTweaker#861]
I am trying to add a recipe for the alloy furnace from the mod gadgetrycore, I am very new to craftTweaker so I am not sure where to look for the correct mod reference,  below is what I have in my script, when I join my world it tells me something like there is no member gadgetrycore.

import crafttweaker.item.IIngredient;
import crafttweaker.item.IItemStack;
import crafttweaker.oredict.IOreDictEntry;

import mods.gadgetrycore.alloy;

mods.gadgetrycore.alloy.addRecipe([<ore:ingotTin> # 1, <ore:ingotCopper> * 3], [<primal:bronze_ingot> # 4]);

**Comment by jaredlll08** [comment]
1) Use the issue template.
2) I don't add support for gadgetrycore, they do it themselves, so download their mod as well.
3) Seriously, why do you feel the need to remove the issue template?

**Comment by mitchngwen** [comment]
The template did not seem fitting for a simple question. Thank you for the warm welcome. I have downloaded their mod. Are you trying to say go ask for help from their site? Is there an easy way to look up the proper importmods string for the particular mod I am adding? can I find it in the .jar file?

**Comment by jaredlll08** [comment]
That is because discord is the place for questions.
https://discord.blamejared.com

Where are you getting that line from? Like what docs say that is a valid line? (link would be helpful)

**Comment by mitchngwen** [comment]
I did not get the line from anywhere, I assumed that is what it is and it did not work so I thought you could help and I do not like discord.

**Comment by kindlich** [comment]
As far as I know, Gadgetry machines do not have crafttweaker support.

Mods need to add support by themselves or need an addon like ModTweaker to add in support for them.


The reason why we insist on people using the template is that it asks for specific information needed for helping people with issues.
For example, you did not state on what version of MC you are on, if I were to assume you used the latest CrT Beta (1.14) then there would be a greatly different approach to solving an error.

Usually, asking the mod author is the easiest way to learn if they or an addon adds CrT support as they most likely know about these things.

**Comment by mitchngwen** [comment]
Thank you for the help, I will ask the mod author.
