### ISSUE TITLE
Primalcore

### ISSUE THREAD

**Issue by mitchngwen** [CraftTweaker/CraftTweaker#862]
#### Intro:
I need some help

#### Issue Description:
trying to remove the sariras bronze recipe from primalcore

#### What happens:

I get error parsing primal.zs:3 -- ) expected

#### What you expected to happen:

I expected it to remove the bronze recipe

#### Script used:
mods.primal.Smelter.removeRecipe(primal:alloy_bronze);

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): 

[crafttweaker.log](https://github.com/CraftTweaker/CraftTweaker/files/3775099/crafttweaker.log)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Crafttweaker: CraftTweaker2-1.12-4.1.19
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

[latest.log](https://github.com/CraftTweaker/CraftTweaker/files/3775096/latest.log)

**Comment by jaredlll08** [comment]
Read the issue template.

Firstly your script isn't formatted -_- how am I meant to know if you have:

```
<item>

Or

item
```

And I'm not downloading some random log files. Upload to gist or pastebin.

**Comment by mitchngwen** [comment]
https://pastebin.com/ZcqeCTQ6

And the log is too big to upload to pastebin without pro

I am going off these instruction:
https://github.com/An-Sar/PrimalCore/wiki/CraftTweaker:-Hibachi

I also asked them for help 16 hours ago with no response, I was hoping you could help

**Comment by mitchngwen** [comment]
What do you mean by it is not formatted?

**Comment by jaredlll08** [comment]
Just upload your script to pastebin or gist.

**Comment by mitchngwen** [comment]
After walking away from it for a few hours I have figured it out it was a very simple mistake.  this is the correct way to do it:
mods.primal.Smelter.removeRecipe("primal:alloy_bronze");
