### ISSUE TITLE
removal not working

### ISSUE THREAD

**Issue by mitchngwen** [CraftTweaker/CraftTweaker#866]
#### Issue Description:
Script not working as intended

#### What happens:
The kitsu's forgecraft crucible bronze ingot recipe does not get removed, I do not get any errors though.

#### What you expected to happen:
Remove recipe for for kitsu's forgecraft crucible recipe bronze.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue)
https://pastebin.com/ieZFnF6Y

`mods.forgecraft.NBTCrucible.removeRecipe("bronze");`

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/k36cSpwT
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2847
- Crafttweaker: 4.1.19
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 
Latest log file too big for pastebin. Weak

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
I don't even know what kitsu's Forgecraft is. Report to them
