### ISSUE TITLE
CTGUI

### ISSUE THREAD

**Issue by Notlucky101** [CraftTweaker/CraftTweaker#868]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:

I bring Up the CTGUI and I cannot click on the ore dictionary.
In fact nothing on the left side is clickable.
However though the right side buttons do work, they do show that they we click.

#### What you expected to happen:

I would expect to see a check mark on the checkbox

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
recipes.removeShaped(<minecraft:hopper>, [[<enderio:item_alloy_ingot:9>, <minecraft:log>, <enderio:item_alloy_ingot:9>],[<enderio:item_alloy_ingot:9>, <minecraft:log>, <enderio:item_alloy_ingot:9>], [null, <enderio:item_alloy_ingot:9>, null]]);
recipes.removeShaped(<minecraft:hopper>, [[<minecraft:iron_ingot>, <minecraft:log>, <minecraft:iron_ingot>],[<minecraft:iron_ingot>, <minecraft:log>, <minecraft:iron_ingot>], [null, <minecraft:iron_ingot>, null]]);
recipes.removeShaped(<minecraft:hopper>, [[<minecraft:iron_ingot>, null, <minecraft:iron_ingot>],[<minecraft:iron_ingot>, <minecraft:chest>, <minecraft:iron_ingot>], [null, <minecraft:iron_ingot>, null]]);
//Don't touch me!
//#Add
recipes.addShaped(<minecraft:hopper>, [[<minecraft:stone>, <tconstruct:wooden_hopper>, <minecraft:stone>],[<minecraft:stone>, <thermalfoundation:material:24>, <minecraft:stone>], [null, <minecraft:stone>, null]]);
//File End

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
[PREINITIALIZATION][CLIENT][INFO] Current loaders after merging: [[preinit]]
[PREINITIALIZATION][CLIENT][INFO] Loading scripts for loader with names [preinit]
[PREINITIALIZATION][CLIENT][INFO] [preinit | SIDE_CLIENT]: Skipping file {[0:crafttweaker]: recipes.zs} as we are currently loading with a different loader
[PREINITIALIZATION][CLIENT][INFO] Completed script loading in: 3ms
[PREINITIALIZATION][CLIENT][INFO] Current loaders after merging: [[preinit], [alchemistry]]
[PREINITIALIZATION][CLIENT][INFO] Loading scripts for loader with names [alchemistry]
[PREINITIALIZATION][CLIENT][INFO] [alchemistry | SIDE_CLIENT]: Skipping file {[0:crafttweaker]: recipes.zs} as we are currently loading with a different loader
[PREINITIALIZATION][CLIENT][INFO] Completed script loading in: 0ms
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Building registry
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Successfully built item registry
[INITIALIZATION][CLIENT][INFO] Current loaders after merging: [[preinit], [alchemistry], [recipeevent | crafttweaker]]
[INITIALIZATION][CLIENT][INFO] Loading scripts for loader with names [crafttweaker | recipeevent]
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: recipes.zs}
[INITIALIZATION][CLIENT][INFO] Completed script loading in: 456ms
[POSTINITIALIZATION][CLIENT][INFO] Removing recipes for various outputs
[POSTINITIALIZATION][CLIENT][INFO] Removing Shaped recipes for <minecraft:hopper>
[POSTINITIALIZATION][CLIENT][INFO] 1 removed
[POSTINITIALIZATION][CLIENT][INFO] Removing Shaped recipes for <minecraft:hopper>
[POSTINITIALIZATION][CLIENT][INFO] 1 removed
[POSTINITIALIZATION][CLIENT][INFO] Removing Shaped recipes for <minecraft:hopper>
[POSTINITIALIZATION][CLIENT][INFO] 1 removed
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Hopper with name ct_shaped-1889985875
[POSTINITIALIZATION][CLIENT][INFO] Applying MrCrayfish's Furniture Mod changes...
[AVAILABLE][CLIENT][INFO] Fixed the RecipeBook

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.2
- Forge:14.23.5.2847
- Crafttweaker: 1.12-4.1.19
- Using a server: 
![2019-11-05_15 24 04](https://user-images.githubusercontent.com/42447191/68256087-eb309700-ffe3-11e9-861a-1e5f467e791d.png)

- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Right click on the slot you want to edit.

Also seriously don't upload your logs directory to github, read the template -_-
