### ISSUE TITLE
Ore dict?

### ISSUE THREAD

**Issue by Notlucky101** [CraftTweaker/CraftTweaker#871]
I am not sure if this a really a bug, but I cannot get right of the top recipe or the bottom recipe.
I did select the ingot and check the oredict but seem either I am doing something wrong or it is bug.
![2019-11-06_01 39 57](https://user-images.githubusercontent.com/42447191/68287099-08428580-0037-11ea-9897-1c7bfd8e5e2a.png)
the second on from the bottom is my own recipe.

**Comment by Notlucky101** [comment]
correction (I cannot get rid instead of I cannot get right)

**Comment by jaredlll08** [comment]
follow the template. I can't help you if you don't give me any of the information I need to help -_-
