### ISSUE TITLE
CraftTweaker-1.14.4-5.0.1.132.jar crashes servers.

### ISSUE THREAD

**Issue by gravysamich** [CraftTweaker/CraftTweaker#874]
title says it all. tried to use craft tweaker on my server, but it just doesn't work. tried making a new server and only installing craft tweaker but it still crashed so i am sure it is this mod.

https://pastebin.com/PXVM6FMk paste bin of the crash log.

**Comment by jaredlll08** [comment]
Thanks!
Fixed in https://github.com/CraftTweaker/CraftTweaker/commit/614a24757df3c4e9d4171829acfeda7f1af389d4
