### ISSUE TITLE
Code Not Working!

### ISSUE THREAD

**Issue by iBliz** [CraftTweaker/CraftTweaker#875]
Issue Description:
I tried making a furnace smelting recipe and some cauldron fill & fluid recipes using the Inspirations mod but none of them have worked. I am a big noob at this though so sorry if I make any silly or dumb mistakes with my code.

What happens:
I write out the code in a .zs file, launch Minecraft, go into my world, and try to put magma blocks into a furnace fuel area. I had designed the magma blocks to act as fuel for 200 ticks. In the furnace code, I also had written that if you smelted stone you could get magma and it also didn't work. I had also tried my cauldron code(s) but that code also didn't do what it was intended to. I wrote a code to produce flint when I dip gravel in a cauldron filled with water. I also did the same with mycellium, dirt, and sludge (Industrial Foregoing) and I wrote another command to turn magma into lava on contact with a cauldron.

What you expected to happen:
For the furnace code, I expected the magma block to act as fuel and the stone would smelt into magma. For the cauldron code I expected the gravel to turn into flint, the dirt to turn into mycellium, and the magma to turn into lava.

Script used:

Cauldron Recipes: https://pastebin.com/50Rxp9a9

Furnace Recipes: https://pastebin.com/LyykmsHM

crafttweaker.log file:
https://pastebin.com/UeCtL0UV

Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Crafttweaker: CraftTweaker2-1.12-4.1.19
- Using a server: No
- If yes, does the client have the exact same scripts?

Your most recent log file where the issue was present: 

https://pastebin.com/5Bb2P9qy

**Comment by jaredlll08** [comment]
nothing is calling those `init()` functions.

not sure why you even have `init()` functions, you could just have the lines inside them and the code will run.

I suggest you take a look here:
https://docs.blamejared.com/1.12/en/#Getting_Started/

**Comment by justinrusso** [comment]
Are the `init` functions being called?

I use this method often, and you can see we have a `postInit.zs` file that more than often is the source that calls all of these init functions. https://github.com/DarkPacks/SevTech-Ages/blob/master/src/scripts/crafttweaker/postInit.zs#L50
