### ISSUE TITLE
Automatically Generated Recipe Names

### ISSUE THREAD

**Issue by NielsPilgaard** [CraftTweaker/CraftTweaker#876]
**Feature request name**
Automatically Generated Recipe Names

**Feature request description**
As we spoke about on Discord, the feature would be an additional recipe function:
`What I would maybe offer is a "craftingTable.generateName(prefix, suffix, inputs, outputs)"`

**Feature request reason**
It would help ease new devs into CrT, and hopefully stop me from making silly mistakes in the future.

**Feature request dependencies**
Nope.

**Comment by jaredlll08** [comment]
It's taken a while but we have discussed it, adding a method like that would bring it's own issues that would need to be accounted for.

Also there isn't much demand for it, people are fine with setting the recipe names themselves.

**Comment by NielsPilgaard** [comment]
Alright 👍
