### ISSUE TITLE
[1.14.4] Recipe Type for Create not found

### ISSUE THREAD

**Issue by oitsjustjose** [CraftTweaker/CraftTweaker#878]
#### Issue Description:
Creating a Crushing (and other) recipe for Create via CraftTweaker's new `.addJSONRecipe` function does not work. This could be a result of a bad implementation of JSON recipes on Create's side, or an issue with CraftTweaker, although since my datapack version of this JSON recipe worked, my best guess is that it might be CT?

#### What happens:
In trying to create a custom JSON recipe for [Create](https://www.curseforge.com/minecraft/mc-mods/create), the error `Could not get RecipeType with name: <recipetype:create:crushing>! RecipeType does not appear to exist!` occurs. In testing with other mods and using JSON-based recipes in CraftTweaker, I do not have this issue.

#### What you expected to happen:
The JSON recipe to work via `<recipetype:create:crushing>$addJSONRecipe`.

#### Script Used

[Here are two scripts](https://gist.github.com/oitsjustjose/d12516f1d534c0aa63832485ca3860ab), named `not working.zs` and `working.zs`. As you may expect, these scripts are ones that don't and do work, respectively. As you can see, Silent's Mechanisms recipes work fine, but for some reason Create's do not (the recipe type isn't even acknowledged as correct).

#### [crafttweaker.log](https://pastebin.com/rCmBKmME)

____
#### Affected Versions

- Minecraft: 1.14.4
- Forge: 28.1.81
- Crafttweaker: 5.0.1.133
- Using a server: No
- [ModList](https://gist.github.com/oitsjustjose/1c3c4ef1aabdc323632abf761554c1b3)

#### [Most recent log file](https://gist.githubusercontent.com/oitsjustjose/e6de14162f21a91891a8fe3076f97034/raw/73070df8f3a7be855a026a491eff61a4e7572227/latest.log)

**Comment by jaredlll08** [comment]
Create registers their recipe types as "minecraft:crushing" instead of "create:crushing"

**Comment by oitsjustjose** [comment]
What an odd way to do that :thinking:, especially since the recipe type in the datapack `JSON` is `create:crushing`. 

Thanks for the help! I'll go put in a ticket for Simibubi to look into using the `minecraft` namespace.

**Comment by jaredlll08** [comment]
No idea why the datapack one works, but no where here do they use their modid:
https://github.com/Creators-of-Create/Create/blob/master/src/main/java/com/simibubi/create/AllRecipes.java#L29-L41
