### ISSUE TITLE
NBTTagString cannot be cast to NBTTagCompound

### ISSUE THREAD

**Issue by drago87** [CraftTweaker/CraftTweaker#881]
I'm trying to hide all the liquid buckets from the mod PrimalCore

the buckets uses nbt data and ii'm trying to iterate to remove all of them exept the empty bucket

```
val stringArray = [
    "water",
    "lava",
] as string[];

for fluid in stringArray {
mods.jei.JEI.hide(<primal:bucket_clay>.withTag({Fluid: {FluidName: fluid, Amount: 1000}}));
mods.jei.JEI.hide(<primal:bucket_terra>.withTag({Fluid: {FluidName: fluid, Amount: 1000}}));
mods.jei.JEI.hide(<primal:bucket_cinis>.withTag({Fluid: {FluidName: fluid, Amount: 1000}}));
}
```
i'm getting this error
ERROR: [crafttweaker]: Error executing {[0:crafttweaker]: JEIHide.zs}: net.minecraft.nbt.NBTTagString cannot be cast to net.minecraft.nbt.NBTTagCompound

Is there a right way to do it?

**Comment by jaredlll08** [comment]
Follow the issue template, I need literally all the info you decided to leave out -_-

**Comment by drago87** [comment]
Apperently now it works....
