### ISSUE TITLE
[1.14.4] RecipeType natural-progression:damage_tools not found

### ISSUE THREAD

**Issue by oitsjustjose** [CraftTweaker/CraftTweaker#882]
#### Intro:
Heya! Similar issue to #878, but this time with a mod I've written so if it's something idiotic I've done, I'm going to fix it. 

I just wrote up (yesterday) a custom recipe type that is almost identical to `ShapelessRecipe`, but instead of deleting damageable items, it damages them and leaves them in place.

I wanted to integrate this into my modpack to make recipes harder using CT, but I came across the same issue as in #878 -- except I *know* I'm using my (`natural-progression`) namespace.

[Here's how I register the recipe type](https://github.com/oitsjustjose/Natural-Progression/blob/27566db9ba68bced0f85c10972ba4798f6f0c9f7/src/main/java/com/oitsjustjose/naturalprogression/NaturalProgression.java#L135-L140), and [here's how it's written](https://github.com/oitsjustjose/Natural-Progression/blob/master/src/main/java/com/oitsjustjose/naturalprogression/common/recipes/DamageItemRecipe.java).

#### Issue Description:
`<recipetype:natural-progression:damage_tools>.addJSONRecipe(...)` does not work as intended, when the recipe type is confirmed to work and works fine as a datapack.

#### What happens:

The error "Could not get RecipeType with name: <recipetype:natural-progression:damage_tools>! RecipeType does not appear to exist!" is thrown when that exact recipe type works [as a JSON](https://gist.github.com/oitsjustjose/c6958da1c8f533d88b1e9ad7f0267000) in a datapack.

#### What you expected to happen:

CraftTweaker to accept this recipe type as valid, thus allowing the recipe to work.

#### [`crafttweaker.log`](https://gist.github.com/oitsjustjose/e1634705b0afb7b8b3879423ebd954d6)

____
#### Affected Versions

- Minecraft: 1.14.4
- Forge: 28.1.90
- Crafttweaker: 5.0.1.133
- Using a server: No

#### Your most recent log file where the issue was present: 

[`latest.log`](https://gist.github.com/oitsjustjose/5a27cf25a8285a166a49266bccd85608)

**Comment by jaredlll08** [comment]
Keep in mind, RecipeSerializers are different from IRecipeType (which is what the bracket handler uses), So for you, you could use the shapeless crafting type, or you could make your own recipe type (but I don't know if that would still work in the crafting grid).

For making your own IRecipeType:
https://github.com/CraftTweaker/CraftTweaker/blob/a91346485af8b04e13c56424e72e8121aaed1ac4/src/main/java/com/blamejared/crafttweaker/impl/script/ScriptRecipe.java#L56

https://github.com/CraftTweaker/CraftTweaker/blob/00db92a516db7e46b6b7042873c55d39f413a6cb/src/main/java/com/blamejared/crafttweaker/CraftTweaker.java#L101
