### ISSUE TITLE
[1.12.2] Game freezes while finishing up CraftTweaker.

### ISSUE THREAD

**Issue by JoeJoeTV** [CraftTweaker/CraftTweaker#885]
#### What happens:
Sometimes(not every time), when loading the game, it freezes on "Loading - Finishing up" "LoadComplete - Crafttweaker2" and then then window will become "Not Responding".

#### What you expected to happen:
The game loads normally.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/deVaN4fW

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/31z3H9iM

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2874
- Crafttweaker: 1.12-4.1.19
- Using a server: No
- If yes, does the client have the exact same scripts?

-Modpack Mod List(I am the Modpack Author): https://pastebin.com/Xn7PgDzn

#### Your most recent log file where the issue was present: 

https://gist.github.com/JoeJoeTV/3d5c45697d7885741c7529bf7ba94613 (Had to use gist, because file was too large.

**Comment by jaredlll08** [comment]
I have never been able to reproduce this, it is possible it will be fixed in the next version of CraftTweaker when using FastWorkBench, but I can't offer anything of value right now.

**Comment by JoeJoeTV** [comment]
Thanks for replying so fast. Was this bug reported before? and will it help if I install FastWorkBench now or only with the next upcoming CraftTweaker Version?

**Comment by jaredlll08** [comment]
related to:
https://github.com/CraftTweaker/CraftTweaker/issues/829
adding `#disable_search_tree` to your script may fix the issue.
