### ISSUE TITLE
oreDict size check

### ISSUE THREAD

**Issue by drago87** [CraftTweaker/CraftTweaker#887]
is there a way to check if a oredict is emty or contains something?
Example
```
val test = oreDict[ingotIron];

if test.size >= 1 
{
     Do stuff...
}
```

**Comment by kindlich** [comment]
Actually, that's a lot easier:
```
test.empty
```

Returns `true` if the ODE is empty, and `false` if it is not.

It can be found in the corresponding wiki page:
<https://docs.blamejared.com/1.12//en/#Vanilla/OreDict/IOreDictEntry/#zengetters>
