### ISSUE TITLE
[1.12.2] JEI integration: mods.jei.JEI.addItem only adding some items.

### ISSUE THREAD

**Issue by UvMidnight** [CraftTweaker/CraftTweaker#889]
Description:
In the JEI support for crafttweaker, mods.jei.JEI.addItem will not result in an item being added to jei if it does not have an unique display name that is not a subsection of another display name. Not entirely sure if it is on your side or JEI.

What happens:
Using the built in jei support through mods.jei.JEI.addItem with an item that does not have an unique display name that is not a subsection of another display name result in the item not being added to JEI.

What you expected to happen:
All items get added to JEI, regardless of the tag data.

Script used:
https://pastebin.com/kr1xeVBY

crafttweaker.log:
https://pastebin.com/gRS5G22w

Affected Versions:
Minecraft 1.12.2
Forge 14.23.5.2847
Crafttweaker 1.12-4.1.19
JEI version: 1.12.2-4.15.0.291
Using a server: No

Created with minimal modlist, replicated with only JEI and crafttweaker.

Latest log:
https://gist.github.com/UvMidnight/5e57206c4edbe90fc62f09f025ae17d0

**Comment by jaredlll08** [comment]
On Jei side, we just pass the item to JEI, so not sure how this could be us
