### ISSUE TITLE
A recipe is not rendering on server

### ISSUE THREAD

**Issue by Halfdeaf** [CraftTweaker/CraftTweaker#891]
#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):https://gist.github.com/Halfdeaf/162ed1679103ff0ec8dfc2a5eca87ea6

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.14
- Forge: 28.1.93
- Crafttweaker: 5.0.1.140
- Using a server: yes
- If yes, does the client have the exact same scripts? yes

#### Your most recent log file where the issue was present: 

https://gist.github.com/Halfdeaf/cbf1060d0301501b9e862182b71916ac

**Comment by jaredlll08** [comment]
I'm going to need the client log as well please

**Comment by jaredlll08** [comment]
so I setup the scripts on a local server:

Hopper renders fine
![image](https://user-images.githubusercontent.com/5553605/70355943-f6ddda80-187b-11ea-8eae-71b0c1701fa7.png)
same with chests
![image](https://user-images.githubusercontent.com/5553605/70356080-42908400-187c-11ea-91d8-59c878291d77.png)


only thing that is weird is the sticks, but I think that is a different issue
![image](https://user-images.githubusercontent.com/5553605/70356114-53d99080-187c-11ea-919d-f238c3f1540a.png)

**Comment by jaredlll08** [comment]
Talked on discord, issue isn't with our mod.
