### ISSUE TITLE
Thermal Foundation shapeless recipe remove not working

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#895]
I tried to remove the shapeless crafting for Platinum Ingot but when i start the game the recipe is not removed. 

Here is the code: 
`recipes.removeShapeless(<thermalfoundation:material:134>, [<thermalfoundation:ore:6>] [<thermalfoundation:material:1024>]);`

**Comment by jaredlll08** [comment]
Follow the issue template. We need more details like the log.

**Comment by ghost** [comment]
Sorry it's my bad! I made a mistake in the Ingreditent[] syntax.

This is the correct:
`recipes.removeShapeless(<thermalfoundation:material:134>, [<thermalfoundation:ore:6>, <thermalfoundation:material:1024>]);
`

**Comment by jaredlll08** [comment]
No worries, just please close the issues (and post your solution for others!) if you solve it yourself :)
