### ISSUE TITLE
Thermal Foundation Platinum Ore smelting recipe

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#897]
#### Issue Description:
I tried to delete the smelting recipe of the Platinum Ore. The recipe is removed but i got error message.

#### What happens:
The code is successfully remove the recipe but i got this error.
`[AVAILABLE][CLIENT][ERROR] No Furnace recipe exists for: 1xtile.thermalfoundation.ore@6`

#### What you expected to happen: 
If the recipe is removed why i got error?

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): [crafttweaker.log](https://pastebin.com/iFjJ8TKb)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: **1.12.2**
- Forge: **forge-14.23.5.2847**
- Crafttweaker: **CraftTweaker2-1.12-4.1.20**
- Using a server: **no**
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present:

[latest.log](https://pastebin.com/UmRRMnJh)

**Comment by jaredlll08** [comment]
I need the full scripts, not a single line.

Keep in mind that if you remove a recipe from the vanilla furnace, it is also removed from the TE furnace, so there is no need to remove them twice.

also these are actually issues with modtweaker, I have no idea why they aren't working.

Please stop creating a ton of issues for what is obviously a specific thing (thermal expansion stuff not working)

**Comment by ghost** [comment]
> Keep in mind that if you remove a recipe from the vanilla furnace, it is also removed from the TE furnace, so there is no need to remove them twice.

That was the issue. Solved, thanks! Sorry again for the issues ><"
