### ISSUE TITLE
Thermal Foundation Induction Smelter Sand + Tool/Armor/Horse Armor recipes

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#898]
#### Issue Description:
I tried to remove some tool/armor/horse armor recipes from the Induction Smelter.

#### What happens:
I got errors and the recipes won't delete.

#### What you expected to happen:
Delete the recipes.

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): [crafttweaker.log](https://pastebin.com/14zam3J3)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: **1.12.2**
- Forge: **forge-14.23.5.2847**
- Crafttweaker: **CraftTweaker2-1.12-4.1.20**
- Using a server: **no**
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

[latest.log](https://pastebin.com/JxWMVUXK)

**Comment by jaredlll08** [comment]
The errors are saying that the recipes don't exist in the first place, so you can't remove something that doesn't exist. 

Your inputs are probably wrong / in the wrong order

**Comment by ghost** [comment]
But this is the recipe: https://imgur.com/D8nVq4g Sand + Tool (Sand accepts anySand)

**Comment by jaredlll08** [comment]
so these are actually issues with modtweaker, I have no idea why they aren't working.

Please stop creating a ton of issues for what is obviously a specific thing (thermal expansion stuff not working)

**Comment by ghost** [comment]
Sorry about that! Then, can i create an issue to your modtweaker repo? or its not needed?
