### ISSUE TITLE
Common_setup error, no log creation

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [CraftTweaker/CraftTweaker#899]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:
While loading a fresh instance of 1.14.4, Crafttweaker gives an error screen that generates no log. It mentions an error during the common_setup event phase. 

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): https://gist.github.com/ZephyrWindSpirit/a09b9f307b238081032117d39e198800

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.14.4
- Forge: 28.1.106
- Crafttweaker: 5.0.1.150
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://gist.github.com/ZephyrWindSpirit/fd2fe9b2ba6dbf3277c07feef998ce83

**Comment by jaredlll08** [comment]
This is a long shot, but are you able to test this not on a mac?

or do you have anything in place that would stop a file being made?

**Comment by jaredlll08** [comment]
Closing because no feedback.

(also I have been informed that this may have to do with how you are running minecraft, I have no more info besides that)
