### ISSUE TITLE
Nested Tags support

### ISSUE THREAD

**Issue by Partonetrain** [CraftTweaker/CraftTweaker#900]
**Feature request name**
Nested Tags Support 

**Feature request description**
Support for nested tags, such as such as <tag:forge:sand/red>

**Feature request reason**
Many mods, and Forge, use nested tags when there are multiple groups of items. For instance, forge has tags for all ingots, and all ingots of a certain type:

- forge:ingots
- forge:ingots/iron
- forge:ingots/gold
- forge:ingots/copper

and so on.

**Feature request dependencies**
None, as far as I can tell

**Comment by jaredlll08** [comment]
This already works...?

```zenscript
<tag:forge:ingots>
<tag:forge:ingots/iron>
<tag:forge:ingots/gold>
<tag:forge:ingots/copper>
```
I haven't tested this myself, but I know that someone has added a new tag under the forge group

**Comment by Partonetrain** [comment]
My apologies, this is a different issue I improperly assumed wasn't working because of nested tags. I will be updating this issue

**Comment by Partonetrain** [comment]
I was trying to add a tag to a tag (i.e) `<tag:forge:beacon_payment>.addItems([<tag:forge:gems>]);`
as vanilla can do something similar

```
{
  "replace": false,
  "values": [
    "#forge:gems"
  ]
}
```

but on second thought I can iterate all items with that tag like so:

```
for item in <tag:forge:gems>.items {
   <tag:forge:beacon_payment>.addItems(item);
}
```

Sorry for the trouble.
