### ISSUE TITLE
Thaumcraft dump command not working

### ISSUE THREAD

**Issue by drago87** [CraftTweaker/CraftTweaker#901]
#### Issue Description:
Using /crafttweaker thaumcraftDump or /ct thaumcraftDump

#### What happens:
No such command! [Click to show help]

#### What you expected to happen:
Dumps all the Thaumcraft information to the crafttweaker.log file.

#### Script

https://pastebin.com/ZR4t6PWV

#### crafttweaker.log
https://pastebin.com/8Gc5YFS0

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Crafttweaker: 1.12-4.1.20
- Thaumcraft: 1.12.2-6.1.BETA26

#### Your most recent log file where the issue was present: 

log file to big to do a pastebin (2812kb pastebin take a max of 512kb)
if you realy need it i can try to split it up

**Comment by jaredlll08** [comment]
We don't add support for thaumcraft.

you need modtweaker.

As for:
```
log file to big to do a pastebin (2812kb pastebin take a max of 512kb)
if you realy need it i can try to split it up
```
Use gist.github.com in the future
