### ISSUE TITLE
New crafting table recipes don't show in JEI

### ISSUE THREAD

**Issue by Blatts12** [CraftTweaker/CraftTweaker#902]
#### Intro:
I want to change/create some recipes for my personal modpack.
btw: i see typo in kiln... -.-

#### Issue Description:
So, i'm changing some recipes, they are in the game but don't show in JEI
https://imgur.com/a/0TIwJum <-- no recipe in JEI
https://imgur.com/a/4AzFxxV <-- working recipe

#### What happens:
Recipes don't show in JEI.
First script lines: 25, 30, 35

#### What you expected to happen:
Recipes are shown in JEI.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://gist.github.com/Blatts12/eb16fc51a81366da1de768bb41a29437
https://gist.github.com/Blatts12/4e5c11ebf1aff7063bf92c48ce0d3ed5

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/aFNBcuZt

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Crafttweaker: 4.1.20
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://gist.github.com/Blatts12/0c20d46bd96ceb52a041808657e340e2

**Comment by jaredlll08** [comment]
Do the recipes for the furnace show? or it is just the recipes for the atum kiln / bricks that aren't showing?

**Comment by Blatts12** [comment]
Furnace isn't shown neither

**Comment by jaredlll08** [comment]
I'm going to have to say that this is another mod.


in your log you have a bunch of errors from JEI not related my CraftTweaker:
https://gist.github.com/Blatts12/0c20d46bd96ceb52a041808657e340e2#file-latest-log-L5236

Try removing that mod and see if it still happens?

(I should say, this late in 1.12, I highly doubt that this is an issue with my mod, I would have had reports about it before, so it is most likely another mod messing with things)

**Comment by Blatts12** [comment]
Okay, I found the culprit [IGCM](https://www.curseforge.com/minecraft/mc-mods/ingameconfigmanager)

**Comment by Blatts12** [comment]
https://github.com/CreativeMD/IGCM/issues/55
