### ISSUE TITLE
[1.14.4] Error running tag scripts

### ISSUE THREAD

**Issue by WenXin20** [CraftTweaker/CraftTweaker#903]
#### Issue Description:
When trying to add a block to the tag small_flowers, I get an error that says line 3 is missing a semicolon, even though one is there.
I may also be missing something from the file that I'm unaware of. I tried to used the github example that was provided, but no luck so far.

#### What happens:
- Logging into a world produces an error with the provided script.

#### What you expected to happen:
- It should instead register the block under the tag small_flowers

#### Script used:
- [Gist](https://gist.github.com/WenXin20/924122acf63ea70444344bd6ff30f55c)

#### crafttweaker.log file::
- [Gist](https://gist.github.com/WenXin20/a98cb25ca858138a3ddbf84564d389e9)

____
#### Affected Versions:

- `Minecraft: v1.14.4`
- `Forge: v28.1.107`
- `Crafttweaker: v5.0.1.150`
- Using a server: No

#### Your most recent log file where the issue was present: 

[Full Log](https://gist.github.com/WenXin20/d11aea8d54d60bc0453e9f5af4985efe)
Error starts at `[19:51:33]`

**Comment by jaredlll08** [comment]
There is no
```zenscript
<block:modid:name>
```
bracket handler, you should be using the blockstate bracket handler
```zenscript
<blockstate:modid:name>
```

**Comment by WenXin20** [comment]
If that's the case, then the example at the link below is incorrect. The top few example lines says to use `<block:modid:name>`

https://github.com/CraftTweaker/CraftTweaker-Examples/blob/master/1.14/tags.zs

**Comment by jaredlll08** [comment]
Ah that, so the comment at the top  was more so me planning on how it will be implemented, and as a little snippet to send to others to get their thoughts, it was made before I had even implemented blocks/states

If you look at the very last line however, 
https://github.com/CraftTweaker/CraftTweaker-Examples/blob/master/1.14/tags.zs#L34
I do use the `<blockstate:` bracket.

Sorry for the confusion, we are working on the docs, just a lot to do in the mod itself to not much time :(

**Comment by WenXin20** [comment]
Ah, it's no problem! Thanks!
