### ISSUE TITLE
furnace.removeAll(); doesn't work

### ISSUE THREAD

**Issue by IchHabeHunger54** [CraftTweaker/CraftTweaker#904]
#### Intro:
furnace.removeAll(); doesn't do anything.
#### Issue Description:
furnace.removeAll(); doesn't remove any recipes. crafttweaker.log doesn't say anything about it. Also, adding furnace recipes doesn't work properly, though I don't know if these issues are related or not.
#### What happens:
No removal of furnace recipes; no adding of furnace recipes; no message in the crafttweaker.log file.
#### What you expected to happen:
The old furnace recipes getting removed, the new ones getting added, proper output in the crafttweaker.log file.
#### Versions:
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Crafttweaker: 4.1.19
- Using a server: No

**Comment by kindlich** [comment]
Without the CrT log and your script file we can't do anything.

Also, did you make sure your script file is a `.zs` file and not a `.zs.txt` file?

**Comment by IchHabeHunger54** [comment]
Yes, the file is only zs.
Here is the script: https://pastebin.com/2mSEXDUv
Here is the log: https://pastebin.com/vR0yD894
Since it wouldn't have fitted to pastebin otherwise, I removed the "Added ... to ore dictionary entry ..." and the "Added brewing recipe ..." lines from the log.

**Comment by kindlich** [comment]
You have an error while adding a recipe.
In CrT 1.12 furnace recipes are handled after crafting recipes, so an error in adding a crafting recipe will prevent the furnace stuff from happening.

**Comment by kindlich** [comment]
Something to do with MoreFurnaces and an AIOOB with index 7.
Are you trying to use a metadata value of 7 when there are only 6 Tiers or something (I don't know that mod -.-)

**Comment by IchHabeHunger54** [comment]
Yes, I am, and that was the problem. But `/ct syntax` didn't say anything about `morefurnaces:furnaceblock:7` being invalid.

Anyway, sorry to bother you.
