### ISSUE TITLE
Help with script 1.14.4

### ISSUE THREAD

**Issue by Sixdd6** [CraftTweaker/CraftTweaker#905]
#### Issue Description:
I'm having an issue with a script I wrote, the relevant information is included below.

#### What happens:
I get an error in the crafttweaker.log about "ERROR crafting.zs:6:1: Could not cast null to IIngredient"

#### What you expected to happen:
I expected the "null" in the recipe to be passed as an empty slot in the crafting grid as per previous versions of crafttweaker.

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): [crafttweaker.log](https://gist.github.com/Sixdd6/574169c03f3995453615589a2e7fce8a)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.14.4
- Forge: 28.1.109
- Crafttweaker: 5.0.1.150
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

[latest.log](https://gist.github.com/Sixdd6/485ad7c5b5d52564cc200f8184b3cb6b)

**Comment by jaredlll08** [comment]
You don't use `null` anymore, you are meant to use `<item:minecraft:air>`

**Comment by Sixdd6** [comment]
EDIT: Oops beat me to it, forgot to refresh the page.

Nevermind, I found an example that did this with <item:minecraft:air>. Problem solved itself with a little more research.
