### ISSUE TITLE
Tag cannot be null

### ISSUE THREAD

**Issue by WenXin20** [CraftTweaker/CraftTweaker#906]
#### Issue Description:
When trying to add a block to the tag small_flowers, I get an error that says "Tag cannot be null!"
I may also be missing something from the file that I'm unaware of. I tried to use what was suggested in the previous issue, but no luck.

#### What happens:
- Logging into a world produces a "Tag cannot be null!" error with the provided script.

#### What you expected to happen:
- It should instead register the block under the tag small_flowers

#### Script used:
- [Gist](https://gist.github.com/WenXin20/bee3e00ac09b95375e196c8c530e88e3)

#### crafttweaker.log file::
- [Gist](https://gist.github.com/WenXin20/85377bbf6ee82c587322dc6f83aa6774)

____
#### Affected Versions:

- `Minecraft: v1.14.4`
- `Forge: v28.1.107`
- `Crafttweaker: v5.0.1.150`
- Using a server: No

#### Your most recent log file where the issue was present: 

[Full Log](https://gist.github.com/WenXin20/a52d92ea7aabde35880635aa78325483) (Crash report at the end is unrelated to this mod)
Error for this is located at `[18:54:33]`
Error at the beginning of the log at `[18:31:14]` might also be related.

**Comment by kindlich** [comment]
Afaik, you first need to create the tag.
Try something like
```zenscript
<tag:minecraft:small_plants>.createBlockTag();
<tag:minecraft:small_plants>.addBlocks(<blockstate:mubble:fire_flower>);
```

**Comment by WenXin20** [comment]
Thanks, I'll try that.

**Comment by jaredlll08** [comment]
I assume what kindlich said fixed this (because that is what I would have said)
