### ISSUE TITLE
buildcraft refinery recipe looking for colon

### ISSUE THREAD

**Issue by karlkeilai** [CraftTweaker/CraftTweaker#907]
Hello,
I'm attempting to write a craft tweaker script but it says it requires a colon somewhere within the recipe
The recipe is:
Refinery.addRecipe(<vehicle:fuelium>, 200, 10, <buildcraftenergy:fluid_block_oil_dense_heat_1>);

It gives me a message saying that it is expecting a colon on this line but cannot find it.
A log was not created by craft tweaker.

All help is appreciated. Version is 1.12.2
![error message](https://user-images.githubusercontent.com/43070141/71566191-86de0100-2a83-11ea-8e5d-5f4056c8f1e6.PNG)

**Comment by kindlich** [comment]
This has nothing to do with CraftTweaker.
But rather the BuildCraftCompat mod.
Also, in 1.12, BCCompat only offers handlers for the Assembly Table and Combustion Engine IIRC.
