### ISSUE TITLE
bring "replaceAllOccurrences" into modern version?

### ISSUE THREAD

**Issue by jexacan** [CraftTweaker/CraftTweaker#908]
I was coding in the new version of CraftTweaker when I noticed that the new "replaceAllOccurrences" command was no longer supported. I would appreciate it if you could bring this back. The time it takes to replace all recipes manually is way more than any reasonable person has or wants to take on a project.

**Comment by jaredlll08** [comment]
Not a chance, merging that PR was one of the biggest regrets I made with the project.
