### ISSUE TITLE
/ct jeiCategories not outputting any details

### ISSUE THREAD

**Issue by JCAustin** [CraftTweaker/CraftTweaker#909]
#### Issue Description:
When attempting to identify jei Categories to hide via scripts using the /ct jeiCategories or /crafttweaker jeiCategories no categories are output to crafttweaker.log. I'm not one to normally submit bugs to Github but this has me stumped, if I'm missing something in my request let me know and I will fix. 

#### What happens:
On both server and client when running the commands /ct jeiCategories or /crafttweaker jeiCategories it appends '--- JEI Categories ---' to crafttweaker.log but no actual entries afterward while giving an error message in chat saying, 'An unknown error occurred while attempting to perform this command'

#### What you expected to happen:
crafttweaker.log would output ---JEI Categories --- followed by something like 
embers.stamp
thermaldynamics.covers
etc. 

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
[https://pastebin.com/rdpidwEr](https://pastebin.com/rdpidwEr) - 00_default.zs
[https://pastebin.com/EwpnhfXg](https://pastebin.com/EwpnhfXg) - 01_unification.zs
[https://pastebin.com/fHRSx0iy](https://pastebin.com/fHRSx0iy) - 02_jei.zs

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
[https://pastebin.com/SeMX3Zby](https://pastebin.com/SeMX3Zby) - crafttweaker.log

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: forge-14.23.5.2847
- Crafttweaker: CraftTweaker2-1.12-4.1.20.jar
- Using a server: Yes
- If yes, does the client have the exact same scripts? Yes

#### Your most recent log file where the issue was present: 

[https://pastebin.com/aJkhnVYq](https://pastebin.com/aJkhnVYq) - Server Console Log

**Comment by jaredlll08** [comment]
can you run it in a single player world?

**Comment by JCAustin** [comment]
Wow... I can't believe I didn't think of that after spending 3 days troubleshooting this... 

It works! Thanks for the help. Sorry to bother! Keep up the great work!
