### ISSUE TITLE
Immersive Engineering: Metal Press Mold Damage/Consimed?

### ISSUE THREAD

**Issue by drago87** [CraftTweaker/CraftTweaker#910]
Is it possible for the Immersive Engineering: Metal Press Mold to be consumed or damaged?

**Comment by kindlich** [comment]
It is possible for pretty much any item to be consumed or damaged in a crafting table recipe.
Check [Item Transformers](https://docs.blamejared.com/1.12/en/#Vanilla/Items/Item_Transformers/) on the wiki.


Also, such questions are better asked at the [BlameJared discord server](https://discord.blamejared.com)!
