### ISSUE TITLE
Crash with syntax error in replaceAllOccurences function

### ISSUE THREAD

**Issue by drago87** [CraftTweaker/CraftTweaker#911]
#### Issue Description:
Accidently added a extra < in

```
recipes.replaceAllOccurences(<tfc:metal/ingot/copper>, <tfctech:metal/wrought_iron_gear>, <*>.only(function(item) {
    return !isNull(item) & <<immersiveengineering:metal_decoration0:3>.matches(item);
}));
```

#### What happens:
Game crashes at startup

#### What you expected to happen:
Game starts and an error in chat and crafttweaker.log

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/vC2ZrYtk

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/iYA3NTqA
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Crafttweaker: 1.12-4.1.20
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

[crash.log](https://pastebin.com/mQ4VFxYd)
[latest.log](https://gist.github.com/drago87/382f538197b0e3eff416bd918c29c3e9)

**Comment by jaredlll08** [comment]
I'm not sure the issue...
You added an extra `<` and now it is crashing?
try removing it...?
