### ISSUE TITLE
[1.14.4] Error Running Scripts message, even with no scripts.

### ISSUE THREAD

**Issue by darkphan** [CraftTweaker/CraftTweaker#916]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:

When starting a world in a pack with just JEI and CraftTweaker (with no scripts at all, or even with simple scripts) there is an "Error running scripts" message

#### What you expected to happen:

No error messages stating "Error running scripts"

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

No script used to replicate issue.

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

crafttweaker.log: https://gist.github.com/darkphan/5d9f493dc0733307b16ff730085928ab

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.14.4
- Forge: 28.1.111
- Crafttweaker: 1.14.4-5.0.1.154
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

latest.log: https://gist.github.com/darkphan/77174786bfb88b41c3e0ca4cfdb0f23e

**Comment by jaredlll08** [comment]
Try the latest one released, and see if it still happens

**Comment by darkphan** [comment]
It appears to be all good now. Thanks!
