### ISSUE TITLE
[1.12.2] Suggestion

### ISSUE THREAD

**Issue by Dimentive** [CraftTweaker/CraftTweaker#918]
**Feature request name**
Fortune for Custom Drops

**Feature request description**
Fortune affecting custom drops.

**Feature request reason**
It makes sense.

**Feature request dependencies**
No.

**Comment by jaredlll08** [comment]
I have no idea what you're asking for, but 1.12 is not getting any new features.

**Comment by Dimentive** [comment]
Sorry, I was tired. Didn’t explain myself well. I’m suggesting support for the Fortune enchantment for custom drops. If you, say, create a custom ore with ContentTweaker, its drops will not be affected by Fortune.

I also assuming that mob drops are also added with CraftTweaker are not affected by Looting(?). Not sure if this is right to post on CraftTweaker’s GitHub repository, though. Anyway, it’s a shame CT will get no new features for 1.12.2, but that’s understandable.
