### ISSUE TITLE
Bad local variable type exceptions

### ISSUE THREAD

**Issue by Dabombber** [CraftTweaker/CraftTweaker#921]
### Issue Description:
I'm tying to exclude one item from an oredict entry in a recipe ingredient. I think my code is OK, `/ct syntax` has no problems with it, but it causes exceptions.

I guess it's because of the `or`ing with an unset variable, but it even happens with example 3 where `records` should be set before `or`ing.

#### What happens:
`Bad local variable type`

#### What you expected to happen:
Recipe added.

#### Scripts used:

1. [Bad local variable type](https://gist.github.com/Dabombber/cb92a0b47fd2fb28ee820586948bd146)
2. [Works, except for the unwanted rock](https://gist.github.com/Dabombber/91d9fd4cc131fdb2fff6b5255ccea2fd)
3. [Bad local variable type](https://gist.github.com/Dabombber/5d62f5f044ed33ec72375cda6af80659)
4. [Bad local variable type](https://gist.github.com/Dabombber/7d359f4d51292b6425e4b1918678bc88)
5. [Horrible, horrible success](https://gist.github.com/Dabombber/855c2e87398cc47767c73dfdbe4e042d)

#### crafttweaker.log files:
1\. [crafttweaker.log](https://gist.github.com/Dabombber/3ee545a9c9787fb2a4059054f3a161ec)
3\. [crafttweaker.log](https://gist.github.com/Dabombber/4f5e21d3d368db405af24354f0e223fc)
4\. [crafttweaker.log](https://gist.github.com/Dabombber/793099ec2c34ad290a4e40b0cf7f5907)

____
#### Affected Versions:

- Minecraft: 1.12
- Forge: 1.12.2-14.23.5.2847
- Crafttweaker: 1.12-4.1.20
- Using a server: No

**Comment by kindlich** [comment]
Well, you need to initialize the variable with something.
Else, how would you do the OR in line 7?

You could initialize it with something from the oredict that you know matches.
Or you could ditch the whole and do it like
`<ore:record>.only(function(item){return !item.matches(<minecraft:record_13>);})`

Though that would still show that one record in JEI :thinking:

**Comment by Dabombber** [comment]
Yea, it shouldn't be `or`ed while uninitialised in example 3, but it still bugs out. And example 5 is pretty much initialising from a known match, but it's a lot of code for something which should be simple.

Hopefully I'm missing some obvious way of doing it, but I couldn't find a complement to `|`. Something like `<ore:record> ^ <minecraft:record_13>` would be nice.

**Comment by kindlich** [comment]
Try something like
```zs
var records as IIngredient = null;
for item in <ore:record> {
    if(!item.matches(<minecraft:record_13>) {
        records = isNull(records) ? item : (records | item);
    }
}
```

**Comment by kindlich** [comment]
Also, I recommend joining Jared'S [Blamejared Discord Server](https://discord.blamejared.com) since usually more people reply there (and faster)

**Comment by Dabombber** [comment]
This seems to work:

<details><summary>test.zs</summary>
<p>

```zenscript
import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;

var records as IIngredient = null;
for item in <ore:record>.items {
    if(!item.matches(<minecraft:record_13>)) {
        records = isNull(records) ? item as IIngredient: (records | item);
    }
}
recipes.addShapeless("lies", <minecraft:cake>, [records]);
```

</p>
</details>

~~but if I try to put it into a function it packs a sad.~~

EDIT: Still had a 1.12-4.1.19 version in one of my testing profiles, no problems with functions in 1.12-4.1.20.

It seems the third example can be made to work by initialising `records` to `null`, and `item` didn't even need to be cast as `IIngredient` so that must be some ternary operator thing.

**Comment by kindlich** [comment]
Closing this then.
If there are any other issues regarding this, please reply here and I'll reopen it.
