### ISSUE TITLE
Tracking the dimension the player is in

### ISSUE THREAD

**Issue by puncrafter** [CraftTweaker/CraftTweaker#923]
Is there a way to make a variable persist even after relogging?

I want to track what dimension the player is by using the PlayerChangedDimension event, and it works fine until the player relogs and the variable resets.

Alternatively, is there a better way to check which dimension the player is in?

Pastebin of the script in question, if it helps: [https://pastebin.com/eTmKz12y](https://pastebin.com/eTmKz12y)

**Comment by jaredlll08** [comment]
You should ask here:
https://discord.blamejared.com

To set you in the right direction though, IPlayer extends IEntity
IEntity has:
```zenscript
IData getNBT();
void update(IData data);
```
So you can get the current data, and update it with new data
Entity NBT is saved to file (for players their .dat files) and would allow storing variables across scripts / world loads

**Comment by kindlich** [comment]
You can additionally add event handlers to the playerlogin event and get the player's world and dimension from there as well.


Though you may want to change your script in any case since it wouldn't work on servers like that :stuck_out_tongue:
