### ISSUE TITLE
trying to set up a craftable currency

### ISSUE THREAD

**Issue by forestasog** [CraftTweaker/CraftTweaker#929]
#### Issue Description:
I want to use this currency mod called "better coin mod" and convert between the coins with crafts.

#### What happens:
The recipe requires 8 bronze coins to make 1 silver coin, but only consumes 1 bronze coin.

#### What you expected to happen:
For the recipe to consume 8 bronze coins.

#### Script used 
https://pastebin.com/LSVu1fP8

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.14.4
- Forge: 28.2.0
- Crafttweaker: 5.0.1.133
- Using a server: no

**Comment by jaredlll08** [comment]
the crafting table will only ever take 1 item, you can't use amounts in inputs

**Comment by forestasog** [comment]
o ok, thx :P
