### ISSUE TITLE
Add lootingEnchantBonus

### ISSUE THREAD

**Issue by HerleyJLancaster** [CraftTweaker/CraftTweaker#930]
Error: Example4.zs:12> 2 methods available but none matches

To reproduce: https://pastebin.com/BasGHgCK

Expected Behavior: add lootingEnchantBonus function

Log: https://pastebin.com/BGRzb7JU

Version Info (Exact versions only): LootTweaker: 0.1.5+MC1.12.2 CraftTweaker/Minetweaker: Crafttweaker 4.1.20 Forge: 14.23.5.2847 Minecraft: 1.12.2 Tconstruct: 2.13.0.171

I figured out how to add/remove loo but need to add lootingEnchantBonus

**Comment by Daomephsta** [comment]
CraftTweaker's entity drops API doesn't work like that, you can't pass it objects from LootTweaker's loot table API. They're completely separate systems.
Don't try to learn ZenScript by just guessing what works.  
The docs for beginners are lacking, so either find me on my discord when I'm awake (8pm GMT - 9am GMT); or join the [CraftTweaker Discord](discord.blamejared.com) which is big enough to have someone who can help you awake whatever your timezone is.
