### ISSUE TITLE
Why wont you help 

### ISSUE THREAD

**Issue by HerleyJLancaster** [CraftTweaker/CraftTweaker#931]
"Error: [crafttweaker | SIDE_Client]: Error parsing Stray.zs:6 --: expected

To Reproduce This is the script that I have written is here: https://pastebin.com/BasGHgCK

Expected behavior: add lootingEnchantBonus

Version Info (Exact versions only): LootTweaker: 0.1.5+MC1.12.2 CraftTweaker/Minetweaker: Crafttweaker 4.1.20 Forge: 14.23.5.2847 Minecraft: 1.12.2 Tconstruct: 2.13.0.171

youtube Tutorial by IterationFunk: https://www.youtube.com/watch?v=Gam65KJ4RDM

I wont join discord. thats why i posted this on GitHub, but you wont help. i watched this and his other videos here: https://www.youtube.com/watch?v=Gam65KJ4RDM

This script works 100% without the LootingEnchantBonus Line: https://pastebin.com/2DgQ3czU. NO DISCORD as this is supposed to be a support site as well. please do not close the issue as i keep waking up to find the issue closed before i can respond

**Comment by HerleyJLancaster** [comment]
I even just tested to make sure its working

**Comment by jaredlll08** [comment]
Okay so firstly.
You can reply to closed issues.
Secondly, your issue is with LootTweaker, related code, not CraftTweaker related code.
Thirdly, Github is not a support site, Github is to report issues.
As @Daomephsta has said many times now, your understanding of ZenScript is wrong, read the docs and maybe try smaller things. https://docs.blamejared.com

**Comment by HerleyJLancaster** [comment]
But its working

**Comment by jaredlll08** [comment]
Dude, your issue is with LootTweaker stuff, I don't help with that. Go speak to them.

**Comment by HerleyJLancaster** [comment]
i am but you keep closing it

**Comment by jaredlll08** [comment]
This is the CRAFTTWEAKER repository, not the LOOTTWEAKER repository.

**Comment by HerleyJLancaster** [comment]
and the only way i can contact the mod author

**Comment by jaredlll08** [comment]
maybe
try
the
loottweaker
repository
?
?
?
?
https://github.com/Daomephsta/LootTweaker

**Comment by Daomephsta** [comment]
> only way i can contact the mod author
You are in my Discord, so that's nonsense

**Comment by Daomephsta** [comment]
@HerleyJLancaster 
> only way i can contact the mod author

You're in my discord, so that's nonsense
