### ISSUE TITLE
[1.12.2] Mushroom blocks all register with the same name.

### ISSUE THREAD

**Issue by DesertMoonGW** [CraftTweaker/CraftTweaker#932]
#### Intro:
I am attempting to give each mushroom and mushroom block a unique name so they aren't just titled as generic "Mushroom". I am trying to give brown mushroom, brown mushroom block, red mushroom, and red mushroom block the new names of Porcini Mushroom, Porcini Mushroom Block, Fly Agaric Mushroom, Fly Agaric Mushroom Block, respectively.

#### Issue Description:
Once I apply a name change to one of them, it applies that same name to all of them. If I apply multiple names to a different one of these four, it choses whichever one is last in the script.

#### What happens:
Every mushroom block has the name that is last defined to any of the four different mushroom blocks, rather than have their own names.

#### What you expected to happen:
For each mushroom block to take their specifically chosen name

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/7vDg9bJJ
It is worth noting that the other items work fine.

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/DK3AP5XD

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Crafttweaker: 1.12-4.1.20
- Using a server: No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://pastebin.com/DcUcmrBr

**Comment by jaredlll08** [comment]
This isn't possible just due to how it is done in the code.
