### ISSUE TITLE
[1.14+] Functions are only searched for in the root scripts folder

### ISSUE THREAD

**Issue by NielsPilgaard** [CraftTweaker/CraftTweaker#933]
I spoke to kindlich on the Discord about this issue, I'm posting it here as a reminder :)

Placing functions in .zs files in `minecraftfolder/scripts/functions/utility.zs` is throwing `java.lang.NoClassDefFoundError: scripts/utility` 
The same happens for other folders that are not the root scripts folder.

[CraftTweaker.log](https://gist.github.com/NillerMedDild/d1e1c15969cacaf3f4c207048acc1e20)
[Script contents in Gist](https://gist.github.com/NillerMedDild/6db3636b7e0d701526cab09d3ef23508)
### Versions
- CraftTweaker-1.15.2-6.0.0.6

**Comment by NielsPilgaard** [comment]
~~Seems to be fixed in both 1.14 and 1.15 branches.~~ False positive, the issue still exists.

**Comment by kindlich** [comment]
This should be fixed in the beta release on CF now, if not please reopen
