### ISSUE TITLE
[Feature Request] Advanced Creative Tabs Manipluation

### ISSUE THREAD

**Issue by 0xebjc** [CraftTweaker/CraftTweaker#934]
**Creative Tabs - Register & Unregister Items**

**Feature request description**
Ability to remove creative tabs, and item register & unregister for any item for any tab by using zenscripts to unregister items in creative tabs and register them in other creative tabs either existing or via creating new creative tabs,  additionally ability to remove creative tabs / unregister them.  Specifically for 1.12 as that's the mod pack version being developed.

**Feature request reason**

While building mod packs with many mods, the creative tabs become really cluttered.  I would like to reorganized all my added mods by removing them from all their unique mod creative tabs, sorting them into the default creative tabs, for example all moded swords go into a sword tab, and armor into a separate armor tab, all books in a separate tab, all potions from all mods into one tab, etc.

**Feature request dependencies**
It could be a feature for vanilla or moded minecraft, but more helpful for moded minecraft.

**Comment by jaredlll08** [comment]
This can maybe be done, would need to be researched more, but I will say now that it won't be for 1.12, it would be for 1.14+

**Comment by kindlich** [comment]
Not feasible for us to do, since it may break mods.
See #1033 for more info
