### ISSUE TITLE
Warning Message, each time I log on.

### ISSUE THREAD

**Issue by Arctic90x** [CraftTweaker/CraftTweaker#937]
I removed recipe and now I keep getting a message saying WARNING: Recipe named [minecraft:fishing_rod] may not contain a ':' replacing with '_'!

I did add the image so you could see. I am not sure how to fix this or why it's happening or maybe it's a normal thing?

![2020-03-10_07 00 54](https://user-images.githubusercontent.com/52586001/76306565-83de6880-629d-11ea-9ba2-51d89ff3ae91.png)

**Comment by jaredlll08** [comment]
Follow the template.
Read the actual error
and I swear, why do you think a screenshot of text is useful in any capacity?

**Comment by Arctic90x** [comment]
Dude, I'm only 13 and still learning. I was simply asking for help but guess you're not in the mood to help. Thanks for nothing. . .

**Comment by jaredlll08** [comment]
Okay well firstly:
we have an issue template, it gives us information about what you are actually using, such as the Minecraft version.

For all I know you may be using the CraftTweaker 1.3.2 version, which is VERY different than the latest 1.15.2 version.

It also asks for the scripts you're using, so I can see what you're actually running and I can help more.

Secondly: 
Reading text off images is really really annoying and just not needed when we provide a crafttweaker.log file that has the full error there.


If you still want help, make a new issue and provide us with the things that we ask for.
