### ISSUE TITLE
Warning Message, each time I log on.

### ISSUE THREAD

**Issue by Arctic90x** [CraftTweaker/CraftTweaker#938]
- What happens:
I removed a recipe to add my own and now I keep getting a message saying 
**WARNING: Recipe named [minecraft:fishing_rod] may not contain a ':' replacing with '_'**

I am not sure why it's happening or maybe it's a normal thing, I am still learning how to use CraftTweaker any help would be great!

- My Script 
//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
recipes.removeShaped(<minecraft:fishing_rod>, [[null, null, <ore:stickWood>], [null, <ore:stickWood>, <ore:string>], [<ore:stickWood>, null, <ore:string>]]);
//Don't touch me!
//#Add
recipes.addShaped(<advanced-fishing:blazing_fishing_pole>, [[null, null, <minecraft:blaze_rod>],[null, <minecraft:blaze_rod>, <minecraft:string>], [<minecraft:blaze_rod>, null, <jaff:iron_hook>]]);
recipes.addShaped("minecraft:fishing_rod", <minecraft:fishing_rod>, [[null, null, <ore:plankWood>], [null, <ore:plankWood>, <minecraft:string>], [<ore:stickWood>, null, <jaff:iron_hook>]]);
//File End

- crafttweaker.log file 
([PREINITIALIZATION][CLIENT][INFO] Current loaders after merging: [[preinit]]
[PREINITIALIZATION][CLIENT][INFO] Loading scripts for loader with names [preinit]
[PREINITIALIZATION][CLIENT][INFO] [preinit | SIDE_CLIENT]: Skipping file {[0:crafttweaker]: recipes.zs} as we are currently loading with a different loader
[PREINITIALIZATION][CLIENT][INFO] Completed script loading in: 2ms
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Building registry
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Successfully built item registry
[INITIALIZATION][CLIENT][INFO] Current loaders after merging: [[preinit], [recipeevent | crafttweaker]]
[INITIALIZATION][CLIENT][INFO] Loading scripts for loader with names [crafttweaker | recipeevent]
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: recipes.zs}
[INITIALIZATION][CLIENT][WARNING] Recipe name [minecraft:fishing_rod] may not contain a ':', replacing with '_'!
[INITIALIZATION][CLIENT][INFO] Completed script loading in: 374ms
[POSTINITIALIZATION][CLIENT][INFO] Removing recipes for various outputs
[POSTINITIALIZATION][CLIENT][INFO] Removing Shaped recipes for <minecraft:fishing_rod>
[POSTINITIALIZATION][CLIENT][INFO] 1 removed
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Blazing Fishing Pole with name ct_shaped626143335
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Fishing Rod with name minecraft_fishing_rod
[AVAILABLE][CLIENT][INFO] Fixed the RecipeBook)

- Minecraft: 1.12.2
- Forge: 14.23.5.2832
- Crafttweaker: 4.1.20

**Comment by jaredlll08** [comment]
In the future, PLEASE do not post your scripts into the github issue, upload them to https://gist.github.com, github issues have special markup formatting that messes with the scripts, it removes `<>` from the scripts and sometimes more.

```
ecipes.addShaped("minecraft:fishing_rod", minecraft:fishing_rod, [[null, null, ore:plankWood], [null, ore:plankWood, minecraft:string], [ore:stickWood, null, jaff:iron_hook]]);
```
Recipe names are in the `modid:name` format, so here the modid is `minecraft` and name is `fishing_rod`

The recipe name should only be the last part `fishing_rod`, recipes added by CraftTweaker all use the `crafttweaker` modid, so in this case it is trying to add a recipe with the name `crafttweaker:minecraft:fishing_rod` which is invalid. 

So the actual error is saying "You can't have that as a name, we are going to replace your `:` with a `_` so the recipe name will become: `crafttweaker:minecraft_fishing_rod`
