### ISSUE TITLE
Unsupported Mod

### ISSUE THREAD

**Issue by Arctic90x** [CraftTweaker/CraftTweaker#943]
**Feature request name** 1.12.2 Mod Support for Nature's Compass
https://www.curseforge.com/minecraft/mc-mods/natures-compass

**Feature request reason** It's unsupported that I can tell and it would be nice to be able to use it within a mod pack and have support for the given mod.

**Comment by jaredlll08** [comment]
Not sure how the mod is unsupported, but ask the mod author to add support.
