### ISSUE TITLE
1.15 Error when people are joining a server

### ISSUE THREAD

**Issue by Darkere** [CraftTweaker/CraftTweaker#944]
#### Issue Description:
Error every time a player joins the server. 
``` [13:14:52] [Netty Epoll Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.ModIdArgument@226b0b9c (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
>.... [13:14:52] [Netty Epoll Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize com.blamejared.crafttweaker.impl.commands.CTCommands$$Lambda$10705/412846216@899a554 (class com.blamejared.crafttweaker.impl.commands.CTCommands$$Lambda$10705/412846216) - will not be sent to client!
>.... [13:14:52] [Netty Epoll Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize com.blamejared.crafttweaker.impl.commands.CTCommands$$Lambda$10721/305563650@8ba7e31 (class com.blamejared.crafttweaker.impl.commands.CTCommands$$Lambda$10721/305563650) - will not be sent to client!
>.... [13:14:52] [Netty Epoll Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.ModIdArgument@33320f53 (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
>.... [13:14:52] [Netty Epoll Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.EnumArgument@4c7c972c (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
>.... [13:14:52] [Netty Epoll Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.EnumArgument@44579706 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
```
This is spamming our latest.log hiding actual errors. 

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
I do not believe this is script related but you can find all our scripts here: 
https://github.com/Team-RAM/RAM/tree/master/overrides/scripts

___
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.15.2
- Forge: 31.1.19
- Crafttweaker: 1.15.2-6.0.0.9
- Using a server: yes
- If yes, does the client have the exact same scripts? yes

lastest.log : https://gist.github.com/Darkere/50d23bad7528a3a15e725773ad85d25b
Crafttweaker log: https://gist.github.com/Darkere/a54aad473708e85a4e191bff2f7702ed
Casting errors are race conditions, sometimes there sometimes not. Unrelated to this case.

**Comment by jaredlll08** [comment]
This is an issue with the command library minecraft uses, you'll notice you're even getting spam from Forge commands, nothing can be done to fix it, and other mods also suffer from it (biomes o plenty for example)
