### ISSUE TITLE
[1.7.10] craft tweaker legacy errors

### ISSUE THREAD

**Issue by seitenca** [CraftTweaker/CraftTweaker#945]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:

addResearch(string, string, Optional string, int, int, int, string, string)
addResearch(string, string, Optional string, int, int, int, ZenTypeNative: minetweaker.item.IItemStack, ZenTypeNative: null.null[], string[])
addResearch(string, string, Optional string, int, int, int, ZenTypeNative: minetweaker.item.IItemStack)
ERROR: Emt.zs:229 > 3 methods available but none matches the parameters (string, string, string, int, long, int, ZenTypeNative: minetweaker.item.IItemStack)
This is usually an error in your script, not in the mod

#### What you expected to happen:

no errors

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://github.com/seitenca/NewHorizons/blob/master/scripts/Blood-Magic-Thaumcraft.zs

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://github.com/seitenca/NewHorizons/blob/master/minetweaker.log

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.7.10
- Forge: 1614
- Crafttweaker: 3.1-legacy
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://github.com/seitenca/NewHorizons/blob/master/minetweaker.log

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
1.7.10 is no longer supported.

**Comment by seitenca** [comment]
nice, thanks for you help :)

**Comment by kindlich** [comment]
The problem is that the negative values are seen as long and not as int.

Try to use `-2 as int` instead of only `-2` and do the same for the other negative parameters

**Comment by seitenca** [comment]
@kindlich ok, thanks :D
