### ISSUE TITLE
[1.15.2]Request to add 'ctgui' command

### ISSUE THREAD

**Issue by EnterFor** [CraftTweaker/CraftTweaker#946]
**Feature request name**

Request to add 'ctgui' command

**Feature request description**

You can add / remove recipes using the GUI

**Feature request reason**

It's very helpful for beginners and reduces editing time

**Feature request dependencies**

GUI similar to 1.12

**Comment by jaredlll08** [comment]
Request denied.
The language is easy to learn.
I don't want to waste dev time making something I don't like. (I'm not going to accept a PR I don't like either.)
By having the gui, it leads people to expect everything to be done via a gui, which is just impossible.
