### ISSUE TITLE
[1.12.2] script error

### ISSUE THREAD

**Issue by takeshipoggies** [CraftTweaker/CraftTweaker#948]
#### Issue Description:
I'm trying to create a modpack, installed Craft Tweaker and Avaritia1.1x and I wanted to modify some normal and extreme crafting recipes... I'm kind of a noob at coding but I'm 99.99% sure this is a syntax error and nothing else.

#### What happens: 
When I try to load the script file I get the error "[crafttweaker | SIDE_CLIENT]: Error parsing hello.zs:1 (the name of my script file) -- identifier expected"

#### What you expected to happen:
The game should remove the old normal recipe for the Philosopher Stone from ProjectE and replace it with my custom extreme recipe.

#### Script used:
https://gist.github.com/TheBestCube/1b7f94dcc7b151feb27c93b5a8b50446#file-hello-zs

#### crafttweaker.log file:
https://gist.github.com/TheBestCube/7d1bcedbb5492c5ff6dd8a99fc638972#file-crafttweaker-log

____
#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Crafttweaker: Craft Tweaker 2 v4.1.20
I'm also using 
1) Content Tweaker 4.9.1
2) Crafting tweaks 8.1.9
3) Mod Tweaker 4.0.18
(don't remember if they are related)
- Using a server: No.
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 
https://gist.github.com/TheBestCube/974f85d3045dc3d6ddd5c6a03b54b499#file-latest-log

**Comment by jaredlll08** [comment]
why are you importing an item?

**Comment by takeshipoggies** [comment]
Should I not do that? I’m following the Iteration Funk tutorials on youtube, not sure if I should or not...

**Comment by takeshipoggies** [comment]
So I tried that and it turns out you were right. You don’t want to import anything that’s an item or a different way of crafting, from some mods like Extended Crafting or similar, in your .zs file. You just wanna edit the recipes, that’s all.
