### ISSUE TITLE
[1.15.2] Command And Script Error

### ISSUE THREAD

**Issue by BunCat09** [CraftTweaker/CraftTweaker#952]
#### 1. Issue Description:
I was trying to add some recipes to convert between minecraft's and quark's chests.  
____
#### 2. Issue Description:
Commands on the wiki page doesn't work. I tried "minetweaker names" and "minetweaker reload" but it didn't work so i typed "crafttweaker" instead of "minetweaker". It accepted crafttweaker but not "names" or "reload".

#### What happens:
When i load a world, a long error message shows up in chat and my script just doesn't work.

#### What you expected to happen: 
I was expecting a shapeless-alike recipe for converting chests to eachother.

#### Script used:
https://pastebin.com/GnWajygG

#### crafttweaker.log file:
https://pastebin.com/1ZSnGH3h

____
#### Affected Versions:

- Minecraft: 1.15.2
- Forge: 31.1.30 and 31.1.34
- Crafttweaker: 6.0.0.9
- Using a server: NO

#### Your most recent log file where the issue was present: 
[2020-04-01-1.log](https://github.com/CraftTweaker/CraftTweaker/files/4415799/2020-04-01-1.log)

[pastebin/gist/etc link here] --> pastebin doesn't let me because of the file size of the log is greater than 512kb so i attached the log.

**Comment by kindlich** [comment]
First, if you use those commands then you are most likely on the wrong wiki.

1.14 and 1.15 are fundamentally different from the previous versions:
They use a new ZS engine, have different commands and even some names are different.

Take a look at the example
<https://github.com/CraftTweaker/CraftTweaker-Examples/blob/master/1.14/general.zs>

And use this wiki
<https://docs.blamejared.com/1.14/en/>

Also, there is no `crafttweaker reload` you can use the normal `/reload` command from vanilla to reload scripts.

**Comment by BunCat09** [comment]
I used this wiki which was on the mods curseforge page: http://minetweaker3.powerofbytes.com/wiki/Main_Page
I'll use the proper one now thanks.
