### ISSUE TITLE
crash bug ?

### ISSUE THREAD

**Issue by eloe79** [CraftTweaker/CraftTweaker#953]
Minecraft Version: 1.15.2
Operating System: Windows 10
Java Version: 1.8.0_241, Oracle Corporation
Forge: net.minecraftforge:31.1.30
ProjectE-1.15.2-PE1.0.3B.jar

https://pastebin.pl/view/0063eb4b

Steps to reproduce:

#### Issue Description:
trying to reload after seting custom EMC - /projecte seteemc /reload

## Your most recent log file where the issue was present: 
[pastebin/gist/etc link here] - https://pastebin.pl/view/b2af3039

ps, also reported to ProjectE - https://github.com/sinkillerj/ProjectE/issues/1989

**Comment by jaredlll08** [comment]
This is an issue with them, not us.
