### ISSUE TITLE
Crash on world enter with Quark

### ISSUE THREAD

**Issue by Insane96** [CraftTweaker/CraftTweaker#954]
#### What happens:
When entering a world with both CraftTweaker, Quark and Quark Oddities the game crashes

#### What you expected to happen:
To not crash

#### Script used:
https://gist.github.com/Insane96/1c13a39c726527cc09880bdfba945902

#### crafttweaker.log file:
https://gist.github.com/Insane96/1c13a39c726527cc09880bdfba945902

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.15.2
- Forge: 31.1.27
- Crafttweaker: 6.0.0.10
- Using a server: Nop

#### Your most recent log file where the issue was present: 
https://gist.github.com/Insane96/ee8c0bd707db49f5103a9ca80cc31df6

Reported over to Quark's too https://github.com/Vazkii/Quark/issues/2007

**Comment by jaredlll08** [comment]
I don't see how this could be an issue with my code, the only way I'm involved is by converting my ingredient to a vanilla ingredient, which if there was a problem with, would have crashed much sooner.

current guess:
The tag may not exist, I don't know if insane vanilla is a mod or your modpack, if it is your modpack, are you sure you are creating an item tag? if so, what is the script?
if insane vanilla is a mod:
it is probably adding tags too late or something / the tag is empty

**Comment by Insane96** [comment]
Yeah, forgot to add the tag. But still the game shouldn't crash.
Also why is Quark mentioned in the crash-log?

**Comment by jaredlll08** [comment]
I'm not sure what to tell you, but it's vanilla's code that is crashing, there is nothing I can do about that, like the tag isn't just empty, it straight up doesn't exist.
