### ISSUE TITLE
Problem removing recipes [Crafft Tweaker 1.12.2]

### ISSUE THREAD

**Issue by takeshipoggies** [CraftTweaker/CraftTweaker#957]
#### Issue Description:
I have a new problem here... I am seriously trying to get to know how CraftTweaker works. I happen to have discovered a way to edit Avaritia1.1x recipes but now the issue comes with normal recipes ahahah..
If it's some syntax error I don't know what to do because I'm using the in-game commands for Craft Tweaker. :(

#### Script used:

https://gist.github.com/TheBestCube/e2f958911d61b02de3608a4be09db372#file-avaritia_generic-zs

#### crafttweaker.log file:

https://gist.github.com/TheBestCube/9f79644ec5c80a4cc3a872d5c653fbc1#file-crafttweaker-log

#### Affected Versions:

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Crafttweaker: 1.12 - 4.1.20
- Using a server: Nope

#### Your most recent log file where the issue was present:

https://gist.github.com/TheBestCube/a49774a6547e70bce83c72f9d1954873#file-latest-log

**Comment by jaredlll08** [comment]
`recipes` not `recipe`

**Comment by takeshipoggies** [comment]
Whoops my bad I was in a hurry. Thanks and I’m sorry to bother you probably dealing with way more complicated things..

**Comment by jaredlll08** [comment]
It's all good ^^

If you have further issues or questions, you should join the discord, https://discord.blamejared.com
