### ISSUE TITLE
[1.15.2]Refined Storage changing disk recepie

### ISSUE THREAD

**Issue by beaconborn** [CraftTweaker/CraftTweaker#959]
#### Intro:
I tried to change recepies for my modpack to play with friends
Some recepies changed sucsesfully, in script silicon destruction_core, storage_housing, but 1k_disk not changing,maybe i doing it wrong. Usualy disk creates with 2 NBT tags which shows the UUID.

#### Issue Description:
Maybe not your bug, maybe not bug at all

#### What happens:
prints errors in chat and reverce all recepies to default

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

in gist 

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
in gist 

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.15.2
- Forge: 31.1.46
- Crafttweaker: 6.0.0.13
- Refined Storage: 1.8.1
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://gist.github.com/RIKRUS/fa47c9c6e649b7f895c76421dd4a46c4

**Comment by jaredlll08** [comment]
ooh boy okay

so firstly:
no idea what you're doing here:
https://gist.github.com/RIKRUS/fa47c9c6e649b7f895c76421dd4a46c4#file-script-L1-L3
just remove them

secondly:
https://gist.github.com/RIKRUS/fa47c9c6e649b7f895c76421dd4a46c4#file-script-L5
variables cannot start with a number.
