### ISSUE TITLE
[1.15.2] Unable to make shapeless recipe

### ISSUE THREAD

**Issue by Secretname2009** [CraftTweaker/CraftTweaker#961]
#### Intro:
I am trying to make a shapeless recipe for a server that converts diorite, granite and andesite to cobblestone but the same error occured every time i tried to reload the script. It would be nice to get some help with this error.

#### Issue Description:
Issue is that while parsing it expects a ; at line 5 and column 121. That location is in the middle of a "null" and wouldnt make any sense to add. Even after adding the ; at requested spot it returns same error but it expects another one beside it.

#### What happens:
What happens is the parser expects a ; at line 5 and column 121 for unknown reasons.

#### What you expected to happen:
The script file would be parsed correctly and recipes created.

#### Script used: 
https://pastebin.com/gjCbTVmG

#### crafttweaker.log file: 
https://pastebin.com/fWdXqTVq

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.15.2
- Forge: 31.1.48
- Crafttweaker: 6.0.0.19
- Using a server: Yes
- If yes, does the client have the exact same scripts? It would but server is failing to parse it itself.

#### Your most recent log file where the issue was present: 

https://pastebin.com/jug6iDX8

**Comment by kindlich** [comment]
You need `<item:minecraft:cobblestone>` instead of `<minecraft:cobblestone>` and the same for the other Brackets

**Comment by Secretname2009** [comment]
Thats new to me. Thanks for the help.

**Comment by jaredlll08** [comment]
Well 1.14 and 1.15 are a complete rewrite...
