### ISSUE TITLE
[Feature request] IItemDefinition on 1.15.2

### ISSUE THREAD

**Issue by jamesjimmy88** [CraftTweaker/CraftTweaker#962]
**Feature request name**
The name for the feature request, something short and descriptive, example: "Blockstate Support"

**Feature request description**
Describe what you would like added

**Feature request reason**
Why do you need this? / Why do you think this would be useful?

**Feature request dependencies**
Does the feature request require anything to be implemented? / Will this feature request only be useful when combined with another mod?

**Comment by jaredlll08** [comment]
What would you even want in it?

makeStack isn't really used now that there isn't metadata.

most of the other methods (there really aren't many) are ItemStack specific (individual ItemStacks can override it, not limited to just the item)

**Comment by jaredlll08** [comment]
Closing due to no reply.
