### ISSUE TITLE
CraftTweaker GUI JEI integration

### ISSUE THREAD

**Issue by rlnt** [CraftTweaker/CraftTweaker#964]
**Feature request description**
I am currently creating a modpack with some friends. As they are not experienced in programming or using any scripting language at all, the CraftTweaker GUI for the crafting table is quite handy for them. We'd like to tweak a lot of already given recipes so it would be nice if you could have a JEI integration in the GUI where you just search for the item and click the little plus sign like it is when you want to craft the item.
After clicking the plus, the recipe should be automatically moved in the CT GUI to edit it. That would save a ton of time.

**Feature request reason**
It makes editing existing recipes a lot faster if you just want to edit one or two ingredients.
Especially for people with no experience in scripting, this would be handy. They could edit the recipe in the GUI very fast and just give the file to me.

**Feature request dependencies**
It would only work if JEI is installed. No other dependencies are needed.

**Comment by jaredlll08** [comment]
CTGui isn't supported any more.
