### ISSUE TITLE
Enchantment Management

### ISSUE THREAD

**Issue by jbjornberg** [CraftTweaker/CraftTweaker#965]
**Enchantment Management**
I'd like to be able to modify which enchantments are able to be attained through the Enchantment Table, as well as via loot in Dungeons.

The reason I need it is due to the nature of my Server. It revolves around unique weapons with unique enchantment sets, and I'd like to restrict some of the enchantment mods I've installed to only being accessible through NBT Editing.

I've considered disabling the Enchantment Table entirely but ideally I'd like to keep it and just modify it so only vanilla enchantments can be found through it.

i.e. I've disabled the "Heroic Armory" weapons from being found randomly or crafted, and instead modified them with unique enchantments (i.e. lifesteal/living) and made a quest for them via Custom NPCs.

If this already exists or this only requires modification of something in bin, I apologize as I looked up a lot of key-words like "Enchantment Restriction" or "Enchantment Table Modification" and I couldn't seem to find anything.

Thanks!

**Comment by jaredlll08** [comment]
Last I checked, I can't change enchantments from the enchantment table.
Even if I could, it I doubt it would work for the other mods that add enchantment systems, like TE or quark
