### ISSUE TITLE
[1.15.2]  `/ct hand` outputting withTag and withDamage together

### ISSUE THREAD

**Issue by Snownee** [CraftTweaker/CraftTweaker#966]
#### Issue Description:

Using `/ct hand` to damaged tool will output `withTag` and `withDamage` together, rather than one of them.

#### What happens:

Giving you:
```
<item:minecraft:diamond_pickaxe>.withTag({Damage: 1}).withDamage(1)
```

#### What you expected to happen:

```
<item:minecraft:diamond_pickaxe>.withDamage(1)
```

____

- Crafttweaker: 6.0.0.23

**Comment by jaredlll08** [comment]
Fixed in a commit that I forgot to reference, but it is fixed in the latest build
