### ISSUE TITLE
Vargs break on static methods

### ISSUE THREAD

**Issue by Darkhax** [CraftTweaker/CraftTweaker#974]
#### Issue Description:
When a static ZenMethod has vargs it will fail in weird and different ways depending on the signature of the method. For example if there are non-varg arguments it will complain about having too many arguments. If there are only varg arguments there will be a compilation failure.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.15.2
- Forge: 88
- Crafttweaker: 26
- Using a server: no
- If yes, does the client have the exact same scripts? yes

#### Files/Logs/Stuff

[Static Method + Vargs + Other Args](https://gist.github.com/Darkhax/b8a2e6744c63199255592dff773c1bae)
[Static Method + Vargs + No other Args](https://gist.github.com/Darkhax/2dd7885bf212ca5e7be0b84e5bcbb649)
[Non-Static Vargs](https://gist.github.com/Darkhax/fcd8057ac43681b8b1e1b1b56f556efc)

**Comment by kindlich** [comment]
Closing this since it should be fixed and judging by the private conversations we had, you don't need it any more 😛
