### ISSUE TITLE
New furnace command requested for 1.12.2+

### ISSUE THREAD

**Issue by bookerthegeek** [CraftTweaker/CraftTweaker#976]
**Feature request**
I would like `furnace.removeAllFuel();` to be a valid command.

**Feature request description**
I would like one command to remove all fuels from the furnace.

**Feature request reason**
One line to remove all furnace fuels vs a lot of lines removing each fuel individually. 

**Feature request dependencies**
Nope. Just Minecraft.

**Comment by jaredlll08** [comment]
Sorry for the long wait, 1.12 really isn't on my priority list at all.

Seeing as `furnace.setFuel` accepts an IIngredient, doing:
```zs
furnace.setFuel(<*>, 0);
```

Should work.
