### ISSUE TITLE
"/ct conflict" is broken - "Warning: JEI plugin not loaded!"

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [CraftTweaker/CraftTweaker#978]
#### Intro:
"/ct conflict" command appears to be broken.

#### Issue Description:
- I'm not using a modpack. 
- When I type the command it says:
 https://gyazo.com/136ffdba819c602349af03ea15d1b305
- Even though I **do** have the JEI mod installed:
https://gyazo.com/2caa4d9449106269f25179a34f8d8ae4

#### What happens:
I described this in the "Issue Description". There's nothing else to say.

#### What you expected to happen:
I expected the command to work.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
No scripts are added.

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/pinkpig3777/5b581cb6072b11b47b32ff73bfc12911

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Crafttweaker: 4.1.20
- Using a server: Yes, Forge (Not SpongeForge or Fabric)
- If yes, does the client have the exact same scripts?
There are no scripts on client or server.

#### Your most recent log file where the issue was present: 

It doesn't show in console or logs when I type commands in-game but:
https://gist.github.com/pinkpig3777/d3a6d600636d924ee0b5ffe8e98d485e

Just to be thorough here is debug.log as well:
https://gist.github.com/pinkpig3777/bcc8d26a84facd21503ea72b0d415a12

**Comment by PiggiesGoSqueal** [comment]
Similarly, /ct jeiCategories does not work. Here is the console error:
https://gist.github.com/pinkpig3777/f8b34b209b610a28f1c3861d9cc08c22

**Comment by kindlich** [comment]
`This command can only be executed on the client...`

You need to be in single player to use that command iirc

**Comment by PiggiesGoSqueal** [comment]
Oh... Thanks
