### ISSUE TITLE
[Spam] [Logs] Jared Dun Goofed and Spammed my Logs again :/

### ISSUE THREAD

**Issue by Lanse505** [CraftTweaker/CraftTweaker#979]
#### Issue Description:
Crafttweaker in 1.15 is currently causing the logs to get spammed with the following errors.
![bild](https://user-images.githubusercontent.com/1495068/82235778-7abfe680-9933-11ea-8e24-4c377cf2a27d.png)

#### What happens:
Me logs be spammed captain, It can't take much longer.

#### What you expected to happen:
My logs to not be spammed, after all this isn't mine and Jareds DMs.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
No Scripts used, this is a default load issue.

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
No crafttweaker.log required :O 

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.15.2
- Forge: 31.2.0
- Crafttweaker: Crafttweaker-1.15.2-6.0.0.27
- Using a server: Nope, though I'd imagine this happens on both sides.

#### Your most recent log file where the issue was present: 
https://gist.github.com/Lanse505/117861d319faba9a0928b3852090d90e

**Comment by Lanse505** [comment]
Also STDOUT and STDERR >->

**Comment by kindlich** [comment]
Hey there, short update:
This will be part of a larger update currently still being on my fork, as I need to fix some stuff.
