### ISSUE TITLE
Crafttweker I didn't have the problem of writing instructions incorrectly, But it doesn't work

### ISSUE THREAD

**Issue by QianMuu** [CraftTweaker/CraftTweaker#980]
The drop file is as follows:
<entity:zombie>.addPlayerOnlyDrop(<minecraft:diamond>,1,8);
<entity:creeper>.addPlayerOnlyDrop(<minecraft:diamond>,1,10);
<entity:spider>.addPlayerOnlyDrop(<minecraft:diamond>,1,12);
<entity:skeleton>.addPlayerOnlyDrop(<minecraft:diamond>,1,15);

There is no problem with the command input because I am 1.10.2 It's a pilot test. It's working normally, but 1.12.2 But it shows an error
It's like this:
ERROR: [crafttweaker]: Error executing {[0: crafttweaker]:
Diaoluo. zs}: null

Moreover, as for the percentage probability of dropped objects, the dropped objects can not be used normally. I write instructions like this:
<entity:skeleton>.addPlayerOnlyDrop(<minecraft:diamond>%20,1,15);
But it shows in the game:
ERROR: Hecheng.zs: 5 a method available but rione matches the parameters
(ZenTypeNative: minetweaker.item.WeightedItemStack, int, int)
This is usually an error in your script, not in the mod addPlayerOnlyDrop(ZenTypeNative: minetweaker.item. IItemStack, Optional int, Optional int)

Why is there such a problem???

**Comment by jaredlll08** [comment]
Use the issue template if you actually want help.
