### ISSUE TITLE
ERROR: [crafttweaker]: Error executing:crafttweaker]: Diaoluo.: null

### ISSUE THREAD

**Issue by QianMuu** [CraftTweaker/CraftTweaker#983]
Hello！
I use 1.12.2, the latest version of crafttwker，
But its command is wrong, which bothers me a lot！

 I set the monster's Loot command, as follows：
<entity:zombie>.addPlayerOnlyDrop(<minecraft:diamond>,1,8);
<entity:creeper>.addPlayerOnlyDrop(<minecraft:diamond>,1,10);

but，Into the game. The command can't be used normally，
as follows：
ERROR: [crafttweaker]: Error executing:crafttweaker]: Diaoluo.: null

I'm sure there's no problem with my papers！
Why can't it be used？

**Comment by kindlich** [comment]
The issue template exists for a reason, please proovide your exact version of CrT, as well as your script and the game log and most importantly, the crafttweaker.log file in a readable format (that is on pastebin or gist.github.com)

One of the reasons why we state you should upload them to gist or pastebin is that GH's markup messes up bracket handlers!

**Comment by jaredlll08** [comment]
No issue template.
No script.
No reply.
