### ISSUE TITLE
SetDiplayName doesn't seem to be working

### ISSUE THREAD

**Issue by jamiewood678** [CraftTweaker/CraftTweaker#985]
#### Intro:
Can't rename on item using craft tweaker.

#### Issue Description:
When using the function `setDisplayName` on an item the expected behavior is that in-game the name is changed to what I've set it too. 

However, this isn't happening.

#### What happens:
Script doesn't error, runs fine but item name in-game doesn't change.

#### What you expected to happen:
That when hovering over the item in the inventory the item name is changed to what I've set it to. In the script given I'm trying to rename an item from 'decay' to 'potion of decay' but the inventory still states that it is called 'decay'.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

The name of the file is `charm - rename decay.zs`

`<item:minecraft:potion>.withTag({Potion: "charm:decay_potion" as string}).setDisplayName("Potion of Decay");`

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/aQR8xMX9
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.15.2
- Forge: 31.1.79
- Crafttweaker:  1.15.2-6.0.0.24
- Using a server:  No
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

https://pastebin.com/6WZUqjDA

**Comment by jaredlll08** [comment]
The method doesn't rename the item everywhere, it creates a new IItemStack with that name (that IItemStack can be returned as a recipe output)

We don't have global renaming yet.
