### ISSUE TITLE
Help with my script

### ISSUE THREAD

**Issue by jopau9** [CraftTweaker/CraftTweaker#986]
[
![Sin título](https://user-images.githubusercontent.com/57316018/82890856-23ca9a80-9f4d-11ea-85fa-314e2f92686e.png)
](url)

All I want is to remove the recipe.

Mod: GhostExplosives

I do not know why it does not work

Any help? pls

**Comment by jaredlll08** [comment]
Firstly, don't post pictures of code.

Secondly, help is provided over discord:
https://discord.blamejared.com

**Comment by jopau9** [comment]
okey sorry
