### ISSUE TITLE
[1.15.2] Inputs in RecipeFunctionMatrix are air

### ISSUE THREAD

**Issue by justinrusso** [CraftTweaker/CraftTweaker#987]
#### Issue Description:
When attempting to use a `RecipeFunctionMatrix`, the inputs are all `<item:minecraft:air>`.

This appears to be caused by the call to `ForgeHooks.getContainerItem` which returns `ItemStack.EMPTY` in `IIngredient.getRemainingItem`. I would assume not every item has a container.
https://github.com/CraftTweaker/CraftTweaker/blob/e3d0d1c13c842f6b3204f1968fe056110257f8c7/src/main/java/com/blamejared/crafttweaker/api/item/IIngredient.java#L55-L58
which is called here https://github.com/CraftTweaker/CraftTweaker/blob/e3d0d1c13c842f6b3204f1968fe056110257f8c7/src/main/java/com/blamejared/crafttweaker/impl/recipes/CTRecipeShaped.java#L137

#### What happens:
When placing the items needed to trigger the recipe function, all inputs in the arrays are `<item:minecraft:air>`.

#### What you expected to happen:
The items should essentially be the same as defined in the recipe.

#### Script & logs:
https://gist.github.com/justinrusso/ec239fc5b11f1b826228c99fc94d2275

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.15.2
- Forge: 31.2.0
- Crafttweaker: 1.15.2-6.0.0.29 and dev (e3d0d1c13c842f6b3204f1968fe056110257f8c7)
- Using a server: No

**Comment by jaredlll08** [comment]
believe this is fixed
