### ISSUE TITLE
FunOres Conflict?

### ISSUE THREAD

**Issue by MagmaSlime123** [CraftTweaker/CraftTweaker#988]
#### Intro:
N/A?

#### Issue Description:
Removing a recipe for the FunOres Metal Furnace (FunOres mod) wont remove the old recipe.

#### What happens:
The recipe still exists...

#### What you expected to happen:
The recipe being removed...

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://hastebin.com/xiponiqobi.xml

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
[crafttweaker.log](https://github.com/CraftTweaker/CraftTweaker/files/4719049/crafttweaker.log)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 2854
- Crafttweaker: CraftTweaker2-1.12-4.1.20.574
- Using a server: No
- If yes, does the client have the exact same scripts? Yes.

#### Your most recent log file where the issue was present: 
[crafttweaker.log](https://github.com/CraftTweaker/CraftTweaker/files/4719026/crafttweaker.log)

[pastebin/gist/etc link here]
https://hastebin.com/xiponiqobi.xml
(Pastebin is down at the time I submitted this, sorry if I shouldn't use Hastebin.)

**Comment by jaredlll08** [comment]
you're script is empty.
your log is an uploaded file (not pastebin / gist like we asked).

and in any case, if a recipe isn't removed, the mod is doing something wrong like registering recipes weirdly or after we remove them. nothing we are going to do about that.
