### ISSUE TITLE
[Feature Request] Block NBT access

### ISSUE THREAD

**Issue by wootaboot** [CraftTweaker/CraftTweaker#989]
Being able to access Block NBT from IBlock or IBlockState. I thought it would have been under IBlock.Data however that returned NULL but i know there is Block NBT as /ct NBT returns NBT for the block.

This would be useful for identifying blocks with specific NBTs. for example waystone has NBT isMossy:1 which you could make breaking that one also drop moss and make isMossy:0 not drop moss. would also be useful for vanilla stuff like chests which use NBT data for storage.

does not require another mod to be useful however would be more useful with other mods.

**Comment by friendlyhj** [comment]
https://gist.github.com/friendlyhj/09f765a1bca07c9f54af656af49961de

You can use the script.

**Comment by friendlyhj** [comment]
can be closed, just to use `world.getBlock(pos).data`
