### ISSUE TITLE
Error with creating my craft 

### ISSUE THREAD

**Issue by ghost** [CraftTweaker/CraftTweaker#990]
CraftTweaker log:
[PREINITIALIZATION][CLIENT][INFO] Current loaders after merging: [[preinit]]
[PREINITIALIZATION][CLIENT][INFO] Loading scripts for loader with names [preinit]
[PREINITIALIZATION][CLIENT][INFO] [preinit | SIDE_CLIENT]: Skipping file {[0:crafttweaker]: 1.zs} as we are currently loading with a different loader
[PREINITIALIZATION][CLIENT][INFO] Completed script loading in: 2ms
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Building registry
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Successfully built item registry
[INITIALIZATION][CLIENT][INFO] Current loaders after merging: [[preinit], [recipeevent | crafttweaker]]
[INITIALIZATION][CLIENT][INFO] Loading scripts for loader with names [crafttweaker | recipeevent]
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: 1.zs}
[INITIALIZATION][CLIENT][ERROR] 1.zs:6: Could not resolve << advanced_solar_panels : crafting : 5>
[INITIALIZATION][CLIENT][ERROR] [crafttweaker | SIDE_CLIENT]: Error parsing 1.zs:6 -- Invalid expression, last token: ,
[INITIALIZATION][CLIENT][INFO] Completed script loading in: 289ms
[POSTINITIALIZATION][CLIENT][INFO] Removing recipes for various outputs
[POSTINITIALIZATION][CLIENT][INFO] Applying MrCrayfish's Furniture Mod changes...
[AVAILABLE][CLIENT][INFO] Fixed the RecipeBook

My code: 
recipes.remove( < appliedenergistics2:certus_quartz_wrench > );
recipes.remove( < appliedenergistics2:nether_quartz_wrench > );

recipes.addShaped( < appliedenergistics2:certus_quartz_wrench > ,
 [[<<advanced_solar_panels:crafting:5>>, null, <<advanced_solar_panels:crafting:5>>],
  [null, <<mekanism:atomicalloy>>, null],
  [null, <<mekanism:atomicalloy>>, null]]);

**Comment by MasterAlex3** [comment]
> [PREINITIALIZATION][CLIENT][INFO] Current loaders after merging: [[preinit]]
> [PREINITIALIZATION][CLIENT][INFO] Loading scripts for loader with names [preinit]
> [PREINITIALIZATION][CLIENT][INFO] [preinit | SIDE_CLIENT]: Skipping file {[0:crafttweaker]: 1.zs} as we are currently loading with a different loader
> [PREINITIALIZATION][CLIENT][INFO] Completed script loading in: 2ms
> [INITIALIZATION][CLIENT][INFO] CraftTweaker: Building registry
> [INITIALIZATION][CLIENT][INFO] CraftTweaker: Successfully built item registry
> [INITIALIZATION][CLIENT][INFO] Current loaders after merging: [[preinit], [recipeevent | crafttweaker]]
> [INITIALIZATION][CLIENT][INFO] Loading scripts for loader with names [crafttweaker | recipeevent]
> [INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: 1.zs}
> [INITIALIZATION][CLIENT][ERROR] 1.zs:6: Could not resolve << advanced_solar_panels : crafting : 5>
> [INITIALIZATION][CLIENT][ERROR] [crafttweaker | SIDE_CLIENT]: Error parsing 1.zs:6 -- Invalid expression, last token: ,
> [INITIALIZATION][CLIENT][INFO] Completed script loading in: 289ms
> [POSTINITIALIZATION][CLIENT][INFO] Removing recipes for various outputs
> [POSTINITIALIZATION][CLIENT][INFO] Applying MrCrayfish's Furniture Mod changes...
> [AVAILABLE][CLIENT][INFO] Fixed the RecipeBook
> 
> Code: 
recipes.remove(<appliedenergistics2:certus_quartz_wrench>);
recipes.remove(<appliedenergistics2:nether_quartz_wrench>);

recipes.addShaped(<appliedenergistics2:certus_quartz_wrench>,
 [[<<advanced_solar_panels:crafting:5>>, null, <<advanced_solar_panels:crafting:5>>],
  [null, <<mekanism:atomicalloy>>, null],
  [null, <<mekanism:atomicalloy>>, null]]);
