### ISSUE TITLE
[1.12.2]IFoodStats.saturationLevel can't be given value

### ISSUE THREAD

**Issue by dong031001** [CraftTweaker/CraftTweaker#992]
## Issue Description
Internal Server Exception after setting a value for an IFoodStats

#### What you expected to happen:
Normally set a saturation level for a player

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

[https://github.com/ET-Team/EnigTech2/blob/master/EnigTech2/minecraft/scripts/contenttweaker/item/AdvancedFruit.zs#L33](url)

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

[crafttweaker.log](https://github.com/CraftTweaker/CraftTweaker/files/4759396/crafttweaker.log) (Too big for pastebin)
note: No [ERROR] present.
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.2
- Forge:2854
- Crafttweaker: CraftTweaker2-1.12-4.1.20.574
- Using a server: yes
- If yes, does the client have the exact same scripts? yes

#### Your most recent log file where the issue was present: 

https://paste.ubuntu.com/p/64MfHpdZFf/
Line 4433

**Comment by democat3457** [comment]
can be closed
