### ISSUE TITLE
Recipe name [0] has duplicate uses, defaulting to calculated hash!

### ISSUE THREAD

**Issue by kill05** [CraftTweaker/CraftTweaker#996]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the crafttweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Everytime I load a world my chat gets spammed with a warning
This is nothing that important but I wanted to ask why this happens

#### What happens:

My chat gets spammed with "Recipe name [0] has duplicate uses, defaulting to calculated hash!"

#### What you expected to happen:

My chat not getting spammed each time I load my worlds

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/3Yj7KBTV

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/tdbE55dQ
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Crafttweaker: 4.1.20.574
- Using a server: no
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

https://pastebin.com/jSj9z7XS

**Comment by kindlich** [comment]
Why are you even using `0` as recipe name?

Line 80:
```zenscript
recipes.addShaped(0, <galacticraftcore:machine>,
  [/*...*/]);
```

That first parameter is the recipe name, and should be unique, so you are getting errors because you use the same name in the following recipes as well.

**Comment by kill05** [comment]
Oooh that's why. It was not me, I use an item from Extended Crafting called recipe maker that automatically generates a recipe in your clipboard and I've never noticed it. Thanks!
