### ISSUE TITLE
Cannot use periods in file script name in 1.14+

### ISSUE THREAD

**Issue by justinrusso** [CraftTweaker/CraftTweaker#999]
#### Issue Description:
In 1.12, file names supported periods such as `test.2.zs` but in 1.14+ it causes an error. I believe in 1.12 the file names were sanitized and periods were converted to underscores.

#### What happens:
The script appears to be run, but nothing the script should have done exists in-game. There is no error in the `crafttweaker.log` file however, an error does exist in the Minecraft log file.
```
java.util.concurrent.ExecutionException: java.lang.ClassFormatError: Illegal class name "scripts/test.2" in class file Scripts
```
[Full error](https://pastebin.com/caeXt04X)

#### crafttweaker.log file:
```
[14:40:06.357][COMMON_SETUP][CLIENT][INFO] Started loading Scripts for Loader 'setupCommon'!
[14:40:07.199][COMMON_SETUP][CLIENT][INFO] Finished loading Scripts!
[14:40:32.344][DONE][SERVER][INFO] Started loading Scripts for Loader 'crafttweaker'!
[14:40:32.395][DONE][SERVER][INFO] Loading test.2.zs
```

____
#### Affected Versions:

- Minecraft: 1.15.2
- Forge: 31.2.0
- Crafttweaker: 1.15.2-6.0.0.29
- Using a server: No

**Comment by kindlich** [comment]
Hey there, 

I think that this issue was already fixed.
If not, please reply and I will reopen this issue
